### ISSUE TITLE
Disable Android updates pop up.

### ISSUE THREAD

**Issue by 15mgm15** [MicrosoftDocs/appcenter-docs#100]
I am having a hard time trying to find if there is a way to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d269a0-0b09-c2f6-d37a-319831bcf782
* Version Independent ID: f2c17a3a-87bb-0c75-9efb-de6ffb6f7738
* Content: [App Center Distribute for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin)
* Content Source: [docs/sdk/distribute/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @TroubleMakerBen
* Microsoft Alias: **bereimol**

**Comment by jwargo** [comment]
@15mgm15 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

If you have a question about how to do something, ask our support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by softlion** [comment]
You can remove the default update dialog by implementing the ReleaseAvailable callback and calling Distribute.NotifyUpdateAction(UpdateAction.Postpone);
