### ISSUE TITLE
self hosted Bitbucket repository 

### ISSUE THREAD

**Issue by yassineKharraz** [MicrosoftDocs/appcenter-docs#1000]
I've seen that Gitlab is supported for self-hosted instance , is self-hosted Bitbucket not supported ?

**Comment by King-of-Spades** [comment]
Unfortunately it's unsupported: https://docs.microsoft.com/en-us/appcenter/build/connect

You can file or upvote 👍 a feature request for it here: https://github.com/Microsoft/appcenter/issues

I recommend including any specific details about the request you have in mind, if applicable.
