### ISSUE TITLE
Build with SQLite VSIX package for Universal Windows Platform

### ISSUE THREAD

**Issue by jjindrich** [MicrosoftDocs/appcenter-docs#1005]
Hello, I need to build UWP application which requires installation of VSIX package for Universal Windows Platform https://sqlite.org/2020/sqlite-uwp-3310100.vsix. This package is required by Azure Mobile Services Offline data support. Is there any way how to install it during build ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be2ace35-a6ef-349a-e009-ca55e3778602
* Version Independent ID: 85a92e95-828a-54f8-b7e7-4f86b8e76abc
* Content: [Configure a C# UWP app in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/windows/uwp/first-build#feedback)
* Content Source: [docs/build/windows/uwp/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/windows/uwp/first-build.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by King-of-Spades** [comment]
Currently, we don't have direct support for installing custom tooling, and I'm not seeing that in the build image: https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md

You could try installing it via a build script: https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/

You could also request feature support be added for it, or for some other approach for your scenario: https://github.com/Microsoft/appcenter/issues.

**Comment by jjindrich** [comment]
@King-of-Spades Build script seems ok, but can I install vsix ? Is there Visual Studio on build machine ? I think it's required.

**Comment by King-of-Spades** [comment]
Yes, all the details for the windows machines are on the link I shared: https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md

**Comment by jjindrich** [comment]
@King-of-Spades thanks link provided.
I created appcenter-post-clone.ps1 and tested locally. VSIX file is located in same location. Locally it installs VS extension correctly.
File content:
Write-Host "VSIX started"
& 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VSIXInstaller.exe' /quiet sqlite-uwp-3310100.vsix
Write-Host "VSIX completed"

But still build failed with this error: ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2348,5): Error MSB3774: Could not find SDK "SQLite.UWP.2015, Version=3.31.1".

Any idea how to troubleshoot that extension is installed correctly ?

**Comment by King-of-Spades** [comment]
The problem might be the paths you're supplying. We have some pre-defined path variables here, but I don't know if they're sufficient: https://docs.microsoft.com/en-us/appcenter/build/custom/variables/

**Comment by jjindrich** [comment]
@King-of-Spades thanks, now works, VSIX is installed correctly.
Please can you help me with signing ? I uploaded my PFX file into Build definition but I don't know how to access it during build - not described https://docs.microsoft.com/en-us/appcenter/build/windows/uwp/first-build#35-simulator-build.
I need to use my own Windows Store certificate to sign package.

**Comment by King-of-Spades** [comment]
@jjindrich Two things to check:
1. Check if the build works without signing. 
2. This documentation covers troubleshooting options on your side: https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/build-failed#if-building-works-locally-but-not-in-app-center

If that still doesn't work and you have further questions, I recommend reaching out to the App Center Support team; I'm going on vacation soon so I won't be available.
