### ISSUE TITLE
App Center Errors for iOS

### ISSUE THREAD

**Issue by diogot** [MicrosoftDocs/appcenter-docs#1008]
Why there isn't support for App Center Errors in iOS? Many supported platforms run on iOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d3221f1-fd33-0f5b-5566-8af37bbe2244
* Version Independent ID: 6efcb61b-28bf-09bc-886d-c7a7188b91dc
* Content: [App Center Diagnostics - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/#feedback)
* Content Source: [docs/diagnostics/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-diagnostics**
* GitHub Login: @winnie
* Microsoft Alias: **yuli1**

**Comment by winnie** [comment]
Hey @diogot - thanks for the feedback. We haven't had bandwidth to prioritize this feature yet. 

I'm going to close this issue but please give the feature request in the App Center repo an upvote: https://github.com/microsoft/appcenter/issues/192. Thanks!
