### ISSUE TITLE
Any way to use from iOS background code?

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/appcenter-docs#101]
I have a Xamarin iOS project that is used with background notifications. I can't get any analytics data, where exactly should I add the initialization call to get some? I tried in the overridden DidReceiveRemoteNotification in AppDelegate.cs but nothing happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72f6fe-74d6-696e-e709-5f6d577c0a58
* Version Independent ID: b3d0ea8b-5a1f-bf71-7dc2-9685cf23c00b
* Content: [Get Started with Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/Xamarin)
* Content Source: [docs/sdk/getting-started/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@amp64 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
