### ISSUE TITLE
No "More" Menu

### ISSUE THREAD

**Issue by sebhb** [MicrosoftDocs/appcenter-docs#1017]
There is no "More" Menu under "Settings" to transfer the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7031e14-f8ab-1d70-6910-72565048b2c1
* Version Independent ID: 23e13d47-a99e-452a-4891-af3147995842
* Content: [Creating and managing apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/creating-and-managing-apps#feedback)
* Content Source: [docs/dashboard/creating-and-managing-apps.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/creating-and-managing-apps.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by King-of-Spades** [comment]
The menu requires the "Manager" permission. I can see it on my side, if you have the manager permission enabled for the app currently and it's still not showing up, you should contact support:

**appcenter.ms > ? > contact support**
