### ISSUE TITLE
Mandatory attribute does not work as expected

### ISSUE THREAD

**Issue by cuongtvc** [MicrosoftDocs/appcenter-docs#102]
I had a mandatory release and it was disabled, but when I applied a patch to enable it, it becomes enabled and optional, that means mandatory attribute had been change to false. My command: appcenter codepush patch -a my_account/my_app Production -l v10 -x false
Appcenter Version 1.0.14.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c2bd47-97e3-abc8-fbdd-305f0c631827
* Version Independent ID: 318718e7-a38a-7cc5-01a4-7ce0153c4398
* Content: [Use the App Center CLI to release CodePush updates - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#feedback)
* Content Source: [docs/distribution/codepush/cli.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/cli.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@cuongtvc The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

It feels like you're trying to ask a support question. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
