### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by epuidokas** [MicrosoftDocs/appcenter-docs#1020]
`GDPR section of the Service Trust portal` link leads to a blank page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd84a4ba-2763-349d-ca45-1adec494d357
* Version Independent ID: 61f5bc4a-6aea-7af2-76aa-9b45d24aba19
* Content: [General Data Protection Regulation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/gdpr/)
* Content Source: [docs/gdpr/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @iageoghe
* Microsoft Alias: **iageoghe**

**Comment by King-of-Spades** [comment]
It currently appears to be working: https://servicetrust.microsoft.com/ViewPage/GDPRGetStarted
