### ISSUE TITLE
upload-symbols command incomplete

### ISSUE THREAD

**Issue by guidedways** [MicrosoftDocs/appcenter-docs#1021]
Please provide a more exhaustive example of the upload command. It's not clear how to specify the target app / company / organization / platform etc. "appcenter crashes help" doesn't work either, so there's no way to learn about the additional parameters the command expects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94f7999c-0c3c-ee5d-c8a9-29ee9aa0d622
* Version Independent ID: 1c9f21ed-86de-8e79-d007-e80945edf360
* Content: [iOS Symbolication - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#feedback)
* Content Source: [docs/diagnostics/iOS-symbolication.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/iOS-symbolication.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-diagnostics**
* GitHub Login: @winnie
* Microsoft Alias: **yuli1**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
