### ISSUE TITLE
Glovo app estafeta

### ISSUE THREAD

**Issue by Claytonglovo** [MicrosoftDocs/appcenter-docs#1026]
Olá bom dia, não consigo abrir a aplicação golvo para estafeta em meu Android gostaria de receber auxilio

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3659cbf-c706-9af5-b3ed-9e0cdb5f2819
* Version Independent ID: 97d69564-1130-e541-9362-c9272983784d
* Content: [Install a Build from App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/installation)
* Content Source: [docs/distribution/installation.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/installation.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by King-of-Spades** [comment]
Hi, 

Using google translate, it sounds like you requested support here. 

If you're still encountering this issue, you can try reaching out to our support team at **appcenter.ms > ? > Contact Support**

Unfortunately our support is only provided in English.
