### ISSUE TITLE
Problemas com a aplicação Glovo 

### ISSUE THREAD

**Issue by Claytonglovo** [MicrosoftDocs/appcenter-docs#1027]
Este é o link da aplicação Glovo 

https://slack-redir.net/link?url=https%3A%2F%2Finstall.appcenter.ms%2Forgs%2Fglovoapp%2Fapps%2Fglover-1%2Fdistribution_groups%2Fpublic

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
