### ISSUE TITLE
Export 2 Items; not found.

### ISSUE THREAD

**Issue by petrogad** [MicrosoftDocs/appcenter-docs#1030]
After installing the certificate, I don't see the export 2 items as noted in #6 of the "Getting a certificate from apple - .p12" section.

Is there a step I'm missing? I see both the Distribution and Development certificate in my keychain access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01f1809-2316-7d47-1547-23775f6dd618
* Version Independent ID: 7d719380-4d1d-e995-e0e5-b2474ae5e9af
* Content: [iOS Code Signing in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/code-signing#feedback)
* Content Source: [docs/build/ios/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/code-signing.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by petrogad** [comment]
Fixed; I had my "System" selected under keychain, not "Login".

Apologies!

**Comment by King-of-Spades** [comment]
Thanks for letting us know, I should be able to highlight the "login" part a little more to hopefully prevent future confusion.
