### ISSUE TITLE
Only Swift instructions included - no Objective C

### ISSUE THREAD

**Issue by crystalneth** [MicrosoftDocs/appcenter-docs#1036]
This page only has Swift language instructions and is missing Objective C versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45228922-4a96-8c08-7d27-69ef98d44943
* Version Independent ID: d04ef359-7b17-8a14-970b-5c48820976cd
* Content: [Get Started with iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios)
* Content Source: [docs/sdk/getting-started/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/ios.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by MatkovIvan** [comment]
Hi @crystalneth,

Sorry for delayed reply.
At the top of the page there is a drop-down list for choosing a language.

See https://github.com/MicrosoftDocs/appcenter-docs/issues/858#issuecomment-566868792
