### ISSUE TITLE
In-app updates doesn't work properly

### ISSUE THREAD

**Issue by jiewei93** [MicrosoftDocs/appcenter-docs#1038]
Hi,i'm working android 7.0,I've follow steps by steps in the documentation but still in-app updates doesn't prompt update dialog even i've installed from the public distribution installation link.

Appreciates any helps in advanced.

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
