### ISSUE TITLE
App Crashes while trying to integrate CodePush in android React Native app

### ISSUE THREAD

**Issue by MianMUAmer** [MicrosoftDocs/appcenter-docs#1039]
Hi
So I want in-app update, but just learnt that it is not supported with React Native. I wanted to try code push as an alternative. I am following its docs and my app crashes because of these lines in MainApplication.java

@Override
    protected String getJSBundleFile(){
      return CodePush.getJSBundleFile();
}

I dont know why. I am following this for React < 0.60

![image](https://user-images.githubusercontent.com/34229327/82473418-328afa80-9ad2-11ea-97be-eed3d6da5fcc.png)

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
