### ISSUE TITLE
Oh no, we couldn’t configure your branch!

### ISSUE THREAD

**Issue by ygliboch** [MicrosoftDocs/appcenter-docs#1041]
<img width="690" alt="Screenshot 2020-05-21 at 18 11 14" src="https://user-images.githubusercontent.com/45264639/82577664-f7510000-9b93-11ea-9263-0a9f4fb3c745.png">
Hi

I can't configure my build, because provision profile does not include the provided signing certificate. I can't understand why, I use a profile that generates from xcode. I also tried other options from the documentation and none worked
<img width="503" alt="Screenshot 2020-05-21 at 18 09 47" src="https://user-images.githubusercontent.com/45264639/82574290-89a2d500-9b8f-11ea-8d5b-7a5425333527.png">
<img width="690" alt="Screenshot 2020-05-21 at 18 11 14" src="https://user-images.githubusercontent.com/45264639/82577664-f7510000-9b93-11ea-9263-0a9f4fb3c745.png">

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by DonavanMartin** [comment]
Still an issue.

**Comment by ygliboch** [comment]
@AlgoSolu if it helps you, then my problem was far from the certificates. I just needed to fix all the errors in the appcentre logs that I hadn't noticed before

**Comment by King-of-Spades** [comment]
This isn't an issue that documentation can address, because the error message isn't diagnosable on it's own.

**Comment by 77TecShaeer** [comment]
+++

**Comment by King-of-Spades** [comment]
@77TecShaeer So, I'm no longer working on App Center and afaik, my old findings are still accurate that the error itself isn't diagnosable. 

That said, there is a general troubleshooting guide here that might help: https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/build-failed#if-building-works-locally-but-not-in-app-center

**Comment by AhteshamKhanCoder** [comment]
I had this issue because of the p12 certificate provided is not associated with the provisional profike
