### ISSUE TITLE
Store connection validity.

### ISSUE THREAD

**Issue by gdchapman** [MicrosoftDocs/appcenter-docs#1042]
Hi, do you have plans to extend the store connection validity period? 
As per documentation above "The connection is valid for 90 days for an application in App Center." The 90 day limit results in failed distributions and manual creation of Intune store connections.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c31b388-68fd-649d-eb12-37c94fa6793c
* Version Independent ID: a590f5fc-c426-ef66-a3c5-732928325347
* Content: [Publish applications to Intune Company Portal - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/intune)
* Content Source: [docs/distribution/stores/intune.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/intune.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by Oddj0b** [comment]
Hey,

We have an open feature request for handing Intune connections better, my best recommendation is to give it a vote here: https://github.com/microsoft/appcenter/issues/407

This repository is for fixing issues with our documentation, so I will be closing this issue.
