### ISSUE TITLE
How to connect --test-series with Espresso tests to run a specific suite of tests and not all tests.

### ISSUE THREAD

**Issue by emathew80** [MicrosoftDocs/appcenter-docs#1044]
Hello, 

I am wondering how we can specify a --test-series inside our native espresso code to run only specified tests.

Ex. 

I have 3 tests:

Login
Make Transaction
Cancel Order

Via gradle wrapper, I can run something like 

./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.app.testCases.login.Login

./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.app.testCases.transaction.MakeTransaction

./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.app.testCases.CancelOrder.Cancel

Each of these commands will only run that specific test. I want to be able to do this using appcenter. I assume the --test-series would be flag to do this, but I have no idea how to connect the --test-series that I specify on appcenter to what test it should run.

Is there some kind of annotation that must be used in the Espresso test code to connect back to the --test-series on appcenter?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
