### ISSUE TITLE
Fix links to customizable strings

### ISSUE THREAD

**Issue by softlion** [MicrosoftDocs/appcenter-docs#105]
For iOS:

https://github.com/Microsoft/AppCenter-SDK-Apple/blob/develop/AppCenterDistribute/AppCenterDistribute/Resources/fr.lproj/AppCenterDistribute.strings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d269a0-0b09-c2f6-d37a-319831bcf782
* Version Independent ID: f2c17a3a-87bb-0c75-9efb-de6ffb6f7738
* Content: [App Center Distribute for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin)
* Content Source: [docs/sdk/distribute/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @TroubleMakerBen
* Microsoft Alias: **bereimol**

**Comment by jwargo** [comment]
@softlion what are you asking us to do here? All you've done is link to a translation page and I don't know what that means.

**Comment by softlion** [comment]
I commented on the content [article](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin) so you can fix the links in this article. 
These links currently opens a 404 github page (The title of this ticket is "Fix links to customizable strings").

The bad links are in the chapter "customizable strings".

One of the correct link (for ios) is [link](https://github.com/Microsoft/AppCenter-SDK-Apple/blob/develop/AppCenterDistribute/AppCenterDistribute/Resources/fr.lproj/AppCenterDistribute.strings)

The other is for Android and i let you find it.
