### ISSUE TITLE
Missing Campaign Name Max Length and valid characters

### ISSUE THREAD

**Issue by ehuna** [MicrosoftDocs/appcenter-docs#1058]
What is a campaign name max length?
What are the valid characters accepted for a campaign name?

Same questions on title and message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aadf839d-04fb-8d6e-dd5d-57a79c1d0914
* Version Independent ID: ea1d2e77-e3dd-19c7-9abd-ecd8f156a00c
* Content: [Using the Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/rest-api)
* Content Source: [docs/push/rest-api.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/rest-api.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-push**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@ehuna We announced that we're retiring the service by the end of the year. The service is in preview mode anyway, so it should not be used for production apps.  As we're retiring the service, we do not expect to make any documentation changes going forward. 

The length limit is, I think, 100 characters, but I do not know for sure, I'll see if I can find out. Acceptable characters are the normal ones you'd expect - it's a string and can contain spaces, so use letters, spaces, dashes, etc. You can validate it in the App Center Portal.
