### ISSUE TITLE
Typo on Log Flow bullet #1

### ISSUE THREAD

**Issue by jabulenc** [MicrosoftDocs/appcenter-docs#106]
> Check if the SDK is properly integarted and if our backend is receiving data.

*integrated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b54905c-48c1-06be-2676-c1ca8a9463f2
* Version Independent ID: 56586cc1-d598-9f6b-8cda-a3359ed56e4f
* Content: [Understanding the App Center Log Flow Page - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/log-flow#feedback)
* Content Source: [docs/analytics/log-flow.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/log-flow.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by jwargo** [comment]
@jabulenc fixed, thanks,
