### ISSUE TITLE
OS in "App Center Test Devices" should list the OS not just the version

### ISSUE THREAD

**Issue by charlesroddie** [MicrosoftDocs/appcenter-docs#1060]
[Enter feedback here]

---
OS in "App Center Test Devices" should list the OS not just the version

E.g. "Android 4.2.2" instead of "4.2.2".

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c64c24-c463-0383-84ca-35465cd40f47
* Version Independent ID: 391d0c7a-f6e5-3269-c616-e83266050331
* Content: [Devices Available - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/devices)
* Content Source: [docs/test-cloud/devices.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/devices.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @Priskorn
* Microsoft Alias: **miprisk**

**Comment by Priskorn** [comment]
Hi @charlesroddie We added a (Android/iOS) selector to the "App Center Test Devices" page.
Thanks for reaching out. 

https://docs.microsoft.com/en-us/appcenter/test-cloud/devices/ios

cc: @Oddj0b
