### ISSUE TITLE
Dark Theme contrast is too high

### ISSUE THREAD

**Issue by joehanna** [MicrosoftDocs/appcenter-docs#1063]
When using the "Dark" Theme in docs, I find I get sore eyes and get "burn in" very quickly with the high contrast of the white text (#e3e3e3) on very dark background (#171717) - especially during long articles. I have to stop reading and come back to it - or switch back to the Light theme.  All of which defeats the purpose of having a dark theme which is meant to be easier on the eyes.

Can we get an additional dark theme that has a softer contrast, something more akin to stackoverflow.com's dark theme (#e7e8eb text on #2d2d2d background)? It is very easy to read and doesn't have the same high contrast issues.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f3af3f-ef07-8896-4b3c-05cef163b51a
* Version Independent ID: b4b1f6a4-5975-358b-1cf4-f7b10a2245cd
* Content: [Environment Variables - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/)
* Content Source: [docs/build/custom/variables/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/variables/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
Hi, 

Thanks for the feedback. Our team is responsible for the technical content relating to App Center, but the theme colors are inherited from the core Microsoft docs, so the request should be handled by them. 

For example here's a recent request that sounds very similar: https://github.com/MicrosoftDocs/feedback/issues/2850
