### ISSUE TITLE
Do updates delete the previous version?

### ISSUE THREAD

**Issue by sublime392** [MicrosoftDocs/appcenter-docs#1066]
Does the act of installing an update first delete the previous version? I am trying to figure out why my app settings (iOS) are not persisting across app updates, and I can't find anything in the docs about it here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3659cbf-c706-9af5-b3ed-9e0cdb5f2819
* Version Independent ID: 97d69564-1130-e541-9362-c9272983784d
* Content: [Install a Build from App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/installation)
* Content Source: [docs/distribution/installation.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/installation.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by King-of-Spades** [comment]
Normally for iOS & Android, installing an app that you've previously installed overwrites the app. 

However, depending on where & how that data is stored for the app, some data might be preserved. I believe in most cases the logic applied is based on how you're managing the app and you should be able to experiment & test with the scenario locally.

**Comment by DmitriyKirakosyan** [comment]
Hi @sublime392 ,

Normally iOS app user data is not removing on app update. If, for example, you store your settings in UserDefaults, then you should be able to access a previously stored data after you update the app using the App Center Distribution service.

If the issue still persists for you, please share more context about the method you use to store your app settings.
