### ISSUE TITLE
AppCenter support for Katalon Tests

### ISSUE THREAD

**Issue by jagmitsingh** [MicrosoftDocs/appcenter-docs#1068]
I have a requirement to execute Katalon Studio tests against an IOS Mobile App using the appCenter.  Katalon Studio is a automation framework build on top of Appium.  Does the AppCenter support Katalon Tests execution? I know it supports appium, will it support execution of Katalon tests?

**Comment by King-of-Spades** [comment]
App Center doesn't currently have any explicit support for Katalon. It's possible your tests could still work, if Katalon doesn't require any unsupported or conflicting dependencies, but the App Center Test team isn't currently QA'ing that support. 

Even if it does work, it could also break at a later date, and that would also not be supported. There has been some discussion of working with it in the Katalon community: https://forum.katalon.com/t/how-to-integrate-katalon-with-visual-studio-appcenter/20151/9

But that discussion is a bit old.
