### ISSUE TITLE
UWP when?

### ISSUE THREAD

**Issue by RobbyRobbyRobby** [MicrosoftDocs/appcenter-docs#107]
I see you have iOS, Android and Xamarin working with In-App updates, when is UWP getting this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc4748f-3820-3b4d-b6d5-f0566063ce30
* Version Independent ID: 103d8b55-8719-dcaa-0670-d22e46e328cb
* Content: [Enable In-app Updates - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/inappupdates)
* Content Source: [docs/distribution/inappupdates.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/inappupdates.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by jwargo** [comment]
@RobbyRobbyRobby The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

If you want to ask a question about feature availability, contact our support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
