### ISSUE TITLE
Method `Crashes.trackException` not found in `com.microsoft.appcenter:appcenter-crashes:3.2.2`

### ISSUE THREAD

**Issue by chimbori** [MicrosoftDocs/appcenter-docs#1074]
Perhaps I’m missing something, but the `Crashes.trackException()` method as documented here is nowhere to be found. Its counterpart `.trackError()` is present, but they serve different purposes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216ee8d4-5303-a857-ceca-47a4c5a79ea9
* Version Independent ID: 2f6a68b7-5120-ab3a-b94a-0d8e929881d9
* Content: [App Center Crashes for Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#handled-errors)
* Content Source: [docs/sdk/crashes/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/android.md)
* Service: **vs-appcenter-sdk**
* GitHub Login: @winnie
* Microsoft Alias: **yuli1**

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for mention it! We updated docs about it.
I’m closing this issue, but feel free to reopen this issue if it isn’t resolved or you have additional questions.
