### ISSUE TITLE
Is "Crashes.HasReceivedMemoryWarningInLastSessionAsync()" relevant without an app crash in the last session? 

### ISSUE THREAD

**Issue by kgouraw** [MicrosoftDocs/appcenter-docs#1075]
Hi,

I'm using below code snippet, OnStart() of Xamarin Form App.cs, 

bool hadMemoryWarning = await Crashes.HasReceivedMemoryWarningInLastSessionAsync();
if (hadMemoryWarning)
{
      Analytics.TrackEvent("Last_Session_Memory_Warning", new Dictionary<string, string>() { { "Had Memory Warning", hadMemoryWarning.ToString() } });
}

My app is running very smoothly without any issues but I get "hadMemoryWarning" as a "True" a few times with the same iOS device in the AppCenter Analytics as I'm writing it as a warning event.  

Is it relevant to call "Crashes.HasReceivedMemoryWarningInLastSessionAsync()" without calling  "await Crashes.HasCrashedInLastSessionAsync()" ?
If Yes, then Crashes.HasReceivedMemoryWarningInLastSessionAsync() API should provide more information about memory leaks.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a98dc868-6ec0-4d6e-652a-ed90d6c092b4
* Version Independent ID: d6061a26-6aef-be3a-c89a-3c8b290e2c9a
* Content: [App Center Crashes for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin)
* Content Source: [docs/sdk/crashes/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/xamarin.md)
* Service: **vs-appcenter-sdk**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by kgouraw** [comment]
Hey Kent,
This issue is not related to technical support. Please try to understand. I'm asking, does "Crashes.HasReceivedMemoryWarningInLastSessionAsync()" have any standalone meaning? Means should we call Crashes.HasReceivedMemoryWarningInLastSessionAsync() without Crashes.HasCrashedInLastSessionAsync() = true?


> Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team.
> 
> If you need technical help, you can contact support by:
> 
> 1. Going to https://appcenter.ms/apps
> 2. Selecting **? > Contact Support** (in the upper right corner).
>    Reference this issue for context if needed.
> 
> If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by King-of-Spades** [comment]
Thanks for the clarification. I can reopen this as a documentation request and ask our product group if they have an answer, but I don't have an ETA on when they will respond. I help directly with publishing info to docs, but can only publish the info I receive.

**Comment by AnastasiaKubova** [comment]
The `Crashes.HasReceivedMemoryWarningInLastSessionAsync` is true when the app received a low memory warning in the last session. This call is memorization of [this system event](https://developer.apple.com/documentation/xcode/improving_your_app_s_performance/reducing_your_app_s_memory_use/responding_to_low-memory_warnings). Our SDK doesn't collect memory leaks information.
The `Crashes.HasCrashedInLastSessionAsync()` is true if the app has crashed in the last session. 
These are two independent methods.

**Comment by russelarms** [comment]
I'm closing the issue since the initial question is answered. @kgouraw Please, feel free to reply in case you have any more questions.
