### ISSUE TITLE
Documentation for attachments does not match implementation

### ISSUE THREAD

**Issue by avargaskun** [MicrosoftDocs/appcenter-docs#1082]
The documentation for adding attachments to a crash reports shows the following example:

```javascript
var errorCallback = function(error) {
    console.error(error);
};

var processFunction = function(attachments, sendCallback) {
    attachments.addTextAttachment('Hello text attachment!', 'hello.txt');
    var imageAsBase64string = '...';
    attachments.addBinaryAttachment(imageAsBase64string, 'logo.png', 'image/png');
    sendCallback(true); //crash will be sent
};

AppCenter.Crashes.process(processFunction, errorCallback);
```

However, based on the [code for the latest version of the plugin](https://github.com/microsoft/appcenter-sdk-cordova/blob/5411abfb27fd8ef0ab7ad0968cc5223e7a928229/cordova-plugin-appcenter-crashes/www/Crashes.js#L54) (0.5.1) the `attachments` argument to the `processFunction` method is an array of reports, and each element of the array defines the functions `addTextAttachmnent` and `addBinaryAttachment`. If implemented as the example in the documentation states, the code throws an exception due to those functions not being implemented as part of the array of reports itself. 

Given the current implementation of the plugin, a more accurate example would be:

```javascript
var errorCallback = function(error) {
    console.error(error);
};

var processFunction = function(attachments, sendCallback) {
    attachments.forEach(function(attachment) {
        attachment.addTextAttachment('Hello text attachment!', 'hello.txt');
        var imageAsBase64string = '...';
        attachment.addBinaryAttachment(imageAsBase64string, 'logo.png', 'image/png');
    }
    sendCallback(true); //crash will be sent
};

AppCenter.Crashes.process(processFunction, errorCallback);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b26e51-6e0f-2efb-d0e1-f420013dd8ca
* Version Independent ID: 182aadb8-f93f-be6c-90f5-aad413d49fa6
* Content: [App Center Crashes for Apache Cordova - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/cordova)
* Content Source: [docs/sdk/crashes/cordova.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/cordova.md)
* Service: **vs-appcenter-sdk**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by russelarms** [comment]
Hi, @avargaskun! Sorry for the delay.
I have checked the issue and am updating the docs.
