### ISSUE TITLE
Internet Capability required

### ISSUE THREAD

**Issue by JogyBlack** [MicrosoftDocs/appcenter-docs#1085]
One important point to mention is that in order for the App Center analytics to work, is that the app need to declare the Internet (Client) capability on the package manifest. It may sound obvious, but is something that should be added to the troubleshooting section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2add0f-2806-8bfa-92d5-cc3fdd1e1055
* Version Independent ID: c572b535-a780-fba3-0845-f5127d98d7d6
* Content: [UWP, WPF, and WinForms SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/uwp#feedback)
* Content Source: [docs/sdk/troubleshooting/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/uwp.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by AnastasiaKubova** [comment]
Hi, thanks for getting in touch with us! We already updated docs about it. Please see [here](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/android#what-android-permissions-are-required).
I’m closing this issue, but feel free to reopen this issue if it isn’t resolved or you have additional questions.
