### ISSUE TITLE
documentation of build settings

### ISSUE THREAD

**Issue by schriftgestalt** [MicrosoftDocs/appcenter-docs#1086]
> If you're integrating the SDK binaries manually, make sure your modules are enabled for your project.

This is mentioned on the troubleshooting page (https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/macos) but why not on the getting started page (https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/macos). This could have saved me a couple hours.

**Comment by joujouuc** [comment]
Thanks. Please keep sending. Appreciate it

Den mån 20 juli 2020 23:26Georg Seifert <notifications@github.com> skrev:

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! This already mentions in the fifth part of this [topic](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/macos#34-integration-by-copying-the-binaries-into-your-project).
I’m closing this issue but feel free to reopen this issue if it isn’t resolved or you have additional questions.

**Comment by schriftgestalt** [comment]
The page you are linking to doesn’t mention this at all and it has only 4 parts?

**Comment by AnastasiaKubova** [comment]
The fifth part `Add the SDK frameworks to the project in Xcode` contains the next phrase:
> A dialog will appear, make sure your app target is checked. Then click Finish.

This means adding the App Center SDK to the project.
