### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by franny11** [MicrosoftDocs/appcenter-docs#109]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc863ba-5295-2db8-b37f-584e662e725a
* Version Independent ID: db2a1468-e4fa-6c55-985f-616de1e6484f
* Content: [App Center Pricing Information - Visual Studio App Center](https://docs.microsoft.com/en-ca/appcenter/general/pricing#faq)
* Content Source: [docs/general/pricing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/pricing.md)
* Service: **vs-appcenter**
* GitHub Login: @joemellin
* Microsoft Alias: **joemel**

**Comment by jwargo** [comment]
@franny11 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
