### ISSUE TITLE
Publish Separate build architecture apks through app center

### ISSUE THREAD

**Issue by SAShah-Fintech** [MicrosoftDocs/appcenter-docs#1096]
I am trying to publish react-native app on Google Play Store through app center.
While building my app I have set def enableProguardInReleaseBuilds = true in android\app\build.gradle file.
So, I have four apks 1) app-arm64-v8a-release.apk 2) app-armeabi-v7a-release.apk 3) app-x86_64-release.apk 4) app-x86-release.apk
When I create new release and trying to upload the app it only allows me to upload 1 apk file or bundle.
![image](https://user-images.githubusercontent.com/40629254/88635917-e4980180-d0d5-11ea-99ec-a01e29d7f765.png)

My requirement is to upload all 4 apks at a time through app center.
Can you please help me out to do so or do I have any other option??
**Let me know if it is possible through app center SDK, because my ultimate goal is to automate uploading apks through SDK.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868e3edf-f3af-950e-4f8a-ea30c392e883
* Version Independent ID: a725a1f2-fe7b-b7be-8e5e-6db22c2a756d
* Content: [Publish to Google Play Store - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay)
* Content Source: [docs/distribution/stores/googleplay.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/googleplay.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
