### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by brimmy11** [MicrosoftDocs/appcenter-docs#110]
The line that says "In case of a failure while publishing, the status will change to failed with an appropriate error message" should be amended to say "In case of a failure while publishing, the status will change to failed with an completely useless error message". Seriously though, the error message just tells me that there is an error and to contact support with a correlation id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c31b388-68fd-649d-eb12-37c94fa6793c
* Version Independent ID: a590f5fc-c426-ef66-a3c5-732928325347
* Content: [Publish applications to Intune Company Portal - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/intune)
* Content Source: [docs/distribution/stores/intune.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/intune.md)
* Service: **vs-appcenter**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by jwargo** [comment]
@brimmy11 thank you for the feedback; I've asked @gaknoll to review your comment.

**Comment by brimmy11** [comment]
Hi @jwargo @gaknoll , I didn't really expect to be taken seriously but since I have an audience let's address it. Below is an error we (my scrum team) are receiving when attempting to publish an application from App Center to Intune.

One of my colleagues is already in contact with App Center support to understand the details of the error so I do not require support with that. My comment was around the documentation not being accurate.

![error](https://user-images.githubusercontent.com/26055630/39500961-bcc922da-4dea-11e8-919c-77c4f1e4d6a8.png)

**Comment by jwargo** [comment]
@brimmy11 we're committed to making App Center the best tool it can be, so your feedback is greatly appreciated. I agree that the error message doesn't tell you a lot, so we can definitely make things better (assuming that we have additional information about the error that we can share). It could be that we don't know much beyond what we've told you, but I'm going to have to let @gaknoll  answer that one. Please keep the feedback coming.

**Comment by gaknoll** [comment]
@brimmy11 sorry for the delay in getting back to you. We greatly appreciate the feedback and I'll be working with our Stores integration team to improve the Intune documentation to be more accurate and useful. I hope our support team was able to help you resolve the error though!
