### ISSUE TITLE
upload Firebase Crashlytics symbol issue through App Center build

### ISSUE THREAD

**Issue by chetandobariya** [MicrosoftDocs/appcenter-docs#1101]
my app is using firebase crashyltics for crash reporting. 

currently, I am using App Center to distribute build for testing and App Store version.

I am struggling to upload symbol to the Firebase Crashlytics. every build shows missing dysm file in firebase console.

Do App Center has any script that I can run in post.sh build script that automatically get symbols.zip file and upload to the firebase console??

Looking forward to the solution!

**Comment by King-of-Spades** [comment]
These resources might help, if you know how to accomplish the same task locally but are struggling to do it in App Center. 

Our Build Script guide: https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/
Our Environment Variables doc: https://docs.microsoft.com/en-us/appcenter/build/custom/variables/

This repository has sample build scripts, but I don't see anything specific to Firebase: https://github.com/Microsoft/appcenter

**Comment by chetandobariya** [comment]
This issue is not solved yet.. please reopen it and help us to find the script to upload symbols to firebase crashlytics when we make build from app center..

Your mention docs link doesn't help

**Comment by King-of-Spades** [comment]
Unfortunately it's out-of-scope for our support & documentation. Build scripts allow you to add custom behavior to your build, but customizing that behavior is up to you. If you can get the task working locally using a script, the docs I cited may help you convert that local script to operate in App Center.
