### ISSUE TITLE
Stub library unavailable

### ISSUE THREAD

**Issue by GMozz** [MicrosoftDocs/appcenter-docs#1102]
I would like to use the stub library because we also distribute our app on the Play Store, but the dependency "com.microsoft.appcenter:appcenter-distribute-play" doesn't seem to exist (anymore).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40294974-bc6b-45af-f1bd-3bd8187153ac
* Version Independent ID: 21420d35-1e72-a8b8-d587-40b2913120ba
* Content: [App Center Distribute for Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#remove-in-app-updates-for-google-play-builds)
* Content Source: [docs/sdk/distribute/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/android.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-distribute**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by GMozz** [comment]
Apparently you must add the following maven repository, but it's not documented anywhere:
`maven {
    url "https://dl.bintray.com/vsappcenter/appcenter/"
}`

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! I checked this behavior on an empty app with the [latest version](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.1.0) of App Center follow [this guideline](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android) and all works well for me. Could you please clarify what version of App Center do you use? Is it happens on an empty app?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
This was a known [issue](https://github.com/microsoft/appcenter-sdk-android/issues/1453) and already fixed. Now the `appcenter-distribute-play` module can be used without this workaround.
I’m closing this issue but feel free to reopen this issue if it isn’t resolved or you have additional questions.
