### ISSUE TITLE
driver.label throws java.lang.RuntimeException

### ISSUE THREAD

**Issue by agulia1** [MicrosoftDocs/appcenter-docs#1108]
Following error is thrown on the line:
driver.label("Stopping App");

similar error is there is seen on using :
File srcFile = ((TakesScreenshot)(driver)).getScreenshotAs(OutputType.FILE);

Error:

java.lang.RuntimeException: Unable to get test information. Make sure the test class includes a @Rule:
  @Rule
  public TestWatcher watcher = Factory.createWatcher();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36da5026-39aa-9a48-440c-7e57da3e3373
* Version Independent ID: eff2f79f-df52-829f-a0c3-71396e365884
* Content: [Help and Feedback - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/help#accessing-app-center-free-support)
* Content Source: [docs/help.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/help.md)
* Service: **vs-appcenter**
* GitHub Login: @wisdeom

**Comment by agulia1** [comment]
we are using cucumber with junit as framework. Cucumber accepts only @before and @after annotations, so i think the @Rule and @Test are ignored

**Comment by DmitriyKirakosyan** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
