### ISSUE TITLE
when i use silent update

### ISSUE THREAD

**Issue by lybrooks** [MicrosoftDocs/appcenter-docs#1109]
reactnative 0.61.5

java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: index=1 count=0 at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:344) at com.facebook.react.bridge.ReactContext$ExceptionHandlerWrapper.handleException(ReactContext.java:351) at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:179) at android.app.ActivityThread.main(ActivityThread.java:5769) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674) Caused by: java.lang.IndexOutOfBoundsException: index=1 count=0 at android.view.ViewGroup.addInArray(ViewGroup.java:4449) at android.view.ViewGroup.addViewInner(ViewGroup.java:4370) at android.view.ViewGroup.addView(ViewGroup.java:4184) at android.view.View$

**Comment by DmitriyKirakosyan** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
