### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by davidpricedev** [MicrosoftDocs/appcenter-docs#111]
Please make it clear that all of the "Processing crashes in JavaScript" section pertains to the NEXT run of the app, not the run that is crashed/crashing. 

Also, documenting the changes in the files that need to happen when you want to switch back and forth between javascript-enabled and not would be useful too: 
ios/employeecompanion/AppDelegate.m :: 
    // Initialize AppCenter crashes
    // register = allow JS callbacks, automatic = no JS callbacks
    [AppCenterReactNativeCrashes register];
    //[AppCenterReactNativeCrashes registerWithAutomaticProcessing];

android/app/src/main/res/values/strings.xml ::
    
    
    <string moduleConfig="true" name="appcenterCrashes_whenToSendCrashes">ASK_JAVASCRIPT</string>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e420f-cf2a-1d5b-d86a-d01c09bcf7a0
* Version Independent ID: 59c746fb-cf4d-3019-2b48-56b69e09aa27
* Content: [App Center Crashes for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native#process)
* Content Source: [docs/sdk/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@davidpricedev Thanks, I'll have the PM take a look at making an update.

**Comment by saraford** [comment]
@davidpricedev Hi :wave: Thanks for opening this issue and for the feedback! I'm the PM for this feature area. I'll make these changes at my next opportunity and let you know when it is done in case you'd like to review.

**Comment by syntax-e** [comment]
Reading the docs I was under the (optimistic) impression that "Processing crashes in JavaScript" happened on the same run as the crash, giving me the opportunity to serialize up the app's redux state tree as a crash report attachment. While it's still possible to send local state up as part of the crash report on the subsequent run, the implementation is going to be a bit tougher than I had originally estimated based solely on the docs.

**Comment by elamalani** [comment]
@davidpricedev @geocachingsyntaxerror Thanks for your feedback, we will update the SDK doc in a few days.

**Comment by guperrot** [comment]
@davidpricedev @geocachingsyntaxerror the docs have been updated. If you have other feedbacks, please don't hesitate to create new issues.
