### ISSUE TITLE
is it possible to run Appium tests in JavaScript using post-build script?

### ISSUE THREAD

**Issue by Buthrakaur** [MicrosoftDocs/appcenter-docs#1110]
Is it possible to run Appium tests in JavaScript using post-build script? Could you please provide any instructions if so?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90c615b-f4be-f496-63fb-498d315fd59e
* Version Independent ID: 0088372d-5849-e037-004e-617953b07f7c
* Content: [Testing Builds on Real Devices - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/build-test-integration)
* Content Source: [docs/build/build-test-integration.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/build-test-integration.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
The short answer is "no," the long answer is "maybe...?"

App Center Test doesn't support Appium (JavaScript), though it does support Appium (Java). (https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/appium/)

Technically, it is possible to run tests inside App Center Build, without Test, but there's a lot of limitations:
- Can't test on physical devices
- The simulator is auto-selected & can't be customized
- The Build timeout isn't increased

But, all of those caveats aside...build scripts allow you to customize logic beyond what's supported, you just have to keep in mind that the system isn't designed to support that but you might be able to get it working anyways. (https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/backup-data)

Usually, if you can get everything working purely via command line, AND it isn't blocked by any of those limitations I mentioned; it can work.
