### ISSUE TITLE
No mention of VS for windows or Mac for enabling ENABLE_TEST_CLOUD, two screenshots are confusing. needs clear distinction between VS for Windows and Mac

### ISSUE THREAD

**Issue by pchandravadan** [MicrosoftDocs/appcenter-docs#1114]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b5055c-bc86-18a2-7dc1-8c6582894763
* Version Independent ID: 092ee4b8-04fc-2067-13a2-20c0318882a9
* Content: [Get started with UITest and Xamarin.Forms - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/xamarin-forms)
* Content Source: [docs/test-cloud/frameworks/uitest/xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/xamarin-forms.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
