### ISSUE TITLE
No App Center Option for "Start testing your app."

### ISSUE THREAD

**Issue by LeoSalemann** [MicrosoftDocs/appcenter-docs#1119]
**Prepare to run tests in App Center** Step 2  says to _Click on Start testing your app._ No such option exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4463d3b-1421-1d44-30cc-d5cc04068c1e
* Version Independent ID: 2d60043a-4150-8ada-3f86-09c0458b5086
* Content: [Run Included Tests with App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/quickstarts/android/test)
* Content Source: [docs/quickstarts/android/test.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/quickstarts/android/test.md)
* Service: **vs-appcenter**
* GitHub Login: @sshibu
* Microsoft Alias: **t-shshib**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
