### ISSUE TITLE
Configuring OSX cloud images

### ISSUE THREAD

**Issue by scopp** [MicrosoftDocs/appcenter-docs#113]
Are these cloud machines configurable in any manor?  Are these images on Azure marketplace?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022126c7-2d61-9c53-6881-149310c137c0
* Version Independent ID: 4fe62fb4-6dd9-057e-8f57-fb4c6dcb71f8
* Content: [App Center Cloud Build Machines - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/software#feedback)
* Content Source: [docs/build/software.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/software.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@scopp The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
