### ISSUE TITLE
Doesn't denote if AppCenter.Start is additive or not

### ISSUE THREAD

**Issue by Tommigun1980** [MicrosoftDocs/appcenter-docs#1137]
The documentation doesn't say whether you can call AppCenter.Start multiple times with different modules.

My use case is I'd like to init crash reporting as early as possible (in the native parts of my Xamarin.Forms project), while my shared Xamarin.Forms project would initialise analytics later on. It is not clear from the documentation whether you can call Start multiple times, and if you can, it doesn't tell whether the modules sent in are additive or not.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72f6fe-74d6-696e-e709-5f6d577c0a58
* Version Independent ID: b3d0ea8b-5a1f-bf71-7dc2-9685cf23c00b
* Content: [Get Started with Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin)
* Content Source: [docs/sdk/getting-started/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/xamarin.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by russelarms** [comment]
Hi there, sorry for the delay! For the described purpose, our SDK has a special API: https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#change-state-of-service-in-runtime
Thus, you will need to call `Start` from the earliest point with a required service ("Crashes"):
`AppCenter.Start("ios={Your App Secret};android={Your App Secret};uwp={Your App Secret}", typeof(Crashes));`
 and then use `Analytics.SetEnabledAsync(true);` in another part of your application.

**Comment by Tommigun1980** [comment]
> Hi there, sorry for the delay! For the described purpose, our SDK has a special API: https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#change-state-of-service-in-runtime
> Thus, you will need to call `Start` from the earliest point with a required service ("Crashes"):
> `AppCenter.Start("ios={Your App Secret};android={Your App Secret};uwp={Your App Secret}", typeof(Crashes));`
> and then use `Analytics.SetEnabledAsync(true);` in another part of your application.

Thank you! I really appreciate the answer.

**Comment by Tommigun1980** [comment]
Actually let me reopen this -- as it may make sense to add what you said to the documentation for the Start method. Feel free to close if it's not deemed relevant, but it may make sense to make the aforementioned addition.
Thanks.

**Comment by russelarms** [comment]
We've updated the SDK docs on the separate start of App Center services, soon they'll be available on the portal.

**Comment by Tommigun1980** [comment]
Thank you!
