### ISSUE TITLE
Windows 10 app support

### ISSUE THREAD

**Issue by haymansfield** [MicrosoftDocs/appcenter-docs#1139]
Is there any support for Windows 10 Apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c31b388-68fd-649d-eb12-37c94fa6793c
* Version Independent ID: a590f5fc-c426-ef66-a3c5-732928325347
* Content: [Publish applications to Intune Company Portal - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/intune)
* Content Source: [docs/distribution/stores/intune.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/intune.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
See this chart for platform support: https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix
