### ISSUE TITLE
How to get the Symbols zip

### ISSUE THREAD

**Issue by jthake** [MicrosoftDocs/appcenter-docs#114]
It would be useful to know how to get the Symbols zip. I found this old hockeyapp documentation on this https://www.hockeyapp.net/help/sdk/ios/4.0.0/docs/docs/HowTo-Upload-Symbols.html

That had these steps.
Chose Window > Organizer in Xcode.
Select the tab Archives.
Select your app in the left sidebar.
Right-click on the latest archive and select Show in Finder.
Right-click the .xcarchive in Finder and select Show Package Contents.
You should see a folder named dSYMs which contains your dSYM bundle. If you use Safari, just drag this file from Finder and drop it on to the corresponding drop zone in HockeyApp. If you use another browser, copy the file to a different location, then right-click it and choose Compress YourApp.dSYM. The file will be compressed as a .zip file. Drag & drop this file to HockeyApp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663b3972-5d13-f787-05c6-45f0d49127ef
* Version Independent ID: 1aa13690-4428-163d-4cb4-f8fecad0665e
* Content: [App Center Crash Reporting for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/crashes/ios)
* Content Source: [docs/crashes/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/crashes/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @anlinde
* Microsoft Alias: **anlinde**

**Comment by jwargo** [comment]
@jthake thanks for the suggestion, we'll take a look at adding this to the docs.

**Comment by saraford** [comment]
@jthake hi :wave: Thanks for the feedback. Good catch. Let me see what I can do to port some of this relevant information over from HA docs. I'll let you know when it's done in case you'd like to review.
