### ISSUE TITLE
Android Test: Possibility to run the same test scopes on different devices in parallel

### ISSUE THREAD

**Issue by hs-mzaretski** [MicrosoftDocs/appcenter-docs#1143]
On the AppCenter Core Concept page there is a paragraph about devices concurrency
![image](https://user-images.githubusercontent.com/56677471/94163158-310e7c00-fe90-11ea-9f98-6b329267c57b.png)
But I didn't find any info about possibility to run all test suite on all devices at the same time. For example I have 20 tests. I want to know if it is possible to run all 20 tests on every device from device set, without dividing the test suite on parts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b34a665-39c4-e724-115c-489617a84cf7
* Version Independent ID: 9911c56b-792f-5fed-cd2b-7147647fee16
* Content: [App Center Test Core Concepts - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/core-concepts)
* Content Source: [docs/test-cloud/core-concepts.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/core-concepts.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
>  I want to know if it is possible to run all 20 tests on every device from device set, without dividing the test suite on parts

That's the normal operation of App Center Test. Device concurrency just relates to how many devices can be running those tests at once, while the rest of the devices are queued.
