### ISSUE TITLE
Run UI Tests on iOS physical devices

### ISSUE THREAD

**Issue by pchandravadan** [MicrosoftDocs/appcenter-docs#1144]
Documentation doesn't mention how to run UI Tests on iOS physical devices. I see Android has a way to mention device serial but not iOS as mentioned below.

IApp app = ConfigureApp.Android.ApkFile("/path/to/android.apk")
                               .DeviceSerial("03f80ddae07844d3")
                               .StartApp();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226ce68c-8e61-5b59-b158-2bc6f0c7e399
* Version Independent ID: f2386335-1233-877c-05ff-6eb0aabce32e
* Content: [Xamarin.UITest - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/)
* Content Source: [docs/test-cloud/frameworks/uitest/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by pchandravadan** [comment]
Hello, I am just wondering if you have any update on when this will be updated. Thanks for your help!

**Comment by King-of-Spades** [comment]
Modifying the doc itself will take some time, between juggling other updates and tasks. But in general I think this is the method you can use: https://docs.microsoft.com/en-us/dotnet/api/xamarin.uitest.configuration.iosappconfigurator.deviceidentifier?view=xamarin-uitest-sdk#Xamarin_UITest_Configuration_iOSAppConfigurator_DeviceIdentifier_System_String_

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
