### ISSUE TITLE
The Premier Support section is out of date. 

### ISSUE THREAD

**Issue by langjtl** [MicrosoftDocs/appcenter-docs#1146]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36da5026-39aa-9a48-440c-7e57da3e3373
* Version Independent ID: eff2f79f-df52-829f-a0c3-71396e365884
* Content: [Help and Feedback - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/help)
* Content Source: [docs/help.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/help.md)
* Service: **vs-appcenter**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
The links still appear to be valid, however the first of the two links requires a Microsoft account login, I'll add a note clarifying that. 

If that's insufficient for the issue you're noticing, please provide more details.
