### ISSUE TITLE
Add platform limits for maximum number of organizations can be created in one day

### ISSUE THREAD

**Issue by shuhaoy** [MicrosoftDocs/appcenter-docs#1159]
[Enter feedback here]

Currently, the platform seems to limit the maximum number of organizations can be created in one day. If so, can you add the limits for it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 753feb24-6869-bdbf-0880-1b5ae52732e0
* Version Independent ID: 8e4db4a1-07c2-ae46-3843-b139f19c1fb1
* Content: [Platform limits for App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/platform-limits)
* Content Source: [docs/general/platform-limits.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/platform-limits.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
AzDO PR - 47158

**Comment by King-of-Spades** [comment]
This is part of our internal anti-abuse measurements and we can't expose the exact details. If you're having issues with these limits, please contact our customer support as we want to learn more about your use case: https://docs.microsoft.com/en-us/appcenter/help
