### ISSUE TITLE
I have a multi-platform App what platform is wpf/windows

### ISSUE THREAD

**Issue by scarrier92** [MicrosoftDocs/appcenter-docs#1160]
AppCenter.Start("ios={secret IOS};" +
                  "uwp={secret uwp};" +
                  "android={secret android};"+
                  "**windows/wpf/???**={secret windows}",

how is the name of the platform called
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e799e45-8feb-d74c-4e25-3bdf49301766
* Version Independent ID: b6aef403-76f7-5df2-aa5d-3ed66397893d
* Content: [Get Started with WPF/WinForms - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms)
* Content Source: [docs/sdk/getting-started/wpf-winforms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/wpf-winforms.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by AnastasiaKubova** [comment]
For desktop apps you can try to use `windowsdesktop` keyword. But keep in mind that at the same time you can use this keyword only for one desktop app (either for Windows or WPF).
