### ISSUE TITLE
Where is "{Your App Secret}" found?

### ISSUE THREAD

**Issue by mneitzke** [MicrosoftDocs/appcenter-docs#1161]
Where is "{Your App Secret}" found?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5756765e-fef2-e8d9-f8d9-5c01690095b8
* Version Independent ID: b474e30a-6e59-97fc-476a-92be5ec3a01a
* Content: [App Center Crashes for UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp)
* Content Source: [docs/sdk/crashes/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/uwp.md)
* Service: **vs-appcenter-sdk**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by russelarms** [comment]
Hi there, sorry for the delay.
The App Secret can be found on the Getting Started page or Settings page of your app on the App Center portal (https://appcenter.ms).

I'm closing this issue, but feel free to write here if you have any additional questions or concerns.
