### ISSUE TITLE
Logs won't be uploaded when UWP application is in the background

### ISSUE THREAD

**Issue by bmwilson1978** [MicrosoftDocs/appcenter-docs#1163]
I think it's worth while noting that AppCenter logs will not sync up if the UWP application is in the background, even if extended execution is configured to allow the UWP application to not suspend in the background.

The reason I feel this point is important to document is the fact it took quite a number of months and us providing sample applications to Microsoft Support only to be told after all this time that it won't sync logs up if the UWP application is in the background - no matter what.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a696f4-2ae6-adbe-f62c-5d0210f9a477
* Version Independent ID: 072ca2d9-fe77-8c6e-c785-5591c2dd0b95
* Content: [App Center Analytics for Windows - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/windows#no-internet-access)
* Content Source: [docs/sdk/analytics/windows.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/windows.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-analytics**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
Thanks for that context, sorry for the frustration. If you still recall the support ticket, would you be willing and able to provide the identifier for it or respond to the ticket noting you opened this docs issue? It will help me cross-reference the findings a bit more quickly, though if that's not feasible for you that's okay, it'll probably just take me a bit longer to get and confirm all the relevant details to document.

**Comment by bmwilson1978** [comment]
Hi there, apologies for the delay.  The support ticket ref is 120071423002832.

**Comment by AnastasiaKubova** [comment]
The [fix](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/uwp#use-app-center-in-the-background-tasks) has been published, so I'm closing this issue but feel free to reopen this issue if you have additional questions.
