### ISSUE TITLE
Build Option is not visible for WPF app in app center

### ISSUE THREAD

**Issue by mageshsankar** [MicrosoftDocs/appcenter-docs#1165]
[I have using WPF app in app center, but could not able to find the Build option for WPF apps, is build option  available wpf app?]

![image](https://user-images.githubusercontent.com/55440472/98319721-67025c80-2007-11eb-9bf6-ecaf5cfdc667.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bad7023-e00b-b6af-b71f-1823e7829dec
* Version Independent ID: 77a10f16-f669-3934-08b3-ceefa52b2059
* Content: [App Center Build Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/)
* Content Source: [docs/build/troubleshooting/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/troubleshooting/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
Unfortunately Build doesn't support WPF: https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix
