### ISSUE TITLE
Build without a Mac for the P12

### ISSUE THREAD

**Issue by MattPil29** [MicrosoftDocs/appcenter-docs#1167]
Hi,

It took a while but we figured out there is a way of setting up a build WITHOUT a mac.  The steps in this document require one for obtaining CSR and P12.  

I posted the solution here: https://stackoverflow.com/questions/9418661/how-to-create-p12-certificate-for-ios-distribution/64771489#64771489

Please consider adding this as an alternative route, it will save people hours!

Thanks, Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01f1809-2316-7d47-1547-23775f6dd618
* Version Independent ID: 7d719380-4d1d-e995-e0e5-b2474ae5e9af
* Content: [iOS Code Signing in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/code-signing)
* Content Source: [docs/build/ios/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/code-signing.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
Building for iOS without a Mac isn't a supported scenario. So even if it's possible consistently, it's not in scope for us to document.
