### ISSUE TITLE
Expand InTune distribution doc to provide additional clarification and use cases

### ISSUE THREAD

**Issue by NateRickard** [MicrosoftDocs/appcenter-docs#117]
Would be great to add a bit more detail on what is being done behind the scenes and add some clarifications... some examples:

- Does App Center configure the app in InTune for you?  Does App Center send the app artifact to InTune as a LOB app?  etc. etc. (https://docs.microsoft.com/en-us/intune/apps-add).
- Can App Center support additional InTune scenarios like apps that are configured as "Required" in InTune (which would push the app directly to users and not require them to download it via the company portal).
- How can admins edit the app config in InTune to alter the way the the app is assigned to users, etc.  Don't want to recreate the InTune docs here, just provide some clarity on where AppCenter's role ends and InTune takes over.
- Possible naming/wording confusion: "Company Portal" is messaged heavily in this doc, but InTune != Company Portal and supports multiple app assignment scenarios, such as the aforementioned "Required" apps that get pushed directly to users.
- Are there InTune features that **cannot** be supported vis this integration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c31b388-68fd-649d-eb12-37c94fa6793c
* Version Independent ID: a590f5fc-c426-ef66-a3c5-732928325347
* Content: [Publish applications to Intune Company Portal - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/intune)
* Content Source: [docs/distribution/stores/intune.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/intune.md)
* Service: **vs-appcenter**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by pnghub** [comment]
HI! Nate - this is great feedback. 
The current (first) iteration of App Center - Intune integration only supports a push to the company portal but we do have plans to iterate on this.

If you had the time, would be great to have a phone meeting to understand your scenarios a bit more,  esp since we have had(are having) some conversations with the Intune team on additional integration options.

best, girish

**Comment by jwargo** [comment]
@NateRickard I've asked the PM for that part of the product to take a look at this.

**Comment by gaknoll** [comment]
@NateRickard Thanks for your feedback here! I'll work with the Stores to improve documentation to be more clear. If you'd be willing, @pnghub and I would still be interested in learning more about your scenarios for future iterations of the App Center & Intune integration.
Best,
Garrett
