### ISSUE TITLE
very nice docs! 

### ISSUE THREAD

**Issue by tinker1992** [MicrosoftDocs/appcenter-docs#1173]
[在此处输入反馈]
very nice docs!  

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0d13e061-cb49-5ee6-dfbd-249e8e2f11d5
* Version Independent ID: 88cb3aa2-3938-76b4-8297-dcc6380292d5
* Content: [Device registration - Visual Studio App Center](https://docs.microsoft.com/zh-cn/appcenter/distribution/auto-provisioning#how-to-generate-a-p12-file)
* Content Source: [docs/distribution/auto-provisioning.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/auto-provisioning.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
Thanks!
