### ISSUE TITLE
iPhone 12

### ISSUE THREAD

**Issue by mastermind69** [MicrosoftDocs/appcenter-docs#1174]
Hello 

When do you validate iPhone 12 ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10e7f03f-6bea-d9f7-16cd-282eef86b482
* Version Independent ID: d78888d0-cab0-4bfa-468c-5f7945745217
* Content: [iOS Devices Available - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/devices/ios)
* Content Source: [docs/test-cloud/devices/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/devices/ios.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
I've added a note to that doc about when devices are updated and how to check currently available devices manually in the App Center Test UI.

**Comment by mastermind69** [comment]
Hello

It's not working
Now I can see my correct device but I can't download the build (same issue)
________________________________

**Comment by King-of-Spades** [comment]
This guide is specific to devices available in our cloud for automated testing. It sounds like you might be referring to a build or distribute issue of some kind, rather than automated testing.
