### ISSUE TITLE
MSUpdateActionPostpone - Postpone Duration

### ISSUE THREAD

**Issue by rajazz** [MicrosoftDocs/appcenter-docs#1176]
Hi,

  Is there any postpone duration for AppCenter update postpone api

**Comment by russelarms** [comment]
Hi there, sorry for the delay.
We don't have an API to change the postponing duration. 

BTW the SDK is open-sourced, so if it's urgent, you can fork and change the SDK yourself: https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenterDistribute/AppCenterDistribute/MSACDistribute.m#L808
