### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by chrissago** [MicrosoftDocs/appcenter-docs#1178]
This document appears to refer to a now obsolete distribute call and does not explain what to use instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Distribute a build via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
thanks for the report! Can you tell me which call appears to be obsolete so I can confirm that with our product team?

**Comment by chrissago** [comment]
Sorry, I think I was wrong about this. Closing.
