### ISSUE TITLE
AppCenter iOS SDK v4.0.0 naming convention

### ISSUE THREAD

**Issue by amanssharma** [MicrosoftDocs/appcenter-docs#1180]
For a public product I think a couple of type names (I only work with `Analytics` and `Crashes`, but `ServiceAbstract ` and `ErrorReport` also seem to qualify) you've chosen for v4.0.0 of the iOS SDK are too generic and have a potential to create namespace collision issues.
On a project that I work on, I have a protocol named Analytics which defines APIs that multiple analytics SDKs used in my app expose.
This conflicted straight-up with the `Analytics` class in AppCenter.
I got around it by using the fully-qualified class-name but I think that for a public product, some less generic class names should have been chosen.
This is my opinion, and I am by no means an expert on this topic, but I thought I should share this feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34fd58f9-ea70-d0ba-3348-60ae07299df4
* Version Independent ID: 2d6c5944-5b2a-9a1d-f8b4-9f1b0d51bcaa
* Content: [How to migrate to App Center SDK 4.0.0 and higher - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/migration/apple-sdk-update)
* Content Source: [docs/sdk/getting-started/migration/apple-sdk-update.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/migration/apple-sdk-update.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by MatkovIvan** [comment]
Hi @amanssharma,

Mentioned names are Swift aliases for Objective-C classes that have "MSAC" prefix that makes it unique. Objective-C doesn't have namespaces, but Swift has another convection, all classes there are in namespaces. It is implicit in Swift, meaning that all types, variables (etc) are automatically scoped by the module. You need to put the package name in front of the class name to resolve the conflict. Something like: `YourTargetName.Analytics`
