### ISSUE TITLE
Signing Info File section out of date; test-cloud.exe no longer makes those files

### ISSUE THREAD

**Issue by jmegner** [MicrosoftDocs/appcenter-docs#1182]
The [Signing Info File](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/android/signing#signing-info-file) section says:

> find the test-cloud.exe ... use it to generate the Signing Info file

But test-cloud.exe no longer supports generating Signing Info files.  I personally tested with Xamarin.UITest 3.0.12, and I've seen [reports](https://intercom.help/appcenter/en/articles/2117063-xamarin-uitest-and-signing-android-apps) that the support was dropped after Xamarin.UITest 2.2.7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647306df-2aad-1ff2-31c2-6c33e23c85b1
* Version Independent ID: 20d54205-eb1a-f9ca-1784-ee3358022f0f
* Content: [Xamarin.UITest and Signing Android Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/android/signing)
* Content Source: [docs/test-cloud/frameworks/uitest/android/signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/android/signing.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
