### ISSUE TITLE
No mention of DispatcherUnhandledException in Wpf programs

### ISSUE THREAD

**Issue by henrikmbach** [MicrosoftDocs/appcenter-docs#1183]
There is no mention of the handling of unhandled exceptions via the DispatcherUnhandledException property in a Wpf program. Like, should there be some AppCenter code in the method that handles the DispatcherUnhandledException to record a crash or not? I guess if I use the DispatcherUnhandledException there will be no crashes in my program. I searched google for appcenter and DispatcherUnhandledException and I found nothing. Note - the args.Handled is set to true, so Wpf does not continue with processing the exception. If I use the DispatcherUnhandledException and set args.Handles to true, I suppose there will be no recording in AppCenter of a crash? Should I add code to the DispatcherUnhandledException method to record a AppCenter crash? I'm investigating a case where nothing about crashes is recorded in AppCenter for a proper build installed on my developer pc, but running a debug version through Visual Studio on the same developer pc records a crash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eae5644-1b90-680a-25aa-9ebc77b3ce58
* Version Independent ID: 05a373b3-f6eb-e92e-72a3-d8bd49fa9aab
* Content: [App Center Crashes for Windows - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms)
* Content Source: [docs/sdk/crashes/wpf-winforms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/wpf-winforms.md)
* Service: **vs-appcenter-sdk**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by russelarms** [comment]
Hi there, sorry for the delay!

> There is no mention of the handling of unhandled exceptions via the DispatcherUnhandledException property in a Wpf program.

The case is a bit unclear to me. Unhandled exceptions should go through the Crashes module. 

> Like, should there be some AppCenter code in the method that handles the DispatcherUnhandledException to record a crash or not?

If your application must keep running after an unhandled exception, you can't report the exception as a crash in App Center but you can instead report it as an error: 
```
Application.ThreadException += (sender, args) =>
{
    Crashes.TrackError(args.Exception);
};
AppCenter.Start(...);
```
