### ISSUE TITLE
WatchOS

### ISSUE THREAD

**Issue by albeaver** [MicrosoftDocs/appcenter-docs#119]
Documentation does not include any information what is needed to have support for a WatchOS target. Errors are given when compiling about how "WatchOS" does not match "iPhone" but the documentation should include what is required for submitting WatchOS apps, or specifically mention if WatchOS deployments are not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc01291c-f6a0-4610-a27d-60718852390d
* Version Independent ID: 2b51b117-6b8c-f4d9-a2b2-43c891d20171
* Content: [Configure a Objective-C or Swift iOS build in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/first-build)
* Content Source: [docs/build/ios/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@albeaver thanks for the feedback, I'll have the PM team take a look.

**Comment by dipree** [comment]
@albeaver thanks for your feedback, unfortunately app extensions are currently not supported. We'll update the docs soon.
