### ISSUE TITLE
Needs details on possibilities of using Enterprise install of Github

### ISSUE THREAD

**Issue by wouterla** [MicrosoftDocs/appcenter-docs#120]
A little more detail on how flexible the OAuth flow is from App Center (can I provide my own URL, or does it work only through github.com?) would help me determine whether I can use app-center with a hosted-on-aws instance of Github Enterprise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12fa9a24-2575-3fa4-ffab-cafaeab496c1
* Version Independent ID: bbb99ead-eecc-222a-bc16-7509be5e8ec9
* Content: [Connect to a repository to start building your mobile app - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/connect)
* Content Source: [docs/build/connect.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/connect.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by nilofer** [comment]
@wouterla thanks for this feedback. App Center does not currently support GitHub Enterprise.

**Comment by timg-mlbam** [comment]
Any chance support for GitHub enterprise is on the roadmap? Our org would love to use it but can't today because of this.

**Comment by nilofer** [comment]
Hi @timg-mlbam, App Center still does not currently support GitHub Enterprise and it is not on our public short-term roadmap.

**Comment by jayad-aadrit** [comment]
Is gitlab supported?

**Comment by jwargo** [comment]
@jayad-aadrit No, as of [this document](https://docs.microsoft.com/en-us/appcenter/build/connect)

**Comment by jayad-aadrit** [comment]
@jwargo Thanks! for the quick response. I've tried it with github public repo, wanted to know whether it works with private github repo as well?

**Comment by nilofer** [comment]
@jayad-aadrit Private GitHub repos are supported. However, GitHub Enterprise repos are not.
