### ISSUE TITLE
 Does App center support Appium -Cucumber -Junit ?

### ISSUE THREAD

**Issue by yogashanmugam** [MicrosoftDocs/appcenter-docs#1200]
[Enter feedback here]

On App center Test document its mentioned. JUnit 4.9 - 4.12 is supported not JUnit 5.
I would like to know does app center support Cucumber -Appium -Junit 
Its mandatory to use BDD in my project and We already  using app center . 
Thanks in advance   
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a93e3805-5fd5-c6c9-f25d-1be5c41ed77f
* Version Independent ID: 9826c974-24a2-b65e-9603-14428f6bb5bc
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-gb/appcenter/test-cloud/frameworks/appium/)
* Content Source: [docs/test-cloud/frameworks/appium/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/appium/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
