### ISSUE TITLE
Note block is confusing

### ISSUE THREAD

**Issue by jlinstrum** [MicrosoftDocs/appcenter-docs#1201]
Toward the top of the document there is this note:

"UWP only supports starting Crashes with AppCenter.Start and none of the other API calls provided by the Crashes class are supported on UWP, They only work for Xamarin.iOS, Xamarin.Android and Xamarin.Forms apps deployed to iOS and Android..."

However, Crashes.TrackError is now supported as per https://github.com/Microsoft/appcenter/issues/150 .

So, this note at the top is a little confusing. I know that Crashes.TrackError works (I have used it in my program - it's great!). Do the other API calls work or not? (I haven't had to use them yet so I don't know). The note should be changed to indicate what works, what doesn't, and what might work in the future.

Cheers,
John Linstrum

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5756765e-fef2-e8d9-f8d9-5c01690095b8
* Version Independent ID: b474e30a-6e59-97fc-476a-92be5ec3a01a
* Content: [App Center Crashes for UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp#handled-errors)
* Content Source: [docs/sdk/crashes/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/uwp.md)
* Service: **vs-appcenter-sdk**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
We updated related docs so I’m closing this issue. Feel free to reopen this issue if it isn't resolved or you have additional questions.
