### ISSUE TITLE
REPL should have been mentioned.  It is invaluable for testing and formulating UITest code.

### ISSUE THREAD

**Issue by grockland** [MicrosoftDocs/appcenter-docs#1203]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a102da-b3f2-2221-9e8c-a5acdeb70071
* Version Independent ID: a1edc60a-613c-f19e-0b93-2a8368bdc8dd
* Content: [Xamarin.UITest cheat sheet - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/cheatsheet)
* Content Source: [docs/test-cloud/frameworks/uitest/cheatsheet.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/cheatsheet.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
