### ISSUE TITLE
Distribute.CheckForUpdates on button does nothing

### ISSUE THREAD

**Issue by ColdstarJoey** [MicrosoftDocs/appcenter-docs#1208]
Hey I have a button on my settings page in Xamarin Forms that I want to manually check for updates but when I add Distribute.CheckForUpdates(); to the button it does nothing and the application is set to mandatory in app center. I'm I missing something

**Comment by DmitriyKirakosyan** [comment]
Hi @ColdstarJoey 
Thank you for reaching out to us!
It sounds like this issue for technical support, but this repository isn't monitored by our support team.

If you need technical help, you can contact support by:
1. Going to [appcenter.ms](https://appcenter.ms/)
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
