### ISSUE TITLE
clarificatio on docs

### ISSUE THREAD

**Issue by jarodms** [MicrosoftDocs/appcenter-docs#1210]
On the page: https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios
"Adding your device", part 1, second bullet where it says "Click the profile icon in the **upper-left** corner of the App Center portal."

It should read "upper-right corner" based on how the app works and the screenshot on that page.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811f9eee-5b17-06e1-c108-dbef47984425
* Version Independent ID: 8fe50e13-c934-6a43-bf7d-1f33946da9d3
* Content: [Testing iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios)
* Content Source: [docs/distribution/testers/testing-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-ios.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by DmitriyKirakosyan** [comment]
Hi @jarodms 

Thank you for reaching out to us.

Your suggestion is absolutely correct. We will update the docs.
Thanks!

**Comment by DmitriyKirakosyan** [comment]
The page is fixed. Closing this.
