### ISSUE TITLE
It's not clear to me what the difference between a 'device configuration' and a 'device' is.

### ISSUE THREAD

**Issue by JvandeKraats** [MicrosoftDocs/appcenter-docs#1213]
While reading this page it's not clear to me what the difference between a 'device configuration' and a 'device' is.
Can anyone explain this to me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc863ba-5295-2db8-b37f-584e662e725a
* Version Independent ID: db2a1468-e4fa-6c55-985f-616de1e6484f
* Content: [App Center Pricing - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/pricing)
* Content Source: [docs/general/pricing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/pricing.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
