### ISSUE TITLE
Incorrect link to note about showing updateDialog to iOS users

### ISSUE THREAD

**Issue by swrobel** [MicrosoftDocs/appcenter-docs#1217]
The link to the note about showing updateDialog to iOS users is outdated. I believe the new link should be: https://github.com/Microsoft/react-native-code-push#app-store

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 839ed343-89da-4d62-c160-8f81fe396518
* Version Independent ID: 12f9c437-71ee-6f7a-bf72-0010a073df97
* Content: [React Native SDK with CodePush API Reference - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref)
* Content Source: [docs/distribution/codepush/rn-api-ref.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/rn-api-ref.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @swrobel 

Thank you for catching and reporting this issue.
I prepared a PR fixing it.

**Comment by DmitriyKirakosyan** [comment]
Fixed. Closing the issue.
