### ISSUE TITLE
[LINK]

### ISSUE THREAD

**Issue by brimmy11** [MicrosoftDocs/appcenter-docs#122]
I think the word [LINK] was supposed to be replaced by a link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b24e043-b73c-c05d-b101-56d2b89a3a7a
* Version Independent ID: 234e0be5-9c02-b8b4-7a5d-6032f5cba4e8
* Content: [App Center Test - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/)
* Content Source: [docs/test-cloud/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/index.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@brimmy11 yep, you're right. I'll get that fixed.

**Comment by glennwester** [comment]
@brimmy11 Thanks for reporting! This is fixed.
