### ISSUE TITLE
concept of Local Tests not documented in Core Concepts

### ISSUE THREAD

**Issue by wouterb-synamedia** [MicrosoftDocs/appcenter-docs#1222]
The page (Signing iOS Apps for Automated Testing - Visual Studio App Center)
distinguishes between Local and App Center tests,
but it does not define local, and also the Core Concepts page does not define it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46606943-b42c-bcb0-8ff9-0088c3316779
* Version Independent ID: fcacda16-ea6f-40fb-f385-32382524a5e6
* Content: [Signing iOS Apps for Automated Testing - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/ios-sign-for-testing)
* Content Source: [docs/test-cloud/ios-sign-for-testing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/ios-sign-for-testing.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
