### ISSUE TITLE
is a Factory Reset done for the device?

### ISSUE THREAD

**Issue by wouterb-synamedia** [MicrosoftDocs/appcenter-docs#1224]
This page mentions a reset to default settings.
Does this involve a factory reset?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47ee8bb1-0229-793b-2766-1c8ed9a91d3f
* Version Independent ID: 4d368875-689b-4b1f-0fb6-716c0557b613
* Content: [App Center Test Security - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/security?source=docs)
* Content Source: [docs/test-cloud/security.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/security.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by Priskorn** [comment]
Hi @wouterb-synamedia 

we don't perform factory reset but rather have internal tooling for "cleaning" between test runs for android and restore for apple instances 

Thanks
