### ISSUE TITLE
React Native Platform Parameter missing documentation

### ISSUE THREAD

**Issue by omonk** [MicrosoftDocs/appcenter-docs#1232]
On the [platform paramter](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#platform-parameter) section it details selection of the specific platform that you want to create a release for. 

![image](https://user-images.githubusercontent.com/7108120/116401446-2ac7f000-a823-11eb-9d87-d6625bf74574.png)

This list the `Platform Parameter` section is in refers to the available flags one can pass to the `release-react` command  but is not actually listed in the full [CLI example list](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#releasing-updates-react-native):

```
appcenter codepush release-react -a <ownerName>/<appName> -d <deploymentName> -t <targetBinaryVersion>
[-t|--target-binary-version <targetBinaryVersion>]
[-o|--output-dir]
[-s|--sourcemap-output]
[-c|--build-configuration-name <arg>]
[--plist-file-prefix]
[-p|--plist-file]
[-g|--gradle-file]
[-e|--entry-file]
[--development]
[-b|--bundle-name <bundleName>]
[-r|--rollout <rolloutPercentage>]
[--disable-duplicate-release-error]
[-k|--private-key-path <privateKeyPath>]
[-m|--mandatory]
[-x|--disabled]
[--description <description>]
[-d|--deployment-name <deploymentName>]
[-a|--app <ownerName>/<appName>]
[--disable-telemetry]
[-v|--version]
```

## Questions

- If I run `appcenter codepush release-react -a App/AppName -d Production --plist-file ios/app/Appname-Info.plist` will this only deploy to iOS? 
- Which platform is targeted if this is omitted from the command list?
- Is this flag still available?
- What does it look like?
- How can I target both Android and iOS in the same command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c2bd47-97e3-abc8-fbdd-305f0c631827
* Version Independent ID: 318718e7-a38a-7cc5-01a4-7ce0153c4398
* Content: [Releasing CodePush updates using the App Center CLI - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#platform-parameter)
* Content Source: [docs/distribution/codepush/cli.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/cli.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @omonk 

Thank you for reaching out to us!

The command `codepush release-react` doesn't have a "platform" parameter. It retrieves the platform by the provided owner name and app name (`[-a|--app <ownerName>/<appName>]`), using the AppCenter open API.
You can see it in CLI code here: [appcenter-cli/release-react.ts#L126](https://github.com/microsoft/appcenter-cli/blob/master/src/commands/codepush/release-react.ts#L126) -> [appcenter-cli/appsOperations.js#L1540](https://github.com/microsoft/appcenter-cli/blob/master/src/util/apis/generated/operations/appsOperations.js#L1540).

I will update the docs to avoid confusing readers in future.

**Comment by omonk** [comment]
Hey @DmitriyKirakosyan thanks for the reply!

That's good to know thank you, from your comment and looking at our implementation it looks as though the naming of our apps is a bit funky then! Our ownerName is the same as our appName for our iOS app but is suffixed with `-1` for our Android app, e.g. 

```
ownerName = FooBar
iOS appName = FooBar
Android appName = FooBar-1
```
