### ISSUE TITLE
Get information whether the server is reachable or not

### ISSUE THREAD

**Issue by rubiomiguel06** [MicrosoftDocs/appcenter-docs#1234]
Imagine a case where an app using the AppCenter Crashes and Analytics API is running on a device with restricted internet access (firewall policies, etc). Is there a way of knowing if the AppCenter's domains are reachable by the API? Is it possible to check if the local log storage is empty in order to be sure that the logs were sent to the server?

I will be deploying a UWP App in several machines where the mentioned above case could be possible, and I would like to know if the data of that user will be available on the AppCenter or not, in order to take different measures in case it will not (report the installation via an automated email or something like that in order to keep track of the deployed versions of the app in the field).

I couldn't find anywhere on the documents the domain name the API reports the logs to (in order to make a quick check if it is accessible with an HTTP/GET or so)

**Comment by Jamminroot** [comment]
Hey @rubiomiguel06, thanks for reaching out.

Endpoint which is mainly used in the SDK is `in.appcenter.ms`, and it should be the first place to check if backend is reachable.

As for "how" - there's no public API for that in SDK.
