### ISSUE TITLE
(Appcenter Appium Mobile automation) How to automate Multi factor authentication enabled accounts 

### ISSUE THREAD

**Issue by AG-QALab** [MicrosoftDocs/appcenter-docs#1235]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7bab69-cfac-aefa-3ec0-b61d1dc3bf4f
* Version Independent ID: 73c4d2ba-d784-074c-6117-e81a4e0ae059
* Content: [Using Azure DevOps for UI Testing - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/vsts-plugin)
* Content Source: [docs/test-cloud/vsts-plugin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/vsts-plugin.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by lucen-ms** [comment]
@LTIQA can you please add more description what you expect?

**Comment by AG-QALab** [comment]
We have test service accounts. By using these accounts we are able to login without 2 factor authentication till now (in Appcenter Appium Mobile Automation). Currently, Microsoft team enable 2 factor authentication process for all service accounts. In this case, How to do automation ? Is there any way to do automation ?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
