### ISSUE TITLE
jcenter() End of life

### ISSUE THREAD

**Issue by dmgerdes-sch** [MicrosoftDocs/appcenter-docs#1237]
Can you migrate com.microsoft.appcenter:espresso-test-extension:1.4 to maven?  Android Studio 4.2 is deprecating jcenter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d8bdce-a2ad-80cb-efdb-74c0bb3ebb8c
* Version Independent ID: b8d0b4a7-a6b0-42d6-aab3-58a9d8681502
* Content: [Preparing Espresso Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/espresso/)
* Content Source: [docs/test-cloud/frameworks/espresso/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/espresso/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by AnastasiaKubova** [comment]
Hi! The `espresso-test-extension` was moved to the maven repository. Please see [this guide](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/espresso/) about integration espresso tests via maven.
