### ISSUE TITLE
Concept of Distribution Group in App Center doesn't now exist?

### ISSUE THREAD

**Issue by SandipAhluwalia** [MicrosoftDocs/appcenter-docs#124]
Has Teams replaced Distribution Groups as I can't find the "New Group" group button from the top of the screen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a807b36-339c-dd76-a6bb-132005991516
* Version Independent ID: 8ffb33e3-09fd-fe41-742f-a9f4d11bf901
* Content: [Manage App Center Distribution Groups - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/groups)
* Content Source: [docs/distribution/groups.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/groups.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by SandipAhluwalia** [comment]
Okay, I have now found it in the Distribute menu, so it does exist :)

**Comment by jwargo** [comment]
@SandipAhluwalia I'm glad you figured it out. Going forward, the comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by spacesuitdiver** [comment]
This is under distribution group settings, what even does this do?
![image](https://user-images.githubusercontent.com/2807897/84809237-63762680-afcf-11ea-8569-16dcc6a9bd28.png)
