### ISSUE TITLE
DatePicker not working with ja-JP culture

### ISSUE THREAD

**Issue by VikashChauhan51** [MicrosoftDocs/appcenter-docs#1241]
[Enter feedback here]

**DatePicker not working with ja-JP culture:**

Following code return digit instead of digit with text:
            string day=date.Day.ToString();
            string year=date.Year.ToString();

**Current result:**
day =14
year=2021

**Expected result:**
day =14日
year=2021年

**Verified on Device** 📱 8
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465e759c-e3d6-d9d6-5a45-e15e8b9156ef
* Version Independent ID: bb77c744-4cb8-49b9-7f00-b42664e5cb2f
* Content: [Automating Xamarin.Forms Date & Time Pickers with Xamarin.UITest - Visual Studio App Center](https://docs.microsoft.com/en-gb/appcenter/test-cloud/frameworks/uitest/features/date-time-pickers)
* Content Source: [docs/test-cloud/frameworks/uitest/features/date-time-pickers.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/features/date-time-pickers.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by VikashChauhan51** [comment]
Here two issues with sample code:

**First:**
Following code return digit instead of digit with text:
    ```
     string day=date.Day.ToString();
     string year=date.Year.ToString();
```

**Second:**
we need to swipe the **"inComponent"** for **day 1->2**, **month 0->1**  and **year  2->0** with following hake:

       app.Query(x => x.Class("UIPickerView").Invoke("selectRow", date.Day, "inComponent", 1, "animated", true));
        app.Tap(day);

        app.Query(x => x.Class("UIPickerView").Invoke("selectRow", date.Year, "inComponent", 2, "animated", true));
        app.Tap(year);

//Hake for ja-JP culture specific text
            
 ```
 year = date.ToString("Y").Replace(month, string.Empty);
 day = date.ToString("M").Replace(month, string.Empty);
```
    
**Note:** Verified on iphone8

@lucen-ms please help to provide a robust solution which will work with all supported cultures.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
