### ISSUE TITLE
[LOC]Fixed inappropriate japanese "レポポ"→"リポジトリ" (ja-jp) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/appcenter-docs#1242]
ja-jp:"https://docs.microsoft.com/ja-jp/appcenter/build/connect"
![build_connect_j](https://user-images.githubusercontent.com/40815708/118383688-3e54c280-b63b-11eb-9a59-74eeeedce163.png)

en-us:"https://docs.microsoft.com/en-us/appcenter/build/connect"
![build_connect_e](https://user-images.githubusercontent.com/40815708/118383691-414fb300-b63b-11eb-93a9-cdb8f3b7e082.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12fa9a24-2575-3fa4-ffab-cafaeab496c1
* Version Independent ID: bbb99ead-eecc-222a-bc16-7509be5e8ec9
* Content: [Managing source repository connections - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/connect)
* Content Source: [docs/build/connect.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/connect.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by JasonCard** [comment]
@hyoshioka0128 Thank you for this feedback. I'll follow up internally to human translate this article.
cc @lucen-ms

**Comment by JasonCard** [comment]
@hyoshioka0128 The Japanese translation is now fixed to, "ビルド エージェントがリポジトリに接続できるように、build.appcenter.ms のブロックを解除する必要がある場合があります。".
@lucen-ms please go ahead to close this issue.

**Comment by hyoshioka0128** [comment]
@JasonCard - Thanks. Fixed. 
Closed #1242 .
