### ISSUE TITLE
Ambiguous documentation

### ISSUE THREAD

**Issue by vtourraine** [MicrosoftDocs/appcenter-docs#1243]
> Connecting to a repository owned by an organization on GitHub or team on Bitbucket requires admin access

The wording here is ambiguous: does this require “admin access” for the App Center account or for the GitHub account? Or maybe both? It would be great if you could clarify that, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da27216-2ec0-ab4f-6235-cafde99f44d8
* Version Independent ID: 268f8ecb-5d39-2164-0120-43453bfb19ef
* Content: [Code Repository Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/code-repos#not-listed)
* Content Source: [docs/build/troubleshooting/code-repos.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/troubleshooting/code-repos.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by wisdeom** [comment]
This means you need Admin access to your GitHub/Bitbucket repository. Thanks for bringing this to our attention. I'll see if we can better clarify this doc.

**Comment by vtourraine** [comment]
@wisdeom Thank you for the quick clarification! 👍 Would be great to update the documentation accordingly.

**Comment by lucen-ms** [comment]
Thank you @vtourraine , docs have been updated.

**Comment by vtourraine** [comment]
Really appreciated, thank you!
