### ISSUE TITLE
Typo in page

### ISSUE THREAD

**Issue by iakdeniz64** [MicrosoftDocs/appcenter-docs#1245]
Typo in Note at the end of page. Should be "Your system `path` variable must include access to your machine's Java installation."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d8bdce-a2ad-80cb-efdb-74c0bb3ebb8c
* Version Independent ID: b8d0b4a7-a6b0-42d6-aab3-58a9d8681502
* Content: [Preparing Espresso Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/espresso/)
* Content Source: [docs/test-cloud/frameworks/espresso/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/espresso/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by lucen-ms** [comment]
Thank you @iakdeniz64 for reporting the type - it is now fixed.
