### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by thibault-ml** [MicrosoftDocs/appcenter-docs#125]
In the comparison table, Switf should be Swift

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8713388f-7f2b-1d33-2250-e2b4672feac9
* Version Independent ID: 108f8b11-d960-e440-138c-16b53e4989f8
* Content: [Mobile App Testing Frameworks Overview - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/migration/test-cloud/frameworks)
* Content Source: [docs/migration/test-cloud/frameworks.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/migration/test-cloud/frameworks.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
fixed, thanks!
