### ISSUE TITLE
Properties of crash report

### ISSUE THREAD

**Issue by ridmal** [MicrosoftDocs/appcenter-docs#1256]
The documentation mentioned that we can control sending out our crash report using this method

```
Crashes.setListener({
    shouldProcess: function (report) {
        return true; // return true if the crash report should be processed, otherwise false.
    },
});
```

Just wondering what are the properties of this report param in above function ? ( Can't find that in the documentation ) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e420f-cf2a-1d5b-d86a-d01c09bcf7a0
* Version Independent ID: 59c746fb-cf4d-3019-2b48-56b69e09aa27
* Content: [App Center Crashes for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native)
* Content Source: [docs/sdk/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/react-native.md)
* Service: **vs-appcenter-sdk**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @ridmal 

Thank you for reaching out to us!

This is ErrorReport class. Please check the implementation in the native repos:
[appcenter-sdk-android/ErrorReport.java](https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/model/ErrorReport.java)
[appcenter-sdk-apple/MSACErrorReport.h](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenterCrashes/AppCenterCrashes/Model/MSACErrorReport.h)

**Comment by ridmal** [comment]
Thank you @DmitriyKirakosyan
