### ISSUE TITLE
MAUI Support

### ISSUE THREAD

**Issue by johnathan-s** [MicrosoftDocs/appcenter-docs#1259]
Will this test framework still work with MAUI or will there be a new framework (and if there will be a new framework, what will it be)? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b5055c-bc86-18a2-7dc1-8c6582894763
* Version Independent ID: 092ee4b8-04fc-2067-13a2-20c0318882a9
* Content: [Get started with UITest and Xamarin.Forms - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/xamarin-forms?tabs=windows)
* Content Source: [docs/test-cloud/frameworks/uitest/xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/xamarin-forms.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by vhugogarcia** [comment]
I have the same question 🙋🏼‍♂️. 

Is a MAUI library going to be released at the same time in November?

**Comment by Jacko1394** [comment]
MAUI Release pushed back to Q2 of 2022 (Apr/May)
Maybe giving time for AppCenter to support building MAUI apps? 😁

**Comment by mnxamdev** [comment]
I'm interested in .Net MAUI support for App Center Builds. Do we have a timeline on that? Thanks.

**Comment by czmirek** [comment]
The last item in [Appcenter's changelog](https://docs.microsoft.com/en-us/appcenter/general/changelog) is from 2019. I don't think there's going to be any update for MAUI or anything else. I want to update my app to MAUI so I'm moving from appcenter to Azure DevOps eventhough I really like appcenter.

**Comment by joker109** [comment]
Any expected timeline of MAUI support package to come?

**Comment by MatkovIvan** [comment]
@joker109 please follow updates in https://github.com/microsoft/appcenter/issues/2416

Closing this thread as duplicate

**Comment by dgerding** [comment]
Hi AppCenter team, please provided a concrete answer about Maui test support with a timeline.

**Comment by AlexeyBudynkov** [comment]
@dgerding Hello. We're still working on it.
You can follow this issue https://github.com/microsoft/appcenter/issues/2416
