### ISSUE TITLE
Supported versions and requirements

### ISSUE THREAD

**Issue by zhangcx627** [MicrosoftDocs/appcenter-docs#1261]
Could you please add the new version of Xcode. Now the latest support is 12.4.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f23aa5-409f-7f45-8f4a-b6ea3f580419
* Version Independent ID: 4f34bc23-2820-3f28-272f-7a0554906b31
* Content: [Configure an Objective-C or Swift iOS build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/)
* Content Source: [docs/build/ios/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by zhangcx627** [comment]
Any updates?

**Comment by zhangcx627** [comment]
Any updates?

**Comment by DmitriyKirakosyan** [comment]
Hi @zhangcx627 

This issue is a duplicate of https://github.com/microsoft/appcenter/issues/2185.

Please follow the progress in the original issue.
I'm closing this one as a duplicate.
