### ISSUE TITLE
Provide detail on key alias and key password

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/appcenter-docs#1262]
Please provide links or additional information on 'Key alias' and 'Key password'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0be492-e3a3-4552-d4e1-1a390d0a086a
* Version Independent ID: 9f8bd631-f95e-c182-ddbe-9f626289cc84
* Content: [Xamarin.Android Code Signing Setup in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/xamarin/android/code-signing)
* Content Source: [docs/build/xamarin/android/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/xamarin/android/code-signing.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @samrueby

Thank you for reaching out!

These are the alias and password for your `.jks` file. Please read more info on how to generate such key file here: [Generate an upload key and keystore](https://developer.android.com/studio/publish/app-signing#generate-key).

I'm closing this issue. Please let me know if you have additional questions.
