### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Suil3File** [MicrosoftDocs/appcenter-docs#127]
Onp issues

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06813350-a37b-a4a2-fdbc-a59caefb9f32
* Version Independent ID: 29787958-5b4e-efc2-2af5-2af0ee53216e
* Content: [App Center Build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/)
* Content Source: [docs/build/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/index.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@Suil3File Do you have a question about App Center? The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
