### ISSUE TITLE
Question about network activity - is there request batching?

### ISSUE THREAD

**Issue by wh1t3cAt1k** [MicrosoftDocs/appcenter-docs#1272]
Is the SDK architected in such a way that it collects data, and submits it only once in a while so that you don't end up being too "chatty" with a remote server?

I couldn't find this info in the documentation or FAQ.

**Comment by DmitriyKirakosyan** [comment]
Hi @wh1t3cAt1k 

Thank you for reaching out to us!

We have a new API in the SDK that allows to control the network requests.
Usage:
```swift
// swift
AppCenter.networkRequestsAllowed = false
```

```kotlin
// kotlin
AppCenter.setNetworkRequestsAllowed(true)
```

By default the AppCenter SDK tries to send data over the network without batching it. If network is not available or `isNetworkRequestsAllowed` was set to `false`, it saves the logs to the local storage and sends pending data once it can.

The docs describing `isNetworkRequestsAllowed` API are not live yet, sorry for the inconvenience.

**Comment by wh1t3cAt1k** [comment]
Hi @DmitriyKirakosyan , thanks for the clarification. That's helpful.
