### ISSUE TITLE
AppCenterAnalytics. Please clarify Custom Event Limits

### ISSUE THREAD

**Issue by gutley** [MicrosoftDocs/appcenter-docs#1273]
According to [the event metric docs](https://docs.microsoft.com/en-gb/appcenter/analytics/event-metrics):

_The maximum number of distinct custom events that can be tracked daily is 200. This count resets at 12 AM UTC. However, there isn't a limit on the maximum number of events instances sent per device._

Can you please clarify what 'distinct' means in this case. Is it referring to the event name, or the entire contents of the event.

E.g
```
Analytics.trackEvent("Event1", withProperties: [["property": 1]])
Analytics.trackEvent("Event2", withProperties: [["property": 1]])
Analytics.trackEvent("Event3", withProperties: [["property": 1]])
... 200 events later
Analytics.trackEvent("Event200", withProperties: [["property": 1]])
Analytics.trackEvent("Event201", withProperties: [["property": 1]])
```
In the above, does it mean "Event201" will be dropped as its over 201 custom event names?

Compared to
```
Analytics.trackEvent("Event1", withProperties: [["property": 1]])
Analytics.trackEvent("Event1", withProperties: [["property": 2]])
Analytics.trackEvent("Event1", withProperties: [["property": 3]])
... 200 events later
Analytics.trackEvent("Event1", withProperties: [["property": 200]])
Analytics.trackEvent("Event1", withProperties: [["property": 201]])
```
Do any of those get dropped since they are all distinct by their properties being different?

My reading of the docs is that its "Event201" that gets dropped as I assume you mean just the event name when you say "distinct", but this needs clarification.

Thanks

**Comment by DmitriyKirakosyan** [comment]
Hi @gutley 

Thanks for reaching out to us!

Your understanding is correct, events are considered distinct if the event name is different. So, "Event201" will be dropped.

Closing the issue. Please let me know if you have additional questions.
