### ISSUE TITLE
EnterText is not working for Android Devices

### ISSUE THREAD

**Issue by girishkodupurath** [MicrosoftDocs/appcenter-docs#1274]
The entertext is not working in Android, tried the Invoke and setText as well its not working. The page doesn't talk about the same

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0807edfc-cec4-2b00-72cc-36508cd11a3d
* Version Independent ID: e796f545-f652-49d5-b629-88b87aba5b6f
* Content: [Working With - WebViews - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/features/webviews)
* Content Source: [docs/test-cloud/frameworks/uitest/features/webviews.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/features/webviews.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
