### ISSUE TITLE
Where is the link?

### ISSUE THREAD

**Issue by iniprocjoe** [MicrosoftDocs/appcenter-docs#1276]
There should be a link to the log monitor here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b54905c-48c1-06be-2676-c1ca8a9463f2
* Version Independent ID: 56586cc1-d598-9f6b-8cda-a3359ed56e4f
* Content: [Understanding the App Center Log Flow Page - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/log-flow)
* Content Source: [docs/analytics/log-flow.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/log-flow.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-analytics**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @iniprocjoe 

Thanks for reaching out to us!

The "Log flow" page is inside the "Analytics" section on the Portal. Link is specific to your app and looks like this: `https://appcenter.ms/users/<user-name>/apps/<app-name>/analytics/log-flow`

<img width="1045" alt="Screenshot 2021-08-13 at 00 56 49" src="https://user-images.githubusercontent.com/536497/129275274-734cbf65-87d8-455c-98c8-933086586a4d.png">

Let me know if you have additional questions.
