### ISSUE TITLE
Find the following line of code, which sets the source URL for bridge for production releases:

### ISSUE THREAD

**Issue by DanielWFrancis** [MicrosoftDocs/appcenter-docs#1281]
"source URL for bridge for production releases" doesn't sound like it makes sense. And I don't have this line in my AppDelegate.m file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b2c451f-f6df-655c-abaf-60bcf150e478
* Version Independent ID: 9659d8a9-1b8d-a81b-65e9-c04b0ee1abd8
* Content: [Get Started with the React Native Client SDK - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started)
* Content Source: [docs/distribution/codepush/rn-get-started.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/rn-get-started.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by lucen-ms** [comment]
@DanielWFrancis thank you for your suggestion but we believe the documentation is correct. If you cannot find the line, please contact our support: https://docs.microsoft.com/en-us/appcenter/help with repro steps. Thank you.
