### ISSUE TITLE
Explain the approach of splitting production and non-production analytics

### ISSUE THREAD

**Issue by Juriyx** [MicrosoftDocs/appcenter-docs#1286]
I want to split production and non-production analytics. What is the official recommended way of doing that?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d0fe9f-178c-2b98-f02d-ae2f0918abbe
* Version Independent ID: 76aa6f90-1025-405e-715c-bf00ac545a78
* Content: [App Center Analytics Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/faq)
* Content Source: [docs/analytics/faq.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/faq.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-analytics**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by mizevkon** [comment]
Hello @Juriyx, thanks for reaching out.
There are 2 ways you could achieve this:
1. Add suffixes (or prefixes) for your non-prod versions, like "0.1-beta" or "0.3.2-WIP" and then filter by this on Analytics page.
2. Use separate AppId (secret) for production and non-production applications

Hope it helps!

**Comment by DmitriyKirakosyan** [comment]
I'm closing the issue. Please feel free to reopen if you have additional questions.
