### ISSUE TITLE
A new organization will be created??

### ISSUE THREAD

**Issue by DevAlien** [MicrosoftDocs/appcenter-docs#129]
Why that? We had everything configured already, and we are shipping the app already with the other organization, why we have to configure everything again just for this? It does not make sense that I have to change all the keys inside the project, lose all the data we had already and everything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de5a7b9-2742-0ea0-3170-d6fb5da0d2de
* Version Independent ID: f24ff5eb-4fb5-7a96-ff76-6c96386c9498
* Content: [Connecting Repositories Using the GitHub App - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/github-app)
* Content Source: [docs/build/github-app.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/github-app.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by jwargo** [comment]
@DevAlien The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
