### ISSUE TITLE
How can I configure local AppCenter directory

### ISSUE THREAD

**Issue by IndexOutOfLimit** [MicrosoftDocs/appcenter-docs#1290]
I want to configure the local AppCenter directory but didn't see any option there. When I looked the SDK code it is configured as below for UWP:
global::Windows.Storage.ApplicationData.Current.LocalFolder.Path.

Is there any way to configure this path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d0fe9f-178c-2b98-f02d-ae2f0918abbe
* Version Independent ID: 76aa6f90-1025-405e-715c-bf00ac545a78
* Content: [App Center Analytics Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/faq)
* Content Source: [docs/analytics/faq.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/faq.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-analytics**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
The DotNet App Center SDK doesn't have an API for customizing the App Center directory. We have a similar feature request for it. You can track it [here](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1409). I am closing this issue but feel free to reopen it if you will have additional questions.

**Comment by Petry33** [comment]
Ok thank you very much

joi, 14 oct. 2021, 09:49 Anastasia Senyushina ***@***.***> a
scris:
