### ISSUE TITLE
Issue when using the Android Distribute SDK with Android targetSdkVersion 31

### ISSUE THREAD

**Issue by pratimagauns** [MicrosoftDocs/appcenter-docs#1297]
Using AppCenter Distribute SDK - 4.1.0

As per Google Docs, 

**Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. 
See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.**

I have updated my app to target Android 12. Since I have AppCenter Distribute SDK dependency included, I get gradle build errors. On analyzing I noticed that AppCenter Distribute SDK have ``DeepLinkActivity`` Activity with intent-filter tag without `android:exported` property explicitly set.

```
 <activity
            android:name="com.microsoft.appcenter.distribute.DeepLinkActivity"
            android:theme="@android:style/Theme.NoDisplay" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="updates"
                    android:path="/"
                    android:scheme="appcenter" />
            </intent-filter>
 </activity>
```

Please update the above property to allow using this SDK dependency in app targeting Android 12.

Let me know if any more info is needed.

**Comment by AnastasiaKubova** [comment]
This issue was fixed in the [4.2.0](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.2.0)  version of App Center SDK. Please update the App Center SDK dependency to the [latest](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.3.1) version and try again. 
I'm closing this issue but feel free to reopen it if this issue still persists.
