### ISSUE TITLE
Note on Xcode 12 and iOS 14 is outdated

### ISSUE THREAD

**Issue by philipphofmann** [MicrosoftDocs/appcenter-docs#1298]
The note on `Xcode 12 and iOS 14 are available now!` seems outdated or obsolete. I think it should state that Xcode 13 and iOS 15 are available now.

<img width="875" alt="Screen Shot 2021-11-04 at 09 27 48" src="https://user-images.githubusercontent.com/2443292/140281537-8bb2ad43-3429-4120-a3ae-4b13ad6be128.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c68ff8e7-e2ab-9335-6cc1-68d1d3765d6e
* Version Independent ID: a087c437-3e69-d420-a6e4-6fffa7611882
* Content: [Preparing XCUITest Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/xcuitest/)
* Content Source: [docs/test-cloud/frameworks/xcuitest/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/xcuitest/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
The mentioned `Note` was removed. Closing.
