### ISSUE TITLE
[Test - Espresso] Preparing for Upload guide: Add clarification about modifications to the build system

### ISSUE THREAD

**Issue by King-of-Spades** [MicrosoftDocs/appcenter-docs#13]
# Overview
https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/espresso.md#1-changes-to-the-build-system

# Description
I think two items are potentially confusing here:
#### 1) It's not very clear that the user needs to look at different build.gradle files for the settings they're applying:
> Make sure you have a jcenter() entry in the `build.gradle` in your project root directory:
vs.
> Add the following dependency in your app module's `build.gradle` file:

The proximity of these two items misled me for awhile into thinking I was to apply both changes to the same `build.gradle` file. One possible way to make this clearer is to add emphasis to what the actual hint names of the files are. For example, in my project, it looks like the format is:

- build.gradle (Project: projectname)
- build.gradle (Module: app)

It would be good if someone could confirm that format is consistently what should be expected in an app; or if there's some other aspect that varies. ("projectname" looks like it varies based on the actual name of the project, but I think the rest is still displayed as normal.)

#### 2) Starting with Gradle 3.0, androidTestCompile is deprecated and you should use androidTestImplementation instead.

I think it's a bit confusing whether the only change the user should be making in this scenario is to change `androidTestCompile('com.microsoft.appcenter:espresso-test-extension:1.2')` to `androidTestImplementation('com.microsoft.appcenter:espresso-test-extension:1.2')` renaming the method but passing in the same argument...or if the user actually needs to modify the element in some additional way.

**Comment by dipree** [comment]
Seems like it's Test docs. Assigning to @glennwester
