### ISSUE TITLE
Deleting an app

### ISSUE THREAD

**Issue by eimantas** [MicrosoftDocs/appcenter-docs#130]
I couldn't find a button to delete an app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0087c543-d8f4-5ea6-5ac6-8b30ec1b9e6c
* Version Independent ID: 92b8f8de-268b-a249-46e9-053edf2e97c0
* Content: [App Center Operating System/Platform Services Matrix - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix)
* Content Source: [docs/general/platform-service-matrix.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/platform-service-matrix.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@eimantas The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jwargo** [comment]
@eimantas you can find instructions on how to delete at app here: https://intercom.help/appcenter/general-questions/how-can-i-delete-an-app-in-app-center
