### ISSUE TITLE
Consider adding proper secret management for App Center secrets

### ISSUE THREAD

**Issue by gavination** [MicrosoftDocs/appcenter-docs#1300]
The page definitely tells the user where to enter their secrets to enable App Center support for their apps, but there's nothing mentioning a potential "best practice" to secure their secrets and reference them in the actual method call. This would dissuade the potential possibility of a developer checking secrets into their source code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72f6fe-74d6-696e-e709-5f6d577c0a58
* Version Independent ID: b3d0ea8b-5a1f-bf71-7dc2-9685cf23c00b
* Content: [Get Started with Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin)
* Content Source: [docs/sdk/getting-started/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/xamarin.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! Please follow the guide about [protecting the App Center secret value](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/xamarin#protect-the-app-center-secret-value).
I am closing this issue but feel free to reopen it if you will have additional questions.
