### ISSUE TITLE
Examples section of "Invoking JavaScript" is there but empty

### ISSUE THREAD

**Issue by MaxFmi** [MicrosoftDocs/appcenter-docs#1301]
See image. The last section "Examples" says "This section will cover some common use cases that may be found when writing Calabash tests involving webviews."

![Screenshot 2021-11-08 at 08 50 22](https://user-images.githubusercontent.com/61872738/140703503-109ee310-75c2-4ce0-8bbb-fc5a0db68c72.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0807edfc-cec4-2b00-72cc-36508cd11a3d
* Version Independent ID: e796f545-f652-49d5-b629-88b87aba5b6f
* Content: [Working With - WebViews - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/features/webviews)
* Content Source: [docs/test-cloud/frameworks/uitest/features/webviews.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/features/webviews.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
