### ISSUE TITLE
"InvokeJS on iOS" doesn't work  as explained

### ISSUE THREAD

**Issue by MaxFmi** [MicrosoftDocs/appcenter-docs#1303]
InvokeJS on Android works as described and expected.
App.Query(x => x.WebView().InvokeJS("any JavaScrip command"));

Invoking the same command under iOS results in doing nothing and just stepping over the execution.
App.Query(x => x.WebView().InvokeJS("any JavaScrip command"));

In my case I tried to scroll to a specific element by id
"document.getElementById('any_id').scrollIntoView(true)";

Original documentation
https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/features/webviews#invokejs-on-ios

FYI:
I've found some posts but they weren't very helpful. They just confused me even more. Would be great if the original documentation would describe how to use it insimple steps.

PS: The Example section is empty. https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/features/webviews#examples -> https://github.com/MicrosoftDocs/appcenter-docs/issues/1301

Workaround:
I don't know any yet. If anyone knows a solution or have a work-around, please let me know.

Thanks for your effort.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0807edfc-cec4-2b00-72cc-36508cd11a3d
* Version Independent ID: e796f545-f652-49d5-b629-88b87aba5b6f
* Content: [Working With - WebViews - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/features/webviews)
* Content Source: [docs/test-cloud/frameworks/uitest/features/webviews.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/features/webviews.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
