### ISSUE TITLE
App center test center with Appium

### ISSUE THREAD

**Issue by iparry7979** [MicrosoftDocs/appcenter-docs#1305]
This doco suggests that App Center Test supports Appium with Java (JUnit). Is it possible to use the Test Centre if you have Appium with tests written in C# (MSTest)?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0a8ff9f-6c1c-80ef-eab0-335b6e9e3bf7
* Version Independent ID: 1c0db36f-ad7b-a4b1-23cf-baca276cac1e
* Content: [Supported Test Frameworks - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/)
* Content Source: [docs/test-cloud/frameworks/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
