### ISSUE TITLE
Upload API

### ISSUE THREAD

**Issue by bikemike** [MicrosoftDocs/appcenter-docs#1306]
What happened to the upload API? It seems some breaking changes were made to the API and now my upload script is now broken. Were these changes communicated in some way?

The documentation still refers to getting an upload_url which doesn't seem to exist in the new API.

`Create an upload resource and get an upload_url (good for 24 hours)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Distribute a build via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by mizevkon** [comment]
Hello @bikemike,
Could you please specify which part of API seems to be broken? I have tested the flow described in [docs](https://docs.microsoft.com/en-us/appcenter/distribution/uploading) for steps 1-5 and was able to upload the file

**Comment by bikemike** [comment]
I'm not saying the API is broken, I'm saying my upload script broke because the upload API was changed in a way that is not backwards compatible.

The documentation, however, hasn't fully been updated and still has wording that was only valid for the old API:


```
Upload New Release
Upload a new release using these sequential API calls:

Create an upload resource and get an upload_url (good for 24 hours): The endpoint to call is POST /v0.1/apps/{owner_name}/{app_name}/uploads/releases
```

The API no longer returns an upload_url.

**Comment by mizevkon** [comment]
Now I see your point @bikemike. We will update the documentation accordingly to the changes. It is a pity that it has affected your script, however I can recommend to check [this example](https://github.com/microsoft/appcenter-Xamarin.UITest-Demo/blob/main/ac-distribute.sh) so it could be aligned with current API. Apologies for this.

**Comment by mizevkon** [comment]
Hello @bikemike, we have updated [documentation](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#upload-new-release) accordingly. Thanks for finding it out and have a good day!
