### ISSUE TITLE
Page is badly linked

### ISSUE THREAD

**Issue by chao-master** [MicrosoftDocs/appcenter-docs#131]
The [testing on devices](https://developer.xamarin.com/guides/testcloud/testing-on-devices/) links here under "Testing on local devices" Which this page no contains no information on

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b26380a-c6b6-31d8-3367-f156d9e11910
* Version Independent ID: 861c727f-76cd-ac8e-daa5-57b0db01c2e0
* Content: [Test Cloud Migration Guide - Visual Studio App Center](https://docs.microsoft.com/en-gb/appcenter/migration/test-cloud/)
* Content Source: [docs/migration/test-cloud/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/migration/test-cloud/index.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by glennwester** [comment]
Hi @chao-master, 

Thanks for making us aware! We have a fix underway.
