### ISSUE TITLE
API error during update the upload resource's status to uploadFinished

### ISSUE THREAD

**Issue by MMLino** [MicrosoftDocs/appcenter-docs#1311]
[Enter feedback here]
I followed all the steps described into the https://docs.microsoft.com/en-us/appcenter/distribution/uploading#upload-new-release to release a new package version into appcenter but during the upload resource's status to uploadFinished I received this error:
`{"code":"not_found","message":"Error: upload with id 08cfec70-1264-4def-84f6-ca7eb01f7e88 not found"}`

I send this request:
`curl -X PATCH https://api.appcenter.ms/v0.1/apps/<USER_APPCENTER>/<APPNAME_APPCENTER>/uploads/releases/**<UPLOAD_ID>** -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-API-Token: <TOKEN_APPCENTER> -d '{"upload_status": "uploadFinished"}`

The <UPLOAD_ID> was retrieved from the step 2. of https://docs.microsoft.com/en-us/appcenter/distribution/uploading#upload-new-release
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Distribute a build via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by celio-neto** [comment]
The tutorial is wrong the UPLOAD_ID from step 2 is not the correct ID. You should use the first ID you got from the first call. That should do the trick. It took me a while and going back and forth on the code to figure this one out.

**Comment by MMLino** [comment]
@celio-neto Thank you for the suggestion.
I solved the issue using the ID from the first step response.
