### ISSUE TITLE
Choose iOS or Android as OS option for React Native app on AppCenter

### ISSUE THREAD

**Issue by charity-detalytics** [MicrosoftDocs/appcenter-docs#1324]
Should I choose iOS, Android or create 2 separate apps for React Native?
<img width="563" alt="Screen Shot 2022-01-10 at 17 32 05" src="https://user-images.githubusercontent.com/63986409/148751743-b47c8903-e791-4288-aa5a-099ce923fcd9.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by CyberMew** [comment]
I think it should be separate?
Edit: nvm issue has been closed

**Comment by charity-detalytics** [comment]
@CyberMew Thanks for your comment!
It mentions here https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started

> As with all other React Native plugins, the integration experience is different for iOS and Android, so follow the setup steps depending on the platform(s) you target for your app. Note, if you're targeting both platforms it's recommended to create separate CodePush applications for each platform.
