### ISSUE TITLE
flutter support

### ISSUE THREAD

**Issue by wiltwitt** [MicrosoftDocs/appcenter-docs#133]
I am using Flutter dev environment.  Does App Center support Flutter.io apps? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 513760ea-3340-4d6c-7566-13f39e691681
* Version Independent ID: e39b0e88-0d00-4a3b-6a32-1999231e0e50
* Content: [App Center Analytics for Apache Cordova - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/cordova)
* Content Source: [docs/sdk/analytics/cordova.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/cordova.md)
* Service: **vs-appcenter**
* GitHub Login: @ruslan-bikkinin
* Microsoft Alias: **v-rubikk**

**Comment by wiltwitt** [comment]
I use azure backend by the way

**Comment by jwargo** [comment]
@wiltwitt The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
