### ISSUE TITLE
xcrun instruments -s devices doesn't return a list of simulators

### ISSUE THREAD

**Issue by biozal** [MicrosoftDocs/appcenter-docs#1336]
In the directions it states to use:

xcrun instruments -s devices 

but on my Mac this doesn't return a list of simulators instead I get:
❯ xcrun instruments -s devices
xcrun: error: sh -c '/Applications/Xcode-13.2.0.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode-13.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find instruments 2> /dev/null' failed with exit code 17664: (null) (errno=Invalid argument)
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

If I run this, however, I do get a list of simulators:
xcrun simctl list

I believe the documentation needs to be updated.

Thanks,
Aaron

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 192e3c97-ef59-1232-dfb0-65f77a8f960c
* Version Independent ID: 1794e724-d580-1d90-188d-6d2885bedc2f
* Content: [Local testing with iOS Simulators - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/ios/simulator?tabs=vswin)
* Content Source: [docs/test-cloud/frameworks/uitest/ios/simulator.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/ios/simulator.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by Priskorn** [comment]
Thanks for letting us know 
Fixed now
