### ISSUE TITLE
Menu descriptions seem out of date for VS Mac

### ISSUE THREAD

**Issue by SmatchyLaPaglia** [MicrosoftDocs/appcenter-docs#1337]
"Select View > Pads > Unit Tests to display the Unit Test pad. Expand UsingUITest > UsingUITest.UITests > Test Apps"

There is no "Pads" choice anymore, and I can see no obvious "Test Apps" area.

I could be dumb and missing something but I can't figure out how to follow these instructions.

**Comment by Priskorn** [comment]
Thanks for letting us know about outdated instructions 
Should be up to date now
