### ISSUE TITLE
Link to Espresso docs broken

### ISSUE THREAD

**Issue by charliealbright** [MicrosoftDocs/appcenter-docs#1348]
The external link to Espresso documentation is broken on this page. 

Current link: https://developer.android.com/training/testing/ui-testing/espresso-testing.html

Screenshot of current broken link:
![Screenshot 2022-03-24 101158](https://user-images.githubusercontent.com/5331378/159948292-6f5962a5-52cf-4717-95b0-30e6c6e181d1.png)

Suggested replacement: https://developer.android.com/training/testing/espresso

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d8bdce-a2ad-80cb-efdb-74c0bb3ebb8c
* Version Independent ID: b8d0b4a7-a6b0-42d6-aab3-58a9d8681502
* Content: [Preparing Espresso Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/espresso/)
* Content Source: [docs/test-cloud/frameworks/espresso/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/espresso/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by Priskorn** [comment]
I see it was fixed 
thanks
