### ISSUE TITLE
You start by adding the App Center Test task to your build definition.

### ISSUE THREAD

**Issue by PulkitSethi1984** [MicrosoftDocs/appcenter-docs#135]
Is there any explanation for this 'You start by adding the App Center Test task to your build definition.'? What kind of novice has written this blog? This is really appalling. Please give proper demonstration. No use going round and round between Xamarin and Microsoft blogs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7bab69-cfac-aefa-3ec0-b61d1dc3bf4f
* Version Independent ID: 73c4d2ba-d784-074c-6117-e81a4e0ae059
* Content: [Using Team Services for UI Testing - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/vsts-plugin#vsts-general-setup)
* Content Source: [docs/test-cloud/vsts-plugin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/vsts-plugin.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by jwargo** [comment]
@PulkitSethi1984 We're happy to accept constructive criticism of the docs in this forum. If you have suggestions on how to make the docs better, please provide them.

**Comment by PulkitSethi1984** [comment]
Just better explain 'You start by adding the App center test task to your
build definitions'

**Comment by jwargo** [comment]
@PulkitSethi1984 We do, starting here: [https://docs.microsoft.com/en-us/appcenter/test-cloud/getting-started](https://docs.microsoft.com/en-us/appcenter/test-cloud/getting-started). The writer rightfully focuses on the VSTS specific features and settings and lets the remainder of the Test docs describe everything else you need.

**Comment by PulkitSethi1984** [comment]
That is all I was saying, you will redirect to test cloud docs, and they
will to app center. No body has expalined how to add test task to build
definition. Let me enlighten you
Read this and then try to understand what you guys are missing
* https://tomsoderling.github.io/AppCenter-Automated-UI-tests-on-build/
<https://tomsoderling.github.io/AppCenter-Automated-UI-tests-on-build/>*

*Kindly read the blog well, before replying*

**Comment by jwargo** [comment]
@PulkitSethi1984 thank you very much for your feedback, we will try to make this more clear.

**Comment by PulkitSethi1984** [comment]
Thanks
