### ISSUE TITLE
Missing number four

### ISSUE THREAD

**Issue by LuanPham97** [MicrosoftDocs/appcenter-docs#1364]
It's missing number four.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e799e45-8feb-d74c-4e25-3bdf49301766
* Version Independent ID: b6aef403-76f7-5df2-aa5d-3ed66397893d
* Content: [Get Started with WPF/WinForms - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms)
* Content Source: [docs/sdk/getting-started/wpf-winforms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/wpf-winforms.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by LuanPham97** [comment]
let me quick edit

**Comment by lucen-ms** [comment]
Thank you @LuanPham97 - I've merged your PR.
