### ISSUE TITLE
TestNG support

### ISSUE THREAD

**Issue by pramodKarande** [MicrosoftDocs/appcenter-docs#1368]
Currently, as per the documentation, there is no support for TestNG.
Is there any future plan to support TestNG?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a93e3805-5fd5-c6c9-f25d-1be5c41ed77f
* Version Independent ID: 9826c974-24a2-b65e-9603-14428f6bb5bc
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/appium/)
* Content Source: [docs/test-cloud/frameworks/appium/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/appium/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by AnatolyPristensky** [comment]
Hello @pramodKarande and thank you for getting in touch with us. 
Unfortunately we have no plans for support TestNG in the nearest future.
