### ISSUE TITLE
Getting different version of maven-surefire-plugin in logs

### ISSUE THREAD

**Issue by pramodKarande** [MicrosoftDocs/appcenter-docs#1372]
Hi team,
I am executing my maven test on App center and In logs, I have noticed that a different version of maven-surefire-plugin getting used for execution, different from the one which I have added in my pom.xml

refer below image
<img width="920" alt="Screenshot 2022-07-15 at 7 31 15 PM" src="https://user-images.githubusercontent.com/47946801/179238952-e04c7c0c-a0b8-460a-93e6-92aa5bb9d126.png">

pom.xml
<img width="754" alt="Screenshot 2022-07-15 at 7 33 48 PM" src="https://user-images.githubusercontent.com/47946801/179239442-21099461-163e-48c1-b228-41df60cecba6.png">

listeners which I have mentioned here are getting skipped on appcenter execution but they are working for local execution.
can anyone help me with this?

**Comment by pramodKarande** [comment]
I tried messaging my queries via the 'Contact Support' option multiple times but never got any reply.
the support option is still functioning?

**Comment by DmitriyKirakosyan** [comment]
Hi @pramodKarande , thank you for reaching out! We will check this issue and get back with updates.
As for the `Contact Support`, it is functioning. I'll sync with the support team and check if we missed any of your messages.

**Comment by DmitriyKirakosyan** [comment]
@pramodKarande , The support team said they replied to you. They found conversations with you on June 23 and July 15, but you didn't respond on these conversations. Could you please ensure if you check the email address you used to report from?

**Comment by pramodKarande** [comment]
I have reported issues using my corporate email id but never got any response.  (can you please check for this email?)
I have used the below portal from the App center
<img width="611" alt="Screenshot 2022-07-21 at 3 20 17 PM" src="https://user-images.githubusercontent.com/47946801/180185088-6fd4defe-3cef-42a4-a11b-d1c6435512be.png">

**Comment by DmitriyKirakosyan** [comment]
Yes, this was the email we received your report from. Please check your spam, the email should come from `@app-center.intercom-mail.com`.
If no email even in spam or junk, then check with your admin team to see if they are blocking any email coming from domain `@app-center.intercom-mail.com`.

**Comment by pramodKarande** [comment]
Thanks for confirming.. will check with the admin team.

**Comment by AlexeyBudynkov** [comment]
I think we should close this ticket, because the conversation moved to intercom

**Comment by pramodKarande** [comment]
nope
It is still open
I am not able to receive emails from `@app-center.intercom-mail.com` yet

for now, Plz provide the solution on this thread only

**Comment by pramodKarande** [comment]
@AlexeyBudynkov could you please reopen the issue?

**Comment by DmitriyKirakosyan** [comment]
Hi @pragarwa , have you checked with your Admin team if you have any firewall or anything that could block the domain of our support team?

Meanwhile, I'll ask our support team to take a look at this github thread and reply here if possible.

**Comment by pramodKarande** [comment]
Hi @DmitriyKirakosyan, I have already reported this email-related issue to my Admin team.. but it is not resolved yet.

**Comment by ankasani** [comment]
@pramodKarande , This is Anvesh from the support team, I have pinged you over the Microsoft team, lets continue there. Will close this thread!
