### ISSUE TITLE
Incorrect information on page about automating date/time pickers.

### ISSUE THREAD

**Issue by SittenSpynne** [MicrosoftDocs/appcenter-docs#1373]
The code on this page doesn't work in current iOS or Xamarin. Sites like https://intercom.help/appcenter/en/articles/2435221-controlling-datepickers-in-xamarin-forms-apps-with-xamarin-uitest-on-ios have information about an alternative that works. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465e759c-e3d6-d9d6-5a45-e15e8b9156ef
* Version Independent ID: bb77c744-4cb8-49b9-7f00-b42664e5cb2f
* Content: [Automating Xamarin.Forms Date & Time Pickers with Xamarin.UITest - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/features/date-time-pickers)
* Content Source: [docs/test-cloud/frameworks/uitest/features/date-time-pickers.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/features/date-time-pickers.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @SittenSpynne , you are right, this approach doesn't work anymore. We will need to update the doc.
Please use the workaround from the article you mentioned.

**Comment by thewulf7** [comment]
Closing issue as its fixed
