### ISSUE TITLE
Wording error

### ISSUE THREAD

**Issue by Sarah-Godfrey** [MicrosoftDocs/appcenter-docs#1374]
[Enter feedback here]
Update: Adding your device
3. In the Phone's Settings, select General, **VPN** & Device Management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811f9eee-5b17-06e1-c108-dbef47984425
* Version Independent ID: 8fe50e13-c934-6a43-bf7d-1f33946da9d3
* Content: [Testing iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios)
* Content Source: [docs/distribution/testers/testing-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-ios.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @Sarah-Godfrey , thank you for reporting this issue! We will update the docs.
