### ISSUE TITLE
AppSecret in Info.plist?

### ISSUE THREAD

**Issue by below** [MicrosoftDocs/appcenter-docs#1376]
"Under URL Schemes > Item 0, change the value to appcenter-{APP_SECRET} and replace {APP_SECRET} with the App Secret of your app."

To my knowledge, the Info.plist is public and easily inspectable. Is the APP_SECRET really a secret? If so, then putting it into Info.plist seems like a bad idea. If not, it probably should not be called "secret".

Could you clarify this?

**Comment by aleksandr-dorofeev** [comment]
Hello @below 
`APP_SECRET` isn't a really secret.
It is an identifier of your app and it can not be used to retrieve or edit existing data.
More information you can find in the [documentation](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/ios#protect-the-app-center-secret-value).

**Comment by below** [comment]
Thank you @aleksandr-dorofeev ! If I may add a follow-up: If I plan to release my app as open source, it is probably not a good idea to publish the token there, is it? Or does the API also use the bundle identifier, which of course would be different for third party builds of the app?

**Comment by aleksandr-dorofeev** [comment]
Yes, it's really not best practice to keep a secret in an open source project. You can try using CI to inject the secret into your project.
