### ISSUE TITLE
What protocols and ports do the servers use?

### ISSUE THREAD

**Issue by th-anguyen** [MicrosoftDocs/appcenter-docs#1378]
We are a large organization and simply cannot whitelist all protocols and ports for an IP or URL, due to security.

Can you provide the protocols and ports used for AppCenter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7ce797b-ea45-8a51-d25f-fc9665d42205
* Version Independent ID: 0c4c8b1e-7df0-e823-3461-e6379fff1895
* Content: [App Center Connections to allow list - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/allowlist)
* Content Source: [docs/general/allowlist.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/allowlist.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by AlexeyBudynkov** [comment]
Hello. This is the only information we can share about it [Download Azure IP Ranges and Service Tags – Public Cloud from Official Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=56519)

**Comment by whirlwin** [comment]
Whitelisting all Azure IP ranges is not a solution especially not into an internal tool, such as GitHub. This is basic lack of network security.

It is just as safe as deciding you don't let burglars into your house unless they wear blue shoes.
