### ISSUE TITLE
Dead link https://engineering.appcenter.ms/tables-identity-direct-access-a0a97f69b050

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/appcenter-docs#138]
Found in docs/azure//index.md
Maybe this in an MS internal-only link, but isn't publicly accessible

**Comment by jwargo** [comment]
@nschonni this link isn't in the App Center docs - it'll have to be fixed by the Azure docs team.

**Comment by jwargo** [comment]
oh, sorry, I see it now.

**Comment by jwargo** [comment]
Fixed
