### ISSUE TITLE
Google Play Store Vulnerability

### ISSUE THREAD

**Issue by InternationalTyres** [MicrosoftDocs/appcenter-docs#1380]
Hi,

I've followed the instructions to get my build to be approved by Google to the Play Store with the App Center Distribute package, the section here:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d269a0-0b09-c2f6-d37a-319831bcf782
* Version Independent ID: f2c17a3a-87bb-0c75-9efb-de6ffb6f7738
* Content: [App Center Distribute for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#remove-in-app-updates-for-google-play-builds)
* Content Source: [docs/sdk/distribute/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/xamarin.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @InternationalTyres , could you elaborate on this issue please? What is the question exactly?

**Comment by DmitriyKirakosyan** [comment]
Closing for now. Let me know if the issue persists.
