### ISSUE TITLE
Deleting User's Analytics Data?

### ISSUE THREAD

**Issue by BlueSpiritbox** [MicrosoftDocs/appcenter-docs#1381]
Hello,

I have a question regarding the deletion of a user's analytics data. There's a section under GDPR > Analytics > Delete [https://docs.microsoft.com/en-us/appcenter/gdpr/analytics-forget-me](https://docs.microsoft.com/en-us/appcenter/gdpr/analytics-forget-me), but all it's talking about is how to block incoming data. Is there a way to actually delete the data or is it the same thing?

Thanks!

**Comment by AnatolyPristensky** [comment]
Hello @BlueSpiritbox,
We have a retention rate of 28 days, so if you do not send any more data it will be deleted after this period.

**Comment by BlueSpiritbox** [comment]
> Hello @BlueSpiritbox, We have a retention rate of 28 days, so if you do not send any more data it will be deleted after this period.
Great! Thank you for the clarification
