### ISSUE TITLE
React-native integration doc could point to simple start functions as well

### ISSUE THREAD

**Issue by aureosouza** [MicrosoftDocs/appcenter-docs#1387]
We noticed that the documentation for [Android](https://github.com/MicrosoftDocs/appcenter-docs/blob/10cf5264f83015c2c5cf7f320f7ea2eca23f6334/docs/sdk/getting-started/android.md) and [iOS](https://github.com/MicrosoftDocs/appcenter-docs/blob/10cf5264f83015c2c5cf7f320f7ea2eca23f6334/docs/sdk/getting-started/ios.md) presents the possibilty of starting the services calling `start` functions that accept the `appSecret` as an argument. 

But this is not particularly true for the [React Native](https://github.com/MicrosoftDocs/appcenter-docs/blob/10cf5264f83015c2c5cf7f320f7ea2eca23f6334/docs/sdk/getting-started/react-native.md) doc, which expects the `AppCenter-Config.plist` and `appcenter-config.json` files to be added for each build flavor. This is an extra complexity when we have multiple build flavors configured in AppCenter. Or when we'd like to integrate with known solutions such as `react-native-config` which uses a [single source of truth](https://en.wikipedia.org/wiki/Single_source_of_truth) file for all build flavor specific configs. And in fact there's a few issues regarding app center opened there ([here](https://github.com/luggit/react-native-config/issues/282), [here](https://github.com/luggit/react-native-config/issues/601), and [here](https://github.com/luggit/react-native-config/issues/346)) and the workaround so far was to use pre-build to generate these files on the fly, which doesn't seem like an optimal solution.

The point is in fact we can call the native start functions with the appSecret in React Native integration as well. So if we have already a solution in place for build flavors configs, we could pass the appSecrets as argument using React Native in the same way as the regular Android and iOS documentation points out. I wrote a small post on this [here](https://medium.com/@aureosouza0801/integrate-appcenter-and-react-native-config-85d44b7a3d2).

So a possible suggestion could be to present this option in the React Native doc as well, in which it's not required necessarly to have multiple `AppCenter-Config.plist` and params in `appcenter-config.json`, but we could call the [Android start](https://github.com/MicrosoftDocs/appcenter-docs/blob/10cf5264f83015c2c5cf7f320f7ea2eca23f6334/docs/sdk/getting-started/android.md#41-add-the-start-method) on MainApplication and the [iOS start](https://github.com/MicrosoftDocs/appcenter-docs/blob/10cf5264f83015c2c5cf7f320f7ea2eca23f6334/docs/sdk/getting-started/ios.md#42-add-the-startwithservices-method) or [configure](https://github.com/MicrosoftDocs/appcenter-docs/blob/10cf5264f83015c2c5cf7f320f7ea2eca23f6334/docs/sdk/getting-started/includes/apple-configure-appcenter.md) in AppDelegate when integrating react native projects.

**Comment by MikhailSuendukov** [comment]
Hi @aureosouza thanks for contacting us, your suggestion makes sense to me, we will update our documentation.

**Comment by DmitriyKirakosyan** [comment]
The documentation is updated. Closing.
