### ISSUE TITLE
Dead link https://developer.apple.com/programs/ios/information/iOS_Program_Information_4_3_15.pdf

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/appcenter-docs#139]
Found in docs/distribution//codepush/cordova.md

**Comment by jwargo** [comment]
@Zakeelm can you please update this doc (and close the issue)?

**Comment by Zakeelm** [comment]
Fixed this and waiting on the PR to be merged. Going to go ahead and close this. Thanks for pointing this out!
