### ISSUE TITLE
Create API Token link is broken.

### ISSUE THREAD

**Issue by omatrot** [MicrosoftDocs/appcenter-docs#1393]
Create API Token link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11daca97-5587-17af-c377-6dfd93f14700
* Version Independent ID: 11daca97-5587-17af-c377-6dfd93f14700
* Content: [Export App Center Build configuration to Azure Pipelines - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/build/export-to-azure-pipelines)
* Content Source: [docs/build/export-to-azure-pipelines.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/export-to-azure-pipelines.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @akamenev
* Microsoft Alias: **ankamene**

**Comment by lucen-ms** [comment]
Thank you @omatrot, the link has been fixed.
