### ISSUE TITLE
Update latest SDK version

### ISSUE THREAD

**Issue by nosko** [MicrosoftDocs/appcenter-docs#1394]
Last version of the SDK is 5.0.0, not 4.1.0 as stated in docs, which can lead to error behaviour when used in production

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa9700f5-b9e0-dfe1-ddbc-b5a3231dde11
* Version Independent ID: 11728c80-1474-c1dc-caf0-2c6b6c44bbb3
* Content: [Get Started with Android - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/android)
* Content Source: [docs/sdk/getting-started/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/android.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by nosko** [comment]
https://github.com/MicrosoftDocs/appcenter-docs/compare/live...nosko:appcenter-docs:patch-1

**Comment by DmitriyKirakosyan** [comment]
Updated. Closing.
