### ISSUE TITLE
[Question] - is it possible to build using Github actions or Gitlab CI, but test using Appcenter?

### ISSUE THREAD

**Issue by dinbtechit** [MicrosoftDocs/appcenter-docs#1398]
[Question] - is it possible to build using Github actions or Gitlab CI, but test using Appcenter?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a947746f-ae22-69e1-83a5-b4c71e57faa9
* Version Independent ID: 1fe0b1a8-1562-3ec7-7973-ea76964e478e
* Content: [App Center Command-Line Interface (CLI) - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/cli/)
* Content Source: [docs/cli/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/cli/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by MikhailSuendukov** [comment]
Hi @dinbtechit and thanks for reaching us. You can run your tests from anywhere, here is the documentation to help you:
[Start a test run](https://learn.microsoft.com/en-us/appcenter/test-cloud/starting-a-test-run)
[Test reports](https://learn.microsoft.com/en-us/appcenter/test-cloud/test-reports)
I'm closing this issue, if you have any more questions on this topic, feel free to reopen it.
