### ISSUE TITLE
Xamarin.UI.Tests doesn't test properly before releasing

### ISSUE THREAD

**Issue by Viktor027** [MicrosoftDocs/appcenter-docs#1399]
Hi All.

I'm writing this compliant especially for them who are responsible for releasing cycle of Xamarin UI tests.
I'm starting with words that we really like this framework. It's friendly, easy and enough for our needs.

But previous several releases are total setbacks.
1) 3.2.7 - 3.2.9 impossible to run real iOS device (problem with clear cache. there is some topic on GitHub)
2) 4.0.0 - impossible to run start app. Local (Xamarin) problem appears from the scratch after calling ConfigureApp.Android

System.TypeInitializationException : The type initializer for 'Xamarin.UITest.ConfigureApp' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'Xamarin.UITest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

3) 4.0.1 - can't work with Repl() . When the console is opened it writes that "This is not the real repl - this is just a placeholder".
Screenshot() doesn't work, always return null.
maybe else some functions don't work I couldn't check them yet.

Conclusion:
1) Consider testing common functions properly before realises 
2) If you don't need this framework anymore than consider making it for open-source in order we solve problems which you solve not in a hurry 
3) This framework can be awesome if you elevate his priority in your daily tasks

**Comment by DmitriyKirakosyan** [comment]
Hi @Viktor027 , Thank you for reaching out and for the fair suggestion!

We will take your notes into account!
Closing.
