### ISSUE TITLE
Dead link https://www.visualstudio.com/en-us/features/release-management-vs.aspx

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/appcenter-docs#140]
Found in docs/distribution//codepush/vsts-extension.md
I couldn't figure out what docs repo is missing the redirect

**Comment by jwargo** [comment]
@Zakeelm will you please fix this link and close the issue?

**Comment by Zakeelm** [comment]
Fixed and waiting on the PR to be merged. Going to go ahead and close this. Thanks for pointing this out!
