### ISSUE TITLE
MAUI macOS support clarification

### ISSUE THREAD

**Issue by kdotdk** [MicrosoftDocs/appcenter-docs#1402]
Hi

Documentation writes:

> Supported platforms:
>    MAUI iOS
>     ...
>    .NET 6.0 macOS
> 

Does this imply:
- MAUI macOS is not supported?
- MAUI macOS will be supported later?
- MAUI macOS should use alternative app center?

Best Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72f6fe-74d6-696e-e709-5f6d577c0a58
* Version Independent ID: b3d0ea8b-5a1f-bf71-7dc2-9685cf23c00b
* Content: [Get Started with Xamarin - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin)
* Content Source: [docs/sdk/getting-started/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/xamarin.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @kdotdk , thank you for reaching out!

If I'm not mistaken, .net MAUI supports MacCatalyst only at this moment.
AppCenter SDK doesn't support it yet. You can track the progress in https://github.com/microsoft/appcenter-sdk-dotnet/issues/1702.

Closing as duplicate.
