### ISSUE TITLE
Retry frequency and post timeout is not mentioned

### ISSUE THREAD

**Issue by kasimier-vireq** [MicrosoftDocs/appcenter-docs#1406]
The retryFrequency and postTimeout parameters in e.g. WaitForElement are not mentioned.
Do those parameters have concrete default values (not null) by default? What are those default values locally and in AppCenter?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c48b923b-a582-17a3-94ca-084f6f109ade
* Version Independent ID: 813e276a-5098-b142-c8d4-f6fe1bb6548e
* Content: [Working with Timeouts - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/features/timeouts)
* Content Source: [docs/test-cloud/frameworks/uitest/features/timeouts.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/features/timeouts.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hi @kasimier-vireq , thank you for reaching out!

* `retryFrequency` - The time in milliseconds to wait before retrying the failed query call
  **Default**: 250
* `postTimeout` - The time in milliseconds to wait after the element has been found
  **Default**: 150

The default values are the same for local and AppCenter runs.
