### ISSUE TITLE
Request to add release process for zip file builds (e.g. simulator builds)

### ISSUE THREAD

**Issue by jayshah123** [MicrosoftDocs/appcenter-docs#1407]
The docs do not specify any way to host `.app`/`.zip` files which might be used by developers to use in their simulators.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5abd09b-056f-1144-fb8d-ed2515468001
* Version Independent ID: d47b7918-5b9f-0ab9-a634-a245d6ff0280
* Content: [Distribution FAQ - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/distribution/faq)
* Content Source: [docs/distribution/faq.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/faq.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by lucen-ms** [comment]
@jayshah123 list of supported extensions are stated in the dialog when you create new release and on https://learn.microsoft.com/en-us/appcenter/distribution/uploading

If you want to add a new feature, please create a ticket in product repository https://github.com/Microsoft/appcenter
This one is only for changes in documentation.
