### ISSUE TITLE
Symbolication changes from iOS 16 - no documentation?

### ISSUE THREAD

**Issue by az-oolloow** [MicrosoftDocs/appcenter-docs#1408]
It seems that with bitcode being discontinued by Apple AppCenter stopped symbolicating all the Apple's frameworks symbols.

e.g. we have a recurring issue which is not in our code and with Xcode 13/iOS 15 SDK the symbolication worked:

![image](https://user-images.githubusercontent.com/47766072/211712706-5f32f333-a869-4c8b-8ead-2cb45a20cdf4.png)

But now with iOS 16 SDK the same issue looks like this:

![image](https://user-images.githubusercontent.com/47766072/211712775-fa87ed75-4b4f-4018-a24f-3c89c8dea411.png)

There is nothing in the documentation about this change in behaviour?

**Comment by DmitriyKirakosyan** [comment]
Hello @az-oolloow, thank you for reaching out!
Please [contact support team](https://learn.microsoft.com/en-us/appcenter/help) with this issue.

Since it's not related to the docs, I'm closing it.
