### ISSUE TITLE
Add section for App Store Encryption Export Regulations

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#1409]
Apple developers must affirm whether their app uses encryption when submitting their app to the App Store **_"—including any third-party libraries it links against—"_**.

> Typically, the use of encryption that’s built into the operating system—for example, when your app makes HTTPS connections using [URLSession](https://developer.apple.com/documentation/foundation/urlsession)—is exempt from export documentation upload requirements, whereas the use of proprietary encryption is not. To determine whether your use of encryption is considered exempt, see [Determine your export compliance requirements](https://help.apple.com/app-store-connect/#/dev63c95e436).

Source: [Apple Developer - Article - Complying with Encryption Export Regulations](https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations)

Can a section be added to the documentation that provides the affirmation to comply with the App Store Encryption Export Regulations for app developers that link the AppCenter SDK(s) in their apps please?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c043814c-66b5-4656-087e-0cbcab8d2d27
* Version Independent ID: 4edd3772-2eab-083c-2756-27266fce999d
* Content: [Visual Studio App Center Security and Compliance - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/general/app-center-security)
* Content Source: [docs/general/app-center-security.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/app-center-security.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
Hello @antonys1 , thank you for reaching out!

We only use Apple's OS built-in encryption [CommonCryptor](https://opensource.apple.com/source/CommonCrypto/CommonCrypto-60061/include/CommonCryptor.h.auto.html), and save the encrypted file into the App's folder. The encrypted data is saved within an event and error logs until it can be sent over the internet. Before sending over the internet it gets decrypted and then it is sent over the internet with https request using NSURLSession.

Note, the only thing which gets encrypted is a transmission token, see:
https://github.com/microsoft/appcenter-sdk-apple/blob/2214f9ee2476f28af64cb38359defe59e85197a1/AppCenterCrashes/AppCenterCrashes/MSACCrashes.mm#L579
https://github.com/microsoft/appcenter-sdk-apple/blob/2214f9ee2476f28af64cb38359defe59e85197a1/AppCenter/AppCenter/Internals/Storage/MSACLogDBStorage.m#L73

The transmission target API is not documented and thus isn't officially supported. I believe you don't use this API. In such case, encryption is not happening on the AppCenter SDK side.

If you are not sure if you should specify if your app is using encryption I recommend you to reach out to Apple support team and consult on your specific case.

**Comment by ghost** [comment]
Thank you @DmitriyKirakosyan.
