### ISSUE TITLE
Dead link https://google.github.io/android-testing-support-library/docs/espresso/

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/appcenter-docs#142]
The library project appears to have been renamed/moved to https://github.com/android/android-test but I'm not sure about the Expresso part.
Link found in docs/test-cloud//supported-frameworks.md

**Comment by jwargo** [comment]
@glennwester can you please fix this link then close the issue?

**Comment by glennwester** [comment]
Thanks for reporting @nschonni, I'll get this fix in today.

**Comment by glennwester** [comment]
This has been fixed.
