### ISSUE TITLE
APK chunk size issue

### ISSUE THREAD

**Issue by Vibinreji** [MicrosoftDocs/appcenter-docs#1427]
Hi, I am trying to upload apk to app center via API using gradle script.I am getting an error while uploading chunk

**{"error":true,"chunk_num":1,"error_code":"InvalidLength","message":"Invalid chunk length. ChunkNumber: 3 Expected: 4194304 Actual: 978056"}**

APK size will change for every project So how can be all the chunk would be same size which is 4194304.

My Actual APK size is 13560968,after splitting into 4 chunks,three chunk size will be 4194304, 4th one will be 978056 due to my apk size.But app center is expecting 4th one also should be 4194304.How we can resolve this issue?

**Comment by MikhailSuendukov** [comment]
Hello @Vibinreji  and sorry for the long wait. Please contact AppCenter support to resolve this issue.
