### ISSUE TITLE
Dead link https://github.com/facebook/react-native/tree/master/packager

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/appcenter-docs#143]
Found in docs/distribution/codepush/react-native.md

**Comment by jwargo** [comment]
@Zakeelm can you please fix this link and close the issue?  I'm pretty sure it's been moved to here: https://github.com/facebook/metro, but I'm not an expert.

**Comment by Zakeelm** [comment]
You're right! Fixed this and waiting on the PR to be merged. Going to close this
