### ISSUE TITLE
Not getting release_id as numeric from api response. 

### ISSUE THREAD

**Issue by ravizworldz** [MicrosoftDocs/appcenter-docs#1432]
hi 
I am getting release id as alphanumeric in response of below API.
URL:
"https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME/uploads/releases/$UPLOAD_ID"
Response:
{"id":"927c8bef-ef49-42e8-8329-c3d8a3c6a2c1","upload_status":"uploadFinished"}

note: as recommned by document there should be ‘release_distinct_id' which is not available in above response. So the reason I am using ‘id’ from above response, which is NOT number.

Below distribute API accept release_id as numeric only.
/v0.1/apps/{owner_name}/{app_name}/releases/{release_id}
distribute_response {"status":400,"name":"Error","message":"The \"release_id\" path parameter is invalid (\"927c8bef-ef49-42e8-8329-c3d8a3c6a2c1\") \n\"927c8bef-ef49-42e8-8329-c3d8a3c6a2c1\" is not a properly-formatted whole number"}

Sometimes it return HTML:

distribute_response <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
parse error: Invalid numeric literal at line 1, column 7

Where I can get release_id as numeric?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Distribute a build via App Center - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by stephan-markovic** [comment]
@ravizworldz 
The distinct numerical id of the of the release is returned as "release_distinct_id" when calling the [/v0.1/apps/{owner_name}/{app_name}/uploads/releases/{upload_id}](https://openapi.appcenter.ms/#/distribute/releases_getReleaseUploadStatus:~:text=release_id%7D/ios_manifest-,GET,-/v0.1/apps/%7Bowner_name) and will only be set when the upload status is "readyToBePublished"
