### ISSUE TITLE
Xamarin.UITests Repl Not working

### ISSUE THREAD

**Issue by UPSAndrewP** [MicrosoftDocs/appcenter-docs#1434]
There's an issue with Repl since 4.0 came out it seems. It's made it very difficult to use the tool affectively and have brought down our productivity to the point where we need to downgrade it to version 3 to use the tool. However, I've started using the Wait Helper function which is only available in 4.0+. So downgrading to 3.9 breaks everything.
When are we going to get a fix for Repl?

**Comment by IlyaBausovAkvelon** [comment]
@UPSAndrewP Thank you for contacting us.
Have you tried the latest version of Xamarin.UITest? Version 4.1.4.
REPL should be fixed here.

**Comment by UPSAndrewP** [comment]
> @UPSAndrewP Thank you for contacting us. Have you tried the latest version of Xamarin.UITest? Version 4.1.4. REPL should be fixed here.

I have, and even though there's a small improvement, it's still really buggy and doesn't work properly with similar issues.

**Comment by IlyaBausovAkvelon** [comment]
@UPSAndrewP
Could you please specify issues that you've faced?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
