### ISSUE TITLE
Xamarin.UITest Properties Function Query wont locate element

### ISSUE THREAD

**Issue by UPSAndrewP** [MicrosoftDocs/appcenter-docs#1435]
There's an issue with the Property Query function. It will not locate custom properties.
The way Xamarin Forms is used, we don't add ID's or Class names to our elements. The Dev's said that it doesn't translate to both Android and iOS devices so they've created a new property called 'Label'. We've been using marked to find these, however there are instances where we would like to use contains, or be direct with properties.
However when we build the Query x => x.Property("Label").Contains("Example_"), it doesn't locate anything. (I've used label and Label, just incase it was case sensitive) I've used different properties like id and it works out. Is this feature broken? It would be extremely beneficial if this worked.

![image](https://github.com/MicrosoftDocs/appcenter-docs/assets/135199370/befdf4cf-b8c8-4912-8bae-c876ab9c0fb8)

**Comment by IlyaBausovAkvelon** [comment]
Hi @UPSAndrewP,
Have you tried to search this label with full name?

**Comment by UPSAndrewP** [comment]
> Hi @UPSAndrewP, Have you tried to search this label with full name?

I have, it doesn't find it, it doesn't work properly.

**Comment by IlyaBausovAkvelon** [comment]
@UPSAndrewP,
Could you please try to name custom property CustomLabel instead of Label?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
