### ISSUE TITLE
Multiplatform UI Test App project template missing

### ISSUE THREAD

**Issue by pauljereb** [MicrosoftDocs/appcenter-docs#1442]
In Visual Studio for Mac 17.6.1 (Community), there's no project template for Multiplatform "UI Test App" as shown on the screenshot in chapter "Adding a UITest project to an existing solution". Is this template not available in the Community edition?

<img width="1012" alt="image" src="https://github.com/MicrosoftDocs/appcenter-docs/assets/50493018/922f8b8a-aae0-494f-bf78-a7278b0059b3">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5b5055c-bc86-18a2-7dc1-8c6582894763
* Version Independent ID: 092ee4b8-04fc-2067-13a2-20c0318882a9
* Content: [Get started with UITest and Xamarin.Forms - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/xamarin-forms?tabs=macos)
* Content Source: [docs/test-cloud/frameworks/uitest/xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/uitest/xamarin-forms.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by DmitriyKirakosyan** [comment]
App Center does not support MAUI projects at this moment, please use older version of Visual Studio.
