### ISSUE TITLE
Terrible Doc

### ISSUE THREAD

**Issue by BicycleMark** [MicrosoftDocs/appcenter-docs#145]
What do I do with thsi command line. Add to a post build script? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8739961-b56c-598c-c23a-0be804729621
* Version Independent ID: 82b926d2-8043-71ed-4501-4e39166b0881
* Content: [Starting a Test Run - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/starting-a-test-run)
* Content Source: [docs/test-cloud/starting-a-test-run.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/starting-a-test-run.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@BicycleMark do anything you want with it. Use it to trigger a test manually from the command line. Add it to a shell script you use to kick off a build, or a post-build script like you mentioned. We're simply trying to show how to use the CLI to kick off a test. 

We're happy to accept constructive criticism on how to make our docs better. If you have a suggestion for how we can make the doc more effective, please let us know.

**Comment by jwargo** [comment]
@glennwester FYI

**Comment by BicycleMark** [comment]
Almost all who are using this tool need to be pointed to how to set up test
on a server side build - most common usage. That is what is expected. The
doc shows a worst practice of not using a CI/Cd build to test with. Please
update to a common usage

**Comment by pahnev** [comment]
I agree. What is the build-dir supposed to be? I seriously can’t figure it out? And why is the iOS doc about this so much simpler and straightforward?

Aand why there is no integration with the Build? Why do we need to mess with these scripts? I’m sure I’m not the only one who would want to use AppCenter for the complete ci loop — from code push, to tests and to deployment.

**Comment by glennwester** [comment]
Hi @BicycleMark, thanks for writing in and making us aware of this! We have a PR in the works and the doc will be updated soon.

**Comment by winnicki** [comment]
+1 to @BicycleMark's comment about docs for most common usage. Luckily I found 
[this post](https://tomsoderling.github.io/AppCenter-Automated-UI-tests-on-build/), but ya, the reason anyone is writing automated UI tests in production is to run them post-build to verify. It should be a documented.
