### ISSUE TITLE
Was the following limit recently added/updated? `Maximum number of apps created for each user/organization per hour: 10 apps`

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/appcenter-docs#1454]
We have recently started seeing the following error
```
Retryable error creating app: 429: {"error"=>{"code"=>"RateLimitExceeded", "message"=>"Limit for creating apps exceeded. Please wait a bit before trying again."}}
```

We believe it's related to the following limit.
```
Maximum number of apps created for each user/organization per hour: 10 apps
```

Was that limit recently added/updated? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 753feb24-6869-bdbf-0880-1b5ae52732e0
* Version Independent ID: 8e4db4a1-07c2-ae46-3843-b139f19c1fb1
* Content: [Platform limits for App Center - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/general/platform-limits)
* Content Source: [docs/general/platform-limits.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/platform-limits.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by lucen-ms** [comment]
Yes, it was added in summer.
