### ISSUE TITLE
Is there a number to call to learn more information about the number of hours for test and number of concurrent devices for a plan

### ISSUE THREAD

**Issue by KermitPPI** [MicrosoftDocs/appcenter-docs#1456]
Hello,

The current explanation on this page is hard to understand and is a little confusing, I am trying to select the best plan and it is confusing because I don't clearly understand what is meant by concurrent devices and tests, is there a number I can call where I can speak to someone so that I can get some additional clarification or examples?  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdc863ba-5295-2db8-b37f-584e662e725a
* Version Independent ID: db2a1468-e4fa-6c55-985f-616de1e6484f
* Content: [App Center Pricing - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/general/pricing#faq)
* Content Source: [docs/general/pricing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/pricing.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by nikita-potashev** [comment]
You can contact support and ask any question about billing, we will be happy to help.  [How to contact support.](https://learn.microsoft.com/en-us/appcenter/help)
