### ISSUE TITLE
Connecting a New Repository needs to be better!!

### ISSUE THREAD

**Issue by mdalikazi** [MicrosoftDocs/appcenter-docs#147]
I was looking for a way to connect one more repository to AppCenter, and to save my life I couldn't find an option to do so in AppCenter. I sifted through the documentation only to find this golden piece of Easter Egg, hidden away from plain sight:

"Connect a new repository via the GitHub app by clicking the Connect your repository button in the email and repeat the process to create a new connection."

This means I need to keep the welcome email around in my inbox to connect a new repository. That link is not available anywhere else. This is simply bad!!! This needs to be part of my account settings or Add new app in AppCenter. This is crazy!!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de5a7b9-2742-0ea0-3170-d6fb5da0d2de
* Version Independent ID: f24ff5eb-4fb5-7a96-ff76-6c96386c9498
* Content: [Connecting Repositories Using the GitHub App - Visual Studio App Center](https://docs.microsoft.com/en-gb/appcenter/build/github-app)
* Content Source: [docs/build/github-app.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/github-app.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by jwargo** [comment]
@mdalikazi I think you're right, lets see what we can do to make this better. @nrajpurkar

**Comment by nilofer** [comment]
@mdalikazi Thanks for this feedback. I'll make the documentation clearer that this is only way to add a new repository at the current time. Your product feedback is appreciated as well!

**Comment by putuyoga** [comment]
There is no way to integrate existing app to github pull request? :(

**Comment by jwargo** [comment]
@putuyoga could you please clarify what you're asking?

**Comment by nilofer** [comment]
@putuyoga At this time, you need to create a new App Center app from the GitHub app to enable GitHub PR Checks. You cannot add this to existing App Center apps.
