### ISSUE TITLE
Only GIT????

### ISSUE THREAD

**Issue by angelieri** [MicrosoftDocs/appcenter-docs#148]
"Only Git repositories are supported at this point"
I'm Microsoft since as I remember. Each time is getting tough to stay using it.
I'm 100% Microsoft and not able to connect to App Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d825ca-716c-074c-74f6-d3bfb095962a
* Version Independent ID: 6a4a0742-7430-1c18-710d-afb63e2666c6
* Content: [App Center Build Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/faq#the-repository-i-want-to-connect-to-is-not-listed-in-the-link-repository-step)
* Content Source: [docs/build/faq.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/faq.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@angelieri the comments area of the App Center docs is provided to enable readers to suggest changes or request enhancements to the docs. We're happy to accept constructive feedback here on the docs and how to make the docs better.  

Product feedback (and questions) should be provided through the chat capabilities provided through the blue chat window in the lower-right corner of any App Center page. You have not provided any information about what type of repository you would like to use with App Center.  If you provide details about your requirements, perhaps we can help you.
