### ISSUE TITLE
Wrong support email listed on page.

### ISSUE THREAD

**Issue by ZehCastro** [MicrosoftDocs/appcenter-docs#1483]
The support email listed there doesn't work: support@appcenter.ms
![image](https://github.com/MicrosoftDocs/appcenter-docs/assets/1457644/f8d6f39c-ed90-46bf-ad69-2cc6174006a6)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36da5026-39aa-9a48-440c-7e57da3e3373
* Version Independent ID: eff2f79f-df52-829f-a0c3-71396e365884
* Content: [Help and Feedback - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/help#accessing-app-center-free-support)
* Content Source: [docs/help.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/help.md)
* Service: **vs-appcenter**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by lucen-ms** [comment]
We are sorry for issues with our support@appcenter.ms email address and working hard on restoring it back.

**Comment by lucen-ms** [comment]
Email address is restored. We are sorry for the issue.
