### ISSUE TITLE
Appcenter is not working, but the AppCenter Status Page says All Systems Operational.

### ISSUE THREAD

**Issue by seungyoubkim** [MicrosoftDocs/appcenter-docs#1486]
I can't use the codepush at the moment, nor can I access [appcenter.ms](https://appcenter.ms), but [status.appcenter.ms](https://status.appcenter.ms/) says that everything is working like the image below. Why?

![image](https://github.com/MicrosoftDocs/appcenter-docs/assets/106951161/bf0ce474-7cb7-4816-9d57-5ca7fe9e7b53)

**Comment by louisiscoding** [comment]
I did face the same issue yesterday. Having builds failing for no reason. Seems like microsoft is abandoning this project seriously...

**Comment by lucen-ms** [comment]
We are sorry for delayed status page update during the last incident.
