### ISSUE TITLE
Not receiving push notifications on android

### ISSUE THREAD

**Issue by ChizuNoYama** [MicrosoftDocs/appcenter-docs#149]
I have a slight problem with the push functionality. It seems like the push notifications are not consistent, at least with Android. I have  a forms project running .netstandard 2.0 and I have followed the instructions exactly and for some time I was able to receive the notifications, but from one moment to another I stopped getting them. Is there something I am missing that's not stated on the documentation?

**Comment by ChizuNoYama** [comment]
I put the permissions in this order 

``<uses-permission android:name="com.cob.fiu.edu.BizPass.permission.C2D_MESSAGE" />``
``<permission android:name="com.cob.fiu.edu.BizPass.permission.C2D_MESSAGE" android:protectionLevel="signature" />``

and did the old clean and rebuild and it works now. weird.

**Comment by jwargo** [comment]
@titonton The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
