### ISSUE TITLE
TrackError is inaccessible from method issue

### ISSUE THREAD

**Issue by rodrigojuarez** [MicrosoftDocs/appcenter-docs#150]
When I try to track an error I'm getting this error

Method `Microsoft.AppCenter.Crashes.Crashes.TrackError(System.Exception,System.Collections.Generic.IDictionary`2<string, string>)' is inaccessible from method `XXXXXX.SendEventToExternalLog(System.Exception,string)'

It's a Xamarin.Forms app, and the issue is when I try to run the app in the android emulator, I'm using Windows 10 and VS 2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a98dc868-6ec0-4d6e-652a-ed90d6c092b4
* Version Independent ID: d6061a26-6aef-be3a-c89a-3c8b290e2c9a
* Content: [App Center Crashes for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin#ask-for-the-users-consent-to-send-a-crash-log)
* Content Source: [docs/sdk/crashes/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/xamarin.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@rodrigojuarez The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
