### ISSUE TITLE
Update warning about issues with AppCenter in VSTO apps

### ISSUE THREAD

**Issue by LDS2020** [MicrosoftDocs/appcenter-docs#1505]
[Enter feedback here]

I would update the comment:

There's a known issue when integrating the SDK into VSTO projects. For more details, please visit https://github.com/microsoft/appcenter-sdk-dotnet/issues/1583/.

to something like:

There were known issue when integrating the SDK into VSTO projects prior to the release of SQLitePCLRaw 2.1.7. For more details, please visit https://github.com/microsoft/appcenter-sdk-dotnet/issues/1583/ and https://github.com/ericsink/SQLitePCL.raw/issues/455.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e799e45-8feb-d74c-4e25-3bdf49301766
* Version Independent ID: b6aef403-76f7-5df2-aa5d-3ed66397893d
* Content: [Get Started with WPF/WinForms - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms)
* Content Source: [docs/sdk/getting-started/wpf-winforms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/wpf-winforms.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by MikhailSuendukov** [comment]
Hello and thank you for reaching us out!
We're planning to release this [fix](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1768) with the next version of the AppCenter DotNet SDK, so we won't be adding it to known issues. I'll close this issue, but if you have any other questions, feel free to reopen it.

**Comment by LDS2020** [comment]
Hi [MikhailSuendukov](https://github.com/MikhailSuendukov). I'm a little confused by your latest comment. When the new AppCenter DotNet SDK is released will you remove that comment in the Known Issues or change it to the past tense, to encourage people to upgrade the version with the fix?

**Comment by MikhailSuendukov** [comment]
Apologies for the misunderstanding earlier. Following the release of the fix, we plan to remove this statement from the prerequisites section of our documentation, as we do not typically document errors associated with older versions of AppCenter.

**Comment by LDS2020** [comment]
No problem. That makes sense.
