### ISSUE TITLE
Doesn't support Expo

### ISSUE THREAD

**Issue by dpuckett** [MicrosoftDocs/appcenter-docs#1508]
React native openly recommend using Expo to build apps with their technology. Because of this a huge shift to using expo by default when creating React Native apps has happened. 
Your solution does not support this development process, and so is not fit for purpose with regards to best practices recommended by the technologies creators.

Make your App Center products Expo compliant, or you will be left for something else that does.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by MikhailSuendukov** [comment]
Thank you for reaching out to us!
Could you please specify which `AppCenter` services you are referring to? If you are experiencing issues with the integration of the `appcenter-react-native-sdk` into your Expo application, please describe the issue and provide an error log if possible.
