### ISSUE TITLE
Old support

### ISSUE THREAD

**Issue by rigoll** [MicrosoftDocs/appcenter-docs#1509]
[This support page is really old and suggest downgrading to really old stuff]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a93e3805-5fd5-c6c9-f25d-1be5c41ed77f
* Version Independent ID: 9826c974-24a2-b65e-9603-14428f6bb5bc
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/test-cloud/frameworks/appium/)
* Content Source: [docs/test-cloud/frameworks/appium/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/frameworks/appium/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by alexey-chernikov** [comment]
Currently App Center Test supports only Appium 1.x versions, latest version of 1.x branch is 1.22.
