### ISSUE TITLE
AppCenter crashes on startup

### ISSUE THREAD

**Issue by richardpineo** [MicrosoftDocs/appcenter-docs#1510]
Occasionally, AppCenter will crash on startup without much indication as to why it crashes. It's maybe 1/1000 launches but the application should not crash ever.

The client calling location isn't anything special:
```swift
let services = [Analytics.self, Crashes.self]
AppCenter.start(withAppSecret: appCenterKey, services: services)
```

Here is a call stack on the main thread of the most recent crash:
![image](https://github.com/MicrosoftDocs/appcenter-docs/assets/8593979/6ff13e33-d8ad-4a69-bd68-d3875b8ff6cf)

**Comment by MikhailSuendukov** [comment]
Hi @richardpineo 
Thank you for getting in touch with us. According to the crash report and its frequency, I suspect that the issue may be linked to memory management in your application. Presence of the SDK paths in the call stack may indicate that the SDK was the last one trying to access already corrupted or limited memory. In case the SDK itself is responsible for this crash, we would need a solid reproduction steps and a small demo application which can be used for reproducing the issue.

For any future issues related to the SDK, we encourage you to contact us through our [SDK repository](https://github.com/microsoft/appcenter-sdk-apple).

**Comment by tyjjuG-biqtom-jitma4** [comment]
Hamza
