### ISSUE TITLE
`delayInHours` documentation should note the minimum

### ISSUE THREAD

**Issue by simon-assistiq** [MicrosoftDocs/appcenter-docs#1517]
Under `rollbackRetryOptions` the [documentation](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref) says:

> delayInHours (Number) - Specifies the minimum time in hours that the app will wait after the latest rollback before attempting to reinstall the same rolled-back package. Defaults to 24.

The documentation does not specify the minimum `delayInHours`. The support team told me that one should not set it to zero as it can cause problems. This should be specified in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 839ed343-89da-4d62-c160-8f81fe396518
* Version Independent ID: 12f9c437-71ee-6f7a-bf72-0010a073df97
* Content: [React Native SDK with CodePush API Reference - Visual Studio App Center](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref#codepushoptions)
* Content Source: [docs/distribution/codepush/rn-api-ref.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/rn-api-ref.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @lucen-ms
* Microsoft Alias: **lucen**

**Comment by MikhailSuendukov** [comment]
Hello and thanks for reaching out to us. We have clarified this detail in this [PR](https://github.com/MicrosoftDocs/appcenter-docs/pull/1523). I'm closing this issue, but if you have any other questions, feel free to contact us.
