### ISSUE TITLE
Developer help to ensure our use of analytics doesn't violate GDPR

### ISSUE THREAD

**Issue by AndyDentFree** [MicrosoftDocs/appcenter-docs#152]
There is nothing on the site that I can find as of 27th May saying what we need to do if we want to use analytics and be compliant with GDPR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 251647b8-9e1a-1b6c-c152-66c4bf5d4c52
* Version Independent ID: 3b409924-b402-2401-ce34-ce4ef9c541c5
* Content: [GDPR - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/gdpr/your-data)
* Content Source: [docs/gdpr/your-data.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/your-data.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @iageoghe
* Microsoft Alias: **iageoghe**

**Comment by jwargo** [comment]
@AndyDentFree thanks for the feedback. We published our first set of GDPR docs last week, and more are on the way. We can’t advise you on how to be compliant, but we will show you how to manage your client’s data as it relates to GDPR. Stay tuned.

**Comment by jwargo** [comment]
@AndyDentFree We published a new set of GDPR docs this morning, take a look.
