### ISSUE TITLE
How to select valid gradle Build variant

### ISSUE THREAD

**Issue by Naitbit** [MicrosoftDocs/appcenter-docs#153]
`Build configuration` for Android project does not seem to show any valid gradle tasks.
Displayed tasks shows variants such as `normal.dimensionDebug` which then tries to execute commands such as:
`[command]/Users/vsts/agent/2.133.3/work/1/s/gradlew clean :app:assembleNormal.dimensionDebug :app:testNormal.dimensionDebug :app:lintNormal.dimensionDebug`
Which fail because other then `clean` all of them are invalid. Gradle failure:
`Task 'assembleNormal.dimensionDebug' not found in project ':app'.`

(Valid task would be `assembleNormalDebug` for that case)

Is there a way of selecting valid Build Variant, or overwrite UI selection via custom build script?

**Comment by jwargo** [comment]
@Naitbit The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
