### ISSUE TITLE
Multi-deployment Testing on Android needs matchingFallbacks to be specified

### ISSUE THREAD

**Issue by fshafiee** [MicrosoftDocs/appcenter-docs#155]
Recently, I tired to setup the staging in one our fresh projects. I followed the instructions on how to do the Multi-deployment Test (https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#android), but I was not able to sync, build, or run the project because gradle could not resolve the `releaseStaging` class path on included libraries, which makes sense of coures, since these libraries provide only `debug` and `release` buildTypes.

It took me a few days to readup the docs around gradle and test different configs to find the right solution. All it needs is a fallback. (http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.BuildType.html#com.android.build.gradle.internal.dsl.BuildType:matchingFallbacks)

Keep in mind that this was a fresh project with every package and tool on their latest versions. 
`Android Studi 3.1.2`
`react-native: "0.54.0"`
`react-native-code-push: "^5.3.3"`
`appcenter: "^1.5.0"`
`appcenter-analytics: "^1.5.0"`
`appcenter-crashes: "^1.5.0"`
`appcenter-push`: "^1.5.0"`

I guess it makes sense to include this tip in the doc somewhere. I have already create a PR. I hope it saves someone else the trouble.
https://github.com/MicrosoftDocs/appcenter-docs/pull/154

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39490e39-be97-2bba-5afc-6bc8bed39690
* Version Independent ID: 357a2070-e41c-b346-e18b-606eec7255c2
* Content: [Using the React Native SDK with CodePush - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#multi-deployment-testing)
* Content Source: [docs/distribution/codepush/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/react-native.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@farzadshafiee thanks for sharing.  We don't want you to have to work for several days to figure something out. Don't forget that you have direct access to our dedicated support team, you can ask them for help anytime. Just look for the blue chat icon in the lower-right corner of any App Center page, click that to open a chat with our support team.  You won't always get an immediate response, but you will get your questions answered in a timely manner.
