### ISSUE TITLE
Failed to apply settings

### ISSUE THREAD

**Issue by johnliedtke** [MicrosoftDocs/appcenter-docs#156]
I continually get the "Failed to apply settings" error message when trying to set up Push Notifications in the App Center admin portal. I have triple checked all the input fields to ensure they contain the correct keys, etc. Is there something wrong with the service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc364b7b-1462-5c0a-ca8b-e25f2847f41f
* Version Independent ID: 3829a377-4190-4644-a6c1-7e90e19483a5
* Content: [App Center Push for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/ios)
* Content Source: [docs/sdk/push/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/ios.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@johnliedtke The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by krystofbe** [comment]
hi @johnliedtke! Did you find a solution? I'm facing the same problem

**Comment by jwargo** [comment]
@krystofbe just use the support feature in App Center, click the blue chat button in the lower-right corner of every page and our dedicated support team will help you.
