### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by johnliedtke** [MicrosoftDocs/appcenter-docs#157]
The documentation erroneously requests the app prefix for APNS when the Team ID is what is required. I would recommend changing the documentation and app center to specify Team ID. I spent a couple hours debugging this and finally figured it out by trying out another push notification center provider.

Note App prefix != Team ID for enterprise apps... it looks like they are the same for non-enterprise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc364b7b-1462-5c0a-ca8b-e25f2847f41f
* Version Independent ID: 3829a377-4190-4644-a6c1-7e90e19483a5
* Content: [App Center Push for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/ios)
* Content Source: [docs/sdk/push/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/ios.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@johnliedtke thanks for pointing this out. We'll take a look at updating the docs. @dimazaid can you review?

**Comment by dimazaid** [comment]
hi @johnliedtke!
Thanks for pointing this out.
The documentation follows the guidance from Apple that all new app developers who joined after 2011 will have the Team ID same as the App Prefix ID. We will add a note to call out that the 2 values could be different if the developers had joined before. Link to guidance from Apple: https://developer.apple.com/library/content/technotes/tn2311/_index.html

As a follow up, if you added a Team ID in App Center for your app, will it work? can you please verify?

**Comment by johnliedtke** [comment]
Nice find, I was wondering why they differed. I can confirm the team ID worked. My client’s app has been running since 2008-2009 which explains why they’re not the same. 

It might be easier to just specify they use the team ID :)
