### ISSUE TITLE
wrong nuget url

### ISSUE THREAD

**Issue by gmoney494** [MicrosoftDocs/appcenter-docs#158]
you guys still use an old v2 url in the private nuget source config file. "<add key="nuget" value="https://api.nuget.org/v2/index.json" />", its v3 now. totally threw me off when i added it at first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d825ca-716c-074c-74f6-d3bfb095962a
* Version Independent ID: 6a4a0742-7430-1c18-710d-afb63e2666c6
* Content: [App Center Build Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/faq#the-repository-i-want-to-connect-to-is-not-listed-in-the-connect-to-repository-step)
* Content Source: [docs/build/faq.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/faq.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@gmoney494 thanks for pointing that out. We'll take a look at it.

**Comment by jwargo** [comment]
@gmoney494 the docs have been updated, thanks for pointing out the issue.
