### ISSUE TITLE
Contradictory Information

### ISSUE THREAD

**Issue by Michael-Osborn-Sanford** [MicrosoftDocs/appcenter-docs#159]
https://docs.microsoft.com/en-us/appcenter/analytics/faq
What is the maximum number of event properties that I can define per event? What happens if I send more than the limit?
The maximum number of event properties is currently set to five. If more than five properties are sent, they are automatically rejected. 

https://docs.microsoft.com/en-us/appcenter/analytics/event-metrics
The maximum number of event properties per event is 20. When more than 20 properties are sent, the first 20 properties are processed and the rest are automatically dropped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d0fe9f-178c-2b98-f02d-ae2f0918abbe
* Version Independent ID: 76aa6f90-1025-405e-715c-bf00ac545a78
* Content: [App Center Analytics Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/faq#feedback)
* Content Source: [docs/analytics/faq.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/faq.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by blparr** [comment]
Thank you @Michael-Osborn-Sanford , you're completely right! We increased the number from 5 to 20, and only updated one of the docs. I'll upddate asap.

**Comment by jwargo** [comment]
@Michael-Osborn-Sanford Fixed. thanks for pointing it out.
