### ISSUE TITLE
React Native for UWP

### ISSUE THREAD

**Issue by jpshelley** [MicrosoftDocs/appcenter-docs#160]
With Microsoft supporting react-native-windows development for UWP, will AppCenter support builds or other features for a React Native UWP application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af0b7eca-4e00-1857-1e31-e17d7f03ef4d
* Version Independent ID: 0fd8c4e7-43e3-ad39-4c41-3e798f2bd54a
* Content: [App Center Build for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/react-native/)
* Content Source: [docs/build/react-native/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/react-native/index.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @daadam
* Microsoft Alias: **daadam**

**Comment by jwargo** [comment]
@jpshelley The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
