### ISSUE TITLE
Code signing with corporate code signing certificate

### ISSUE THREAD

**Issue by arfurdo** [MicrosoftDocs/appcenter-docs#161]
I assume this build process support pfx files that are secured to specific users? Is it possible to safely sign with company code sign certificate ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be2ace35-a6ef-349a-e009-ca55e3778602
* Version Independent ID: 85a92e95-828a-54f8-b7e7-4f86b8e76abc
* Content: [Configure a C# UWP app in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/windows/uwp/first-build)
* Content Source: [docs/build/windows/uwp/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/windows/uwp/first-build.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@arfurdo The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
