### ISSUE TITLE
Upload symbols via CLI

### ISSUE THREAD

**Issue by southerneer** [MicrosoftDocs/appcenter-docs#162]
My company currently uses Bugsnag for crash reporting. Bugsnag provides a handy interface for uploading symbols via command line: https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/. This allows us to script uploading symbols as a step in a command line script; much easier than opening AppCenter in the browser and "manually" uploading symbols. It would be really awesome to see this kind of capability baked into the Codepush CLI...any plans for this in the near future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b36a466-fc92-153a-e513-a2f39ed4bf36
* Version Independent ID: bfca53b7-2d88-1665-57a8-163a88af183e
* Content: [App Center Crash Reporting for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/crashes/react-native)
* Content Source: [docs/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/crashes/react-native.md)
* Service: **vs-appcenter**
* Product: **unspecified**
* GitHub Login: @anlinde
* Microsoft Alias: **anlinde**

**Comment by jwargo** [comment]
@southerneer The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, or have product questions, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
