### ISSUE TITLE
Mrsmile

### ISSUE THREAD

**Issue by yarlay** [MicrosoftDocs/appcenter-docs#163]
My post

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8ba7a8-f1c1-c6d3-5f89-39ac5aa4f41c
* Version Independent ID: 83fae69c-9555-9afe-20b0-4c3415231e28
* Content: [App Center Azure Subscription Info - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/azure-subscriptions/)
* Content Source: [docs/general/azure-subscriptions/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/azure-subscriptions/index.md)
* Service: **vs-appcenter**
* GitHub Login: @joemellin
* Microsoft Alias: **joemel**

**Comment by jwargo** [comment]
@yarlay Did you have a comment to make on the docs?
