### ISSUE TITLE
Software Engineer

### ISSUE THREAD

**Issue by ManOnTheMountainTech** [MicrosoftDocs/appcenter-docs#164]
Required permissions needs to be stated as part of the sequence of steps required to get a module, such as crashes, going. Putting required permissions in the troubleshooting step wastes time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f6a73b-cde4-a960-792e-df0db60f2090
* Version Independent ID: a97c3ad0-dd1d-7212-c70f-15b764e0cbe7
* Content: [Android SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/android)
* Content Source: [docs/sdk/troubleshooting/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@ManOnTheMountain Thanks for the suggestion.  I'll pass your suggestion on to the product team.

**Comment by elamalani** [comment]
@ManOnTheMountain Thanks for the feedback. We plan to restructure SDK documentation in the future and I will make sure this feedback is addressed.
