### ISSUE TITLE
Excellent introduction to App Center Test

### ISSUE THREAD

**Issue by 24coins** [MicrosoftDocs/appcenter-docs#167]
Very well written. Thank you for the links to documentation which further explains key related concepts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b24e043-b73c-c05d-b101-56d2b89a3a7a
* Version Independent ID: 234e0be5-9c02-b8b4-7a5d-6032f5cba4e8
* Content: [App Center Test - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/)
* Content Source: [docs/test-cloud/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/index.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@24coins thanks for the feedback.
