### ISSUE TITLE
[React Native] Using Jest to test?

### ISSUE THREAD

**Issue by ducpt2** [MicrosoftDocs/appcenter-docs#171]
[React Native] Any chance we can use Jest to test our app on cloud (using Visual Studio Team Services)? and do you have any document and tutorial to using test with App Center?

Thanks in advance.

**Comment by jwargo** [comment]
@ducpt2 That's a question best covered by our support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
