### ISSUE TITLE
Environment variable to change the build mode

### ISSUE THREAD

**Issue by jdnichollsc** [MicrosoftDocs/appcenter-docs#172]
Hi guys,

Exist any way to change the build mode, to use **Debug** instead of **Release**, using environment variables (React Native/iOS)? or using appcenter-pre-build.sh?

Thanks in advance, Nicholls

**Comment by jwargo** [comment]
@jdnichollsc The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jdnichollsc** [comment]
Ohh but it would be perfect to add examples about that because it is missing from the documentation

**Comment by jwargo** [comment]
@nrajpurkar got an example you can throw at this?

**Comment by nilofer** [comment]
@jdnichollsc, you can see some examples of build scripts in our [example repo](https://github.com/Microsoft/appcenter-build-scripts-examples).

You would have to change
```
defaultConfigurationName = Release;
```
to
```
defaultConfigurationName = Debug;
```

**Comment by jdnichollsc** [comment]
@nrajpurkar ohh beautiful, where can I find that example from the repo? I can't see any example changing the *defaultConfigurationName*, but let my try :)

**Comment by nilofer** [comment]
I don't actually think that exact example exists. Feel free to contribute to the examples if you come up with something, we would definitely welcome any contributions! @jdnichollsc

**Comment by jdnichollsc** [comment]
@nrajpurkar I can see the following log after build the app
```
2018-06-12T18:39:19.8227530Z /Users/vsts/agent/2.134.2/work/1/s/react-native/appcenter-pre-build.sh: line 1: defaultConfigurationName: command not found
```

Let me know what you think

**Comment by jwargo** [comment]
@jdnichollsc use App Center support to get help with issues. There's a dedicated team monitoring the chat system, so you'll get a better response.

**Comment by jdnichollsc** [comment]
thanks guys!
@nrajpurkar thanks for the idea about the contributions, check my first contribution: https://github.com/Microsoft/appcenter-build-scripts-examples/pull/10
