### ISSUE TITLE
Feature request portal link is busted

### ISSUE THREAD

**Issue by atrich** [MicrosoftDocs/appcenter-docs#173]
I want to request support for the react native framework detox (OSS supported by wix) but your feature request link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1f8239-19fa-9c4b-52f5-b9c19cafbb4a
* Version Independent ID: 1980a317-8a4a-10b3-eedd-32af9d36cfbe
* Content: [Supported Test Frameworks - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/supported-frameworks)
* Content Source: [docs/test-cloud/supported-frameworks.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/supported-frameworks.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@atrich thanks for the suggestion, can you help me understand what link you're referring to?

For feature requests, etc, use the chat window App Center.  Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by cashewshideout** [comment]
The second paragraph on this page (https://docs.microsoft.com/en-us/appcenter/test-cloud/supported-frameworks) states "To file a request for a new test framework or vote for an existing request, visit the feature request portal." The link on "feature request portal" is broken. There is no blue chat button on the page.

**Comment by jwargo** [comment]
@cashewshideout thanks. The blue chat icon is on any App Center page, you won't find it in the docs. If you're in App Center and don't see the blue chat button, then check to make sure you don't have any pop-up blockers active or other browser technology that would limit access to external services from the page.

**Comment by atrich** [comment]
I don't want to chat with anyone. I want the "feature request portal" link to work.

**Comment by jwargo** [comment]
@atrich i'm sorry, but you'll have to use chat to do that.  We've removed the link to the feature request as that was something we were experimenting with and decided to stick with what we have. The chat process gets your feedback directly to the PM team.
