### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by GlennWilson** [MicrosoftDocs/appcenter-docs#175]
This:           You can still be create, compile and uploade to App Center Test from Windows.
Should be: You can still create, compile and upload to App Center Test from Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb0ff0a-1fb7-9362-34e4-50879d07f0f2
* Version Independent ID: 469a4e00-53a3-b903-eb0d-1d307b4b4166
* Content: [Preparing Xamarin.UITests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/uitest)
* Content Source: [docs/test-cloud/preparing-for-upload/uitest.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/uitest.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@GlennWilson thanks. I fixed that typo and cleaned up the doc. I'll get this published once @glennwester reviews it.
