### ISSUE TITLE
advising to use `sudo` with `npm install appcenter-cli` on macOS and Linux

### ISSUE THREAD

**Issue by 0xpatrickdev** [MicrosoftDocs/appcenter-docs#177]
[This](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/index#1-install-the-app-center-cli) may not be the best advice: 

> Note
> On macOS and Linux, you may need to prefix this command with `sudo`

Usually sudo is needed to install an npm package when one was previously installed with sudo/root permissions. For reference as to why this is not good, here's a good resource: https://givan.se/do-not-sudo-npm/
In the spirit of making everyone better devs, maybe we can remove this and advice people to use nvm or point them to resources like [this](https://docs.npmjs.com/getting-started/fixing-npm-permissions) or [this](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 609b687a-a22b-47e0-b20f-767a56109c47
* Version Independent ID: f6e679d5-638b-c150-5fe9-11cbfe97c7ae
* Content: [Use CodePush to update your app live - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/index)
* Content Source: [docs/distribution/codepush/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/index.md)
* Service: **vs-appcenter**
* GitHub Login: @iageoghe
* Microsoft Alias: **iageoghe**

**Comment by jwargo** [comment]
@pcooney10 thanks, I'll have the PM take a look at this. I agree with you completely, but sometimes you have to give people shortcuts to keep them moving.

**Comment by 0xpatrickdev** [comment]
Yes, I understand the tradeoff but figured I'd raise the point.

**Comment by jwargo** [comment]
@pcooney10 I made the docs more clear.
