### ISSUE TITLE
About the Contact us

### ISSUE THREAD

**Issue by gilles-leblanc** [MicrosoftDocs/appcenter-docs#179]
The Contact us section mentions: "Report a bug or a make a feature request using the blue button at the bottom right of every App Center portal page and the product team will respond to you. ".

Either I'm really not seeing what's right in front of me or this isn't accurate anymore because I can't find a blue button and at the bottom right of any App Center pages.

It might also be helpful to link to whatever page or email address this button links to so a person searching for this doesn't have to leave this page to search for this somewhere else. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dd71a0-a249-a87b-e4eb-e4da0a20472f
* Version Independent ID: 450c26f5-ab13-8df5-d45a-6086f5391b23
* Content: [App Center Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/support-center)
* Content Source: [docs/general/support-center.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/support-center.md)
* Service: **vs-appcenter**
* GitHub Login: @joemellin
* Microsoft Alias: **joemel**

**Comment by jwargo** [comment]
@gilles-leblanc  Good point, I'll add a link to this page: https://intercom.help/appcenter/getting-started/getting-help-with-app-center which shows how it works.

You won't see the blue chat button in the Docs, only in App Center. If you don't see it, then you're having other issues. Do you have a pop-up blocker enabled in the browser?

**Comment by gilles-leblanc** [comment]
I disabled all add-ons (ublock origin, privacy badger, https everywhere, greasemonkey, etc.) and I now see the button. My bad.

**Comment by nol13** [comment]
still dont see it on firefox with everything disabled, is on chrome and safari, though the link don't work in any

**Comment by jwargo** [comment]
@nol13 it feels like your message was incomplete, were you asking a question?

**Comment by nol13** [comment]
no, just fyi that it doesn't work

**Comment by jwargo** [comment]
@nol13 I see that now, checking into this. thanks for letting us know.

**Comment by nol13** [comment]
Right, I guess I should use full sentences. Specifically, the links to the help topics after typing in a search were not working. Button wasn't showing in Firefox on mac. Thanks!

**Comment by jwargo** [comment]
@nol13 OK, links from search are working for me, it's just the chat button that's missing (in three browsers). I have someone taking a look.
