### ISSUE TITLE
Link to release notes

### ISSUE THREAD

**Issue by cosminstirbu** [MicrosoftDocs/appcenter-docs#184]
Hello,

It would be nice if each SDK Platform entry (Android, iOS, macOS, UWP, etc) would have a link to the SDK release notes.

So far I wasn't able to find them.

Regards,
Cosmin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72f6fe-74d6-696e-e709-5f6d577c0a58
* Version Independent ID: b3d0ea8b-5a1f-bf71-7dc2-9685cf23c00b
* Content: [Get Started with Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin)
* Content Source: [docs/sdk/getting-started/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@cosminstirbu the release notes are in the SDK repositories. https://github.com/Microsoft/AppCenter-SDK-Apple/blob/develop/CHANGELOG.md

**Comment by cosminstirbu** [comment]
Not sure if those apply to Xamarin as well. For instance it seems that there has been a 1.7.1 release, and the latest .nuget package is 1.7.0

Also it mentions in the change log that a duplicate symbol error was fixed in  Xamarin wrapper SDK in 1.7.1 - does this mean that 1.7.0 is broken?

I'm currently using 1.7.0, which was published 15 hrs ago and it's not clear if I should revert due to those errors (also the app is running just fine, and there are no console warnings that I can see, so I'm not sure how those errors impact us).

Regards,
Cosmin

**Comment by jwargo** [comment]
@elamalani can you address these questions?

**Comment by iamclement** [comment]
Hello @cosminstirbu,

The Xamarin release note can be found on the [DotNet GitHub release page](https://github.com/Microsoft/AppCenter-SDK-DotNet/releases).
There is no release for Xamarin version 1.7.1, we always bump the version in the code after a release but there is no version 1.7.1 released yet.
What can be confusing is the App Center Xamarin SDK is a wrapper around our native iOS and Android SDKs but those native SDKs have their own versioning. For instance the "duplicate symbol error" was found on the **native App Center iOS SDK** version 1.7.0. But the released App Center Xamarin SDK never used that version. We fixed the issue in the native iOS SDK in its version 1.7.1. The App Center Xamarin SDK 1.7.0 integrates the native App Center iOS SDK version 1.7.1 containing the fix.

So yes you can use the App Center NuGet packages v1.7.0 for your Xamarin app.
