### ISSUE TITLE
Need to connect Visual Studio App Center to BitBucket.

### ISSUE THREAD

**Issue by Akshaybhalerao111** [MicrosoftDocs/appcenter-docs#185]
Hi Team,

My BitBucket repository is in AWS EC2 instance, how can I connect that repository to my Visual Studio App Center to fetch the code.

Regards,
Akshay

**Comment by jwargo** [comment]
@Akshaybhalerao111 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
