### ISSUE TITLE
Cross platform frameworks could be clarified

### ISSUE THREAD

**Issue by luisnaranjo733** [MicrosoftDocs/appcenter-docs#186]
Currently, the "Preparing test for Upload" page group contains pages for cross platform and platform specific all thrown together in the same group. It would be easier for readers to reason with their decision making on which framework to use if they were grouped by "cross platform" and "platform specific".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium)
* Content Source: [docs/test-cloud/preparing-for-upload/appium.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@luisnaranjo733 thanks for the suggestion. We're in the planning process to do a refresh on the docs, and doc structure is one of the prime motivators. I doubt we'll split things into cross-platform and platform, but we will try to organize better.
