### ISSUE TITLE
Location of data processing and legal address for contracts needed

### ISSUE THREAD

**Issue by marcus-franzen** [MicrosoftDocs/appcenter-docs#187]
Hi AppCenter-Team,

we would need to know where the data is processed and ideally having an option to choose EU-based servers for the AppCenter.
Also we provide our clients in our DPA the address of used cloud services, I could not find that either.

Many thanks!
Marcus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd84a4ba-2763-349d-ca45-1adec494d357
* Version Independent ID: 61f5bc4a-6aea-7af2-76aa-9b45d24aba19
* Content: [General Data Protection Regulation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/gdpr/)
* Content Source: [docs/gdpr/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/index.md)
* Service: **vs-appcenter**
* GitHub Login: @iageoghe
* Microsoft Alias: **iageoghe**

**Comment by iageoghe** [comment]
Hi Marcus,

Unfortunately at this time we do not offer our customers a choice of region. Depending on which of our services you are using, App Center processes data in the EU and/or the US. 

Thanks,

Ian
