### ISSUE TITLE
Version number next to Date

### ISSUE THREAD

**Issue by AntRemo** [MicrosoftDocs/appcenter-docs#188]
Hi

Can the version number be added to the date? I have to go to Nuget to determine which date is associated to the version I have installed.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62690a4a-94f3-21cb-a674-d297e557ca62
* Version Independent ID: 3adaeac7-e034-5b5b-19c5-1c0151a7264c
* Content: [App Center Changelog - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/changelog)
* Content Source: [docs/general/changelog.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/changelog.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by jwargo** [comment]
@AntRemo The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by AntRemo** [comment]
@jwargo 

Thanks for the reply :)

Should I reach out to App Center support for the updating of this page on the doc site?

Thanks

**Comment by jwargo** [comment]
@AntRemo Use support to get the answer to the question, suggest a doc update if you think it makes sense.
