### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by starkos** [MicrosoftDocs/appcenter-docs#189]
"before getting started with our serivces" …should be "services".

"develeoper, viewer, or manager" …should be "developer".

"Create a team within your ogranization" …should be "organization".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1709b666-1277-498f-5a89-b907c8ce881b
* Version Independent ID: 648c03f3-9822-31cc-0c4f-4d4a0d928ac3
* Content: [Using App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/)
* Content Source: [docs/dashboard/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/index.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by jwargo** [comment]
@starkos thanks for catching those. Fixed,
