### ISSUE TITLE
Appium c#

### ISSUE THREAD

**Issue by alinaum** [MicrosoftDocs/appcenter-docs#19]
Can I run tests with appium written on C# ? If yes where is the documentation for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* [Content](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium#feedback)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: vs-appcenter

**Comment by glennwester** [comment]
Hi Aline, we solely support the Appium Java client with JUnit as the test runner. We hope to add support for Appium C# in the future. Alternatively, we do support Xamarin.UITest which is a C# based automation framework.

**Comment by cosminstirbu** [comment]
I am also interested in support for Appium C# - since we use it to support UWP tests as well.

So we're interested in either adding UWP support in Xamarin.UITest or add Appium C# support in the Test-Cloud

**Comment by glennwester** [comment]
Hi @cosminstirbu thanks for letting us know! I'm assuming you're using WinAppDriver to drive the UWP UI testing?

**Comment by cosminstirbu** [comment]
Yeap, we're using WinAppDriver to drive UWP.

**Comment by glennwester** [comment]
That's great to hear, do you use this to test Win32 as well or strictly UWP?

**Comment by cosminstirbu** [comment]
Strictly UWP. However we didn't start the development on our UWP app,
currently we're working on the iOS version - so we've made the decision to
go with Appium since we plan to support UWP in the near future.

**Comment by nnguyen2102** [comment]
I'm currently using Microsoft UnitTest framework with Appium, C# to test Android and IOS real devices. Will my tests work with App Center?

Sample test case written in Visual Studio 2017:
namespace AppCenterTests
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            DesiredCapabilities cap = new DesiredCapabilities();
            cap.SetCapability("deviceName", "Samsung S8+");

            AndroidDriver<AppiumWebElement>  Driver = new AndroidDriver<AppiumWebElement>(new Uri(""), cap);

            Driver.GetScreenshot();
        }
    }
}

**Comment by jwargo** [comment]
@nnguyen2102 The comments feature of the docs is designed to enable customers to suggest changes to the docs or ask clarifying questions about the docs. If you need help with the product, please login to the App Center dashboard and click the blue chat button in the lower-right corner of the page. Our dedicated support resources will answer any questions you have there.

**Comment by jcummings2** [comment]
See also microsoft/appcenter#102 and microsoft/appcenter#453
