### ISSUE TITLE
Format of properties

### ISSUE THREAD

**Issue by MattiasFindwise** [MicrosoftDocs/appcenter-docs#190]
"Properties":"{\"extra_00\":\"5bcacf3598ca44ebbbc99e4488cfc854\",\"extra_01\":\"2673e48867c74d51af8dc24c762a8b28\",\"extra_02\":\"5b76c801e5074cd3a13ea37253b94484\",\"extra_03\":\"c1e76aa252c947d4b4bcd4d1d96a7be6\",\"extra_04\":\"caea50034c4f441a963700fa3cf70d03\"}"

Is this a string? I thought/hoped that it would be a nested JSON object? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14a1fd-c1c2-f1a7-dd70-97c1200571f1
* Version Independent ID: f502c9bf-5593-1dd7-3551-6a7ca21f6f5c
* Content: [App Center Export - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/export)
* Content Source: [docs/analytics/export.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/export.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by MattiasFindwise** [comment]
This is already documented in another issue

**Comment by jwargo** [comment]
@blparr can you help out here?

**Comment by jwargo** [comment]
@MattiasFindwise can you share where?
