### ISSUE TITLE
Allow notifications to be seen inside the app

### ISSUE THREAD

**Issue by FerLuisxd** [MicrosoftDocs/appcenter-docs#191]
For example if someone missed the notification for some reason, they can be seen inside one tab in the app  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65373652-7eda-af01-0f72-d01fcce4c131
* Version Independent ID: f85b66b3-ca30-bb5c-bfae-6425661d3365
* Content: [App Center Push for Xamarin.Forms Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms)
* Content Source: [docs/sdk/push/xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-forms.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@FerLuisxd are you trying to suggest a change to the docs? If so, can you be more specific?

**Comment by jwargo** [comment]
@elamalani or @dimazaid can you help here?

**Comment by elamalani** [comment]
@FerLuisxd We don't support this in App Center and it looks like a feature request for Push Notification service.
