### ISSUE TITLE
Xamarin.Forms Not able to send Notification for android app From App Center Client

### ISSUE THREAD

**Issue by SonamSIngh1** [MicrosoftDocs/appcenter-docs#192]
Hi have created two apps one for iOS and other for android. I am successfully able to send push notifications using App Center Client to iOS but I am not receiving it on android, but I am  able to send Android  through UI ofApp Center.
Even I tried to change name of app , in that case its says error not found. I have tired it with various payloads

**Comment by jwargo** [comment]
@SonamSIngh1 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
