### ISSUE TITLE
Different Versions of Node.js Required?

### ISSUE THREAD

**Issue by GlennWilson** [MicrosoftDocs/appcenter-docs#195]
I suspect these two references should be consistent and both say Node.js version 8 or better?

Or, maybe better, leave out the Node.js version on this page, so that info does not need to be maintained?

> After the test run has been created, ensure that the following software is installed on the computer that will submit the tests:
> 
> Node.js 6.3
> App Center CLI
> 
> Instructions for installing the App Center CLI maybe be found in the README.md on GitHub.

But in the linked reference (https://github.com/Microsoft/AppCenter-CLI#installation)

>Prerequisites
> App Center CLI requires Node.js version 8 or better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb0ff0a-1fb7-9362-34e4-50879d07f0f2
* Version Independent ID: 469a4e00-53a3-b903-eb0d-1d307b4b4166
* Content: [Preparing Xamarin.UITests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/uitest)
* Content Source: [docs/test-cloud/preparing-for-upload/uitest.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/uitest.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@glennwester we just updated the one and haven't fixed the other one yet.

**Comment by glennwester** [comment]
Assigning @amchew

**Comment by amchew** [comment]
Thanks @GlennWilson for notifying on the discrepancy! I've made a PR to fix this [here](https://github.com/MicrosoftDocs/appcenter-docs-pr/pull/707).

**Comment by jwargo** [comment]
Fix applied, closing issue
