### ISSUE TITLE
Maximum number of install IDs

### ISSUE THREAD

**Issue by MKielblock** [MicrosoftDocs/appcenter-docs#196]
What is the maximum number of install IDs/devices that one can target using the Custom devices list option when sending a Push Notification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a9c2bfe-e6be-bce0-7d66-8af878cecffa
* Version Independent ID: 00ed44c9-1037-03b1-be92-0d2869cc4b23
* Content: [App Center Push - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/)
* Content Source: [docs/push/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/index.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by jwargo** [comment]
@dimazaid can you answer this, then update the docs?

**Comment by jwargo** [comment]
App Center currently supports a maximum of 20 install ID/devices in a custom device list.
