### ISSUE TITLE
Possible to delay notification permission request?

### ISSUE THREAD

**Issue by alexcurylo** [MicrosoftDocs/appcenter-docs#200]
Passing  Push to MSAppCenter.start() has the System "... would like to send you notifications" dialog pop up immediately on first launch. These days a pretty significant fraction of users (like 60%, some stats claim) reflexively disallow notifications that pop up immediately like that, so I'd like to only have the System alert show after an appropriate pre-permission opt-in of my own during onboarding (or later, if they decline during onboarding but decide to attempt a permission-requiring action later). Since apparently you can't call MSAppCenter.start() twice, I can't see any way to accomplish that. Is it possible currently? If not, some way to add a pre-permission flow, or at least only trigger initial APNS registration on command, that would be a nice feature to put on your roadmap somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc364b7b-1462-5c0a-ca8b-e25f2847f41f
* Version Independent ID: 3829a377-4190-4644-a6c1-7e90e19483a5
* Content: [App Center Push for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/ios)
* Content Source: [docs/sdk/push/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@alexcurylo The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by liltimtim** [comment]
I know this is closed however I found a solution (lead here from the Microsoft Documentation site).  This is also a VERY popular Google search result topic so I figured I might offer some sort of solution. 

I hope this can help you @jwargo 

### Inside my PushNotificationPrimingViewController.swift

```Swift
import UIKit
import UserNotifications
import AppCenterPush
import AppCenter
class PushNotificationPrimingViewController: UIViewController {
    private let center: UNUserNotificationCenter = UNUserNotificationCenter.current()

    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    private func setupUI() {
        // removed for brevity 
    }
    
    @objc private func optInPressed() {
        // tells AppCenter to start the service
        MSAppCenter.startService(MSPush.self)
        // set the service enabled 
        MSPush.setEnabled(true)
        center.requestAuthorization(options: [.alert, .badge, .carPlay, .sound]) { (granted, err) in
            if granted {
                // yay push enabled 
            } else {
               // the user didn't like us :( 
            }
        }
    }
    
    @objc private func skipPressed() {
       
    }
}
```


### Inside my AppDelegate.swift file

```Swift
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        MSPush.didRegisterForRemoteNotifications(withDeviceToken: deviceToken)
    }
    
    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        MSPush.didFailToRegisterForRemoteNotificationsWithError(error)
    }
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        let result: Bool = MSPush.didReceiveRemoteNotification(userInfo)
        if result {
            completionHandler(.newData)
        }
        else {
            completionHandler(.noData)
        }
    }
```

**Comment by dhei** [comment]
Hi @alexcurylo @liltimtim,
It is possible to delay push notification permission on iOS using App Center. 
Please see our documentation at https://docs.microsoft.com/en-us/appcenter/push/faq. Basically you can do this by delaying the AppCenter.Start(typeof(Push)) method call until you want the permission pop-up to show up.

**Comment by liltimtim** [comment]
@dhei although that link is useful, I don't believe that this documentation reference should be just in the FAQs.  When setting up push notifications, it would probably be in the interest of everyone if this was readily apparent instead of a developer having to dig through things.  I never reached that FAQ by googling for similar answers, however I did arrive at this Github issue.  

However, I accomplish what the original poster was wanting to achieve with the code mentioned above and it was placed there for the sole purpose of providing those whom arrive here via Google with a quick and easy to implement answer / example since the documentation fails to explain delayed pushes properly (IMO).

**Comment by dhei** [comment]
@liltimtim Really appreciate the feedback, I agree it doesn't make sense to be in the FAQ section. We will make move it to the setup documentation and improve our docs.

**Comment by alexcurylo** [comment]
@dhei Yes, the documentation to `start` appears to imply that's the only place you can start services. A reference to delaying service starts to later would definitely reduce confusion!
