### ISSUE TITLE
‌alihamzehzadeh

### ISSUE THREAD

**Issue by Alihamzehzadeh** [MicrosoftDocs/appcenter-docs#201]
پشتیبانی کنید از ماکروسافت

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06813350-a37b-a4a2-fdbc-a59caefb9f32
* Version Independent ID: 29787958-5b4e-efc2-2af5-2af0ee53216e
* Content: [App Center Build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/)
* Content Source: [docs/build/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/index.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@Alihamzehzadeh do you have a question or comment about the App Center docs?  App Center support is provided directly from within the App Center portal - just click the blue chat icon in the lower-right corner of any App Center page and our dedicated support team will respond.

**Comment by jwargo** [comment]
@Alihamzehzadeh I haven't heard back from you, so I'm closing this issue.
