### ISSUE TITLE
"In some cases" part isn't clear

### ISSUE THREAD

**Issue by enagorny** [MicrosoftDocs/appcenter-docs#202]
Please describe "In some cases" when and why this cases could appear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a7f669-58a0-6700-13c5-e8f9c647943c
* Version Independent ID: eec16d36-776d-3438-ed39-ad8e98ff2c08
* Content: [App Center Analytics for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/react-native#wait-for-js-to-enable-app-center-analytics)
* Content Source: [docs/sdk/analytics/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @TroubleMakerBen
* Microsoft Alias: **bereimol**

**Comment by elamalani** [comment]
@dhei agreed to make this change in the docs.

**Comment by dhei** [comment]
@enagorny, thanks for the feedback. Doc is updated now and let us know if you have more questions.
