### ISSUE TITLE
Question/Feedback: Missing steps for android integration

### ISSUE THREAD

**Issue by zen0wu** [MicrosoftDocs/appcenter-docs#203]
I've done `react-native link` and got it working on iOS (Analytics has data), but not Android.

From my shallow observation, maybe we need to add things like

```
import com.microsoft.appcenter.reactnative.appcenter.AppCenterReactNativePackage;
import com.microsoft.appcenter.reactnative.analytics.AppCenterReactNativeAnalyticsPackage;
import com.microsoft.appcenter.reactnative.crashes.AppCenterReactNativeCrashesPackage;

...
    protected List&lt;ReactPackage&gt; getPackages() {
        return Arrays.asList(
            ...,
            new AppCenterReactNativePackage(MainApplication.this),
            new AppCenterReactNativeCrashesPackage(MainApplication.this, "XYZ"),
            new AppCenterReactNativeAnalyticsPackage(MainApplication.this, true)
         );
     }
```

Since 1. those packages exist and I didn't find anything in the link script, and 2. I can't get Android integration work

Also, AppCenterReactNativeCrashesPackage seems to live under the wrong package namespace, which differs from its path.

I could be totally wrong, please kindly correct me if that's the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by zen0wu** [comment]
Update: I added these 6 lines and it shows up in app center. Might be a delay, since there's no precise time so there's no way for me to make sure.

**Comment by jwargo** [comment]
@shivawu The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by zen0wu** [comment]
I'm confused with the comment. Compared to the other 2 comments on the page, which is related to the exact same topic (#174 and #98), why is this one not qualified as a "suggested change" or a "question"? Also my question is not answered either.

I'm aware of the support feature on the page. I just feel this might be an issue with the doc so it's faster to report it here.

**Comment by jwargo** [comment]
@shivawu you're asking a question about how to get something to work - that makes it a support question. We have an experienced team manning support, and that's the way you get help with App Center.  Asking for help on the docs doesn't get you direct access to people who can help. If there's something missing in the docs, let us know, but get it working with the help of the support team - they, or you, can recommend doc changes based on what you learn getting past your issue.

**Comment by zen0wu** [comment]
Great, thanks for the clarification
