### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by michelmoorlag** [MicrosoftDocs/appcenter-docs#204]
My app supports multiple languages and I would like the user to receive the notification in it's own language.

First I thought I could use Audiences with device propertie "Language" and send a localized message for every language I support. The problem is that I need to send a message to Device ID and according to the api I can not combine notification_target . I have to choose between "type" : "audiences_target" or "type" : "devices_target". Intercepting the message isn't an option either because it is called after the notification is received. 

**So how can I send localized messages to specific devices?**

**Comment by jwargo** [comment]
@michelmoorlag The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
