### ISSUE TITLE
The sasUrl returns an error (which is not documented here)

### ISSUE THREAD

**Issue by cuducos** [MicrosoftDocs/appcenter-docs#205]
This pages reads:

>  a successful response from this method will indicate the location from which the information may be retrieved securely.

However when I reach this point I'm always getting an error from the `sasUrl`, doesn't matter if I send it with the `X-API-Token` header or not. Actually this documentation does not clarify HOW to do the request to the `sasUrl` – POST? GET? Which headers are required?

The error is always:

```xml
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Time:2018-07-04T13:20:18.8237474Z</Message><AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail></Error>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 251647b8-9e1a-1b6c-c152-66c4bf5d4c52
* Version Independent ID: 3b409924-b402-2401-ce34-ce4ef9c541c5
* Content: [Managing Your Data - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/gdpr/your-data#export)
* Content Source: [docs/gdpr/your-data.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/your-data.md)
* Service: **vs-appcenter**
* GitHub Login: @iageoghe
* Microsoft Alias: **iageoghe**

**Comment by cuducos** [comment]
Ooops… the error changes! With `curl -H "X-API-Token: xxxxxxxxx"` plus the `sasUrl` the error is:

```xml
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b5d17c26-e01e-001e-399c-138189000000
Time:2018-07-04T13:41:22.9481223Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was rl

2018-08-03T13:18:13Z
/blob/dsr0ede6f06e/$root



2017-11-09




</AuthenticationErrorDetail></Error>
```

**Comment by jwargo** [comment]
@cuducos contact our support team (click the blue chat icon in the lower-right corner of any App Center page) to resolve your issue. I'll have the team take a look at documenting the error on the page (although any service will return an error if there's something wrong with the request).

**Comment by cuducos** [comment]
>  contact our support team (click the blue chat icon in the lower-right corner of any App Center page) to resolve your issue

Hi @jwargo. I'm sorry, but I cannot find that icon. This is what I see in `https://appcenter.ms/apps`:

![image](https://user-images.githubusercontent.com/4732915/42325692-5b68dc12-803d-11e8-8ba0-f2711c3e7d9d.png)

And this is what I see in the help page that led me to the error, `https://docs.microsoft.com/en-us/appcenter/gdpr/your-data`:

![image](https://user-images.githubusercontent.com/4732915/42325827-bc3680a8-803d-11e8-9d5f-da9a65f20495.png)


Can you help with an actual URL where I can find it, or with better instructions to find it in the pages I've tried?

**Comment by jwargo** [comment]
@cuducos turn off pop-up blockers, etc. 

I can't point you to a URL for it as its embedded in App Center pages.

**Comment by cuducos** [comment]
> @cuducos turn off pop-up blockers, etc.

Off. But I cannot login anymore. Maybe, despite the error reported on #206, my account was already deleted. Good news — or kind off.

**Comment by iageoghe** [comment]
Hi @cuducos, you have correctly deduced that a DSR export request will fail after a DSR delete. However, it looks like there may be a couple of things going on here and as you point out, the documentation looks like it could use some revision around the export process. 

1. The first call that needs to be made for export is to the [POST](https://openapi.appcenter.ms/#/operations/gdpr/DataSubjectRight_ExportRequest) method. 

2. Using the returned token, issue a [GET](https://openapi.appcenter.ms/#/operations/gdpr/DataSubjectRight_ExportStatusRequest). The export operation may take some time and for this reason the method may return an error code indicating that the processing is still on-going. If the operation has completed, the method will return a sasUrl which can be [used](https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1#sas-examples) to download the additional export assets not returned by our standard GET API methods. 

I am going to close this issue and get to work on an new revision of this portion of the docs. Thank you for letting us know where we could make improvements; it is appreciated.
