### ISSUE TITLE
Error in the “Manage Your Data » Delete” API

### ISSUE THREAD

**Issue by cuducos** [MicrosoftDocs/appcenter-docs#206]
Following instructions from [Manage Your Data](https://docs.microsoft.com/en-us/appcenter/gdpr/your-data#delete) support page led me to an error:

I could get the token with:
```sh
$ curl -X POST -H "X-API-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
   https://appcenter.ms/api/v0.1/user/dsr/delete
```

This command gave me the following response:

```json
{"token":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","createdAt":"2018-07-05T13:28:35.2455507Z"}
```

Then I tried to use this token to the next HTTP request:

```sh
curl https://api.appcenter.ms/v0.1/user/dsr/delete/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

Which gave me the following error:

```json
{"code":"BadRequest","message":"Value cannot be null.\r\nParameter name: internal-user-email\r\n","correlationId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
```

@joemellin told me the other day via e-mail that Microsoft is GDPR ready with this API. However the API fails to provide a copy of my data (#205) and now fails in the right to be forgotten with this error.

**Comment by jwargo** [comment]
@cuducos App Center support is provided through the chat button in App Center. The support team does not monitor the issues queue (although I've asked them to take a look at this). Have you turned off pop-up blockers in your browser?  Other customers have seen the chat icon when they turn off blockers in their browser.  There's no need to open a second issue for the same topic.

**Comment by cuducos** [comment]
> There's no need to open a second issue for the same topic.

It's **not** the same topic: API endpoints are different and errors are different. To be clear:

| Issue | API Endpoint | Error(s) |
|-------|--------------|--------|
| #205 | **Export** data | `Signature fields not well formed` and `Signature did not match` |
| #206 | **Delete** data | `Value cannot be null. Parameter name: internal-user-email` |

**Comment by cuducos** [comment]
I cannot login to `https://appcenter.ms` anymore (_Your email or password were incorrect_) which might tell me that despite the error reported in this issue my account was deleted. But I cannot confirm since instead of a success message I got an error.

**Comment by iageoghe** [comment]
@cuducos It looks like we left out a finer point in our docs: namely that customers (or former customers in this case) should pass the [email associated](https://openapi.appcenter.ms/#/operations/gdpr/DataSubjectRight_DeleteStatusRequest) with the deleted account. This email isn't kept, but hashed and checked along with the token against the record of deletion. 

Would you mind trying again passing your email as a variable in the QueryString?

**Comment by cuducos** [comment]
Like a charm, @iageoghe : )

```sh
$ curl https://api.appcenter.ms/v0.1/user/dsr/delete/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\?email\=xxxxxxxxxx@xxxxxxxx.xxxx
```

Gave me:

```json
{"status":"InProgress"}
```

Sweet ❤️ Many many thanks : )

Not sure if I can close this issue (as my _individual_ issue is settled) or if you wanna let it open as a reminder to include this in the docs. It's up to you now, peeps.

**Comment by iageoghe** [comment]
Thanks @cuducos! We will close the issue and update the documentation today.
