### ISSUE TITLE
Appcenter integraton compile keyword

### ISSUE THREAD

**Issue by freeknortier** [MicrosoftDocs/appcenter-docs#207]
In the documentation it states the following : 

`dependencies {
    def appCenterSdkVersion = '1.6.1'
    compile "com.microsoft.appcenter:appcenter-analytics:${appCenterSdkVersion}"
    compile "com.microsoft.appcenter:appcenter-crashes:${appCenterSdkVersion}"
}
`

The compile keyword has been deprecated for Android. What should it be replaced with?

**Comment by guperrot** [comment]
Hi, you can use implementation instead of compile.
