### ISSUE TITLE
Extra variables

### ISSUE THREAD

**Issue by alexsorokoletov** [MicrosoftDocs/appcenter-docs#209]
Would be great to get "organization id" or "organization name" and "application id" so that we can use them in a generic scripts, for example, to build url to the current build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca50588e-c8ad-2b8e-683f-bc5fc612dfe4
* Version Independent ID: 5d9513bd-d179-eaeb-96aa-06bd5ba0224f
* Content: [Build Scripts - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#app-center-variables)
* Content Source: [docs/build/custom/scripts/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/scripts/index.md)
* Service: **vs-appcenter**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by lucas-james** [comment]
As a workaround you can set them as extra environment variables in your build configuration, but agreed...it wouls be nice if these values were provided out of the box :)

**Comment by jwargo** [comment]
@alexsorokoletov thanks for the suggestion, the product team added this suggestion to the list.

**Comment by alexsorokoletov** [comment]
Thank you!
Well I can do a lot of things manually right? :) it’s just a question of convenience 

Alex
