### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Marcelino1965** [MicrosoftDocs/appcenter-docs#210]
Schuppig g

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1709b666-1277-498f-5a89-b907c8ce881b
* Version Independent ID: 648c03f3-9822-31cc-0c4f-4d4a0d928ac3
* Content: [Using App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/#set-up-your-app-center-account)
* Content Source: [docs/dashboard/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/index.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by jwargo** [comment]
@Marcelino1965 Do you have a question or comment about the App Center docs?
