### ISSUE TITLE
Order of all to Crashes.SetEnabledAsync

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [MicrosoftDocs/appcenter-docs#211]
Crashes.SetEnabledAsync has to be called after AppCenter.Start other wise no crash reports are uploaded and it results in the error 
"Crashes service hasn't been started. You need to call [MSAppCenter start:YOUR_APP_SECRET withServices:LIST_OF_SERVICES] first."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a98dc868-6ec0-4d6e-652a-ed90d6c092b4
* Version Independent ID: d6061a26-6aef-be3a-c89a-3c8b290e2c9a
* Content: [App Center Crashes for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin)
* Content Source: [docs/sdk/crashes/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@Steven-Mark-Ford I've asked the team to take a look at this.

**Comment by elamalani** [comment]
@Steven-Mark-Ford Crashes.SetEnabledAsync() is set to true by default when you use AppCenter.Start()  API. It is not required to call the API before start.

**Comment by Steven-Mark-Ford** [comment]
Sorry I meant it has to be called AFTER start not before (I have updated my original comment above). Thanks for the info about its default value. I still think that the docs should mention somewhere that it should be called after start, or even better, prevent this behavior and still allow the crash reports to be uploaded regardless of the order of call. Calling it before start() breaks the crash report system for the rest of the runtime until you restart the app.

**Comment by elamalani** [comment]
@Steven-Mark-Ford You are not required to call this API even after Start() API. It's surprising that your crash reports are sent to our backend only after you call this API. Can you enable verbose logging and share the console logs with us to investigate it further?

**Comment by Steven-Mark-Ford** [comment]
@elamalani my crash reports go up if I don't call this method. But I think the documentation needs to be updated.

**Comment by elamalani** [comment]
@Steven-Mark-Ford  What changes are you suggesting in the docs? As I mentioned, you should still see the crash getting uploaded without calling this API.

**Comment by Steven-Mark-Ford** [comment]
Not a big issue but you could mention somewhere that "Crashes.SetEnabledAsync" should not be called before "AppCenter.Start". But yeah, I suppose this could just clutter the docs. I'm happy if you want to close this.

**Comment by vinaypancholi** [comment]
What will be expected behavior if the application crashed and on app restart, internet is not available then how logs will be synced?
Is this handling automatic syncing the logs/error report when the internet is available?

**Comment by jwargo** [comment]
@vinaypancholi yes, thats how it works.
