### ISSUE TITLE
"There should be no signing configurations in the Gradle configuration in the repository"

### ISSUE THREAD

**Issue by JeremyBradshaw7** [MicrosoftDocs/appcenter-docs#212]
What exactly does this mean? If I remove all entries under signingConfigs in build.gradle the AppCenter build shows the error:
Execution failed for task ':app:validateSigningRelease'.
&gt; Keystore file not set for signing config release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb88b888-1e68-8a75-efa4-cef2c33d4369
* Version Independent ID: 2fd3c90f-d7e5-5af3-9a50-b5571ac84995
* Content: [Android Code Signing Setup in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/android/code-signing)
* Content Source: [docs/build/android/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/android/code-signing.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@derpixeldan can you help here?

**Comment by dipree** [comment]
@ranterle can you help here?

**Comment by matthiaswenz** [comment]
The underlying reason for this piece is that it is wise from a security standpoint to not check in your signing credentials into your repository.
Another point to note is that if your app is already signed through the Gradle build steps, trying to resign it in the manual signing step will most likely fail.
So I think this is where this reference comes from - it can definitely be formulated more clearly. How about:
"If you decide not to put your signing credentials into your repository, you can also upload the keystore and configure the signing credentials through App Center. In this case, App Center will first build your Android app and then perform a manual signing step after the successful build.
Since trying to sign a build twice is not supported, please make sure that if you provide the signing credentials manually, you have no conflicts with signing configurations in your Gradle configuration for the chosen build variant."

**Comment by vforvasile** [comment]
@ranterle thank you for explaining!
One question though: if I set the keystore inside AppCenter, which parts of the build.gradle config should I remove in order for the signing release to be set only once?

**Comment by matthiaswenz** [comment]
@vforvasile do you see any errors with your current configuration? Can you help me better understand what part about it you only want to be set once?

**Comment by byrnedo** [comment]
@vforvasile Did you get an answer to this? I'm having the same trouble, I just have an 'if env is set' section in my signing config (as they describe in the react native docs) but it's failing on appcenter

**Comment by bobber205** [comment]
Seeing this same error.

**Comment by glintpursuit** [comment]
> Seeing this same error.

Did you got solution ?

**Comment by matthiaswenz** [comment]
@bobber205 @Abhi-Tech9 Sorry for the late response - to help you fix these potential problems, as this is a ticket for the App Center documentation, can you provide more details on your configuration and what exact error you are seeing? You can also share this in private with our customer service, ideally with the information about which app in App Center you're seeing problems with.
Alternatively, you can also create an issue in our [public repo](https://github.com/microsoft/appcenter/issues).

**Comment by glintpursuit** [comment]
@ranterle, thanks for response. 

I am trying to use App Center build with KeyStore provided on App Center. 

As per the latest suggestion from customer service, I have disables signing config in build.grdle by commented it out, like below 

// signingConfigs {
    //     release {
    //         // storeFile file(MYAPP_RELEASE_STORE_FILE)
    //         // storePassword MYAPP_RELEASE_STORE_PASSWORD
    //         // keyAlias MYAPP_RELEASE_KEY_ALIAS
    //         // keyPassword MYAPP_RELEASE_KEY_PASSWORD
    //     }
    // }

but now I am getting below error 

A problem occurred evaluating project ':app'.
> Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.

so documentation does't exactly say what settings we don't need put in build.gradle to use appcenter provided signing key 

Note: I am trying to build this to use .aab experimental feature enabled in app center.

**Comment by matthiaswenz** [comment]
@Abhi-Tech9 This means that your Gradle configuration is referencing the signing configuration `release` somewhere, i.e. you have a line like `signingConfig signingConfigs.release` in your configuration somewhere - so removing the entire signing configuration will not be sufficient.

I will follow up with you from the App Center support to further keep this issue for our documentation.

**Comment by glintpursuit** [comment]
Yes, after commenting below mentioned line getting new error but it is something related to not proper singing key 

Commented out 
  //signingConfig signingConfigs.release

Error : 

jarsigner: Certificate chain not found for: ***.  *** must reference a valid KeyStore key entry containing a private key and corresponding public key certificate chain.

**Comment by dickwyn** [comment]
I got the gradle file to reference the keystore values referenced in the branch build configuration by commenting out the following line(s) in the `android/app/build.gradle` file

```
signingConfigs {
    debug {
        storeFile file('debug.keystore')
        storePassword 'android'
        keyAlias 'androiddebugkey'
        keyPassword 'android'
    }
}
buildTypes {
    release {
        // Caution! In production, you need to generate your own keystore file.
        // see https://facebook.github.io/react-native/docs/signed-apk-android.
        //signingConfig signingConfigs.debug
        minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
    }
}
```

Got confused with the code sample in the docs that adds `releaseSigningConfig` to the `build.gradle` file.

Turns out if you upload the keystore and fill in the keystore credentials in the build configuration, there is no need to make any changes to the `build.gradle` file

**Comment by MrTarantula** [comment]
I know this is closed, but maybe somebody can provide some insight. I'm using option 2, but if I comment out signingConfig as above, gradle fails to build:

```
Initializing gradle...                                              1.0s
Resolving dependencies...                                           4.8s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      10.1s
Gradle build failed to produce an Android package.
```

This happens locally as well as in App Center. So what should my signing configuration look like in order to have App Center sign it?

**Comment by dickwyn** [comment]
@MrTarantula assuming that your build type in your App Center configuration is set to "release"

```
buildTypes {
    ...
    release {
        minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
   }
}
```

Also, you need to drop in your `.keystore` or `.jks` file into your config alongside your configuration.

<img width="595" alt="Screen Shot 2019-10-24 at 2 12 16 PM" src="https://user-images.githubusercontent.com/11251672/67526037-cb56b600-f668-11e9-91a5-05dc104a9083.png">

**Comment by MrTarantula** [comment]
That's exactly how I have it configured currently. It fails every time. If I add back `signingConfig signingConfigs.debug` then it will complete, but will not install on a device.

**Comment by dickwyn** [comment]
Did you set your build variant to `release`?

**Comment by MrTarantula** [comment]
Yes. I should note that I am building with Flutter, using the post-clone script from [here](https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/flutter/android-build/appcenter-post-clone.sh). The script also sets the release flag.

**Comment by dickwyn** [comment]
I am not familiar with how app signing works on Flutter. My project is on React Native

**Comment by MrTarantula** [comment]
It still builds and signs with standard Gradle, so it shouldn't be an issue.

**Comment by dickwyn** [comment]
Were you able to generate an `.apk` or `.aab` with your gradle config?

**Comment by MrTarantula** [comment]
On my local machine, with the same code, the same `android.keystore`, but with the release config explicitly set, yes, it builds and signs.

**Comment by MrTarantula** [comment]
but if there is no signingConfig set it will fail.

**Comment by dickwyn** [comment]
Yes for local, you need to have a signingConfig that specifies the keystore and its credentials but (based on my experience) by allowing App Center to sign the application, you don't need to have a signingConfig for `release`.

**Comment by vforvasile** [comment]
If you check the box `My gradle settings are set to sign automatically` then you must specify in **signingConfigs** the keystore.

![image](https://user-images.githubusercontent.com/9382283/67550074-4e7e1780-f70e-11e9-8759-6a0b9a7ff9b9.png)

For instance:
```
    signingConfigs {
        debug {
            storeFile rootProject.file("app/debug.keystore")
            storePassword "********"
            keyAlias "androiddebugkey"
            keyPassword "********"
        }
        release {
            storeFile rootProject.file("app/release.keystore")
            storePassword "********"
            keyAlias "release-alias"
            keyPassword "********"
        }
    }
```
And below in **buildTypes**:

```
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        } 
        release {
            signingConfig signingConfigs.release
        }
    }
```
_This approach will work if you have your keystores in `android/app` directory_
Hope this helps.

**Comment by MrTarantula** [comment]
This is what finally worked for me, from flutter/flutter#18232:

```gradle
release {
            signingConfig null

            applicationVariants.all { variant ->
                variant.outputs.all { output ->
                    output.outputFileName = "app-release.apk"
                }
            }
}
```

I still consider this a hack/workaround, but someone may want to put it in the docs.

**Comment by MrTarantula** [comment]
And for flavors:

```gradle
applicationVariants.all { variant ->
    variant.outputs.all { output ->
        if (variant.buildType.name == "release") {
            output.outputFileName = "app-${variant.baseName}.apk"
        }
    }
}

**Comment by vargasjona** [comment]
Maybe someone is facing a similar issue I am using React Native and I solve it by adding this

gradle.properties
```
MYAPP_UPLOAD_STORE_FILE=something.keystore
MYAPP_UPLOAD_KEY_ALIAS=secure-alias
MYAPP_UPLOAD_STORE_PASSWORD=secure-pass
MYAPP_UPLOAD_KEY_PASSWORD=secure-key
```

build.gradle

```
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE') && file(MYAPP_UPLOAD_STORE_FILE).exists()) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
``` 

```
 release {
        if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE') && file(MYAPP_UPLOAD_STORE_FILE).exists()) {
            signingConfig signingConfigs.release
        }
        minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
 }
```

**Comment by manish0707** [comment]
@jonra1993 In this case will I have to upload my keystore file to git...??

**Comment by vargasjona** [comment]
Hello @manish0707 yes you should and also use environment variables to secure keys
