### ISSUE TITLE
Error in Android app build configuration

### ISSUE THREAD

**Issue by carlosbasecodeit** [MicrosoftDocs/appcenter-docs#216]
I have a solution with an android project and an iOS project tha I have to configure in App Center. I didnt have any problems with the build configuration for iOS, but I have problems with the configurations of the android project.
After link my repository I see all my branchs in this repository but when I try to configure the build in any branch, the Build Configuration pop up give me this error "We couldn’t find any Xamarin Android projects in your branch."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af635c53-8b58-a6c4-bd0f-cefb71bbfee4
* Version Independent ID: c388dd37-6b0c-47f0-b2a1-58590b3d3de5
* Content: [Xamarin SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/xamarin)
* Content Source: [docs/sdk/troubleshooting/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@cafe1984 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
