### ISSUE TITLE
YAY

### ISSUE THREAD

**Issue by transdigiware** [MicrosoftDocs/appcenter-docs#217]
Build now as soon as posible with the central apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06813350-a37b-a4a2-fdbc-a59caefb9f32
* Version Independent ID: 29787958-5b4e-efc2-2af5-2af0ee53216e
* Content: [App Center Build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/)
* Content Source: [docs/build/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/index.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@transdigiware are you asking a question about the docs or suggesting an edit to the docs? I can't tell.

**Comment by transdigiware** [comment]
just suggesting like that.s ,, @

**Comment by transdigiware** [comment]
sugested @jwargo

**Comment by jwargo** [comment]
@transdigiware I'm sorry, I don't understand what you're telling me.

**Comment by transdigiware** [comment]
Coba translator semoga memahami
