### ISSUE TITLE
Issue with `SECRET`

### ISSUE THREAD

**Issue by adteulade** [MicrosoftDocs/appcenter-docs#218]
I think you should add the following to this page:

SECRET is an undocumented VSTS reserved prefix, please only use this string if something precedes it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f3af3f-ef07-8896-4b3c-05cef163b51a
* Version Independent ID: b4b1f6a4-5975-358b-1cf4-f7b10a2245cd
* Content: [Environment Variables - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/)
* Content Source: [docs/build/custom/variables/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/variables/index.md)
* Service: **mobile-center**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by jwargo** [comment]
@adteulade thanks, I'll have the team take a look at making the change.

**Comment by dipree** [comment]
Hey, we're adding a prefix which is not exposed to users. Regardless of what you specify on App Center, it won't collide with anything in VSTS. Thanks, Dan
