### ISSUE TITLE
Is it possible to provide additional msbuild parameters?

### ISSUE THREAD

**Issue by lassana** [MicrosoftDocs/appcenter-docs#219]
In the AppCenter logs I found `msbuild` command usage:

```
/Library/Frameworks/Mono.framework/Versions/5_10_1/bin/msbuild /Users/vsts/agent/2.136.1/work/1/s/Droid/***.Droid.csproj /t:PackageForAndroid /p:Configuration=Develop
```

Is it possible to add additional `msbuild` arguments? I'm especially interested in setting "/p:AotAssemblies" and "/p:AndroidSupportedAbis".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72f6fe-74d6-696e-e709-5f6d577c0a58
* Version Independent ID: b3d0ea8b-5a1f-bf71-7dc2-9685cf23c00b
* Content: [Get Started with Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin)
* Content Source: [docs/sdk/getting-started/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@lassana I'm a little unclear about your question. Are you asking about the SDK or one of the services?  

Your best bet with questions like this is to ask our support team.  App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

If there's a doc update that should be made after you have your answer, the support team will let us know.

**Comment by lassana** [comment]
@jwargo I'm asking about AppCenter Build services: https://docs.microsoft.com/en-us/appcenter/build/

**Comment by jwargo** [comment]
@lassana OK, that makes sense. I thought so, but the comment came in from the Xamarin getting started doc. You really should ask through support. In the mean time, one of the Build PMs will check in here.
