### ISSUE TITLE
Push API/SDK Limitations

### ISSUE THREAD

**Issue by bdwellons** [MicrosoftDocs/appcenter-docs#220]
It would be nice if the documentation listed limitations of the APIs. After extensive local trial and error it looks like getting the device's installId in Cordova set by AppCenter is not possible? After pulling what appears to be the installId from the GET notifications API, trying to send a push notification to a single installId from the APIs to Cordova apps is also not possible. Can you please confirm that this is the case, and if so, please modify documentation to describe current limitations of AppCenter services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb96601-f906-374d-b0d8-537e5f80de3e
* Version Independent ID: b66d21ae-1205-3d76-f577-d58891382c08
* Content: [App Center Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/pushapi#send-notifications-to-device-ids)
* Content Source: [docs/push/pushapi.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/pushapi.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by bdwellons** [comment]
Sorted it out later in the evening. AppCenter.getInstallId only seems to work when it is passed a success function as the first parameter and not a second function as an error handler. Don't have the time to dig in to why now, but this can be closed.

**Comment by jwargo** [comment]
@bdwellons we're planning on a refresh of the docs, and one of the things I want to add is a limitations section to each service's docs.  I'm not sure when this will happen, but it's in my plan.
