### ISSUE TITLE
getInstallId for Cordova

### ISSUE THREAD

**Issue by bdwellons** [MicrosoftDocs/appcenter-docs#221]
Is the following mechanism or something similar available in Cordova AppCenter?
await AppCenter.getInstallId()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 846243f4-8201-c23f-9719-63326aae7572
* Version Independent ID: 5c8f7b51-1102-b427-a650-06cfc11f71e6
* Content: [Other React Native APIs - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/react-native)
* Content Source: [docs/sdk/other-apis/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/other-apis/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@bdwellons The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

For this particular question, you're probably better off asking support. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
