### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by Sleeplikelion** [MicrosoftDocs/appcenter-docs#222]
nop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by jwargo** [comment]
@Sleeplikelion do you have a question or comments about the docs?
