### ISSUE TITLE
Using Github app extremly confusing

### ISSUE THREAD

**Issue by macrozone** [MicrosoftDocs/appcenter-docs#223]
The documentation and the whole userflow about github integration is really confusing and flawed.

I managed to setup app center that it builds on pushes on my configured branches, but not when i created a PR on a branch. The checks just did not appear

I had to restart completly from scratch and add the github market place app and then reconfigure completly everyhting.

This leads to errors and waste of time.

- it should be possible to migrate existing apps to use the back reporting to github ("checks")
- configuring appcenter should make it impossible to miss the full integration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de5a7b9-2742-0ea0-3170-d6fb5da0d2de
* Version Independent ID: f24ff5eb-4fb5-7a96-ff76-6c96386c9498
* Content: [Connecting Repositories Using the GitHub App - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/github-app#connecting-existing-apps)
* Content Source: [docs/build/github-app.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/github-app.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by macrozone** [comment]
also this setup page that is sent through email has to be accessible through some UI.

How i am I supposed to ad a new app otherwise? relying on an email is a really bad idea

**Comment by jwargo** [comment]
@macrozone I've asked the product's PM to respond to this.

**Comment by macrozone** [comment]
@jwargo This has already been reported two months ago: https://github.com/MicrosoftDocs/appcenter-docs/issues/147

it seems i am not the only one struggling with this.

Imaging this situation:

- you goto appcenter.ms and click on "add new app" and create a new app
- you configure all your branches, distributions, tests, etc. in appcenter and you are able to build whenvere someone pushes something on a branch
- you then want to have also checks and builds whenever a developer opens a Pull Request.
- bam, you are screwed, you have to restart from scratch, because you did not know that there is a special "github marketplace onboarding" flow.

Also its now nearly impossible to add more apps in the future using this secret advanced github interation. There is no Ui to do so, but the secret one you get, when you click on the email link, that you got maybe some weeks/months/years ago when you added the app center marketplace app to github?

It should be like this:

- goto https://appcenter.ms/
- click on "add new repository"
- select an existing repository with a hint that you can grant access to additional repos throug github if you need

it should be either impossible to add apps without this - OR - it should be super easy to connect "manual" created apps in app center to existing repos with the full github integration

**Comment by jwargo** [comment]
@macrozone you can already do that. The GitHub app, as I understand it, is just a way to do this *from* GitHub. You can already log into App Center, create an app and point it to a GitHub repo, that functionality has been in there since before launch.

**Comment by macrozone** [comment]
@jwargo that is true, that's how we have set it up before. But then, you can't trigger builds from github pull requests, you don't have this "checks" integration which reports back go github.

the documentation even sais that you have to restart from scratch: https://docs.microsoft.com/en-us/appcenter/build/github-app#connecting-existing-apps

as much as i love app center, this is inaccatable



Edit: To be super clear, i am talking about this integration:

<img width="777" alt="bildschirmfoto 2018-07-18 um 15 39 52" src="https://user-images.githubusercontent.com/1972353/42885354-0d3cf690-8aa1-11e8-8427-4bf95f319318.png">

And the ability to trigger builds on Pull requests, rather than pushes on branches:

<img width="795" alt="bildschirmfoto 2018-07-18 um 15 42 08" src="https://user-images.githubusercontent.com/1972353/42885433-340df3aa-8aa1-11e8-96ea-4eb91872af7f.png">

**Comment by jeremycbutler** [comment]
I am having the same issues and unable to locate my welcome email. @macrozone How did you re-trigger a welcome email to properly set it up?

**Comment by nilofer** [comment]
@jeremycbutler @macrozone we just enabled the ability to add a new repository without the link from the welcome email. You can follow instructions to [connect a new repository](https://docs.microsoft.com/en-us/appcenter/build/github-app#connecting-a-new-repository) and adjust your installation configuration in GitHub.

**Comment by nilofer** [comment]
@macrozone thank you for the rest of the feedback you provided. This is helpful for us in understanding how to make this experience better!

**Comment by macrozone** [comment]
@nrajpurkar awesome, I can confirm this works. But some feedback on it:

- if you have selected "All repositories" in github under "Repository access", you have to change it to something else and back. Then you can save and you will see the setup screen from appcenter.
- its probably better to only give access to the apps you need, so you won't run into that anyway. Maybe you can mention that in the docs!
- Connecting Existing Apps is still not possible

**Comment by putuyoga** [comment]
connecting existing apps?

**Comment by nilofer** [comment]
@putuyoga please see the [reply](https://github.com/MicrosoftDocs/appcenter-docs/issues/147#issuecomment-436459952) on the other issue you commented on.

**Comment by jlewicki-nevo** [comment]
I see this issue is closed, but I wanted to add to the feedback that not being able to add github PR checks to an existing app is truly lousy.  It's a shame since lots of the rest of the product is so good!  

Hopefully this will be addressed at some point.

**Comment by jwargo** [comment]
@jlewicki-nevo The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, especially if you have product feedback, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
