### ISSUE TITLE
App Center don't restores from public NuGet feeds

### ISSUE THREAD

**Issue by GanesanRengasamy** [MicrosoftDocs/appcenter-docs#225]
Hi

I have added the NuGet.config file as you mentioned in the document and push that in the github and trying to build my application by AppCenter. But I have faced the NuGet restore issue. 

![image](https://user-images.githubusercontent.com/16695209/42924243-e6967fd8-8b46-11e8-98cc-85874b683a22.png)

Please find my Github repository as below,

https://github.com/GanesanRengasamy/UWPSample.git

Please help me to resolve this NuGet restore issue

Thanks,
Ganesan R.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be2ace35-a6ef-349a-e009-ca55e3778602
* Version Independent ID: 85a92e95-828a-54f8-b7e7-4f86b8e76abc
* Content: [Configure a C# UWP app in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/windows/uwp/first-build#37-nuget-restore)
* Content Source: [docs/build/windows/uwp/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/windows/uwp/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by GanesanRengasamy** [comment]
Hi, 

I have added the new test app again in appcenter and again link my Github repository and trigger the build from appcenter now the NuGet packages has been restored successfully from public NuGet feeds. 

Thanks,
Ganesan R.

**Comment by jwargo** [comment]
@GanesanRengasamy The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
