### ISSUE TITLE
AppCenter doesn't list correct Android flavor dimensions under "build variant"

### ISSUE THREAD

**Issue by jamesem** [MicrosoftDocs/appcenter-docs#226]
Does AppCenter plan to ever support an Android project which utilises "flavor dimensions"?

When using such a project, the Build variant drop down menu does not list correct assemble configurations, so builds do not succeed.

**Comment by jwargo** [comment]
@jamesem The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
