### ISSUE TITLE
Apps Center "chat support" button does not appear in Firefox

### ISSUE THREAD

**Issue by jamesem** [MicrosoftDocs/appcenter-docs#227]
Hi,

I have noticed that the blue button that is referred to on the following "Support" page, doesn't actually appear if you are using Firefox.

https://intercom.help/appcenter/getting-started/getting-help-with-app-center

Firefox 61.0.1 (64-bit) on OSX 10.13.5

**Comment by jwargo** [comment]
You have to turn off any pop-up blockers, etc. I just tested it on FireFox for macOS 61.0.1 and it appears just fine.

**Comment by jamesem** [comment]
Thank you, I do not use any third party popup blockers, however after turning off "Tracking Protection" in Firefox, the blue button appeared.

Is it possible to mention this in the help docs, when pointing customers towards the blue button? I had originally tried to find that support option and had given up.

**Comment by jwargo** [comment]
@jamesem yeah, absolutely. I'll change the getting started doc now.

**Comment by jamesem** [comment]
Perfect, thanks

**Comment by jwargo** [comment]
@jamesem check out the getting started doc now, does that work?

**Comment by jamesem** [comment]
Looks great.
