### ISSUE TITLE
y

### ISSUE THREAD

**Issue by Sleeplikelion** [MicrosoftDocs/appcenter-docs#228]
[Enter feel ack here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b892ccc-dfc5-3e39-e69e-5416a2423dfc
* Version Independent ID: 01f9db85-32f1-5a6e-df5e-731000696967
* Content: [App Center Crash Reporting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/crashes/)
* Content Source: [docs/crashes/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/crashes/index.md)
* Service: **vs-appcenter**
* GitHub Login: @anlinde
* Microsoft Alias: **anlinde**

**Comment by jwargo** [comment]
@Sleeplikelion do you have a question or comment about the App Center docs?
