### ISSUE TITLE
More info on push notification "type" value

### ISSUE THREAD

**Issue by c-lamont** [MicrosoftDocs/appcenter-docs#229]
I would like to know more about the push notification "type" value. Are the two options above "devices_target" and "audiences_target" the only two options? Is it possible to send a notification to all devices for example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb96601-f906-374d-b0d8-537e5f80de3e
* Version Independent ID: b66d21ae-1205-3d76-f577-d58891382c08
* Content: [App Center Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/pushapi#send-push-notification-to-an-audience)
* Content Source: [docs/push/pushapi.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/pushapi.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by dimazaid** [comment]
Hi @c-lamont! Yes, you can use "null" and this will send it to all registered devices (broadcast).

**Comment by c-lamont** [comment]
Hi @dimazaid, thanks for the info.

Is there somewhere to view all the possibilities for sending push notification?

**Comment by jwargo** [comment]
@c-lamont Dimah made a [change to the docs](https://docs.microsoft.com/en-us/appcenter/push/pushapi) yesterday to reflect this, take a look.

**Comment by c-lamont** [comment]
Thanks @dimazaid!
