### ISSUE TITLE
Event Metric Limits - Property Count

### ISSUE THREAD

**Issue by thomasphillipsgb** [MicrosoftDocs/appcenter-docs#230]
"The portal will show up the ten property values with highest count."
Do these still get tracked anyway? I see there is an 'Other' category.
I ask this is because we are looking to run some App Insights through Azure. I'm not certain if we can create an event type which will log 50+ unique property values. Or if we're stuck with having to track specific events, which can only track 200 daily (as per "The maximum number of distinct custom events that can be tracked daily is 200...")

**Comment by jwargo** [comment]
@Maxgamerboy1 the easiest way to get help with questions like this is to use App Center support. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
