### ISSUE TITLE
How can I specify `xcodebuild -configuration` when build on AppCentre?

### ISSUE THREAD

**Issue by jonakyd** [MicrosoftDocs/appcenter-docs#232]
I have many configuration setups for my XCode project instead of just `Debug` and `Release`. How can specify that when I build with AppCentre?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc01291c-f6a0-4610-a27d-60718852390d
* Version Independent ID: 2b51b117-6b8c-f4d9-a2b2-43c891d20171
* Content: [Configure a Objective-C or Swift iOS build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/first-build)
* Content Source: [docs/build/ios/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@jonakyd The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by pateljay43** [comment]
@jonakyd App center is using `xcodebuild archive` command and we can specify a scheme to build with a branch. You can change the configuration in that Scheme configuration for `Archive` step (select Debug or Release)

**Comment by thorbenprimke** [comment]
@pateljay43 - thanks for the tip! This should be noted in the settings / build configuration screen on App Center. As in - we use the `archive` type to build your app and you should make sure that the intended configuration is set. 

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2F10UeedrT5MIfPG%2Fgiphy.gif&token=yay" data-gitmeme-token="yay"><img src="https://media1.giphy.com/media/10UeedrT5MIfPG/giphy.gif" title="Created by gitme.me with /yay"/></a>

**Comment by pateljay43** [comment]
Yes. Personally I kind of agree with mentioning that somewhere, but the only reason I believe why its not shown on AppCenter settings webpage is because someone could have assumed - as we are making a "build" which can be installed on an apple device later on we will know that it is archiving. I mean you cannot install a build, over the air, by `xcodebuild build` action. If you know what I mean

**Comment by ponchautf** [comment]
Hi, in our case, we use xcode configuration to produce "flavored" application (we have our main application but for some VIP customer we produce a dedicated app, almost with same feature but different layout)
In this case, we are searching a way to indicate the configuration to use on the build settings.
Is it possible? foreseen?
