### ISSUE TITLE
App Store two-factor auth

### ISSUE THREAD

**Issue by kirk-marple** [MicrosoftDocs/appcenter-docs#233]
The Apple Dev Program now requires two-factor auth to be enabled, in order to enroll.

But it appears that connecting the iOS App Store via App Center doesn't yet support two-factor auth?

I think I'm blocked from publishing to the app store then?  Any workarounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edcd9010-7381-ef0a-85ee-3289b742c8de
* Version Independent ID: 63c5a53d-e211-a17e-e0c0-27638748da7d
* Content: [Publish to iTunes - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple#feedback)
* Content Source: [docs/distribution/stores/apple.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/apple.md)
* Service: **vs-appcenter**
* GitHub Login: @pnghub
* Microsoft Alias: **gned**

**Comment by pnghub** [comment]
Thx for the feedback Kirk. You are right in that iOS App Store updates via App Center does not currently support two-factor auth and will need to use the App store directly for store publishing in this scenario. This item is in the backlog, though we do not have an ETA yet. Your feedback is appreciated and will help us with data to build a case for getting this higher up in the priority order.

**Comment by jwargo** [comment]
@kirk-marple The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by kirk-marple** [comment]
@jwargo Understood, but my point for posting it here was that it likely needs to be documented, given anyone following the instructions to create a new Apple Dev Program account would run into the same problem.   I'll followup with support to see about any workarounds, thanks.

**Comment by jwargo** [comment]
@kirk-marple yes, absolutely - just ask Support to mark it needing a doc update and we'll update the docs based on the results you get from your support call.

**Comment by Eric-Dunaway** [comment]
Is there a doc update for how we are supposed to set up Apple Store with App Center? 

Does App Center no longer support  Apple Store now that 2FA is required?

**Comment by jwargo** [comment]
@Eric-Dunaway we're working on a doc update.

**Comment by BorlandFA** [comment]
I've ran into the same problem and I am blocked... It would be really good if App Center supports 2FA.

**Comment by ghost** [comment]
I am blocked on this as well. Any update on timeline to support 2FA for connecting the iOS App Store?

**Comment by jwargo** [comment]
We just published a workaround to the docs. If you're part of a team and have someone with an older Apple ID (that doesn't require 2FA) then you can share those credentials via App Center.

**Comment by gtbuchanan** [comment]
That's the _workaround_? Are you joking?

App-specific passwords don't seem to work either for whatever reason.

Glad I'm just getting around to looking at VSAC. Doesn't seem to be a viable option at the moment.

**Comment by jwargo** [comment]
@gtbuchanan No, we're not - that's the current work-around.  Unfortunately, when Apple changes their requirements or systems, it takes us some time to adjust. We're working on a solution, please be patient.

**Comment by gtbuchanan** [comment]
I understand. My astonishment is based on the fact that Apple had 2FA and app-specific passwords long before they made it required (circa 2015). Just seems like this could have been avoided or made more clear up front. Nonetheless, I'm glad it's being looked at.

**Comment by thchia** [comment]
> However, old Apple IDs can still connect to App store connect without two-factor authentication.

Does this mean that I can establish the connection to App Store connect with an Apple ID that is *not* enrolled in any kind of Developer Account?

**Comment by jwargo** [comment]
@thchia No, that's not what it's saying.

**Comment by gabors** [comment]
I'm shocked that Microsoft can say that AppCenter supports Apple AppStore or TestFlight integrations. You guys should be ashamed.

**Comment by jwargo** [comment]
@gabors The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. We understand that its inconvenient when issues like this arise, but all we can do is react to the changes Apple made to their systems. 

We'll fix this as quickly as we can.  In the mean time, please be constructive with your feedback.

**Comment by jwargo** [comment]
@gabors @thchia @gtbuchanan @kirk-marple @Eric-Dunaway @BorlandFA @raju-eitr Support for Two Factor Authentication (2FA) available now - [read the documentation](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple#adding-two-factor-authentication). Use the support chat button in the lower-right corner of any App Center page if you have any issues.

**Comment by gabors** [comment]
Nice work. Will try it out.

**Comment by stevehurcombe** [comment]
This isn't working for me. I have to reconnect the account every day by entering the two factor code. 

The build fails with this error (wasting my free build minutes in the process!).

##[error]{"release_notes":"Layouts tweaks","destinations":[{"id":"00000000-0000-0000-0000-000000000000","name":"iTunes Connect users","message":"Failed to publish to store. Error: Service Connection is not valid. Please use PATCH to update the connection","code":"unauthorized"}],"code":"partially_succeeded","message":"Release notes string or mandatory update boolean were successfully updated, but failed to distribute to some or all of the destinations."}

**Comment by jwargo** [comment]
@stevehurcombe The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by Lucas-Geitner** [comment]
>Thanks  @jwargo !

**Comment by elkaz-tennis** [comment]
@jwargo it appears app-specific passwords are no longer working. I've generated a few different ones and used them with an Apple ID (email), and each returns the following error:

> Ooops, wrong username or password.

Any thoughts?

**Comment by WDRed** [comment]
User menu (upper right corner) > Account settings > Developer account (Pencil icon) Edit action > If you will see "Inactive" in red then navigate to 3 dots menu and reconnect
