### ISSUE TITLE
Two factor not supported?

### ISSUE THREAD

**Issue by vishnu4** [MicrosoftDocs/appcenter-docs#235]
If i go inside my IOS application in app center, and go to distribute/stores and click on "connect to store", i'm given an interface to connect to an apple developer account.  When i try to do this, i get an error that says 'Two-Factor Authentication is currently not supported'.  But the documentation above implies that it is supported.  

Since it's impossible to have an apple developer account w/out 2 factor authentication, any idea why the discrepancy between this document and the actual site exists?  And when it will be fixed?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de79b71-e877-4882-9b78-bb4084afeed7
* Version Independent ID: 0991f861-34cc-2b8d-f155-8005bda5e2df
* Content: [Managing your Apple ID and certificates - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/manage-apple-secrets)
* Content Source: [docs/dashboard/manage-apple-secrets.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/manage-apple-secrets.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by jwargo** [comment]
@vishnu4 We're aware of this issue and I've asked the PM to update the docs. In the mean time, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).  

Perhaps they know how to fix this while I work to get the docs updated.

**Comment by guillermodoghel** [comment]
Same issue..

**Comment by jwargo** [comment]
@guillermodoghel we've updated the docs with a [workaround](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple#two-factor-authentication-workaround) while we work to implement a more permanent solution.

**Comment by thomhubers** [comment]
@jwargo That's a dead link (I can't open it at least), do you have a workaround to open and read your workaround?

**Comment by jwargo** [comment]
@thomhubers sorry about that, that's not the right link. It's in the docs, nothing special. You can access it [here](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple#two-factor-authentication-workaround). and I fixed the earlier reference.

**Comment by thomhubers** [comment]
Thanks for the updated link. There's a big if in that workaround. When is the permanent solution expected?

**Comment by jwargo** [comment]
@thomhubers yep, we know it. We're working on a solution, it's on the [Roadmap](https://docs.microsoft.com/en-us/appcenter/general/roadmap), so that means we're working on it now.  No ETA, but we're working on it (sorry).

**Comment by thiago-rcarvalho** [comment]
Would be nice a fix for this asap. We don't have any accounts eligible for the workaround :(

**Comment by jwargo** [comment]
@stealthcold yes, absolutely. We understand and we're working on a solution.

**Comment by helgeu** [comment]
What would happen if appcenter could use an generated app password? Or is this a problem on the Apple side when authenticating again? This is possible in other apps so why not appcenter?

**Comment by jwargo** [comment]
@helgeu Can you provide a little more detail? I'm not sure what you're asking/suggesting.

**Comment by helgeu** [comment]
It was more like a question "is this possible to use"? https://support.apple.com/en-us/HT204397

If I try to generate such a password and then use this when trying to connect from appcenter, it just says "oops wrong password" or something.

**Comment by Oddj0b** [comment]
@helgeu Great question thanks for reaching out and providing context. We do **not** have support for the app-specific password right now.

The solution we are working on for the Apple App Store will require both the 6-digit code and an app-specific password. We are aware that it isn't optimal, but because we both need to login into the App Store connect website and use application loader, both are a hard requirement.

**Comment by helgeu** [comment]
@Oddj0b I do really not care if the solution is "hard to use" or have many steps and several logins. The only concern is that there exists a solution and I can use it. Apple was not really interested in "resetting" my id back to not using two factor, so the only hope is that this gets "some solution". Thx and keep up the good spirit and work ;-)

**Comment by gljubicic** [comment]
You can use Two Factor, but you have to have a device connected with that Apple ID. 
AppCenter does not support SMS two factor.

See screenshot below:
![image](https://user-images.githubusercontent.com/115181276/194383545-d7778989-979f-4f0d-8e98-624f75f64cdb.png)
