### ISSUE TITLE
cordova build

### ISSUE THREAD

**Issue by andrster** [MicrosoftDocs/appcenter-docs#236]
Is there any plan to Build for cordova in the future

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0087c543-d8f4-5ea6-5ac6-8b30ec1b9e6c
* Version Independent ID: 92b8f8de-268b-a249-46e9-053edf2e97c0
* Content: [App Center Platform Services Matrix - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix)
* Content Source: [docs/general/platform-service-matrix.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/platform-service-matrix.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@andrster We're evaluating it. We have some customers asking for it, but we have other things with higher priority on our roadmap right now.
