### ISSUE TITLE
How can we deploy multiple android APKs?

### ISSUE THREAD

**Issue by luisnaranjo733** [MicrosoftDocs/appcenter-docs#237]
Android apps typically ship multiple APKs to support various screen densities and CPU architectures. This is important to Android because of the inherent device fragmentation that exists on that platform.

How can we deploy multiple APKs to AppCenter through the VSTS build task? Right now, it only supports one apk path. If it supported multiple paths, the task could theoretically deploy multiple.

Does AppCenter itself support multiple APKs?

https://developer.android.com/google/play/publishing/multiple-apks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28aa9747-f64a-d886-487d-8ebb97d717b8
* Version Independent ID: 0c7edbb7-4bf7-f66c-c8a7-275308365f27
* Content: [Deploy VSTS Builds with App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/vsts-deploy)
* Content Source: [docs/distribution/vsts-deploy.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/vsts-deploy.md)
* Service: **vs-appcenter**
* GitHub Login: @andyzg
* Microsoft Alias: **t-anzha**

**Comment by jwargo** [comment]
@luisnaranjo733 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by pradeepvishwakarma** [comment]
Is there any workaround on this ?
I can't find relevant solutions. Can anyone help me into it.
