### ISSUE TITLE
This page is missing Windows/UWP instructions

### ISSUE THREAD

**Issue by brunck** [MicrosoftDocs/appcenter-docs#238]
This page is linked in App Center on the New Release window for UWP Distribution, but it has nothing about Windows distribution on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by jwargo** [comment]
@brunck thanks for bringing this to our attention, I'll have the PM take a look.

**Comment by gaknoll** [comment]
@brunck We are in the process of updating this to include UWP instructions. Thank you for pinging us about this!

**Comment by gittessie-qrypt** [comment]
it's also missing the MacOS instructions
