### ISSUE TITLE
AppCenter.Start() rises an exception

### ISSUE THREAD

**Issue by Disjes** [MicrosoftDocs/appcenter-docs#239]
Hello,

When I try to call AppCenter.Start("androidkey", typeof(Push)) from App.xaml.cs I get the following error on Android;

Java.Lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference

**Comment by jwargo** [comment]
@Disjes The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
