### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bruno-garcia** [MicrosoftDocs/appcenter-docs#24]
"UITest will hat test execution" should be: "UITest will halt test execution"
Where to fork and fix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0474be-6e14-b8e6-b6cf-934a04f0e509
* Version Independent ID: 4a79fc1d-8dca-1c17-718f-c30fda180f05
* [Content](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/index.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
Docs are public on Github at https://github.com/MicrosoftDocs/appcenter-docs. Feel free to fork and submit suggested changes.  I'll fix this one manually, thanks for pointing it out.

**Comment by bruno-garcia** [comment]
Pull request done. 

From docs there's just a link to 'give feedback' but no indication it's hosted here. 
Once I wrote the feedback I got a link to the issue created.

**Comment by putmanj00** [comment]
This article is dated 01/19/2019....has Microsoft mastered time travel?

**Comment by jwargo** [comment]
@putmanj00 fixed. Thanks for finding that.
