### ISSUE TITLE
Android Multiple Flavor Dimensions

### ISSUE THREAD

**Issue by navinilavarasan** [MicrosoftDocs/appcenter-docs#240]
Android Multiple flavor dimensions seems to be not supported and document does not contain this as a limitation.

**Comment by jwargo** [comment]
@navinilavarasan Can you give me some context here? Which service are you working with?

**Comment by navinilavarasan** [comment]
This is about the appcenter build service.The build service in appcenter is unable to discover android flavor dimensions properly and errors out. Thought a mention in the documents on the limitation would help people. More information about it can be found here: https://github.com/Naitbit/AppCenterGradleFlavors

**Comment by nilofer** [comment]
Hi @navinilavarasan, thanks for brining this up. We will add this to the documentation.
