### ISSUE TITLE
App Center Crashes Link Broken

### ISSUE THREAD

**Issue by allenmc1** [MicrosoftDocs/appcenter-docs#241]
Trying to learn more about App Center crash reporting, appears that link is broken? This link is featured prominently on this page (https://docs.microsoft.com/en-us/appcenter/) under the heading Crashes:

https://docs.microsoft.com/en-us/appcenter/crashes/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fcc87ca-795c-5629-1476-f1d4ad1132fb
* Version Independent ID: 5d59aac2-71e1-7206-9e2a-956c03d1eea4
* Content: [Page Not Found - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/crashes/appcenter/diagnostics/)
* Content Source: [docs/404.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/404.md)
* Service: **vs-appcenter**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@allenmc1 thanks for pointing this out. We made some changes recently (migrating Crashes to Diagnostics) and missed a link. I'll fix it.

**Comment by DennisSmolek** [comment]
Link Still Broken...
Still cant get the correct symbols...

**Comment by jwargo** [comment]
Just go to the [Diagnostics page](https://docs.microsoft.com/en-us/appcenter/diagnostics/).  I'm working on fixing the links.

**Comment by jwargo** [comment]
Fixed
