### ISSUE TITLE
MacOS and WPF support

### ISSUE THREAD

**Issue by VladislavAntonyuk** [MicrosoftDocs/appcenter-docs#242]
If application crashes on macOS or WPF the report is not sent

**Comment by jwargo** [comment]
@VladislavAntonyuk The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
