### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by syntax-e** [MicrosoftDocs/appcenter-docs#245]
"In case you want to setup the getErrorAttachments callback to work with ES2107 async/await functions, you can return a fulfilled Promise instead. "

ES2107 =&gt; ES2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e420f-cf2a-1d5b-d86a-d01c09bcf7a0
* Version Independent ID: 59c746fb-cf4d-3019-2b48-56b69e09aa27
* Content: [App Center Crashes for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native)
* Content Source: [docs/sdk/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@geocachingsyntaxerror thanks. It took me a while to understand what you were asking for. I'll make the change.
