### ISSUE TITLE
codePush.sync()

### ISSUE THREAD

**Issue by cloris-l** [MicrosoftDocs/appcenter-docs#246]
when I use codePush.sync() i get a error that is 'CodePush Couldn`t sent request to https://codepush.azurewebsites.net...........'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0856f1-457f-ac33-ff00-59b6a6290bea
* Version Independent ID: 773bab86-6f25-2415-e220-26fd02fb201f
* Content: [Using the Cordova SDK with CodePush - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cordova)
* Content Source: [docs/distribution/codepush/cordova.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/cordova.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@cloris-l The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
