### ISSUE TITLE
Private git server support

### ISSUE THREAD

**Issue by halfred888** [MicrosoftDocs/appcenter-docs#247]
Currently it's possible to connect repos from bitbucket/github/VTTS. Any chance to see possibility to connect repos from privately hosted git servers ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfeef07-e3eb-9804-5c27-7ac3ec73d768
* Version Independent ID: d7c03ef1-1f84-e1f5-5913-ffad45d9efe1
* Content: [App Center Roadmap - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/roadmap)
* Content Source: [docs/general/roadmap.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/roadmap.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by jwargo** [comment]
@halfred888 I've asked the product's program manager to respond to this. 

Generally you can get answers to questions like this using the chat icon found in the lower-right corner of any App Center page. Our dedicated support team responds to questions there.

**Comment by halfred888** [comment]
@jwargo Thanks! I did ask in chat and got an answer without ETA, therefore I'm raising the issue here. We are just planning our work and have to figure out whether to postpone CI integration or look for alternatives.

**Comment by nilofer** [comment]
@halfred888 unfortunately it is not currently possible to connect to privately hosted git servers.

**Comment by halfred888** [comment]
@nrajpurkar that's why I'm asking if there are any plans to make it possible..

**Comment by jwargo** [comment]
@halfred888 Right now, we're focusing on supporting popular, public repositories. Our current [public roadmap](https://docs.microsoft.com/en-us/appcenter/general/roadmap) does not include anything regarding on-premises connectors.   As customers ask for this feature, we'll consider adding it, but right now there is no ETA for this.

**Comment by halfred888** [comment]
@jwargo Thanks for info! Keep up the good work ;)
