### ISSUE TITLE
Nullable Install Id

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [MicrosoftDocs/appcenter-docs#248]
Why is the install id nullable. Could the content give an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 691afa4b-1cbf-85ed-fb46-37a226d6c780
* Version Independent ID: b71c2a3c-a4f8-6614-15cf-13202ffed888
* Content: [Other Android APIs - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android)
* Content Source: [docs/sdk/other-apis/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/other-apis/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@Steven-Mark-Ford I'll ask the product's PM to update the docs with an example. 

In the mean time, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by elamalani** [comment]
@Steven-Mark-Ford InstallId should not be nullable. As mentioned, its created for each device once the app is installed. This identifier remains the same for a device when the app is updated and a new one is generated only when the app is re-installed or the user manually deletes all app data.

Do you see it empty with getInstallId() API?

**Comment by Steven-Mark-Ford** [comment]
The actual api returns a nullable guid (see screenshot). My question is why? In what circumstances can this return null?

![image](https://user-images.githubusercontent.com/1920816/44437094-cc6efc00-a5fb-11e8-995f-e8eda36f184c.png)

**Comment by iamclement** [comment]
@Steven-Mark-Ford What platform are you using? It looks like Xamarin.

**Comment by iamclement** [comment]
On Xamarin iOS it can't be null but on Xamarin Android it is null if called before the start method of the SDK simply because Android needs the Application context provided at the start of the SDK to access the shared preferences where the installId is saved.

**Comment by Steven-Mark-Ford** [comment]
Would be nice to have this somewhere in the doc as a note

**Comment by jwargo** [comment]
@Steven-Mark-Ford don't forget, the docs are open source, so feel free to fork them, make a change, and submit a PR. 

In the mean time, I'll ask the team to update the docs with that information.

**Comment by Steven-Mark-Ford** [comment]
@jwargo I'm happy to take this one if you like? i.e. via a PR.

**Comment by jwargo** [comment]
@Steven-Mark-Ford got for it, I'd love that!
