### ISSUE TITLE
Secret is in invalid format or failed to connect with provided secret

### ISSUE THREAD

**Issue by VTariko** [MicrosoftDocs/appcenter-docs#249]
Trying to configure the export errors to Azure Blob using the "PATCH /v0.1/apps/{owner_name}/{app_name}/export_configurations/{export_configuration_id}"
I get export_configuration_id from query "GET
/v0.1/apps/{owner_name}/{app_name}/export_configurations", it works correctly.
However, instead of a successful result, an error is returned "Secret is in invalid format or failed to connect with provided secret"
What does it mean and how to get away from it?

**Comment by jwargo** [comment]
@VTariko The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
