### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ac2112** [MicrosoftDocs/appcenter-docs#250]
From the Build -&gt; VSTS -&gt; No project, you're presented with "No repositories found.  The project doesn't have any repository you can access to. Please see our FAQ if the item you are looking for is missing."  The FAQ link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fcc87ca-795c-5629-1476-f1d4ad1132fb
* Version Independent ID: 5d59aac2-71e1-7206-9e2a-956c03d1eea4
* Content: [Page Not Found - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/appcenter/build/#the-repository-i-want-to-connect-to-is-not-listed-in-the-link-repository-step)
* Content Source: [docs/404.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/404.md)
* Service: **vs-appcenter**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@ac2112 I can't find the broken link, what is the source page?  You commented on the not found page, so I can't see where you found this.

**Comment by ac2112** [comment]
Via Appcenter.ms/users/xxxxx/apps/xxxxx/build/connect/vsts

In the “select repository” for your project, you get the message “No repositories found”.  The link is under “....our FAQ...”

[cid:image003.png@01D4386F.B5CEEEF0]

________________________________

**Comment by jwargo** [comment]
@ac2112 Aaah, thanks. I couldn't tell that you were coming in from App Center. Thanks.

**Comment by jwargo** [comment]
Can you try it now? I pointed that link to the Diagnostics page.

**Comment by ac2112** [comment]
The link works but it’s not to the right page.  The page it use to reference was telling you how to integrate with VSTS.

________________________________

**Comment by jwargo** [comment]
Engineering will update the UI and point the link to the right part of the troubleshooting docs. Right now that's all I can do.
