### ISSUE TITLE
Function name to be invoked in build.gradle

### ISSUE THREAD

**Issue by flashimxd** [MicrosoftDocs/appcenter-docs#251]
[Enter feedback here]
§Hi Guys,
I spended some time trying to set up the appcenter push configuration for android, and I figured out that if you are using graddle > 3, the name of the function that you should include as requisite in buildScript changed to maven:

before: google();
after: 
maven {
            url 'https://maven.google.com/'
            name 'Google'
        }

I Think could be a good idea you guys update the MS documentation in the react-native section:

https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-android

Thank you so much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7078a8ed-8f99-1544-8601-8c778fd2bbc1
* Version Independent ID: 9b1886d6-c9f8-e73b-e2b6-db6022f579ac
* Content: [App Center Push for React Native Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-android)
* Content Source: [docs/sdk/push/react-native-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/react-native-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@flashimxd thanks, I'll have the team take a look.

**Comment by dhei** [comment]
Hello @flashimxd, I am from the App Center SDK team. I can't reproduce your issue in my TestApp (see https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/develop/TestApp/android/build.gradle#L3-L29). It works fine without specifying maven url. What is the `com.android.tools.build:gradle` version in your android/build.gradle? Can you provide repro steps?

**Comment by flashimxd** [comment]
Hi @dhei, actually I reported something wrong to you guys the google()  function is a shortcut to marven() (they point to the same repository), the unique diference is that google() can just be used in Gradle 4.x+, Android Studio 3.x+ and Gradle plugin for Android 3.x+..

Reference: https://stackoverflow.com/questions/46467561/difference-between-google-and-maven-url-https-maven-google-com

Thank you guys for you time!

**Comment by dhei** [comment]
Thanks @flashimxd, we will update the docs shortly.

**Comment by flashimxd** [comment]
Hei @dhei , I appreciate! 
Thank you!
