### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by HoneyBrook2121** [MicrosoftDocs/appcenter-docs#252]
Confused at times but I am making good strides in developing an app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ece9ab-9965-2ddf-34b6-44f0f61fe599
* Version Independent ID: 16261b98-a85e-060f-ccf4-3a24f5f14c4c
* Content: [Get Started with UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/uwp)
* Content Source: [docs/sdk/getting-started/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@HoneyBrook2121 that's great to hear. Just so you know, support for App Center is just a click away. To access our dedicated support team, click the blue Chat button in the lower-left corner of most App Center pages, then ask your question. You'll here back from our support team within a day or so.
