### ISSUE TITLE
IOS void type

### ISSUE THREAD

**Issue by brianhager** [MicrosoftDocs/appcenter-docs#255]
It appears that an IOS method can have a void return type and does not necessarily have to return NSString:

        [Export("InitializeUITestData:")]
        public void InitializeUITestData(NSString value)
        {
            new UITestData().SeedTestData();
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa921db3-7ee6-595d-e9a7-c32feecffe1d
* Version Independent ID: 674ae548-212c-5a24-7d2b-ef8792a1015a
* Content: [Working With - Backdoors - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-backdoors)
* Content Source: [docs/test-cloud/uitest/working-with-backdoors.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/working-with-backdoors.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@brianhager thanks, I'll have the PM look at this.

**Comment by glennwester** [comment]
@brianhager Thanks for reporting! We'll update.

**Comment by valdetero** [comment]
@glennwester why was this closed? The docs do not appear to be updated.

**Comment by jwargo** [comment]
@valdetero I'm not sure - I think it's because he thought he'd make an update, but didn't.

**Comment by jwargo** [comment]
@Oddj0b Can you take care of this please?

**Comment by jwargo** [comment]
@brianhager we updated the docs, thanks for pointing this out. Sorry it took so long
