### ISSUE TITLE
Appium Driver

### ISSUE THREAD

**Issue by dannybarrientos** [MicrosoftDocs/appcenter-docs#257]
Do not close to using a driver, remember that the automation in mobile phones grow constantly, are open to changes
http://appium.io/docs/en/about-appium/intro/
look at the different framework git 

> https://github.com/dannybarrientos/TestAutomationFrameworks/blob/master/java-test-automation.md#web-ui-test-automation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium)
* Content Source: [docs/test-cloud/preparing-for-upload/appium.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by dannybarrientos** [comment]
do not close when using only the appcenter drive, they are being very excluded, remember that your infrastructure is adapted to the world, not the world to you.

**Comment by jwargo** [comment]
@dannybarrientos are you asking a question about the docs or making a suggestion to change the docs? It's not clear from the information you provided.

**Comment by dannybarrientos** [comment]
I asking a question about the docs abaout AppiumDriver?.👍

**Comment by jwargo** [comment]
OK, but what's the question? I'm not seeing it.

**Comment by blparr** [comment]
Hola @dannybarrientos ! Cómo podemos ayudarle? Nos puede aclarar su pregunta sobre AppiumDriver?

Muchas gracias y que tenga un buen día!

**Comment by dannybarrientos** [comment]
La pregunta es, que cuando estoy trabajando en AppCenter me exigen que modifique mis drivers a lo que ustedes tienen EnhancedAndroidDriver o EnhancedIOSDriver y no con AndroidDriver,
La idea es estar abierto.
La ideología de AppCenter es prestar el servicio en la nube para ejecutar pruebas, si un usuario viene con un framework de Automatizacion diferentes a los mencionados en la lista, deberían tener la forma de configurar sus test de acuerdo a sus necesidades, ejemplo: si el framework ofrece reporte,la idea seria que ustedes lo mostraran el reporte que genere y ustedes les especificaran el lugar de saludad.

por ejemplo estoy trabajando con este 
http://serenity-bdd.info/docs/serenity/#_running_remote_tests

Ha tenido bastante acojida en diferentes nubes

En el momento trabajo en la nube de **appCenter**, **Aws Device Farm** ,**Saucelab** , **Kobiton** y **browserstack**. 
si quieren podemos trabajar conjuntamente ? en mejorar la plataforma AppCenter
Feliz día

**Comment by blparr** [comment]
Déjeme asegurar que entendí su pregunta. Le gustaría utilizar sus propio test framework y traerlo a App Center?
