### ISSUE TITLE
Undocumented Rate Limit

### ISSUE THREAD

**Issue by eoinmcc** [MicrosoftDocs/appcenter-docs#258]
While testing some export functionality, I ran into a rate limit/quota issue.

Could you let us know what the rate limits on the GDPR Push export endpoint are?

**Comment by eoinmcc** [comment]
Going to anecdotally answer my own question here and suggest that its 

15/day (rolling)

**Comment by jwargo** [comment]
@eoinmcc sorry for the delay, we were out yesterday for the US Labor Day holiday. I'll have the PM respond (and update the docs).

**Comment by iageoghe** [comment]
@eoinmcc you mention the push export endpoint. Can you tell me specifically what push [methods](https://openapi.appcenter.ms/#/push) you are calling? Or are you calling a GDPR [endpoint](https://openapi.appcenter.ms/#/gdpr)? 

@dimazaid do you know of any rate limits on calls to the push API?

Thanks, Ian

**Comment by eoinmcc** [comment]
No worries on the delay, and apologies for not being more specific.

Issue I had was with - https://openapi.appcenter.ms/#/push/Push_ExportDevices

While testing I appear to have hit some limit that expired after about 24 hours.

**Comment by dimazaid** [comment]
Hi! Using the tracking ID, are you able to see the status of your request? Can you clarify what you mean with limit here? Do you mean the number of calls to your API?

**Comment by jwargo** [comment]
@eoinmcc there's been no response in the last 26 days, so I'm going to close this. Please contact our support team for help. Feel free to reopen this if you have a doc update to suggest.
