### ISSUE TITLE
ENABLE_TEST_CLOUD is not defined anywhere

### ISSUE THREAD

**Issue by jimbobbennett** [MicrosoftDocs/appcenter-docs#260]
The docs refer to the ENABLE_TEST_CLOUD compiler flag, saying that newer versions of VS define this for you - but they don't. Tested with VS2017 15.8 and VS for Mac 7.7, this compiler flag is not set in the blank forms app templates either directly, or intrinsically at compile time.

Can this be changed to be DEBUG, of else can the templates be fixed up.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd5535b-f176-9808-90c3-e35d1ad4ca88
* Version Independent ID: 382fe3a0-b895-8283-95ad-615475c94d5e
* Content: [UITest Cheat Sheet - Visual Studio App Center](https://docs.microsoft.com/en-gb/appcenter/test-cloud/uitest/cheatsheet#initializing_tests_on_ios)
* Content Source: [docs/test-cloud/uitest/cheatsheet.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/cheatsheet.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@jimbobbennett I'll ask the PM to take a look and respond. 

Don't forget, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by glennwester** [comment]
@jimbobbennett Thanks for reporting! We'll get this fix to the template in for a future version of Visual Studio.
