### ISSUE TITLE
Electron app build

### ISSUE THREAD

**Issue by DeekshithShetty** [MicrosoftDocs/appcenter-docs#261]
Is there any plan to support builds for electron apps in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0087c543-d8f4-5ea6-5ac6-8b30ec1b9e6c
* Version Independent ID: 92b8f8de-268b-a249-46e9-053edf2e97c0
* Content: [App Center Platform Services Matrix - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix)
* Content Source: [docs/general/platform-service-matrix.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/platform-service-matrix.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by nilofer** [comment]
@DeekshithShetty Support for building electron apps is not on our [public roadmap](https://docs.microsoft.com/en-us/appcenter/general/roadmap) at the moment. We appreciate the feature request!
