### ISSUE TITLE
It seems Xamarin UWP is not supported but the docs are not clear

### ISSUE THREAD

**Issue by jimbobbennett** [MicrosoftDocs/appcenter-docs#262]
According to the Appcenter team, UWP apps built with Xamarin.Forms are not supported.

The docs don't make this clear as a UWP Xamarin Forms app is still a UWP app (as opposed to Android vs Xamarin Android).

Can this be made clearer as I'm already speaking to one customer who is confused by this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0087c543-d8f4-5ea6-5ac6-8b30ec1b9e6c
* Version Independent ID: 92b8f8de-268b-a249-46e9-053edf2e97c0
* Content: [App Center Platform Services Matrix - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix)
* Content Source: [docs/general/platform-service-matrix.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/platform-service-matrix.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@jimbobbennett OK, I'll have the PM take a look. Don't forget, this is open source, so if you want to propose a change, simply submit a PR. Since you work for Microsoft, you can even do it in our private repo.

**Comment by elamalani** [comment]
@jimbobbennett Thanks for sharing the feedback. In this document page, we only list platforms supported by App Center. Anything missing is not included in the list by default.

I will close the issue for now, and update the page again if I hear a lot of people asking for it.
