### ISSUE TITLE
AppCenter.start(getApplication(), "{Your App Secret}", Analytics.class, Crashes.class);

### ISSUE THREAD

**Issue by socialnoopasen** [MicrosoftDocs/appcenter-docs#263]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa9700f5-b9e0-dfe1-ddbc-b5a3231dde11
* Version Independent ID: 11728c80-1474-c1dc-caf0-2c6b6c44bbb3
* Content: [Get Started with Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android)
* Content Source: [docs/sdk/getting-started/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@socialnoopasen did you have a question about the docs?

The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
