### ISSUE TITLE
carthage docs?

### ISSUE THREAD

**Issue by loufranco** [MicrosoftDocs/appcenter-docs#264]
I can't figure out how to get appcenter to automatically detect that I use Carthage.  I tried

1. Just committing Cartfile and Cartfile.resolved
2. Also committing Carthage/Checkouts
3. Using Cartfile and Cartfile.resolved and a appcenter-post-clone.sh that did a carthage bootstrap, like:

```
#!/usr/bin/env bash

cd "$APPCENTER_SOURCE_DIRECTORY"
carthage bootstrap
```

There is no evidence in the log that that script was run (but it does show up in the branch's settings as having been detected)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62690a4a-94f3-21cb-a674-d297e557ca62
* Version Independent ID: 3adaeac7-e034-5b5b-19c5-1c0151a7264c
* Content: [App Center Changelog - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/changelog)
* Content Source: [docs/general/changelog.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/changelog.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by jwargo** [comment]
@loufranco The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by loufranco** [comment]
Please write docs about how to get carthage working and how to troubleshoot it if it isn't.  I mentioned what I did, because none of that worked (and it's the normal way to do carthage). I did also initiate a support ticket, thanks.

**Comment by orischwartz** [comment]
I also struggled to get a relatively simple Carthage app working with AppCenter. The [docs](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#pre-build) and [release notes](https://docs.microsoft.com/en-us/appcenter/general/changelog#july-2017) make references to built-in Carthage support but it's not implemented--you have to make use of the custom scripts feature.

Here's what worked for us:

1. Add `appcenter-pre-build.sh` file to your repository. You can use an `appcenter-pre-clone.sh` script instead but that executes *before* the call to `sudo xcode-select --switch [xcode version]` that sets your build's configured xcode version, and that will likely lead to incompatibilities (the default xcode version was 9.4).
1. Your pre-build script should run `carthage bootstrap --platform ios --no-use-binaries --verbose` 
1. You *must* reconfigure and save your build or appcenter doesn't detect that you have a new custom script. Go to `builds > branch > settings icon > save & run`

Sample script:

#### appcenter-pre-build.sh
```bash
#!/usr/bin/env bash

cd [relative directory with Carfile]
CMD="carthage bootstrap --platform ios --no-use-binaries --verbose"
echo "running: $CMD"
$CMD
```

**Comment by loufranco** [comment]
@orischwartz I finally was able to get this to work automatically by just deleting my build configuration and re-making it.  I did not have Carthage when I first made the config -- it appears that it can't detect it being added later.

But re-making it worked.
