### ISSUE TITLE
How to remove bug tracker?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#266]
I had connected my organization's VSTS account just to toy with the feature a little bit. After some deliberation, it wound up not being a feature we wanted to use at this time. How do I remove it?

**Comment by jwargo** [comment]
The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by ghost** [comment]
jwargo,

This was a suggested change as a matter of fact. My wording definitely leans towards a help request and I apologize for that. Having how to remove it in the docs would be very useful. :) Information is provided for how to add it, but now how to remove it.

**Comment by jwargo** [comment]
@DougMurphyABA Thanks for the clarification, I'll have the PM take a look at making a doc update.

**Comment by jwargo** [comment]
@amchew Can you please take a look?

**Comment by amchew** [comment]
@DougMurphyABA Hi, thanks for reaching out! To disconnect the bug tracker from your app, please see step 6 in the [documentation](https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/).

I think what you may be asking is how to completely remove the bug tracker from your account, yes? :) 

If so, currently, we don't have the functionality for users to manually remove their connected bug tracker, and we can do this on our end for you. At the bottom right-hand side of your logged in[ App Center](http://appcenter.ms) page, please click on the blue Intercom button, and mention that you'd like to manually remove your connected bug tracker. 

I've taken your comment as a +1 as a feature request though. 

Thank you!
Amanda

**Comment by ghost** [comment]
@amchew Thank you for your response! I was looking to completely remove it for now, so I will get help using the intercom button.

**Comment by amchew** [comment]
Cool :) 
In the Intercom conversation, you can copy and paste the link to this issue, and mention in the chat to channel this conversation to Amanda Chew (that's me), and I'll follow up there.
