### ISSUE TITLE
Do you support xUnit for Xamarin.UITest? 

### ISSUE THREAD

**Issue by DalSoft** [MicrosoftDocs/appcenter-docs#269]
This is currently a blocker for us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1f8239-19fa-9c4b-52f5-b9c19cafbb4a
* Version Independent ID: 1980a317-8a4a-10b3-eedd-32af9d36cfbe
* Content: [Supported Test Frameworks - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/supported-frameworks)
* Content Source: [docs/test-cloud/supported-frameworks.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/supported-frameworks.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@DalSoft I'll pass the feedback on to the PM team.

**Comment by glennwester** [comment]
Hi @DalSoft, apologies for we currently only support NUnit 2. I've made note of your feature request and will provide an update if it becomes available.

**Comment by DalSoft** [comment]
For others looking for xUnit support we are using https://experitest.com/ It's based on Appium but importantly for us allows us to run our xUnit tests on Cloud Devices. Works very well so far with our Xamarin app.
