### ISSUE TITLE
Analytics throws exception

### ISSUE THREAD

**Issue by TiBall** [MicrosoftDocs/appcenter-docs#27]
When I call AppCenter.Start($"android={ANDROID_APPCENTER_KEY};uwp={UWP_APPCENTER_KEY}",
				typeof(Analytics), typeof(Crashes), typeof(Distribute));
I get this exception in Android. Any Ideas?
02-26 17:13:36.117 E/AndroidRuntime(10529): FATAL EXCEPTION: AppCenter.Looper
02-26 17:13:36.117 E/AndroidRuntime(10529): Process: com.companyname.CleanbirdApp, PID: 10529
02-26 17:13:36.117 E/AndroidRuntime(10529): java.lang.AbstractMethodError: abstract method "boolean com.microsoft.appcenter.channel.Channel$Listener.shouldFilter(com.microsoft.appcenter.ingestion.models.Log)"
02-26 17:13:36.117 E/AndroidRuntime(10529): 	at com.microsoft.appcenter.channel.DefaultChannel.enqueue(DefaultChannel.java:551)
02-26 17:13:36.117 E/AndroidRuntime(10529): 	at com.microsoft.appcenter.AppCenter.sendStartServiceLog(AppCenter.java:599)
02-26 17:13:36.117 E/AndroidRuntime(10529): 	at com.microsoft.appcenter.AppCenter.finishStartServices(AppCenter.java:586)
02-26 17:13:36.117 E/AndroidRuntime(10529): 	at com.microsoft.appcenter.AppCenter.access$400(AppCenter.java:52)
02-26 17:13:36.117 E/AndroidRuntime(10529): 	at com.microsoft.appcenter.AppCenter$5.run(AppCenter.java:562)
02-26 17:13:36.117 E/AndroidRuntime(10529): 	at android.os.Handler.handleCallback(Handler.java:739)
02-26 17:13:36.117 E/AndroidRuntime(10529): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-26 17:13:36.117 E/AndroidRuntime(10529): 	at android.os.Looper.loop(Looper.java:148)
02-26 17:13:36.117 E/AndroidRuntime(10529): 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-26 17:13:36.167 D/ViewRootImpl(10529): ViewPostImeInputStage processPointer 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72f6fe-74d6-696e-e709-5f6d577c0a58
* Version Independent ID: b3d0ea8b-5a1f-bf71-7dc2-9685cf23c00b
* [Content](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/Xamarin)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/xamarin.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@TiBall To get help with a particular feature, use the blue chat button in the lower-right corner of the App Center dashboard window. We have a dedicated team of support personnel who are there to answer your questions.

**Comment by elamalani** [comment]
@TiBall You can enable Verbose logging in your application right before the AppCenter.Start() API by using the API below and share the logs with us for debugging.

AppCenter.LogLevel = LogLevel.Verbose;

**Comment by TiBall** [comment]
Thx for getting back to me!
However, I "sadly" can´t reproduce the error. Updated from Appcenter v1.2 to v1.4 and cleaning the repository did the job. I tried to reset my branch to the previous version, but the error does not show any more. Sometimes Android with Xamarin has some really strange behaviours, sry.

**Comment by guperrot** [comment]
It's unfortunately common that updating any library can lead to errors if bin/obj folders are not cleaned, xamarin has a build cache that can get stale quickly. We advise to always perform a full clean build when such an error is experienced.

**Comment by elamalani** [comment]
@TiBall Thanks for the update. I will close this issue but feel free to reach out to us in case of any question.

**Comment by kyunghoon** [comment]
getting same exact issue, any resolution to this?

**Comment by guperrot** [comment]
@kyunghoon have you tried closing VS, cleaning bin/obj folders and retry? If it does not work, please create a support ticket using the blue chat button on any page of https://appcenter.ms portal.
