### ISSUE TITLE
Create and update api detail

### ISSUE THREAD

**Issue by rsuk** [MicrosoftDocs/appcenter-docs#271]
I had a stab at creating a new export configuration for Application Insights using the api, but didn't get very far as the example json blob is for blob storage. I think the docs need updating (either in this Topic, or in the https://openapi.appcenter.ms docs). Can you confirm what the json blob would look like for an Application Insights export? I'm guessing something like:

```
{
  "type": "????",
  "export_entities": [
    "crashes"
  ],
  "instrumentation_key": "{my key value was here}"
}
```

.. but don't know what the "type" value should be.

I also tried updating an existing configuration to enable crashes, errors and attachments, but got a Bad Request response for this json blob (ids removed):

```
{
  "export_entities": [
    "crashes","errors","attachments"
  ]
}
```

.. also tried just:

```
{
  "export_entities": [
    "crashes"
  ],
  "instrumentation_key": "{my key value was here}"
}
```

.. with the same Bad Request response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14a1fd-c1c2-f1a7-dd70-97c1200571f1
* Version Independent ID: f502c9bf-5593-1dd7-3551-6a7ca21f6f5c
* Content: [App Center Export - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/export)
* Content Source: [docs/analytics/export.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/export.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by jwargo** [comment]
@rsuk I'll have the PM take a look at doing a doc update. In the meantime, the comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
