### ISSUE TITLE
Not able to get crash logs on app center

### ISSUE THREAD

**Issue by wilsonShakya4577** [MicrosoftDocs/appcenter-docs#272]
Hi, I am using Xamarin IOS as platform, I have been trying to get crash logs but nothing working for me.
I am able to see data on analyst window, error in error section but not exception. Please help
{
"device" : {
"appVersion" : "2.3.0.15",
"appBuild" : "2.3.0.15",
"osName" : "iOS",
"timeZoneOffset" : 330,
"wrapperSdkVersion" : "1.9.0",
"osVersion" : "11.4.1",
"wrapperRuntimeVersion" : "11.2.0",
"locale" : "en_IN",
"wrapperSdkName" : "appcenter.xamarin",
"carrierName" : "Vodafone India",
"appNamespace" : "com.Kastle.KASTLEPresence",
"osBuild" : "15G77",
"sdkName" : "appcenter.ios",
"oemName" : "Apple",
"sdkVersion" : "1.9.0",
"model" : "iPhone7,2",
"screenSize" : "1136x640"
},
"timestamp" : "2018-09-24T07:31:07.072Z",
"type" : "startService",
"services" : [
"Crashes",
"Analytics"
]
}
[MSAppCenter configureWithAppSecret:transmissionTargetToken:fromApplication:]/274 App Center SDK configured successfully.

[AppCenterAnalytics] INFO: -[MSAnalytics applyEnabledState:]/142 Analytics service has been enabled.

AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/598 EnableUncaughtExceptionHandler is set to NO, we're running in a Xamarin runtime

**Comment by jwargo** [comment]
@wilsonShakya4577 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jwargo** [comment]
@wilsonShakya4577 I'm sorry it took so long to respond to you, I didn't see this request come in, I normally respond in a day.

**Comment by PaulsonM** [comment]
I'm having the same problem with Xamarin.Forms iOS
Referencing #974 here - https://github.com/microsoft/appcenter-sdk-dotnet/issues/974
