### ISSUE TITLE
Unclear expanations for first time users

### ISSUE THREAD

**Issue by bmvalente** [MicrosoftDocs/appcenter-docs#273]
. In the "Prerequisites", how do we install/configure Maven and Maven Surefire ? How should the .pow file look like
. What is the Project structure that it should have ? Where to I place the test classes ?

I think that a zip file with a sample Project would go a long way to solve these questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium)
* Content Source: [docs/test-cloud/preparing-for-upload/appium.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@bmvalente thanks for the feedback, I'll ask the PM team to take a look.

**Comment by glennwester** [comment]
@bmvalente thanks for writing in! So we can make the appropriate changes to our docs, I'd like to clarify your questions. You don't need to have Surefire added to the package, it's what we use to run your tests on our execution hosts. The modifications to your pom.xml should be as follows: https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md#1a-changes-to-the-build-system-for-maven-users . Please see the following example and let us know if you have any questions https://github.com/King-of-Spades/AppCenter-Test-Samples/tree/master/Appium.
