### ISSUE TITLE
GitHub Enterprise Support?

### ISSUE THREAD

**Issue by TradeArcher2020** [MicrosoftDocs/appcenter-docs#274]
Can App Center and GitHub Enterprise work together?  If so, how?  If now, can we expect that support sometime in the near future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de5a7b9-2742-0ea0-3170-d6fb5da0d2de
* Version Independent ID: f24ff5eb-4fb5-7a96-ff76-6c96386c9498
* Content: [Connecting Repositories Using the GitHub App - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/github-app)
* Content Source: [docs/build/github-app.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/github-app.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by nilofer** [comment]
Hi @chrisaswain, App Center does not currently support GitHub Enterprise and it is not on our public short-term roadmap.

**Comment by jomnius** [comment]
Is it on non-public short-term roadmap, if you can comment on such (after 2 months wait)? Is it on any long-term roadmap?

**Comment by bryancross** [comment]
@nrajpurkar I'm obviously just speculating on the feasibility here, but it seems like enabling connectivity to GitHub Enterprise would be a fairly simple addition.  And it would open up App Center for use by a _lot_ of Enterprise developers who would very much like to be using it.

**Comment by jwargo** [comment]
@bryancross actually it isn't. Most customers have GitHub enterprise hidden behind a firewall, so we can't poke into it to check for updates. Some organizations are OK with opening firewall ports for this, others, not so much. So, to create a solution that works for all use cases, would require building a piece of on-premises software that a customer installs internally and works for all possible use cases. It's doable, but it's likely a large effort.

**Comment by bryancross** [comment]
@jwargo Not being able to check for updates is not necessarily a bad thing.  Using Webhooks and an event driven model is much easier to support and much easier on the GitHub Enterprise infrastructure than polling.  In either case, customers would have to configure their networks to support access, but this is something they do for 100s of other CI tools already.

**Comment by jwargo** [comment]
@bryancross agreed, but apparently we're hearing from customers that many IT organizations don't allow external access. Is this not true? do most GHE customers expose firewall ports to let cloud services in?

**Comment by bryancross** [comment]
@jwargo Plenty of anecdotal evidence both ways, frankly.  Anything I can do from a GitHub perspective to provide more actionable info?

**Comment by jwargo** [comment]
@bryancross Thanks. Apparently we've had discussions with the GitHub team about this very subject, the PM's closely connected with them. Because of the complexity of this, based on our current understandings, support for GitHub Enterprise is not currently on our roadmap.

**Comment by bryancross** [comment]
Ah, well, that's a bummer :(
