### ISSUE TITLE
Please suport

### ISSUE THREAD

**Issue by Aalmaho** [MicrosoftDocs/appcenter-docs#275]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa9700f5-b9e0-dfe1-ddbc-b5a3231dde11
* Version Independent ID: 11728c80-1474-c1dc-caf0-2c6b6c44bbb3
* Content: [Get Started with Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android#4-start-the-sdk)
* Content Source: [docs/sdk/getting-started/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@Aalmaho do you have a question about the docs?
