### ISSUE TITLE
Notificaitons spelling wrong ;)

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/appcenter-docs#276]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bad7023-e00b-b6af-b71f-1823e7829dec
* Version Independent ID: 77a10f16-f669-3934-08b3-ceefa52b2059
* Content: [App Center Build Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/#a-code-signed-build-cannot-be-installed-on-an-ios-device)
* Content Source: [docs/build/troubleshooting/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/troubleshooting/index.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@pilcherd yep, you're right. Fixed it. Thanks.
