### ISSUE TITLE
Can I disable Push services?

### ISSUE THREAD

**Issue by Wenfengcheng** [MicrosoftDocs/appcenter-docs#279]
I want to disable push notification when user log out, I try to set *Push.SetEnabledAsync(false);*, but nothing worked, I can also receive notification on Device.

Does AppCenter contains method such as *AppCenter.End(services);* can disable service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a483e190-f75f-a52c-2472-e459d20df9d6
* Version Independent ID: 126a6e30-7c6d-f42c-57c3-2ac62d619ac8
* Content: [App Center Push Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/faq)
* Content Source: [docs/push/faq.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/faq.md)
* Service: **vs-appcenter**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by jwargo** [comment]
@Wenfengcheng The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
