### ISSUE TITLE
Are one-click releases with AC Distribution possible with builds from AC?

### ISSUE THREAD

**Issue by Hoid** [MicrosoftDocs/appcenter-docs#28]
Once I build my app on AC with the most recent build, do I have to ability to push that build to Distribution without having to download it and upload it back to Distribution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde49960-01fb-c5ff-ad3d-b8b6c7ac8d11
* Version Independent ID: 524b6257-9c78-600a-9e8d-193c59fc6b48
* [Content](https://docs.microsoft.com/en-us/appcenter/distribution/)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/index.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@Hoid To get help with a particular feature, use the blue chat button in the lower-right corner of the App Center dashboard window. We have a dedicated team of support personnel who are there to answer your questions.

**Comment by jwargo** [comment]
@Hoid the configuration is described in the platform-specific build docs. Here's a link the the [Android build doc](https://docs.microsoft.com/en-us/appcenter/build/android/first-build#37-distribute-to-a-distribution-group).
