### ISSUE TITLE
react-native appcenter-push

### ISSUE THREAD

**Issue by keithics** [MicrosoftDocs/appcenter-docs#280]
lacking appcenter-push..
it should add
npm install appcenter-push --save
react-native link appcenter-push

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by zuhair-naqvi** [comment]
+1

**Comment by jwargo** [comment]
@keithics thanks, I'll have the PM take a look.
