### ISSUE TITLE
NuGet for AppCenter API

### ISSUE THREAD

**Issue by balivo** [MicrosoftDocs/appcenter-docs#281]
There's no NuGet package for AppCenter API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/index)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@balivo No, why would there be? It's a REST API. 
There are, I believe, NuGet packages for the App Center SDK.

**Comment by balivo** [comment]
@jwargo the NuGet packages allready have is for "client" (receives push, send info for Analytics, take care about Distribution, etc)... AppCenter don't have a NuGet for "server-side" operations (like, send push notifications, etc)... Ok, we have a REST API, but don't have a NuGet for easy setup (plug and play) with it... I thinking about create this package for "server side" AppCenter operations....

**Comment by balivo** [comment]
My AppCenter client NuGet implementation: https://github.com/balivo/appcenter-openapi-sdk

**Comment by thomasgalliker** [comment]
@jwargo haha, seriously? If something is a REST API it means that there is no need to have an easy-to-use .NET API? This kind of thinking leads to cases where we end up with dozens of different nugets, all with more or less issues, different feature sets, different quality... Of course its not your task to implement it but Microsoft could at least host the official repository for such a project. Agree?

**Comment by thomasgalliker** [comment]
I use this nuget to send push notifications from my aspnet core backend to users: https://www.nuget.org/packages/AppCenter.Push.Server

All services are abstracted with interfaces for easy IoC’ing and testability. 

Any feedback is welcome 👍
