### ISSUE TITLE
sdk

### ISSUE THREAD

**Issue by bunthonn** [MicrosoftDocs/appcenter-docs#282]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40294974-bc6b-45af-f1bd-3bd8187153ac
* Version Independent ID: 21420d35-1e72-a8b8-d587-40b2913120ba
* Content: [App Center Distribute for Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android)
* Content Source: [docs/sdk/distribute/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@bunthonn The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
