### ISSUE TITLE
Can I get the firebase Token ? 

### ISSUE THREAD

**Issue by sulaemansantoso-IT** [MicrosoftDocs/appcenter-docs#283]
i wish to to get the firebase token to store on my database so that i can send notification only to selected devices.. how can i do that with app center push notification ?

**Comment by jwargo** [comment]
@sulaemansantoso-IT The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by sulaemansantoso-IT** [comment]
ok i'm sorry

thank you very much
