### ISSUE TITLE
Need mention of Bitbucket Server

### ISSUE THREAD

**Issue by douglasknudsen** [MicrosoftDocs/appcenter-docs#286]
We are users of private cloud hosted Bitbucket Server, I do not see this mentioned here as possible source control connectors.

**Comment by jwargo** [comment]
@douglasknudsen checking to make sure, but as I understand it, we only support public providers today.

**Comment by jwargo** [comment]
@douglasknudsen confirmed: we do not support any private cloud or on-premises version control systems at this time.

**Comment by douglasknudsen** [comment]
@jwargo ah, ok.  thanks for the lightening fast response!
