### ISSUE TITLE
Push.PushNotificationReceived example should be expanded

### ISSUE THREAD

**Issue by NCleverly** [MicrosoftDocs/appcenter-docs#287]
I want to request that  the code snippet be given also show the notification in the example. Right now if you implement the code snippet you can no longer have the notification show. I contacted App center support and even they do not know how to show it in xamarin forms.

for example i have the following in my code:
```
private void SetupPushNotificationHandle()
        {
            // This should come before AppCenter.Start() is called
            // Avoid duplicate event registration:
            if (!AppCenter.Configured)
            {
                Push.PushNotificationReceived += (sender, e) =&gt;
                {
                    OceanBusiness business = CoreDependencyService.GetBusinessLayer&lt;OceanBusiness&gt;();
                    // If there is custom data associated with the notification,
                    // print the entries
                    if (e.CustomData != null)
                    {
                        foreach (var key in e.CustomData.Keys)
                        {
                            switch (key)
                            {
                                case CoreSettings.ClearData:
                                {
                                    if(key.ToLower() == "true")
                                        business.RemoveData();
                                    break;
                                }
                            }
                        }
                    }

                };
            }

```
It should be possible to at the end if no item match to just show the Notification to the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65373652-7eda-af01-0f72-d01fcce4c131
* Version Independent ID: f85b66b3-ca30-bb5c-bfae-6425661d3365
* Content: [App Center Push for Xamarin.Forms Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms)
* Content Source: [docs/sdk/push/xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-forms.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@NCleverly Thanks for the suggestion, I'll have the PM take a look.

**Comment by achocron** [comment]
Have you taken a look at the [demo application ](https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/238ab98e68112b0fcd98d15413714ae45ea84e34/Apps/Contoso.Forms.Demo/Contoso.Forms.Demo/App.xaml.cs#L69) in the SDK repo? I believe it does what you are looking for.

**Comment by NCleverly** [comment]
Sadly that example displays a device alert not a platform Push Notification. The issue I have is that the notification will no longer show on the devices notifications. There was a  Xamarin.Android Issue that fixed this that shows an android only way to show the notification after the interception. I am suggesting for Xamarin.Forms we should have example that shows you how to do the same thing.

Reference https://github.com/MicrosoftDocs/appcenter-docs/issues/57

**Comment by achocron** [comment]
Thanks for the feedback. In the meantime, if you need some guidance for showing it in a Xamarin project in the iOS application, I recommend checking out this issue: https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/757

**Comment by NCleverly** [comment]
Why was this closed as the other issue referenced does not in fact my address the question? Rather it simply shows how to handle a third party conflict. My issue is that when the Push.PushNotificationReceived has a delegate added you can no longer show the notification without platform specific code.

**Comment by elamalani** [comment]
@NCleverly We don't plan to add an API to show native notification toasts in the foreground of the application. Once we support it, we will update our documentation on the usage. Thanks!

**Comment by NCleverly** [comment]
@elamalani To reiterate i want to show a PUSH Notification. Exactly the same notification that would have been displayed had i not added the above code. My issue is that you have not shown how to do this.

**Comment by achocron** [comment]
Ah, are you trying to show a notification in the background? Or foreground? By default, notifications don't show up in the foreground either way. And adding a handler shouldn't interfere with the toast showing up in the background. Which scenario are you asking about? Sorry for the confusion.

**Comment by NCleverly** [comment]
Okay, so first i am not trying to show a toast like this
[Toast](http://www.mkyong.com/wp-content/uploads/2012/03/android-Toast-example.png)
i want to show a push notification like this:
[Twillio example](https://s3.amazonaws.com/com.twilio.prod.twilio-docs/images/t_3uIdWRwKl2jWx2HWpR25RUdhElEBaTolo0n9bi_oQJ5Y.width-808.png)

and i can assure you that added the delegate does hide that notification entirely.

And i am trying with the app in the background.

**Comment by ghost** [comment]
Thanks NCleverly for your messages, I agree with you and I'm waiting for the same answer.
Thanks

**Comment by iamclement** [comment]
Hi there, 
The code snippet only shows how to handle the notification in foreground. From there people can do whatever they want, some want in-app banner, some want system alert others just want to play a sound...
@NCleverly  and @JulienDollon to answer the question in order to display a system alert in foreground you just need to call the completion handler from the `WillPresentNotification` callback with the  `UNNotificationPresentationOptions.Alert` enum value. Hope this helps.

**Comment by jwargo** [comment]
@elamalani @clpolet should we update the docs with this?

**Comment by iamclement** [comment]
I like to have a generic code snippet but I can add a link to the UNNotificationPresentationOptions doc saying it can do toast, sound...

**Comment by jwargo** [comment]
@clpolet close issue?

**Comment by NCleverly** [comment]
I did not see how this answers my question. You keep discussing other delegates but not how to show the push notification received.  If you would like to close i would request that you reread the issue is not being able show a push notification after evaluating whether a custom data value match a value. Is the delegate Push.PushNotificationReceived not supposed to be used like this?

**Comment by jwargo** [comment]
@NCleverly the answer was given:  in order to display a system alert in foreground you just need to call the completion handler from the WillPresentNotification callback with the UNNotificationPresentationOptions.Alert enum value. 

Does that not address your question?  If not, please clarify.

**Comment by NCleverly** [comment]
Please see my above edit. I am made the issue clearer.

**Comment by iamclement** [comment]
OK I understand the whole thing now. You want to display that system toast depending on the custom data in the push payload. ~~I don't think you can achieve that using the App Center push callback directly.~~ First approach: But it's doable within the `WillPresentNotification`. The [UNNotification.Request](https://developer.xamarin.com/api/property/UserNotifications.UNNotification.Request/) should contain the payload but you'll have to parse it yourself.

**Comment by iamclement** [comment]
It's actually possible to use the AC Push callback for this but not sure if it's quicker to implement. Second approach: Within the AC Push callback you'll basically have to rebuild the notification as a local system alert and post it. Creating and posting the local system alert is explained [in this documentation](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/deprecated/local-notifications-in-ios-walkthrough).
Let me know what you chose and how it goes.

**Comment by NCleverly** [comment]
The continuing failure here is that I do not want a TOAST. I need it to act like I never touched the flow.  If the custom data point is not present or value is not what I expect the notification systems need to behave exactly as it would before. Any display as a Toast is therefore not acceptable as a solution. Please view the images to compare toasts vs push notification. The notification has to show in the device notifications area and remain until the user dismisses it.

**Comment by iamclement** [comment]
Sorry I meant system alert not toast, the second solution would still display a system alert not an in-app alert or toast as you say. But if you really don't want to break the flow of the notification than the first approach is the right one.

**Comment by jwargo** [comment]
@NCleverly are you making progress on this? Did @clpolet's information help you accomplish what you need to accomplish?

**Comment by NCleverly** [comment]
I am still working on how to call the android Notfication.Builder and The iOS Code. and will be opening a suggestion with the app center SDK team allow for creating these in the forms shared code instead of having to wire up platform specific code.

**Comment by jwargo** [comment]
@NCleverly OK, I'm going to close this issue, feel free to reopen if you need, but going through support is the best approach.
