### ISSUE TITLE
UWP Internet (Client) Permission Required

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/appcenter-docs#289]
This page (and the AppCenter Overview page) should indicate the UWP app needs "Internet (Client)" permission. This was probably overlooked because I believe a new UWP app defaults to have that permission. However my app doesn't need it, so I had disabled it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2add0f-2806-8bfa-92d5-cc3fdd1e1055
* Version Independent ID: c572b535-a780-fba3-0845-f5127d98d7d6
* Content: [UWP SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/uwp)
* Content Source: [docs/sdk/troubleshooting/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by iamclement** [comment]
That's right thanks for reporting it. I'll make the change.

**Comment by iamclement** [comment]
This is now added to the UWP getting started.
