### ISSUE TITLE
Documentation on creating automated tests does not exist 

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#29]
The main use-case for appcenter testing (test cloud) is to be able to create automated tests that run after a new build is triggered. However, the documentation talks just about how to upload a one off test to appcenter from your local machine using a pre-built app bundle. It wasn't until I found this blog https://tomsoderling.github.io/AppCenter-Automated-UI-tests-on-build/ that I could figure out how to create automated tests via post build scripts. I think this needs to be front and center for appcenter test. You can even see that in the blog the author took 34 builds before they got what they wanted, even with support from appcenter. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd83c51-172c-1ec2-a485-9118c1109c0b
* Version Independent ID: 44c1a155-e819-aa43-f3aa-2f254afb259b
* [Content](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/index.md)
* Service: vs-appcenter

**Comment by glennwester** [comment]
Hi @tura08 thanks for the feedback! We know this process could be made clearer and easier, thank you for sharing the link. In addition to improving the documentation, we'll more tightly integrate these two services in the near future.

**Comment by ghost** [comment]
Hi @glennwester thanks for acknowledging this. Something else to note is that it is not currently feasible to build and test in appcenter due to the build time limit of 30 mins. I am barely able to run tests on two devices before the build times out. I am going to move to VSTS for build and run testing and deployment in appcenter via VSTS.

**Comment by glennwester** [comment]
Hi @tura08, we have a solution for this! You can add --async to to end of your upload command to return immediately after the the app and test files have uploaded. Can you please try this and let me know if it resolves your issue?

**Comment by ghost** [comment]
Using --async means that my build is now independent of my tests and therefore a build could potentially pass even though the tests fail. I want my pipeline to consists of build, test and distribute... i.e. I want to wait for the tests...

**Comment by josemperezr** [comment]
Can I run tests with appium written on Node using the framework Nightwatch ?

**Comment by glennwester** [comment]
Hi @tura08, for the purposes of trialing our service, could you reduce the length of your testing suite so that you can perform an end to end build/test/distribute workflow?

**Comment by awesomes007** [comment]
Is there a replacement for Xamarin Test Recorder?

**Comment by jwargo** [comment]
@awesomes007  The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
