### ISSUE TITLE
Gradle sample project

### ISSUE THREAD

**Issue by JenniferPerezBedoya** [MicrosoftDocs/appcenter-docs#290]
Hi, I have a gradle project, when I run mvn -DskipTests -P prepare-for-upload package only /test-classes and pom are generated. I had to create dependency-jars and put it on target/upload/ because it wasn't generated automatically. When I run the tests on appcenter I get an error: No project dependencies found in POM. Unable to generate server-POM but I don't know what to do. Have you a sample generated structure to run the tests, so I can compare it with mine. Or an issues wiki that I can read to solve the errors generated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium)
* Content Source: [docs/test-cloud/preparing-for-upload/appium.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@JenniferPerezBedoya I apologize for the late reply to this,  you caught me right at the weekend break. The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by JenniferPerezBedoya** [comment]
Thank you, that's cool.
