### ISSUE TITLE
.NET Standard 2.0 Library Builds

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/appcenter-docs#291]
Should document: .NET Standard 2.0 library projects need to have Build &gt; Advanced &gt; "Debugging information" changed from the default of "Portable" to "Full".  Discovered when building .NET Standard 2.0 libraries in combination with a UWP app. With "Portable", AppCenter build "mspdbcmf.exe" will exit with code 1106 from fatal error CMF1106 "input PDB file is not generated by /DEBUG:fastlinkW".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be2ace35-a6ef-349a-e009-ca55e3778602
* Version Independent ID: 85a92e95-828a-54f8-b7e7-4f86b8e76abc
* Content: [Configure a C# UWP app in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/windows/uwp/first-build)
* Content Source: [docs/build/windows/uwp/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/windows/uwp/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@kburgoyne I'll have the SDK team and take a look. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by elamalani** [comment]
@jwargo This is Build related as well.

**Comment by jwargo** [comment]
@elamalani you're right, sorry.

**Comment by nilofer** [comment]
Hi @kburgoyne, this is a known [issue](https://developercommunity.visualstudio.com/content/problem/307296/error-msb6006-mspdbcmfexe-exited-with-code-1106.html) that was fixed in VS 15.9 Preview 3. The hosted agents don't currently have the preview versions on them.

**Comment by kburgoyne** [comment]
Right-o. Thanks.
