### ISSUE TITLE
Wrong info to find deployment key in android setup.

### ISSUE THREAD

**Issue by Girish2015** [MicrosoftDocs/appcenter-docs#294]
In the Android setup part, the command to get deployment keys is given as "code-push deployment list &lt;ownerName&gt;/&lt;appName&gt;". I suppose this is the old cli which is no longer needed to be used with appcenter. 
The command should be updated as "appcenter codepush deployment list".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39490e39-be97-2bba-5afc-6bc8bed39690
* Version Independent ID: 357a2070-e41c-b346-e18b-606eec7255c2
* Content: [Using the React Native SDK with CodePush - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#android-setup)
* Content Source: [docs/distribution/codepush/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@Girish2015 thanks, I'll have the team take a look.

**Comment by Zakeelm** [comment]
Going to go ahead and close this, have submitted a PR to fix this. Should be live soon. Thanks for pointing this out!

**Comment by theill** [comment]
This documentation still references "code-push" CLI command instead of "appcenter". Did the PR not get merged?

**Comment by jwargo** [comment]
@Zakeelm can you please take a look?
