### ISSUE TITLE
App Center variables examples

### ISSUE THREAD

**Issue by Eyesonly88** [MicrosoftDocs/appcenter-docs#296]
In the App Center Variables section, the variable name and a brief description is provided. However, it is sometimes unclear what the expected values of those variables are. It would be great if another column is added that has an example value of each variable.

For example, what is the value of `APPCENTER_REACTNATIVE_PACKAGE `? is that whatever is inside `package.json` ? or is it the project build version number?

Another question is, how do we know if the build was triggered for from an Android project or iOS project for a React Native app?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca50588e-c8ad-2b8e-683f-bc5fc612dfe4
* Version Independent ID: 5d9513bd-d179-eaeb-96aa-06bd5ba0224f
* Content: [Build Scripts - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/)
* Content Source: [docs/build/custom/scripts/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/scripts/index.md)
* Service: **vs-appcenter**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by jwargo** [comment]
@Eyesonly88 that's a good suggestion, I'll have the PM take a look.

**Comment by nilofer** [comment]
Thanks for the suggestion @Eyesonly88! We'll take a look at that table and see how we can provide some more clear examples. For your RN question, if you have both an iOS app and Android app configured from the same repo to be built when you push a new commit, both projects will get built.

**Comment by Eyesonly88** [comment]
Hi @nrajpurkar ok thanks. Regarding the RN question, yes they both get built but when having a post-build script, we need to know programatically which build is being built.

For example, if we are doing a `CodePush` post-build, then we need to know which version (iOS or Android) to do the CodePush deploy for.

**Comment by manueldomi** [comment]
@Eyesonly88 So is there any way to know if the build script is being executed for IOS or Android or we must manually set an ENV variable to distinguish ?
