### ISSUE TITLE
Using API Rest for automations

### ISSUE THREAD

**Issue by juliohenderson** [MicrosoftDocs/appcenter-docs#299]
How to enable codepush through API?
I am analyzing the swagger page but have not yet found any way from api to this action

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/pt-br/appcenter/api-docs/#how-to-find-your-app-name-and-owner-name)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@juliohenderson The CodePush REST API is documented on our [Swagger Page](https://openapi.appcenter.ms/#/codepush). What are you trying to do with the API?

As I understand it, the publishing process requires the App Center CLI, there isn't a REST API for that part of it as it relies upon stuff happing on the developer's PC to publish an update. I've asked the product's PM to take a look, he can provide more information than I can,.

**Comment by juliohenderson** [comment]
I'm working on a whitelabel system and I'm automating our publishing, so I'm creating an app directly from the api and in the back comes the app_secret and I'm saving it in our DB but I also need to have the deployment key to save in the bank and later able to automate our build. What is missing? I already have the deployment key return with /v0.1/apps/{owner_name}/{app_name}/deployments but I have to go to the App Center site and manually enable the CodePush functionality to be able to generate the keys and I would like to do this activation through the API to create more automations, is there any way I can do this?

**Comment by jwargo** [comment]
@juliohenderson The best way to get help is not by asking here. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
