### ISSUE TITLE
Appcenter download page & links

### ISSUE THREAD

**Issue by gregkeys** [MicrosoftDocs/appcenter-docs#30]
We are in the process of integrating appcenter and running into a user acceptance issue.

The download page for the app shows the app name which is not attractive to our customers for example
example-com-Android
example-com-iOS

we would like to be able to change that title to something more attractive such as
example.com Android App
example.com iOS App

also the downloads are coming from rink.hockeyapp.net we are getting feedback from customers thinking our site has been hacked, can this be change to either microsoft or something less suspect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9596a2ab-2a3d-66cc-bc9d-b06256bef86f
* Version Independent ID: 9c12d768-6e98-997b-192a-623e3d7bb68e
* [Content](https://docs.microsoft.com/en-us/appcenter/general/#feedback)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/index.md)
* Service: vs-appcenter

**Comment by lumaxis** [comment]
Hey @gregkeys!

Please note that these GitHub comments are meant for issues specific to our documentation. To get help with a particular feature, use the blue chat button in the lower-right corner of the App Center dashboard window.
Could you please open a chat there with your specific app name so we can check why the name shows up wrong in the dialog? Feel free to mention you talked to Lukas before, so it gets correctly routed to me.
The URL will most likely change at some point but for now we are continuing to use URLs from HockeyApp, which is itself also an official Microsoft product.
