### ISSUE TITLE
Breaking Changes: Update Carthage to Version 0.31.1

### ISSUE THREAD

**Issue by jeremycbutler** [MicrosoftDocs/appcenter-docs#300]
Xcode 10 introduced an issue when using Carthage bootstrap that would produce a `Could not find any available simulators for iOS` during builds on the Cloud Build Machines. The issue was introduced as Apple changed the way they are [listing available devices](https://github.com/Carthage/Carthage/issues/2602) that Carthage was not handling.

Carthage released an update last night to fix this issue and can be found in [Carthage version 0.31.1](https://github.com/Carthage/Carthage/releases).

App Center is currently unusable while the Cloud Build Machines are still using the 0.30.0 version of Carthage. Please update as soon as possible!

**Comment by jwargo** [comment]
@jeremycbutler The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by sstadelman** [comment]
@jwargo Hey John!

**Comment by jwargo** [comment]
@sstadelman hey!  Wassup?
