### ISSUE TITLE
Using App Center build service but dSYM and map files aren't uploaded automatically.

### ISSUE THREAD

**Issue by alexandrius** [MicrosoftDocs/appcenter-docs#305]
Hi, I'm using AppCenter build service with ReactNative app but crashes tab still requires me to upload mapping files. Any help is highly appreciated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a12c34d-324f-63d9-6e74-2794d468c51d
* Version Independent ID: 7320e6d7-a421-2cad-f620-b76d799495f1
* Content: [Symbolication - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/symbolication)
* Content Source: [docs/diagnostics/symbolication.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/symbolication.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by jwargo** [comment]
@alexandrius The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
