### ISSUE TITLE
Send directed push notification based on custom properties

### ISSUE THREAD

**Issue by shnaz** [MicrosoftDocs/appcenter-docs#308]
Hey
I was looking at the Push notification and was wondering if it is possible to send notifications to a set of devices based on custom properties?
F.x I want to notify all devices with following custom property:
email: bob@email.com
Documentation states that it is possible to create Audiences based on properties and notify thereby audiences, but I am not interested in creating and saving it as an Audience.

Basically what I want is to fetch a set of DeviceIds based on some custom properties and then via. the API(doing this from our own service backend) send a notification to the specific device ids, type: devices_target.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb96601-f906-374d-b0d8-537e5f80de3e
* Version Independent ID: b66d21ae-1205-3d76-f577-d58891382c08
* Content: [App Center Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/pushapi#send-notifications-via-api)
* Content Source: [docs/push/pushapi.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/pushapi.md)
* Service: **vs-appcenter**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by jwargo** [comment]
@shnaz I'm not sure whether you can do this, I'll ask the PM to respond. 

The easiest way to get help is to use our dedicated support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by shnaz** [comment]
Sending notification based on properties(without having to save it as audience) can be useful in many ways. 
It is often useful to send one-time notifications based on certain criterias. 
For example: Sending a one-time notification to devices in Denmark(Country=DK) who has the AppVersion=1.1 and DeviceModel=SM-G950F. 

Is this something Visual App Center Notifications has on the roadmap?

**Comment by jwargo** [comment]
@shnaz as I mentioned, you should ask your product questions through support. Login to App Center and use the blue chat button on the lower-right corner of every page. You can also access support through the link I provided in my previous response.

**Comment by shnaz** [comment]
Support says it cannot be done, hence my question: "Is this something Visual App Center Notifications has on the roadmap?" 

@jwargo @dimazaid 

Thanks in advance

**Comment by dimazaid** [comment]
Hello @shnaz ! 
This is something on our roadmap but no timeline at the moment. I'll find your ticket on Intercom and continue the discussion there.

**Comment by shnaz** [comment]
Basically what I am referring to is the OneSignal's way of sending notification based on custom properties(filters): [Create notification based on filters/tags](https://documentation.onesignal.com/reference#section-send-based-on-filters-tags-create-notification)

Can you give an ETA for this kind of functionality so our team can know what to expect in the near future?

We are very excited about App Center and would like to use it for push notification, analytics and crash reporting(transitioning from HockeyApp soon which we use currently).

Best regards

**Comment by jwargo** [comment]
@shnaz I just took over responsibility for the Push service (and Azure Notification Hubs as well), let me chat with @dimazaid first and I'll get back to you.

**Comment by shnaz** [comment]
Thanks @dimazaid.

Currently we have implemented a solution using OneSignal purely because of that feature. We use it to send notifications to specific users.

**Comment by thiago-rcarvalho** [comment]
We need this feature too 😕
We are currently evaluating other services as App Center does not offer this.

**Comment by smilingerdk** [comment]
This would be very useful for me too!

**Comment by jwargo** [comment]
All - thanks for the feedback. As @dimazaid said, it's on our roadmap, but I can't provide an ETA at this time. Right now you can do this through custom properties and audiences, but I understand the need for a more ad-hoc way to do this.
