### ISSUE TITLE
Error when submitting though interface

### ISSUE THREAD

**Issue by masimplo** [MicrosoftDocs/appcenter-docs#309]
Submitting the app to *iTunes Connect users* through the App Center interface, exactly as described here, I get an error:

```
DEBUG [2018-10-16 06:38:47.07]: [Transporter]: DBG-X: parameter Errors = [ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/Xxxxxx.app/Assets.car' can't be read. Try rebuilding the app with a non-beta version of Xcode and submit it again."]
```
Submitting the exact same IPA through Application Loader works fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edcd9010-7381-ef0a-85ee-3289b742c8de
* Version Independent ID: 63c5a53d-e211-a17e-e0c0-27638748da7d
* Content: [Publish to iTunes - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple)
* Content Source: [docs/distribution/stores/apple.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/apple.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by jwargo** [comment]
@masimplo The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
