### ISSUE TITLE
Distribution options.

### ISSUE THREAD

**Issue by randomiser** [MicrosoftDocs/appcenter-docs#31]
"Support to sign with a Distribution certificate and provisioning profile will be added at a later time." 
Is there an ETA or roadmap available for this? This is 100% the feature we need for appcenter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01f1809-2316-7d47-1547-23775f6dd618
* Version Independent ID: 7d719380-4d1d-e995-e0e5-b2474ae5e9af
* [Content](https://docs.microsoft.com/en-us/appcenter/build/ios/code-signing)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/code-signing.md)
* Service: vs-appcenter

**Comment by dipree** [comment]
This only counts when automatic signing is enabled, you can still sign for distribution with manual signing. However, there's currently no ETA when we will support to sign for distribution with automatic signing.

**Comment by jwargo** [comment]
@derpixeldan close this?

**Comment by dipree** [comment]
Will it open a new one when he's answering?

**Comment by jwargo** [comment]
@derpixeldan It will reopen automatically if/when he responds.

**Comment by syntax-e** [comment]
Does this thread imply that I'll need to leverage Xcode manual certificates (and not Xcode Managed Certificates) if I intend to distribute App Center ad-hoc iOS builds to testers within my company via App Center?

**Comment by jwargo** [comment]
@geocachingsyntaxerror The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by syntax-e** [comment]
That makes sense. I do believe the docs could be a little more clear about when Xcode Automatically Managed Signing is appropriate and when Manual Signing is required; especially for common use cases like local build (development profile) vs a beta build (ad hoc profile) build vs a distribution build (distribution profile.)

**Comment by martin-richter-uk** [comment]
Do I still need to use manual sign for distribution?
