### ISSUE TITLE
Build Failed because of Workspace

### ISSUE THREAD

**Issue by RonMcgonagall** [MicrosoftDocs/appcenter-docs#310]
Hello ! 

I am trying to build my iOS app and the workspace specify in the build command is not correct : 
[command]/usr/bin/xcodebuild -sdk iphoneos -workspace /Users/vsts/agent/2.140.2/work/1/s/ACPT.xcodeproj/project.xcworkspace ...

causing the 
##[error]Error: /usr/bin/xcodebuild failed with return code: 65

/project.xcworkspace should not be listed there. If I build locally or on Aure Dev Ops and I specify /Users/vsts/agent/2.140.2/work/1/s/ACPT.xcodeproj it work perfectly.

However, there is no way to edit the workspace in app center.

Also, in the build config of app center, the Project/Workspace section display ACPT.xcodeproj only

Thanks !

**Comment by jwargo** [comment]
@RonMcgonagall  The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
