### ISSUE TITLE
[Swift - iOS] How can I add some big files which are not on GitHub ?

### ISSUE THREAD

**Issue by aman-sood** [MicrosoftDocs/appcenter-docs#313]
I have some third party SDK framework which is around 900 Mb in size and only needed for app. build, versioning is not required as we don't maintain it. 

Also Github has a limitation for 100 Mb so even if we want we can't use Github.

I am looking out for dev center integration with my Github repository for my project. Please help

**Comment by jwargo** [comment]
@aman-sood The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
