### ISSUE TITLE
How to send a push to a group of user_id(s) from our backend?

### ISSUE THREAD

**Issue by oferRounds** [MicrosoftDocs/appcenter-docs#316]
It’s not clear to me:
1. What user_data does our backend need to store in order to send push to a group of users?
2. Can it work with our internal user_ids?
3. If so, when is the connection between the device push token and our external user_id is made?
4. Where is this connection stored – in App Center or in our backend?
Etc.

Can you explain a bit about the flow in general?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a483e190-f75f-a52c-2472-e459d20df9d6
* Version Independent ID: 126a6e30-7c6d-f42c-57c3-2ac62d619ac8
* Content: [App Center Push Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/faq)
* Content Source: [docs/push/faq.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/faq.md)
* Service: **vs-appcenter**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by dimazaid** [comment]
Hi @oferRounds, can you please send these questions on our Support? I'll be able to answer them better. When you go to the App Center portal, click on the blue bubble on the bottom right corner of the screen. 

To briefly answer your questions:
The best way would be to create a mapping table in your backend, that maps the user_ids to Installation IDs. At the time of Push you will retrieve the installation ID based on the user_id and use it to directly send the push notification. We can provide more info via the support channel as described above.

**Comment by oferRounds** [comment]
Thanks, will do!
