### ISSUE TITLE
Annotations on errors

### ISSUE THREAD

**Issue by nathanielcook** [MicrosoftDocs/appcenter-docs#317]
With these changes, can annotations now be added to errors?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5b27c9-d8b4-38a4-8302-09a5c670278d
* Version Independent ID: a412a737-f270-e0fb-cdd9-abdcb98f74df
* Content: [Updates on App Center Diagnostics are coming soon - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/pre-merge)
* Content Source: [docs/diagnostics/pre-merge.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/pre-merge.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by jwargo** [comment]
I'm not sure. Have you asked support? That's the best way to get help. Click the blue chat icon in the lower-left corner of any App Center page.

**Comment by blparr** [comment]
@nathanielcook That is correct. Annotations will now be available for both errors and crashes.
