### ISSUE TITLE
Thx 

### ISSUE THREAD

**Issue by firewicca** [MicrosoftDocs/appcenter-docs#318]
THz thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba5bae42-8218-6f63-b28f-b6e6642f3ea2
* Version Independent ID: 1082232d-7609-692b-5d76-903a1134bf97
* Content: [Getting Started with App Center Test - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/getting-started)
* Content Source: [docs/test-cloud/getting-started.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/getting-started.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@firewicca Did you have a question? The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
