### ISSUE TITLE
OS vs Platform

### ISSUE THREAD

**Issue by kszicsillag** [MicrosoftDocs/appcenter-docs#319]
In section "Create your App" there is a step "Select the appropriate OS and platform depending on your project as described above". However, on the "Add new app" page of App Center there is no option for Unity. The Prerequisites section does not help either as it lists platforms, but on the App Center page these options are more related (but not fully equivalent though) to the OS radio button group. On the page the platform options are OS dependent, but none of them offers option for Unity. What platform should we choose on the Add new App page for Unity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0365781-58e5-a72a-9422-0ebd586877fe
* Version Independent ID: 5f7e41ef-448a-b27b-9041-bb38ff38ae16
* Content: [Get Started with Unity - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/unity#2-create-your-app-in-the-app-center-portal-to-obtain-the-app-secret)
* Content Source: [docs/sdk/getting-started/unity.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/unity.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by jwargo** [comment]
@kszicsillag the PM for this product is out today, but I'll see if I can get you an answer ASAP. In the mean time, don't forget about our dedicated product support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jwargo** [comment]
@kszicsillag I think the Unity UI is behind a feature flag, please reach out to support and ask them, they should be able to turn it on for you.

**Comment by kszicsillag** [comment]
Now I see the Unity option in the platform list, thanks!
