### ISSUE TITLE
"no-duplicate-release-error" was renamed already

### ISSUE THREAD

**Issue by arznaar** [MicrosoftDocs/appcenter-docs#32]
https://github.com/Microsoft/appcenter-cli/pull/367

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c2bd47-97e3-abc8-fbdd-305f0c631827
* Version Independent ID: 318718e7-a38a-7cc5-01a4-7ce0153c4398
* [Content](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/cli.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@arznaar I'm not sure I understand what you're asking be done here. Can you elaborate? Are you proposing a change?

**Comment by arznaar** [comment]
Page https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/cli.md has the following text:
```
Releasing Updates (Cordova)

appcenter codepush release-cordova -a <ownerName>/<appName> -d <deploymentName> -t <targetBinaryVersion> 
[-t|--target-binary-version <targetBinaryVersion>] 
[--is-release-build-type] 
[-b|--build] 
[-r|--rollout <rolloutPercentage>]
[--no-duplicate-release-error] 
[-k|--private-key-path <privateKeyPath>] 
[-m|--mandatory] 
[-x|--disabled] 
[--description <description>] 
[-d|--deployment-name <deploymentName>]
[-a|--app <ownerName>/<appName>] 
[--disable-telemetry] 
[-v|--version] 
```

But today `--no-duplicate-release-error` doesn't work because it was renamed in https://github.com/Microsoft/appcenter-cli/pull/367 and released already.

I believe we should fix documentation: change `--no-duplicate-release-error` key to `--disable-duplicate-release-error`

**Comment by arznaar** [comment]
I tested it on the appcenter-cli@1.0.11 (release-cordova command), but this key is mentioned in other code-push commands too. So, i believe, you should check the current version and update documentation for them too if needed

**Comment by jwargo** [comment]
@arznaar thank you. I've assigned the feature's program manager to review this and make the appropriate updates to the docs.

**Comment by jwargo** [comment]
Docs have been updated to reflect this change.
