### ISSUE TITLE
Suggestion: IApp.Invoke for Xamarin Forms

### ISSUE THREAD

**Issue by ehuna** [MicrosoftDocs/appcenter-docs#321]
Could you please add a 'Backdoor' for Xamarin Forms?

I can use the IApp.Invoke on iOS and Android - and then call some code on my Core/PCL/NetStandard library - but it would more elegant if I could just have an IApp.Invoke that works directly on Xamarin Forms, e.g. maybe directly on the code-behind of a XAML page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa921db3-7ee6-595d-e9a7-c32feecffe1d
* Version Independent ID: 674ae548-212c-5a24-7d2b-ef8792a1015a
* Content: [Working With - Backdoors - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-backdoors)
* Content Source: [docs/test-cloud/uitest/working-with-backdoors.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/working-with-backdoors.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
I'm not sure exactly what you're asking for, but I'll pass this on to the PM.

**Comment by glennwester** [comment]
Hi @ehuna, thanks for writing in. This is a feature request to have invoke work across Xamarin Forms shared code, this is something we can look into!
