### ISSUE TITLE
it is unable to debug test with xamarin.UITest via android device

### ISSUE THREAD

**Issue by juepiezhongren** [MicrosoftDocs/appcenter-docs#323]
vs 15.8.6
xamarin.UITest 2.2.6.1904-dev

when i debug the test, it was unable to enter the break point, and just with the output of 
"The thread 0x3f84 has exited with code 0 (0x0).
The program '[17356] testhost.x86.exe' has exited with code 0 (0x0)."

**Comment by jwargo** [comment]
@juepiezhongren The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by juepiezhongren** [comment]
once i can not use xamarin.Uitest locally, how can i move into cloud?????

**Comment by jwargo** [comment]
@juepiezhongren as I said, use product support.
