### ISSUE TITLE
Unity is not listed under the SDK -> Getting Started node

### ISSUE THREAD

**Issue by craigktreasure** [MicrosoftDocs/appcenter-docs#324]
The Unity docs are difficult to find unless you access them from a search engine. People might get the idea that Unity is not supported.
![image](https://user-images.githubusercontent.com/6309423/47324765-010c2d80-d616-11e8-9883-b24e8ac48e00.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0365781-58e5-a72a-9422-0ebd586877fe
* Version Independent ID: 5f7e41ef-448a-b27b-9041-bb38ff38ae16
* Content: [Get Started with Unity - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/unity)
* Content Source: [docs/sdk/getting-started/unity.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/unity.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by elamalani** [comment]
@craigktreasure We are officially going to enable Unity support in a few days. Once we enable the platform support, we will also light up the docs to get started with Unity SDK. 

I'll share more information with you on the email thread. :)
