### ISSUE TITLE
Stalled error displaying continually when I run iOS app using appium on appcenter

### ISSUE THREAD

**Issue by neerajkumar-lad** [MicrosoftDocs/appcenter-docs#325]
## Description
I am trying to run iOS automation on appcenter using the following command

command:
appcenter test run appium --app "username/appname" --devices f5c68fb6 --app-path "/Path/XXXX.ipa"  --test-series "applaunchtest" --locale "en_US" --build-dir /path/target/upload 

When I run above command I could see that in the app-center test created and does all pre-requested like validating.. uploading.. and start execution on device also.. after 5 mins execution start giving error as "Current test status: Stalled error (contact support for more info)"

I tried changing other iPhone devices but the same result always.

## Environment:
iOS App React Native Version : 0.57.1

**Comment by jwargo** [comment]
@neerajkumar-lad The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
