### ISSUE TITLE
where can i submit issue about xamarin.UITest???

### ISSUE THREAD

**Issue by juepiezhongren** [MicrosoftDocs/appcenter-docs#326]
said above

**Comment by jwargo** [comment]
@juepiezhongren The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
