### ISSUE TITLE
we need docs about how to debug test against java-apk via real device.

### ISSUE THREAD

**Issue by juepiezhongren** [MicrosoftDocs/appcenter-docs#327]
said above

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0474be-6e14-b8e6-b6cf-934a04f0e509
* Version Independent ID: 4a79fc1d-8dca-1c17-718f-c30fda180f05
* Content: [Xamarin.UITest - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/#feedback)
* Content Source: [docs/test-cloud/uitest/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/index.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@juepiezhongren I'll pass the feedback on to the product's PM.
