### ISSUE TITLE
Missing information for installing a build for iOS and other platforms

### ISSUE THREAD

**Issue by derekr** [MicrosoftDocs/appcenter-docs#328]
Would be helpful to include info for installing on other platforms. Right now I'm experiencing an issue where I've registered a device, but when I navigate to an app I know I have access to I get an error about not having access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3659cbf-c706-9af5-b3ed-9e0cdb5f2819
* Version Independent ID: 97d69564-1130-e541-9362-c9272983784d
* Content: [Install a Build from App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/installation)
* Content Source: [docs/distribution/installation.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/installation.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by jwargo** [comment]
@derekr thanks for the suggestion, I'll pass it on to the PM. Are you getting the help you need from our support team?

**Comment by derekr** [comment]
I didn't contact support, but if I refresh the page that says I don't have access it loads the install screen.

**Comment by jwargo** [comment]
@derekr interesting. Well, don't forget it's there when you need it. Just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by gaknoll** [comment]
Thanks for the feedback @derekr! We are currently redoing all of the docs for Distribution that includes a more complete section for installing builds as a tester. We'll be going live in the upcoming weeks.
