### ISSUE TITLE
removeListener is performed automatically.

### ISSUE THREAD

**Issue by PaliwalSparsh** [MicrosoftDocs/appcenter-docs#330]
https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/8efd255623163c9e73b95c3eeee3e6593cc9398e/appcenter-crashes/Crashes.js#L80

Maybe you should make it clear that there is no need to removeListener as you have done that yourself while calling setListener. I was worried if there could be problem calling setListener mulitple times. And thanks for everything the documentation is awesome and also the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e420f-cf2a-1d5b-d86a-d01c09bcf7a0
* Version Independent ID: 59c746fb-cf4d-3019-2b48-56b69e09aa27
* Content: [App Center Crashes for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native#process)
* Content Source: [docs/sdk/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@PaliwalSparsh thanks for the feedback, I'll pass it on.

**Comment by jwargo** [comment]
@PaliwalSparsh we made an update to the docs this morning. Closing this issue.
