### ISSUE TITLE
iOS push notification - Appcenter "category" keyword ignored

### ISSUE THREAD

**Issue by gunapandianraj** [MicrosoftDocs/appcenter-docs#332]
Unable to send iOS reserved key value pair { "Category" : "value" }  to show custom actions for push notification's. for now category key value pair is ignored while converting to platform specific payload.

In documentation only following reserved keys are provided : 
- badge
- sound
- content-available
- mutable-content

i would like to know is this a limitation in Appcenter push or is there any alternate keyword we have to use.

**Comment by dhei** [comment]
Hi @gunapandianraj,

Thanks for getting in touch. 

When you send a push notification with custom data `{ "Category" : "value" }`, if you've implemented `- (void)push:(MSPush *)push didReceivePushNotification:(MSPushNotification *)pushNotification` delegate to intercept the notification, you should see your custom data in `pushNotification.customData`. I verified just now `{ "Category" : "value" }` custom data worked as expected. For more information, see our docs on [Intercept push notifications](https://docs.microsoft.com/en-us/appcenter/sdk/push/ios#intercept-push-notifications).

Can you clarify what do you mean by 
> for now category key value pair is ignored while converting to platform specific payload.

**Comment by gunapandianraj** [comment]
well the thing is it should not come under custom data. Its a iOS Reserved Keyword (like 
 eg .Badge,Sound .. etc) to show custom buttons in push notification. 

if its coming under custom data the system will not intercept and it will not show our registered custom actions. 

Looks like its a limitation in appcenter for now. Thanks for the response.

Refer this apple doc for category keyword:

https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types

**Comment by gunapandianraj** [comment]
The payload conversion am talking about is if you send this below json in appcenter [swagger](https://openapi.appcenter.ms/#/push) API for push
```

{
  "notification_content": {
    "name": "Welcome",
    "title": "WelcomeTitle”,
    "body": "Welcome",
     "category":"test",
    "custom_data": {
      "additionalProp1": "string",
      "additionalProp2": "string",
      "additionalProp3": "string"
    }
  }
}
```
i will get the converted payload in device like below.

```

{
    aps =     {
        alert =         {
            body = Welcome;
            title = WelcomeTitle;
        };
    };
    "mobile_center" =     {
        additionalProp1 = string;
        additionalProp2 = string;
        additionalProp3 = string;
    };
}


```

above you can see the **category** key pair is not coming. 

I need payload like below for custom actions to work in iOS.


```
{
   “aps” : {
      “category” : “test”
      “alert” : {
         “body” : “Welcome!”
         “title” : “Push From App Center”
        
      }
   }
}

```

**Comment by dhei** [comment]
@gunapandianraj,

Thanks for the clarification. 
What you asked for is definitely on our roadmap. We don't have an ETA for this, but we will provide an update if as soon as it becomes available.

**Comment by Phenek** [comment]
Hey guys,

@gunapandianraj  Do you have a workaround?

@dhei Is this feature is really in the roadmap?

We need this for our users could fast reply.

**Comment by jwargo** [comment]
@Phenek As @dhei said, we want to fix this, but we have other work we're focused on right now. Your best option right now is to build a local notification using the custom data from the notification.
