### ISSUE TITLE
Cancel build from script

### ISSUE THREAD

**Issue by danielmhanover** [MicrosoftDocs/appcenter-docs#333]
Is there a way to cancel or change a build, or just the build's distribution, after checking a condition in a post-clone or pre-build script?

**Comment by jwargo** [comment]
@danielmhanover The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
