### ISSUE TITLE
Is there any support for Cucumber framework?

### ISSUE THREAD

**Issue by arifzaman2** [MicrosoftDocs/appcenter-docs#337]
Greetings,

I just wanted to know whether App Center supports Cucumber framework. I wanted to add some test cases in my automation code using Cucumber. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium)
* Content Source: [docs/test-cloud/preparing-for-upload/appium.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@arifzaman2 not that I know of, but I'll ask the PM to weigh in here. Also, remember that App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by glennwester** [comment]
@arifzaman2 Hello! Our cucumber support is limited to Calabash, which has been deprecated. Which testing framework are you using to drive synthetic gestures?

**Comment by Adegreenfinch** [comment]
How can a script written with appium and cucumber be adapted to work in app center?

**Comment by jwargo** [comment]
@Adegreenfinch The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
