### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by ts-taibul** [MicrosoftDocs/appcenter-docs#34]
good

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa9700f5-b9e0-dfe1-ddbc-b5a3231dde11
* Version Independent ID: 11728c80-1474-c1dc-caf0-2c6b6c44bbb3
* [Content](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/android.md)
* Service: vs-appcenter

**Comment by Vitala764** [comment]
Ага
