### ISSUE TITLE
Status code 500 when trying to login with my apple developer account

### ISSUE THREAD

**Issue by VanHoutte** [MicrosoftDocs/appcenter-docs#340]
Hi

I'm trying to link my apple developer account but I get the following error on the network request to the server:
Status code 500: {"error":{"code":"internal_server_error","message":"Internal Server Error (Support ID: 883a0e6c-fe49-421a-9251-d65ff44b0f6d)"}}

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edcd9010-7381-ef0a-85ee-3289b742c8de
* Version Independent ID: 63c5a53d-e211-a17e-e0c0-27638748da7d
* Content: [Publish to iTunes - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple#adding-two-factor-authentication)
* Content Source: [docs/distribution/stores/apple.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/apple.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by jwargo** [comment]
@VanHoutte1337 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
