### ISSUE TITLE
Javascript/Nativescript Support?

### ISSUE THREAD

**Issue by biapar** [MicrosoftDocs/appcenter-docs#341]
Is't possibile to use App Center with other JS framework like Angular o VUEJS or Nativescript?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a9c2bfe-e6be-bce0-7d66-8af878cecffa
* Version Independent ID: 00ed44c9-1037-03b1-be92-0d2869cc4b23
* Content: [App Center Push - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-3ypX_BhzCCqdW9dOWG4.CQ&epi=je6NUbpObpQ-3ypX_BhzCCqdW9dOWG4.CQ&irgwc=1&OCID=AID681541_aff_7593_1243925&tduid=(ir__uyss121223l10wf1hm6296w2k22xkeulke9bkguo00)(7593)(1243925)(je6NUbpObpQ-3ypX_BhzCCqdW9dOWG4.CQ)()&irclickid=_uyss121223l10wf1hm6296w2k22xkeulke9bkguo00)
* Content Source: [docs/push/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/index.md)
* Service: **vs-appcenter**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by jwargo** [comment]
@biapar Visual Studio App Center is a service for native applications; web applications are not supported at this time, nor is NativeScript.
