### ISSUE TITLE
No HEAD for /v0.1/apps/{owner_name}/{app_name}/push/devices/{install_id}

### ISSUE THREAD

**Issue by thisisthekap** [MicrosoftDocs/appcenter-docs#348]
As a developer I want to check if devices are registered using a HEAD request to `/v0.1/apps/{owner_name}/{app_name}/push/devices/{install_id}`.

`/v0.1/apps/{owner_name}/{app_name}/push/devices/{install_id}` supports DELETE only. This implies that a device has to be deleted to check if it actually is registered to receive push notifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb96601-f906-374d-b0d8-537e5f80de3e
* Version Independent ID: b66d21ae-1205-3d76-f577-d58891382c08
* Content: [App Center Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/pushapi)
* Content Source: [docs/push/pushapi.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/pushapi.md)
* Service: **vs-appcenter**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by jwargo** [comment]
@thisisthekap I've passed your feedback on to the PM team.

Remember, the comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by thisisthekap** [comment]
@jwargo Thanks for your effort. Should we follow up using this GitHub issue, or the App Center Help.

**Comment by jwargo** [comment]
@thisisthekap I left this issue open, so the PM team should respond to you here.

**Comment by dimazaid** [comment]
Hello,

This is not supported today, but we added it to our backlog of API updates.

Thanks!
Dimah
