### ISSUE TITLE
Where is build.gradle File located?

### ISSUE THREAD

**Issue by Rfxiao** [MicrosoftDocs/appcenter-docs#349]

**Comment by jwargo** [comment]
@Rfxiao Android projects have several, and the Android project structure changes from time to time.  Just look in the Android documentation or in your project folder.

The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
