### ISSUE TITLE
App Registration

### ISSUE THREAD

**Issue by godbrother** [MicrosoftDocs/appcenter-docs#355]
Associated Windows Store app not listing registration portal(https://apps.dev.microsoft.com/#/appList).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb42032-a67b-b601-7ef0-bdf1c8838f73
* Version Independent ID: 4d052b88-6fe1-358e-47a7-4d2687f02c10
* Content: [App Center Push for Universal Windows Platform - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/uwp#2-get-package-sid-and-application-secret-from-application-registration-portal)
* Content Source: [docs/sdk/push/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@godbrother Do you have a question or comment about the docs? The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by ghost** [comment]
Same issue for me. Associated Windows Store app not listing registration portal. Why does the app not appear under Registration Portal after i associated with store from VS

**Comment by jwargo** [comment]
@rjax87 as described here: https://github.com/MicrosoftDocs/appcenter-docs/issues/519, this issue relates to the app store and Visual Studio, not App Center. I suggest you take this up with the store.
