### ISSUE TITLE
Xamarin.Forms MAC support

### ISSUE THREAD

**Issue by rafsanulhasan** [MicrosoftDocs/appcenter-docs#356]
Currently there is no support for Xamarin.Mac projects in App center. Is there any plan to include Xamarin.Forms apps for MACOS in the Mobile center? If yes, how long it would take to include this feature into App center? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c51c4f2-ae33-9065-c235-76501ca3d406
* Version Independent ID: 967f2326-50f3-5be0-ac9c-9552ce43245f
* Content: [Configure a Objective-C or Swift Mac build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/macos/first-build)
* Content Source: [docs/build/macos/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/macos/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @andyzg
* Microsoft Alias: **t-anzha**

**Comment by jwargo** [comment]
@rafsanulhasan I'm not sure where this is on our roadmap, so I'll ask the PM to comment. 

Note: The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by nilofer** [comment]
Hi @rafsanulhasan, App Center does not currently support Xamarin.Mac and macOS support is in preview. It is not on our public short-term roadmap.
