### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by rafsanulhasan** [MicrosoftDocs/appcenter-docs#357]
I found that Android watch projects are supported in App center. Android TV projects using Xamarin.Forms project is not supported yet. Is there any plan to support it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b6246f8-55fc-c271-b83d-d1564c013fc8
* Version Independent ID: 48b809d8-ea94-af5f-e5be-9519403aa95f
* Content: [Configure a Java Android build in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/android/first-build)
* Content Source: [docs/build/android/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/android/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@rafsanulhasan I'll ask the PM to comment.

**Comment by jwargo** [comment]
@rafsanulhasan I'm not sure where this is on our roadmap, so I'll ask the PM to comment.

Note: The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs.

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the App Center Help Center.

**Comment by nilofer** [comment]
Hi @rafsanulhasan, App Center does not currently support Android TV projects and it is not on our public short-term roadmap.
