### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by rafsanulhasan** [MicrosoftDocs/appcenter-docs#358]
Currently tvOS projects are not supported in App Center? Is there any plan to include it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc01291c-f6a0-4610-a27d-60718852390d
* Version Independent ID: 2b51b117-6b8c-f4d9-a2b2-43c891d20171
* Content: [Configure a Objective-C or Swift iOS build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/first-build)
* Content Source: [docs/build/ios/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@rafsanulhasan I'm not sure where this is on our roadmap, so I'll ask the PM to comment.

Note: The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs.

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the App Center Help Center.

**Comment by nilofer** [comment]
Hi @rafsanulhasan, we do not have tvOS support on our public short-term roadmap.
