### ISSUE TITLE
xxx

### ISSUE THREAD

**Issue by didos2010** [MicrosoftDocs/appcenter-docs#36]
C:\> lxrun /setdefaultuser root

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb38f19-e7f0-8349-8731-e701745c644f
* Version Independent ID: d8928ac3-206c-e8f3-0124-364311e4e4d7
* [Content](https://docs.microsoft.com/en-us/appcenter/sdk/#requirements)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/index.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@didos2010 are you suggesting some change to the doc?
