### ISSUE TITLE
How do I upload builds like I do in hockey app today?

### ISSUE THREAD

**Issue by apple-ihack-geek** [MicrosoftDocs/appcenter-docs#360]
How do I upload builds like I do in hockey app today? Today we have our own build machines, we build our builds, and upload them to hockey app, and then our testers download the builds from hockey app.  We have no interest in paying for cloud based building machines.  But where is there documentation on uploading builds we build on our own  build machine? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc863ba-5295-2db8-b37f-584e662e725a
* Version Independent ID: db2a1468-e4fa-6c55-985f-616de1e6484f
* Content: [App Center Pricing Information - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/pricing)
* Content Source: [docs/general/pricing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/pricing.md)
* Service: **vs-appcenter**
* GitHub Login: @joemellin
* Microsoft Alias: **joemel**

**Comment by jwargo** [comment]
@apple-ihack-geek all of the documentation for App Center's distribution capabilities are in the Distribution section of the App Center docs. To upload your build, just use the instructions in the [Release a Build](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#uploading-the-package) doc.
