### ISSUE TITLE
Provide a way for an open APK distribution as in Hockey App

### ISSUE THREAD

**Issue by frmz** [MicrosoftDocs/appcenter-docs#361]
I am an Hockey App user dealing with the November 2019 deadline, currently i use Hockey to allow my users to manually download the app, this is done for beta testing but also to allow them to roll back their releases if they want to or install the app where no store is available. Hockey allows me to do this easily and distribute the APK in a PUBLIC page without any restriction. Here in app center i need to create and manage groups which doesnt work in this use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by gaknoll** [comment]
Hi @frmz - App Center does work a little differently when it comes to distribution groups. A solution for your scenario in App Center would be to create a distribution group - and either during creation or in the distribution groups settings menu - toggle on "Allow Public Access". This will generate a public URL that will allow any tester with the link to download the latest release (as seen in attached gif), without having to invite and manage individual testers. Note: we are currently working on a feature that would allow users with that link to also view and download previous versions of the app. 
Would this work for your scenario?
![public-groups-demo](https://user-images.githubusercontent.com/33528647/48714901-b9130300-ebe1-11e8-9aea-cb44e0bbf3fc.gif)

**Comment by frmz** [comment]
Thanks @gaknoll for the reply, yeah so, a public URL with the ability to download previous releases would have the same functionality as Hockey App public download page has now and allow me to switch over. Will test it ASAP, hope the "release history" feature will not take long.
