### ISSUE TITLE
Sending rich notifications (Expandable, Buttons, etc.)

### ISSUE THREAD

**Issue by ollyfg** [MicrosoftDocs/appcenter-docs#362]
Platform: React Native for Android.

I have got my app all set up and receiving push notifications, however I would like to be able to customise our notifications with buttons (https://developer.android.com/training/notify-user/build-notification), and to make them expandable if we are sending more than 1 line of text (https://developer.android.com/training/notify-user/expanded).

Is this possible using AppCenter Push Notifications? If not, what is the recommended way to enrich our notifications?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7078a8ed-8f99-1544-8601-8c778fd2bbc1
* Version Independent ID: 9b1886d6-c9f8-e73b-e2b6-db6022f579ac
* Content: [App Center Push for React Native Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-android)
* Content Source: [docs/sdk/push/react-native-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/react-native-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@ollyfg I'll have the team take a look at this one. We recently updated the docs to highlight more notification options, but perhaps we need to add more.

**Comment by achocron** [comment]
@ollyfg As of today, the App Center SDK does not have any APIs that enable rich notifications.

That being said, there is a possible workaround that you could use, but it's a bit complex and I haven't tested it. Basically, you will want to disable the Firebase messaging service and use a custom broadcast listener. This will prevent Firebase and App Center from  intercepting the notification. Then, you could implement your own receiver/notifier in Java, and follow the steps you linked above to add the actions.

For reference on how you might disable the Firebase messaging service, check out [this method](https://github.com/Microsoft/AppCenter-SDK-Android/blob/da30acb2727fd25680404fe187b5c2ac42340cc0/sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/FirebaseUtils.java#L63). This will also indirectly disable the App Center Push listener.

For the push notifier, I'd recommend using [this class](https://github.com/Microsoft/AppCenter-SDK-Android/blob/develop/sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/PushNotifier.java) as a reference.

Sorry that there is no straightforward way to accomplish what you are looking for.

**Comment by ollyfg** [comment]
Thanks for the links, I'll have a look!
