### ISSUE TITLE
Unable to add jira tracking

### ISSUE THREAD

**Issue by jalpesh** [MicrosoftDocs/appcenter-docs#363]
Getting the below error 

Add bug tracker
Error during processing Jira request

Not getting any information on how to solve it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99771c68-5f45-887a-e926-9ea772021f99
* Version Independent ID: 865109fc-64b8-ba77-2e10-8002886c46c7
* Content: [App Center bug tracker documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/)
* Content Source: [docs/dashboard/bugtracker/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/bugtracker/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@jalpesh The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jalpesh** [comment]
Sorry about that. Will do
