### ISSUE TITLE
Describe how to Version Releases via App Center Distribute task

### ISSUE THREAD

**Issue by Imroath** [MicrosoftDocs/appcenter-docs#365]
When releasing via AppCenter Release can have a number and timestamp format like 1.0(150912873).
When releasing via App Center Distribute task there is no documentation on how to specify the timestamp and all releases have a number 1.0(1). Please elaborate in the documentation on how the versioning should be done when using App Center Distribute task.

**Comment by jwargo** [comment]
@Imroath I've asked the PM team to take a look at your question and respond. In the mean time the comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jwargo** [comment]
@botatoes ????

**Comment by botatoes** [comment]
Hi, we are following the version and release semantics of Google and Apple. I will update the documentation to make it more clear.
