### ISSUE TITLE
How to remove Apple Developer integration?

### ISSUE THREAD

**Issue by MisterJimson** [MicrosoftDocs/appcenter-docs#366]
This content needs to describe how to remove the Apple Developer integration (remove the certificate and username/password) from App Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d13e061-cb49-5ee6-dfbd-249e8e2f11d5
* Version Independent ID: 88cb3aa2-3938-76b4-8297-dcc6380292d5
* Content: [Device registration - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/auto-provisioning)
* Content Source: [docs/distribution/auto-provisioning.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/auto-provisioning.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by jwargo** [comment]
@MisterJimson I'll ask the PM team to take a look. In the mean time, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by Oddj0b** [comment]
hi @MisterJimson that is a reasonable request and I will update it tomorrow.
