### ISSUE TITLE
How to download the proguard mappings.txt file?

### ISSUE THREAD

**Issue by prakashvadrevu** [MicrosoftDocs/appcenter-docs#368]
I am currently trying out the `Build` feature to build my Android app.

`ProGuard` is enabled in my Release build. After the app gets built, I am able to download the APK but not the `mappings.txt` file (the proguard mapping file). Where can I get that from? Can you please document it?

**Comment by jwargo** [comment]
@prakashvadrevu I'll have the PM team take a look at a doc update. In the mean time, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by prakashvadrevu** [comment]
Thank you @jwargo! I will ask the support team.
