### ISSUE TITLE
How to replace `google-services.json` file in the project root before build?

### ISSUE THREAD

**Issue by prakashvadrevu** [MicrosoftDocs/appcenter-docs#369]
I am currently trying out the `Build` feature to build my Android app.

I have to replace `google-services.json` file in the project root folder before the build starts. How do I do that? I tried the following steps:

- Added my `google-services.json` file contents in an Environment Variable in the Build configuration
- Wrote an `appcenter-pre-build.sh` script to read this environment variable's contents and copy them to an empty file and rename it to `google-services.json`

But, Somehow, I dont see this script getting triggered before the build starts. Can you please let me know if I am missing anything here or please let me know how to solve this.

**Comment by jwargo** [comment]
@prakashvadrevu The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by prakashvadrevu** [comment]
Thank you @jwargo! I will ask the support team.
