### ISSUE TITLE
errors api issues

### ISSUE THREAD

**Issue by studuffy** [MicrosoftDocs/appcenter-docs#372]
Hi, I noticed a couple of issues in the errors api: 

- the ../errors/errorCountsPerDay request (not for a specific errorGroup) is only ever returning zeros at the moment, even with a valid version provided. works fine for a specific errorGroup though.
 - it looks like there's an issue with the firstOccurrence value on the errorGroups calls. it seems to always be "0001-01-01T00:00:00Z"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/index#feedback)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@studuffy I'll have the PM take a look.

**Comment by blparr** [comment]
Hello,
Thanks for reaching out.

Can you please reach out to us via Support (blue button in the bottom right portal)? It'll be easier for us to investigate the issue.

Thanks!

**Comment by jwargo** [comment]
@studuffy Did you contact support? Is this still an issue for you?  I'm going to close this, please let me know if we need to do a doc update here.
