### ISSUE TITLE
Push notification title and message NULL

### ISSUE THREAD

**Issue by stesvis** [MicrosoftDocs/appcenter-docs#373]
I implemented this code and it works great while the app is running and open.
```
// This should come before AppCenter.Start() is called
// Avoid duplicate event registration:
if (!AppCenter.Configured)
{
    Push.PushNotificationReceived += (sender, e) =>
    {
        // Add the notification message and title to the message
        var summary =  $"Push notification received:" +
                            $"\n\tNotification title: {e.Title}" +
                            $"\n\tMessage: {e.Message}";
    
        // If there is custom data associated with the notification,
        // print the entries
        if (e.CustomData != null)
        {
            summary += "\n\tCustom data:\n";
            foreach (var key in e.CustomData.Keys)
            {
                summary += $"\t\t{key} : {e.CustomData[key]}\n";
            }
        }

        // Send the notification summary to debug output
        System.Diagnostics.Debug.WriteLine(summary);
    };
}

// AppCenter.start after
AppCenter.Start(..., ... ,typeof(Push), ...);
```
The problem is when the app in in the background, or when it's closed.
In those two cases, I get the notification, but after I click on it, the title and message are NULL, while the custom data is correctly set.

Why is that? How to get title and message in those cases?

**Comment by jwargo** [comment]
@stesvis The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by faramos** [comment]
@stesvis I´m having the same problem. Did you find the solution?
Thanks in advance

**Comment by jwargo** [comment]
@faramos please contact support for help.

**Comment by ronaldris21** [comment]
I-m getting the same issue, what can I do?

**Comment by jwargo** [comment]
@ronaldris21 ask our support team, the docs is not the place to get help with your code.
