### ISSUE TITLE
Does code signing require building the app in App Center?

### ISSUE THREAD

**Issue by suzukieng** [MicrosoftDocs/appcenter-docs#374]
I'm planning to migrate an app from HockeyApp to VS App Center. Previously we built the app on our own infrastructure and uploaded the IPA and symbols to HockeyApp via the REST API. This required us to rebuild/redeploy to HockeyApp every time the provisioning profile changes. VS App Center claims to be able to this automatically, but it's unclear to me if this is tied to building the app on VS App Center.

If we still want to build the app on our infrastructure (we would like to not give source repository access) and continue to upload IPAs, is VS App Center capable of re-signing the IPA and replacing the embedded provisioning profile with an updated one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01f1809-2316-7d47-1547-23775f6dd618
* Version Independent ID: 7d719380-4d1d-e995-e0e5-b2474ae5e9af
* Content: [iOS Code Signing in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/code-signing)
* Content Source: [docs/build/ios/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/code-signing.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by jwargo** [comment]
@suzukieng The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by thsbrown** [comment]
I would love and answer to this as well.

**Comment by inPhilly** [comment]
@thsbrown or @suzukieng did you find the answer to this? App Center Help Center is closed until Monday and I have a critical update that I need to post immediately.

**Comment by thsbrown** [comment]
@inPhilly it is possible to resign the app via app center. When a new iOS user signs up app center should add their device id and resign the app with them included. You can also do this manually from the dashboard
