### ISSUE TITLE
EarlGrey 2.0 is now open sourced.

### ISSUE THREAD

**Issue by tirodkar** [MicrosoftDocs/appcenter-docs#375]
Hey folks, quick documentation update - EarlGrey 2.0 is now open-sourced.

https://github.com/google/EarlGrey/tree/earlgrey2

It combines XCUITest with EarlGrey and therefore allows proper out-of-process end to end testing with XCUITest along with EarlGrey's robust synchronization and white-box testing support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8713388f-7f2b-1d33-2250-e2b4672feac9
* Version Independent ID: 108f8b11-d960-e440-138c-16b53e4989f8
* Content: [Mobile App Testing Frameworks Overview - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/migration/test-cloud/frameworks)
* Content Source: [docs/migration/test-cloud/frameworks.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/migration/test-cloud/frameworks.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@tirodkar thanks, I'll have the PM look at making a docs update.

**Comment by glennwester** [comment]
@tirodkar thanks! I have a PR open with these changes.

**Comment by tirodkar** [comment]
Awesome! Thanks @glennwester & @jwargo
