### ISSUE TITLE
Publishing APK to Google Play doesn't list current builds, only option is upload APK.

### ISSUE THREAD

**Issue by stevehurcombe** [MicrosoftDocs/appcenter-docs#377]
I have connected to the Google Play store but there doesn't seem to be a way to publish an APK from a build completed in appcenter. It is implying that I have to download the APK and the uploaded it back to be able to push it into the app store. What would be the benefit compared to downloading an uploading to Play?

Cheers
Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by stevehurcombe** [comment]
I've found the problem. Distribute->Stores->Alpha>Publish to store only allows upload APK.

Whereas Build->[Build]->Distribute->Store works as expected.

**Comment by jwargo** [comment]
@stevehurcombe I'm glad you found your solution. I sent a link to the PM to see if a doc update is warranted. 

In the meantime, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
