### ISSUE TITLE
Native app

### ISSUE THREAD

**Issue by corteggo** [MicrosoftDocs/appcenter-docs#378]
Where is Visual Studio AppCenter's native app located at? Is it available in AppStore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811f9eee-5b17-06e1-c108-dbef47984425
* Version Independent ID: 8fe50e13-c934-6a43-bf7d-1f33946da9d3
* Content: [Testing iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios)
* Content Source: [docs/distribution/testers/testing-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@corteggo No, there is not currently a version of the App Center app available for the iOS platform. 

Any time you need help with App Center, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by corteggo** [comment]
Next time, please update documentation early as you stated in https://github.com/MicrosoftDocs/appcenter-docs/issues/418. Thank you.

**Comment by jwargo** [comment]
@corteggo I'm sorry, I don't understand the point of your statement. If you have constructive criticism for the docs, please share it. I apologize if this omission caused you an issue - when the doc was created, we had an iOS version of the app available. Unfortunately, Apple did not allow us to publish the app to the App Store. Apparently we forgot to pull that reference after we failed to get the iOS version published.
