### ISSUE TITLE
CodePush release promotion command incorrect?

### ISSUE THREAD

**Issue by jakeam** [MicrosoftDocs/appcenter-docs#38]
The documentation states that to promote a release it should look something like this `appcenter codepush promote -a <ownerName>/<appName> <sourceDeploymentName> <destDeploymentName>` where as I have to actually prefix the source and destination deployment names with -s and -d.

**Comment by wbget** [comment]
[this?](https://github.com/MicrosoftDocs/appcenter-docs/pull/4)
```
appcenter codepush promote -s Staging -d Production
```

**Comment by jwargo** [comment]
it's:

```
appcenter codepush promote -s <source_deployment> -d <dest_deployment>
```

So, to go from Staging to Production, you'd use:

```
appcenter codepush promote -s Staging -d Production
```
