### ISSUE TITLE
c++/cx Support

### ISSUE THREAD

**Issue by GlenUnderwood** [MicrosoftDocs/appcenter-docs#381]
Will there ever be app center support for apps built with c++/cx?

**Comment by jwargo** [comment]
@GlenUnderwood The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jwargo** [comment]
@GlenUnderwood like give me an example? We support a lot of platforms - not specific languages, but multiple target platforms. What are you looking for us to support? Anytime you have feedback, just click the blue button in the bottom-right corner of any App Center page and provide your feedback. It's all tracked and makes it back to the PM.

**Comment by GlenUnderwood** [comment]
Sorry, didn't mean to post on the wrong board. Followed this link from an MS page that was discussing analytics with App Center.   C++/CX is a microsoft extension to the C++ language for use on Windows' UWP platform. C# has support in App Center, but not c++/cx. It's an alternative .NET that we are required to use due to the vast amount of cross-platform code we use which us plain C++.
