### ISSUE TITLE
Appium version listed wrong

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [MicrosoftDocs/appcenter-docs#382]
Maybe I'm confused but I think the docs are wrong where they say "Support for Appium version 1.7.1 only". Appium 1.7.1 is not an available version (https://mvnrepository.com/artifact/io.appium/java-client) and your sample project is using Appium 5.0.4 (https://github.com/King-of-Spades/AppCenter-Test-Samples/blob/master/Appium/Android/Maven/pom.xml).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium)
* Content Source: [docs/test-cloud/preparing-for-upload/appium.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by glennwester** [comment]
Hi @Blackbaud-ChristiSchneider, Appium 1.7.1 is referring to the [Appium release](https://github.com/appium/appium/releases). We will soon upgrade this support to Appium 1.10.0. [java-client](https://github.com/appium/java-client/releases) has separate versioning.
