### ISSUE TITLE
Explicit steps to the Xcode scheme management

### ISSUE THREAD

**Issue by ariya** [MicrosoftDocs/appcenter-docs#383]
Instead of just:

> To share a scheme, click on "Manage schemes" in Xcode and ...

I suggest the complete detaile steps:

> To share a scheme, from Xcode menu, choose _Product_ > _Scheme_ > _Manage schemes_ and ...

This will save a hassle for those not completely familiar with Xcode scheme handling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3efbfa-b70b-9039-4b49-6ba4ce6c36af
* Version Independent ID: 73e079aa-bbc3-2a06-a5d1-c4827bd5e3dc
* Content: [App Center Build Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/ios)
* Content Source: [docs/build/troubleshooting/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/troubleshooting/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajp**

**Comment by jwargo** [comment]
@ariya that's a great suggestion, I'll have the PM take a look at the doc change.

**Comment by nilofer** [comment]
Thanks for the suggestion @ariya. We're updating this in the docs.
