### ISSUE TITLE
Real devices?

### ISSUE THREAD

**Issue by leffsu** [MicrosoftDocs/appcenter-docs#384]
No mentioning of the list of the real devices. Users are forced to sign up and try to look them up by themselves. I understand that you want people to check your service out but I'm not willing to use the service which neglects it.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: bdc863ba-5295-2db8-b37f-584e662e725a
* Version Independent ID: db2a1468-e4fa-6c55-985f-616de1e6484f
* Content: [App Center Pricing Information - Visual Studio App Center](https://docs.microsoft.com/ru-ru/appcenter/general/pricing)
* Content Source: [docs/general/pricing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/pricing.md)
* Service: **vs-appcenter**
* GitHub Login: @joemellin
* Microsoft Alias: **joemel**

**Comment by jwargo** [comment]
@leffsu our device catalog changes on a regular basis (when new devices are added, and older ones removed). This information is not listed on the pricing page, but you can find it [elsewhere in the documentation](https://docs.microsoft.com/en-us/appcenter/test-cloud/devices).
