### ISSUE TITLE
REQ: option for `appcenter release-react` to exclude bundling assets (only js)

### ISSUE THREAD

**Issue by mattslight** [MicrosoftDocs/appcenter-docs#386]
Hi I know that it is possible to bundle without assets using the vanilla command. But as per the docs the preferred method to deploy for react-native is through react-release (and I fully agree).

Can we have an option please to only bundle JS and exclude assets, this is helpful for making smaller deployment packages when you know the assets have not changed.

Thanks,
Matthew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c2bd47-97e3-abc8-fbdd-305f0c631827
* Version Independent ID: 318718e7-a38a-7cc5-01a4-7ce0153c4398
* Content: [Releasing CodePush updates using the App Center CLI - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#releasing-updates-react-native)
* Content Source: [docs/distribution/codepush/cli.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/cli.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@mattslight I'm not sure if that's possible. Let me have the PM take a look and respond.

**Comment by mattslight** [comment]
Thank you - really appreciate it. And please keep up the good work.

**Comment by Zakeelm** [comment]
Hey there @mattslight 

I'm not sure I quite understand the scenario you're trying to account for, can you clarify? 
From my understanding, the CodePush server performs file-based diffing, which ultimately means only updated and new files are sent to client device.

**Comment by mattslight** [comment]
Well the react-release command seems to bundle JS and assets in my case. The payload is about 4300Kb.

The payload size is fairly constant +/- 50kb and never seems to matter whether I do small or bigger changes (only ever to JS files).

The command I use is this: `appcenter codepush release-react -a ACCOUNT/PROJECT -d Staging --output-dir ./build`

**Comment by mattslight** [comment]
Checking the build/codepush folder confirms the following:-

```
build/CodePush  tree -d                                                                           10s
.
└── assets
    ├── assets
    │   └── img
    │       ├── intro
    │       └── patterns
    ├── js
    │   └── lib
    │       └── react-native-zss-rich-text-editor
    │           ├── img
    │           └── src
    └── node_modules
        ├── react-native-datepicker
        ├── react-native-elements
        │   └── src
        │       └── rating
        │           └── images
        ├── react-native-video-controls
        │   └── assets
        │       └── img
        └── react-navigation
            └── src
                └── views
                    └── assets

23 directories, 76 files
```

**Comment by mattslight** [comment]
Hi @Zakeelm - thanks for your help on this.

Is it clear what I am trying to achieve? Do you have any thoughts on whether my request is possible? My bundle size is rapidly increasing now over 5000Kb for every code push. I am concerned about the performance hit to my customers.

Thank you.

**Comment by jwargo** [comment]
@mattslight but we should be doing a delta comparison and only sending the changed assets. have you confirmed that all that data is being sent to the device?

**Comment by Zakeelm** [comment]
I do understand and +1 on what @jwargo said. The diff should account for this and only send the changed assets. I do have a follow up question, are each of your CodePush releases proceeded by a binary release?

**Comment by mattslight** [comment]
> @mattslight but we should be doing a delta comparison and only sending the changed assets. have you confirmed that all that data is being sent to the device?

I subscribed to CodePush progress updates as per:

```
CodePush.sync( {}, this.codePushStatusDidChange.bind(this), this.codePushDownloadDidProgress.bind(this)

codePushDownloadDidProgress(progress) {
    this.setState({ progress })
  }
```

And then in render

``` 
if (this.state.progress) {
      progressView = (
        <Text>
          {Math.round(parseInt(this.state.progress.receivedBytes) / 1024)} of{' '}
          {Math.round(parseInt(this.state.progress.totalBytes) / 1024)} Kb received
        </Text>
      )
```

That's how I came to know the size and I can 'watch' it downloading 5000Kb approx. I haven't used any network monitoring tools to actually confirm it, but I assume the CodePush progress methods are accurate.

**Comment by mattslight** [comment]
From what I can tell there is no 'delta' comparison. CodePush deployment payload is as per the tree I sent above. As you can see it is sending assets as part of the payload.

The `appcenter codepush release-react` is actually using the following command to generate the payload bundle:

` bundle --assets-dest build/CodePush --bundle-output build/CodePush/main.jsbundle --dev false --entry-file index.js --platform ios --sourcemap-output build/CodePush/main.jsbundle.map`

I can run this manually to reduce the bundle size without the --assets-dest

**Comment by jwargo** [comment]
@mattslight but to @Zakeelm's question, did you deploy a new binary before this?

**Comment by mattslight** [comment]
@jwargo Deployed new binary means Xcode build and appstore publish?

**Comment by jwargo** [comment]
yep, or deploy via USB to a local device.

**Comment by mattslight** [comment]
I don't always deploy a new binary (but isn't that the point of CodePush?). What's your line of thinking?

**Comment by jwargo** [comment]
@mattslight If you deploy a new binary with an older set of assets, then CodePush is going to deploy its whole bundle on sync.

**Comment by mattslight** [comment]
@jwargo Sorry, I don't follow can you elaborate please. 

Am I to understand from what you are saying that I should deploy a new binary to reduce the CodePush payload or that I shouldn't deploy a new binary?

**Comment by jwargo** [comment]
@mattslight shouldn't.

**Comment by mattslight** [comment]
Right - gotcha. So I generally only release a new binary if I link a new native library. If it's just JS updates then I codepush. The assets generally never change (app only has a few fonts, svgs and pngs).

**Comment by mattslight** [comment]
@jwargo Does 5000 kb for incremental CodePush releases sound a lot to you? What payload sizes should I be expecting if a handful of lines of JS change from push to push?

**Comment by jwargo** [comment]
@mattslight sorry, not an expert - I just own the docs. I do know that CodePush shouldn't be sending the whole package every time, should only be sending the changed assets. so, if you're getting everything, then we need to figure out why (whether it's your fault or ours :-)). At this point, the docs isn't the right place to be having this conversation. Can you please open App Center and click the blue chat button in the lower-right corner and start a conversation with our dedicated support team?  They'll help you and we'll see if this is a bug or something else. That OK?

**Comment by mattslight** [comment]
Sure no problem, I appreciate your help. Btw this really wasn't the conversation I wanted to have lol.

I came here because it says in the docs if I have a request for a feature I should raise it here. I was asking for a feature for `appcenter release-react` to have an option to exclude automatically adding the assets to the CodePush update.

Thanks for your time.

**Comment by jwargo** [comment]
@mattslight yeah, unfortunately, I think you found a bug. :-)
