### ISSUE TITLE
Cordova?

### ISSUE THREAD

**Issue by phil-lgr** [MicrosoftDocs/appcenter-docs#388]
Any ETA for Cordova builds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06813350-a37b-a4a2-fdbc-a59caefb9f32
* Version Independent ID: 29787958-5b4e-efc2-2af5-2af0ee53216e
* Content: [App Center Build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/)
* Content Source: [docs/build/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/index.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@phil-lgr We have no current plans to support Apache Cordova apps in the Build service; I'm sorry. That being said, I've been working on documenting this. I've gotten build working for Android projects and I'm this close to figuring it out for iOS applications. My plan was to write up some docs and a blog post by the end of the year (first draft was due last Friday) but I've not gotten it all working yet. I'll try to wrap this up early next year and publish my findings.   Android's easy, but there's something weird about the iOS build that we haven't figured out yet. Stay tuned.

**Comment by JoshuaHintze** [comment]
@jwargo would love an update on Cordova build!

**Comment by jwargo** [comment]
@GimpMaster I've not been able to get Build working for Cordova iOS.  I applied the same approach as I did with Android, but ran into some issues with build settings and wasn't able to actually get an executable out of the build process. Basically I'm not an experienced iOS developer, so I just couldn't get past the issues.

**Comment by JoshuaHintze** [comment]
Hey John, Is there anything I can do to help? We have a team of pretty experienced Cordova IOS app developers.

I'm assuming this git-repo here:  https://github.com/microsoft/appcenter-sdk-cordova

Only does the 3 things it mentions: Analytics, Crashes, Push Notifications ?

**Comment by jwargo** [comment]
@GimpMaster good question.  If you want to help me figure this out (Build for Cordova iOS), we can write a blog post about it. Here's my repo for Android, works great (as far as I can tell). Here's the one for iOS, I just don't know iOS build settings well enough to get very far with it.

Yes, that's the SDK and it only supports those features. Industry support for Cordova is waning (as much as it saddens me), so that's as far as we've gone.

**Comment by JoshuaHintze** [comment]
Hey John. I didn't see those links from you for your repos. Did they get stripped out from your post?

Would love to see the blog post about it.  Either way happy to help.

**Comment by jwargo** [comment]
@GimpMaster yeah, apparently they did. Weird. trying again: [Android Repo - Cordova-Build-Android](https://github.com/jwargo/Cordova-Build-Android), [iOS Repo - Cordova-Build-iOS](https://github.com/jwargo/Cordova-Build-iOS). If they get stripped out again, email me or look in my public repos, they're there.
