### ISSUE TITLE
AppCenter Distribution Groups automatic distribution behavior

### ISSUE THREAD

**Issue by Thomas0c** [MicrosoftDocs/appcenter-docs#389]
Hi there. I'm a migrating HockeyApp user and there is a feature which I'm missing. For Distribution Groups in AppCenter it seems that only `Collaborators` get pushed a new release automatically whereas for other distribution groups associated with the same app you have to manually release a new build using the UI.

In HockeyApp apps would automatically distribute to to users and distribution groups associated with an app - and I'm wondering if that's intentionally not in AppCenter, or?

Thanks in avance.

**Comment by jwargo** [comment]
@Thomas0c thanks for reaching out. The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, or have a question about a hockeyApp feature, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
