### ISSUE TITLE
Sandbox or Production?

### ISSUE THREAD

**Issue by K232** [MicrosoftDocs/appcenter-docs#39]
I don't understand the radio buttons regarding Sandbox or Production, and unfortunately the docs do not give any further information. AppCenter says:
"Use Sandbox for initial development and Production for production version of the application. The environment should match the development certificate that you've used to build the application."

So first I selected Sandbox. I made some tests and everything worked fine with my single iOS test device. Now I published my app with Testflight, so it's not available in Apples AppStore yet, only for BetaTesters. Testing push on iOS now shows error messages "Bad channel". Maybe that's because I still have sandbox configuration?

I removed the configuration from AppCenter and created the exact same configuration (using the same key from Apples Key Service). The only difference: I now selected Production instead of Sandbox. Is that correct? I experience some problems now because push notifications are not delivered, it says 0 of 0 sent...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6415607-5d22-0249-2537-1d7887b46f16
* Version Independent ID: 32fafbc0-515e-043f-3481-6f7c3fe2cc91
* [Content](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-ios.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@k232 The comments feature of the docs is designed to enable customers to suggest changes to the docs or ask clarifying questions about the docs. If you need help with the product, please login to the App Center dashboard and click the blue chat button in the lower-right corner of the page. Our dedicated support resources will answer any questions you have there.

**Comment by K232** [comment]
Yes, that's why I asked in the documentation. I expected some help there, but actually it contains even less information than the product itself 😟

**Comment by jwargo** [comment]
@K232 I understand, I just wanted to make sure you knew that this isn't a support forum. Use the support system we've implemented in App Center and let us know what could be more clear in the docs.

**Comment by K232** [comment]
Ok, now I'm lost.... I thought this github issue tracker should be used in case of missing details in the documentation...😳

**Comment by jwargo** [comment]
It is, but it's not a support forum. It feels like you need help, so that's why I'm suggesting you go to the right place to get the help you need. Once you're up and working, if you want to make suggestions on how to update the docs, this is the place to be. 

Do you have suggestions you want to make on the docs?

**Comment by K232** [comment]
Sure. What is the meaning of "Sandbox" and "Production"? And could I use the same apple key for both?

**Comment by MehrdadMzfr** [comment]
@K232 hi, Sandbox and Production are iOS concepts, they are used to separate development and prod apps.
based on the cert you used to build the app, you need to choose the environment.
Sandbox is for Development Certs
Production is for Adoc or App store distribution. For test flight apps, you need to build it using prod certs. 

Re Auth Key, correct, you can use one key for both environments.

Please remember that your apps need to re-register with push once you change environment. for that you can re-install the app. I would suggest to create separate App Center apps for each environment.

**Comment by jacob-israel-turner** [comment]
Hey guys!  Kind of want to piggy back this thread since it's gotten a little traffic.

It would be nice if we could configure both a sandbox and production environment for the push notifications, so that I don't have to choose whether I want to send notifications to a local device for development or a device in TestFlight/production.  I'd rather be able to switch between the environments, similar to how I can switch between environments in the CodePush tab.

If there's a better place for me to submit this feedback, please let me know.

**Comment by jwargo** [comment]
@jacob-israel-turner we opened up a GitHub repo to publish our roadmap and gather feedback - the best place to give feedback is https://github.com/Microsoft/appcenter
