### ISSUE TITLE
Android build generated by App center gives an error: "Unable to load script from assets 'index.android.bundle'."

### ISSUE THREAD

**Issue by amoljain** [MicrosoftDocs/appcenter-docs#390]
I created a build but it insta-crashes on device with an error: "Unable to load script from assets 'index.android.bundle'."

When I look at build logs, it looks like an 'index.android.bundle' was indeed generated but for some reason the app cant seem to find it. 

I had to locally create a bundle by running: `react-native bundle --platform android --dev false --entry-file index.js   --bundle-output android/app/src/main/assets/index.android.bundle   --assets-dest android/app/src/main/res/` and then push it to my branch to make the build work. 

Am I missing a step? Should the documentation include steps on how to generate this bundle? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc47bc0e-c9ca-d7cb-5e19-544bc0433e0d
* Version Independent ID: 4f249ef5-6c58-e7a7-bce8-10ded2430d9d
* Content: [Configure a React Native Android build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/react-native/android/index)
* Content Source: [docs/build/react-native/Android/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/react-native/Android/index.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@amoljain I'm not sure. The best option for you is to ask our support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by antbui** [comment]
Hi @amoljain 
I am facing the same issue with you. Without 'index.android.bundle' on branch, the app can not start although appcenter built successfully.
In case, we put this file to branch, in the next build time, if we don't re-bundle, the app can't load new change.
Do you have any idea to overcome this issue?
Thanks in advance.

**Comment by jwargo** [comment]
@antbui please see my previous comment - the best place to get support is not the docs, please contact our dedicated support team.
