### ISSUE TITLE
App bundle support

### ISSUE THREAD

**Issue by pjkarels** [MicrosoftDocs/appcenter-docs#392]
Are there any plans to utilize the open sourced 'bundletool' that Google has provided to support building App Bundles?

**Comment by jwargo** [comment]
@pjkarels The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, or have a roadmap question, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
