### ISSUE TITLE
Push Notification not working on production App but working on developing model App

### ISSUE THREAD

**Issue by mowen0303** [MicrosoftDocs/appcenter-docs#393]
When I use `react-native run-android` on my device , the push notification is working, the device can receive pushed message.

But, 

When I use `./gradlew installRelease` to install a release app, can't receive push notification. (The push notification status on app center is success) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21783434-15c7-bd2a-2238-408d9a8497bb
* Version Independent ID: 4479f5df-259e-5f4e-8484-a587e3bb84be
* Content: [App Center Push for Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/android)
* Content Source: [docs/sdk/push/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@mowen0303 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
