### ISSUE TITLE
the best

### ISSUE THREAD

**Issue by technololy** [MicrosoftDocs/appcenter-docs#394]
deeply simple.............you guys save the world

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@technololy Thanks!
