### ISSUE TITLE
Build scripts not detected

### ISSUE THREAD

**Issue by shahthepro** [MicrosoftDocs/appcenter-docs#395]
I added a post-clone [build script to my repository](https://github.com/shahthepro/binault/commit/68b1b8572dc85cf465c66dcc6ae1fcc84076b3a8).

However, app center cannot detect the build script. It shows "None".

![screenshot_2018-12-23 build configuration binault app center](https://user-images.githubusercontent.com/10547529/50381328-44ccf300-06aa-11e9-8217-d029c04df8b4.png)

I have tried deleting the app on AppCenter and creating a new one. Still it is not detected.

**Comment by jwargo** [comment]
@shahthepro The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
