### ISSUE TITLE
How to use Api 'getTransmissionTarget ' ? 

### ISSUE THREAD

**Issue by Damoness** [MicrosoftDocs/appcenter-docs#396]
I can't find any information .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a7f669-58a0-6700-13c5-e8f9c647943c
* Version Independent ID: eec16d36-776d-3438-ed39-ad8e98ff2c08
* Content: [App Center Analytics for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/react-native)
* Content Source: [docs/sdk/analytics/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by jwargo** [comment]
@Damoness OK, i'll have the PM take a look at a potential doc update. In the mean time App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by dhei** [comment]
Hi @Damoness, App Center RN SDK actually provides a set of private APIs for Microsoft internal users only. `getTransmissionTarget` is one of such APIs only for internal users, that's why it's not documented publicly. Sorry for the confusion.
