### ISSUE TITLE
Page not found when navigate from Microsoft blogs

### ISSUE THREAD

**Issue by truongkhanhduy95** [MicrosoftDocs/appcenter-docs#397]
URL: https://blogs.msdn.microsoft.com/vsappcenter/mobile_cicd_101/
When clicked on the link: docs.microsoft.com/en-us/appcenter/build/custom/variables, the extra dot make it 404

![capture](https://user-images.githubusercontent.com/17457150/50390510-7907e880-076a-11e9-83ff-d4cb10e29660.PNG)

**Comment by jwargo** [comment]
@truongkhanhduy95 Thanks. I'll have someone take a look.
