### ISSUE TITLE
please add a note about ApplicationAttribute Debuggable

### ISSUE THREAD

**Issue by wizzard0** [MicrosoftDocs/appcenter-docs#399]
on Android, SDK detects debug/release by reading android:debuggable from app manifest;
and this is set to TRUE by default even in release appcenter builds

Please add a note that one needs to include `[assembly: Application(Debuggable=false)]`, it would've saved us a couple of days debugging if it was documented.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d269a0-0b09-c2f6-d37a-319831bcf782
* Version Independent ID: f2c17a3a-87bb-0c75-9efb-de6ffb6f7738
* Content: [App Center Distribute for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin)
* Content Source: [docs/sdk/distribute/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @TroubleMakerBen
* Microsoft Alias: **bereimol**

**Comment by wizzard0** [comment]
(debuggable:false is required for in-app updates to work)

**Comment by jwargo** [comment]
@wizzard0 I'll have the PM take a look.

**Comment by jaeklim** [comment]
@wizzard0 Thanks for the info and apologize for any inconvenience. I filed a bug for this one, we will review the step that you mentioned is required or investigate if it is caused by something else.

**Comment by guperrot** [comment]
In Xamarin builds it's false in debug and true in release, including in App Center builds. It does require more investigation why this specific application does not behave the standard way.

**Comment by guperrot** [comment]
Hi @wizzard0, normally if you build in release mode (including in AppCenter build), the application does not end up having debuggable=true by default. The default is false for release builds and we have tested with apps of our own.

Do you have any kind of customization in your app that would have switched this flag incorrectly to true? Like in the xml manifest or another file.

**Comment by jwargo** [comment]
@wizzard0 it feels like you've bumped into something more than a simple doc update, Do you have a response to the question from @guperrot?  Perhaps we should move this to the support queue - please log into App Center and click the blue chat button and start a discussion there.

**Comment by wizzard0** [comment]
Hmm, interesting. It certainly stays debuggable=true in release.

Currently we don't have time to try and minimize the reproduction steps, but I've noted this isn't an intended behavior in our bug tracking system, and if it will resurface with a smaller project then I'll post the details here.

Thanks for the updates!

**Comment by guperrot** [comment]
If you really have debuggable=true for release builds, you would not be able to submit the application to Play Store, it would be a serious bug in the Xamarin build system, for now I still think this specific project has something odd that make it switch to true somehow. Will wait for your answer if you find anything.
