### ISSUE TITLE
Additional Information limits

### ISSUE THREAD

**Issue by charabaruk** [MicrosoftDocs/appcenter-docs#40]
Does `TrackError()` have the same limits on the `properties` argument as `Analytics.TrackEvent()` -- that is, maximum five values, with a 64-character limit on each?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf40a33-9822-a710-501b-afb68625a0f5
* Version Independent ID: 648bf340-6093-7a7e-9662-5124df8c9206
* [Content](https://docs.microsoft.com/en-ca/appcenter/errors/)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs-pr/blob/live/docs/errors/index.md)
* Service: vs-appcenter

**Comment by blparr** [comment]
Hi there, that is correct. The limits in error properties are the same as the limits in event properties.

**Comment by jwargo** [comment]
@blparr close the issue?

**Comment by charabaruk** [comment]
Shouldn't this information be added to the doc, though?

**Comment by blparr** [comment]
Definitely agree @coldacid , I will add that information.

**Comment by olived84** [comment]
I am using that TrackError method but I am not able to find any report on the appCenter site. But when application totally crash... I see the exceptions... What am I missing

**Comment by phlashdev** [comment]
Same here, I cannot see them anywhere...
As what I've seen under "Errors->Feature Set", the AppCenter UI module will show an entry for handled errors. But this is not showing up for me at the moment.

**Comment by jwargo** [comment]
@blparr can you please address the new questions?

**Comment by blparr** [comment]
Hi @olived84 and @Phlash1989 , handled errors in currently in preview behind a feature flag. You need to request access to the feature so we can enable it for you. Can you please, contact us via our support system (blue button on the app center portal) with the accounts where you would like this feature to be enabled on?

Thanks!

**Comment by mxstudios** [comment]
Why do the docs say that it handles up to 20 values of 125 characters each?

**Comment by blparr** [comment]
@mxstudios That is indeed the case. We increased the limits to 20/125 few months back. What's your concern and how can we help? Thanks

**Comment by mxstudios** [comment]
The previous comment said it only allowed 5, which seemed to be the case for me. But when I updated to a later package on a hunch it allowed the 20.  I didn’t realize it was updated in a later build since I was getting only the 5 and this thread or docs didn’t mention it was only available in later build. 

Thanks!

**Comment by blparr** [comment]
@mxstudios You can see the update in our Changelog: https://docs.microsoft.com/en-us/appcenter/general/changelog. You will find this update on April 25th.
