### ISSUE TITLE
assembleDebugAndroidTest

### ISSUE THREAD

**Issue by IgorGanapolsky** [MicrosoftDocs/appcenter-docs#403]
I get an error:
&gt; Task 'assembleDebugAndroidTest' not found in root project 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28fe6afc-06ad-8465-f29a-04b2a118a378
* Version Independent ID: 73b3398b-23b8-230d-d296-8900e053096a
* Content: [Preparing Espresso Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/espresso)
* Content Source: [docs/test-cloud/preparing-for-upload/espresso.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/espresso.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@IgorGanapolsky The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by IgorGanapolsky** [comment]
My comment was about the incorrect command in the doc!  Makes sense???

**Comment by jwargo** [comment]
@IgorGanapolsky no, not really, sorry. All you did was report that you're getting an error, which is why I suggested you contact support. Can you please provide some additional information?

**Comment by IgorGanapolsky** [comment]
Dude, read the linked doc above: 
> Content: Preparing Espresso Tests for Upload - Visual Studio App Center

Now, the command in that doc is causing the error on my end.
