### ISSUE TITLE
Support for Bitbucket Server

### ISSUE THREAD

**Issue by tomisaacson** [MicrosoftDocs/appcenter-docs#404]
I got to this page from https://appcenter.ms/users/tom-isaacson-bkm5/apps/Link-iOS/build/connect/bitbucket where it said "We’re working on adding support for other code hosts." but there doesn't seem to be anything on the roadmap. When might you add support for Bitbucket Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfeef07-e3eb-9804-5c27-7ac3ec73d768
* Version Independent ID: d7c03ef1-1f84-e1f5-5913-ffad45d9efe1
* Content: [App Center Product Roadmap - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/roadmap)
* Content Source: [docs/general/roadmap.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/roadmap.md)
* Service: **vs-appcenter**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@tomisaacson I've asked the PM to respond.

**Comment by nilofer** [comment]
Hi @tomisaacson, support for on-premise Bitbucket Server is not on our public short-term roadmap, and we don't have an ETA to share at the current time.
