### ISSUE TITLE
AppCenter Post Test / Distribute Script

### ISSUE THREAD

**Issue by mikekpl** [MicrosoftDocs/appcenter-docs#405]
This is more of a feature request than an issue. It will be more beneficial if we could have post-test script / post-distribute script much like of post-build scripts.

**Comment by jwargo** [comment]
@mike14u OK, thanks. I'll pass this on to the PM team. Just so you know, a more direct way to provide product/roadmap feedback is through the blue chat button in the lower-right corner of any App Center page. That connects you directly to our dedicated support team and our PMs, so they're happy to take any feedback there.
