### ISSUE TITLE
Build scripts in Android not being detected

### ISSUE THREAD

**Issue by kuyazee** [MicrosoftDocs/appcenter-docs#406]
According to the [documentation](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/), I should add the build script in the project level file. 

> Place the scripts with the respective format next to the project-level (.xcodeproj, build.gradle, .csproj, .sln or package.json) file that you've selected in the build configuration and we will run them as custom build steps.

As you can see on the image below there are two build.gradle's.

<img width="200" alt="screen shot 2019-01-04 at 5 29 27 pm" src="https://user-images.githubusercontent.com/17846698/50681460-882e4680-1046-11e9-9a05-ccdba94a0b97.png">

Since there are two build.gradle's I placed the build script on the project level, which is the root directory of the project. However the actual location where I have to place the buildscript is in `<root directory>/app`, the module level build.gradle, in order for the script to be detected.

**Comment by jwargo** [comment]
@kuyazee thanks, I'll have the PM take a look at doing an update to the docs.

**Comment by nilofer** [comment]
Thanks for noticing this @kuyazee. We're fixing this in the docs.
