### ISSUE TITLE
Windows Store support is missing

### ISSUE THREAD

**Issue by jjindrich** [MicrosoftDocs/appcenter-docs#407]
Hi, please could you add comments about Windows Store (public) ? When it will be supported ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee37f80-6f73-b27c-de32-bee9f66e1484
* Version Independent ID: 20201175-3afa-dd1f-bd9e-59f84b5ba8ca
* Content: [Publish to consumer and enterprise stores - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/)
* Content Source: [docs/distribution/stores/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/index.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by jwargo** [comment]
@jjindrich I've asked the PM to respond.

**Comment by Oddj0b** [comment]
Short answer, not any time soon as we are focusing our effort into creating a compelling solution for HockeyApp customers.

I have noted it as a feature request.

**Comment by SunjayKalsi** [comment]
Any time frame on publishing to Windows Store support? I feel this is important as HockeyApp is being retired later on this year

**Comment by jwargo** [comment]
@SunjayKalsi we started publishing our current roadmap here: https://github.com/Microsoft/appcenter/issues. You also have the ability to request features on that repo and highly voted features make it into our roadmap.

**Comment by jjindrich** [comment]
Submitted new fr https://github.com/microsoft/appcenter/issues/1827
