### ISSUE TITLE
App Center - add to C++ app built as a Windows Application Packaging Project?

### ISSUE THREAD

**Issue by sseyod** [MicrosoftDocs/appcenter-docs#408]
[Enter feedback here]

How do I add support for App Center diagnostics / crash reporting to C++ apps for the Windows Store?

The style of C++ app in question, are Windows apps using "Windows Application Packaging Projects" to deliver them through the Windows Store. See https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net for info on this, if that helps explain things.

So far as I can see, it is not yet possible to add App Center diagnostics / SDK support to C++ apps written in this way to Visual Studio, which is a *real* shame.

Thanks in advance...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5756765e-fef2-e8d9-f8d9-5c01690095b8
* Version Independent ID: b474e30a-6e59-97fc-476a-92be5ec3a01a
* Content: [App Center Crashes for UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp)
* Content Source: [docs/sdk/crashes/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by jwargo** [comment]
@sseyod App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jozefizso** [comment]
@jwargo your answer does not address OP issues at all.

When will C++ SDK exist for AppCenter?

**Comment by jwargo** [comment]
@jozefizso as I tried to make clear, this is not the place to ask product or product support questions.  As I explained in my previous answer, we have a dedicated support team available through that blue chat button in the lower-right corner of every App Center portal page. If you have questions about the availability of a feature, ask there - not here in the docs. If you want to request a feature, you can easily do so here: https://github.com/Microsoft/appcenter.

Voting down and complaining about my previous answer isn't going to get you a different response. All you need to do is follow the instructions I've provided and you will get the answer you seek.
