### ISSUE TITLE
WinForms and WPF Support

### ISSUE THREAD

**Issue by StefanKoell** [MicrosoftDocs/appcenter-docs#409]
WinForms github issue has been closed.
WPF github issue is open but no confirmation yet.

We desperately need support for WinForms and WPF apps - at least for the analytics part. How hard can this be. The WinForms code base I got from MS was a private build and nobody cared to publish the source (Open Source?!). Now the code seems to be lost (according to MS). Really?! You can support macOS but not WinForms / WPF?!

Please, please, please!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfeef07-e3eb-9804-5c27-7ac3ec73d768
* Version Independent ID: d7c03ef1-1f84-e1f5-5913-ffad45d9efe1
* Content: [App Center Product Roadmap - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/roadmap)
* Content Source: [docs/general/roadmap.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/roadmap.md)
* Service: **vs-appcenter**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@StefanKoell thanks for the feedback. The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, or when you have feedback on the roadmap, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
