### ISSUE TITLE
Screen Presentation Automatically?

### ISSUE THREAD

**Issue by dylanshine** [MicrosoftDocs/appcenter-docs#410]
Does App Center track view controller presentation automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea43ae40-337d-83b4-8129-85ff1a8c6ede
* Version Independent ID: d37ccc38-a4bc-5368-9b58-8720995f8bc2
* Content: [App Center Analytics for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/ios)
* Content Source: [docs/sdk/analytics/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@dylanshine The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
