### ISSUE TITLE
Is Xcode project needed?

### ISSUE THREAD

**Issue by hlynnerup** [MicrosoftDocs/appcenter-docs#411]
Thank you for the description, even though I haven't had success yet sending push notifications to IOS devices…
I have a couple of questions to the above and Xamarin.IOS develoment in Visual Studio (Windows), that I hope you can help me with!
1. Do I have to create a project/app on the Mac - I would like to use the Mac as "slave" computer - ssh connected.

2. Creating an Xamarin.IOS app from scratch (step by step - regarding the IOS/entitlement, etc.), what to configure in VS, Mac, Appcenter and Apple developer center (certificates, Keys, Identifiers, Devices, Provisioning Profiles). I haven't been able to find info - every doc I find assumes that the app is already there.

So far I have completed to create a push app for IOS, the app, when installed and launched on the device, ask for permission to send messages, but when I send messages from appcenter, nothing shows up on the iPhone (it's working when I test on my Android device).

TIA!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6415607-5d22-0249-2537-1d7887b46f16
* Version Independent ID: 32fafbc0-515e-043f-3481-6f7c3fe2cc91
* Content: [App Center Push for Xamarin.iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios)
* Content Source: [docs/sdk/push/xamarin-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@hlynnerup The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
