### ISSUE TITLE
Offline Sync support

### ISSUE THREAD

**Issue by vikram-v** [MicrosoftDocs/appcenter-docs#412]
Does this SDK supports offline sync for sending Custom events ? Say we want to capture some custom events when there is no network and send to Appcenter when the mobile app connects back to internet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae82f3e9-78b4-e743-1d4a-58dee115de10
* Version Independent ID: 50a18a62-58db-10eb-65d6-b0614d0553fc
* Content: [App Center Analytics for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/xamarin)
* Content Source: [docs/sdk/analytics/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @TroubleMakerBen
* Microsoft Alias: **bereimol**

**Comment by jwargo** [comment]
@vikram-v I'm assuming it caches data and uploads when it can, but I'm not certain. I'll ask the PM to respond. Don't forget that App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by blparr** [comment]
Hello! Yes, if the app is offline, the SDK will store up to 300 logs in storage. Once the network connectivity is restored, the SDK will send these logs to the App Center backend.
You can find this info in the Analytics FAQ as well: https://docs.microsoft.com/en-us/appcenter/analytics/faq
