### ISSUE TITLE
App Center is misspelled. 

### ISSUE THREAD

**Issue by TheWildUnicorn** [MicrosoftDocs/appcenter-docs#413]
In the "Testing iOS Apps" section, under the "Installing an app" heading, App Center is misspelled. The sentence reads, "When you click on an app, Ap Center displays additional information about the app." It should read, "When you click on an app, App Center displays additional information about the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811f9eee-5b17-06e1-c108-dbef47984425
* Version Independent ID: 8fe50e13-c934-6a43-bf7d-1f33946da9d3
* Content: [Testing iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios)
* Content Source: [docs/distribution/testers/testing-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@TheWildUnicorn thanks, I fixed it.
