### ISSUE TITLE
Carthage Binary Rate Limit

### ISSUE THREAD

**Issue by WarSunsOfPeace** [MicrosoftDocs/appcenter-docs#414]
I currently use the aws sdk in an ios app, this library is added through Carthage.  When Carthage is run it skips the binary because of an API rate limit.  When i run this locally it has no problems downloading the file.   The problem is building the aws-sdk from source takes too long and times out the build.  Is there a way to use our git hub credentials in the carthage dependency downloads?

*** Skipped downloading aws-sdk-ios.framework binary due to the error:
	"API rate limit exceeded for <IP ADDRESS>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

**Comment by jwargo** [comment]
@w0mba7 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
