### ISSUE TITLE
Missing Info for iOS (React Native)

### ISSUE THREAD

**Issue by jdnichollsc** [MicrosoftDocs/appcenter-docs#415]
Hi guys, I can't see the JS code required to implement "Common tasks for push notifications". What're the callbacks to use from the react native part?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb94e7c4-0cce-e560-e548-5e0a930a4f75
* Version Independent ID: 5cc41638-30ea-62d5-de78-cb7a69c3aec2
* Content: [App Center Push for React Native iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-ios)
* Content Source: [docs/sdk/push/react-native-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/react-native-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@jdnichollsc I'll have the team respond.

**Comment by iamclement** [comment]
Hi @jdnichollsc, these callbacks are not accessible from JS directly you need to touch your native iOS apps to get to them. They are used for scenarios like _a notification is received in foreground_ or _a notification is tapped by the user_. The App Center JS callback `onPushNotificationReceived` cannot be used to detect those scenarios reliably. `onPushNotificationReceived` is still called but it doesn't tell if it was triggered because of a notification received or by a tap on the notification.

Let me know if that answers your question.

**Comment by jdnichollsc** [comment]
@clpolet thanks for your response, but can you add any example to notify these scenarios to the JS code of the app? On the other hand, I don't know what happen in our app but the `onPushNotificationReceived` is not executed from iOS, only works for Android :/

**Comment by iamclement** [comment]
So there is no JS code for the scenario we are talking about. I also responded to [this other GH issue](https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/505) on the SDK repo :). Let's focus on the SDK issue first there might be some learning there.

**Comment by jdnichollsc** [comment]
I shared our example from the AC portal, you can use that to improve the documentation about the JS side 👍

**Comment by iamclement** [comment]
@jdnichollsc thanks for your input we'll take it from here.

**Comment by clive107** [comment]
Hi all, does appcenter push able to handle push notification when react native iOS app is not running?

**Comment by jdnichollsc** [comment]
@clive107 yes Sir, from my experience :)

**Comment by jwargo** [comment]
@clive107 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. when you have questions, just ask our support team. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by abdallaemadeldin** [comment]
@jwargo @clpolet @clive107 @elamalani 
how to pass the a flag when notification clicked to js?

**Comment by ilyashumihin** [comment]
Hi, @abdallaemadeldin!
Thanks for getting in touch.

As stated in [this section](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-ios#intercept-push-notifications) you can set up a listener to be notified whenever a push notification is received has been tapped by the user. Also you can set up [custom data](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-ios#custom-data-in-your-notifications) and read it when you receive a notification.
