### ISSUE TITLE
iOS Device Debug

### ISSUE THREAD

**Issue by thedevdavid** [MicrosoftDocs/appcenter-docs#416]
The code should be

```
    #ifdef DEBUG
        jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
    #else
        jsCodeLocation = [CodePush bundleURL];
    #endif
```

Because localhost is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39490e39-be97-2bba-5afc-6bc8bed39690
* Version Independent ID: 357a2070-e41c-b346-e18b-606eec7255c2
* Content: [Using the React Native SDK with CodePush - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#multi-deployment-testing)
* Content Source: [docs/distribution/codepush/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@DLevai94 thanks, we'll take a look.

**Comment by botatoes** [comment]
@DLevai94 We're having our codepush team doing a verification and will add it to the docs. Thanks! :)

**Comment by alexandergoncharov-zz** [comment]
Hi @DLevai94 ,

That's good catch! Thanks! I've updated MS docs and Github docs.
Please feel free to reopen this issue if you have any questions.

Thanks,
Alexander
