### ISSUE TITLE
Codepush iOS Debug Device

### ISSUE THREAD

**Issue by thedevdavid** [MicrosoftDocs/appcenter-docs#417]
On real device the localhost isn't working. The code needs to be:

```
    #ifdef DEBUG
        jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
    #else
        jsCodeLocation = [CodePush bundleURL];
    #endif
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39490e39-be97-2bba-5afc-6bc8bed39690
* Version Independent ID: 357a2070-e41c-b346-e18b-606eec7255c2
* Content: [Using the React Native SDK with CodePush - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#multi-deployment-testing)
* Content Source: [docs/distribution/codepush/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@DLevai94 thanks, we'll take a look.

**Comment by botatoes** [comment]
Closing this as this is a duplicate.
