### ISSUE TITLE
Reference to iOS App

### ISSUE THREAD

**Issue by TheWildUnicorn** [MicrosoftDocs/appcenter-docs#418]
Hi there, 

In the "Installing an app" section of this document, in the first paragraph, there is a reference to a native mobile app. After contacting your team, I was told that there currently is no app for iOS that allows a developer to distribute a build to a tester via App Center. Can the documentation here be clarified? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811f9eee-5b17-06e1-c108-dbef47984425
* Version Independent ID: 8fe50e13-c934-6a43-bf7d-1f33946da9d3
* Content: [Testing iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios)
* Content Source: [docs/distribution/testers/testing-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@TheWildUnicorn you're right - Android only. I'll make the change.
