### ISSUE TITLE
The CALEBE TRUE

### ISSUE THREAD

**Issue by cristianomarquesadmo1** [MicrosoftDocs/appcenter-docs#419]
Versio 1.1.2 of CALEBE TRUE
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64bf6eee-8421-34eb-a50e-78132fa8d45f
* Version Independent ID: 99cb3da9-7d74-8648-a438-de3849bd6a2c
* Content: [Unity SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/unity)
* Content Source: [docs/sdk/troubleshooting/unity.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/unity.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by jwargo** [comment]
@cristianomarquesadmo1 i don't understand what you're asking for or suggesting here. Can you please explain?

The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by maestersid** [comment]
Not sure what the feedback actually is. Please re-open to clarify if needed.
