### ISSUE TITLE
v1.4.0 Release Notes?

### ISSUE THREAD

**Issue by phileo** [MicrosoftDocs/appcenter-docs#42]
Where can I find release notes for AppCenter SDK v1.4.0 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62690a4a-94f3-21cb-a674-d297e557ca62
* Version Independent ID: 3adaeac7-e034-5b5b-19c5-1c0151a7264c
* [Content](https://docs.microsoft.com/en-us/appcenter/general/changelog)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/changelog.md)
* Service: vs-appcenter

**Comment by elamalani** [comment]
@phileo Our release notes are documented here:
https://github.com/Microsoft/AppCenter-SDK-DotNet/releases/tag/1.4.0
