### ISSUE TITLE
3.7 NuGet Restore broken link

### ISSUE THREAD

**Issue by brodymerritt** [MicrosoftDocs/appcenter-docs#420]
The link for environment variables in this section redirects to Build Scripts instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf851143-9dbb-f208-f804-659694927d5b
* Version Independent ID: 8483c311-3184-2271-f6bb-d6bcfd682050
* Content: [Building Xamarin apps for Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/xamarin/android/#37-nuget-restore)
* Content Source: [docs/build/xamarin/android/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/xamarin/android/index.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@broderickmerritt thanks. Fixed.
