### ISSUE TITLE
Get all registered devices and their custom properties

### ISSUE THREAD

**Issue by AutumnEvans418** [MicrosoftDocs/appcenter-docs#422]
I want to be able to get all registered devices and their custom properties.  This way I can send notifications to particular devices based on their custom property.  An audience will not work because it depends on the data in the notification.  Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb96601-f906-374d-b0d8-537e5f80de3e
* Version Independent ID: b66d21ae-1205-3d76-f577-d58891382c08
* Content: [App Center Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/pushapi#send-notifications-via-api)
* Content Source: [docs/push/pushapi.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/pushapi.md)
* Service: **vs-appcenter**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by jwargo** [comment]
@chrisevans9629 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by AbdurrahmanSefer** [comment]
Are you find the way?

**Comment by jwargo** [comment]
@AbdalrhmanAlsafr You can export the device data using the export API: https://openapi.appcenter.ms/#/push/Push_ExportDevices then use that data on your backend to send notifications,

**Comment by AutumnEvans418** [comment]
@AbdalrhmanAlsafr the suggestion @jwargo provided is what we are currently doing.  we match the device id with a username and use that to send to their devices.
