### ISSUE TITLE
How to send a silent push notification?

### ISSUE THREAD

**Issue by VahidShir** [MicrosoftDocs/appcenter-docs#423]
How can we send **_silent_** push notifications in Android? By "silent" I mean a notification that doesn't show up in notification bar, so that user doesn't notice it.

I saw this [StackOverFlow ](https://stackoverflow.com/questions/49155493/how-can-i-send-a-silent-notifications-using-app-center-push-service)link but it seems it's not yet supported. So I wanna know if it's so, when the silent push notifications will be supported for Android?

**Comment by jwargo** [comment]
@VahidShir The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
