### ISSUE TITLE
System.getenv() instead of System.getProperty()

### ISSUE THREAD

**Issue by mikeroneer** [MicrosoftDocs/appcenter-docs#424]
The code example does not work that way. As far as I know, `System.getProperty()` gets a Java property. Since we wanna get an environment variable there, `System.getenv()` should be used.

**Comment by jwargo** [comment]
@mikeroneer Can you please provide me with some more detail? Which code example? I don't know which document you are referring to.

**Comment by mikeroneer** [comment]
@jwargo The one in point 3 "Storing Signing Details in the Repository with Environment Variables" (https://docs.microsoft.com/en-us/appcenter/build/android/code-signing)

**Comment by matthiaswenz** [comment]
That is correct, thanks for bringing this up!

**Comment by SebastienMelki** [comment]
Just wanted to point out that this was closed a year ago yet the docs are still wrong on https://docs.microsoft.com/en-us/appcenter/build/android/code-signing  .. had to find this issue to fix my issue :(

**Comment by jwargo** [comment]
@SebastienMelki we made a doc update based on the feedback, what's still wrong with the docs?

@ranterle and @nrajpurkar can one of you please take a look at this?

**Comment by SebastienMelki** [comment]
> @SebastienMelki we made a doc update based on the feedback, what's still wrong with the docs?
> 
> @ranterle and @nrajpurkar can one of you please take a look at this?

Hey thanks for replying. Well I was getting nowhere with System.getProperty in section C of https://docs.microsoft.com/en-us/appcenter/build/android/code-signing and then I saw this issue to use environment variables instead (System.getenv) and it worked like a charm. But the docs still show System.getProperty, I might be missing something else? 
<img width="958" alt="Screen Shot 2020-01-08 at 7 03 38 PM" src="https://user-images.githubusercontent.com/5787993/71999402-002ae000-324a-11ea-8da4-c7d323305b94.png">
