### ISSUE TITLE
Session and Device Information incomplete

### ISSUE THREAD

**Issue by randallhelms** [MicrosoftDocs/appcenter-docs#425]
The Session and Device Information section is frustratingly incomplete:

'Once you add App Center Analytics to your app and start the SDK, it will automatically track sessions and device properties like OS Version, model, etc. without writing any additional code.' 

Why wouldn't you provide a list of exactly which properties are automatically captured, or at least a link to such a list? This is a big omission.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5244cedd-4e07-c533-d474-83839cb0f7d2
* Version Independent ID: e86872c7-de1b-9f16-6b44-ba44bea1ae04
* Content: [App Center Analytics for Android - Visual Studio App Center](https://docs.microsoft.com/en-gb/appcenter/sdk/analytics/android)
* Content Source: [docs/sdk/analytics/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@randallhelms I'll pass the feedback on to the PM. I imagine what happened is we just assumed you'd follow the steps and add Analytics to an app. Once you do that, you'll see everything we capture in the dashboard. Is having the list of metrics going to change your interest in using the service? We capture the core stuff you'd want to be able to categorize devices running your application.

**Comment by jwargo** [comment]
@randallhelms I spoke with the PM and she said she's going to do an update. I'm going to close this issue. Please reopen if you want to add anything to it
