### ISSUE TITLE
Missing informations if using Cocoapods

### ISSUE THREAD

**Issue by Under-Warz** [MicrosoftDocs/appcenter-docs#43]
Hi guys,

It could be great if you edit this part https://docs.microsoft.com/fr-fr/appcenter/distribution/codepush/react-native#multi-deployment-testing for users using Cocoapods about the modification of `Per-configuration Build Products Path`

For Cocoapods users like me, I also have to edit the PODS_CONFIGURATION_BUILD_DIR in my project's targets to get third part libraries work with the new staging configuration. And before building staging env, we have to build Release env first because Staging env libraries might depend of Release's files.

Best regards,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 39490e39-be97-2bba-5afc-6bc8bed39690
* Version Independent ID: 357a2070-e41c-b346-e18b-606eec7255c2
* [Content](https://docs.microsoft.com/fr-fr/appcenter/distribution/codepush/react-native#multi-deployment-testing)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs-pr/blob/live/docs/distribution/codepush/react-native.md)
* Service: vs-appcenter

**Comment by Zakeelm** [comment]
Hey there! 

Thanks for the suggestion, i'm currently investigating how I can improve the documentation for this. Can you elaborate on how you had to edit the PODS_CONFIGURATION_BUILD_DIR? I would like to know the steps a cocoapods user should take to get third party libraries to work.

**Comment by Under-Warz** [comment]
Hi @Zakeelm, well if I let the default `PODS_CONFIGURATION_BUILD_DIR` for the new environment `Staging` it doesn't work. I needed to change the configuration for `Staging` in `PODS_CONFIGURATION_BUILD_DIR` using the same variable as `Release` : `${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)`
<img width="513" alt="capture d ecran 2018-03-20 a 11 40 18" src="https://user-images.githubusercontent.com/1148175/37649859-7fd0b59c-2c33-11e8-9d9f-757278dd026c.png">

**Comment by Zakeelm** [comment]
Thanks for elaborating. This helps! I'm going to work on updating our docs to reflect this. I will follow up when the docs are updated!

**Comment by Zakeelm** [comment]
Hey just wanted to give an update on this, we're going to be doing a big overhaul of our CodePush docs in the coming weeks. I'm going to go ahead and close this. This will be updated ASAP as will all of the docs 🙂
