### ISSUE TITLE
Improvements to the example

### ISSUE THREAD

**Issue by pahnev** [MicrosoftDocs/appcenter-docs#431]
I had to find this blog post https://blogs.msdn.microsoft.com/vsappcenter/visual-ui-testing-for-android-apps-with-espresso-and-studio-app-center/, to finally figure out what I should put for the `build-dir` parameter. I think you should improve the explanation of those parameters here in the docs.

I also think a lot of people would like to know how to integrate the build step with a test. Now there is basically no documentation about that. So if anyone is trying to achieve that here's the post-build script that worked for me:

```bash
APPCENTER_TOKEN=YourOwnAPIToken

#Because the script is run from the `app` folder we need to go back one level
cd ..
#These scripts run the builds and produce the APKs we can upload to AppCenter
./gradlew assembleDebug
./gradlew assembleDebugAndroidTest
   
#You need to create your API token in the AppCenter, because `appcenter test run espresso` requires you to be logged in.
appcenter test run espresso --app "demo-app" --devices "demo-devices" --test-series "master" \
--app-path "$APPCENTER_SOURCE_DIRECTORY/app/build/outputs/apk/debug/app-debug.apk" --locale "en_US" \
--build-dir "$APPCENTER_SOURCE_DIRECTORY/app/build/outputs/apk/androidTest/debug" --token $APPCENTER_TOKEN --debug
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8739961-b56c-598c-c23a-0be804729621
* Version Independent ID: 82b926d2-8043-71ed-4501-4e39166b0881
* Content: [Starting a test run - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/starting-a-test-run)
* Content Source: [docs/test-cloud/starting-a-test-run.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/starting-a-test-run.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@pahnev thanks, I'll have the PM take a look at making an update.

**Comment by glennwester** [comment]
Hi @pahnev, thanks for making us aware of this! We've updated and the PR should be merged shortly.
