### ISSUE TITLE
Setting properties on unhandled exceptions

### ISSUE THREAD

**Issue by justintoth** [MicrosoftDocs/appcenter-docs#434]
This documentation shows how to set custom properties on handled exceptions in Xamarin (via Crashes.TrackError), however it doesn't show how to set custom properties on unhandled exceptions. This means that if an exception is caught then it will contain the extra properties (e.g. user and device data), however if the exception wasn't thrown in a try/catch then it won't have any of those exxtra properties. Not good!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a98dc868-6ec0-4d6e-652a-ed90d6c092b4
* Version Independent ID: d6061a26-6aef-be3a-c89a-3c8b290e2c9a
* Content: [App Center Crashes for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin)
* Content Source: [docs/sdk/crashes/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@justintoth I'll have the team look into making an update.

**Comment by thyeggman** [comment]
Hi @justintoth - we don't support setting properties for crashes right now.  You can do something similar by adding a [crash attachment](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin#add-attachments-to-a-crash-report).  If this is a feature you'd like, you can create an issue on our [.NET repo](https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/new).

**Comment by justintoth** [comment]
This is a show stopper for us, as AppCenter is supposed to support everything that HockeyApp does and more. The Xamarin SDK for AppCenter seems very limited, as if it's in an Alpha stage, definitely not a product meant to replace HockeyApp by end of year. You can add a crash attachment to an exception that wasn't handled on app restart (via Crashes.GetErrorAttachments) but you can't add properties to it. You can't add a crash attachment to a caught exception that you're logging via Crashes.TrackError but you can add properties to it. Very inconsistent behavior between the two. We'll stick with HockeyApp for now until this becomes a full-fledged product.
