### ISSUE TITLE
OutputPath example appears to be incorrect

### ISSUE THREAD

**Issue by jefffhaynes** [MicrosoftDocs/appcenter-docs#435]
In the "OutputPath" error resolution, the example path given is "YourProjectDir/bin/$(Configuration)".  However, this is not the typical output path, which would be "/bin/$(Configuration)".  This is either an issue in the documentation or the tooling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a5fe44-6d64-dc1d-9b12-42001a42df4b
* Version Independent ID: 45e022e4-c2fe-5b93-a9ee-8b7942eb507f
* Content: [App Center Build Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/xamarin)
* Content Source: [docs/build/troubleshooting/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/troubleshooting/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@jefffhaynes thanks for pointing this out, we'll take a look at an update.

**Comment by octopotato** [comment]
Hi @jefffhaynes I just took a look at this and created a sample project. As you can see from the screenshot, following the instructions of the documentation (ourXamarin.Android > Project Options > Build > Output) does in fact display the output path as `YourProjectDir/bin/$(Configuration)`.

If you're referring to the `csproj`, then yes the typical output path is `bin/$(configuration)` which is relative to where the `csproj` is located. Let me know if that helps or if I misunderstood you.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/28269664/51857316-c685f100-22e6-11e9-97cb-d8673c995cd0.png">
