### ISSUE TITLE
Xcode gives Module 'AppCenter' not found error while Archive

### ISSUE THREAD

**Issue by serkon** [MicrosoftDocs/appcenter-docs#436]
I generated Ionic 3 and 4 app. I have implemented the instruction as you described to my project. Then ran `ionic cordova build ios` for generate ios plaform. Opened it using Xcode for distrubition, then when i press 'Product/Archive' i am getting Module 'AppCenter' not found error.

There are also a lof of bug while installing you described above. Please check again is really working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63d2707b-0af3-1005-ef9e-aec7f4dc4123
* Version Independent ID: bfa153b4-cc8c-6332-723c-471fc82813ec
* Content: [Get Started with Apache Cordova - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/cordova)
* Content Source: [docs/sdk/getting-started/cordova.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/cordova.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by johnwargo** [comment]
@serkon The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jwargo** [comment]
@serkon The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
