### ISSUE TITLE
.NET  Server Sample 

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#437]
Please add a sample with a Web Api Controller . Is a wrapper SDK for the REST API planned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb96601-f906-374d-b0d8-537e5f80de3e
* Version Independent ID: b66d21ae-1205-3d76-f577-d58891382c08
* Content: [App Center Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/pushapi)
* Content Source: [docs/push/pushapi.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/pushapi.md)
* Service: **vs-appcenter**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by jwargo** [comment]
@ericbrunner No plans for a wrapper SDK for the REST API that I'm aware of today, but we're planning on some updates to the API and the API docs over the next few months.
