### ISSUE TITLE
Build Action GoogleServicesJson is missing

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#438]
I tried several times the procedure of adding the google-services.json to the Droid root folder as desccribed above including save, close and reopen but the Build Action *GoogleServicesJson* doesn't show up.
Any idea?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: edb6a101-b62b-95c8-32e5-5769bd116457
* Version Independent ID: c0c08f43-46d6-6929-4eda-8e293fbbcd4f
* Content: [How to add Firebase SDK - Visual Studio App Center](https://docs.microsoft.com/de-at/appcenter/sdk/push/migration/xamarin-android)
* Content Source: [docs/sdk/push/migration/xamarin-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/migration/xamarin-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@ericbrunner The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by ghost** [comment]
@jwargo Thanks for getting back and your clarification. My intend was to report some difficulties and provide enhancement in the documention.
If interested you can take a look here for further details: 

https://developercommunity.visualstudio.com/content/problem/437373/build-action-googleservicesjson-missing.html

It took me 2 days in getting to a working PUSH enabled App with AppCenter.

**Comment by jwargo** [comment]
@ericbrunner I'm so sorry to hear that - it's supposed to be a quick setup.   Please just use that chat button in App Center - it will get you help pretty quickly. 

I'll ask the team to look at trying to make this easier

**Comment by vkuttyp** [comment]
You have to install the following nuget package: 
Xamarin.GooglePlayservices.Basement
