### ISSUE TITLE
Xamarin.Forms Android Launch Mode MainLauncher = true

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#439]
When the MainLauncher = true then you also have to add the OnNewIntent code mentioned in the documentation. I verified it! Without that code the AppCenter Push message notification doesn't show up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65373652-7eda-af01-0f72-d01fcce4c131
* Version Independent ID: f85b66b3-ca30-bb5c-bfae-6425661d3365
* Content: [App Center Push for Xamarin.Forms Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms#launch-mode)
* Content Source: [docs/sdk/push/xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-forms.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@ericbrunner best to ask support on this one, I can't help.

**Comment by guperrot** [comment]
Hi, I just tested in one of our application with MainLauncher = true and it does not require this call.
If you need it in your application, its because of another options on your activity, can you share the full attributes of that activity?

**Comment by ghost** [comment]
@guperrot Here my Code. I will verify it again today. 
Test scenario:
1. App launched and in background (home button  pressed in phone)
2. Send Notification from AppCenter
Expected: Droid Notification in Notification Area

2nd Test will be the same WITHOUT the OnNewIntent override from the docs.
![screenshot_20190129-033035](https://user-images.githubusercontent.com/6480047/51880151-76ef0600-2376-11e9-88f8-5c7bf9206261.png)



`using System;
using Android.App;
using Android.Content.PM;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;
using Microsoft.AppCenter.Push;

namespace ZoneApp.Droid
{
    [Activity(Label = "ZoneApp", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true,
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            LoadApplication(new App());
        }

        protected override void OnNewIntent(Android.Content.Intent intent)
        {
            base.OnNewIntent(intent);
            Push.CheckLaunchedFromNotification(this, intent);
        }
    }
}`

**Comment by ghost** [comment]
@guperrot You are right. That OnNewIntent code is in my case not required.
