### ISSUE TITLE
Queries about capabilities and usage

### ISSUE THREAD

**Issue by goldengecko** [MicrosoftDocs/appcenter-docs#44]
1. When I use automatic sending, it seems to want dsym and js map files uploaded, but when I enable sending in Javascript, it doesn’t. Why?

2. Either way, it doesn’t seem to provide me useful information about where the crash occurred (file, method, line etc) - am I missing something here?

3. I set up the system to add a text attachment to the report using the following code:

      getErrorAttachments: () => {
        const info = 'some text information I want to see along with the crash report'
        const textAttachment = ErrorAttachmentLog.attachmentWithText(info, 'version.txt')
        return [textAttachment]
      },

I have verified that it’s being called, but I can’t see the information anywhere in the crash report user interface. Where is it put? Or am I calling it incorrectly (the example only shows returning an array of text and binary attachment)?

4. How can I tell what permission to send reports the user has previously given? If they have given UserConfirmation.ALWAYS_SEND permission, I don’t want to show an alert that it’s been sent, but if they have just said yes to sending once, I do want to tell them.

5. Once they have given the UserConfirmation.ALWAYS_SEND permission, how do I reset it so it asks them again?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e420f-cf2a-1d5b-d86a-d01c09bcf7a0
* Version Independent ID: 59c746fb-cf4d-3019-2b48-56b69e09aa27
* [Content](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native#feedback)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/react-native.md)
* Service: vs-appcenter

**Comment by goldengecko** [comment]
I have just found where I can see the attachments in the UI, so please ignore point 3.

**Comment by elamalani** [comment]
@goldengecko For symbolicating JS crashes in iOS, you always need to upload dsym and mapping files. App Center will only then be able to show you useful information about the crash with file name, method and line number. If not, please open a support ticket with us to investigate the issue.

In the UI alert if the user selects ALWAYS_SEND, the SDK will store that selection and will send all the application crashes that happens later without showing the alert. If they select SEND option, the SDK will send the crash to App Center, but will show the alert UI again before sending the next crash.

We dont have an API to reset the user confirmation in the SDK.

**Comment by goldengecko** [comment]
Hmmm, I have been trying to upload the DSYM and mapping files, but it still doesn't give me any useful information. I see that for a `react-native run-ios` build, it puts it in my project's ios/build/Build/Products/Debug-iphonesimulator folder and there's just the MyApp.app.dSYM - I presume that is the only one I would have to upload? And for an archive build, I see there's a dSYMs folder in the xcarchive which has several .dSYM files in it. Do I need to upload all of them or just the MyApp one?

For the map file, I'm using the command:
```
react-native bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output unused.jsbundle --sourcemap-output index.ios.map
```
to generate it. This is a copy and paste of the command in the documentation except changing the entry file since mine is just index.js.

I couldn't find where to open a support ticket from anywhere within the AppCenter, so am replying here.

I also followed the instructions which recommended to create two apps, one for the android build and one for the ios build. It's OK having different places to go to look at the crash reports for the different platforms, but is there some way of looking at the analytics for them combined? My analytics are tracking activities that people do in the app rather than anything platform specific. What would happen if I used the same app secret for both? (or do you use that to know what platform you are dealing with?)

**Comment by elamalani** [comment]
@goldengecko For opening a support ticket, login to https://appcenter.ms portal. There is a blue icon on the lower right end of the portal. Once you click on the icon, click on "New conversation" button to send a message to our product team. That way, we can better help you investigate the first issue.

There is no way in Ap Center to view combined Analytics for both the apps. We want to support "App groups" where you can group similar apps together (in your case RN iOS and Android) that should solve your issue but there is no ETA for that feature.
