### ISSUE TITLE
Cloning builds for different branches

### ISSUE THREAD

**Issue by mussa-ibragimov** [MicrosoftDocs/appcenter-docs#440]
Is there a proper(easy, fast and working) way of coping a build config and using it for another branch?

Right now I have an android application(java) configured build for my dev branch, but I want to build different branches so that my team can test the work before merging it to dev branch. Configuring builds is tedious and practically cannot be done for every branch.

Thank you.

**Comment by jwargo** [comment]
@mussa-ibragimov The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
