### ISSUE TITLE
[AppCenterPush] Sound file 'default' not found; falling back to default.

### ISSUE THREAD

**Issue by K232** [MicrosoftDocs/appcenter-docs#441]
In https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms#android it says I could supply "default" for sound on Android, but if I do so I see the following messagein Application Output window:

 `[AppCenterPush] Sound file 'default' not found; falling back to default.`

Nevertheless it works fine, default sound is played as expected. Just wanted to let you know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65373652-7eda-af01-0f72-d01fcce4c131
* Version Independent ID: f85b66b3-ca30-bb5c-bfae-6425661d3365
* Content: [App Center Push for Xamarin.Forms Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms)
* Content Source: [docs/sdk/push/xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-forms.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@K232 thanks; I'll have the team take a look.

**Comment by guperrot** [comment]
Hi, the message is confusing but actually harmless. The SDK does not assume any default string and will just fall back to using the default sound if it does not find a matching file.

**Comment by guperrot** [comment]
Please also note that if you see this message, then Firebase is not used, your push integration will not work on Android 9+ devices or any device starting April.

Please look at https://docs.microsoft.com/en-us/appcenter/sdk/push/migration/xamarin-android.
