### ISSUE TITLE
How to specify icon for Android Push?

### ISSUE THREAD

**Issue by K232** [MicrosoftDocs/appcenter-docs#442]
On some androids, everything works fine: Push is received and correct icon is displayed. But on some Androids, only a blank box is shown :-( 
I've tried supplying the default icon as shown in https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms#configure-notifications-default-values 
```
<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/icon" />
```
I've added "icon.png" in my drawable folder, as "AndroidResource" of course. Nevertheless it still just shows a blank box next to the push message. Are there any requirements for the png (width / height / etc) ?
![missingicon](https://user-images.githubusercontent.com/685016/51994899-fcc39c00-24b1-11e9-8fa3-ca29204483ef.jpg)

**Comment by jwargo** [comment]
@K232 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by K232** [comment]
Sorry @jwargo , I posted it here because I thought that the documentation might be updated. Currently there is no information about the requirements for the icon, and I guess there are at least recommendations regarding type (png jpg gif etc.) or width / height etc. so updating the documentation would also help other people using this feature.
Typically I'll just contact support if I'm sure I followed all instructions before, but currently I do not find these information in the docs. But of course I will contact support now. Thanks

**Comment by jwargo** [comment]
@K232 no worries, it just sounded like you were asking questions. The docs could be updated, what normally happens is support helps the customer through their issues, then submits a doc update on the backend. If you have a specific update you want made, suggest it here, if something isn't working, lets get it working before trying to update the docs,
