### ISSUE TITLE
have an issue 

### ISSUE THREAD

**Issue by hussam996** [MicrosoftDocs/appcenter-docs#443]
In my app if I have fresh or new install every thing work fine ..but when I update older version the Crash Happen at  " MSAppCenter.start   " in app delegate this is the crash error

[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'

for more info :

est3lamat`+[MSDeviceTracker sharedInstance]:
    0x100afbb00 &lt;+0&gt;:  adrp   x8, 329
    0x100afbb04 &lt;+4&gt;:  ldr    x8, [x8, #0xc68]
    0x100afbb08 &lt;+8&gt;:  cmn    x8, #0x1                  ; =0x1 
    0x100afbb0c &lt;+12&gt;: b.ne   0x100afbb1c               ; &lt;+28&gt; at MSDeviceTracker.m:37
    0x100afbb10 &lt;+16&gt;: adrp   x8, 329
    0x100afbb14 &lt;+20&gt;: ldr    x0, [x8, #0xc60]
    0x100afbb18 &lt;+24&gt;: b      0x100b58b60               ; symbol stub for: objc_retainAutoreleaseReturnValue
    0x100afbb1c &lt;+28&gt;: stp    x29, x30, [sp, #-0x10]!
    0x100afbb20 &lt;+32&gt;: mov    x29, sp
    0x100afbb24 &lt;+36&gt;: adrp   x0, 329
    0x100afbb28 &lt;+40&gt;: add    x0, x0, #0xc68            ; =0xc68 
    0x100afbb2c &lt;+44&gt;: adr    x1, #0xd0ca4              ; __block_literal_global
    0x100afbb30 &lt;+48&gt;: nop    
    0x100afbb34 &lt;+52&gt;: bl     0x100b58800               ; symbol stub for: dispatch_once
    0x100afbb38 &lt;+56&gt;: ldp    x29, x30, [sp], #0x10
    0x100afbb3c &lt;+60&gt;: b      0x100afbb10               ; &lt;+16&gt; at MSDeviceTracker.m:37

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45228922-4a96-8c08-7d27-69ef98d44943
* Version Independent ID: d04ef359-7b17-8a14-970b-5c48820976cd
* Content: [Get Started with iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios)
* Content Source: [docs/sdk/getting-started/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @troublemakerben
* Microsoft Alias: **bereimol**

**Comment by jwargo** [comment]
@hussam996 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
