### ISSUE TITLE
Documentation is missing how to change crash config to be processed by JavaScript

### ISSUE THREAD

**Issue by Eyesonly88** [MicrosoftDocs/appcenter-docs#445]
The documentation doesn't show how to change the crash reporting configuration from ALWAYS_SEND to ASK_JAVASCRIPT for projects that have already answered "ALWAYS_SEND".

I had to go into the source code to find out what to do in order to change my existing project from the ALWAYS_SEND configuration to the ASK_JAVASCRIPT configuration.

The documentation should outline these steps.

For anyone interested in doing this before the docs are updated, read a file called `postlink.js` inside `appcenter-crashes/scripts`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e420f-cf2a-1d5b-d86a-d01c09bcf7a0
* Version Independent ID: 59c746fb-cf4d-3019-2b48-56b69e09aa27
* Content: [App Center Crashes for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native)
* Content Source: [docs/sdk/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@Eyesonly88 thanks, I'll have the team take a look.

**Comment by dhei** [comment]
Hi @Eyesonly88,
Thanks for the feedback. Yes, you can figure out how to manually change the config if you dig into that script. 
If you re-run `react-native link` after configured, you should be prompted with the crash configuration choice on Android and iOS again. Do you not getting this prompt?


```For the Android app, should crashes be sent automatically or processed in JavaScript before being sent? (Use arrow keys)
    ❯ Automatically
      Processed in JavaScript by user

For the iOS app, should crashes be sent automatically or processed in JavaScript before being sent? (Use arrow keys)
    ❯ Automatically
      Processed in JavaScript by user```

**Comment by dhei** [comment]
Close due to lack of response and unable to repro.
