### ISSUE TITLE
Instructions for macOS are missing

### ISSUE THREAD

**Issue by m2u-84** [MicrosoftDocs/appcenter-docs#449]
The „Where can I find my .app.zip file?“ link from MS App Center’s „Distribute“ → „Groups“ → „New release“ for uploading new macOS builds screen brings me here. But there are no instructions for macOS here. Our build system produces DMG files and .app folders, both of which aren‘t accepted as input. The web front-end just says „Version could not be created from build.“, the CLI outputs „release binary file uploading failed: HTTP 422 Unprocessable Entity“. Simply renaming the DMG to ….app.zip isn‘t helping either, so please provide proper help in this article. Thanks & regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#feedback)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by jwargo** [comment]
@m2u-84 I'll have the team take a look at making this clearer. 

When you're not sure how something works, remember that App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by botatoes** [comment]
Hi, you should be able to upload .app.zip files. If you are experiencing an issue, please open an intercom ticket and we'll help you there. 

I'll update the docs to include information about MacOS in our docs.
