### ISSUE TITLE
Realisation

### ISSUE THREAD

**Issue by hendra4ditya** [MicrosoftDocs/appcenter-docs#45]
Stock#25714

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45228922-4a96-8c08-7d27-69ef98d44943
* Version Independent ID: d04ef359-7b17-8a14-970b-5c48820976cd
* [Content](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/ios.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@hendra4ditya I don't understand your comment. Are you proposing a change to the docs?
