### ISSUE TITLE
Doesn't cover how to unblock on newer versions of Android OS

### ISSUE THREAD

**Issue by justingden** [MicrosoftDocs/appcenter-docs#452]
This requires adding your specific application to install unknown sources, no longer just a single setting globally.

Here is an example of the instructions:
https://www.verizonwireless.com/support/knowledge-base-222186/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcecd38a-7696-e7f8-853d-d3c12c0b050c
* Version Independent ID: abdba972-b2cd-6c73-83fe-bb1abaac190f
* Content: [Testing Android Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android)
* Content Source: [docs/distribution/testers/testing-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-android.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@justingden are you looking for a doc update or help getting this to work?

**Comment by justingden** [comment]
Just a doc update. I got through it fine, but just wanted it clarified for
other users that might be confused.

Let me know if you need any more info on the specifics.

Thank you,

Justin

**Comment by justingden** [comment]
It will also ask you automatically once you try to install the APK and
allow you to go to settings for the app that did the download.

Justin

**Comment by Oddj0b** [comment]
Hi @justingden, I have updated the docs.

https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android

**Comment by justingden** [comment]
Cool, thank you and that was quick :)

**Comment by jwargo** [comment]
@justingden we aim to please!
