### ISSUE TITLE
Missing info on how to get mappings from the App Center Build service

### ISSUE THREAD

**Issue by Eyesonly88** [MicrosoftDocs/appcenter-docs#453]
This doc needs more information on:
- How to get the `mappings.txt` file from the App Center build service? where is this `mapping.txt` file located when the app is built using app center?
- For builds generated by App Center, we would expect the `mappings.txt` file to be uploaded automatically to the Diagnostics for each build. If that's not the case, then how can we send it ourselves using your API? an example would be highly appreciated.
- Is the location of `mappings.txt` different between Android apps and React Native apps?
- Assuming someone figured out how to get this to work, what does the deobfuscated stacking traces look like?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e9c7ee-7522-cc0a-7ff1-7748f93efa83
* Version Independent ID: 683bf206-d70c-192b-6f59-f03dd1f66885
* Content: [Android ProGuard - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-proguard)
* Content Source: [docs/diagnostics/Android-ProGuard.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/Android-ProGuard.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by jwargo** [comment]
@Eyesonly88 thanks, I'll have the team take a look at doing an update.

**Comment by winnie** [comment]
Hi @Eyesonly88,

Thanks for the feedback! Unfortunately, our build service doesn't make the `mappings.txt` file available for download and doesn't automatically upload them to our Diagnostics service. This is something we hope to support in the future but isn't on our short term roadmap. I'll let you know if there are any updates. 

In the meantime, you can upload your mappings file in UI under the Diagnostics --> Mapping tab as shown below:

![image](https://user-images.githubusercontent.com/8868628/52310368-08064400-2958-11e9-905c-320203246768.png)

Thanks!

**Comment by jwargo** [comment]
@winnieli1208 close?

**Comment by Eyesonly88** [comment]
@winnieli1208 @jwargo Thanks for the reply but not all my questions were answered:

- Where is this `mapping.txt` file located when the app is built using app center?
- How can we send it ourselves using your API? an example would be highly appreciated
- Is the location of `mappings.txt` different between Android apps and React Native apps?
- Assuming someone figured out how to get this to work, what does the deobfuscated stacking traces look like?

**Comment by winnie** [comment]
Hi @Eyesonly88,

1. The location is dependent on the build system you use but for Android builds it's typically inside sth like `app/build/outputs/mapping/...`
2. We don't have any available APIs to retrieve the `mappings.txt` file. I've noted this as a feature request so our team can revisit this in the future.
3. Waiting to hear back from our engineering team to confirm
4. Here's a screenshot of a deobfuscated stack trace as an example

![image](https://user-images.githubusercontent.com/8868628/52496506-513cda80-2b88-11e9-837c-84ddb9e47b5f.png)



I'm also tagging @ranterle, an engineer on our team in case you have any additional questions. Thanks!!

**Comment by hsc-alexe** [comment]
@winnieli1208 @ranterle
Do you have any updates on the prioritization of this request or when we could expect to see this feature implemented? My team has been using AppCenter to build & distribute our app, but not being able to deobfuscate crashes is frankly not an acceptable place for us to be in long-term.

**Comment by jwargo** [comment]
@hsc-alexe I'm not sure if the feature has been proposed [here](https://github.com/Microsoft/appcenter/issues) but that is the quickest view to our roadmap and your opportunity to get your item on it.

**Comment by Eyesonly88** [comment]
@hsc-alexe I've proposed a feature for Android source maps (upvote if this is what you need too) > https://github.com/Microsoft/appcenter/issues/75

**Comment by matthiaswenz** [comment]
@Eyesonly88 regarding your question
> Is the location of `mappings.txt` different between Android apps and React Native apps?

It is not significantly different, where in your typical Android app the mappings.txt would be here:
`app/build/outputs/mapping/{variant}`
for React Native they are here:
`android/app/build/outputs/mapping`

**Comment by droidluv** [comment]
Has the feature request for the auto upload/download of mapping.txt for proguard enabled build flavours been created if so can someone point me there? Right now to create the mapping.txt, I will have to generate it manually on my machine and then upload it seems, why when making everything else easy, make only this part a pain?

**Comment by matthiaswenz** [comment]
@droidluv We are aware of this request. This thread here is about making the artifacts available as a download. Adding the mappings to your release automatically just as you are able to distribute a release to your users is equally important to us but technically more complex.

I am not aware of any other feature request for this, so would recommend to create one and outlining your use case in there.

**Comment by nilofer** [comment]
@droidluv to piggy-back on @ranterle's comment, you can file a feature request for that on our [repo](https://github.com/Microsoft/appcenter/issues) if it isn't already there

**Comment by gchiacchio** [comment]
Anyone looking for a guide on how to upload the generated `mapping.txt` to AppCenter, you can see my comment (with instructions) in the [proposed feature](https://github.com/microsoft/appcenter/issues/75#issuecomment-493184790)

**Comment by hopewise** [comment]
@Eyesonly88 I could not find the file where you mentioned in my project.. is there something I have to do to generate the mapping file?

**Comment by matthiaswenz** [comment]
@hopewise do you know whether ProGuard is actually running in your build? By default, the ProGuard mappings are enabled only for release builds (look for the `minifyEnabled` setting ([Android developer link](https://developer.android.com/studio/build/shrink-code)) in your build.gradle.
