### ISSUE TITLE
React Native Android source maps are not supported

### ISSUE THREAD

**Issue by Eyesonly88** [MicrosoftDocs/appcenter-docs#454]
I believe this doc needs to be updated to mention that RN android apps don't have source maps and therefore the stack traces don't show the JavaScript files/lines. 

This is a big issue for many people and it needs to be shown here as it is a current limitation.
(https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/208)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2b0f5e-997d-d42d-f7e2-8168cdc812e0
* Version Independent ID: 7f760699-c91d-e427-25be-85a4611fba7d
* Content: [Limitations - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/limitations)
* Content Source: [docs/diagnostics/limitations.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/limitations.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by jwargo** [comment]
@Eyesonly88 thanks, I'll ask the team to take a look.

**Comment by winnie** [comment]
Hi @Eyesonly88, thanks for the feedback! I've updated the [docs](https://docs.microsoft.com/en-us/appcenter/diagnostics/limitations) to mention this limitation.

**Comment by Eyesonly88** [comment]
Thank you.
