### ISSUE TITLE
Problem with In-App Updates

### ISSUE THREAD

**Issue by dotfig** [MicrosoftDocs/appcenter-docs#456]
In app updates with Android version 5.1 does not function properly but Android version 7.0 does. Not sure why this is but is there a work around for this, or am I doing something wrong?

**Comment by jwargo** [comment]
@dotfig The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
