### ISSUE TITLE
Mention of Fastlane

### ISSUE THREAD

**Issue by matt-paul** [MicrosoftDocs/appcenter-docs#457]
I'm unclear on the relevance of Fastlane, mentioned in the first paragraph...
``` Publish iOS app upgrades to the App Store and TestFlight with Fastlane in App Center.```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edcd9010-7381-ef0a-85ee-3289b742c8de
* Version Independent ID: 63c5a53d-e211-a17e-e0c0-27638748da7d
* Content: [Publish to iTunes - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple)
* Content Source: [docs/distribution/stores/apple.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/apple.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by jwargo** [comment]
@matt-paul I'll have the team take a look and clarifying that.
