### ISSUE TITLE
Adding Jira to Bug Tracker

### ISSUE THREAD

**Issue by mamdouht** [MicrosoftDocs/appcenter-docs#460]
I had an issue doing that.
I am using Jira with Two-Step Verification. so I had to create an API token and use it instead of my password (using my ID). then i was able to connect Jira to Bug Tracker properly.
I think adding this to the documentation might help other people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99771c68-5f45-887a-e926-9ea772021f99
* Version Independent ID: 865109fc-64b8-ba77-2e10-8002886c46c7
* Content: [App Center bug tracker documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/)
* Content Source: [docs/dashboard/bugtracker/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/bugtracker/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@mamdouht thanks, I'll have the team take a look.

**Comment by amchew** [comment]
Thanks @mamdouht for the suggestion and for using Jira as a bug tracker! I’ll make the changes in the docs shortly.

**Comment by amchew** [comment]
Thanks a lot again for sharing this feedback @mamdouht ! I've made a PR to update the docs here: https://github.com/MicrosoftDocs/appcenter-docs-pr/pull/1150.

**Comment by amchew** [comment]
It will be published shortly, I'm closing this ticket for now. Feel free to reopen if you see any other issues!
