### ISSUE TITLE
Silent push for iOS without UI

### ISSUE THREAD

**Issue by pfedotovsky** [MicrosoftDocs/appcenter-docs#461]
The documentation doesn't mention if it's possible to do silent push without UI.
I've filled GitHub issue about the topic: https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/831

If silent push w/o UI is possible, documentation should describe how to do it. If not, it should also be explicitly stated in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6415607-5d22-0249-2537-1d7887b46f16
* Version Independent ID: 32fafbc0-515e-043f-3481-6f7c3fe2cc91
* Content: [App Center Push for Xamarin.iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios)
* Content Source: [docs/sdk/push/xamarin-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by MatkovIvan** [comment]
Hi Pavel,

This is documented in [[Optional] Enable silent notifications](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios#optional-enable-silent-notifications) section.

Thanks,
Ivan

**Comment by pfedotovsky** [comment]
That's not exactly what I'm asking.
I can send a silent push, that's working fine. But I still get UI notification that is presented to the user. I want to disable any user notification and just update app data silently. How to do it?

**Comment by MatkovIvan** [comment]
@pfedotovsky leave the message field empty and put your data in "Custom data"

**Comment by pfedotovsky** [comment]
@MatkovIvan thank you!

I leave "Message" & "Title" fields empty and now notification UI is not presented. I think this should be mentioned in the documentation.

However, when my app is in the background, a callback is not triggered (but when I open the app it is triggered). I believe it's due to how iOS processes background updates and I guess it should also be mentioned in the docs.

**Comment by MatkovIvan** [comment]
You're welcome. I'll add a note to the doc about it.
