### ISSUE TITLE
How to enable line numbers in stack traces

### ISSUE THREAD

**Issue by danim-hub** [MicrosoftDocs/appcenter-docs#462]
This document does not specify how to show line numbers in stack traces.  I understand *release* builds comes with no debugging information, but I think these releases can be "symbolicated" in iOS, and probably there is a similar verb for Android.  Please comment if it is possible to do this, and it will be really appreciated if you update this document accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a98dc868-6ec0-4d6e-652a-ed90d6c092b4
* Version Independent ID: d6061a26-6aef-be3a-c89a-3c8b290e2c9a
* Content: [App Center Crashes for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin)
* Content Source: [docs/sdk/crashes/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@danim-hub I'll have the team take a look at doing an update.

**Comment by winnie** [comment]
Hi @danim-hub,

We don't currently display line numbers in Xamarin stack traces. I'm actually in conversation with the Xamarin team as we think this is a limitation on the Xamarin side since we don’t process any Xamarin logs and line numbers are only available in debug builds of Xamarin apps.

In the meantime, I've noted this as a feature request to help our team prioritize this in the future. I'll keep you posted when I hear back and have a workaround/solution. Thanks for your patience!

**Comment by thedee** [comment]
> Hi @danim-hub,
> 
> We don't currently display line numbers in Xamarin stack traces. I'm actually in conversation with the Xamarin team as we think this is a limitation on the Xamarin side since we don’t process any Xamarin logs and line numbers are only available in debug builds of Xamarin apps.
> 
> In the meantime, I've noted this as a feature request to help our team prioritize this in the future. I'll keep you posted when I hear back and have a workaround/solution. Thanks for your patience!

Anything new on this?  I am using Xamarin and AppCenter and when things get logged there are no lines #'s in the exception log.

**Comment by amrosama2020** [comment]
[+]

**Comment by winnie** [comment]
Hey there - apologies for the delay. No updates on this yet. We have an item on our backlog to investigate this some more but unfortunately I don't have an ETA. I'll post here with updates. 

Thanks!

**Comment by amrosama2020** [comment]
@winnieli1 Thanks a lot for the update.

**Comment by stiansun** [comment]
Following! This feature would definately be at large help.

**Comment by SkyeHoefling** [comment]
This would be a huge benefit to us as well

**Comment by sandorfr** [comment]
It's weird the official screenshots include the line numbers. So I guess it must boil down to uploading some files like pdb. It just lacks some guidance. Why did you close this @jwargo ?

**Comment by jwargo** [comment]
@sandorfr because @winnieli1 responded with a direct answer, I assumed that was enough. If you want it open, please do so.

**Comment by breyed** [comment]
Generally, responding with a direct answer isn't reason to close an issue. The issue has to have reached a state of resolution, e.g. fixed, not applicable, etc. Since this issue is on the docs specifically, it represents the lack of documentation regarding enabling line numbers. The docs should probably be updated to mention the that the stack traces don't support showing line numbers, since that's a common feature with stack traces. This issue should stay open until that doc update is made.

Separately, there's another issue about actually implementing line numbers (not just documenting). That issue is in the private backlog that @winnieli1 mentioned and presumably is still open. Unfortunately, there's no transparency into the private backlog issue.

**Comment by AhmedAdelAlDesouqy** [comment]
Any update about this issue?
I'm using App Center with Xamarin.Android and there are still no line numbers in the crash reports :(

**Comment by danielmeza** [comment]
Without line number this feature loose power and, this have reach a complete year and will be great if we get some update, like a link to point the discussion to the right point or to track the feature implementation.

**Comment by shehrozeee** [comment]
Still looking for line number

**Comment by fgiacomelli** [comment]
Same request for me

**Comment by danielmeza** [comment]
Shall we wait until .net 5 comes to Xamarin in order to get this feature? If yes I can wait 👯

**Comment by Mikilll94** [comment]
Same issue here:
In release mode, line numbers are not shown in stack traces on both iOS and Android.

In debug mode, line numbers are shown.

**Comment by catlan** [comment]
See open issue on App Center [#165](https://github.com/microsoft/appcenter/issues/165) and Xamarin Android [#3657](https://github.com/xamarin/xamarin-android/issues/3657).

**Comment by fgiacomelli** [comment]
I obtained lines number using mono-symbolicate tool, enabling debug info and saving pdb and dll of each build. But it's a very useful information, it would be great if App Center should be able to do it automatically

**Comment by danielmeza** [comment]
@fgiacomelli question. The dll that you publish with the app has the debug info enabled or you enabled it just to get the pdb and then publish a dll version without debug support? I has because enable debug infrastructure affect the performance.

**Comment by fgiacomelli** [comment]
at this time we are publishing a version with full debug info enabled; performances are not really worsened and for us is more important being able to fix crashes quickly.
@danielmeza did you tried to use a stacktrace produced from a release version (without pdb) with pdb files generated from the same version built with debug info enabled? I'm not sure it can works, but if it do, it would be great

**Comment by danielmeza** [comment]
@fgiacomelli No, I have not test yet I don't know how to put the pdb in the apk to be distrubuted to production! even when I deploy the app In debug mode when I use adb logcat to see the log the stack trace doesn't show the line number info.

**Comment by joncortez** [comment]
> at this time we are publishing a version with full debug info enabled; performances are not really worsened and for us is more important being able to fix crashes quickly.
> @danielmeza did you tried to use a stacktrace produced from a release version (without pdb) with pdb files generated from the same version built with debug info enabled? I'm not sure it can works, but if it do, it would be great

What settings in your Android project did you have to set and the values to enable correct generation of .mSYM on Release builds? I had MonoSymbolArchive = true, DebugSymbols = true, and DebugType = PdbOnly. It generated the .mSYM files and when I run mono-symbolicate, I am getting IndexOutOfRangeException error when it is trying to parse a raw crash report from AppCenter.

**Comment by joncortez** [comment]
> at this time we are publishing a version with full debug info enabled; performances are not really worsened and for us is more important being able to fix crashes quickly.
> @danielmeza did you tried to use a stacktrace produced from a release version (without pdb) with pdb files generated from the same version built with debug info enabled? I'm not sure it can works, but if it do, it would be great

What settings in your Android project did you have to set and the values to enable correct generation of .mSYM on Release builds? I had MonoSymbolArchive = true, DebugSymbols = true, and DebugType = PdbOnly. It generated the .mSYM files and when I run mono-symbolicate, I am getting IndexOutOfRangeException error when it is trying to parse a raw crash report from AppCenter.

**Comment by nrobeson** [comment]
Still waiting for line numbers.

**Comment by elielson-anjos** [comment]
any news on this?

**Comment by ali-h2010** [comment]
Any update on this?
we still can't see any line numbers on 2023?

**Comment by bruno-garcia** [comment]
Sentry has line numbers for .NET PDBs: https://github.com/getsentry/sentry-dotnet/issues/1740
You can configure your Sentry project (slug and auth token) in MSBuild: https://docs.sentry.io/platforms/dotnet/configuration/msbuild/ and symbols are auto uploaded
