### ISSUE TITLE
Crashes.SetEnabledAsync doesn't default to true on app restart

### ISSUE THREAD

**Issue by dstulic** [MicrosoftDocs/appcenter-docs#463]
Crashes.SetEnabledAsync stores value on disk, and the value is used on following app runs.
To repro:

first run
`
      AppCenter.Start("key", typeof(Crashes));
      Crashes.SetEnabledAsync(false);
`

second run
`
      AppCenter.Start("key", typeof(Crashes));
      //Crashes.IsEnabledAsync() - returns false
`

Looks like disabling crashes is stored on disk and value is used in following app runs. While this may be a desired feature, it needs to be documented. Currently there seems to be lack of documentation around it.

**Comment by jwargo** [comment]
@dstulic thanks, I'll have the team take a look.

**Comment by MatkovIvan** [comment]
Hi @dstulic,

This is by design. I'll add the note to our docs.

Thanks,
Ivan

**Comment by gmarbury** [comment]
Crashes.IsEnabledAsync() always returns false. Even after setting it to true

**Comment by AnastasiaKubova** [comment]
Hi, @gmarbury ! Please make sure that you use `Crashes.IsEnabledAsync() ` after Crashes have been [started](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin#check-if-app-center-crashes-is-enabled).
