### ISSUE TITLE
How do I enable this?

### ISSUE THREAD

**Issue by 343max** [MicrosoftDocs/appcenter-docs#464]
How do I enable this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc4748f-3820-3b4d-b6d5-f0566063ce30
* Version Independent ID: 103d8b55-8719-dcaa-0670-d22e46e328cb
* Content: [Enable In-app Updates - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/inappupdates)
* Content Source: [docs/distribution/inappupdates.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/inappupdates.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by jwargo** [comment]
@343max The document you referenced describes that this is automatically enabled when you add the SDK to your app.  If you're not sure how this works, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by 343max** [comment]
I'm pretty sure it isn't enabled by default, at least I never saw the screen for our builds.

In the end I've found a documentation here: https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#add-in-app-updates-to-your-app
