### ISSUE TITLE
Is the query PUT, POST, DELETE? 

### ISSUE THREAD

**Issue by toshe** [MicrosoftDocs/appcenter-docs#466]
&gt; Stop collecting all SDK data for a specific device from the server: 
Is this API query also a PUT query?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67fac13b-a00b-2ac8-682c-66ea2b5841b9
* Version Independent ID: e11445ce-4afa-a87b-102b-97df2b868bc7
* Content: [How to stop collecting data - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/gdpr/how-to-stop-collecting-data)
* Content Source: [docs/gdpr/how-to-stop-collecting-data.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/how-to-stop-collecting-data.md)
* Service: **vs-appcenter**
* GitHub Login: @kpiteira
* Microsoft Alias: **kapiteir**

**Comment by jwargo** [comment]
@iageoghe and @kpiteira can you fix this inconsistency in the docs?

**Comment by jwargo** [comment]
Docs updated
