### ISSUE TITLE
react-native@0.57.1: The engine "node" is incompatible with this module. Expected version ">=8.3". Got "6.16.0"

### ISSUE THREAD

**Issue by SeanningTatum** [MicrosoftDocs/appcenter-docs#467]
I don't know why I get this error, this error happens on android and ios

```
[1/4] Resolving packages...
[2/4] Fetching packages...
error react-native@0.57.1: The engine "node" is incompatible with this module. Expected version ">=8.3". Got "6.16.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
##[error]/bin/sh failed with return code: 1
##[error]/bin/sh failed with error: /bin/sh failed with return code: 1
```

node version: v10.14.2
OS: Mac OS Mojave 10.14.2

**Comment by jwargo** [comment]
@SeanningTatum The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
