### ISSUE TITLE
Be specific on the location of .xcscheme file

### ISSUE THREAD

**Issue by ariya** [MicrosoftDocs/appcenter-docs#469]
&gt; Then make sure the added .xcscheme file is added to source control and pushed to your remote repository - which App Center accesses.

Can be the location of the said .xcscheme file be given more specifically? I have tried to place at the top-level of the source directory, still no success (App Center does not recorgnize it). Placing it under the .xcodeproj directory? Same thing, no luck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3efbfa-b70b-9039-4b49-6ba4ce6c36af
* Version Independent ID: 73e079aa-bbc3-2a06-a5d1-c4827bd5e3dc
* Content: [App Center Build Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/ios)
* Content Source: [docs/build/troubleshooting/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/troubleshooting/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajp**

**Comment by jwargo** [comment]
@ariya thanks, I'll have the team take a look.

**Comment by harlando** [comment]
I am also getting the same error. Bootstrapped the app, pushed to BitBucket and got the same issue. All my schemes are shared. I am not using an Xcode workspace....just a project. I'm not sure how/where to get this xcscheme file. My other React Native project on App Center has been building fine since last year... thank you for helping

**Comment by nilofer** [comment]
@ariya @harlando we should be able to pick them up if they are under the project folders where Xcode creates them by default.

If you are still facing issues, please reach out to App Center support which is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
