### ISSUE TITLE
Are you killing the project?

### ISSUE THREAD

**Issue by mbertelsen** [MicrosoftDocs/appcenter-docs#47]
The roadmap is short and you haven’t release anything in over 2 months? Are you terminating the project?  You have not fixed Managed exceptions and that have been a issue since day one? We was changing from RayGun to AppCenter but if you are not dedicated and stop development we will change back again.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 62690a4a-94f3-21cb-a674-d297e557ca62
* Version Independent ID: 3adaeac7-e034-5b5b-19c5-1c0151a7264c
* [Content](https://docs.microsoft.com/da-dk/appcenter/general/changelog)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/changelog.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@mbertelsen we're regularly releasing features for this product, we released new features and a new version of the SDK just last week.  This project is under active development.

I apologize for the short roadmap, but we're in the process of tightening up some infrastructure capabilities right now and getting ready for GDPR is a focus as well.
