### ISSUE TITLE
768

### ISSUE THREAD

**Issue by neeeeek100** [MicrosoftDocs/appcenter-docs#470]
765

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9596a2ab-2a3d-66cc-bc9d-b06256bef86f
* Version Independent ID: 9c12d768-6e98-997b-192a-623e3d7bb68e
* Content: [App Center General Info - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/)
* Content Source: [docs/general/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/index.md)
* Service: **vs-appcenter**
* GitHub Login: @joemellin
* Microsoft Alias: **joemel**

**Comment by jwargo** [comment]
@neeeeek100 I don't understand what you're asking.
