### ISSUE TITLE
How do you disable bitcode in Visual Studio for Mac?

### ISSUE THREAD

**Issue by mikeberlin** [MicrosoftDocs/appcenter-docs#471]
I am not able to see where to disable bitcode from within Visual Studio for Mac. Where can this be disabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94f7999c-0c3c-ee5d-c8a9-29ee9aa0d622
* Version Independent ID: 1c9f21ed-86de-8e79-d007-e80945edf360
* Content: [iOS Symbolication - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication)
* Content Source: [docs/diagnostics/iOS-symbolication.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/iOS-symbolication.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by jwargo** [comment]
@mikeberlin I'll have the PM team take a look at making this clearer. In the mean time, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by lumaxis** [comment]
Hey @mikeberlin!
For Xamarin.iOS projects, Bitcode is currently always disabled by default so there should be nothing for you to do here.
Are you already experiencing any issues with Bitcode and crash report symbolication?

**Comment by mikeberlin** [comment]
Thanks for the reply. I am having some issues with uploading symbols within App Center. They sent me to this url to see if bitcode was enabled, and if so, to disable it.

https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication

In that url, the directions are not very clear on how to disable it. It's good to know that it is disabled by default. I'll follow up with the App Center support team with this new information.
