### ISSUE TITLE
App Center API - example of how to download test results?

### ISSUE THREAD

**Issue by jameslavery-zz** [MicrosoftDocs/appcenter-docs#473]
Is there an example of the sequence of calls we need to make to download UITest results, including screenshots?

**Comment by jwargo** [comment]
@jameslavery assigned the PM

**Comment by Oddj0b** [comment]
I am not aware of a plug-n-play solution, but let me ask around to find a solution and document it.

**Comment by jameslavery-zz** [comment]
@Oddj0b Thanks - I'm not after a plug-n-play solution (that would be lazy), but a pointer/solution would be useful!

**Comment by Oddj0b** [comment]
Let's keep the conversation going in #472
