### ISSUE TITLE
Add note to advise that 'Third-party application access via OAuth' policy setting must be enabled

### ISSUE THREAD

**Issue by rohancragg** [MicrosoftDocs/appcenter-docs#474]
An Organisation Administrator (or Project Collection Administrator) needs to ensure that the setting 'Third-party application access via OAuth' is enabled  (found under 'Organisation Setting | Policies').

Seealso : https://docs.microsoft.com/en-gb/azure/devops/organizations/accounts/change-application-access-policies?view=azure-devops&viewFallbackFrom=vsts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12fa9a24-2575-3fa4-ffab-cafaeab496c1
* Version Independent ID: bbb99ead-eecc-222a-bc16-7509be5e8ec9
* Content: [Managing source repository connections - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/connect#azure-devops-formerly-visual-studio-team-services)
* Content Source: [docs/build/connect.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/connect.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by userjeom3** [comment]
Hi Rohan, it was my pleasure supporting you on this matter. I’ll see if I can put something on the doc. Thanks for your feedback.

**Comment by wisdeom** [comment]
Hi Rohan, it was my pleasure supporting you on this matter. I’ll see if I can put something on the doc. Thanks for your feedback.
