### ISSUE TITLE
Code signing certificate security

### ISSUE THREAD

**Issue by CyberFreek** [MicrosoftDocs/appcenter-docs#475]
Hi, 
The steps in this article instruct the developer to upload the Apple Code signing certificate (.p12 file) public and private keys into app center. Obviously if this certificate were to be obtained by a malicious user it could cause great damage to an organization. Can you describe what security measures are in place to restrict access to this certificate and ensure it doesn't fall into the wrong hands? Also what security controls are available to ensure that only authorized employees can access it? 
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b5aee85-ff56-92ea-bcc1-bcb75766d0ec
* Version Independent ID: 6ff20886-6471-3dcf-1434-a9fbee5c729f
* Content: [Uploading iOS Code Signing Files in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/uploading-signing-files#feedback)
* Content Source: [docs/build/ios/uploading-signing-files.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/uploading-signing-files.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@CyberFreek don't forget, [Microsoft Runs on Trust](https://www.microsoft.com/en-us/legal/compliance/integrity), it's core to everything we do. Your stored certificate and credentials are protected. I'll ask the PM to update the docs with more details.

**Comment by nilofer** [comment]
@CyberFreek certificates cannot be downloaded via the UI or the public API once they are uploaded. The download can only happen via a build on our agents that are torn down after each build and all of these can be traced. The communication between the server and the build agents is encrypted and only the agent can obtain the certificates and secrets.
