### ISSUE TITLE
Can't Find Public Download Link

### ISSUE THREAD

**Issue by justingden** [MicrosoftDocs/appcenter-docs#476]
The text says "In addition to this, a public download link is displayed underneath the distribution group name at the top of the distribution group page. Anyone, including testers who aren't explicitly added to the distribution group, can access the release without signing in using the public download link."

I have looked on all the distribution group pages I can find and I can't find the Public Download Link. Where is this or is it gone now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a807b36-339c-dd76-a6bb-132005991516
* Version Independent ID: 8ffb33e3-09fd-fe41-742f-a9f4d11bf901
* Content: [Manage App Center Distribution Groups - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/groups)
* Content Source: [docs/distribution/groups.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/groups.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by jwargo** [comment]
@justingden I'll have the team take a look.

**Comment by botatoes** [comment]
@justingden you need to make the distribution group public. Go to the distribution group and click on the wrench icon then check the app can be downloaded by anyone toggle
<img width="555" alt="image" src="https://user-images.githubusercontent.com/7900087/53268727-c1288600-369b-11e9-8f89-db813e8adfa5.png">

**Comment by justingden** [comment]
Please don't close this. I don't see what you sent me. See this screenshot.

[image: image.png]

Thank you,

Justin

**Comment by justingden** [comment]
![image](https://user-images.githubusercontent.com/47331336/53269437-17022b80-36a6-11e9-825b-268061d1eb58.png)

Here is the screenshot with the setting already turned on, there is NO public url.

**Comment by justingden** [comment]
The screen snippet you sent also contradicts the documentation, which says "a public download link is displayed underneath the distribution group name at the top of the distribution group page".

**Comment by jwargo** [comment]
@justingden The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. We'll work on updating the docs. 

It sounds like you're having trouble seeing what we're seeing, so it's best you take this to support.

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by justingden** [comment]
Ok, will do. On the doc side you should look at my last comment, as where
the public URL is obtained from, if it works like the screen snippet, is
different from the doc.

Thank you,

Justin

**Comment by botatoes** [comment]
@justingden You can set public for specific distribution groups. You are in the people tab under the org, meant for managing people, not groups. If you go into an app, go to the specific distribution group you want to make public, you should see the screenshot I posted once you click on the wrench.

**Comment by justingden** [comment]
Thank you, Bo-ying, that is exactly what I was looking for and it does show
up under the distribution group name on that page, as the doc says.

You might want to add that minor clarification to the doc for people like
me that are confused as to with distribution page.

Thank you again!

**Comment by nlsrchtr** [comment]
@justingden i would highly recommend to remove the screenshot, because you are exposing private data here...

**Comment by justingden** [comment]
@nlsrchtr Great call, I have deleted it from the thread. Thank you.
