### ISSUE TITLE
In-App Updates per Android OS Versions

### ISSUE THREAD

**Issue by dotfig** [MicrosoftDocs/appcenter-docs#481]
I have the in-app updates enabled and running on my device. However, when I try to update on my Android v5.1 device, it does not work but when I update on my Android v7.0 device, it does work. Not sure if the feature only works for specific SDK versions of Android?

On my Andoidv5.1 device, there is a *downloadfile.apk* file that is put in my Download Manager but it does not work

**Comment by jwargo** [comment]
@dotfig The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
