### ISSUE TITLE
Not able to add Apple Developer Account 

### ISSUE THREAD

**Issue by amrutha786** [MicrosoftDocs/appcenter-docs#482]
I am not able to add Apple Developer Account in Distribute > Store, Attached is the screenshot of error that I am seeing. 

<img width="429" alt="screen shot 2019-02-26 at 11 47 58 am" src="https://user-images.githubusercontent.com/21096553/53441781-6608d300-39bc-11e9-80f8-81984039f165.png">

I have enabled Two Step Verification instead of Two Factor authentication.

**Comment by jwargo** [comment]
@amrutha786 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
