### ISSUE TITLE
Suggest Including Information about using App Center Diagnostics in a Development Scenario

### ISSUE THREAD

**Issue by bogan** [MicrosoftDocs/appcenter-docs#485]
The sub articles for each platform (Android, iOS, etc) each state that "Collecting crashes works for both beta and live apps". This is good but I think you should also include information about whether it is possible to write diagnostic information to AppCenter in a "development scenario" as well (e.g. when running an Xamarin iOS app via Visual Studio in either an "device" or "simulator" scenario). From what I have been able to work out, you can do this but it was not clear to me initially that this was possible and if any special steps were required. This is important because programmers need to know not just how to WRITE their App Center diagnostic logic but also need to know how to be able to TEST their diagnostic logic somehow and doing it in a live App Center environment appears to be the only way to do so. The article should therefore explicitly state if such a scenario is supported, whether there are any limitations with this scenario (e.g. latency) and whether any special steps are required to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8e7a19-5fba-7ed3-b28e-849c56095fb3
* Version Independent ID: 296dd414-cbd7-b3c7-a08b-0a68b56c10a5
* Content: [Enabling Diagnostics in an App - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/enabling-diagnostics)
* Content Source: [docs/diagnostics/enabling-diagnostics.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/enabling-diagnostics.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by jwargo** [comment]
@bogan I'll pass on the feedback, but I'm not certain this really needs to be clarified. 

When you add the SDK to an app, we start collecting data (unless you deliberately disable the SDK) - no matter where the app runs. You don't need any special environment for us to do the work we promised you we'd do - we just do it.

**Comment by jwargo** [comment]
@bogan the PM made a clarifying note in the docs. Thanks for suggesting it.
