### ISSUE TITLE
Unable to access Environment Variable

### ISSUE THREAD

**Issue by johnxy84** [MicrosoftDocs/appcenter-docs#487]
I'm using the pre-build script on Android to access my secret but I get '***' when I'm reading and echoing the environment variable. It's just a string within my app so no easy way to know if it worked. Are there extra things to consider when setting and reading envs? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f3af3f-ef07-8896-4b3c-05cef163b51a
* Version Independent ID: b4b1f6a4-5975-358b-1cf4-f7b10a2245cd
* Content: [Environment Variables - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/#feedback)
* Content Source: [docs/build/custom/variables/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/variables/index.md)
* Service: **mobile-center**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by jwargo** [comment]
@johnxy84 There's nothing special that I know of - we're just reading the environment variables from the build system. If this isn't working for you, you're better off asking the support team. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by dennispan** [comment]
@johnxy84 They are intentionally masked in the logs because they are "secret" variables. Any occurrence of the same value are masked in the build logs. To validate it, a possible workaround would be to echo a substring of it.

**Comment by johnxy84** [comment]
Thanks Dennis. I outputted it within my app and confirmed it actually it's there.
________________________________
