### ISSUE TITLE
Accessing in Xcode

### ISSUE THREAD

**Issue by philihp** [MicrosoftDocs/appcenter-docs#488]
How can these be accessed in Xcode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f3af3f-ef07-8896-4b3c-05cef163b51a
* Version Independent ID: b4b1f6a4-5975-358b-1cf4-f7b10a2245cd
* Content: [Environment Variables - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/)
* Content Source: [docs/build/custom/variables/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/variables/index.md)
* Service: **mobile-center**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by philihp** [comment]
To add some clarity here, I have two branches, one for `staging` and one for `release`, each of which has an environment variable giving it a `CODEPUSH_KEY`.

When I add a build step that does a `printenv` command to list all the variables, I see it showing up as `USER-DEFINED_CODEPUSH_KEY`, but environment variables allowed to have a dash in them, so printing this results in printing the value of $USER followed by `-DEFINED_CODEPUSH_KEY`... so `vsts-DEFINED_CODEPUSH_KEY`.

Is the `USER-DEFINED_` prefix being added by Appcenter? Is there a way around this?

**Comment by jwargo** [comment]
@philihp I'll ask someone on the build team to respond, but you should probably just ask support for help.  The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs.  If feels like a doc update would help here, but we can do that after you resolve your issue.

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by nilofer** [comment]
@philihp the ```USER-DEFINED_``` prefix is added by App Center when you add an environment variable when configuring the branch. There isn't a way around this. If you need still need more specific help, please reach out to our support via the blue bubble in the App Center portal.

**Comment by philihp** [comment]
@nrajpurkar can that prefix be changed to `USER_DEFINED_` for reasons in https://unix.stackexchange.com/questions/23659/can-shell-variable-include-character/23714#23714? This would be a breaking change, but I don't imagine they're very useful with that dash.

**Comment by dennispan** [comment]
@philihp If you access the variables in the places documented here: https://docs.microsoft.com/en-us/appcenter/build/custom/variables/#access-the-variables , then `USER-DEFINED_` prefix is not needed. To access them elsewhere, unfortunately there is currently no workaround. I'd encourage adding a new feature request here: https://github.com/Microsoft/appcenter

**Comment by tonyarnold** [comment]
Why is this closed? The issue isn't resolved, and there's no workaround?

**Comment by dennispan** [comment]
@tonyarnold The environment variables configured in App Center Build are currently specifically designed to be used in places documented here: https://docs.microsoft.com/en-us/appcenter/build/custom/variables/#access-the-variables, where you can access them without the `USER-DEFINED_` prefix. This is achieved by storing the variables with `USER-DEFINED_` prefix, and then remove the prefix when we make them available at the places described in the doc. 

Accessing the variables outside of those documented place are currently unsupported. Directly using `USER-DEFINED_xxx` really wasn't our intention. That said, I would definitely be open to hear what you are trying to solve (e.g. where you are trying to access the variables), and see what we can do.

**Comment by tonyarnold** [comment]
Thanks for the info, @DennisPan. 

I have components of my Xcode build that I only wish to run in release builds. To date, I’ve been doing that using environment variables that I watch for in build phase scripts. 

I also use them to pass a password to lock/unlock a bundled Keychain with build secrets in it. 

I really need these available during the Xcode build - I can’t make this work via pre/post build scripts.

**Comment by dennispan** [comment]
@tonyarnold Thanks for the quick reply! Let's move this discussion to https://github.com/microsoft/appcenter/issues/161? Would be great to consolidate feedbacks on this in one place

**Comment by tonyarnold** [comment]
Actually, I take that back. I can think of a workaround for the release components. Not sure what to do about the bundled keychain though.
