### ISSUE TITLE
Appcenter upload API step d) not working ("Cannot PATCH")

### ISSUE THREAD

**Issue by jpage4500** [MicrosoftDocs/appcenter-docs#489]
I'm trying to write a shell script to build and upload our app to AppCenter. I've done this for HockeyApp but apparently the same upload API doesn't work with AppCenter.

I'm following the guide here: https://docs.microsoft.com/en-us/appcenter/distribution/uploading#uploading-using-the-apis

My curl commands worked for steps a - c (getting a URL, uploading the apk, then 'commiting' the release). But, step d) fails with this error:

```
JSON:     { "destination_name": "testing", "release_notes": "testing 1 3 4" }
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot PATCH /</pre>
</body>
</html>
```

Also, while it seemed like the upload itself worked - I never see the app show up in AppCenter console or on a phone with HockeyApp installed.

Any ideas/suggestions?

The old hockeyapp single API call was so much easier!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#feedback)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by jwargo** [comment]
@jpage4500 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
