### ISSUE TITLE
Documentation of import incorrect

### ISSUE THREAD

**Issue by bnfrnz** [MicrosoftDocs/appcenter-docs#49]
`import AppCenter from 'appcenter';`
I don't believe this import can work with the current version of the Cordova SDK, unless I'm missing something...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b907baa-5e3a-da69-a50b-2eb46346a1c8
* Version Independent ID: 74049b61-a973-d240-728a-e725d9383599
* [Content](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/cordova)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/other-apis/cordova.md)
* Service: vs-appcenter

**Comment by Zakeelm** [comment]
@elamalani I think you may be able to help with this!

**Comment by bmourat** [comment]
@elamalani this is correct, we don't need to import anything to use SDK in Cordova

**Comment by bnfrnz** [comment]
I'm sorry, I didn't mean to cause confusion here with my comment. I should mention that I'm writing typescript, not javascript.

![screen shot 2018-03-21 at 20 47 17](https://user-images.githubusercontent.com/26401091/37710754-90865aa6-2d49-11e8-96f0-795aa41651fb.png)

The import suggested [in the docs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/cordova) does not work because the module is not located there. Or am I missing something?

I'm currently just doing this so ts doesn't complain:
`analytics = window.AppCenter.Analytics;`

...which is not a problem really

**Comment by bmourat** [comment]
@bnfrnz 
Oh, I see. Our support for typescript is not at its best for now) And the only workaround is the one that you pointed out. We should add definitions for our modules for better typescript support!

**Comment by elamalani** [comment]
@bnfrnz Thanks for your feedback. We will change the docs based on your feedback. 
https://github.com/MicrosoftDocs/appcenter-docs-pr/pull/549
