### ISSUE TITLE
The setting "Build this branch on every push" doesnt trigger automated build

### ISSUE THREAD

**Issue by jeevacodepro** [MicrosoftDocs/appcenter-docs#491]
As per the documentation "The default setting for build frequency is Build this branch on every push. Every time you push code to a configured branch, a build will automatically begin. You can enable this continuous integration feature or opt to manually choose when builds run."

Ideally when a commit is made on a branch we would expect a build triggered but in my case I need to manually trigger the build irrespective of the above settings. 
The app we are trying to build is xamarin android app. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8372996a-f469-d3f8-90e4-4231c1da7e25
* Version Independent ID: 629db8d3-f349-69e8-b7cc-c0bd3a346bdd
* Content: [Build Sample Android App on App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/quickstarts/android/build)
* Content Source: [docs/quickstarts/android/build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/quickstarts/android/build.md)
* Service: **vs-appcenter**
* GitHub Login: @sshibu
* Microsoft Alias: **t-shshib**

**Comment by jwargo** [comment]
@jeevaeastpoint It sounds like this isn't working as expected for you, so I suggest you reach out to our support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
