### ISSUE TITLE
Crashes Webhook on Slack is pretty minimal

### ISSUE THREAD

**Issue by zaltzy** [MicrosoftDocs/appcenter-docs#493]
Are there any plans on enhancing it (The HockeyApp Crashes webhook was way more descriptive).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79d5a18-b4d0-a8c4-b482-d79284c82ad4
* Version Independent ID: 8dff2b5d-ae26-5f4a-0f56-b19ac446fcf0
* Content: [App Center Webhooks Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/webhooks/#feedback)
* Content Source: [docs/dashboard/webhooks/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/webhooks/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@zaltzy are you suggesting a better example?  You pretty much do whatever you want with the webhook, we're just trying to get you started. I've asked the PM team to respond.

**Comment by zaltzy** [comment]
I can't really do a lot with the Webhook when it comes to Slack - in order to do that I need to change the JSON on the POST that's being sent, and I can't seem to find any documentation on how to do that in App Center...

**Comment by jwargo** [comment]
@zaltzy I don't think you can change the JSON that's sent. You simply get a webhook URL and configure App Center to use it - that's how I understand this works. We send a crashes package and Slack renders it. I'm not an expert, but that's what the documentation tells me.

**Comment by jwargo** [comment]
@zaltzy I just double-checked and what I said above is true. You configure the webhook URL and we send the data we want. We could, and probably should, document the payloads we send based on the event type, that could be useful (what do you think). 

If you want to manipulate what's sent to Slack, you could use something like Azure Functions, Microsoft Flow, or even IFTT to proxy the hook, manipulate it then pass it on to the target system.
