### ISSUE TITLE
Push notifications not work on Xamarin.Forms Android device (Android 8.0 or higher Version) when app is in foreground

### ISSUE THREAD

**Issue by differenz-system** [MicrosoftDocs/appcenter-docs#494]
Push notifications not work on Xamarin.Forms Android device (Android 8.0 or higher Version) when app is in foreground.
All working good in lower then Android 8.0 version. but its not work in Android 8.0 or higher Version.

**Comment by jwargo** [comment]
@differenz-system The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
