### ISSUE TITLE
Scroll much?

### ISSUE THREAD

**Issue by GiorgioG** [MicrosoftDocs/appcenter-docs#496]
This page might be a tad long and useless.  Make it searchable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c64c24-c463-0383-84ca-35465cd40f47
* Version Independent ID: 391d0c7a-f6e5-3269-c616-e83266050331
* Content: [Devices Available - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/devices)
* Content Source: [docs/test-cloud/devices.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/devices.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@GiorgioG to search it, press ctrl-F (Windows) or command-F (macOS) and type the search term you're looking for.  It's a docs page, so there's no other way to search this content. We added this to document the device list, when you're in the product and building device groups, you can use search to find the devices in the catalog more easily.

**Comment by sheodesayali** [comment]
Does the list of devices immediately be updated when there is a new OS version in android or iOS?
Does appcenter send out any notification indicating that a new version of OS is available to so testing can be done on it?

**Comment by Oddj0b** [comment]
@sheodesayali we update it weekly at the moment. We've been trying to find a good channel for sending out information about new devices. I would like to hear your suggestion about what format it should have?

**Comment by tamil12345t** [comment]
does the list of IOS devices available for actual testing?i tried to create a new device set which will have only IOS devices,but when i search for iphone device to add ,i can't able to find any iphone devices?
