### ISSUE TITLE
Crashes.GetErrorAttachments doesn't upload data, not documented

### ISSUE THREAD

**Issue by dstulic** [MicrosoftDocs/appcenter-docs#497]
1)
Crashes.GetErrorAttachments - ErrorAttachmentLog.AttachmentWithText does not upload data.
I'm providing correct file path to the file, but the web portal only shows the "key".
Is there a functional example that actually proves that this functionality works?
2)
The documentation is really slim and could use additional details for these methods. For example:
ErrorAttachmentLog.AttachmentWithBinary - what are the allowed values for contentType? contentType should be an enum instead.
3) 
ErrorAttachmentLog.AttachmentWithText - should not require a file. That should be in the ErrorAttachmentLog.AttachmentWithTextFile.
Instead, ErrorAttachmentLog.AttachmentWithText should take a dictionary style Key-Value pairs, or an actual Dictionary<string,string>

While it is nice to have ability to upload a picture, in practice what we want is to tag crashes with data that is relevant, so for example: 
* unique app run id as a foreign key in the non MS hosted analytics DB; 
* app version string; 
* string representation of unique app state that would help track down the issue.
Saving this data to disc in a text file so that Crashes engine can read text file is very impractical; which is why passing strings to ErrorAttachmentLog is much nicer.

**Comment by jwargo** [comment]
@dstulic I'll have the PM team take a look. In the mean time, if you're having trouble getting something to work, just reach out to our support team, they'll help you out. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by dstulic** [comment]
@jwargo I would, but it takes them a day to respond and quality of response is really low... :/

**Comment by jwargo** [comment]
@dstulic well, that's the only way to get support. The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. I've asked the PM team to take a look at your questions and address any potential docs issues.

**Comment by dstulic** [comment]
@jwargo i understand your point of view, and I am talking to support team as well. So while that is slowly moving, I decided to ask you to improve on documentation. Specifically, I've asked you to:
1) provide a working example of **AttachmentWithText**
2) provide information for ** contentType** in **AttachmentWithBinary**
3) and suggested to add a string key value pairs as an attachment; as opposed to files. Here I provided you with a real world example of what I would like to upload: unique app run id as a foreign key in the non MS hosted analytics DB, and app version - both as strings.
These are the needs of my project, which is currently published to 100K+ users. I suspect that there will be other developers that have similar needs. My hope is that I can help you improve your service including documentation aspects, before many other developers jump in to use it.

**Comment by winnie** [comment]
Hi @dstulic,

Thanks for your feedback! I plan to improve our documentation this week so stay tuned :) It's really helpful to hear this kind of feedback directly from our users and I appreciate you taking the time to write this up.

**Comment by elamalani** [comment]
@dstulic Here is the documentation for AttachmentWithText  API - https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin#add-attachments-to-a-crash-report 

We support all the binary content like png, jpeg, gif, zip, doc etc. for AttachmentWithBinary API.

**Comment by jwargo** [comment]
@dstulic it's been 18 days since the last response, so I'm going to close this issue.

**Comment by dsharkou** [comment]
@dstulic Have you fixed the issue? I'm facing the same issue right now and I'm really interested in working example.
Could you please post it here or describe whether file should be located?

**Comment by dsharkou** [comment]
I've found an answer.
First of all I don't know how to use `AttachmentWithText` (facing the same issue right now, so I'm really interested in working example for it) but after reading https://www.respawnsive.com/playground-part-3-catch-it-trace-it-log-it-and-upload-it I realised I'm able to use `AttachmentWithBinary` and just send bytes of the file.
I hope it'll help the others
