### ISSUE TITLE
Adding an AppCenter connection with a YAML build pipeline

### ISSUE THREAD

**Issue by eebart** [MicrosoftDocs/appcenter-docs#498]
How do I manage the AppCenter Distribution task within a YAML-based build pipeline. I am unable to convert to a visual build pipeline, and cannot figure out specifically how to set up the App Center Connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28aa9747-f64a-d886-487d-8ebb97d717b8
* Version Independent ID: 0c7edbb7-4bf7-f66c-c8a7-275308365f27
* Content: [Deploy Azure DevOps Builds with App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/vsts-deploy#feedback)
* Content Source: [docs/distribution/vsts-deploy.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/vsts-deploy.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by jwargo** [comment]
@eebart The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
