### ISSUE TITLE
App Center API Swagger (In Preview)

### ISSUE THREAD

**Issue by anitconsultantllc** [MicrosoftDocs/appcenter-docs#499]
I'm looking specifically at the "PUSH" section of the API for push notifications.  Most of these API endpoints are returning...

{"message":"Forbidden","code":"Forbidden"}

...after authenticating myself at the top.  Are these working yet and just turned off or am I missing something in utilizing this swagger doc?  

DEVELOPER COMMAND PROMPT OUTPUT
-----------------------------------------------------
C:\WINDOWS\system32>curl -X POST "https://api.appcenter.ms/v0.1/apps/itzzi-18ep-39/Axos_Agent_IOSMobileUI/push/notifications" -H "accept: application/json" -H "X-API-Token: {MY API TOKEN WAS PLACED HERE, EXCLUDING BRACES}" -H "Content-Type: application/json" -d "{ \"notification_target\": { \"type\": \"string\" }, \"notification_content\": { \"name\": \"Testing 1 2 3\", \"title\": \"Hello There\", \"body\": \"I'm hungry now.\", \"custom_data\": { \"additionalProp1\": \"string\", \"additionalProp2\": \"string\", \"additionalProp3\": \"string\" } }}"
{"message":"Forbidden","code":"Forbidden"}
C:\WINDOWS\system32>

**Comment by jwargo** [comment]
@anitconsultantllc Sorry about that - the Swagger isn't properly showing the options you need to use. We're working on an update to fix this. this is where it's likely failing: `"notification_target": { "type": "string" }` you must provide an actual type there. here's an example: https://docs.microsoft.com/en-us/appcenter/push/rest-api#send-notifications-to-device-ids.

**Comment by stankovski** [comment]
Try sending a push via the AppCenter portal with Developer Tools enabled (F12). The portal calls the same API. This way you will be able to see the exact payload, check the app URL, and verify that your user has access to perform this operation.

**Comment by jwargo** [comment]
@anitconsultantllc We're doing an update to fix this.

**Comment by anton-matsyshyn** [comment]
Hi
I'm trying to delete all notification config in appcenter, but i get 403 Frorbiden
What I do wrong?
(I got 202, when I using POST push/notification with same token; I have full acces)
https://ibb.co/Dt0DfqF

**Comment by jwargo** [comment]
@MatsyshynAnton The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
