### ISSUE TITLE
How to upload Symbols for crash reporting

### ISSUE THREAD

**Issue by erwan-lcs** [MicrosoftDocs/appcenter-docs#50]
How does one " Create a ZIP file for the dSYM package on your Mac. " ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663b3972-5d13-f787-05c6-45f0d49127ef
* Version Independent ID: 1aa13690-4428-163d-4cb4-f8fecad0665e
* [Content](https://docs.microsoft.com/en-us/appcenter/crashes/ios)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/crashes/ios.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@erwan-lcs The comments section is for providing comments or suggested edits for the App Center docs. If you have a question, please use the chat option in the bottom-left corner of the App Center dashboard, we have a dedicated team of support resources monitoring chat for questions.

**Comment by Soph** [comment]
@erwan-lcs right click the dsym in Finder and then there should be an option "compress". That will give you a zip file you can then use for uploading.
