### ISSUE TITLE
This seems cool 

### ISSUE THREAD

**Issue by kirill-dev-pro** [MicrosoftDocs/appcenter-docs#501]
But how about Expo support for react-native?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#feedback)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by jwargo** [comment]
@Zmeu213 what specifically are you looking for? Can you be more specific?

**Comment by kirill-dev-pro** [comment]
@jwargo Sure, I was looking for docs related to connecting react-native app to app center. Current doc page describes what to do with plain react-native application but it doesnt work with [Expo](https://expo.io). So I was asking is there are plans for adding more information about this?

**Comment by jwargo** [comment]
@Zmeu213 but what would you want to be able to do with Expo in App Center?  Expo is a runtime container, so your react native app isn't an executable binary we can work with. What are you trying to do that you can't do today?

**Comment by kirill-dev-pro** [comment]
@jwargo well, my motivation was to find a way to make auto test pipeline for different devices and collect bugreports and analytics from app. I thought app center was made for this

**Comment by jwargo** [comment]
@Zmeu213 it is. I'm just not sure how to do that with Expo as expo's the app, not the React Native app.  I don't have enough experience with Expo to know how you'd add third-party SDKs to the Expo runtime. I'll ask the PM to respond.

**Comment by annakocheshkova** [comment]
I saw several people working with expo.

**Comment by annakocheshkova** [comment]
@Zmeu213 sorry for the previous incorrect response. Unfortunately, we have no official support of Expo so you have to eject/detach Expo before linking the SDK.

**Comment by kirill-dev-pro** [comment]
@annakocheshkova but is there any plans of adding such support in the future or this seems impossible or unnecessary?

**Comment by annakocheshkova** [comment]
@Zmeu213 no, unfortunately that's inpossible since we use the native code.

**Comment by kirill-dev-pro** [comment]
Okay, thanks for response
