### ISSUE TITLE
Value of ${applicationId} ?

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/appcenter-docs#503]
Whats the value of `${applicationId} `; if I enter the App Id from AppCenter it gives error in build since it contains `"-" `
Tried putting App Id ie `mobilesdk_app_id` from firebase but it contains `":" ` ; that errors too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed528dcd-ecaf-697e-c64a-30651d26ff3d
* Version Independent ID: 1e92bbb4-5800-6d31-51ee-c6d5864801d1
* Content: [App Center Push for Xamarin.Android Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-android#feedback)
* Content Source: [docs/sdk/push/xamarin-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by smartprogrammer93** [comment]
I left it as is. it worked like a charm :p

**Comment by jwargo** [comment]
@pmahend1 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

I'm curious whether you included the quotation marks, you didn't provide an example of what you did.

**Comment by guperrot** [comment]
You have to use `${applicationId}` as is and not replace it. The build system will replace it for you (with the package name).

**Comment by nguyenthanhliemfc** [comment]
Where I can get ${applicationId}. From AppCenter or Cloud Messing Firebase?

**Comment by nguyenthanhliemfc** [comment]
I think ${applicationId} is Android App Package!
