### ISSUE TITLE
No Header

### ISSUE THREAD

**Issue by c-lamont** [MicrosoftDocs/appcenter-docs#506]
There is no information on what to do with the API Token.
I believe the API Token needs to be set as a header, is that correct?
If so what is the Key?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aadf839d-04fb-8d6e-dd5d-57a79c1d0914
* Version Independent ID: ea1d2e77-e3dd-19c7-9abd-ecd8f156a00c
* Content: [Using the Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/rest-api)
* Content Source: [docs/push/rest-api.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/rest-api.md)
* Service: **vs-appcenter**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@c-lamont it does and I updated the docs recently to show that, but I don't see it.

**Comment by jwargo** [comment]
@c-lamont aaah, here it is: https://docs.microsoft.com/en-us/appcenter/api-docs/index#using-an-api-token-in-an-api-request
