### ISSUE TITLE
Question - Plans to support Detox?

### ISSUE THREAD

**Issue by azamatsmith** [MicrosoftDocs/appcenter-docs#507]
Just curious if there are any plans to support [Detox](https://github.com/wix/Detox) for end-to-end tests? 

Thanks!

**Comment by jwargo** [comment]
@azamatsmith The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

The best place for feature requests is to send them through support (blue chat button in the lower-right corner of every App Center page) or here: https://github.com/Microsoft/appcenter.
