### ISSUE TITLE
Build Phases Shell Script.

### ISSUE THREAD

**Issue by potatowave** [MicrosoftDocs/appcenter-docs#508]
For me with React Native in xcode 10, I had to modify the script as so:

export NODE_BINARY="'node --max_old_space_size=8192' ../node_modules/react-native/scripts/react-native-xcode.sh"

Note the addition of double quotes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6826cbd3-5ac7-94f7-6708-5f9c7f9a8d5a
* Version Independent ID: 5e5287a4-d3f0-70f9-0f1f-c0f6b8ab8938
* Content: [App Center Build Code React Native Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/react-native#feedback)
* Content Source: [docs/build/troubleshooting/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/troubleshooting/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by jwargo** [comment]
@potatowave thanks, I'll have the PM take a look at making an update. @nrajpurkar

**Comment by nilofer** [comment]
@potatowave thanks for the catch here. I'll update the docs to include this difference for RN and Xcode 10.
