### ISSUE TITLE
Xamarin.Android: NetworkManagementSocketTagger

### ISSUE THREAD

**Issue by Fitch24** [MicrosoftDocs/appcenter-docs#509]
Hi.
I see a lot of errors in the log when using the AppCenter SDK.
When I call `AppCenter.Start("********-****-****-****-************", typeof(Analytics), typeof(Crashes))`, then I receive these messages in the log:

> I/qtaguid ( 7914): Tagging socket 62 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(62, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Tagging socket 64 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(64, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 69 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(69) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 69 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(69, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 62 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(62) failed with errno -13
> I/qtaguid ( 7914): Tagging socket 70 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7914): tagSocketFd(70, -667034599, -1) failed with errno-13
> I/qtaguid ( 7914): Untagging socket 64 failed errno=-13
> W/NetworkManagementSocketTagger( 7914): untagSocket(64) failed with errno -13

When I call `Analytics.TrackEvent("SomeEvent")`, then I again see these messages in the log:

> I/qtaguid ( 7480): Tagging socket 74 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7480): tagSocketFd(74, -667034599, -1) failed with errno-13
> I/qtaguid ( 7480): Tagging socket 77 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7480): tagSocketFd(77, -667034599, -1) failed with errno-13
> I/qtaguid ( 7480): Untagging socket 77 failed errno=-13
> W/NetworkManagementSocketTagger( 7480): untagSocket(77) failed with errno -13
> I/qtaguid ( 7480): Tagging socket 77 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7480): tagSocketFd(77, -667034599, -1) failed with errno-13
> I/qtaguid ( 7480): Untagging socket 77 failed errno=-13
> W/NetworkManagementSocketTagger( 7480): untagSocket(77) failed with errno -13
> I/qtaguid ( 7480): Tagging socket 77 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7480): tagSocketFd(77, -667034599, -1) failed with errno-13
> I/qtaguid ( 7480): Untagging socket 77 failed errno=-13
> W/NetworkManagementSocketTagger( 7480): untagSocket(77) failed with errno -13
> I/qtaguid ( 7480): Tagging socket 77 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7480): tagSocketFd(77, -667034599, -1) failed with errno-13
> I/qtaguid ( 7480): Untagging socket 77 failed errno=-13
> W/NetworkManagementSocketTagger( 7480): untagSocket(77) failed with errno -13
> I/qtaguid ( 7480): Tagging socket 77 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7480): tagSocketFd(77, -667034599, -1) failed with errno-13
> I/qtaguid ( 7480): Untagging socket 77 failed errno=-13
> W/NetworkManagementSocketTagger( 7480): untagSocket(77) failed with errno -13
> I/qtaguid ( 7480): Tagging socket 77 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7480): tagSocketFd(77, -667034599, -1) failed with errno-13
> I/qtaguid ( 7480): Untagging socket 77 failed errno=-13
> W/NetworkManagementSocketTagger( 7480): untagSocket(77) failed with errno -13
> I/qtaguid ( 7480): Tagging socket 77 with tag d83ddc1900000000(-667034599) for uid -1 failed errno=-13
> I/NetworkManagementSocketTagger( 7480): tagSocketFd(77, -667034599, -1) failed with errno-13
> I/qtaguid ( 7480): Untagging socket 74 failed errno=-13
> W/NetworkManagementSocketTagger( 7480): untagSocket(74) failed with errno -13

The app works fine. No crashes, no errors (except these mesagges in log), events are tracked normally. What is the reason for these messages and how to get rid of them?

MS VS Community v15.9.10
Xamarin.Android.SDK v9.1,7.0
Microsoft.AppCenter.Analytics v1.14.0
Device Android 4.4.2 (NoxPlayer v6.0.9.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d72f6fe-74d6-696e-e709-5f6d577c0a58
* Version Independent ID: b3d0ea8b-5a1f-bf71-7dc2-9685cf23c00b
* Content: [Get Started with Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/Xamarin)
* Content Source: [docs/sdk/getting-started/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@Fitch24 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
