### ISSUE TITLE
Long build time for monolithic repo due to nuget restore *.sln

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#51]
My Xamarin.Android app lives in a monolithic repo in github alongside other solution files (.sln). Due to appcenter's build process, nuget packages for all solutions are restored causing my build time to increase unnecessarily. This is due to `nuget restore *.sln` command that is run as part of the build process. It would be better if we could specify the solution to restore as part of the build configuration so that only the required packages are restored. This is similar to how VSTS works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf851143-9dbb-f208-f804-659694927d5b
* Version Independent ID: 8483c311-3184-2271-f6bb-d6bcfd682050
* [Content](https://docs.microsoft.com/en-us/appcenter/build/xamarin/android/)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/xamarin/android/index.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@tura08 Thanks for the feedback. This area of the docs site is for gathering feedback and suggested edits for the docs. If you want to provide feedback on the product or to ask questions about a particular feature, use the chat option in the lower-right corner of the App Center console. We have a dedicated team of support resources monitoring the chat area and passing feedback to the product's Program Managers.
