### ISSUE TITLE
Need more details on APIs

### ISSUE THREAD

**Issue by srikcgaa2** [MicrosoftDocs/appcenter-docs#510]
The above documentation does not clearly indicate what happens if there is no internet access when attempting to TrackEvents, are there any exceptions that can be thrown by the API, any internal retries, are there any configurable timeout or any other parameters apart from just the Start and TrackEvent methods.  If these are documented elsewhere, please include the links in this documentation.  If missing, please add detailed documentation to allow us to design appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae82f3e9-78b4-e743-1d4a-58dee115de10
* Version Independent ID: 50a18a62-58db-10eb-65d6-b0614d0553fc
* Content: [App Center Analytics for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/xamarin#custom-events)
* Content Source: [docs/sdk/analytics/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@srikcgaa2 as I understand it, but I'll let the SDK team correct me, analytics data is cached while the device doesn't have network connectivity, and delivered when it does. There's even a method you can use to set the cache size if I remember correctly. 

What do you feel the need to design around? We collect the data and deliver it as soon as we can. What else do you need to happen?

**Comment by srikcgaa2** [comment]
@jwargo, thanks for the response.  The information about caching was not mentioned in this documentation.  Also, the information on setting the cache size is also not mentioned anywhere.  These details would be helpful to plan on our integration.

Regarding design, since the API is of type void, there is no way for us to know if the event reached AppCenter or not and so we were planning to store is in app's local storage so that we can retry if required by sending the same event at a later time.  Scenarios like the app is attempting to send an event but the app is swipe killed which would cause the event to be lost OR does the SDK handle this as well across app relaunches from the cache it maintains?

Also, is the SDK sending it using a separate task OR it attempts to send it in the same thread that invoked the API?

As you can see, the answers to all the queries above are not evident with the existing documentation which is where there seems to be a need for enhancing the API to clarify negative scenarios thereby helping us to design accordingly.

**Comment by srikcgaa2** [comment]
By the way, I just looked at the previously closed issue #412 and that coincidentally talks about the same concern as I mentioned.  I just observed the closed topic now and since the same query has come up from two different people, it does look like there is a need to enhance the API, especially around the negative scenarios, internal retries the API does, threading details.

**Comment by MatkovIvan** [comment]
Hi @srikcgaa2,

> are there any exceptions that can be thrown by the API

No, our SDK doesn't throw any exceptions. If s, please report a bug to us.

> any internal retries

Yes, we have the retry logic for network and some server problems.

> are there any configurable timeout

No, there is no public API to configure it.

> any other parameters apart from just the Start and TrackEvent methods

You can configure [storage size](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#storage-size) in native SDKs (Android and iOS), but it isn't exposed to Xamarin SDK yet.

> there is no way for us to know if the event reached AppCenter or not

It's async operation and it can be sent even on next application launch, so we can't return the status.

> we were planning to store is in app's local storage so that we can retry if required by sending the same event at a later time

You don't need to do it. It's already implemented out of the box.

> Also, is the SDK sending it using a separate task OR it attempts to send it in the same thread that invoked the API?

The SDK uses a background thread for it. You can safely invoke the API from UI thread.

Overall, thanks for your questions, we'll add clarifications to the docs.

Best,
Ivan

**Comment by jwargo** [comment]
@srikcgaa2 it's been 7 days since the last comment, so I'm going to close this.
