### ISSUE TITLE
Multi target management iOS

### ISSUE THREAD

**Issue by hihelloluigi** [MicrosoftDocs/appcenter-docs#513]
Hi guys, I need some information on how to manage multi target in your fantastic platform that I discovered some days ago.

I split my app with different target to manage environments (Dev, Staging ecc..).
How can I add this different targets to my platform? Do I have to create different applications on platform or I can manage all target in only one?

For example in Firebase I can create a single project with different targets (that have different bundle ID).

Thank you a lot

**Comment by jwargo** [comment]
@mo3bius The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
