### ISSUE TITLE
Xamarin.Forms Analytics.TrackEvent to Not Use Location Services by Default

### ISSUE THREAD

**Issue by ant81584** [MicrosoftDocs/appcenter-docs#514]
Xamarin Analytics.TrackEvent seems to use Location Services by default to get the country code.  I would like this to be off by default and/or have option to turn it off.  Currently Apple is strict about using this and I don't need the location.

So now I have to add purpose string for the user to see. NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription. Even though I don't need this information about the user, I have to now prompt them.    

If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by jwargo** [comment]
@ant81584 I'm sorry, but I don't understand the purpose of the issue you submitted. I don't see any questions suggestions for the docs. Can you please clarify what you need/want?

**Comment by annakocheshkova** [comment]
Hi @ant81584. As I already answered you in Intercom, our SDK doesn't make any calls to `CLLocationManager`. You can make sure yourself: the only place where it is used is our test app, no usage in the SDK itself: https://github.com/Microsoft/AppCenter-SDK-Apple/search?q=CLLocationManager&unscoped_q=CLLocationManager

**Comment by ant81584** [comment]
I'm going to remove the Xamarin app center Analytics.TrackEvent code to see if this resolves the issue with Apple.  I only got this issue as soon as I started using it the xamarin forms Analytics.TrackEvent.

Sorry @annakocheshkova about the duplicate prompted question.  I will update once removing this event code helps the issue from apple sees.

**Comment by annakocheshkova** [comment]
@ant81584 feel free to remove App Center packages completely and see if the warning goes away. I will close the issue here, lets keep track of this issue in Intercom.
