### ISSUE TITLE
What are the advantages of using App Center for push notifications

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/appcenter-docs#515]
What are the advantages of using notifications from App Center?

I have to create project in **FCM** console, **GoogleJson** file, need to add firebase **plugins** in my project. 
So what is the role of app center?

**Comment by jwargo** [comment]
@arvindrajachourasiya this doesn't feel like a question or comment about the docs, but I'll give a shot at answering. To build your own push service, you must do all those things you listed PLUS build a system for managing the registration process, storing the device tokens, and sending the push notifications across multiple push services. App Center Push handles the stuff after the PLUS.

**Comment by arvindrajachourasiya** [comment]
@jwargo - I am sorry if my language was rude. Question was about docs only. This information supposed to be mentioned very first.
If I go on page appcenter doc page1 , it redirected me on page2, page2 redirected me on page3.. so on. finally you would end up with closing all tabs. 

As you mentioned  above, storing device token, If my app 1000 people installed is it storing those all token and if I want to send notifications to users(out of 1000) who has taken "Paid service". How? again it comes to our business logic(code).

Thank you.

**Comment by jwargo** [comment]
@arvindrajachourasiya your language wasn't rude, I just didn't see any questions or suggestions in your issue. Thanks for the advice, I'll update the docs with a benefits overview.
