### ISSUE TITLE
No SetUserId method in AppCenter

### ISSUE THREAD

**Issue by c-lamont** [MicrosoftDocs/appcenter-docs#517]
As far as I can see, there is no method `AppCenter.SetUserId("your-user-id");`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3bf0fbb-48d0-4f3c-c6d1-fd691426f00d
* Version Independent ID: 47948784-507a-28f3-bcf6-4cce8c950d2d
* Content: [Other Xamarin APIs - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin)
* Content Source: [docs/sdk/other-apis/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/other-apis/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@c-lamont I'm pretty sure it is, but I'll let the SDK team respond.

**Comment by elamalani** [comment]
@c-lamont Here is the API to set user id in Xamarin - https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#identify-users

**Comment by SmiffyKMc** [comment]
Still no method on the SDK to use SetUserId. If you try using it in the code, it does not exist. Using Xamarin.Android. How can I set this without the method?

**Comment by SmiffyKMc** [comment]
> As far as I can see, there is no method `AppCenter.SetUserId("your-user-id");`.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: c3bf0fbb-48d0-4f3c-c6d1-fd691426f00d
> * Version Independent ID: 47948784-507a-28f3-bcf6-4cce8c950d2d
> * Content: [Other Xamarin APIs - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin)
> * Content Source: [docs/sdk/other-apis/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/other-apis/xamarin.md)
> * Service: **vs-appcenter**
> * GitHub Login: @elamalani
> * Microsoft Alias: **emalani**

Have you been able to resolve this?

**Comment by SmiffyKMc** [comment]
An update to the API worked.
