### ISSUE TITLE
Using "environment variables" per environment

### ISSUE THREAD

**Issue by bsimser** [MicrosoftDocs/appcenter-docs#518]
The environment variables in App Centre don't seem to be very "environmental". For example let's say I have an API that I want to talk to so I enter the name of it and value. However that's only one name and value. Normally I would have the same variable set for a development, test, and production build of the app. There doesn't seem to be any way to specify a scope or build type or environment here, this just seems like a way to store configuration values outside of your codebase but no way to use multiple sets of them based on the type of build you're doing (see tools like Octopus for example that do this sort of thing through [scoping](https://octopus.com/docs/deployment-process/variables#scoping-variables))

**Comment by jwargo** [comment]
@bsimser The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. I don't see any questions or comments about the docs in your issue. 

It feels like you're trying to ask a question about how App Center works and the best way to get questions answered or to figure out how to make App Center work for your particular situation is to ask our support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by bsimser** [comment]
Thanks. Apologies as I was thinking this was the right place but you're right. I'll direct my question through premier services.

**Comment by jwargo** [comment]
@bsimser No need for that, just use the blue chat button on every App Center page - that connects you directly with our dedicated support team and the PM and Engineering teams are available there as well. Also, we recently started collecting customer feedback and feature requests here: https://github.com/Microsoft/appcenter.
