### ISSUE TITLE
Application not available in Microsoft Registration Portal

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#519]
After associating the app with store from VIsual Studio, the application does not appear in the Microsoft Registration Portal. It appears in the Microsoft Dev Center. Can you elaborate on how to do this. and what role of users can associate and see the app sin Dev center.

**Comment by jwargo** [comment]
@rjax87 this is the same topic posted here: https://github.com/Microsoft/appcenter/issues/275. This is not an issue related to Visual Studio App Center. This relates Visual Studio and the App Store, not Visual Studio App Center.
