### ISSUE TITLE
Most page actions open up a question box in Firefox asking if I want to save the password

### ISSUE THREAD

**Issue by Hoid** [MicrosoftDocs/appcenter-docs#52]
There is something wrong with this behavior. It asks me EVERY TIME I do something to save this password, never with a username. There is also no place to submit feedback for App Center within the App Center, so I have to come here to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06813350-a37b-a4a2-fdbc-a59caefb9f32
* Version Independent ID: 29787958-5b4e-efc2-2af5-2af0ee53216e
* [Content](https://docs.microsoft.com/en-us/appcenter/build/)
* [Content Source](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/index.md)
* Service: vs-appcenter

**Comment by jwargo** [comment]
@Hoid that's not true. On every page in App Center, there's a blue chat button in the lower-right corner. Click that and provide feedback and ask questions any time you want. We have a dedicated team of people monitoring that chat full time.
