### ISSUE TITLE
Disabling Carthage bootstrap

### ISSUE THREAD

**Issue by pipacs** [MicrosoftDocs/appcenter-docs#522]
We are using Carthage to pre-populate our Git repo with the dependencies. However App Center is forcing "carthage bootstrap" as an early build step.

Problem is, this step never succeeds as our dependencies are in-house, accessible from our intranet only.

Is there a way to disable the "carthage bootstrap" step?

**Comment by jwargo** [comment]
@pipacs The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
