### ISSUE TITLE
Is there an API to upload the mapping.txt file using curl or so?

### ISSUE THREAD

**Issue by Bassem-Samy** [MicrosoftDocs/appcenter-docs#523]
I couldn't find a REST API to upload the mapping.txt file, is it only done through the UI ? is there a way to use a REST Request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e9c7ee-7522-cc0a-7ff1-7748f93efa83
* Version Independent ID: 683bf206-d70c-192b-6f59-f03dd1f66885
* Content: [Android ProGuard - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-proguard#feedback)
* Content Source: [docs/diagnostics/Android-ProGuard.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/Android-ProGuard.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by winnie** [comment]
Hi @Bassem-Samy,

You can use the upload symbols API to upload the mapping.txt file. Instructions are [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/iOS-symbolication#app-center-api). Let me know if that works!
