### ISSUE TITLE
App not working on mobile

### ISSUE THREAD

**Issue by ravindra2010** [MicrosoftDocs/appcenter-docs#525]
I have created build successfully but the .apk generated by the build is not working on device after distribution. It showing error "application not installed". Please help if you have any idea abut this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcecd38a-7696-e7f8-853d-d3c12c0b050c
* Version Independent ID: abdba972-b2cd-6c73-83fe-bb1abaac190f
* Content: [Testing Android Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android#feedback)
* Content Source: [docs/distribution/testers/testing-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-android.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@ravindra2010 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
