### ISSUE TITLE
Incomplete results in error search endpoint

### ISSUE THREAD

**Issue by softwaresaiyajin** [MicrosoftDocs/appcenter-docs#527]
/errors/search endpoint only returns a maximum of 100 latest items no matter what the date range for timestamp filter is

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/#feedback)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@softwaresaiyajin I'll have the team take a look.

**Comment by winnie** [comment]
Hi @softwaresaiyajin,

This is expected behavior - our search API only returns a maximum of 100 results. Or are you saying the 100 results are the same regardless of the date range?

Thanks!

**Comment by softwaresaiyajin** [comment]
Hi @winnieli1208 ,

Yes, that's exactly the case. If I input the timestamp starting Mar 18 - Apr 18, I'm expecting all crashes within that specified date range will be returned. But the behaviour now returns just a maximum of 100 items. If I specify that page size to be 99, the first page will have 99 items, the second page will just have one item, and that's it.

**Comment by winnie** [comment]
@softwaresaiyajin this is expected, our search functionality returns a maximum of 100 items no matter what time range is specified. I understand this might not be ideal for many users and we are considering increasing this limit. Feel free to create a feature request in this repo so we can monitor community interest. Thanks!

**Comment by softwaresaiyajin** [comment]
Hi @winnieli1208 ,

Yes, I'd like to request this as feature. Please add feature label, I cannot modify the tags.

Thanks!

**Comment by jwargo** [comment]
@softwaresaiyajin we track feature requests here: https://github.com/Microsoft/appcenter. That way people can vote on them, etc.
