### ISSUE TITLE
Appcenter push: dynamic navigation based on custom data

### ISSUE THREAD

**Issue by SharbelWired** [MicrosoftDocs/appcenter-docs#528]
Hi everyone, I'm wondering if I could get some help using AppCenter push in my Xamarin Forms app that targets Android & iOS. 

Essentially, I've followed the instructions and I'm able to see the push notifications in my testing on Android.  I understand that there are different behaviors between foreground and background notifications and have stepped through via the debugger when the PushNotificationReceived event happens..

The issue I'm having is I cannot find a reliable way to isolate when a user is entering the app because they tapped on a notification when the app is not loaded.

In my App.xaml.cs, I have the following:
```
protected override async void OnInitialized()
        {
            
            InitializeComponent();
            Push.PushNotificationReceived += Push_PushNotificationReceived;

            
            AppCenter.Start("ios={ios ID}" +
                  "uwp={Your UWP App secret here};" +
                  "android={android ID}",
                  typeof(Analytics), typeof(Crashes), typeof(Push));

            await NavigationService.NavigateAsync("Splash"); // this is my splash screen that shows

        }

private async void Push_PushNotificationReceived(object sender, PushNotificationReceivedEventArgs e)
        {
            if (e.CustomData != null)
            {
                if (e.CustomData.ContainsKey("roundId"))
                {
                    string roundId = e.CustomData["roundId"];
                   //I want to navigate directly to this UI 
                    await NavigationService.NavigateAsync($"IconNavigationPage/HomeView/Round?roundId={roundId}");
                }
            }
        }
```

So, as you can see, under normal circumstances, the app will load the Splash view which does some loading, and redirects to a home view.  When the notification is received and the user has the app running in the background, on Android, it's working fine.  I changed my launch mode to SingleTop and added the following to my MainActivity.cs
```
protected override void OnNewIntent(Android.Content.Intent intent)
        {
            base.OnNewIntent(intent);
            Push.CheckLaunchedFromNotification(this, intent);
        }
```
The issue is, when the app is not running in the background, and I tap the notification, the Splash screen navigation call is called, then my navigation call in the PushNotificationReceived event.  This essentially causes the app to load the UI that is defined in the event, for a second, then Splash UI redirects happen.   This is due to the fact that OnInitialize() gets ran when the app is loaded from the Tap of the notification, when the app is not running in the background.

I have experimented in trying to implement the PushNotificationReceived event handler in the Android MainActivity.cs file, and I do see that this fires before the same PushNotificationReceived event handlers in the Shared project.   Unfortunately it runs *after* the call to the LoadApplication, so my shared project's OnInitialize() gets fired first (which has that navigation call to Splash)

I guess what I'm looking for is some guidance, or maybe a point to a tutorial, on how I can accomplish notifying the Shared project's OnInitialize not to do the standard navigation to Splash, but rather do the navigation necessary for the Push Notification instead.  I've search high and low, but all of tutorials / docs simply do a debug write to console proving that that the custom data that was passed is there, which I too can see, I cannot find anything that handles real-world use cases of a viable workflow to control navigation based on the tap of a notification.

Any help or guidance would be greatly appreciated.

Thank-you in advance.

**Comment by jwargo** [comment]
@SharbelWired I've asked the team to take a look at providing a recommendation.

**Comment by v-fekalu** [comment]
@SharbelWired Please, try next to resolve situation:
1. Try to set LaunchMode to SingleTask and see if it does required changes.
2. I was unable to find event OnInitialized in activity or app lifecycles. Can you please try OnCreate event instead of the OnInitialized?
3. Other way to accomplish task is to keep state somewhere in app, for example add some static property into App.xaml.cs like next:
```static public bool KeepPage { get; set; } = false;```
set it to `true` inside OnNewIntent, check it in `OnInitialized` and set back to false after:

        ```protected void Push_PushNotificationReceived(Object sender, PushNotificationReceivedEventArgs e) 
        {
			//...
            if (!KeepPage) {
                //...
				await NavigationService.NavigateAsync($"IconNavigationPage/HomeView/Round?roundId={roundId}");
				//...
                KeepPage = false;
            }
        }```

**Comment by SharbelWired** [comment]
@jwargo   I was able to do something similar to your suggestion in your item 3, but unfortunately the public variable in app.xaml.cs is set after the initial redirect.  I was able to use it a little later in the initial redirect to trap the redirect to the home UI.  It's not exactly ideal, but it'll work for now...

**Comment by jwargo** [comment]
@SharbelWired that was @v-fekalu who suggested that.

**Comment by jwargo** [comment]
@SharbelWired OK if I close this?

**Comment by SharbelWired** [comment]
Yes, it can be closed @jwargo
