### ISSUE TITLE
Lack of documentation for webhook JSON payloads

### ISSUE THREAD

**Issue by RyanThomas73** [MicrosoftDocs/appcenter-docs#529]
The documentation for appcenter webhooks has a single example payload for a build event. There do not appear to be any examples of the other payload types. We are investigating the possibility of using webhooks to post events to our own api. We're unable to develop the api endpoint without knowing the structure of the payload.

Additional Note: While documentation for the payload structure would be an important first step, an ideal solution would include test tools that support sending example payloads to urls for internal network facing api endpoints. This would allow us to develop and test the api endpoint before deploying it to an external/public facing location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79d5a18-b4d0-a8c4-b482-d79284c82ad4
* Version Independent ID: 8dff2b5d-ae26-5f4a-0f56-b19ac446fcf0
* Content: [App Center Webhooks Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/webhooks/#)
* Content Source: [docs/dashboard/webhooks/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/webhooks/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@RyanThomas73 I'll have the PM take a look at making an update.

**Comment by nilofer** [comment]
@amchew can you take a look at this please? Thanks!

**Comment by Tempest1000** [comment]
Hello, we are also looking at the ability to post events to our own api, specifically around crash events (when the crash group is created in AppCenter). We would also like to know the structure of the payload that is being sent to the webhook URL as @RyanThomas73 mentioned.

**Comment by amchew** [comment]
Hey @RyanThomas73 and @Tempest1000, thanks for reaching out! Apologies for the delayed response, was OOF. 

It sounds like the requirements are:
- publish structure of build, crash, distribute payload

with the goal for you post events to your API. 

Will update the doc by next week.

**Comment by daveokeeffe** [comment]
> Hey @RyanThomas73 and @Tempest1000, thanks for reaching out! Apologies for the delayed response, was OOF.
> 
> It sounds like the requirements are:
> 
> * publish structure of build, crash, distribute payload
> 
> with the goal for you post events to your API.
> 
> Will update the doc by next week.

Hi @amchew, any chance of getting these API samples?

**Comment by amchew** [comment]
Hey @daveokeeffe sorry for the delay. Will get them to you shortly.

**Comment by amchew** [comment]
Hey @daveokeeffe, @Tempest1000 and @RyanThomas73, I just made a PR to update our docs, you should see it in the next day or so. 

In the meantime, here are examples of the JSON webhook payload for:

1. Build

```JSON
{
  "app_name": "myFirstApp",
  "branch": "master",
  "build_status": "Succeeded",
  "build_id": "33",
  "build_link": "https://appcenter.ms/users/{user-id}/apps/{app-name}/build/branches/master/builds/33",
  "build_reason": "manual",
  "finish_time": "2018-06-14T23:59:05.2542221Z",
  "icon_link": "https://dl0tgz6ee3upo.cloudfront.net/production/apps/icons/000/590/821/original/0c9184328703e417a6a0df02c6b587f0.png",
  "notification_settings_link": "https://appcenter.ms/users/{user-id}/apps/{app-name}/settings/notifications",
  "os": "iOS",
  "start_time": "2018-06-14T23:57:03.4379381Z",
  "source_version": "55820a357ba26831f2eeb3be9973a4ef20618b73",
  "sent_at": "2018-06-14T23:59:08.4897604Z"
}
```
2. Crash

```JSON
{
  "id":"3698593379u",
  "name":"Activity.java line 6314",
  "reason":"android.util.SuperNotCalledException","url":"https://portal-server-core-integration.dev.avalanch.es/orgs/{org-id}/apps/{app-name}/crashes/errors/3698273379u",
  "app_display_name":"{app-name}",
  "app_platform":"Java",
  "app_version":"2.0.1(42)",
  "stack_trace":[],
  "affected_users":0,
  "crash_count":0,
  "sent_at":"2019-05-16T23:47:31.4881512Z",
  "app_id":"48573473-f069-4715-8bab-9ae42cec48b2"
}
```

3. Distribute

```JSON
{
  "app_name":"{app-name}",
  "app_display_name":"{app-display-name}",
  "release_id":"123",
  "platform":"Android",
  "uploaded_at":"2018-07-17T20:46:14Z",
  "fingerprint":"0abed1269e4ae3bf524e4cc7165f4f34",
  "release_notes":"Merge pull request #756 from Microsoft/fix/fix-transmission-target-selection\n\nFix regression in EventActivityUtil",
  "version":"74",
  "short_version":"1.7.0",
  "min_os":"4.0.3",
  "mandatory_update":true,
  "size":2634279,
  "provisioning_profile_name":null,
  "provisioning_profile_type":null,
  "bundle_identifier":"com.microsoft.appcenter.test.jcenter","install_link":"https://install.appcenter.ms/orgs/{org-name}/apps/{app-name}/releases/123?source=email",
  "icon_link":"https://rink.hockeyapp.net/api/2/apps/45d1d9f624924e4686447190345325f3?format=png","distribution_group_id":"1a5a0605-4b9c-4de2-9a35-t569456df0cc",
  "installable":true,
  "sent_at":"2019-05-16T23:20:08.7799314Z",
  "app_id":"f37c6194-9ac9-4504-be61-55re334r5649"
}
```
