### ISSUE TITLE
Build Scripts not running

### ISSUE THREAD

**Issue by luongs3** [MicrosoftDocs/appcenter-docs#53]
I add 2 files appcenter-post-clone.sh and appcenter-post-build.sh and some simple commands as `echo "post-clone"` into them in my project. And it seems that ms appcenter recognized them because in App center -> build -> build scripts, I saw post-clone and pre-build. But in the build output logs, no sign that indicate appcenter run my commands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca50588e-c8ad-2b8e-683f-bc5fc612dfe4
* Version Independent ID: 5d9513bd-d179-eaeb-96aa-06bd5ba0224f
* Content: [Build Scripts - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/index#feedback)
* Content Source: [docs/build/custom/scripts/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/scripts/index.md)
* Service: **vs-appcenter**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by dipree** [comment]
Hi, once added to your repo, in order to save the detected scripts to the build configuration, you have to hit the “Save” or “Save & Build” button in the build configuration.

We know it’s faily unintentional and will change the behaviour in the future.

It’s stated in the docs also:
> Once your build scripts have been detected for the first time or you moved them to a different location, make sure to save the branch configuration to apply the changes!

**Comment by jwargo** [comment]
@luongs3 The comments feature of the docs is designed to enable customers to suggest changes to the docs or ask clarifying questions about the docs. If you need help with the product, please login to the App Center dashboard and click the blue chat button in the lower-right corner of the page. Our dedicated support resources will answer any questions you have there.

**Comment by ButuzGOL** [comment]
I have an error Found index.ios.js for ReactNative index.
In my app i have index.js instead of index.ios.js is there any way to change ?

**Comment by dipree** [comment]
Please reach out through support, so we can better help you with your problem.

**Comment by jwargo** [comment]
@luongs3 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by amadeu01** [comment]
I guess it would be useful to show the image of where you should hit the "Save and build" button after alter the build script.
You could add the image on the [custom script documentation](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/)
Something like that.
<img width="813" alt="image" src="https://user-images.githubusercontent.com/11631092/40892417-553bfcf4-676d-11e8-8143-0bb835dae1e4.png">

**Comment by jwargo** [comment]
@amadeu01 thanks for the suggestion. We try to minimize the use of screen shots in the documentation for two reasons: we could change how this feature or dialog works at any time (and would have to update every screen shot when we did) also, when we translate the docs to other languages, the screenshots won't be in the target language.

**Comment by amadeu01** [comment]
I see.

@jwargo  I agree with you. Thanks for your time and response  😄

**Comment by markwilcox** [comment]
> Once your build scripts have been detected for the first time or you moved them to a different location, make sure to save the branch configuration to apply the changes!

Please update this to say "Every time you modify your build scripts save the branch configuration to apply the changes!".

I just wasted a couple of hours on this, modifying a pre-build script where it was running, but never running the new versions (in the same location) I pushed to the repository. It'd be better to paste the script in the build config if it's not going to automatically update from the repository. I suggest a change to the product so it works one way or the other.

**Comment by softlion** [comment]
Please put this in a yellow bloc on this page !!!

**Comment by softlion** [comment]
Ok it is on a purple note .... not enough visible. Or plz change the behavior to use it automatically asap.

**Comment by dipree** [comment]
We know that the behaviour is not ideal, however, it's documented. If you've any suggestions how to make it more clear in the documentation, please let us know.

**Comment by Crysis21** [comment]
God, I hate this thing. I spent my whole morning trying to figure out what the hell is happening. I use appcenter for a long time, so I didn't have time to read the docs again, but this behaviour was unexpected to me.

**Comment by jwargo** [comment]
@Crysis21 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. I do not see either in your comment.

If you're having trouble getting something to work - ask our support team for help. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by dipree** [comment]
@Crysis21 please consider submitting a feature request in our [public repo](https://github.com/microsoft/appcenter).

**Comment by bramski** [comment]
FFS this issue is a year and a half old and I am still discovering it.

"We know it’s faily unintentional and will change the behaviour in the future."
Your exact words @derpixeldan. Were you just baiting us?

**Comment by dipree** [comment]
@bramski no ETA was committed to, it's a known pain point though. I recommend commenting and upvoting the above [issue](https://github.com/microsoft/appcenter/issues/265).

**Comment by jwargo** [comment]
@bramski please refrain from using abusive language on this forum. This forum exists to enable our customers to ask questions or suggest updates to the documentation. If you'd like to propose a feature or submit a bug, please refer to the [App Center Repo](https://github.com/Microsoft/appcenter) and, as mentioned previously in this post, you can contact our dedicated support team at any time using the blue chat button in the bottom-right corner of any App Center page.

**Comment by Crysis21** [comment]
Guys, it took you more time to answer this issue, that it would've taken you to fix the docs. Or the real issue itself (which would've been quite nice). After all, some of us pay for app center.

**Comment by jwargo** [comment]
@Crysis21 OK, I assumed this was more about changing the behavior then updating the docs.  I'll work with @derpixeldan to update the docs on this.

**Comment by jwargo** [comment]
Done. Please stop the abuse. :-)

**Comment by mauriciopf** [comment]
Hi, I need help! I’m building an app in react native, and I added a appcenter-pre-build.sh next to the package.json and the project setting in app center says Build scripts as none. Why is this if I already have the bash file in my repo???

**Comment by jwargo** [comment]
@mauriciopf if you need help, please contact our dedicated support team - just click the blue chat button in the lower-right corner of any App Center portal page to connect directly with the team.

**Comment by stueynet** [comment]
> Hi, once added to your repo, in order to save the detected scripts to the build configuration, you have to hit the “Save” or “Save & Build” button in the build configuration.
> 
> We know it’s fairly unintentional and will change the behaviour in the future.
> 
> It’s stated in the docs also:
> 
> > Once your build scripts have been detected for the first time or you moved them to a different location, make sure to save the branch configuration to apply the changes!

Sorry but is now the future? Its 2 years later. This is quite problematic if you have an automated build pipeline. Is there any plan for this?

**Comment by wampa007** [comment]
Hello from further into the future...still not fixed in Dec 2021 :)
For all those questioning why the build process isn't picking up your added script, you just have to go to branch settings (currently a wrench icon), wait for it to load (verify it found your script, in my case under build app is shows 'post clone' with a checkmark).  and hit Save and Build.  I suppose that means you have to do this for every branch that has it...

**Comment by markwilcox** [comment]
It could be worse... you could be using Azure DevOps. :wink: (hint - do not use for mobile apps)

Although it's very raw and you have to manage a lot more of the build process yourself, GitHub Actions has been a lot more reliable for me for an automated build pipeline. If you have to pick one of the three Microsoft-owned options here I'd go with that one unless your project is very simple and likely to stay that way. Just relating personal experience here in case it helps anyone encountering this issue more than 3 years after I did!

**Comment by geoweir** [comment]
Still happening in Jan 2022.

**Comment by softlion** [comment]
> Still happening in Jan 2022.

The scripts are running fine. There is only one thing: each time you change a script's content, or add or remove a script, you MUST "edit" the build configuration then press "save" (or save and build). 
You may need to do that on multiple branch, as each branch has its own configuration.

From https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/ :
![image](https://user-images.githubusercontent.com/190756/148983182-8f92eda3-7a6a-4b9f-bab4-204dfa0a1751.png)

This apply for the script content too. Each time the content is changed, you must reapply.

**Comment by geoweir** [comment]
Agreed - scripts run when conditions are met.

But sometimes they are not and there is no warning, nothing in the UI to say the settings or script have changed and need saved. It happily reports the script is there, variables are setup and is exactly the same visually as all our other apps.

Except if you open a build log the pre build script stage is just missing. 

Why not run the stage and emit an error or warning at least?

Or better yet just run the script if it's in the source code? Why decide not to run it because it has changed? The reason we are doing a build is because something has changed.

**Comment by ThomasReyskens** [comment]
Also wasted several hours on this one 😓  Can the save also be triggered from the API?

Edit: found a temp solution: on each push I update the config..
Short snippet:

```bash
          echo "Fetching current config for picking up the build script"
          CFG_DATA=`curl -s "${APPCENTER_BASE_URL}/branches/${CURRENT_BRANCH}/config" -H "Content-Type: application/json" -H "X-API-Token: $APPCENTER_X_API_TOKEN" | jq '.toolsets.buildscripts = {"package.json":{"postClone": "appcenter-post-clone.sh"}}' -c`
          echo
          echo "Updating the build script: ${CFG_DATA}"
          curl -sX PUT -d "$CFG_DATA" "${APPCENTER_BASE_URL}/branches/${CURRENT_BRANCH}/config" -H "Content-Type: application/json" -H "X-API-Token: $APPCENTER_X_API_TOKEN"
          echo
          echo "Restarting the build"
          curl -sX POST "${APPCENTER_BASE_URL}/branches/${CURRENT_BRANCH}/builds" -H "Content-Type: application/json" -H "X-API-Token: $APPCENTER_X_API_TOKEN"
```
