### ISSUE TITLE
Confusion about time filters

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/appcenter-docs#535]
The time filters are mentioned only in the Active users section. Does it mean they are not available for engagement and device metrics?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9593966b-ff1f-fd2a-761d-a5fbd604570b
* Version Independent ID: ed34ddcd-2355-7b10-094e-9de27b5f38bc
* Content: [Understanding the App Center Overview Page - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/overview#feedback)
* Content Source: [docs/analytics/overview.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/overview.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by jwargo** [comment]
@julienshepherd I'm not sure, I'll ask the PM to respond.

**Comment by hamswan** [comment]
The Analytics Overview page shows the Engagement Metrics and this can be seen filtered for Last 7, 30, 60, 90 days.

The time filter apply to all the Metrics you see on the Overview page.

**Comment by jwargo** [comment]
@julienshepherd were you able to get it to work?
