### ISSUE TITLE
Event priority and persistence in Objective-C?

### ISSUE THREAD

**Issue by iiAtlas** [MicrosoftDocs/appcenter-docs#536]
It appears there is no way to set event priority and persistence (`MSFlagsPersistenceNormal`, `MSFlagsPersistenceCritical`) when using Objective C.  The "flags" option is missing from `[MSAnalytics trackEvent:withProperties:]`.  Is this correct?  Or is the documentation simply lacking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea43ae40-337d-83b4-8129-85ff1a8c6ede
* Version Independent ID: d37ccc38-a4bc-5368-9b58-8720995f8bc2
* Content: [App Center Analytics for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/ios#event-priority-and-persistence)
* Content Source: [docs/sdk/analytics/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@iiAtlas I'll ask the PM to respond. Also, please keep in mind that App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by iiAtlas** [comment]
Thanks! Sorry if this was the wrong place to comment..

**Comment by jwargo** [comment]
@iiAtlas No, it isn't, no worries. If the docs are lacking, this is the place to ask. I just pointed that out in case you were in a hurry for the answer as support is probably faster than a docs response.

**Comment by iiAtlas** [comment]
@jwargo Excellent!  Thank you for your wonderful support!

**Comment by elamalani** [comment]
@iiAtlas You can set event priority and persistence in Objective-C as well. Here is the doc link -
https://docs.microsoft.com/en-us/appcenter/sdk/analytics/ios#event-priority-and-persistence

**Comment by iiAtlas** [comment]
@elamalani The documentation you've provided (and which I commented on) is only showing Swift code.  The relevant method does not seem to exist in Objective-C!

**Comment by elamalani** [comment]
@iiAtlas You can switch the language to Objective-C by using the dropdown on the upper right of the docs page.  Here is the code snippet:

NSDictionary *properties = @{@"Category" : @"Music", @"FileName" : @"favorite.avi"};
[MSAnalytics trackEvent:@"Video clicked" withProperties:properties flags:MSFlagsPersistenceCritical];

// If you are using name only, you can pass nil as properties.

**Comment by iiAtlas** [comment]
Hi @elamalani , thanks for the tip on how to change the language -- that helps!  I was just going to comment on how the method `[MSAnalytics trackEvent: withProperties: flags:]` did not exist in the latest AppCenter SDK version, then I checked and noticed I was on `1.6.1` rather than the latest `1.14`.  I've since found the method.  

Thank you both!
