### ISSUE TITLE
Supported versions build machine details are horribly out of date compared to the referenced link

### ISSUE THREAD

**Issue by espoelstra** [MicrosoftDocs/appcenter-docs#537]
It states OS X 10.11.6 on this page but on the other page it shows 10.13 and 10.14 nodes are available (which happen to also be the details of the versions available in Azure DevOps).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc01291c-f6a0-4610-a27d-60718852390d
* Version Independent ID: 2b51b117-6b8c-f4d9-a2b2-43c891d20171
* Content: [Configure a Objective-C or Swift iOS build - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/first-build#feedback)
* Content Source: [docs/build/ios/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by nilofer** [comment]
@espoelstra you're correct, thanks for pointing this out. The detailed list of agent software is most update. I'll update the page that lists OS X 10.11.6
