### ISSUE TITLE
Can I run tests with appium written on Python with appium python-client ? If yes where is the documentation for that?

### ISSUE THREAD

**Issue by Veris-Mansi** [MicrosoftDocs/appcenter-docs#538]

**Comment by jwargo** [comment]
@Veris-Mansi I'm not sure I understand the question, the language you use for writing your Appium tests shouldn't change anything (or need special docs) but I've asked the PM to respond. 

Please keep in mind that App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by Oddj0b** [comment]
Sorry, we only support Appium with the Java flavor. I have asked for more details in your feature request on the Microsoft/appcenter repository.
