### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by tareq143** [MicrosoftDocs/appcenter-docs#54]
This is my 1st project. I need more help to keep my project secure and updated. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83a47f5b-505b-ab6b-6232-5e22e2318e10
* Version Independent ID: ff7978d9-3ce9-9c41-6142-644eb353edff
* Content: [App Center Analytics for UWP - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/uwp)
* Content Source: [docs/sdk/analytics/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @dhei
* Microsoft Alias: **dihei**

**Comment by dhei** [comment]
How can we help you? Do you have any issues or questions?

**Comment by jwargo** [comment]
@tareq143 The comments feature of the docs is designed to enable customers to suggest changes to the docs or ask clarifying questions about the docs. If you need help with the product, please login to the App Center dashboard and click the blue chat button in the lower-right corner of the page. Our dedicated support resources will answer any questions you have there.

**Comment by dparvin** [comment]
To get the country code automatically, you can use something like: AppCenter.SetCountryCode(RegionInfo.CurrentRegion.TwoLetterISORegionName);

**Comment by michael-hawker** [comment]
@dparvin can we get that code added to the docs? I had found some other code elsewhere that was incorrect for some scenarios.

Ah, right, I was reading somewhere that CurrentRegion may always return US? https://stackoverflow.com/questions/44312188/how-to-get-users-region-on-windows-10-uwp

**Comment by michael-hawker** [comment]
Tested on my VM, CurrentRegion returns US still when I change the Country/region in Settings.  `new Windows.Globalization.GeographicRegion().CodeTwoLetter` returns the proper result that I set in Region Settings.

**Comment by jwargo** [comment]
@michael-hawker I'll ask the team to take a look - Don't forget, it's a public repo, we're happy to take pull requests. :-)

**Comment by michael-hawker** [comment]
@jwargo good point, will do :) Buddy of mine pointed me to this commit in your samples which uses what I suggested as well:
https://github.com/Microsoft/AppCenter-SDK-DotNet/commit/46efe1f6a0832e7722a9273d43160c1cc6aa9825

**Comment by iamclement** [comment]
Hi there, the concern is legit but same comment then in the PR.
`Windows.Globalization.GeographicRegion().CodeTwoLetter` doesn't exactly fit the SDK use case. The SDK reports this country code as carrier country code which means it's not supposed to be provided by the user. There was a discussion around this in the App Center DotNet GH repository. We would need a sample using the location service I guess. I'll create a work item on our side to update the documentation with a location service sample but not sure when this will be picked up.
