### ISSUE TITLE
Step 3 Now Doesn't work as documented

### ISSUE THREAD

**Issue by markskiba** [MicrosoftDocs/appcenter-docs#540]
... on my 6S, the Allow configuration wasn't automatic.    There was a separate step of opening the iOS Settings app, find my downloaded config, and then Approve.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811f9eee-5b17-06e1-c108-dbef47984425
* Version Independent ID: 8fe50e13-c934-6a43-bf7d-1f33946da9d3
* Content: [Testing iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios#feedback)
* Content Source: [docs/distribution/testers/testing-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@markskiba I'll ask the PM to take a look

**Comment by botatoes** [comment]
@markskiba thanks for the feedback. I updated the docs with the change. The changes will get merged soon.
