### ISSUE TITLE
Free tier - Azure pipelines

### ISSUE THREAD

**Issue by gerwaldo** [MicrosoftDocs/appcenter-docs#541]
"The free tier" of Azure pipelines increased to:
Private project: One free parallel job that can run for up to 60 minutes each time, until you've used 1,800 minutes (30 hours) per month.
Does this apply to App Center as well ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc863ba-5295-2db8-b37f-584e662e725a
* Version Independent ID: db2a1468-e4fa-6c55-985f-616de1e6484f
* Content: [App Center Pricing - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/pricing#feedback)
* Content Source: [docs/general/pricing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/pricing.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by jwargo** [comment]
@gerwaldo I'm not sure, I'll ask the billing PM to take respond. 

You can also get questions like this answered by our support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by maestersid** [comment]
Hi @gerwaldo, at this time, we have not made any changes to our pricing nor what the free tier offers. It is the same as it was before, though we are always looking at how we can make the offer more compelling in the future.
