### ISSUE TITLE
What about translating the docs?

### ISSUE THREAD

**Issue by vitorverasm** [MicrosoftDocs/appcenter-docs#543]
The app center documentation is pretty straightforward and clear in all steps and it's helping me a lot. But what about supporting other languages?

I don't know a lot about [DocFX](https://github.com/dotnet/docfx) internationalization system and if there is a way to integrate different languages in one DocFX site like it was said in [this comment](https://github.com/dotnet/docfx/issues/803#issuecomment-367566709).

**Comment by jwargo** [comment]
@vitorverasm we haven't translated App Center into any other languages, so once we do that the docs will immediately follow.
