### ISSUE TITLE
Signing with environment variables doesn't work as shown

### ISSUE THREAD

**Issue by justindmyers** [MicrosoftDocs/appcenter-docs#544]
In section 3 (https://docs.microsoft.com/en-us/appcenter/build/android/code-signing) on the code signing page it says that the credentials will be supplied as environment variables on build, but  I could not make this work until I manually set the variables myself.

It seems like the environment variables should be automatically available according to how the docs are worded, but I could not make that work with any combination of settings in the App Center.

I've attached an image showing how I had to set it up to get the build working. It seems like this shouldn't be the behavior, but following the exact example on the how to retrieve the values (e.g. `System.getenv("APPCENTER_KEYSTORE_PASSWORD")`), would only work with a custom environment variable.

![vars](https://user-images.githubusercontent.com/58646/57345100-3dfdc480-710f-11e9-9d04-e9b5c002ecaa.PNG)

**Comment by jwargo** [comment]
@justindmyers I'll have the PM take a look. @nrajpurkar

**Comment by nilofer** [comment]
Hi @justindmyers, thanks for reaching out. Want to clarify what was confusing here so I can make the right changes to the docs. Was the confusing part here that you had to set the environment variables in App Center's UI _in addition to_ having the variables called out in your code?

**Comment by jwargo** [comment]
@justindmyers do you have an answer for @nrajpurkar?  If not, I'll assume you're good and close this issue.

**Comment by jwargo** [comment]
Closing due to no response from the customer.

**Comment by jvandenaardweg** [comment]
I was struggling with the same thing when I noticed this issue.

> Was the confusing part here that you had to set the environment variables in App Center's UI in addition to having the variables called out in your code?

Yes, that's the confusing part :-)

It wasn't clear to me too you need to fill the environment variables in the section where the other environment variables are. The UI is a little confusing there.

**Comment by jwargo** [comment]
@jvandenaardweg do you have any suggestions for how to make it better?

**Comment by nilofer** [comment]
@jvandenaardweg I've added a fix to explicitly call out needing to set the environment variable with a link to the relevant doc. Closing this out, but feel free to re-open and provide any additional suggestions.

**Comment by jvandenaardweg** [comment]
Thanks @nrajpurkar , much better now 👍

Only a small markdown problem with bold text now after this change in the docs

![01384B23-9D65-4678-9A11-E3924EE1F2F6](https://user-images.githubusercontent.com/5155373/61577543-12249500-aae9-11e9-8db9-bf37e45fc5e8.jpeg)
