### ISSUE TITLE
Wrong async method name 

### ISSUE THREAD

**Issue by Lapinou42** [MicrosoftDocs/appcenter-docs#545]
Hello there, 

First of all, thanks for providing this new feature : Auth :) 
I think you should name your sign in method : `SignInAsync` instead of "SignIn" since it's an async method.

Change : 

```
async void SignIn()
{
    try
    {
        // Sign-in succeeded.
        UserInformation userInfo = await Auth.SignInAsync();
    }
    catch (Exception e)
    {
        // Do something with sign-in failure.
    }
}
```

Into : 

```
async Task SignInAsync()
{
    try
    {
        // Sign-in succeeded.
        UserInformation userInfo = await Auth.SignInAsync();
    }
    catch (Exception e)
    {
        // Do something with sign-in failure.
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac18b7db-fbd4-041f-9628-bd014def0cda
* Version Independent ID: 72474382-3a42-c214-8c0e-7ac4dfbc08a9
* Content: [App Center Auth for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/auth/xamarin)
* Content Source: [docs/sdk/auth/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/auth/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **achew**

**Comment by jwargo** [comment]
@Lapinou42 thanks for that feedback, I passed it on to the Auth PM @amchew

**Comment by amchew** [comment]
Hi @Lapinou42! 

Thank you for your quick feedback, testing Auth and reading the docs in detail! We will update the method in the docs to ```async Task SignInAsync()```.
