### ISSUE TITLE
AppCenter Test + Android Emulators

### ISSUE THREAD

**Issue by msft-cofitz** [MicrosoftDocs/appcenter-docs#549]
Are there any plans to add support for running on emulators? I have tests that require a lot of API coverage and leasing all of the physical devices needed is very time consuming.

**Comment by jwargo** [comment]
@cofitz1 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

We also recently started publishing our roadmap and collecting customer feature requests through the App Center repo on Github at https://github.com/Microsoft/appcenter

**Comment by msft-cofitz** [comment]
Redirecting this to the correct github repo :)
