### ISSUE TITLE
AppCenter Test + Device Leases

### ISSUE THREAD

**Issue by msft-cofitz** [MicrosoftDocs/appcenter-docs#550]
Are there any plans to support "leasing" a device for use in a DevOps pipeline for a period of time instead of only supporting test workloads that run directly on the device unassisted?  I have scenarios where using adb directly on a device is necessary to orchestrate testing - ideally a DevOps task could be used to get a device that is accessible for all of the remaining tasks in the pipeline.

**Comment by jwargo** [comment]
@cofitz1 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by msft-cofitz** [comment]
Redirecting this to the correct github repo :)
