### ISSUE TITLE
Set User Id Propagation Time

### ISSUE THREAD

**Issue by michaelmerrill** [MicrosoftDocs/appcenter-docs#553]
How long does propagation take when updating the user's identity through the sdk? Custom properties take up to 30 minutes to propagate. Is setting a user id similar?

**Comment by jwargo** [comment]
@michaelmerrill I'm not sure, but I'll have the PM or SDK team respond.

**Comment by annakocheshkova** [comment]
Hey @michaelmerrill the user id, as well as custom properties, is sent from the SDK right away. The delay might be on the backend.
@jwargo we have to ask somebody from backend team to answer this.

**Comment by jwargo** [comment]
@michaelmerrill which service are you asking about?

**Comment by michaelmerrill** [comment]
App Center Push - https://docs.microsoft.com/en-us/appcenter/push/push-to-user

**Comment by jwargo** [comment]
@michaelmerrill cool, let me check.

**Comment by jwargo** [comment]
@michaelmerrill it should be available pretty quickly, less than a minute in our testing.
