### ISSUE TITLE
Delay showing Push Notifications 

### ISSUE THREAD

**Issue by c-lamont** [MicrosoftDocs/appcenter-docs#555]
The tip regarding "Delay showing Push Notifications" does not work on iOS

When I call the `AppCenter.Start(typeof(Push));`, I get the popup to accept push notifications which is good.

When I receive a notification however, `Push.PushNotificationReceived` is never called either in the foreground or the background.

When I call the `AppCenter.Start(typeof(Push));` in `FinishedLaunching` then everything works correctly and `Push.PushNotificationReceived` is called.

However its not the nicest experience to request to send push notification immediately on opening the app for the first time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4ea7173-6f6e-3ecc-2ec4-f03587ec654b
* Version Independent ID: 03a9eba6-e6f7-7919-4b6a-209f8ef1e75f
* Content: [Tips and Tricks - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/tips)
* Content Source: [docs/push/tips.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/tips.md)
* Service: **vs-appcenter**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@c-lamont as I understand it, it should; we got that directly from our SDK team. I'd suggest you work this out with our support team. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by guperrot** [comment]
Hi, I would suggest delaying the start only the first time for optin, then if push notifications are enabled at start, start immediately.

```
            if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
            {
                var settings = UNUserNotificationCenter.Current.GetNotificationSettingsAsync().ContinueWith(task =>
                {
                    if (task.Result.AuthorizationStatus == UNAuthorizationStatus.Authorized)
                    {
                        app.StartPush = true;
                    }
                });
            }
            else if (UIApplication.SharedApplication.IsRegisteredForRemoteNotifications)
            {
                app.StartPush = true;
            }
```

Where `app` is the Xamarin.Forms app passed in `LoadApplication` then in `OnStart` you can add that boolean property and test it while starting services.

For a pure Xamarin.iOS solution (without Forms), it's more direct:

```
            if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
            {
                var settings = UNUserNotificationCenter.Current.GetNotificationSettingsAsync().ContinueWith(task =>
                {
                    if (task.Result.AuthorizationStatus == UNAuthorizationStatus.Authorized)
                    {
                         AppCenter.Start(typeof(Push));
                    }
                });
            }
            else if (UIApplication.SharedApplication.IsRegisteredForRemoteNotifications)
            {
                AppCenter.Start(typeof(Push));
            }
```

**Comment by jwargo** [comment]
Thanks @guperrot! @c-lamont let me know if this works for you and I'll close the issue. Looks like there's a doc update pending on this as well.

**Comment by c-lamont** [comment]
Thanks @jwargo @guperrot , On first test this has solved the issue and the `Push.PushNotificationReceived` is being fired. 👍

**Comment by c-lamont** [comment]
@jwargo After some more testing the startup screen freezes when the `UNUserNotificationCenter.Current.GetNotificationSettingsAsync().ContinueWith` is called.

**Comment by jwargo** [comment]
@c-lamont OK, so we can't do support through the docs, please open a support ticket using the blue chat button in the bottom-right corner of the App Center portal.
