### ISSUE TITLE
Invalid documentation for Android Code Signing

### ISSUE THREAD

**Issue by zanechua** [MicrosoftDocs/appcenter-docs#556]
~~The current documentation for Android code signing does not indicate which keystore filename to use and where the keystore will be located after you configure a branch. Looking up multiple tutorials online it seems that the keystore should be in app/nameofkeystorefile.keystore or etc. However this is invalid.~~

~~When the agent starts the build, the following script is ran.~~

```bash
Printing Keystore script
#!/bin/sh

BUILD_SRC_ROOT=$BUILD_SOURCESDIRECTORY
KEYSTORE_FILENAME="keystore"

if [ ! -z "$2" ]; then
	BUILD_SRC_ROOT="$2"
fi

if [ ! -z "$3" ]; then
	KEYSTORE_FILENAME="$3"
fi

if [ -z "$1" ]; then
	echo "Keystore is missing."
	exit 1
fi

if [ -z "$BUILD_SRC_ROOT" ]; then
	echo "Source code root directory is not specified."
	exit 1
fi

# Create .certs directory under the source root if doesn't exist
[ -d "$BUILD_SRC_ROOT/.certs" ] || mkdir -p "$BUILD_SRC_ROOT/.certs"

# Decode the base64-encoded certificate contexts to the files
echo "$1" | base64 --decode &gt; "$BUILD_SRC_ROOT/.certs/$KEYSTORE_FILENAME.jks"
```

~~For whatever weird reason, the filename of the keystore i uploaded in appcenter isn't being used. But that being said, the keystore file ends up in the root directory of the git repository in the .certs folder with a jks extension and not keystore. So the proper location of the keyfile would be `rootDirectory/.certs/keystore.jks`~~

`System.getenv` is also invalid as the variables are being passed in as properties during the gradle build command: `/Users/vsts/agent/2.150.3/work/1/s/android/gradlew -DMOBILECENTER_KEYSTORE_PASSWORD=*** -DMOBILECENTER_KEY_ALIAS=*** -DMOBILECENTER_KEY_PASSWORD=*** -DAPPCENTER_KEYSTORE_PASSWORD=*** -DAPPCENTER_KEY_ALIAS=*** -DAPPCENTER_KEY_PASSWORD=*** -p android clean :app:assembleDevKernelRelease`

So it should be `System.getProperty` instead of `System.getenv`

Therefore the correct configuration should be something along the lines of:

```java
storeFile rootProject.file("../.certs/keystore.jks")
storePassword System.getProperty('APPCENTER_KEYSTORE_PASSWORD') ?: APPCENTER_KEYSTORE_PASSWORD
keyAlias System.getProperty('APPCENTER_KEY_ALIAS') ?: APPCENTER_KEY_ALIAS
keyPassword System.getProperty('APPCENTER_KEY_PASSWORD') ?: APPCENTER_KEY_PASSWORD
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb88b888-1e68-8a75-efa4-cef2c33d4369
* Version Independent ID: 2fd3c90f-d7e5-5af3-9a50-b5571ac84995
* Content: [Android Code Signing Setup in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/android/code-signing#feedback)
* Content Source: [docs/build/android/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/android/code-signing.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@zanechua I'll have the Build PM take a look.

**Comment by zanechua** [comment]
After spending more time debugging, I realised that I should probably not even be setting a configuration for the keystore. Only unless the file is inside my repository. Therefore the install-keytool.sh part is still correct and instead the only change here should be the `System.getenv` to `System.getProperty`. Everything else should be the same.

**Comment by zanechua** [comment]
@jwargo 

Why was this closed?

**Comment by jwargo** [comment]
@zanechua because in your response you indicated things that you probably shouldn't have done and didn't ask any additional questions, so I assumed you were good. If you have questions about the docs, please ask them. If you need support, open a support ticket. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by zanechua** [comment]
Yes i did indicate what I should not have done but I did mention that `System.getenv` is inaccurate. This is still a problem with the docs. Removing out all the key signing issues, when I used `System.getenv`, my application wouldn't compile. Hence the docs still need to update the values to `System.getProperty` as mentioned in my previous comment and the original issue.

There are two distinct issues that I thought were present but only one of them is a false positive. The other one is still pretty much an issue and it would be good if you could get it looked at.

**Comment by zanechua** [comment]
Ping @jwargo .

The original issue still stands and this issue should be opened

**Comment by jwargo** [comment]
@zanechua I apologize for the delay, I was out of the country for two weeks and just got back. I'll ping the PM to take another look at this.

**Comment by zanechua** [comment]
After re-looking at this issue again and doing a bit more digging. It seems that this was changed in #428 . I seem to have a misunderstanding of how the signing of the apk through appcenter would work if you didn't specify signing configs. So I am wrong about the necessary change to the documentation and this issue should be closed.

Sorry for the time-wasting @jwargo

For those using appcenter to manage and sign your apks, simply do not include any signing information for your apk under `buildTypes` in your gradle file. AppCenter will build an unsigned apk and subsequently manually sign your apk.

**Comment by matthiaswenz** [comment]
Following up on this - sorry for the delay. With the issue being closed it got lost.
@zanechua You are correct that the way we pass the signing credentials is through System properties (`-D` flags) and this is also how we should instruct people to use them.
Will fix this.
