### ISSUE TITLE
How can I use a client like Postman or Insomnia?

### ISSUE THREAD

**Issue by kevinclarkneudesic** [MicrosoftDocs/appcenter-docs#558]
Can you just tell how to do it via cURL or a different client as well?  Is it just one header for the authentication?  If so, what is the header key for the api key that is used for authentication?  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/index)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@kevinclarkneudesic the swagger page shows you how to do it via curl.  You must authenticate first (using the option at the top of the page), but once you do that, the swagger example updates with the correct auth key. 

I updated the docs recently to describe this, but I can't seem to find it.

**Comment by jwargo** [comment]
@kevinclarkneudesic aah, here it is - yes, just the one header for auth: https://docs.microsoft.com/en-us/appcenter/api-docs/#using-an-api-token-in-an-api-request.

**Comment by kevinclarkneudesic** [comment]
Ah, I see it now. "X-API-Token".  Thank you @jwargo!
