### ISSUE TITLE
Amazon App Store support is missing

### ISSUE THREAD

**Issue by sseyod** [MicrosoftDocs/appcenter-docs#559]
As the comment says - Android App Store support is missing

**Comment by jwargo** [comment]
@sseyod I'm sorry, I don't understand what you're asking for. Can you give me some more context?

Android App Store support is missing from what?

**Comment by sseyod** [comment]
Hi! Sorry if this wasn't clear. I thought the issue I raised would link somehow to the page - please see the table here: https://docs.microsoft.com/en-us/appcenter/distribution/stores/

**Comment by jwargo** [comment]
@sseyod Android App Store is the Google Play Store. They're one in the same.

**Comment by sseyod** [comment]
I am *really* sorry, I can't believe I mistyped - I meant *Amazon* app store. I've corrected the title!

**Comment by Oddj0b** [comment]
Hey @sseyod, it's me again. Same as the other issue, please create a feature request on our public repository using this link: https://github.com/microsoft/appcenter/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=
