### ISSUE TITLE
Can't see build details

### ISSUE THREAD

**Issue by apolishch** [MicrosoftDocs/appcenter-docs#56]
When I run appcenter codepush deployment list --app Appname, I get shown the following:

│ Name       │ Key                                                              │
├────────────┼──────────────────────────────────────────────────────────────────┤
│ Production │ prod-key │
├────────────┼──────────────────────────────────────────────────────────────────┤
│ Staging    │staging-key │

I can no longer see which build is the latest in which environment (or what percentage of users has downloaded it). Is this something that will becoming back? It was a killer feature of code-push and I am sad to see it go!

**Comment by Zakeelm** [comment]
Hey there! 

As of now, this is still available through the CodePush CLI, but not in the App Center one. But, we do make these metrics available in the App Center web portal. We've actually discussed bringing this functionality  back in the new CLI, but later had a priority shift. When our team has bandwidth, we will definitely be looking into this again!
