### ISSUE TITLE
macOS App Store support is missing

### ISSUE THREAD

**Issue by sseyod** [MicrosoftDocs/appcenter-docs#560]
As the title says - macOS App Store support is missing

**Comment by jwargo** [comment]
@sseyod I'm sorry, I don't understand what you're asking for. Can you give me some more context?

macOS App Store support is missing from what?

**Comment by sseyod** [comment]
Hi! Sorry if this wasn't clear. I thought the issue I raised would link somehow to the page - please see the table here: https://docs.microsoft.com/en-us/appcenter/distribution/stores/

**Comment by jwargo** [comment]
@sseyod normally it does, but for these it didn't.

**Comment by Oddj0b** [comment]
@sseyod The documentation is accurate as App Center doesn't support store connections with MacOS apps. If you would like to request App Store support, visit our public repository and create an issue using this link: https://github.com/microsoft/appcenter/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=
