### ISSUE TITLE
Insufficient APNs configuration guide

### ISSUE THREAD

**Issue by shnaz** [MicrosoftDocs/appcenter-docs#562]
Hello

I have a simple suggestion that will make lives of a lot of new beginners easier.

Configuration of Xamarin.iOS and APNS should be made a lot more explicit and thorough than it is. In the [prerequisite](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios#prerequisite---enable-apple-push-notifications-service-apns-for-your-app) section, it states the following: 

> Please configure Apple Push Notifications service (APNs) for your app from your Apple developer account and the App Center portal before adding App Center Push to your app. App Center Push won't get any notifications if you don't setup push notifications.

The above documentation is not enough, specially when AppCenter Push does NOT need the .cert file in order to work. You only have to create it and NOT upload it anywhere, like you would do in OneSignal or Swrve etc. The reason is of course that AppCenter uses an Auth Key to use APNs, therefore that push certificate .p12 file is not needed.

I have used too many unnecessary hours guessing what goes where. I had to contact your support countless times and they had to refer to one your competitor [Swrve](https://docs.swrve.com/faqs/push-notifications-faq/manage-ios-push-certificates-for-push-notifications/) which had a more useful documentation on how to create a push certificate. 

So if you just could update your own documentation to include creation and usage of the push certificate, I am sure you will make a lot of new beginners happy, then we do not have to use OneSignal or Swrve as reference when configuring the push notification.

Thank you

**Comment by jwargo** [comment]
@shnaz I'll do what I can to update the docs. I'm not an expert in APNS, but I'll get one of our engineers to help me.

**Comment by aimankhan** [comment]
Hi @shnaz 
I'm sorry to hear you had issues with this. The reason there isn't a guide to setting up a certificate in APNS included in the documentation you linked to is because that's not something you need for key based authentication.

In other words, you don't need to generate a .p12 file at all - simply following the steps to create a auth key - as shown below will suffice.
![image](https://user-images.githubusercontent.com/13143035/58135991-4c54e180-7be1-11e9-8ec6-a88b696774b5.png)

I hope that helps you gives you an insight into why we don't document cert creation.

Thanks for using AppCenter!

**Comment by shnaz** [comment]
Hi @aimankhan 

I know that the .p12 file is completely useless when using an Auth Key **BUT** you still have to have an Apple Push Services Certificate. Furthermore you have to enable the service for the App ID which requires the forementioned Apple Push Services Certificate.

![image](https://user-images.githubusercontent.com/6933856/58161008-c3d94e00-7c7f-11e9-8022-76c975dadcbf.png)

**Comment by jwargo** [comment]
@shnaz I didn't see a question in your last comment; are you good or do you still need help?

**Comment by shnaz** [comment]
@aimankhan wrote that it was not needed to document the creation of the APNS and setting up the AppID, but I disagree and still suggest you to clarify your documentation on the mentioned parts.

**Comment by jwargo** [comment]
Shnaz, Thank you for your feedback, but our research indicates that the documentation is correct as written, so we will not be making any changes.

**Comment by shnaz** [comment]
Your support-team and I do not agree, but fair enough. :)

<img width="378" alt="Screenshot 2019-06-06 at 17 20 26" src="https://user-images.githubusercontent.com/6933856/59045143-c0e57c80-887f-11e9-928c-ca9c429ce200.png">
