### ISSUE TITLE
Platform Dropdown Menu Always Shows 'Android'

### ISSUE THREAD

**Issue by zigfreid5** [MicrosoftDocs/appcenter-docs#564]
Regardless of the platform chosen, the dropdown picker always shows 'Android' as the selected value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7cb9ac6-0d20-5f02-583f-21021ed5ccce
* Version Independent ID: d7429800-d5af-825a-48d3-b8c45ec7ee4e
* Content: [Other iOS APIs - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios)
* Content Source: [docs/sdk/other-apis/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/other-apis/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@zigfreid5 can you try a different browser? I'm not experiencing that problem here.

**Comment by zigfreid5** [comment]
@jwargo The same thing happens in both Safari and Chrome for me, on both iOS and MacOS.

**Comment by jwargo** [comment]
@zigfreid5 You're referring to in the docs, right?

**Comment by jwargo** [comment]
@zigfreid5 that platform picker at the top of the doc will always say Android. When you make a choice in the drop-down, it switches to the selected page, but always renders the drop-down the same.
