### ISSUE TITLE
Misleading comments about bitcode support

### ISSUE THREAD

**Issue by zigfreid5** [MicrosoftDocs/appcenter-docs#565]
Disabling bitcode may not have any downsides when distributing apps via App Center, but does when distributed through the app store. WatchOS and tvOS targets require bitcode, disabling bitcode results in larger binaries when uploaded to and installed via the AppStore, and I suspect apps without bitcode enabled will not be supported by Apple's "Project Marzipan" when that is released later this year (though that's a bit of conjecture), for similar reasons that bitcode enabled Apple to seamlessly transition WatchOS apps to 64-bit when WatchOS 4 was released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94f7999c-0c3c-ee5d-c8a9-29ee9aa0d622
* Version Independent ID: 1c9f21ed-86de-8e79-d007-e80945edf360
* Content: [iOS Symbolication - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication)
* Content Source: [docs/diagnostics/iOS-symbolication.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/iOS-symbolication.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by jwargo** [comment]
@zigfreid5 I'll have the PM take a look.

**Comment by winnie** [comment]
@zigfreid5 thanks for the feedback! I've updated the docs to specify that we are specifically referring to iOS apps, and not Watch and tvOS. Our team is keeping an eye out on the Marzipan project and will update our docs/product to reflect any major changes. I'll close the issue for now but let me know if you have any other questions.

**Comment by lumaxis** [comment]
>disabling bitcode results in larger binaries when uploaded to and installed via the AppStore

@zigfreid5 Have you actually observed this yourself? I've heard this statement many times before but so far, we've never been able to actually confirm this and I've only seen anecdotal evidence for it. I'd be curious if you have made any specific observations around this.

**Comment by lumaxis** [comment]
To follow up: I just confirmed this with Apple’s engineers at WWDC, disabling Bitcode has no negative effect on the installed app file size.

**Comment by zigfreid5** [comment]
@lumaxis I think you either got misinformation or just misunderstood. There's an explicit breakdown of app sizes in the app store. Here's an example:

![image](https://user-images.githubusercontent.com/4284140/59863478-05721d00-9342-11e9-8f89-88367f3746d1.png)

The Universal binary size is what you will get if you don't enable bitcode. Bitcode lets Apple recompile and optimize your app for each specific device type, resulting in much smaller app sizes for both download and install.

**Comment by caisd1998** [comment]
@zigfreid5, I don't think customer will get universal binary if I don't enable bitcode, I checked the app size shown on TestFlight, it's close to my phone type's Install Size, neither Universal type's Download Size nor Install Size.
