### ISSUE TITLE
App Center push only when app is running in the background

### ISSUE THREAD

**Issue by BradVause** [MicrosoftDocs/appcenter-docs#57]
Hi,

I know it says at the top of this article that the push notifications will work when the app is running in the background. Fair enough - but being able to send notifications when the app is not running is a pretty common feature right? Surely it is possible? How would I go about doing that? Any guidance would be appreciated.

Also - I have implemented everything in this article and eventually got notifications working. However - there is no mention of NotificationManager.Notify() - I had to get that from somewhere else. If you implement everything in this article you won't actually see a notification unless you use the Notification Manager.

Thanks for the guide!
Brad 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed528dcd-ecaf-697e-c64a-30651d26ff3d
* Version Independent ID: 1e92bbb4-5800-6d31-51ee-c6d5864801d1
* Content: [App Center Push for Xamarin.Android Apps - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-android?hubRefSrc=email&utm_source=lfemail&utm_medium=email)
* Content Source: [docs/sdk/push/xamarin-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by dhei** [comment]
Hi Brad, 
Xamarin.Android push notification should work when app is not running at all, there's no special guidance required to make this scenario work. For your second question, I don't think `NotificationManager` is required for push to work, can you explain where do need `NotificationManager.Notify()` in your app? Thanks for using App Center.

**Comment by BradVause** [comment]
This document actually says at the top in a blue rectangle:
"A notification appears in the system notification center only if the application is in the background at the moment the Push is received." I would really like to show notifications whether the app is running or not.

In the Push.PushNotificationReceived method - this code is hit when the notification is received, however this code reads the notification data, it doesn't show any notification at the end of it. I had to implement something like this to get the notification to show:

public void ShowNotification(string body, string Header)
        {
            Notification.Builder builder = new Notification.Builder(this);
            builder.SetSmallIcon(Resource.Drawable.Icon);
            var intent = new Intent(this, typeof(FormsApplicationActivity));
            intent.AddFlags(ActivityFlags.ClearTop);
            PendingIntent pendingIntent = PendingIntent.GetActivity(this, 0, intent, 0);
            builder.SetContentIntent(pendingIntent);
            builder.SetLargeIcon(BitmapFactory.DecodeResource(Resources, Resource.Drawable.Icon));
            builder.SetContentTitle(Header);
            builder.SetContentText(body);
            builder.SetDefaults(NotificationDefaults.Sound);
            builder.SetAutoCancel(true);
            NotificationManager notificationManager = (NotificationManager)GetSystemService(NotificationService);
            notificationManager.Notify(1, builder.Build());
        }

**Comment by dhei** [comment]
Thanks for your feedback,  and sorry about the delay of my response. Yes, you are right--the code snippet of `PushNotificationReceived` method only logs the push notification message received without displaying any notification UI. Therefore you will have to write the UI code that actually display the notification. We will improve this doc with more clear instructions and code snippets.

**Comment by angelru** [comment]
@BradVause Can it receive notification when app is closed?

**Comment by BradVause** [comment]
@angelru no I have not go that to work yet - not sure how to.

**Comment by angelru** [comment]
@BradVause With Firebase Push Notification it's possible, me it works.

https://github.com/CrossGeeks/FirebasePushNotificationPlugin

**Comment by jwargo** [comment]
@BradVause @angelru  The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by angelru** [comment]
@BradVause @jwargo thanks, but the method PushNotificationReceived work when the app is background or closed?

**Comment by andrewleader** [comment]
Seems like this was never answered and should be reopened... how do you programatically receive push notifications when the app is in the background or closed? Like you want your code to wake up and do something in response?

**Comment by jwargo** [comment]
@andrewleader so we updated the docs based on this a year ago. I thought this was resolved - what you see in the docs isn't enough?  Probably the best thing to do is ask support for help.

**Comment by guperrot** [comment]
@jwargo @andrewleader As documented in the notes of https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-android#intercept-push-notifications the user can receive a notification in background (including when an app is not running) but you cannot execute code at receive time. The callback is only executed at notification click time. The only exception is Silent push on iOS (silent on iOS can be actual silent callback or alert + callback). But we don't support the equivalent for Android at this time (so it is a feature request).

**Comment by angelru** [comment]
@guperrot @jwargo @andrewleader I hope the code runs soon upon receiving a notification as a firebase without touching the notification events OnReceived and OnOpened

**Comment by mjfara** [comment]
> @jwargo @andrewleader As documented in the notes of https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-android#intercept-push-notifications the user can receive a notification in background (including when an app is not running) but you cannot execute code at receive time. The callback is only executed at notification click time. The only exception is Silent push on iOS (silent on iOS can be actual silent callback or alert + callback). But we don't support the equivalent for Android at this time (so it is a feature request).

Is there any way of knowing if the notification was already shown (app was in background), or if the notification was received while the app was in the foreground?
