### ISSUE TITLE
Are these iOS API's using Azure.iOS ?

### ISSUE THREAD

**Issue by SogoGolf** [MicrosoftDocs/appcenter-docs#570]
Bit confused, are the Appcenter data API's separate / different from https://github.com/Azure/Azure.iOS ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5daee3ed-f796-73bd-af36-6deb5e33db9d
* Version Independent ID: 91af479e-8b3e-2395-c3f6-0bb0c108b61e
* Content: [Configuring App Center Data for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/data/ios)
* Content Source: [docs/sdk/data/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/data/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@SogoGolf yes. App Center has its own SDK and that's how we implement data sync.
