### ISSUE TITLE
Unclear how to setup xamarion 3.0.0

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#571]
Now first of all is it compatible with .net core 2.1? 

I tried installing the following nuget packages 
Xamarin UITest 3.0.0
Nunit 3.11.0

And I still get warnings that it may not compatible, this is not the first time document your pages good and correctly. I hope to get an answer soon because every minute is a minute that costs me time and money. I thank you.

**Comment by jwargo** [comment]
@laurenspp is what compatible with .NET Core 2.1?  Your issue title says Xamarin 3.0.0, but this isn't the docs for Xamarin. So could you clarify what you're asking?

The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by ghost** [comment]
ok... I contacted support many times :-)

Is xamarin 3.0.0 and Nunit 3.12.0 compatible with net core 2.1?
Because here I always get compatibility issues

**Comment by jwargo** [comment]
@laurenspp I'm sorry, I can't help - I don't know the answer to that question as this isn't the Xamarin team. 

What App Center service are you trying to use? Is this for Test?

**Comment by jwargo** [comment]
@laurenspp it's been 8 days with no response, I'm going to close this issue. It feels like you were looking for Xamarin support, which we can't help you with, but if you have an App Center support question, App Center support is provided directly from within the App Center portal. 

Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
