### ISSUE TITLE
Platform and title are not in sync

### ISSUE THREAD

**Issue by shamprasadrh** [MicrosoftDocs/appcenter-docs#573]
Page title says "Get Started with React Native" but the platform shown is "Android". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#feedback)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by jwargo** [comment]
@shamprasadrh that's just a drop-down you can use to select the same content for a different target platform. Unfortunately it's not being set to the currently selected language.
