### ISSUE TITLE
More details needed

### ISSUE THREAD

**Issue by pronouncedJerry** [MicrosoftDocs/appcenter-docs#574]
Is there something that needs to be done on the device to enable/disable this? Or any device running the software will submit to Log Flow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b54905c-48c1-06be-2676-c1ca8a9463f2
* Version Independent ID: 56586cc1-d598-9f6b-8cda-a3359ed56e4f
* Content: [Understanding the App Center Log Flow Page - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/log-flow#feedback)
* Content Source: [docs/analytics/log-flow.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/log-flow.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by jwargo** [comment]
@pronouncedJerry no, as long as the App Center SDK is in your app and activated, logs move through the system.
