### ISSUE TITLE
UWP C++

### ISSUE THREAD

**Issue by deepaknarula** [MicrosoftDocs/appcenter-docs#576]
Is there a version which would support C++/WinRT UWP Apps as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ece9ab-9965-2ddf-34b6-44f0f61fe599
* Version Independent ID: 16261b98-a85e-060f-ccf4-3a24f5f14c4c
* Content: [Get Started with UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/uwp#feedback)
* Content Source: [docs/sdk/getting-started/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@deepaknarula I'll have the PM take a look at your question. Don't forget as well that App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by elamalani** [comment]
@deepaknarula We only support UWP apps built with C#. We don't have a windows SDK for C++ or WinRT platform.

**Comment by markghayden** [comment]
Are there any plans for Windows C++ support in SDK?

**Comment by winnie** [comment]
Hi @markghayden - C++ for UWP apps isn't on our immediate roadmap. 

There are a few feature requests around crash reporting support for C++ apps: 
https://github.com/microsoft/appcenter/issues/436
https://github.com/microsoft/appcenter/issues/374

Feel free to give these issues a +1 or create a seperate feature request on the [App Center repo](https://github.com/Microsoft/appcenter) to help our team prioritize these features. 

Thanks!
