### ISSUE TITLE
Broken link to Windows plan

### ISSUE THREAD

**Issue by bezysoftware** [MicrosoftDocs/appcenter-docs#577]
The link https://github.com/Microsoft/appcenter/blob/windows/specs/2019-04/Windows-Plan.md doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5756765e-fef2-e8d9-f8d9-5c01690095b8
* Version Independent ID: b474e30a-6e59-97fc-476a-92be5ec3a01a
* Content: [App Center Crashes for UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp)
* Content Source: [docs/sdk/crashes/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@bezysoftware thanks for catching, I'll fix.
