### ISSUE TITLE
Wrong cocoapods version

### ISSUE THREAD

**Issue by mspasov** [MicrosoftDocs/appcenter-docs#578]
Document states that cocoapods is 1.6.1, but the installed version is 1.7.0 (and 1.7.0 breaks my build 😤)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022126c7-2d61-9c53-6881-149310c137c0
* Version Independent ID: 4fe62fb4-6dd9-057e-8f57-fb4c6dcb71f8
* Content: [App Center Cloud Build Machines - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/software)
* Content Source: [docs/build/software.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/software.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@mspasov hmmm, I'll have the team take a look.

**Comment by jwargo** [comment]
@mspasov sorry about that, there was a doc update pending and it's been published.
