### ISSUE TITLE
Appium Javascript

### ISSUE THREAD

**Issue by arifzaman2** [MicrosoftDocs/appcenter-docs#58]
Greetings,

Can I run test with Appium which is written on JavaScript (Webdriver.io to be specific)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium#feedback)
* Content Source: [docs/test-cloud/preparing-for-upload/appium.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@arifzaman2 The comments feature of the docs is designed to enable customers to suggest changes to the docs or ask clarifying questions about the docs. If you need help with the product, please login to the App Center dashboard and click the blue chat button in the lower-right corner of the page. Our dedicated support resources will answer any questions you have there.

**Comment by glennwester** [comment]
@arifzaman2 Thanks for writing in. We don't support the Javascript client in Appium at the moment, this is something we can look into in the future.

**Comment by sanjayaubergine** [comment]
+1

**Comment by fabiodamasceno** [comment]
React Native users are not able to use a decent ui test framework at this time because there isn't support to Detox, Appium nor any functional high-level UI test frameworks (unless to be XCUITest, that is native and not the case). This make unfeasible AppCenter to React Native projects, continuous delivery.  Can community contribute in anyway to speed up this support?

**Comment by ducpt2** [comment]
+1 looking for React Native + Appcenter Test work.

**Comment by Oddj0b** [comment]
@ducpt2 You can create a feature request at our public repository: https://github.com/microsoft/appcenter/issues/new/choose or upvote the agnostic appium test run: https://github.com/microsoft/appcenter/issues/453

**Comment by fabiodamasceno** [comment]
Thanks for the feedback Villars ;D
