### ISSUE TITLE
Third-party Crash Reporting forbids use of Analytics?

### ISSUE THREAD

**Issue by vojtarylko** [MicrosoftDocs/appcenter-docs#580]
Documentation states prerequisite "You are not using any other library that provides Crash Reporting functionality." Is this prerequisite mandatory even when I want to use just AppCenterAnalytics and *not* AppCenterCrashes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45228922-4a96-8c08-7d27-69ef98d44943
* Version Independent ID: d04ef359-7b17-8a14-970b-5c48820976cd
* Content: [Get Started with iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#feedback)
* Content Source: [docs/sdk/getting-started/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@vojtarylko I'll ask the SDK team to give you a formal reply, I have an opinion but don't want to give you faulty information.

**Comment by MatkovIvan** [comment]
Hi @vojtarylko,
 
This limitation is caused by the way of handling low-level signals after a crash. So, the usage of another library can break only crash reporting functionality.
The Analytics module should work in this case.

We'll add a note about it into the docs.

Thanks,
Ivan
