### ISSUE TITLE
Post Build script variable to set build status = fail or pass

### ISSUE THREAD

**Issue by ssharma0312** [MicrosoftDocs/appcenter-docs#583]
Hi

I want to include a logic in my post script to make an external call which returns test results, and mark build as Pass or Fail based on the api response. Is there any variable exposed to set build status to fail or pass?

**Comment by jwargo** [comment]
@ssharma0312 I'll ask the PM to respond.

The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by nilofer** [comment]
Hi @ssharma0312, you should be able to add logic based on the API result of your tests to cause the build to fail. To fail the build, you'll just need to add a line that says `exit 1` in your script. This fails the script and the whole build overall.
