### ISSUE TITLE
Remove AppCenter dependencies from the project (right-click the dependency > Remove dependency).

### ISSUE THREAD

**Issue by vforvasile** [MicrosoftDocs/appcenter-docs#584]
Can you be more specific on what dependencies and from where to remove them? xCode is a huge maze that can be tricky sometimes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1b3f6c-3754-3c3f-1f63-1af79ad651a2
* Version Independent ID: 7fdc3cf5-f1fc-6fca-e9b6-ca1f287e1785
* Content: [React Native SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native?irgwc=1&OCID=AID681541_aff_7593_1375745&tduid=(ir__9qkjh1h9wskfrxc3xkpoxiopbn2xmavfvrgsca0e00)(7593)(1375745)()()&irclickid=_9qkjh1h9wskfrxc3xkpoxiopbn2xmavfvrgsca0e00#feedback)
* Content Source: [docs/sdk/troubleshooting/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by jwargo** [comment]
@vforvasile I'll ask the team to take a look at your question.

**Comment by AnastasiaKubova** [comment]
Hi, @vforvasile! Thank you for your comment. We will fix it.

**Comment by MatkovIvan** [comment]
The detailed steps for it have been added to the docs.

**Comment by hkar19** [comment]
may i know where is the docs?

**Comment by AnastasiaKubova** [comment]
Hi, @hkar19 ! You can find it [here](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native).
