### ISSUE TITLE
Moving apps to appcenter

### ISSUE THREAD

**Issue by brynjar** [MicrosoftDocs/appcenter-docs#585]
This doc still mentions early 2019 - is it possible yet to move apps over from hockey to appcenter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27acd64c-5106-51ce-628c-8a1a17269e95
* Version Independent ID: d57cf8a3-d9de-4a8a-b746-e1f278e2c80c
* Content: [HockeyApp Transition - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/#feedback)
* Content Source: [docs/transition/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/index.md)
* Service: **vs-appcenter**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by dipree** [comment]
Apologize, I'll change it. We're still in a closed beta but it's definitely coming mid 2019.

**Comment by davebcn87** [comment]
Is it still in closed beta? Is it worth to change the SDK for the existing apps now or should we wait until we can move definitely to AppCenter?

**Comment by dipree** [comment]
@davebcn87 it's recommended to move the apps to App Center first, then update the SDK. The option to move apps will be available end of the week or early next week.

**Comment by davebcn87** [comment]
thanks @derpixeldan Where can I follow the progress on that?

**Comment by dipree** [comment]
Yes, it's on our [roadmap on GitHub](https://github.com/Microsoft/appcenter/wiki/Roadmap) and the ticket is [here](https://github.com/Microsoft/appcenter/issues/230).

**Comment by abhayTale86** [comment]
What is the alternative of method onNewCrashesFound() of CrashManagerListener of HockeyApp in App center

**Comment by dipree** [comment]
@abhayTale86 please reach out to us directly via support, the blue button in the lower right in App Center.
