### ISSUE TITLE
AppCenter Auth with native sign in page

### ISSUE THREAD

**Issue by OlexandrStepanov** [MicrosoftDocs/appcenter-docs#587]
[Enter feedback here]

---
Hello 👋,

We would like to use AppCenter as BaaS solution on mobile (iOS+Android) project, and in order to have user data partitions with need to implement authorisation using AppCenter SDK.
But our UI/UX would like to have native UI for sign in page with login & password inputs.
I know that AAD B2C supports [custom UI](https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview) for authorisation, but it will be displayed in a web view instead.
Is it possible to implement AppCenter authorisation without presenting web view but with long & password request from native screen instead?
I know there is [Custom Token](https://firebase.google.com/docs/auth/admin/create-custom-tokens) solution in Firebase for that, is there something similar in AppCenter?

With regards.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f74618cf-1ab9-0977-d07f-26e840058259
* Version Independent ID: cf027587-4bbf-1b73-fb10-b0e40094ef30
* Content: [Managing identities with the App Center Auth Service - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/auth/)
* Content Source: [docs/auth/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/auth/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@OlexandrStepanov I'll ask the PM to take a look at your question.

In the mean time, App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by amchew** [comment]
Здрастуйте @OlexandrStepanov! :) 
I'll am checking, and will get back shortly!

Also, thank you for using Auth! I'd love to learn about your experience with Auth so far. Would you be available for a call next week? If so, email me at amchew [at] microsoft [dot] com.

**Comment by OlexandrStepanov** [comment]
Ni hao, @amchew :)

We are currently on the stage of establishing a new project for our client, mobile app for both platforms, iOS & Android.
The client is using Azure as infrastructure provider, and thus we are looking at AppCenter not only as CI/CD solution, but also as data storage, crash reporting and analytics provider.
We don't have experience with it, but have some with Firebase, and thus compare these two similar services in some kind.
Custom token solution is a feature which seems serious lack of AppCenter functionality.

With regards.

**Comment by valnav** [comment]
> [Enter feedback here]
> 
> Hello 👋,
> 
> We would like to use AppCenter as BaaS solution on mobile (iOS+Android) project, and in order to have user data partitions with need to implement authorisation using AppCenter SDK.
> But our UI/UX would like to have native UI for sign in page with login & password inputs.
> I know that AAD B2C supports [custom UI](https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview) for authorisation, but it will be displayed in a web view instead.
> Is it possible to implement AppCenter authorisation without presenting web view but with long & password request from native screen instead?
> I know there is [Custom Token](https://firebase.google.com/docs/auth/admin/create-custom-tokens) solution in Firebase for that, is there something similar in AppCenter?
> 
> With regards.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: f74618cf-1ab9-0977-d07f-26e840058259
> * Version Independent ID: cf027587-4bbf-1b73-fb10-b0e40094ef30
> * Content: [Managing identities with the App Center Auth Service - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/auth/)
> * Content Source: [docs/auth/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/auth/index.md)
> * Service: **vs-appcenter**
> * GitHub Login: @amchew
> * Microsoft Alias: **amchew**

Hi in order to use a native signup/signin experience with B2C - you will need to use [ROPC](https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-ropc). We have it in User Flows and a have sample with [custom policies-ROPC] (https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/scenarios/source/aadb2c-ief-ropc)

**Comment by OlexandrStepanov** [comment]
Hello @valnav,
Thank you for your feedback.
I have investigated the ROPC flow proposed by you above, but have some open questions left:

- I didn't got where to place username/password validation in ROPC flow, so AAD B2C token is generated only if this pair exist on 3rd party service. Supposed flow is:
`iOS app -(username/pass)-> Azure Function -(username/pass)-> 3rd party API -(3rd-party-token)-> Azure Function -(3rd-party-token)-> AAD B2C -(aad-token)-> Azure Function -(aad-token)-> iOS app.
`

- It looks like AppCenter Auth module doesn't have support for ROPC flow, and if one would like to use it with AppCenter Data module, authentication part must be implemented via MSAL library manually. Is this correct?

With regards.

**Comment by caseyniemann** [comment]
@amchew  Can we use this for a phone auth first approach similar to FB Account Kit, Firebase or Twilio?

**Comment by valnav** [comment]
@OlexandrStepanov
I am not sure i understand your supposed flow, but did you see - [Setup ROPC with Azure AD B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-ropc)

**Comment by amchew** [comment]
Hey @OlexandrStepanov, App Center Auth only supports the sign-in user flows and custom policies, so yes the authentication part must be implemented via MSAL library manually. I would love to learn more about your use case and what you've tried with setting up ROPC, would you be available this week for a call? Email me at amchew [at] microsoft [dot] com. 

@caseyniemann If I understand your question correctly, you're asking if Azure AD B2C supports phone auth (e.g. Firebase's phone auth: https://firebase.google.com/docs/auth/android/phone-auth). Let me know if that's correct! We'll get back shortly on this one.

**Comment by caseyniemann** [comment]
@amchew Yes.  Your competition in this space is FB Account Kit and Firebase Phone Auth---they allow that to be a first authentication---instead of a second (like MFA).

**Comment by valnav** [comment]
@caseyniemann - there are few samples for one time pass code and phone number sign in here - https://github.com/azure-ad-b2c/samples

**Comment by angelru** [comment]
Hello, I am going to carry out a new development and I am thinking of using the entire AppCenter platform, the application will have a login with social networks, if I get the native login token like Facebook, I can authenticate more late with AppCenter Auth? in firebase this is allowed

Regards

**Comment by amchew** [comment]
Hey @angelru, thanks a lot for reaching out! Currently you can’t do that but we are open to prioritize based on users’ needs. Would you mind sharing more about your use case on why you need that,, and what Identity management provider (I.e. Firebase, Auth0, custom) you’re using?

Thanks!

**Comment by angelru** [comment]
@amchew  In the Firebase panel of authenticated users there is an option of how they have connected, username and password, social networks, among others...

With the Facebook SDK in xamarin, I logged in natively and received a token, then later with the firebase sdk in authentication, you can receive that token and log in without the need for a web view or external pages.

We must be able to generate the AppCenter Auth token based on the given OAuth token (issued by Google, Facebook ...) without the need for external pages or web view. This is very important.

For example: 
[https://firebase.google.com/docs/auth/android/facebook-login](https://firebase.google.com/docs/auth/android/facebook-login)

I have it running on Firebase, but I would like to migrate everything to AppCenter and the new developments as well.

Regards

**Comment by angelru** [comment]
Any progress with my query?

**Comment by amchew** [comment]
Thanks @angelru, we're getting a lot of feedback about the native sign-in page, and I'm looking into it. Would you have some time today or tomorrow for a quick chat? Email me at amchew [at] microsoft [dot] com if you are interested.

**Comment by angelru** [comment]
@amchew Done.

**Comment by amchew** [comment]
Replied!

**Comment by devStarscream** [comment]
Do you have any updates on this topic, please?

**Comment by thekeviv** [comment]
Hi,
We are building a Xamarin forms app and want to use App Center. We had the same issue that we want to use the native UI on mobile and I went through this thread to look for a solution. Your solution mainly seems to use ROPC. After doing some research on that, ROPC seems to have many limitations and its own page recommendations not to use it as it is relatively insecure and also limited due to no support for personal accounts. Any plans on supporting native sign in experiences using other methods?

**Comment by King-of-Spades** [comment]
This content was deleted per the discontinuation of Auth here: https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/
