### ISSUE TITLE
AppCenter Push iOS - Ability to register for remote notifications manually

### ISSUE THREAD

**Issue by raver99** [MicrosoftDocs/appcenter-docs#59]
Hi,

I am checking out the AppCenter Push SDK for Xamarin Forms (iOS, Android).
I observed that on iOS the SDK registers for remote notifications when I call AppCenter.Start().
One of my requirements (and best practice really) is to ask the user if he wants to receive push notifications in a context that makes sense for him, in a later point in time, not at the app start, because the rejection rate might be very high.

I could not find the possibility to disable the registration done by the SDK so that I could manually do that.

Did I miss something? Or does the SDK not support that.

Thanks

**Comment by jwargo** [comment]
@raver999 The comments feature of the docs is designed to enable customers to suggest changes to the docs or ask clarifying questions about the docs. If you need help with the product, please login to the App Center dashboard and click the blue chat button in the lower-right corner of the page. Our dedicated support resources will answer any questions you have there.

**Comment by jwargo** [comment]
@raver999 Were you able to get your question answered through App Center support?

**Comment by MehrdadMzfr** [comment]
hi @raver999, yes you use `startService()` where input parameter is push. in order words, you can skip adding push in AppCenter.Start() call the above method when you plan to show Push Permission alert, this method won't require app secret.
