### ISSUE TITLE
Access multiple containers from AppCenter Data

### ISSUE THREAD

**Issue by devStarscream** [MicrosoftDocs/appcenter-docs#590]
Hi you all,

I would like to access all containers (collections) available in my database (in Cosmos DB instance) by using AppCenter-Data.
I've read on this document (web page) that is not possible, yet.

That would be interesting having access to all collections in the database right from AppCenter-Data (similarly to Google's Firebase) and choose directly from the SDK on which container (collection) to add my items.

Just few questions:
a) Is there a way to access all containers from AppCenter-Data and from Data SDK?
b) Am I getting wrong Cosmos DB collections with respect to Firebase collections?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a0f404e-cea8-b8b3-917c-c6e69facfc11
* Version Independent ID: 8fab40e9-9152-e137-7de4-c78e6d80bde1
* Content: [Managing Data with the App Center Data Service - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/data/)
* Content Source: [docs/data/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/data/index.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by Zakeelm** [comment]
Hey there!

This is something we're definitely looking into and are going to investigating going forward. As of now, we use a one collection model, which means you can only utilize one collection at a time with the Data service. 

I would love to hear more about your use case and why one collection doesn't fit your needs. Can you share what you're trying to accomplish with me that would require multiple collections?

**Comment by Zakeelm** [comment]
Hi there! 

We don't currently have plans to implement this change. But, we're keeping an eye on additional requests for this and will continue to investigate as re-prioritize as needed. 
I'm going to close this issue for now and we can re-visit it in the future.

Feel free respond here in this thread and we can continue this discussion!
