### ISSUE TITLE
Push FAQ correction on device limits per request

### ISSUE THREAD

**Issue by sum0999** [MicrosoftDocs/appcenter-docs#591]
The device limit for a single push notification request (when sending to devices) is stated to be **20** devices in the FAQ:
https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/faq.md#push-faq

This should be **100** devices 

(The correct value is mentioned in the REST API section of the Push documentation: https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/rest-api.md#using-the-push-api).

**Comment by blparr** [comment]
Hi @sum0999 , thanks for your feedback. I'll let our Push PM know. cc @jwargo

**Comment by jwargo** [comment]
@sum0999 thanks for catching that, I'll make an update.

**Comment by jwargo** [comment]
Fixed.
