### ISSUE TITLE
SDK for React-native

### ISSUE THREAD

**Issue by shamprasadrh** [MicrosoftDocs/appcenter-docs#592]
Hi, 

is SDK available for React native also? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a0f404e-cea8-b8b3-917c-c6e69facfc11
* Version Independent ID: 8fab40e9-9152-e137-7de4-c78e6d80bde1
* Content: [Managing Data with the App Center Data Service - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/data/)
* Content Source: [docs/data/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/data/index.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by blparr** [comment]
Hi, yes, we have a React Native SDK. See docs here: https://docs.microsoft.com/en-us/appcenter/sdk/analytics/react-native
