### ISSUE TITLE
Support for private GitHub orgs that use SSO

### ISSUE THREAD

**Issue by lbrownell-gpsw** [MicrosoftDocs/appcenter-docs#593]
We have private organizations in GitHub and also use single-sign on.  I connected my account to VS App Center, and all I can see are my own account's repos and a public organization we also maintain.

Will there be support for SSO-enabled GitHub organizations?

**Comment by blparr** [comment]
Hi @lbrownell-gpsw , looks like this is a duplicate of https://github.com/microsoft/appcenter/issues/556. Thank you!
