### ISSUE TITLE
Issue after installing latest dll in Android

### ISSUE THREAD

**Issue by naveen-iiit** [MicrosoftDocs/appcenter-docs#594]
Hello,
I have installed the latest dll from nuget package but after installing it is not supporting with latest core UI dlls as they have updated to 28.0.0.1. It is only supporting 26.0.2

**Comment by elamalani** [comment]
@naveen-iiit This doesn't look like a docs issue. Can you please open a support ticket with us by clicking blue icon on the lower right of App Center portal?
