### ISSUE TITLE
Using App ID instead of App Name for Getting Upload URL using API

### ISSUE THREAD

**Issue by venh** [MicrosoftDocs/appcenter-docs#595]
For App Center Upload using API, we first need to get the Upload URL and for this, we need the Owner Name and the App Name, as per the documentation. But, is there a way to use the App Id instead of App Name for getting this Upload URL? It will be much better to use this, I believe. I tried  searching, but didn't get anything. Please help.

**Comment by jwargo** [comment]
@venh I'm not sure if this is possible, but we've asked the PM to respond.

**Comment by botatoes** [comment]
Hi, this is being addressed by one of our API initiatives. Tagging @nrajpurkar to this for tracking.

**Comment by savage7** [comment]
@nrajpurkar Any news on this? We face the same issue.

**Comment by nilofer** [comment]
@savage7 no changes in this, this work has not been prioritized. I am going to close this out here in the Docs repo as this is meant for issues related to documentation. Feel free to create a feature request for this in our [main repo](https://github.com/microsoft/appcenter/issues).
