### ISSUE TITLE
Not able to see any Analytics data in azure portal but can view them in appcenter

### ISSUE THREAD

**Issue by shwetadodiya** [MicrosoftDocs/appcenter-docs#598]
I had created app for iOS and android in Appcenter.ms.

1) Integrated the SDK 2) Added the event. 3) I can see the events and log flow in the appcenter.ms But not in the Application insights on Portal.azure.com.

As show in this i did followed the steps : https://docs.microsoft.com/en-us/appcenter/analytics/export

Adding an Azure Subscription

App belonging to an organization: If you are the organization admin, go to the Manage section under the organization where the app belongs to. App belonging to a user: If you are the app owner, follow these steps. Login to Appcenter portal Go to user settings. Under Azure, click Add subscription Select an existing Azure subscription or create a new one.

Also this :

On the Appcenter Portal, choose the App. Go to the App Settings. Click on Export and select the New Export option. Select blog storage or Application Insights based on your app needs. Select the type of configuration . I had click the customization and added the instrumentation key for the application

I am not able to see any iOS or android analytics in portal. I can see them in appcenter but not in portal

**Comment by hamswan** [comment]
Hi @shwetadodiya , 
Can you check the following?
When you go the export settings, Are you seeing it enabled?
Can you doublecheck that the Application Insights instrumentation key is valid?
Hamsa

**Comment by shwetadodiya** [comment]
Hello,
Thank you for the reply.
I did check the the settings.
1) It is enable.Please check the screenshot.My instrumentation key is also
seems to be valid.but can you guide me how can i check its valid or not.
2) Where can i check the application insight in portal ? i mean in which
tab ?
3) I had added the application insight and instrumentation key for my iOS
and Android both the app.so how can i differentiate the logs for iOS and
android in portal?

Thank you
Shweta

[image: Screen Shot 2019-06-19 at 12.38.30 PM.png]

**Comment by hamswan** [comment]
@shwetadodiya Did you add a screenshot, I can't see the attachment. Can you add again?

**Comment by shwetadodiya** [comment]
Hello,

Here is the screenshot.
I can see AppcenterExport-LogPrototype1 project in azure.portal.

But i can not see any activity logs or Logs(analytics).
In Appcenter.ms i can see the logs , events and overview of chart showing
how much device have the app installed.
But not in the portal.
I did waited for more than 1hr and also try doing the logs. I can see new
logs in appcenter.ms but not on the azure.portal.
Please help.


[image: Screenshot (15).png]


[image: Screen Shot 2019-06-19 at 12.38.30 PM.png]

**Comment by nikitag-ms** [comment]
You mentioned two apps in your original post: for iOS and Android. Based on the name of the AI resource that you mentioned (`AppcenterExport-LogPrototype1`), I could only find your iOS app (which looks like the app you configured your export for). I do not see any events emitted from any client device for the iOS apps. Is it possible that you are emitting events from Android clients and they appear on the corresponding Android App Center app portal, but your export is set up for your iOS app that does not receive any traffic? 

If so, you could use the iKey of the `AppcenterExport-LogPrototype1` resource to set up what we call "custom export" configuration for your Android app. This way both of your apps will send telemetry to Application Insights into a single resource.

**Comment by shwetadodiya** [comment]
Hi Nikita,
Thank you for the reply.

 1) AppcenterExport-LogPrototype1   - This is for iOS but i dont know why i
can not see my android project there in log portal.
I had export the same application-insight instrumentation key in both of my
iOS and android project.
Is this the reason only iOS project is shown and not android.


2) I execute the iOS project and can see some log events in Appcenter for
iOS now but not yet in log portal in AppcenterExport-LogPrototype1.

3) How deep the logs can be done in portal. For eg : if there is any API
called in my project do i have to write events every places for which i
need logs ? or can i detect or diagnostic logs for API request parameter or
response parameter or bad parameter actions etc ?

4)Creating every new application in log portal for testing can detect the
Credit.
I can see that it was 40$ before and now it is 35$ is it because
AppcenterExport-LogPrototype1
is created?

Thank you
Sweta

**Comment by shwetadodiya** [comment]
Hi ,
Thank you for the reply.

 1) AppcenterExport-LogPrototype1   - This is for iOS but i dont know why i
can not see my android project there in log portal.
I had export the same application-insight instrumentation key in both of my
iOS and android project.
Is this the reason only iOS project is shown and not android.


2) I execute the iOS project and can see some log events in Appcenter for
iOS now but not yet in log portal in AppcenterExport-LogPrototype1.

3) How deep the logs can be done in portal. For eg : if there is any API
called in my project do i have to write events every places for which i
need logs ? or can i detect or diagnostic logs for API request parameter or
response parameter or bad parameter actions etc ?

4)Creating every new application in log portal for testing can detect the
Credit.
I can see that it was 40$ before and now it is 35$ is it because
AppcenterExport-LogPrototype1
is created?

Thank you
Sweta

**Comment by YiMysty** [comment]
Hi Sweta!

1. Yes! If you use the same instrumentation key, no matter the app is android or iOS, it will be export to the same application insights application.

2. We queried our system logs, we saw bunch of data exported today, does the AI show the data now? thanks! 

3. You can check the https://openapi.appcenter.ms/#/analytics here for apis or write the app insights query for your application :) 

4. I do not know about the credit, is it azure credit? it may mean the data is exported to your  application insight application :)

Let us know if these answered you question! :D

Thanks,
Mingzi
