### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by olumide-oyetoke** [MicrosoftDocs/appcenter-docs#60]
I've implemented everything in this article. However, I'm facing some issues.

Issue 1. In the below event,
Push.PushNotificationReceived += (sender, e)

if (e.CustomData != null)
        {
            summary += "\n\tCustom data:\n";
            foreach (var key in e.CustomData.Keys)
            {
                summary += $"\t\t{key} : {e.CustomData[key]}\n";
            }
        }
		
e.CustomData is ALWAYS NOT null.
I always get this custom data key/value pair:
"google.ttl", "2419200"

Issue 2. This method never gets called, even though I use LaunchMode = LaunchMode.SingleTop
protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            Push.CheckLaunchedFromNotification(this, intent);
        }
		

Third issue I encounter is this:
1. My main activity uses LaunchMode = LaunchMode.SingleTop
2. While on my main activity I press the back button to dismiss the activity.
3. I send my push notification from appcenter.ms
4. Notification appears in the notification center quite alright.
5. Once I click the notification, my Main activity launches (still doesn't call OnNewIntent as I explained earlier).
6. The e.Title and e.Message are always null in Push.PushNotificationReceived += (sender, e). Although if I had sent the push notification while the app was in the foreground, e.Title and e.Message will not be null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed528dcd-ecaf-697e-c64a-30651d26ff3d
* Version Independent ID: 1e92bbb4-5800-6d31-51ee-c6d5864801d1
* Content: [App Center Push for Xamarin.Android Apps - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-android)
* Content Source: [docs/sdk/push/xamarin-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@luminelx64 The comments feature of the docs is designed to enable customers to suggest changes to the docs or ask clarifying questions about the docs. If you need help with the product, please login to the App Center dashboard and click the blue chat button in the lower-right corner of the page. Our dedicated support resources will answer any questions you have there.

**Comment by elamalani** [comment]
@luminelx64 Thanks for sharing your feedback on Push service. As John mentioned, for any issues related to the product, please open a support ticket with us by clicking on the blue icon on the lower right of App Center portal. Our product team will help investigate the issue. 

Regarding issue 1, it is a known issue on our SDK and we plan to fix it soon. Firebase started sending "google.ttl" as an automatic custom property and we need to filter it in the SDK.
