### ISSUE TITLE
Unclear steps

### ISSUE THREAD

**Issue by agrabhi** [MicrosoftDocs/appcenter-docs#600]
Not clear how to perform step 7 to get custom redirect uri
- which app is it?
- secret is supposed to be 'secret' - is it safe to put it in plain text?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bac43716-ce54-d6bf-8a2a-0260a8b8f1d3
* Version Independent ID: 5f836302-e4f3-897a-c964-c3a60d39ff6b
* Content: [Getting started with the App Center Auth Service - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/auth/getting-started#feedback)
* Content Source: [docs/auth/getting-started.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/auth/getting-started.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by blparr** [comment]
Hi @agrabhi , can you please specify what 'step 7' in the documentation are you referring to?

**Comment by amchew** [comment]
Hey @blparr, I synced with @agrabhi - he's referring to step 7 of https://docs.microsoft.com/en-us/appcenter/auth/getting-started#register-the-application-and-grant-the-application-permissions-on-azure-ad-b2c. Will make the steps clearer.

**Comment by blparr** [comment]
Thanks @amchew , and thanks @agrabhi for the feedback. I will close this issue then.
