### ISSUE TITLE
Incorrect / Out of date reference to HockeyApp

### ISSUE THREAD

**Issue by RyanThomas73** [MicrosoftDocs/appcenter-docs#603]
The documentation references using the 'AppCenter Android App' and provides installation instructions to install the HockeyApp native app. 

The hockey app native app can only be used to install apps that came from hockey app, not apps that were created directly in an app center organization. 

Additionally the hockey app references should likely be removed with the pending retirement of the hockey app sdk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcecd38a-7696-e7f8-853d-d3c12c0b050c
* Version Independent ID: abdba972-b2cd-6c73-83fe-bb1abaac190f
* Content: [Testing Android Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android)
* Content Source: [docs/distribution/testers/testing-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-android.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by dipree** [comment]
Except for the two screenshots everything is still valid. The HockeyApp native app is capable to download apps from both HockeyApp and App Center. It's using App Center APIs only and will be renamed by the time of the shutdown.

If you're facing any issues downloading releases or seeing an app, please reach out to our support.
