### ISSUE TITLE
Clear user id after setting it

### ISSUE THREAD

**Issue by syntax-e** [MicrosoftDocs/appcenter-docs#605]
How does one clear a user id after setting a user id via AppCenter.setUserId("your-user-id"); ?
I assume setting it to null will do the trick but I can't be sure based on the documentation.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 846243f4-8201-c23f-9719-63326aae7572
* Version Independent ID: 5c8f7b51-1102-b427-a650-06cfc11f71e6
* Content: [Other React Native APIs - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/react-native)
* Content Source: [docs/sdk/other-apis/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/other-apis/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by elamalani** [comment]
@bearer-syntaxerror You can clear the user id by setting it to NULL.
