### ISSUE TITLE
Support for Swift bindings

### ISSUE THREAD

**Issue by tharanagaraj** [MicrosoftDocs/appcenter-docs#606]
Right now, we're hit with the error -
Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
The workaround is to create the SwiftSupport library, repackage and then manually upload the IPA. 
Is there a plan to provide out of the box support? We can no longer use AppCenter to automatically upload builds to TestFlight.

**Comment by botatoes** [comment]
Thanks for pointing this out, I will investigate this

**Comment by anywherepilot** [comment]
Is this an issue with the documentation? If it is an issue with App Center itself, consider filing it in the main repository: https://github.com/microsoft/appcenter/issues

**Comment by King-of-Spades** [comment]
Closing due to no response after @anywherepilot's notes.
