### ISSUE TITLE
What is release type?

### ISSUE THREAD

**Issue by voroninp** [MicrosoftDocs/appcenter-docs#607]
Could you provide more details on what release type is and where it us used in distribution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7031e14-f8ab-1d70-6910-72565048b2c1
* Version Independent ID: 23e13d47-a99e-452a-4891-af3147995842
* Content: [Creating and managing apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/creating-and-managing-apps)
* Content Source: [docs/dashboard/creating-and-managing-apps.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/creating-and-managing-apps.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by blparr** [comment]
Hi @voroninp - Release type is just a tag attached to an app. It is not used as part of the distribution flow.

I'll make a docs update to clarify.

Thanks!

**Comment by MSFT-Chris-Barrett** [comment]
Any update on this?  I can see the list of non-custom release types on the docs page linked in the original issue.  But I haven't found anything explaining what effect the different release types might have.  Does "just a tag" mean these are just for humans to look at and maybe use in custom scripts?  And that AppCenter itself has no behavioral differences based on the release type?

**Comment by brunobertechini** [comment]
+1

**Comment by avakhrushev** [comment]
+1 
@blparr Were there really any changes made to the page? I can't seem to find any in the history, and the Release Type section is still confusing. I wonder if this Issue here was closed by mistake, before anything was actually done to fix it.

**Comment by alburdette619** [comment]
+1, just created a new app for the first time in a while and I'm like, what is this?  *Search* 🤔 🤔 🤔

**Comment by rdsedmundo** [comment]
Still confused by this two years later.

**Comment by andidev** [comment]
haha yeah this is sooo confusing. More confusing is you have to chose one. Lets say I chose Production and then under the app you can chose to create code push environments for dev, test and production for this app with release type Production. 
Please 2 years after do something microsoft. 
Love code push by the way, its just more than fantastic and really helps dealing with the awefully long release process! You guys saved a lot of pains for our customers by releasing bugfixes emidiately. Super thanks!

**Comment by tgkess1018** [comment]
Any updates on this, is this just a fancy way to fill in data for viewing from the UI? This seems to be the only bit of documentation on anywhere...
