### ISSUE TITLE
Oops! There was a problem building the app.

### ISSUE THREAD

**Issue by thsbrown** [MicrosoftDocs/appcenter-docs#608]
We have automatically manage devices turned on for our iOS application, yet anytime a tester tries to register a new iOS device and get our app downloaded after it "re signs" it , they get this error.

This has been happening for more then a month now and at this point, and I'm wondering if this is a known issue.

![MVIMG_20190623_105657](https://user-images.githubusercontent.com/2967721/59991860-df78a100-95fd-11e9-9696-cb095c7419b9.jpg)

**Comment by thsbrown** [comment]
I believe i figured out the issue as it pertains to this page here https://docs.microsoft.com/en-us/appcenter/distribution/auto-provisioning. 

I believe the error occurred because I renamed the provisioning profile and the name needed to match exactly that of the app id on the apple developer console. I had named my provisioning profile originally "App Name - iOS". Once i changed it to "App Name" it worked correctly.

If my above assumption is incorrect, an easy way to find out what you need to name the provisioning profile to is try to re-sign your app manually for a device, when it errors out it will tell you it could not find the provision profile for YOUR_APP_HERE. Whatever name it uses for YOUR_APP_HERE, that's what you need to name your provision profile to.

**Comment by iageoghe** [comment]
Hi @Spartanace1024, are you a collaborator on the app and if so, did you receive a "<App Name> failed to add devices" email from us?

**Comment by nilofer** [comment]
@spartanace1024 are you still experiencing this issue? I'm closing this for now, but feel free to re-open if you still need assistance from us.
