### ISSUE TITLE
Breakpad binaries?

### ISSUE THREAD

**Issue by sseyod** [MicrosoftDocs/appcenter-docs#609]
Hi! Your instructions require us to first build Google's Breakpad tool; however, I'm unable to figure-out how to get that build working (macOS host). Might I strongly urge you to provide pre-build binaries for x86, arm, arm64, x86_64 etc.? I presume you must have already done this, otherwise you'd not have been able to test your solution. Without a compiled Breakpad, I'm unable to use your Android NDK code...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbf28d0-dedf-3e44-7c5b-4d2a2ed22c02
* Version Independent ID: 353d51d2-d428-c95d-2746-1d8b285a312d
* Content: [Android NDK - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk#feedback)
* Content Source: [docs/diagnostics/Android-NDK.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/Android-NDK.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by sseyod** [comment]
I was able to find just one location that I could use to help me build the libraries for Android.

The instructions I followed were in last section here:
    http://zompi.pl/symbolicating-crash-dumps-for-android-in-unreal-engine-4/#lastchapter
I had to edit APP_API three times and remake, once for each target (x86, armeabi-v7a, x86_64)

It would be great for future developers if you could reproduce and verify these steps, and document them.

**Comment by jwargo** [comment]
@sseyod thank you for the suggestion, I'll assign this to the PM to take a look.

**Comment by sseyod** [comment]
@jwargo furthermore, is there any reason why dump_syms can't be fixed so that it can be run *from macOS* to work with Android ELF format files?

Thanks, Pete

**Comment by jwargo** [comment]
@sseyod I have no idea as I didn't understand much of what you asked :-). The PM is out for the next three weeks, but I'll get you an answer as soon as I can.

**Comment by sseyod** [comment]
@jwargo No worries John, thanks for helping :) Hopefully this'll make sense to the PM! Pete

**Comment by sseyod** [comment]
I just wanted to add - it is great that Microsoft are open to receiving feedback from developers. Top stuff!

**Comment by jwargo** [comment]
@sseyod Thanks!

**Comment by winnie** [comment]
@sseyod thanks for the feedback and apologies for the delay! We have an engineering team looking into our NDK support to fix a few issues in the next week or so. We'll address your comments and post updates then.

Thank you for your patience!

**Comment by sseyod** [comment]
Thanks. We're not seeing any crash reports coming through from the NDK crash reporting system, which makes me think that the current implementation might be broken (you mentioned there are a few issues)... so, looking forward to updates as they arrive! Pete

**Comment by jbazeley** [comment]
Hi, I also see no native crashes on the appcenter UI for our app.

If I set AppCenter.setLogLevel(Log.VERBOSE), I see a bunch of logs which *look like* the send succeeded:
e.g.

2019-07-12 16:28:47.432 12071-12129/my_app D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2019-07-12 16:28:47.650 12071-12242/my_app V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2019-07-12 16:28:47.651 12071-12242/my_app V/AppCenter: Headers: {Content-Encoding=gzip, Install-ID=(redacted), App-Secret=(redacted), Content-Type=application/json}
2019-07-12 16:28:47.675 12071-12242/my_app V/AppCenter: {"logs":[{"type":"errorAttachment","timestamp":"2019-07-12T15:28:45.015Z","device":{"sdkName":"appcenter.android","sdkVersion":"2.1.0","model":"Pixel","oemName":"Google", etc. redacted
2019-07-12 16:28:49.165 12071-12242/my+app V/AppCenter: HTTP response status=200 payload=CorrelationId: (redacted)  ReasonCode: Success 
2019-07-12 16:28:49.227 12071-12129/my_app D/AppCenter: Deleting logs from the Persistence database for groupErrors with (redacted)
2019-07-12 16:28:49.227 12071-12129/my_app D/AppCenter: The IDs for deleting log(s) is/are:
2019-07-12 16:28:49.227 12071-12129/my_app D/AppCenter: 	3

Let me know if you need more info and I'll open a ticket.

Cheers

**Comment by sseyod** [comment]
Thanks @jbazeley, glad to know it wasn't just me :) Pete

**Comment by winnie** [comment]
Apologies for the delay. Our engineering team is looking into our NDK support now. We'll get back to you shortly.

Thanks for your patience!

**Comment by jp-andre** [comment]
Hi @sseyod,

While working on this I made myself a script to easily run `dump_syms` and generate a ready-to-upload archive. This uses Docker to compile and run the tool on a Linux VM:
https://github.com/jpeg-ms/breakpad-tools-appcenter

Also, note that you probably don't need to set APP_API. All ABIs will be compiled by default, see: https://developer.android.com/ndk/guides/application_mk

I hope this helps!
Sorry if this isn't the most convenient solution.

**Comment by sseyod** [comment]
Thanks for that. I, too wrote a similar script. For most developers, I'd have thought that that sort of scripting is probably a bridge too far in terms of complexity, and will stop them using Microsoft's Crash Reporting for the Android NDK. Come on Microsoft : provide a native Mac solution :) Pete

**Comment by marko88** [comment]
I still have an issue with reporting JNI crashes and presenting them on AppCenter web side. I can see in log that dump file is proceed and sent successfully, but somehow they don't appear in appcenter, neither in unsymbolicated crashes part. Do you have any news on this, what you suggest since the reporting jni crashes is very important to me?

**Comment by winnie** [comment]
Hey @marko88 do you mind starting a support thread via the blue chat bubble in App Center? This will put you in direct contact with our engineering and support team so they can take a closer look. Thanks!
