### ISSUE TITLE
Too many dependencies for basic crash analytics

### ISSUE THREAD

**Issue by dtaylorus** [MicrosoftDocs/appcenter-docs#61]
I would like to use AppCenter for crash analytics, but I count about 10 dependencies including NewtonSoft.Json and SQLLite when adding the NuGet package Microsoft.AppCenter.Analytics. I have a significant investment in eliminating dependencies (and startup time) in my application, and this large dependency overhead unfortunately makes AppCenter unusable for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ece9ab-9965-2ddf-34b6-44f0f61fe599
* Version Independent ID: 16261b98-a85e-060f-ccf4-3a24f5f14c4c
* Content: [Get Started with UWP - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/uwp)
* Content Source: [docs/sdk/getting-started/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@dtaylorus Do you have a question about the docs?  If you have feedback about the product or need help with the product, please use the chat option in App Center (the blue chat icon in the lower-right corner of most App Center pages).
