### ISSUE TITLE
Repl window is not opening

### ISSUE THREAD

**Issue by techiesalman** [MicrosoftDocs/appcenter-docs#610]
Hi, 

I am trying to open Repl by app.Repl() method but the window is not opening. What can be the reason behind this. I tried to find the solution by googling but to no avail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c51913-785c-84d7-8dc4-b50413fbf804
* Version Independent ID: 4ecc47b2-ca24-b8f9-10c9-2ae7f990dd27
* Content: [Working with the REPL - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-repl?tabs=vswin#feedback)
* Content Source: [docs/test-cloud/uitest/working-with-repl.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/working-with-repl.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@salmank63 The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
