### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sseyod** [MicrosoftDocs/appcenter-docs#611]
Your example code has a typo.

You need to remove the "." from the end of this line:

Crashes.getMinidumpDirectory().thenAccept(new AppCenterConsumer&lt;String&gt;() {.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbf28d0-dedf-3e44-7c5b-4d2a2ed22c02
* Version Independent ID: 353d51d2-d428-c95d-2746-1d8b285a312d
* Content: [Android NDK - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk#feedback)
* Content Source: [docs/diagnostics/Android-NDK.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/Android-NDK.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by jwargo** [comment]
@sseyod thanks for catching that, fixed.
