### ISSUE TITLE
dump_syms

### ISSUE THREAD

**Issue by sseyod** [MicrosoftDocs/appcenter-docs#613]
You say to use dump_syms, but this doesn't seem to work on macOS.

I get a message like "...so: file is neither a fat binary file nor a Mach-O object file"

I've read comments (e.g. https://groups.google.com/forum/#!topic/google-breakpad-discuss/XT8bh08JE4g) saying that to use dump_syms for an Android binary, would require dump_syms to be run on Linux. Can you please advise as to what macOS-based developers, or indeed Windows-based developers, are supposed to do?

Thanks, Pete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbf28d0-dedf-3e44-7c5b-4d2a2ed22c02
* Version Independent ID: 353d51d2-d428-c95d-2746-1d8b285a312d
* Content: [Android NDK - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk#feedback)
* Content Source: [docs/diagnostics/Android-NDK.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/Android-NDK.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by sseyod** [comment]
Furthermore, is the intention that we're supposed to use https://github.com/microsoft/appcenter-sdk-android-breakpad instead?

If so, then that project has various build problems that need fixing (I've logged them there...)

Please advise!

Pete

**Comment by sseyod** [comment]
Just to clarify further, I installed a Linux VM on my mac, pulled your code from GitHub; found it didn't build; had to patch it for Linux; then got it built; I was then able to use dump_syms on Linux from the VM to create the symbols.zip file ... not easy! :)

**Comment by sseyod** [comment]
@jwargo Furthermore, is there any reason why appcenter CLI doesn't contain a simple command to do all this automatically?

Create symbols.zip that covers all the so files in the distribution:
appcenter crashes make-ndk-symbols-zip

**Comment by jwargo** [comment]
@sseyod I can't answer your question, but I'll ask the PM to respond. Isn't this similar to #609 ??

**Comment by winnie** [comment]
Apologies for the delay. Our engineering team is looking into our NDK support now. We'll get back to you shortly. 

Thanks for your patience!

**Comment by jp-andre** [comment]
Hi @sseyod

I've responded to #609, pointing to https://github.com/jpeg-ms/breakpad-tools-appcenter
I hope this helps and we will keep looking into improving this.
