### ISSUE TITLE
Error: Uploading to a HockeyApp store app is not supported

### ISSUE THREAD

**Issue by venh** [MicrosoftDocs/appcenter-docs#614]
I have apps that are getting currently uploaded to Hockey App. But since Hockey App will be deprecated after a couple of months, we are currently in the process of migrating / uploading our mobile builds to App Center. We have both Android and iOS builds for various configurations like Debug, Beta, Automation, Production and so on. I followed the documentation provided in the link [https://docs.microsoft.com/en-us/appcenter/distribution/uploading](https://docs.microsoft.com/en-us/appcenter/distribution/uploading) and was successfully able to upload both Android and iOS builds for various configurations to App Center. But only for Android Production configuration, I get an error "Error: Uploading to a HockeyApp store app is not supported" in the first step itself when I am trying to get an upload url using the following curl command. Can anyone please help me? I am not sure why this alone is failing.

`curl -s -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-API-Token: MyToken' https://api.appcenter.ms/v0.1/apps/org-name/Android-Production/release_uploads`

**Comment by jwargo** [comment]
@venh The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
