### ISSUE TITLE
Benefits

### ISSUE THREAD

**Issue by stevehurcombe** [MicrosoftDocs/appcenter-docs#615]
It's not clear to me why we'd want to use appcenter.ms over using AD B2C directly. 
It would be good to document why adding another dependant service is worth it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bac43716-ce54-d6bf-8a2a-0260a8b8f1d3
* Version Independent ID: 5f836302-e4f3-897a-c964-c3a60d39ff6b
* Content: [Getting started with the App Center Auth Service - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/auth/getting-started#feedback)
* Content Source: [docs/auth/getting-started.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/auth/getting-started.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by jwargo** [comment]
@stevehurcombe we call that App Center Magic - that special stuff that App Center does to make this easier. We talked about it here: https://mybuild.techcommunity.microsoft.com/sessions/77048?source=sessions#top-anchor but I'll ask the PM to take a look at making this more clear in the docs.

**Comment by amchew** [comment]
@stevehurcombe thanks for the feedback and tip to make the docs and value prop clearly! I'll add that section in by tomorrow, and update you again.

**Comment by amchew** [comment]
Hey @stevehurcombe I just made a PR to clearly state the value proposition of App Center Auth, you should see the changes shortly. Thanks again for the tip!

**Comment by amchew** [comment]
Hi @stevehurcombe! I updated the fourth paragraph here: https://docs.microsoft.com/en-us/appcenter/auth/ to include the value proposition for Auth.

Thanks for the tip! :)

**Comment by stevehurcombe** [comment]
Thanks Amanda. 
I didn't think this sentence was correct though:

"It is also currently the only way to use the signed-in user's identity with other App Center services like Data and Push."

The user's identity can be set using the SDK.

**Comment by jwargo** [comment]
@stevehurcombe that’s true. @amchew can you please make that edit?

**Comment by amchew** [comment]
@stevehurcombe great point. I've submitted a new PR to correct my statement. Very nice catch!
