### ISSUE TITLE
Docs incomplete for android

### ISSUE THREAD

**Issue by MakhouT** [MicrosoftDocs/appcenter-docs#617]
In my opinion it's definitely needed to add manual linking process for android. I've spent half a day looking why iOS is running correctly and android isn't. 
I did react-native link and it did not link android correctly. I also created a new project to try it there and it was exactly the same.

In the end the culprit was in MainApplication.java
The following lines weren't added
```
            new AppCenterReactNativeCrashesPackage(MainApplication.this, getResources().getString(R.string.appCenterCrashes_whenToSendCrashes)),
            new AppCenterReactNativeAnalyticsPackage(MainApplication.this, getResources().getString(R.string.appCenterAnalytics_whenToEnableAnalytics)),
            new AppCenterReactNativePackage(MainApplication.this)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#feedback)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by jwargo** [comment]
@MakhouT thanks for the feedback; the requirement to do manual linking should be rare as React Native is supposed to take care of it for you. I'll ask the PM to take a look at doing an update.

**Comment by jwargo** [comment]
@MakhouT engineering's working on a doc update, should have it published in the next couple of days.

**Comment by dbeff** [comment]
Please also keep in mind that the command link is not supported in the new version of React Native. It's a very recent version and with a very important change called autolinking. Based on that the documentation should also include caveats of use link after ver 0.60 of react native.

https://facebook.github.io/react-native/blog/2019/07/03/version-60#native-modules-are-now-autolinked

**Comment by MakhouT** [comment]
Correct @dbeff 
I was using 0.59.10

**Comment by dhei** [comment]
Hey folks,

We are working on docs update of React Native manual android linking for 0.59.x.

@dbeff, yes we are actively working on the autolinking support of React Native 0.60.0. For anyone interested, https://github.com/microsoft/appcenter-sdk-react-native/issues/613 is the one tracking that.

**Comment by felipeptcho** [comment]
For me, it didn't work on Android emulator, but it worked on a real device.

**Comment by felipeptcho** [comment]
Checking the logs, it seems the emulator was not able to make the request (domain not found).

**Comment by jwargo** [comment]
@felipeptcho if you're having problems getting this to work, please reach out to our dedicated support team. In the lower-right corner of any App Center page there's a blue chat button - that connects you to our support team.
