### ISSUE TITLE
Confusing Instructions

### ISSUE THREAD

**Issue by alaskanrogue** [MicrosoftDocs/appcenter-docs#619]
It is not clear in Step 1 what to modify, i.e. add or remove, because there are two sub-steps which both say remove. In the first sub-step, although it says to remove, the details say add.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb6a101-b62b-95c8-32e5-5769bd116457
* Version Independent ID: c0c08f43-46d6-6929-4eda-8e293fbbcd4f
* Content: [How to add Firebase SDK - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/migration/xamarin-android)
* Content Source: [docs/sdk/push/migration/xamarin-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/migration/xamarin-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@alaskanrogue what is not clear? The instructions tell you to remove both. You're whacking two elements from the project's `AndroidManifest.xml` file.

**Comment by alaskanrogue** [comment]
John,

 

                The two highlighted elements in the code shot saying “Add these lines”…

 



 



Marc W. George

Consulting Senior Software Architect and Methodologist

Thought, Systems Consulting & Engineering, Inc.

414 Metropolitan Blvd., Pasadena, MD 21122

(443) 562-6482 | Skype: live:mwg_7 |  <https://www1.gotomeeting.com/join/638050721> GoToMeeting (805) 309-0010 Access Code: 638-050-721
S-S | 6 AM – 10 PM EST

 

 <http://www.linkedin.com/pub/marc-george/0/a5b/505> 

NOTICE OF CONFIDENTIALITY.  The information transmitted herein is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material.  Any review, retransmission, dissemination or other use of this information by anyone other than the intended recipient is prohibited.  If you receive this in error, please contact the sender and destroy all records of the transmission.

**Comment by jwargo** [comment]
@alaskanrogue aaah, I see the issue now, thanks. I’ll update it
