### ISSUE TITLE
Event Metric Limits

### ISSUE THREAD

**Issue by okulygin** [MicrosoftDocs/appcenter-docs#62]
"The maximum number of distinct custom events that can be tracked daily is 200." Is it per App, device or user ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f69ecd-7f5b-570c-4777-c68acdacaf70
* Version Independent ID: 2987abb6-1dad-c456-827a-600952e416ee
* Content: [Understanding App Center Events Metrics - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/analytics/event-metrics#limits)
* Content Source: [docs/analytics/event-metrics.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/event-metrics.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by blparr** [comment]
Hello @okulygin, this limit is per app.

**Comment by okulygin** [comment]
Thank you for prompt response. Would be great if it was possible to increase this limit (by providing customer-owned data store, etc...), because for the apps with significant active users this limit is a really low, which makes it unusable sometimes...

**Comment by blparr** [comment]
Thanks for the feedback! We will consider it for our future improvements.

**Comment by jfichtner** [comment]
+1 on this! 200 total events per app is extremely low. To get useful data, I would expect a typical user to hit 15 or 20 events per use. This means the limit would be hit after about 10 to 15 uses per day!

**Comment by blparr** [comment]
@jfichtner You can define up to 200 distinct event names per app (not per user) - If 15 of your users run into one of these 200 events, they will be sum in the "Users" column, and only one of these 200 events will be counted.

Hope this clarifies!
