### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by stevehurcombe** [MicrosoftDocs/appcenter-docs#621]
I gather that best practice for CosmosDB is to store the primary database connection in the cloud somewhere so that clients only ever have access to their own data. 

I'm hoping that this is the case, in which case it would be great to have a simple architecture diagram calling this out to highlight good design practice.

Thanks for the excellent work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67362701-625c-9ccb-03ec-04ae0f52e583
* Version Independent ID: 47f5204b-96c5-f74f-dade-117ad1a4a733
* Content: [Understanding Cosmos DB - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/data/understanding-cosmos-db)
* Content Source: [docs/data/understanding-cosmos-db.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/data/understanding-cosmos-db.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@stevehurcombe thanks, I’ll have the PM take a look at making an update.

**Comment by Zakeelm** [comment]
I can definitely look into how we can make this happen. To make sure i'm understanding correctly, you're suggesting something that does a bit more in depth than the current diagram, yes?

![image](https://user-images.githubusercontent.com/31293287/61004437-e3edcb00-a31a-11e9-9b09-45e5a6121fef.png)

**Comment by stevehurcombe** [comment]
Hi Zakeelm, 
I think that's a great diagram, I wouldn't make it more complicated. It shows the partitioning quite well.

I think you need a new diagram that illustrates (in a simpler way) how the permission broker is working. I worked it out using this article (amongst others): 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-cosmosdb-auth

This one is useful too:

https://codemilltech.com/connecting-to-cosmos-without-conx-strings/

Best regards
Steve

**Comment by King-of-Spades** [comment]
This content was deleted per the discontinuation of Data here: https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/
