### ISSUE TITLE
App Center Inconsistend instructions for Android, IOS, UWP

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/appcenter-docs#626]
App center instructions to install App Center Analytics and Crashes nugets inconsistent; 
- on UWP, missing info about Crashes nuget; 
- on UWP, adding secret key and everything else according to instructions is not working, neither Analytics nor Crashes section show nothing
- on IOS/Droid, the code sample to start app center tracking (where you enter your secret key) provided by App Center once you create new app is missing semi-column at the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2add0f-2806-8bfa-92d5-cc3fdd1e1055
* Version Independent ID: c572b535-a780-fba3-0845-f5127d98d7d6
* Content: [UWP SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/uwp#feedback)
* Content Source: [docs/sdk/troubleshooting/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@dinobu I’ll have the PM take a look.

**Comment by elamalani** [comment]
@dinobu We are improving the experience for UWP crash reporting in App Center. Once that is done, we will update the getting started instructions on using the crashes NuGet.

Please contact App Center support if you are unable to see any data in Analytics and Crashes once the SDK is integrated into a running app. 

Can you point to the page link where you see a missing semi colon?

**Comment by dinobu** [comment]
> @dinobu We are improving the experience for UWP crash reporting in App Center. Once that is done, we will update the getting started instructions on using the crashes NuGet.
> 
> Please contact App Center support if you are unable to see any data in Analytics and Crashes once the SDK is integrated into a running app.
> 
> Can you point to the page link where you see a missing semi colon?

Create an iOS app for Xamarin in App Center > go to Overview and select Xamarin Forms tab.  In there you will see this:
![app center-1](https://user-images.githubusercontent.com/40807298/60999392-eac31080-a30f-11e9-8f40-e75129016f76.png)

**Comment by dinobu** [comment]
> @dinobu We are improving the experience for UWP crash reporting in App Center. Once that is done, we will update the getting started instructions on using the crashes NuGet.
> 
> Please contact App Center support if you are unable to see any data in Analytics and Crashes once the SDK is integrated into a running app.
> 
> Can you point to the page link where you see a missing semi colon?

is there any ETA where to expect working UWP Xamarin Forms update and documentation update?  

is there any link about this plan you can provide?

Thanks

**Comment by elamalani** [comment]
Here is the [roadmap ](https://github.com/Microsoft/appcenter/wiki/Roadmap#hockeyapp ) link for improved UWP support.

**Comment by elamalani** [comment]
Thanks for reporting the portal bug. We will fix it.

**Comment by dinobu** [comment]
> Thanks for reporting the portal bug. We will fix it.

Created https://github.com/microsoft/appcenter/issues/697

**Comment by winnie** [comment]
Closing this issue. As mentioned by Ela, this is expected as the team is working on adding full diagnostics support for UWP apps. To keep track of progress on the UWP work, I recommend following the App Center [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) and [iteration plan](https://github.com/Microsoft/appcenter/wiki/Iteration-plans).
