### ISSUE TITLE
Crashes on UWP (Xamarin.Forms)

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/appcenter-docs#628]
First, I dont see Crashes working at all on UWP.

Also, I read your document and it is confising to me in these 2 points:

1. When you say crash reporting on UWP is only supported for AppCenter.Start and not through call to Crashes, then what is the point of it?  AppCenter.Start is what is called on App start.  That basically means no crash will ever been reported on UWP if I understand it correctly.

2. When you say "Crash reporting on Windows requires the app to be distributed through the Microsoft Store", that means crash reporting is only visible once you actually have an app in MS store?  That is pretty much saying distribute your app and trust us we will report crashes.  This is very conflicting with the above statement that crashes are only supported on AppCenter.Start and not on Crashes.  

Can you clarify these points please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5756765e-fef2-e8d9-f8d9-5c01690095b8
* Version Independent ID: b474e30a-6e59-97fc-476a-92be5ec3a01a
* Content: [App Center Crashes for UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp)
* Content Source: [docs/sdk/crashes/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by annakocheshkova** [comment]
Hi there, what this means is that the only thing available right now is actually starting the crash service. This doesn't mean that it won't work at all - basic crash functionality will work, but all the other calls like `isEnabled`/`setEnabled` are not available.
2nd point you have understood correctly. As we already mentioned in the docs, we plan to improve App Center's Windows support in Summer 2019 and address all these limitations. 
Here is the [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#hockeyapp) link for improved UWP support.

**Comment by dinobu** [comment]
> Hi there, what this means is that the only thing available right now is actually starting the crash service. This doesn't mean that it won't work at all - basic crash functionality will work, but all the other calls like `isEnabled`/`setEnabled` are not available.
> 2nd point you have understood correctly. As we already mentioned in the docs, we plan to improve App Center's Windows support in Summer 2019 and address all these limitations.
> Here is the [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#hockeyapp) link for improved UWP support.

Thanks Anna, I understand you are working to improve it but what I am trying to point to is that 2nd point is pretty much saying "you cannot see how it looks, how good it reports, what it reports until you implement it and ship it to customer through playstore but as we explained in 1st point, it may or may not work, most likely wont work".  It is basically saying "stay away from this".  The documentation and provided information is literally conflicting itself.

**Comment by winnie** [comment]
Hi @dinobu - we understand this is a major limitation and we have plans to support crash reporting for UWP apps not distributed through the store (looking at the September time frame). 

If you would like to better understand what App Center crash reporting has to offer, I'm happy to chat. Feel free to start a support thread (blue chat bubble) and our support team will triage the ticket accordingly. 

Thanks for your patience!

**Comment by dinobu** [comment]
> Hi @dinobu - we understand this is a major limitation and we have plans to support crash reporting for UWP apps not distributed through the store (looking at the September time frame).
> 
> If you would like to better understand what App Center crash reporting has to offer, I'm happy to chat. Feel free to start a support thread (blue chat bubble) and our support team will triage the ticket accordingly.
> 
> Thanks for your patience!

Thanks @winnieli1208, I think it is best to see it my self once it is supported.

**Comment by winnie** [comment]
We'll let you know as soon as we have something for you to try out. In the meantime, you can follow our [roadmap]( https://github.com/microsoft/appcenter/wiki/Roadmap) for updates.

Closing this issue. Thanks!

**Comment by JanaAbhijit** [comment]
> We'll let you know as soon as we have something for you to try out. In the meantime, you can follow our roadmap for updates.
> Closing this issue. Thanks!

Do we have any updates on UWP Crashes for Xamarin.Forms for sideloaded apps ?  In the roadmaps " Support sideloaded UWP apps" shows as worked not started, Appriciate some updates on this.

**Comment by dinobu** [comment]
> We'll let you know as soon as we have something for you to try out. In the meantime, you can follow our [roadmap](https://github.com/microsoft/appcenter/wiki/Roadmap) for updates.
> 
> Closing this issue. Thanks!

This should not be closed, it is not resolved.  Any updates on this?  Thanks
