### ISSUE TITLE
FACTURAS

### ISSUE THREAD

**Issue by wars23** [MicrosoftDocs/appcenter-docs#63]
DOCUMENTOS XML

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb42032-a67b-b601-7ef0-bdf1c8838f73
* Version Independent ID: 4d052b88-6fe1-358e-47a7-4d2687f02c10
* Content: [App Center Push for Universal Windows Platform - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/sdk/push/uwp)
* Content Source: [docs/sdk/push/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@wars23 Do you have a question or comment about the docs?
