### ISSUE TITLE
Distribute Unity via appcenter

### ISSUE THREAD

**Issue by christopheph** [MicrosoftDocs/appcenter-docs#632]
Hi,

We are trying to distribute a unity application (build with unity editor). We saw that appcenter allows to upload a .zip file, but this does not work, because appcenter cannot find any versioning infos in the zip package. Is there some specific file needed in the package ? I do  not find any information about this error.

Are there other manner to create packages for that kind of project ?

Thank you in advance,

Best regards,

Christophe

**Comment by jwargo** [comment]
@christopheph The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
