### ISSUE TITLE
[UWP] Does not work build under Windows 10.0.14393

### ISSUE THREAD

**Issue by surensaluka** [MicrosoftDocs/appcenter-docs#634]
I have tested this and found when you have the minimum target version below build 14393 it does not work. When I set the current configuration to
Min version build 14393 and
Target version build 17763 it works. Why this not supporting Windows 10 versions below 14393?

**Comment by jwargo** [comment]
@surensaluka I’ll ask the PM to take a look at your comment. However, the comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by nilofer** [comment]
@surensaluka please reach out to support regarding this. Thanks!
