### ISSUE TITLE
Is Data service supported for React-Native? 

### ISSUE THREAD

**Issue by shamprasadrh** [MicrosoftDocs/appcenter-docs#635]
I do not see any documentation for React-Native for Data service. Is it supported? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1f06a24-389f-8986-83b3-5f12d34d4e35
* Version Independent ID: 904c6d8f-ea31-d36c-ec1d-b70df33192e3
* Content: [Getting started with the App Center Data Service - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/data/getting-started)
* Content Source: [docs/data/getting-started.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/data/getting-started.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by jwargo** [comment]
@shamprasadrh no, not at this time, but it’s on our roadmap.

**Comment by Zakeelm** [comment]
Hey there, React Native isn't currently supported, but it's something we're actively working on and should have some news to share on this soon!
