### ISSUE TITLE
Broken link in menu

### ISSUE THREAD

**Issue by fredrikhaglund** [MicrosoftDocs/appcenter-docs#636]
Menu item Build &gt; Xamarin &gt; Android is "broken" since it leads to "https://docs.microsoft.com/en-us/".

Go to: https://docs.microsoft.com/en-us/appcenter/build/xamarin/android/

The menu path is Build &gt; Xamarin &gt; Introduction &gt; Introduction.

So there are two pages titled "Introduction" under Build &gt; Xamarin in the menu. I think there is a miss-configuration and the second "Introduction" should be the "Android" page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936f10b5-b3b4-d755-17ea-b877ca7749f9
* Version Independent ID: 2b404b45-dbfe-182a-b1bc-78f6c1cd9200
* Content: [App Center Build for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/xamarin/)
* Content Source: [docs/build/xamarin/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/xamarin/index.md)
* Service: **vs-appcenter**
* GitHub Login: @daadam
* Microsoft Alias: **daadam**

**Comment by nilofer** [comment]
Thanks for pointing this out @fredrikhaglund. Got a fix on the way!

**Comment by nilofer** [comment]
All fixed! Closing this out.
