### ISSUE TITLE
Deleting mapping files?

### ISSUE THREAD

**Issue by gwharvey** [MicrosoftDocs/appcenter-docs#637]
Please add instructions on how to delete a mapping file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e9c7ee-7522-cc0a-7ff1-7748f93efa83
* Version Independent ID: 683bf206-d70c-192b-6f59-f03dd1f66885
* Content: [Android ProGuard - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-proguard#feedback)
* Content Source: [docs/diagnostics/Android-ProGuard.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/Android-ProGuard.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by winnie** [comment]
Hi @gwharvey you can use the delete symbols API to delete a mapping file: https://openapi.appcenter.ms/#/crash/symbolUploads_delete 

I will update our docs to reflect that. Thanks for your feedback!

**Comment by winnie** [comment]
Docs have been updated: https://docs.microsoft.com/en-us/appcenter/diagnostics/android-proguard#deleting-a-mappings-file. 

Closing this issue.
