### ISSUE TITLE
Not clear what to do if `OnStartup` method doesn't exist for WPF app

### ISSUE THREAD

**Issue by cainejette** [MicrosoftDocs/appcenter-docs#638]
We should mention that if it does not exist, you can override it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e799e45-8feb-d74c-4e25-3bdf49301766
* Version Independent ID: b6aef403-76f7-5df2-aa5d-3ed66397893d
* Content: [Get Started with WPF/WinForms - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms#feedback)
* Content Source: [docs/sdk/getting-started/wpf-winforms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/wpf-winforms.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by winnie** [comment]
Docs are updated: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms#5-start-the-sdk

Closing this issue. Thanks!
