### ISSUE TITLE
Distribute.ReleaseAvailable is not called on Unity Android

### ISSUE THREAD

**Issue by archerfob** [MicrosoftDocs/appcenter-docs#639]
I am trying out the Distribute module with implementing my own UI to handle Distribute.ReleaseAvailable. However, this callback is never called. Distribute.ReleaseAvailable = OnReleaseAvailable; is put in Awake() but still no luck. Please help. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 553de3d3-ad6c-f329-13bc-e55cbf00e6a5
* Version Independent ID: f9f58f2f-0b4f-67bf-1568-a6d89ed48654
* Content: [App Center Distribute for Unity - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/unity)
* Content Source: [docs/sdk/distribute/unity.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/unity.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by AnastasiaKubova** [comment]
Hi, @archerfob ! Thank you for getting in touch! Could you please share the verbose [logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/unity#adjust-the-log-level)?

**Comment by AnastasiaKubova** [comment]
@archerfob we haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.
