### ISSUE TITLE
Clarification on background notifications

### ISSUE THREAD

**Issue by olumide-oyetoke** [MicrosoftDocs/appcenter-docs#64]
Hi,

I need a clarification on this note:
"The background notification click callback does NOT expose title and message. Title and message are only available in foreground pushes."

What about e.Custom data? Does clicking a background notification expose the custom data. If it does, I could make use of it.

Also, could you please give an example of using Push.PushNotificationReceived in an app whose launcher activity is a splashscreen. Becasue in that case, the push notification event handler will be configured in OnCreate method of a temporary Activity (splash screen)

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed528dcd-ecaf-697e-c64a-30651d26ff3d
* Version Independent ID: 1e92bbb4-5800-6d31-51ee-c6d5864801d1
* Content: [App Center Push for Xamarin.Android Apps - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-android#subscribe-to-the-push-event)
* Content Source: [docs/sdk/push/xamarin-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by elamalani** [comment]
@jwargo The DRI from the SDK team should answer this one.

**Comment by guperrot** [comment]
CustomData is always available.
For splash screen have you tried modifying the StartActivity from Splash to Main like this:

```
var intent = new Intent(this, typeof(MainActivity));
intent.PutExtras(Intent.Extras); // copy push info from splash to main, intent contains the push information
StartActivity(intent);
```
