### ISSUE TITLE
Cannot disable notifications for some users

### ISSUE THREAD

**Issue by ikrasnoselskikh** [MicrosoftDocs/appcenter-docs#640]
Hi!
Some users of our company cannot disable email notifications.
It caused by click on the user icon doesn't show dropdown with Account Settings option. So user cannot enter into Account Settings window. These users have such permissions as another users of company and locate in one distribution group.
So we cannot find a way to customize or delete email notifications for some our users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e1cc1d-912c-61a7-04b3-1215b1d2e3a8
* Version Independent ID: 6fdf262f-0133-8ffb-81a6-fd24eb1a3b8e
* Content: [App Center Email Notifications Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/email-notifications/#feedback)
* Content Source: [docs/dashboard/email-notifications/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/email-notifications/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by amchew** [comment]
Hey @ikrasnoselskikh! May I ask if you can take a screenshot of the account settings page? I am testing this out on https://appcenter.ms, and it's working for me.

**Comment by ikrasnoselskikh** [comment]
Hi @amchew! That is it:
/Users/ivankrasnoselskikh/Downloads/2019-07-26 15.03.27.jpg

**Comment by ikrasnoselskikh** [comment]
![2019-07-26 15 03 27](https://user-images.githubusercontent.com/38478214/61953625-2ec43f80-afb7-11e9-89c0-08763eb0ad05.jpg)

**Comment by amchew** [comment]
Hi @ikrasnoselskikh, got it! That screenshot is the view of a tester in the install page of App Center. AFAIK testers can't change their notification settings (fyi @botatoes correct me if that's wrong!). To customize your notifications/or determine if testers should receive it, you can toggle this in the distribution process: 

![image](https://user-images.githubusercontent.com/33160470/61969447-67502300-af8f-11e9-821d-21db8be5b748.png)

**Comment by laalto** [comment]
What if some testers want these notifications some don't?

At the moment sending all appcenter emails to junk since receiving a flood of uninteresting "new version available" emails and changing the notification setting on project level is a no-go.

**Comment by anywherepilot** [comment]
This should be a feature request in the main App Center repository instead. Please have a look whether this one covers your needs, then upvote it: https://github.com/microsoft/appcenter/issues/1118

If not, please create a new feature request there and we will prioritize it against the other requests.

**Comment by King-of-Spades** [comment]
Closing this per @anywherepilot's comment and the age of this thread.
