### ISSUE TITLE
[Exporting Diagnostics Data - Visual Studio App Center] Invalid json property name in payload sample

### ISSUE THREAD

**Issue by Julien-Mialon** [MicrosoftDocs/appcenter-docs#642]
Hello,

I just tried to create some export configuration following this documentation page and found out that the property name `"exportEntities"` in json payload sample is invalid, it should be `"export_entities"` instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 667d49a6-a257-4783-b01f-34d93108669b
* Version Independent ID: b2101b61-2351-20f8-5196-76037f5959bb
* Content: [Exporting Diagnostics Data - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/gdpr/diagnostics-export)
* Content Source: [docs/gdpr/diagnostics-export.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/diagnostics-export.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by winnie** [comment]
Thanks @Julien-Mialon! I just submitted a PR to have this fixed. I'll close this issue once the PR is merged.

**Comment by winnie** [comment]
Docs are updated: https://docs.microsoft.com/en-us/appcenter/gdpr/diagnostics-export

Closing this issue. Thanks!

**Comment by Julien-Mialon** [comment]
Thank you! :)
