### ISSUE TITLE
Global application crash logging ?

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/appcenter-docs#643]
Does / is there a way to log crashes without explicitly writing the entry in a catch block for areas that may not have appropriate exception handling ?

Xamarin forms is the platform I am using.

**Comment by winnie** [comment]
Hi @stephenhauck - the App Center crashes SDK will send crash logs from your app to App Center. You can learn more here: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin

You only need to use the try/catch blocks if you are tracking errors (handled exceptions). Hope that helps!
