### ISSUE TITLE
Push Notification not received in Foreground on Android device targeting Android 8.0+

### ISSUE THREAD

**Issue by quantumarun** [MicrosoftDocs/appcenter-docs#645]
I have a Xamarin.Forms application and had integrated AppCenter Push. All was working fine until recently the push notification stopped getting received in foreground. While debugging i can see the notification is received but it's not shown as notification at the top.

I had followed the steps from below link:
https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms

Here is my code to process Push Notifications

        `void SubscribeForPush()
                {
                    if (!AppCenter.Configured)
                    {
                        Push.PushNotificationReceived += async (sender, e) =>
                        {
                            // Add the notification message and title to the message
                            var summary = $"Push notification received:" +
                                        $"\n\tNotification title: {e.Title}" +
                                        $"\n\tMessage: {e.Message}";

                            // Send the notification summary to debug output
                    System.Diagnostics.Debug.WriteLine(summary);
                    if (!IsEmpty(e.Title) || !IsEmpty(e.Message))
                    {
                        
                        Context context = Android.App.Application.Context;

                        Intent intent = new Intent(context, typeof(MainActivity));
                        intent.PutExtra("type", "notification");

                        // Instantiate the builder and set notification elements, including pending intent:
                        NotificationCompat.Builder builder = new NotificationCompat.Builder(context)
                            .SetDefaults((int)NotificationDefaults.Sound | (int)NotificationDefaults.Vibrate)
                            .SetAutoCancel(true)
                            .SetContentIntent(PendingIntent.GetActivity(context, 0, intent, 0)).SetContentTitle(e.Title)
                            .SetContentText(e.Message)
                            .SetTicker("New Notification")
                            .SetSmallIcon(Resource.Drawable.Icon)
                            .SetPriority((int)NotificationImportance.High);

                        if (Build.VERSION.SdkInt >= BuildVersionCodes.O)
                        {
                            builder.SetChannelId(CHANNEL_ID);
                        }

                        // Build the notification:
                        Notification notification = builder.Build();

                        // Get the notification manager:
                        NotificationManager notificationManager = context.GetSystemService(Context.NotificationService) as NotificationManager;

                        // Publish the notification:
                        notificationManager.Notify(NOTIFICATION_ID, notification);
                    }
                    else
                    {
						// If there is custom data associated with the notification,
						// print the entries
						if (e.CustomData != null)
						{
							summary += "\n\tCustom data:\n";
                            await NavigateToPage();
							
						}
                    }
                };
          }
        }`

**Comment by jwargo** [comment]
@quantumarun The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by quantumarun** [comment]
Thanks @jwargo. I had reached to AppCenter support on this.
