### ISSUE TITLE
Upload crashes

### ISSUE THREAD

**Issue by JDaance** [MicrosoftDocs/appcenter-docs#646]
I used to upload crashes from Lua in my game using HockeyApp http API. Is this still possible? I need to be able to upload crashes from my clients game, without using the SDK, or if you have some lua based SDK?

This is the documentation for this feature on HockeyApp: 
https://support.hockeyapp.net/kb/api/api-crashes#post-custom-crashes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/index#feedback)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by winnie** [comment]
Hey @JDaance - App Center doesn't have an equivalent upload custom crashes API at the moment. This is on our roadmap and we expect to have this complete very soon. Please reference this issue [#31](https://github.com/microsoft/appcenter/issues/31) for the latest updates.

We don't have a Lua based SDK but you should be able to use the uploads API once we implement it. Thanks!

**Comment by JDaance** [comment]
Hey, thats great to hear! Thanks
