### ISSUE TITLE
Missing custom_data length limits

### ISSUE THREAD

**Issue by jarrodbell** [MicrosoftDocs/appcenter-docs#648]
After testing (and getting 400 Bad Request errors), I found there is a 100 character limit for data within custom_data values. This is not documented here, and would have been great to know before implementing code.

{"code":400,"message":"body parameter is invalid or empty.: 'CustomData[\"example\"] value '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012'' exceeds maximum length of '100'."}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aadf839d-04fb-8d6e-dd5d-57a79c1d0914
* Version Independent ID: ea1d2e77-e3dd-19c7-9abd-ecd8f156a00c
* Content: [Using the Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/rest-api#feedback)
* Content Source: [docs/push/rest-api.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/rest-api.md)
* Service: **vs-appcenter**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@jarrodbell thanks for pointing this out (and sorry for the confusion). I’ll take a look at making this more clear in the docs.

**Comment by jwargo** [comment]
@jarrodbell that limitation is documented here: https://docs.microsoft.com/en-us/appcenter/push/send-notification#limitations but I’ll make a reference in the other doc.
