### ISSUE TITLE
option to upload symbol file can not be found

### ISSUE THREAD

**Issue by DavidPineda** [MicrosoftDocs/appcenter-docs#65]
Documentation and tutorials indicate that the map files must be uploaded, but the button or option to upload them is not found on the platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b36a466-fc92-153a-e513-a2f39ed4bf36
* Version Independent ID: bfca53b7-2d88-1665-57a8-163a88af183e
* Content: [App Center Crash Reporting for React Native - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/crashes/react-native)
* Content Source: [docs/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/crashes/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @anlinde
* Microsoft Alias: **anlinde**

**Comment by jwargo** [comment]
@DavidPineda The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by saraford** [comment]
@DavidPineda Hi 👋  You should be able to use the same “Upload Symbols” button on the Symbols page to upload the map files as well. If that doesn't work for you, please use the link intercom above to contact us for support. Thanks! 🙏
