### ISSUE TITLE
Incorrect Method Names

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/appcenter-docs#650]
Here are the correct names for the methods mentioned in this article:

In this section: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms#did-the-app-crash-in-the-previous-session

The method should be:

`var hasCrashed = await Crashes.HasCrashedInLastSessionAsync();`

In this section: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms#details-about-the-last-crash

The method should be:

`var crashReport = await Crashes.GetLastSessionCrashReportAsync();`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eae5644-1b90-680a-25aa-9ebc77b3ce58
* Version Independent ID: 05a373b3-f6eb-e92e-72a3-d8bd49fa9aab
* Content: [App Center Crashes for Windows - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms)
* Content Source: [docs/sdk/crashes/wpf-winforms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/wpf-winforms.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by LanceMcCarthy** [comment]
Why was this closed? The documentation was not updated and those are incorrect methods that do not compile.

To add another error for that page, this is not a method in WinForms/WPF:

`AppCenter.start()`

It should instead be 

`AppCenter.Start()`

**Comment by blparr** [comment]
We made the corresponding documentation update, and therefore the issue was closed automatically. Changes might take a bit to be live.

**Comment by LanceMcCarthy** [comment]
Hi Blanca, 

My apologies for being impatient. I did do a Shift + F5 on the page to make sure I was seeing the latest non-cached version. 

I usually see a linked commit or another discussion when a fix is incoming. By just seeing this:

![image](https://user-images.githubusercontent.com/3520532/62491574-5460fe00-b79a-11e9-868d-682c514212c6.png)

I believed it was arbitrarily closed. Thanks for following up so quickly.

**Comment by blparr** [comment]
Hi, no worries!

Our colleague @guperrot referenced his documentation changes (might not be visible externally), see below:

<img width="712" alt="Screen Shot 2019-08-05 at 1 21 34 PM" src="https://user-images.githubusercontent.com/22063767/62492627-f88b7a80-b783-11e9-9a29-7eba85921999.png">

**Comment by winnie** [comment]
Docs were updated so I'm closing this issue. Thanks!
