### ISSUE TITLE
Errors are available for more than just Xamarin platform

### ISSUE THREAD

**Issue by cainejette** [MicrosoftDocs/appcenter-docs#651]
We should update this to be correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c2b0f5e-997d-d42d-f7e2-8168cdc812e0
* Version Independent ID: 7f760699-c91d-e427-25be-85a4611fba7d
* Content: [Limitations - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/limitations)
* Content Source: [docs/diagnostics/limitations.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/limitations.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by cainejette** [comment]
This page also says errors only for xamarin/unity: https://docs.microsoft.com/en-us/appcenter/diagnostics/using-the-diagnostics-ui

**Comment by winnie** [comment]
Docs have been updated to reflect handled errors support for WPF/WinForms apps: 

https://docs.microsoft.com/en-us/appcenter/diagnostics/using-the-diagnostics-ui
https://docs.microsoft.com/en-us/appcenter/diagnostics/limitations

**Comment by simon-assistiq** [comment]
Doesn't mention iOS. Does that mean iOS handled errors are not supported?

https://learn.microsoft.com/en-us/appcenter/sdk/crashes/ios#handled-errors doesn't say it's not supported…

**Comment by DmitriyKirakosyan** [comment]
@simon-assistiq , iOS handled errors are supported. We will update the docs.
