### ISSUE TITLE
2.1 Convert the application identifier

### ISSUE THREAD

**Issue by tele-bird** [MicrosoftDocs/appcenter-docs#652]
I see that the new initialization code uses app secret instead of app id.... Why do I need to convert the application identifier if it's not used in the new code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e158918e-8740-6b57-4579-9baa3db532ac
* Version Independent ID: 9d14e1ae-ca37-791b-44eb-e3448cbc70ae
* Content: [HockeySDK for Xamarin Migration - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/xamarin-sdk-migration#feedback)
* Content Source: [docs/transition/xamarin-sdk-migration.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/xamarin-sdk-migration.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by tele-bird** [comment]
I found out that I needed to use HockeyApp's app ID value (and NOT the app secret, as these docs imply) in place of {Your App Secret} in the call to AppCenter.Start().

**Comment by anywherepilot** [comment]
The app ID is indeed used by the SDK. It is also used by one App Center API endpoint. However, you're right in that we're trying to not bother users of App Center with this ID.

You can get your app ID from the Overview page, through the API or the CLI, or by checking the `commonContext.appStore.app.id` value in the developer console of a browser after browsing to your app.
