### ISSUE TITLE
Crashes and errors in one call?

### ISSUE THREAD

**Issue by mist3rj** [MicrosoftDocs/appcenter-docs#654]
Hi, can you confirm that with one API call we retrieve both errors and crashes?

e.g. https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/errors/errorGroups/{errorGroupId}

How can I know which HandledError resulted in a crash ?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 667d49a6-a257-4783-b01f-34d93108669b
* Version Independent ID: b2101b61-2351-20f8-5196-76037f5959bb
* Content: [Exporting Diagnostics Data - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/gdpr/diagnostics-export#feedback)
* Content Source: [docs/gdpr/diagnostics-export.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/diagnostics-export.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by winnie** [comment]
Hi @mist3rj - you can call this API to retrieve all crash and error groups: https://openapi.appcenter.ms/#/errors/Errors_GroupList 

In the returned results, you'll see the group ID. If the group ID has a "u" attached to the end of the numbers, then that indicates a crash. 

For example, the first group in the screenshot below is an error group and the second one is a crash group:
![image](https://user-images.githubusercontent.com/8868628/62401217-12844d80-b537-11e9-8549-453c30751106.png)

Hope that helps! Closing this issue for now but please reopen it if this didn't address your initial comment.
