### ISSUE TITLE
Missing import com.microsoft.appcenter.data.models.DocumentWrapper;

### ISSUE THREAD

**Issue by guymerin** [MicrosoftDocs/appcenter-docs#655]
Compile will fail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b937bafd-1f6f-b759-18ec-8f960cc54150
* Version Independent ID: 2c928903-1b57-4dc8-e362-c4b78719df57
* Content: [Configuring App Center Data for Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/data/android#feedback)
* Content Source: [docs/sdk/data/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/data/android.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by King-of-Spades** [comment]
This was deleted in https://github.com/MicrosoftDocs/appcenter-docs-pr/pull/1821
