### ISSUE TITLE
Slightly adjust point 3.1.2

### ISSUE THREAD

**Issue by narcismihaitech** [MicrosoftDocs/appcenter-docs#656]
At point 3.1.2 Integrate React Native Android, it should be stated that the "assets" folder might not exist (it didn't exist for my project, for example). In that case, it should be created under "*project_root*/android/app/src/main/assets"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#feedback)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by hamswan** [comment]
Thanks @Narcis11 we will include this in our next iteration of doc edits.
