### ISSUE TITLE
Uploading issues takes too long

### ISSUE THREAD

**Issue by kys9096** [MicrosoftDocs/appcenter-docs#657]
I'm using App Center with Android NDK (unreal engine 4 + google break pad).
In my app, crash was generated on 02 Aug (at 7:50 p.m), but that issue was not uploaded at diagnostics.

At that time, I thought that I mistook something about my settings.
So I tried to find the problem by the evening of 03 Aug, but I can't find anything.
(Of course, I kept checking if the issue had been uploaded until that time.)

And than, when I checked today(05 Aug), that issues were uploaded at diagnostics...

**I expected a issue to be uploaded in at least a few hours. but it took more than 26 hours in this case. It's too long time to respond to issues.**

**Why does it take a long time to upload issues, and what can I do for reduce this term?**

[PS]
I check the same crashed case without upload symbols at 02 Aug,and that issue was uploaded immediately. But this issue disappeared when I uploaded symbols, and it seemed to be uploaded at same time with the above mentioned things.

**Comment by kys9096** [comment]
Thank you for your dedication.

I really don't mean to rush you, just want to know about progress of job.
Because my project is at an important time, if I can't expect this to improve in a few weeks, I need to add additional temporary things.
Can I expect this to improve in a few weeks?

Thanks.

**Comment by winnie** [comment]
@kys9096 apologies for the delay. Our engineering team is actually working through some NDK issues that may or may not be related to what you're seeing. Can you please start a support ticket and provide your app ID / name so our team can take a closer look for you? 

Thanks!

**Comment by kys9096** [comment]
Thank you for your reply.

How do I start a support ticket?
Is this it?
![image](https://user-images.githubusercontent.com/29933563/62990482-20b36180-be87-11e9-98ec-db033d36c09f.png)

Thanks.

**Comment by winnie** [comment]
@kys9096 yep that's it!

**Comment by winnie** [comment]
Closing this issue since our support and engineering team will be able to resolve this for you. Thanks!
