### ISSUE TITLE
UWP Wrong Token

### ISSUE THREAD

**Issue by BaileyMillerSSI** [MicrosoftDocs/appcenter-docs#658]
I followed the instructions from the App Center well setting up a Universal Windows App. I associated my app to the store using Visual Studio. Then navigated to the Url that was given on the app center website. The instructions are slightly vague for where to get the 'Security Key' because under the Microsoft Store page there is just Application Secrets and a key there. I copied those values and put them into App Center but yet my app notifications fail. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d6b620-92c6-9689-6af4-161e1f34429b
* Version Independent ID: e983d887-f1c4-4a39-81de-c55085bdb98c
* Content: [Push Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/troubleshooting#feedback)
* Content Source: [docs/push/troubleshooting.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/troubleshooting.md)
* Service: **vs-appcenter**
* GitHub Login: @manb-msft
* Microsoft Alias: **manb**

**Comment by jwargo** [comment]
@BaileyMillerSSI We just updated the docs last week to address the setup issues (and Microsoft moving to a new experience for Windows apps), Can you check to see that the docs there are the same as you followed? https://docs.microsoft.com/en-us/appcenter/sdk/push/uwp. 

The best way to work through this is with help from our support team. App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

Get it working with our support team, then lets see what has to happen to the docs to make this more clear.

**Comment by jwargo** [comment]
@BaileyMillerSSI any progress on your end? Was our support team able to help you?

**Comment by BaileyMillerSSI** [comment]
@jwargo Sadly, I have become to busy to look into this so I would chalk it up to a configuration issue on my end and have to close this issue 🤷‍♂
