### ISSUE TITLE
No Symbols Found

### ISSUE THREAD

**Issue by rangav** [MicrosoftDocs/appcenter-docs#66]
Hi

I Uploaded the sourcemap using the command above, when i upload to app center it is showing as no symbols found.

I am unable to find Crashes sources for React Native App.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b36a466-fc92-153a-e513-a2f39ed4bf36
* Version Independent ID: bfca53b7-2d88-1665-57a8-163a88af183e
* Content: [App Center Crash Reporting for React Native - Visual Studio App Center | Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/crashes/react-native)
* Content Source: [docs/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/crashes/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @anlinde
* Microsoft Alias: **anlinde**

**Comment by jwargo** [comment]
@rangav The comments feature of the docs is designed to enable customers to suggest changes to the docs or ask clarifying questions about the docs. If you need help with the product, please login to the App Center dashboard and click the blue chat button in the lower-right corner of the page. Our dedicated support resources will answer any questions you have there.

**Comment by giladno** [comment]
@jwargo there is no chat button in the App Center dashboard. I'm experiencing a problem with symbols as well...

**Comment by jwargo** [comment]
blue icon, bottom right? Try here: https://intercom.help/appcenter

**Comment by giladno** [comment]
<img width="1393" alt="screen shot 2018-03-19 at 23 01 59" src="https://user-images.githubusercontent.com/417148/37622154-9d4aca50-2bc9-11e8-9a65-cb6c5c07b2bc.png">

not there...

**Comment by jwargo** [comment]
@joemellin?

**Comment by jwargo** [comment]
@giladno Do you have a pop-up blocker or something running that would disable that? Support chat is provided through a third-party app (the support engineers are Microsoft employees), so your browser may be blocking it?  My apologies for this. Let me get you help.

**Comment by giladno** [comment]
@jwargo thanks, that was is. Pretty weird, since Intercom works for me on other websites without any need to disable my adblocker.

I've posted my questions there, cheers!
