### ISSUE TITLE
Webhook is not working for Webex teams

### ISSUE THREAD

**Issue by hrushie** [MicrosoftDocs/appcenter-docs#660]
Hello team,

I am trying to add webhook to webex teams to notify new release in the appcenter, but I am getting the following error on the test - 

<img width="356" alt="Screen Shot 2019-08-07 at 4 50 58 PM" src="https://user-images.githubusercontent.com/585126/62660460-b30daf80-b933-11e9-8b21-7193b9d53df4.png">

Same Web-hook url is working in the hockey app side and I am getting notification but when I am testing with appcenter it is not. following is my settings page

<img width="592" alt="Screen Shot 2019-08-07 at 4 46 20 PM" src="https://user-images.githubusercontent.com/585126/62660592-0d0e7500-b934-11e9-99d7-b5f7fef02568.png">

Thanks

**Comment by hrushie** [comment]
@blparr and @amchew any update on this? do we have any solution for this or I have to find out other way to send notifications to webex teams?

**Comment by amchew** [comment]
Hi @hrushie! We currently only support webhooks for Slack and Microsoft Teams unfortunately. You can write an [Azure function](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-serverless-api) that translates the way we POST to fit the requirements of the platform. Please see details [here](https://docs.microsoft.com/en-us/appcenter/dashboard/webhooks/#custom-webhook-support).

**Comment by anywherepilot** [comment]
I hope the answer above helped you set up the web hook. I'll close this issue now. Feel free to reopen if you can't get it to work.
