### ISSUE TITLE
iOS build submitted using App Center does not work on TestFlight (but works if submitted through XCode)

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#661]
I have a React Native project that I'm building for iOS. I have created a "
iOS Distribution (App Store and Ad Hoc)" Certificate and an App Store Distribution provisioning profile. I've added the newly created Certificate to the provisioning profile and set the App ID to explicitly match exactly.

I'm trying to distribute the app using TestFlight but having an issue. If I create an archive using XCode and distribute to TestFlight using XCode the app installs and runs. However, if I send the same certificate and provisioning profile and use App Center to submit to TestFlight, it successfully processes the app but when I attempt to run the app it crashes. I don't understand what the difference could be that is leading to this issue. Any idea or lead would be helpful.

Thank you

**Comment by nilofer** [comment]
Hi @myblueprinteric, can you contact [App Center support ](https://intercom.help/appcenter/en/) so we can better troubleshoot this please? We'll need some additional information to understand the cause of this issue.
