### ISSUE TITLE
guide on how to setup private npm registry

### ISSUE THREAD

**Issue by Evanion** [MicrosoftDocs/appcenter-docs#664]
The documentation for setting up build is lacking documentation on how to setup support for private npm packages.

**Comment by nilofer** [comment]
Thanks for pointing this out @Evanion. You can achieve this using a build script. Take a look at [a way](https://blog.theodo.com/2018/07/installing-private-npm-packages-appcenter-2/) someone else using App Center has solved this.

We have [folder](https://github.com/Microsoft/appcenter/tree/master/sample-build-scripts) with build scripts that is community driven if you'd like to contribute there!

**Comment by phil-andrews** [comment]
You can also do this using an .npmrc file in your project root. It's pretty simple. This is [a tutorial explaining the exact process](https://medium.com/@PhilipAndrews/installing-private-npm-packages-in-microsoft-appcenter-ci-cd-13d61f02aab2)
