### ISSUE TITLE
Uitest uwp

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/appcenter-docs#665]
Why is uwp not mentioned at all in the uitest chapter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0474be-6e14-b8e6-b6cf-934a04f0e509
* Version Independent ID: 4a79fc1d-8dca-1c17-718f-c30fda180f05
* Content: [Xamarin.UITest - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/)
* Content Source: [docs/test-cloud/uitest/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/index.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by winnie** [comment]
Hi @BrayanKhosravian thanks for the feature request! This isn't on our immediate roadmap but Microsoft has another tool called WinAppDriver that might help with UI tests: https://github.com/microsoft/WinAppDriver

**Comment by BrayanKhosravian** [comment]
Thanks for response. So uitesting for uwp is not supported at all with xamarin.uitest? Or is it just not mentioned in the doc?

**Comment by winnie** [comment]
UWP is not supported at all

**Comment by BrayanKhosravian** [comment]
ok thanks.
