### ISSUE TITLE
How can we set the "short version"

### ISSUE THREAD

**Issue by StAI** [MicrosoftDocs/appcenter-docs#667]
How can we set the "short_version" when we are uploading UWP .zip package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by winnie** [comment]
Hi @StAI - you only need to specify a version if you're uploading a .zip for a WPF or WinForms app. Did you run into any issues when uploading a UWP .zip package?

**Comment by StAI** [comment]
We need to release one version for different countries and different environment.
When we use hockeapp we can release f.e. 191.38.0-rc.preprod_PR, 191.38.0-rc.preprod_NL, 191.38.0-rc.prod_PR, 191.38.0-rc.prod_NL and so on.
But appCenter for UWP always resolve version from AppxBundleManifest.xml and this version will be the same for all these packages.
As I know in IOS f.e. there is possibility to set up additional "short version", but in UWP we does not have this.
Is it possible to set "short version" thru api, or change the version after the package upload?

**Comment by Aliaksandr2Kharytaniuk** [comment]
Hello @winnieli1208 ,

Could you please assist us with custom versions? At the moment it's blocks our migration to AppCenter and it's critical for our customer.

Thank you in advance!

**Comment by Aliaksandr2Kharytaniuk** [comment]
@winnieli1208 , @botatoes , @blparr Just a kindly reminder. Do you have any updates?

**Comment by winnie** [comment]
Hi there! Apologies for the delay. Currenlty App Center doesn't support setting the version for UWP app releases. We just take the version that we extract from the app package, which I believe is what HockeyApp does as well.

I added an item to our backlog but unfortunately I don't have an ETA. I'll post here when I have updates!

**Comment by Aliaksandr2Kharytaniuk** [comment]
Hi @winnieli1208,

A lot of thanks for the response! We will look forward to any updates from you.

Thank you in advance!

**Comment by anywherepilot** [comment]
Hi @Aliaksandr2Kharytaniuk. We recently did a change to App Center so now all Windows applications, including UWP, respect the version number which you provide. Please verify whether this is still an issue for you.

When you upload a UWP app as a .zip or .msi file, you can specify one number. This number becomes the build number in App Center, and what used to be called the `bundle_version` in HockeyApp. There is no way to set the `bundle_short_version` for UWP apps at the moment. The version field is always populated with an empty string. The version number behavior is a little confusing. If enough customers want this to change, we will pick it up.

Please let us know whether you would like the documentation to be clearer. If this is a feature request for App Center itself, please head over to the main repository https://github.com/microsoft/appcenter/issues/. Issues which get a lot of votes make it into the product quicker.

**Comment by StAI** [comment]
Hi @jerietve. Is this already released?
I have try to create new release with custom version with no success:
![image](https://user-images.githubusercontent.com/2962278/70534513-4b2ed600-1b6c-11ea-9a27-4a15cf0922a5.png)

**Comment by winnie** [comment]
Hi @StAI - yes we added support for setting the build number for UWP .zip and .msi packages. If you are uploading a zip with an .appx file inside, we will attempt to extract the version number which is why you're seeing the error message. We have plans to improve this experience in the future but no ETA yet. 

We'll keep post here with updates. Thanks!

**Comment by King-of-Spades** [comment]
@winnie is there a tracking item for the relevant feature on here? https://github.com/microsoft/appcenter/issues

**Comment by King-of-Spades** [comment]
I wasn't able to find a definite match for it in the feature request; if I still haven't found one or heard back by next week, I'll migrate this over to the appcenter repository and just leave a note that it might be a duplicate.
