### ISSUE TITLE
Update React Native 0.60+ CodePush support 

### ISSUE THREAD

**Issue by jinyang1994** [MicrosoftDocs/appcenter-docs#670]
The configuration of React Native 0.60+ is slightly different from the previous one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39490e39-be97-2bba-5afc-6bc8bed39690
* Version Independent ID: 357a2070-e41c-b346-e18b-606eec7255c2
* Content: [Using the React Native SDK with CodePush - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#feedback)
* Content Source: [docs/distribution/codepush/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by zanechua** [comment]
The relevant issue for this is https://github.com/microsoft/appcenter-sdk-react-native/issues/635

**Comment by King-of-Spades** [comment]
Hi, sorry for the long time not hearing from us. I'm currently reviewing and cleaning up old issues. 

> The configuration of React Native 0.60+ is slightly different from the previous one.

Can you give any context on what's 'different' that you observed?

**Comment by jinyang1994** [comment]
Sorry, it ’s been a long time, I can’t remember the problem at that time

**Comment by King-of-Spades** [comment]
That's alright, in the process of cleaning up these old issues I'm trying to get us to a point where we don't leave them aging too much. 

- If you have future documentation requests, this is the best place (appcenter-docs)
- For feature requests, you can file those here: https://github.com/microsoft/appcenter/issues
- For technical support, you can contact support by: 
   1. Going to https://appcenter.ms/apps 
   2. Selecting **? > Contact Support** (in the upper right corner).
