### ISSUE TITLE
A few small changes

### ISSUE THREAD

**Issue by e4c4** [MicrosoftDocs/appcenter-docs#671]
Very helpful guide. Just had to make a few small changes to the above instructions to get it to work for me:

Instead of "classpath 'com.google.gms:google-services:4.0.1'", the current version of Google services at this time seems to be "classpath 'com.google.gms:google-services:4.3.0'"

Needed to change "protected void onNewIntent(Intent intent)" to "public void onNewIntent(Intent intent)" in order to be able to override it. Also needed to add "import android.content.Intent;" at the top of "MainActivity.java" in order to recognize Intent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7078a8ed-8f99-1544-8601-8c778fd2bbc1
* Version Independent ID: 9b1886d6-c9f8-e73b-e2b6-db6022f579ac
* Content: [App Center Push for React Native Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-android#feedback)
* Content Source: [docs/sdk/push/react-native-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/react-native-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by duncan-iaria** [comment]
Had to do the above things as well (in my case though I downgraded to 3.2.1 since I had some other dependencies on that version). Thanks for the help!

**Comment by hamswan** [comment]
Thanks for pinpoint this out, we will take a look at the documentation.
