### ISSUE TITLE
The "Windows Plan" link is broken

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/appcenter-docs#674]
The "Windows Plan on Github" link 404's: https://github.com/Microsoft/appcenter/blob/windows/specs/2019-04/Windows-Plan.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e433b8e-4a4b-97a9-b1be-b32130379785
* Version Independent ID: 9d76a644-9b5c-4e0b-3d21-787d742c6f1c
* Content: [Windows Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/windows-support#feedback)
* Content Source: [docs/diagnostics/windows-support.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/windows-support.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by winnie** [comment]
Thanks for reporting this! I just submitted a PR to update the link. In the meantime, here is the right link to the Windows plan: https://github.com/microsoft/appcenter/blob/specs/specs/2019-04/Windows-Plan.md
