### ISSUE TITLE
Wrong podspec location for the iOS

### ISSUE THREAD

**Issue by anandwahed** [MicrosoftDocs/appcenter-docs#676]
In the above documentation the path for the podspecs is wrong and using the above gives an error. The above should be changed to use the below values for the `pod install` to work as expected.
```
pod 'appcenter', path: '../node_modules/appcenter'
pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics'
pod 'appcenter-crashes', path: '../node_modules/appcenter-crashes'
pod 'appcenter-push', path: '../node_modules/appcenter-push'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1b3f6c-3754-3c3f-1f63-1af79ad651a2
* Version Independent ID: 7fdc3cf5-f1fc-6fca-e9b6-ca1f287e1785
* Content: [React Native SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#feedback)
* Content Source: [docs/sdk/troubleshooting/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by hamswan** [comment]
@anandwahed our team will take a look at this in the documentation. Thanks for reporting.

**Comment by AnastasiaKubova** [comment]
Hi, @anandwahed! Thank you for reporting! Could you please clarify what the version of RN do you use? We fixed it for versions lower 0.60 in the last release.

**Comment by anandwahed** [comment]
Hi @AnastasiaKubova we are using the RN version `0.60.5`. The problem is that the Podspec files are present in the root directory of the node_modules. But the document is pointing to use the `ios` folder.

**Comment by annakocheshkova** [comment]
Why would you need to use this path in RN 0.60.5? It introduces autolinking so you don't need to manually specify this path. In fact, I think you'd better delete it from your podfile.

**Comment by anandwahed** [comment]
We actually upgraded the codebase from `0.55.4` to the latest version. And since we had to make some changes manually by viewing the file changes we updated the Podfile. @annakocheshkova are you saying the below entries can be removed completely from the Podfile ?

```
pod 'appcenter', path: '../node_modules/appcenter'
pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics'
pod 'appcenter-crashes', path: '../node_modules/appcenter-crashes'
```

**Comment by annakocheshkova** [comment]
@anandwahed yes. RN 0.60 links plugins automatically after the plugin installation, it doesn't use those references to node_modules anymore. So you should remove those lines, remove the plugins, and add them again.

**Comment by Jamminroot** [comment]
We haven't heard from you for a while now. Closing the issue, but feel free to reopen in case the problem is not resolved.
