### ISSUE TITLE
/Users/vsts/agent/2.155.1/scripts/android-postprocess.sh: line 36: pushd: /Users/vsts/agent/2.155.1/work/1/s/devapp/build/outputs/apk/..: No such file or directory

### ISSUE THREAD

**Issue by kikijhu** [MicrosoftDocs/appcenter-docs#677]
The correct path should be 
`/Users/vsts/agent/2.155.1/work/1/s/devapp/build/outputs/apk/debug `or `/Users/vsts/agent/2.155.1/work/1/s/devapp/build/outputs/apk/release`

`/Users/vsts/agent/2.155.1/scripts/android-postprocess.sh: line 36: pushd: /Users/vsts/agent/2.155.1/work/1/s/devapp/build/outputs/apk/..: No such file or directory`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b6246f8-55fc-c271-b83d-d1564c013fc8
* Version Independent ID: 48b809d8-ea94-af5f-e5be-9519403aa95f
* Content: [Configure a Java Android build in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/android/first-build)
* Content Source: [docs/build/android/first-build.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/android/first-build.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by nilofer** [comment]
Hi @kikijhu, for specific issues with your build please contact App Center support.
