### ISSUE TITLE
Missing a key step (which I found elsewhere)... appcenter login

### ISSUE THREAD

**Issue by GitHubTracey** [MicrosoftDocs/appcenter-docs#68]
one key step which is missing... is that in order to do a code push from the command line using the Dynamic Deployment Assignment, you first need to log into the appcenter. Should probably be mentioned prior to giving the command on how to deploy from command line. As a first attempt, following the getting started guide, it was a critical step. Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39490e39-be97-2bba-5afc-6bc8bed39690
* Version Independent ID: 357a2070-e41c-b346-e18b-606eec7255c2
* Content: [Using the React Native SDK with CodePush - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#feedback)
* Content Source: [docs/distribution/codepush/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@GitHubTracey Great suggestion, thanks. I've asked the product PM to consider a doc update.

**Comment by elamalani** [comment]
@Zakeelm Can you take care of updating CodePush doc?

**Comment by jwargo** [comment]
@GitHubTracey docs updated, thanks for pointing that out.

**Comment by Zakeelm** [comment]
@GitHubTracey Hey, going to close this! I just added a few sentences to our docs to make this more clear.
