### ISSUE TITLE
Crash group reopened

### ISSUE THREAD

**Issue by TParizek** [MicrosoftDocs/appcenter-docs#680]
To my knowledge it's not currently possible to be notified about crash group being reopened. This is a shame. There are two situations when you want to be notified about an issue:
- When some issue appears for the first time
- When some issue appears after it was marked as resolved

Do you have any plans for adding this in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79d5a18-b4d0-a8c4-b482-d79284c82ad4
* Version Independent ID: 8dff2b5d-ae26-5f4a-0f56-b19ac446fcf0
* Content: [App Center Webhooks Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/webhooks/#feedback)
* Content Source: [docs/dashboard/webhooks/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/webhooks/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by amchew** [comment]
Hey @TParizek, thanks for letting us know about your feature request! We currently have no plans for these two functionalities, but that being said, continue to post here, and give us feedback, as we do re-prioritize our roadmap based on user's feedback.
