### ISSUE TITLE
Update the documentation to indicate that submodules are supported on AppCenter

### ISSUE THREAD

**Issue by MarkMichaelis** [MicrosoftDocs/appcenter-docs#681]
Update documentation to indicate that submodules on Azure DevOps are supported:

>Are Git submodules supported?
>For repositories hosted on GitHub, only Git submodules over HTTPS are supported. For repositories hosted on Bitbucket or Azure DevOps (formerly VSTS), only un-authenticated Git submodules are supported for now.

Should be
>Are Git submodules supported?
>For repositories hosted on GitHub and Azure DevOps, Git submodules over HTTPS are supported using the same authentication as the parent repository.  For repositories hosted on Bitbucket, only un-authenticated Git submodules are supported for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da27216-2ec0-ab4f-6235-cafde99f44d8
* Version Independent ID: 268f8ecb-5d39-2164-0120-43453bfb19ef
* Content: [Code Repository Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/code-repos#git-sub)
* Content Source: [docs/build/troubleshooting/code-repos.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/troubleshooting/code-repos.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by zippo227** [comment]
What about private submodule repositories in GitHub?

**Comment by King-of-Spades** [comment]
The original purpose of this issue was addressed, though I'm not sure what the answer is for @zippo227's follow-up question.

**Comment by elamalani** [comment]
@zippo227 Private submodules hosted in GitHub are not supported in App Center.
