### ISSUE TITLE
Warning message in Build scripts section doesn't convey the correct message

### ISSUE THREAD

**Issue by ilaiyarajak** [MicrosoftDocs/appcenter-docs#683]
What is there now:

> Every time you modify the project's build scripts, you must click the Save or Save & Build button to save the branch configuration to apply the changes.

Documentation link: https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/

What is the confusion:
The working functionality is "Whenever there is new build script added or made changes to location of the file we have to click on Save or Save&Build button to save the branch configuration to apply the changes."
The warning message conveys that "Every time you MODIFY the project's build script, you must click the Save or Save & Build button". Actually it is not required to click Save or Save & Build whenever there is modification or update to the existing build scripts. We must click Save or Save & Build button only when there is new build script file or moving the build build script file location.

Proposed warning message:

> Every time you add or update the location of the project's build scripts, you must click the Save or Save & Build button to save the branch configuration to apply the changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca50588e-c8ad-2b8e-683f-bc5fc612dfe4
* Version Independent ID: 5d9513bd-d179-eaeb-96aa-06bd5ba0224f
* Content: [Build Scripts - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/)
* Content Source: [docs/build/custom/scripts/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/scripts/index.md)
* Service: **vs-appcenter**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by King-of-Spades** [comment]
The warning currently reads:
> When App Center detects build scripts for the first time, or whenever you make changes to the location of scripts or, for iOS projects, where you store CocoaPods, you must click the Save or Save & Build button in the build configuration to apply the changes. When you do this, App Center performs an analysis to index your repository tree and updates the build definition.

That update was actually awhile back but it looks like this issue wasn't closed after the update.
