### ISSUE TITLE
Samples for spedifying color, icon and sound in notification

### ISSUE THREAD

**Issue by veringm** [MicrosoftDocs/appcenter-docs#685]
Hi, you write that icon, color and sound can be choosen when sending notification to Android. Would be very helpful with a sample notification_content containing these settings.

However, thank you for very a thorough documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed528dcd-ecaf-697e-c64a-30651d26ff3d
* Version Independent ID: 1e92bbb4-5800-6d31-51ee-c6d5864801d1
* Content: [App Center Push for Xamarin.Android Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-android#feedback)
* Content Source: [docs/sdk/push/xamarin-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by King-of-Spades** [comment]
Thanks for the feedback. Since Push is being retired, I'm closing this issue. 

Blog post announcement: https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/

Push migration guide: https://docs.microsoft.com/en-us/appcenter/migration/push/
