### ISSUE TITLE
Outdated test running guidance

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/appcenter-docs#686]
This page is outdated for the latest version of Xamarin.UITest, which I believe are now upgraded to NUnit 3. The `/include` and `/exclude` command line options were removed in NUnit Console v3, and replaced with `--where`. The exe name also changed, to nunit3-console.exe. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea478860-5dcd-7f19-c9ce-c62e0b18f41d
* Version Independent ID: 1d5e7e80-78fe-b77e-3e9a-1250cbb868fd
* Content: [Working with categorized tests - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-categorized-tests?tabs=vswin)
* Content Source: [docs/test-cloud/uitest/working-with-categorized-tests.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/working-with-categorized-tests.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by glennwester** [comment]
Thanks Chris! @Oddj0b FYI 👍
