### ISSUE TITLE
Difference between iOS id and accessibility label?

### ISSUE THREAD

**Issue by UnreachableCode** [MicrosoftDocs/appcenter-docs#687]
What is the ID from iOS which the AutomationID exposes? Is it an accessibility label? Or is that something else. Need more clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d92e81-8d62-5775-b110-882c6ad6aa9a
* Version Independent ID: 62d282ce-ab98-46d1-1b82-fd28260330d2
* Content: [Get started with UITest and Xamarin.Forms - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/get-started-xamarin-forms#feedback)
* Content Source: [docs/test-cloud/uitest/get-started-xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/get-started-xamarin-forms.md)
* Service: **vs-appcenter**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
UIView.AccessibilityIdentifier.
