### ISSUE TITLE
Xamarin.UITest ClearAppData2 Timeout Exception (OnePlus 7)

### ISSUE THREAD

**Issue by mzhukovs** [MicrosoftDocs/appcenter-docs#688]
I was able to run a test using InstalledApp option on my physical Android device, a OnePlus 7, for a full day before all of a sudden ClearAppData2 timeout issue - it appears this may also happen for Samsung Galaxy 8 phone - any ETA on fixing?

**Comment by mzhukovs** [comment]
Perhaps also noteworthy is if i change AppDataMode to DoNotClear, the exception then becomes:
System.Exception: 'Post to endpoint '/ping' failed after 100 retries. No http result received'

**Comment by mzhukovs** [comment]
@Oddj0b hey do you think you guys will be able to take a look at this one soon? Please let me know when you get a chance.

**Comment by Oddj0b** [comment]
@mzhukovs sorry for the late response here, I've been out of office. Do you only see it on OnePlus 7?

Do you have links to test runs where it is happening or is it a local problem?

**Comment by mzhukovs** [comment]
@Oddj0b local - i will have to try with my other devices since i only recently upgraded to latest version of Xamarin.UITest but i know previous versions it was not an issue

**Comment by Oddj0b** [comment]
@mzhukovs is this still an issue with the latest release of Xamarin.UITest?

**Comment by mzhukovs** [comment]
hi @Oddj0b ,

unfortunately, with v3.0.4-dev2 the issue persists:

> Exception thrown: 'System.Exception' in Xamarin.UITest.dll
> Timed out waiting for result of ClearAppData2

**Comment by GlennWilson** [comment]
@mzhukovs @Oddj0b 
I wonder if this is the issue:
"Also, running locally, if you are connecting to an already installed app you may need to specify a keystore so that the test server can be signed with the one that matches that APK."
https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-android-signing

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
