### ISSUE TITLE
Cordova support

### ISSUE THREAD

**Issue by Drumzey** [MicrosoftDocs/appcenter-docs#690]
Will this feature be available to Cordova based applications?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e63af91-500a-d696-bb0d-544b53b9d85f
* Version Independent ID: 1a47949b-033e-fa40-ba8b-0afb61e0c437
* Content: [Push to User - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/push-to-user#feedback)
* Content Source: [docs/push/push-to-user.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/push-to-user.md)
* Service: **vs-appcenter**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@Drumzey there's nothing specific to the target platform with this feature - we don't care whether it's a Cordova app or any other app. What matters is that we have an identity to send to. Use this: https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/cordova#identify-users to set the identity for Cordova apps. I don't know what the plans are for our Auth Service and Cordova, I'll ask the PM.

**Comment by amchew** [comment]
Hey @Drumzey, thanks for reaching out! Specifically for Auth, implementing Cordova is on our roadmap but there's no ETA for when that will be yet. For more details, here's the [platform matrix for the services we support](https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix).
