### ISSUE TITLE
There may be a typo in the first line under first section

### ISSUE THREAD

**Issue by Zikun-Huang** [MicrosoftDocs/appcenter-docs#691]
In below section, the first line, I guess the "install IDS" should be "install IDs" as that appears in below content.

Original Sentence:
##You did not retain a mapping of your User IDs to Install IDs##
If you did not keep a mapping between your user IDs and install IDS, you must follow some extra steps outlined below.

traced link:
https://docs.microsoft.com/en-us/appcenter/gdpr/diagnostics-delete#you-did-not-retain-a-mapping-of-your-user-ids-to-install-ids

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 755430a6-1d28-bc01-6d15-ef286bb69004
* Version Independent ID: b7cb673a-e6f3-519d-e932-4a23ef84dd6c
* Content: [Deleting Diagnostics Data - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/gdpr/diagnostics-delete#you-did-not-retain-a-mapping-of-your-user-ids-to-install-ids)
* Content Source: [docs/gdpr/diagnostics-delete.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/diagnostics-delete.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by King-of-Spades** [comment]
Looks like this update was already addressed, but we forgot to close the issue. Closing now.
