### ISSUE TITLE
There is no 'Click on Stores under Distribution in the left menu.'

### ISSUE THREAD

**Issue by stewa11** [MicrosoftDocs/appcenter-docs#692]
Thank you for this tutorial.
I was making good headway linking up the service account.
Questions:
1) Where is the JSON service account private key saved to on my windows 10 file system?
2) there is no Distribution nor Stores in the left hand menu. 'Click on Stores under Distribution in the left menu.' Have these been moved or do I need to enable something to get them to show?

Thanks
Stewart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868e3edf-f3af-950e-4f8a-ea30c392e883
* Version Independent ID: a725a1f2-fe7b-b7be-8e5e-6db22c2a756d
* Content: [Publish to Google Play Store - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay)
* Content Source: [docs/distribution/stores/googleplay.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/googleplay.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by ot-dchristopher** [comment]
@stewa11 You have to click on Distribute in order to see Stores appear as a sub-option below it (along with Releases and Groups). Regarding where the JSON file got saved, it's wherever your browser prompted you to save it or defaulted to (Downloads?). This really all depends on your specific environment but every browser has a menu option to view all downloaded files. I hope this helps!

**Comment by anne-k** [comment]
@stewa11 Did you navigate to your app's page? That's where the 'Distribute' menu option is. It doesn't explicitly say in the tutorial but the link to Google Play needs to be set up for each app individually in App Center.

<img width="255" alt="Screenshot 2019-11-26 at 09 54 08" src="https://user-images.githubusercontent.com/27358441/69614234-1468a400-1033-11ea-87d1-aae728f0d9c5.png">

**Comment by stewa11** [comment]
Hi anne-k , ot-dchristopher ,

huge thanks for helping me.

Can you please confirm the URLs?
Is this navigation correct? 
Google Play Console (**example** https://play.google.com/apps/publish/?account=XXXXXXXXXXXXXXXX#AppListPlace)
Click on App, Release Management, then what (please)?

I am happy too demonstrate/learn if you are available for 5 mins on a remote session.

thanks 
Stew

**Comment by ot-dchristopher** [comment]
> Hi anne-k , ot-dchristopher ,
> 
> huge thanks for helping me.
> 
> Can you please confirm the URLs?
> Is this navigation correct?
> Google Play Console (**example** https://play.google.com/apps/publish/?account=XXXXXXXXXXXXXXXX#AppListPlace)
> Click on App, Release Management, then what (please)?
> 
> I am happy too demonstrate/learn if you are available for 5 mins on a remote session.
> 
> thanks
> Stew

The URL you mentioned is in the Google App Store. The one I was referring to is in App Center (https://appcenter.ms). Load your app in App Center, then follow the instructions in the earlier posts.

**Comment by Oddj0b** [comment]
Hi @stewa11, I have PR open to change Distribution to Distribute instead.
