### ISSUE TITLE
UWP support for Javascript

### ISSUE THREAD

**Issue by ramaguduri** [MicrosoftDocs/appcenter-docs#697]
I have followed get started on UWP for JavaScript and tried to add Nuget package for appcenter, there was issue with installing dependency - 

Severity	Code	Description Project	File	Line	Suppression State
Error	Could not install package 'Microsoft.NETCore.Jit 1.0.3'. You are trying to install this package into a project that targets 'UAP,Version=v10.0.17134', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-js-uwp

Current documentation only talks about C# support, is UWP with JavaScript supported?

**Comment by annakocheshkova** [comment]
Hey @ramaguduri unfortunately we do not support it yet. I will mark it as feature request.

**Comment by King-of-Spades** [comment]
@ramaguduri I copied your request to the App Center repository for feature requests: https://github.com/microsoft/appcenter/issues/1809

Feel free to add any additional comments on there, and give the request a 👍to show your support. You can also file other feature requests or vote on them in that repository too.
