### ISSUE TITLE
[Docs][Suggestion] - App Center Crashes - UWP

### ISSUE THREAD

**Issue by mattregul** [MicrosoftDocs/appcenter-docs#7]
- https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp
- https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/uwp.md

(at the bottom of the page)
> Important
> None of the other API calls provided by the `Crashes` class are supported on UWP, they work only for Xamarin. UWP only supports starting Crashes with `AppCenter.Start`.

Should it be further outlined that "Xamarin" is referring to
- Xamarin.iOS & Xamarin.Android 
- Xamarin.Forms being deployed to iOS & Android

to help avoid confusion of anyone writing a Xamarin.Forms app, looking to deploy to UWP?

**Comment by elamalani** [comment]
@mattregul Thanks for your feedback. We will update the documentation to reflect the feedback.
