### ISSUE TITLE
Is Unity Desktop (not UWP) now supported with the introduction of AppCenter for WPF ?

### ISSUE THREAD

**Issue by mightypanda** [MicrosoftDocs/appcenter-docs#701]
I wonder if a Unity application built for Desktop native (x86 or x64) can be now supported after the preview of AppCenter for WPF.
If not, is it going to be supported?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0365781-58e5-a72a-9422-0ebd586877fe
* Version Independent ID: 5f7e41ef-448a-b27b-9041-bb38ff38ae16
* Content: [Get Started with Unity - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/unity)
* Content Source: [docs/sdk/getting-started/unity.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/unity.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by MatkovIvan** [comment]
Hi @mightypanda ,

It's not supported by App Center Unity SDK yet. We've marked this as feature request for now.

**Comment by King-of-Spades** [comment]
@MatkovIvan @mightypanda I'm attempting to determine if we can get this issue transferred over to microsoft/appcenter which handles feature requests. 

We can either copy-paste the request in a new feature, or we find a duplicate feature we can merge that and you can upvote it to give it greater visibility. 

For example, this request looked a bit related:
> Add Unity-Windows to your list of supported platforms
https://github.com/microsoft/appcenter/issues/999

If you can let me know, I can copy it over for you.

**Comment by vvechkanov** [comment]
As @King-of-Spades suggested this feature duplicates the one from the main app center repository:

> Add Unity-Windows to your list of supported platforms 
> microsoft/appcenter#999

So I am closing this feature as duplication. If you think there are some differences in this feature request, feel free to comment and reopen.
