### ISSUE TITLE
App Center distribute dependancy is missing in the documentation for Android. 

### ISSUE THREAD

**Issue by NejatMSultan** [MicrosoftDocs/appcenter-docs#702]
It is not showing what dependacy we should add to the build.gradle file to include the App Center distribute Sdk in "Getting started" section of the documentaion for android. 
It is curretly as seen below.

```
dependencies {
    def appCenterSdkVersion = '2.3.0'
    implementation "com.microsoft.appcenter:appcenter-analytics:${appCenterSdkVersion}"
    implementation "com.microsoft.appcenter:appcenter-crashes:${appCenterSdkVersion}"
}
```

**Comment by hamswan** [comment]
Team is looking at this.

**Comment by annakocheshkova** [comment]
@NejatMSultan the "Getting Started" page shows example of adding only default modules (which are Analytics and Crashes). For Distribute integration, you can refer to [this section](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#1-add-the-app-center-distribute-module). Thank you!
