### ISSUE TITLE
hockeyapp key feature missing - recruitment link

### ISSUE THREAD

**Issue by 8secz-johndpope** [MicrosoftDocs/appcenter-docs#703]
I am piloting alpha build of app - I want to recruit users into new alpha / beta builds.
In hockeyapp this was simple to do - but it doesn't seem like this is possible with appcenter?

did I miss something?

**Comment by 8secz-johndpope** [comment]
https://support.hockeyapp.net/kb/app-management-2/how-to-invite-beta-testers

**Comment by 8secz-johndpope** [comment]
any update? this is effecting launch plans.

**Comment by dipree** [comment]
@8secz-johndpope unfortunately, this is not going to be supported in App Center.

**Comment by 8secz-johndpope** [comment]
I would beseech you guys to reconsider this - it's a death nail for my use case.
I will be migrating to use google Firebase App Distribution in the mean time.
<img width="2048" alt="Screen Shot 2019-10-10 at 1 38 05 pm" src="https://user-images.githubusercontent.com/50567111/66534848-48f7cd80-eb63-11e9-8d21-a7eaaa8001e0.png">

a sample link for users to sign up
https://appdistribution.firebase.dev/i/qjaCcnbV


<img width="1469" alt="Screen Shot 2019-10-10 at 1 51 48 pm" src="https://user-images.githubusercontent.com/50567111/66535375-1fd83c80-eb65-11e9-90c2-12c9e462f904.png">

**Comment by dipree** [comment]
@8secz-johndpope please use our repository for feature requests https://github.com/microsoft/appcenter/issues/1040
