### ISSUE TITLE
Uploading symbols?

### ISSUE THREAD

**Issue by RAM237** [MicrosoftDocs/appcenter-docs#704]
Isn't there a way to upload dSym any more like it was in HockeyApp?
`curl -F "ipa=@$IPA_NAME" -F "dsym=@$DSYM_NAME" &lt;...&gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#feedback)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by velbur** [comment]
Found this
https://openapi.appcenter.ms/#/crash
and trying
POST /v0.1/apps/{owner_name}/{app_name}/symbol_uploads
and then with using response with symbol_upload_id
PATCH
/v0.1/apps/{owner_name}/{app_name}/symbol_uploads/{symbol_upload_id}
but symbols don't appear in Appcenter.
Any ideas?

**Comment by RAM237** [comment]
Same here.
And apps migrated from HockeyApp which had symbols uploaded - do not have them in AppCenter for some reason.

Hey, support, are you there?! The deadline for migration is getting closer and closer, but NONE of my requests received any feedback within 2 weeks now. How are you supposing we must migrate then? It would be fair to extend the deadline until the obvious bugs are fixed/missing functionality is restored on AppCenter side.

**Comment by velbur** [comment]
Found solution. If symbols size larger then 256mb, we can use command line uploading.
`appcenter crashes upload-symbols -s path/to/YourApplication.app.DSYM --app "AppCenterOrgId/AppCenterAppId" --token your-appcenter-token`
And if appcenter is not installed, install it first with: `npm i -g appcenter-cli`

But you if you need using API only, some additional information about API symbols here:
[https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#app-center-api](url)

**Comment by liszto** [comment]
I think it works in the same way than uploading an app. 
When you use the "POST /v0.1/apps/{owner_name}/{app_name}/symbol_uploads"
It will respond with an ID & upload_url. 
I think we must use the "upload_url" as we do for a release here : 
![image](https://user-images.githubusercontent.com/408031/65888679-38479a80-e3a0-11e9-99ec-116a0b80231a.png)

I just have to figure out what is the file parameter to use because I don't think it's ipa but something else, maybe "dsym"

**Comment by RAM237** [comment]
> Found solution. If symbols size larger then 256mb, we can use command line uploading.
> `appcenter crashes upload-symbols -s path/to/YourApplication.app.DSYM --app "AppCenterOrgId/AppCenterAppId" --token your-appcenter-token`
> And if appcenter is not installed, install it first with: `npm i -g appcenter-cli`
> 
> But you if you need using API only, some additional information about API symbols here:
> [https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#app-center-api](url)

@imjustabearrr , thanks for the note! **appcenter-cli** solution seems to be working fine for me.
