### ISSUE TITLE
Xamarin.UITest 3.0.3 ClearAppData does not work on Samsung Galaxy Tab S2

### ISSUE THREAD

**Issue by inikityuk** [MicrosoftDocs/appcenter-docs#705]
Addition to Xamarin.UI.Tests 3.0.3 release notes:
https://www.nuget.org/packages/Xamarin.UITest/
in "Known Limitations" section the same issue happens on "Samsung Galaxy A8"

it fails if "ConfigureApp.Android.ApkFile(androidPackagePath).StartApp(Xamarin.UITest.Configuration.AppDataMode.Clear);"  (or .Auto) is used to launch the tests.

Workaround is to use "ConfigureApp.Android.ApkFile(androidPackagePath).StartApp(Xamarin.UITest.Configuration.AppDataMode.DoNotClear);" flag, but not suitable for all tests.

NOTE: first run on device always go well, but every second run fail. (first run succeed only if no app installed on device)

Attached ui tests debug output:
[ui_tests_debug.txt](https://github.com/MicrosoftDocs/appcenter-docs/files/3577133/ui_tests_debug.txt)

**Comment by blparr** [comment]
Thanks for reporting this - our colleague @Oddj0b will follow up with you soon. Thanks!

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
