### ISSUE TITLE
Wrong method call

### ISSUE THREAD

**Issue by andreabalducci** [MicrosoftDocs/appcenter-docs#706]
[Enter feedback here]
On Android, paragraph 2.2
`Distribute.SetEnabledInDebbugableBuild(true); `
should be 
`Distribute.SetEnabledForDebuggableBuild(true);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d269a0-0b09-c2f6-d37a-319831bcf782
* Version Independent ID: f2c17a3a-87bb-0c75-9efb-de6ffb6f7738
* Content: [App Center Distribute for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#feedback)
* Content Source: [docs/sdk/distribute/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by hamswan** [comment]
We are looking at this.

**Comment by annakocheshkova** [comment]
@andreabalducci I don't see the typo you are referrring to, could you please elaborate?

**Comment by radolo1111** [comment]
27.09.2019 9:22 AM "Anna Kocheshkova" <notifications@github.com> napisał(a):

**Comment by owlstronaut** [comment]
Thank you for the report. We'll get this fixed shortly 😸
