### ISSUE TITLE
Error uploading UWP zip file

### ISSUE THREAD

**Issue by ringleader3** [MicrosoftDocs/appcenter-docs#708]
When I try to upload a build i get this error:
https://www.dropbox.com/s/56ltovc2p0txscg/Screenshot%202019-09-05%2014.48.54.png?dl=0

previously on hockeyapp, i would 'create a version' and then upload a zip file for it, but in AppCenter, there is only an option to upload the zipfile, and then when the upload completes, I get the error in the screenshot.

**Comment by blparr** [comment]
Hi! We use this repo to report docs issues. For your issue, do you mind reaching out to us via support (blue chat button in the app center portal)?

Thanks!
