### ISSUE TITLE
How to upload MSI builds

### ISSUE THREAD

**Issue by hasselmm** [MicrosoftDocs/appcenter-docs#709]
How to upload MSI builds? The docs mention that the build version have to be specified manually for MSI builds, but how to do so? When creating a new release via web interface the process aborts with "Version could not be created from build".

**Comment by anywherepilot** [comment]
Hi @hasselmm! There was a bug in App Center where for certain Windows platforms the version number for .msi files was ignored. We fixed it last month. You should now be able to upload .msi files and the version number you provide will be respected for all Windows apps regardless of platform. Uploading via the API also works again. I will close this issue now.
