### ISSUE TITLE
Custom crashes

### ISSUE THREAD

**Issue by sarahmarciano** [MicrosoftDocs/appcenter-docs#71]
is there an API for sending a custom crash? for ex. my server returned me 404 which I did not expect so I would like to send a crash 
is it possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519e420f-cf2a-1d5b-d86a-d01c09bcf7a0
* Version Independent ID: 59c746fb-cf4d-3019-2b48-56b69e09aa27
* Content: [App Center Crashes for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native)
* Content Source: [docs/sdk/crashes/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@sarahmarciano The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
