### ISSUE TITLE
Three options of code signing look like steps

### ISSUE THREAD

**Issue by jorisw** [MicrosoftDocs/appcenter-docs#710]
Under `Setting up Code Signing`, the three options of code signing seem like sequential steps because of the 1, 2, 3 numbering.

Instead of numbering the three options of code signing, using 1, 2, 3, I would use A, B, C or Roman I, II, III.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb88b888-1e68-8a75-efa4-cef2c33d4369
* Version Independent ID: 2fd3c90f-d7e5-5af3-9a50-b5571ac84995
* Content: [Android Code Signing Setup in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/android/code-signing#feedback)
* Content Source: [docs/build/android/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/android/code-signing.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by anywherepilot** [comment]
Thanks for the idea and the upvote. I have a PR out to change it to A B C and made some other changes which should make the documentation clearer.
