### ISSUE TITLE
Duplicate interface definition for class 'MSAbstractLog'

### ISSUE THREAD

**Issue by synalysis** [MicrosoftDocs/appcenter-docs#712]
I integrated the frameworks in Objective-C and get error messages about duplicate MSAbstractLog, MSService, and MSServiceAbstract. They are present both in AppCenterCrashes.frameworks, AppCenterAnalytics.framework and/or AppCenter.framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2da79c5d-1cef-5ed1-9ea2-8fd7e8940ec7
* Version Independent ID: 81f0e749-1909-072c-b84d-6e9c2ce1cfae
* Content: [HockeySDK for macOS Migration - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/macos-sdk-migration?tabs=objc#feedback)
* Content Source: [docs/transition/macos-sdk-migration.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/macos-sdk-migration.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by hamswan** [comment]
We are taking a look to this.

**Comment by annakocheshkova** [comment]
Hi there @synalysis sorry for the delay! I can't see the errors you mentioned, could you please elaborate: what are you trying to do? Build, archive, run?
Please also share your environment details and project xcconfig would also be good to look at.

**Comment by synalysis** [comment]
The problem occurs when I import headers from different frameworks like this:

#import <AppCenterCrashes/MSCrashes.h>
#import <AppCenterAnalytics/MSAnalytics.h>

The error is issued by the compiler.

Here you find more info about this issue: [https://github.com/microsoft/appcenter-sdk-apple/issues/1734](https://github.com/microsoft/appcenter-sdk-apple/issues/1734)

**Comment by annakocheshkova** [comment]
Ok I see you my colleague already answered you there. Let's close this duplicate issue then, sorry for bothering!
