### ISSUE TITLE
Sample script not consistent with previous example

### ISSUE THREAD

**Issue by steverhall** [MicrosoftDocs/appcenter-docs#714]
The sample script in "Uploading Tests to App Center" is not consistent with the example immediately above with respect to 'xcrun' command, nor did it work for my code. The previous 'xcrun' command worked properly and the sample script should be updated for consistency and correctness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486092bd-b86c-7796-c28f-39d5d25828d1
* Version Independent ID: 68ca1055-25bc-e2d5-6091-ab5fefe8a5a7
* Content: [Preparing XCUITest Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/xcuitest#feedback)
* Content Source: [docs/test-cloud/preparing-for-upload/xcuitest.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/xcuitest.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by Oddj0b** [comment]
@srhallx sorry for the slow response here, when I use the two commands it works for me. However, I build from a `.xcodeproj` and not a `.xcworkspace`. Which are you using?

**Comment by steverhall** [comment]
I was using a .xcworkspace, that could be the issue.

**Comment by Oddj0b** [comment]
A PR have been merged to fix this issue.

https://github.com/MicrosoftDocs/appcenter-docs-pr/pull/1597
