### ISSUE TITLE
What is "release_id"?

### ISSUE THREAD

**Issue by lbrownell-gpsw** [MicrosoftDocs/appcenter-docs#715]
It says it's a number, but what do we put there?  We use semver version number and integer build number, as well as a build type, to identify builds uniquely, but I don't know what to supply for release_id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by RAM237** [comment]
release_id is a unique sequential number of the app version given to you by AppCenter. That is, you very first upload will be release_id=1, the next is 2, and so on. It is provided on the previous step as you run those API calls :)

**Comment by lbrownell-gpsw** [comment]
Thanks @RAM237 

Hrm.  So the data I send to `release_uploads` -- the very first call in the steps -- needs me to specify the next `release_id`?  So, retain the previous and increment?

Here's what I was sending; 104 is the build number in our CI system:
```
{"release_id": 104, "build_version": "1.0.0.0", "build_number": "104"}
```
Here's the result of that first call, `release_uploads`:
```
{"upload_id":"1bf2b720-b7b0-0137-0c3b-0e7672213108","upload_url":"https://rink.hockeyapp.net/api/sonoma/apps/a65fdc5b-b7e5-4651-985c-bb2a08796087/app_versions/upload?upload_id=1bf2b720-b7b0-0137-0c3b-0e7672213108&app_version_id=17&status=4"}
```
Is `app_version_id=17` the equivalent of `release_id`?  Consistency is the hobgoblin of small minds, but it's helpful in this kind of context.  Interesting that we're still uploading to hockeyapp.  Anyway, since it's giving that back to me, why do I need to specify it in the call?  Looks like I don't need to.

However...when attempting to use my system's build number (obviously wrong, but it is an integer!) as the release_id for the upload, I got this:
```
{"status":"error","message":"Bundle Version does not match. Expected value: 104 Actual value: 1.0.0.0"}
```
I did specify 1.0.0.0 as the version number, and that is indeed the version number in the bundle manifest.

What are the right settings?

**Comment by RAM237** [comment]
Not really. I thought you mean release_id in the last step :) Sorry for misleading you!
The very first call goes just fine exactly as in the example - you can provide no body at all, only header and URL.

**Comment by lbrownell-gpsw** [comment]
@RAM237 -- Thanks, I guess, but that's also wrong.

First, [MS's interactive api documentation](https://openapi.appcenter.ms/#/distribute/releaseUploads_create) indicates the body *is* required.  And the page this issue is for provides a link to it just above the example, which seems sensible, since it would appear to be the definition of record, and you can actually execute a call there to see if you're on the right track.

What *did* work for me (before I saw your response) was to swap the values for `build_version` and `build_number` (yay hockeyapp, they always had those two switched around) and use any random integer for for `release_id`.

I just tried your suggestion of no body (weird thing to do with a POST, but whatever).  It "worked" but I got a bad HockeyApp URL back.  It was identical-ish (different generated IDs), except for these two missing parameters:

`&app_version_id=23&status=4`

Seems kind of important, given that the HockeyApp URL without them didn't work.

Oh, and that thing about HockeyApp mixing up versions and build numbers?  Still true.  Instead of showing Version as `1.0.0.0 (120)` (where 120 is the build number), it shows `120 (1.0.0.0)`. One that I uploaded via drag-and-drop shows only `1.0.0.0` (no build number).

Maybe I'm the only one using upload-via-api?

**Comment by RAM237** [comment]
Well, I wouldn't say that this api documentation is _mine_ :)

I am just one of users who tried appcenter a few days back, because my company has to migrate into it from HockeyApp. I came here to check about my request, saw your question above mine and decided to share my experience with you, since anyways there's not much help from support team )))

I haven't met any major issues trying those API calls described above as is. Meanwhile, I've found them quite not handy at all and, by the way, finally turned to using [AppCenter CLI](https://github.com/Microsoft/appcenter-cli) which allows to upload the binaries via single command `appcenter distribute release` similar to how it was on HockeyApp.

**Comment by lbrownell-gpsw** [comment]
@RAM237 My bad, I thought you *were* an MS guy!  Edited that post to not refer to it as "your" stuff.  Anyway, I did get it all working via the APIs, but I'll look at the CLI -- one line sounds mighty appealing.  Thanks for that!

**Comment by anywherepilot** [comment]
Hi @lbrownell-gpsw. I am sorry we took so long to respond. I believe you may be talking about the `release_id` parameter of the first call, the POST to `/apps/{owner_name}/{app_name}/release_uploads`. Is that correct? If that is so, please just ignore that parameter. You do not need to specify it. It is only used if you want to edit an existing release by uploading a different file to it. I have updated the documentation; you should see that online in a couple of days.

If you are referring to the `release_id` URL parameter in the last call, the POST to for example `/apps/{owner_name}/{app_name}/releases/{release_id}/groups` for distributing to a group: this is the ID of the release that App Center created during the previous call where you set the `status` of the upload to `committed`. That call returns a key `release_id` which you should use in the next call.

You can see the release IDs on the App Center website as the mostly sequential numbers in the Release ID column:

![image](https://user-images.githubusercontent.com/7290528/70506440-a1e8df80-1b6d-11ea-99dc-55ee09fd75fa.png)

The `build_version` and `build_number` parameters are only required in some cases, where they become the numbers you see in the Version column. I updated the documentation with those details as well. Once the changes are approved you will see them, and hopefully others won't experience these problems. Thank you for reporting!

**Comment by anywherepilot** [comment]
The documentation update will be live soon. I believe this addresses all questions, similar to the above comments. If not, feel free to reopen.
