### ISSUE TITLE
Example for distribution to group uses deprecated data, has missing fields

### ISSUE THREAD

**Issue by lbrownell-gpsw** [MicrosoftDocs/appcenter-docs#717]
"destination_name" is being replaced with the "destinations" structure, to specify one or more destinations.

The "build" structure seems to be required. If so, please update the example here.  If it is optional, please update the the model info here: https://openapi.appcenter.ms/#/distribute/releases_update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by botatoes** [comment]
Thanks for pointing it out, we've merged changed.
