### ISSUE TITLE
Safe to check App Secret into git?

### ISSUE THREAD

**Issue by tomjohnhall** [MicrosoftDocs/appcenter-docs#718]
These docs don't explain the implications of exposing `appSecret` and /or ways of keeping it safe by importing into`AppCenter-Config.plist` and `appcenter-config.json` from env variables- is this possible?

**Comment by nikitag-ms** [comment]
We do not recommend storing the app secret in a way that would make it accessible publically. This would allow other apps to submit telemetry to the App Center pretending to be yours. There are other security considerations as well.

Consider using the same approach that you use to store other secrets (like connection strings etc.)

**Comment by tomjohnhall** [comment]
I thought so, thanks for clarifying! I’d normally use an .env file but I’d guess this key couldn’t be imported in the js way as it’s needed as build stage? Currently just keeping it checked out of git (private repo, but just in case).

**Comment by nikitag-ms** [comment]
> needed as build stage? 

I do not think it's needed at build stage. As in, of course, you need to call the `Start` method and provide a value to it at build time. But it doesn't have to be a hardcoded string. You can pull it from somewhere not available to the public.
