### ISSUE TITLE
Confusing note on --save/--save-dev flag

### ISSUE THREAD

**Issue by ariya** [MicrosoftDocs/appcenter-docs#719]
The note

> `--save` or `--save-dev` flag is required in this step

causes some confusing because neither flag is mentioned anywhere as part of the installation step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed0fde7-9e78-c318-9f8c-9d921ec7d7b3
* Version Independent ID: 946ead1c-4b65-8318-c77a-ef98873adac7
* Content: [Get Started with React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#feedback)
* Content Source: [docs/sdk/getting-started/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by hamswan** [comment]
Thanks for reporting this, we will look into this.

**Comment by dhei** [comment]
Hi @ariya,

`--save` and `--save-dev` is no longer required for `npm install` in the current version of npm as npm saves the dependency automatically now. We will remove these flags from our doc.
