### ISSUE TITLE
Users not able to get In-App updates from a Public distribution group

### ISSUE THREAD

**Issue by prmeno** [MicrosoftDocs/appcenter-docs#720]
The Public Distribution group that gets automatically created with the name "All users of &lt;app name&gt;" does not allow In-App updates to a user unless he's added as a tester in this Group.
A Public group should allow updates to any user who has the App

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a807b36-339c-dd76-a6bb-132005991516
* Version Independent ID: 8ffb33e3-09fd-fe41-742f-a9f4d11bf901
* Content: [Manage App Center Distribution Groups - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/groups#feedback)
* Content Source: [docs/distribution/groups.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/groups.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by botatoes** [comment]
Tracking this request through https://github.com/microsoft/appcenter/issues/182 
we will ship this functionality this month.
