### ISSUE TITLE
Upload symbols

### ISSUE THREAD

**Issue by velbur** [MicrosoftDocs/appcenter-docs#723]
How to upload symbols using API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3219989-2e3e-06df-828f-61f0ee264131
* Version Independent ID: 15acc773-6d2e-79da-1abe-eaf3e23f5023
* Content: [Using the Diagnostics API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/using-the-diagnostics-api#feedback)
* Content Source: [docs/diagnostics/using-the-diagnostics-API.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/using-the-diagnostics-API.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by winnie** [comment]
Hi @imjustabearrr - you can upload symbols via API by following the instructions here: https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#app-center-api

Let me know if that works for you!
