### ISSUE TITLE
Mention of Push in setting up app in App Center link is vague

### ISSUE THREAD

**Issue by cainejette** [MicrosoftDocs/appcenter-docs#724]
Step 1 under "Create your app in the App Center Portal to obtain the App Secret" says:

To learn how to get started with Push, read the appcenter.ms documentation, where appcenter.ms is a link. It just links to appcenter.ms. Can it be updated to point somewhere more specific?

Also, is this even the section it should be in? This section is talking about creating an app in App Center to get an app secret.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ece9ab-9965-2ddf-34b6-44f0f61fe599
* Version Independent ID: 16261b98-a85e-060f-ccf4-3a24f5f14c4c
* Content: [Get Started with UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/uwp#feedback)
* Content Source: [docs/sdk/getting-started/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by blparr** [comment]
Closing as this is an internal request.
