### ISSUE TITLE
Client App on Android Devices

### ISSUE THREAD

**Issue by ygornascimento** [MicrosoftDocs/appcenter-docs#726]
Hello guys,

Nowadays exist an HockeyApp app at Google Play Store that serves as a client to manage the versions available to be downloaded. Will this same app work with AppCenter, or the HockeyApp app will die? 

Thanks in advance.

**Comment by anywherepilot** [comment]
Hi @ygornascimento. The app already worked with App Center, we just had not renamed it yet! It has been rebranded now: https://play.google.com/store/apps/details?id=com.microsoft.hockeyapp.testerapp&hl=en

I believe this answers your question. Feel free to reopen if not.
