### ISSUE TITLE
React Native limitations say to use CodePush for distribution but CodePush site links back to AppCenter

### ISSUE THREAD

**Issue by hkellaway** [MicrosoftDocs/appcenter-docs#727]
What is the recommended way to enact distribution for React Native apps using MS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55582d9f-9dae-4e97-99ff-edba1c0619d3
* Version Independent ID: dbb9424a-bbae-f444-6ced-a0c6e9e1ae77
* Content: [SDK Limitations & Known Issues - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/limitations#feedback)
* Content Source: [docs/sdk/limitations.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/limitations.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by haidalinda** [comment]
It seems CodePush is available currently within App Center - so the issue was that the docs are confusing

**Comment by BenjErgizerBunny** [comment]
I also found the docs confusing and I'm trying to setup CodePush today.  @hkellaway, were you able to find out what the proper solution is?

**Comment by haidalinda** [comment]
@BenjErgizerBunny the solution is to use CodePush via AppCenter - its already integrated into AppCenter. once you make an account, you'll see it among the services

just a confusing circular link
