### ISSUE TITLE
[Auth] Azure AD B2C - Password reset

### ISSUE THREAD

**Issue by NunoBem** [MicrosoftDocs/appcenter-docs#728]
We implemented B2C in a former project using MSAL sdk the sign up, sign in and password reset in "email accounts". For CI/CD, analytics and crashes we used AppCenter and liked the experience. So with the new Appcenter Auth we wanted to gather everything in our new project.

The **issue** for us is mainly, **unable to implement the password reset**.

We're unable to "call" the password reset policy has we do in MSAL sdk, so we had to hide the password reset label in the sign up sign in policy that Auth uses. 

But having the customer forgotten the password and email us, we reset it in the B2C dashboard. This gives a temporary password so the user can sign in and give a new password. But doesn't work, just gives invalid password error. We don't find any other way around this, besides deleting the account and ask them to sign up again. This is an awful user experience.

.
A not so critical issue will be implementing a login with native ui [#587](https://github.com/MicrosoftDocs/appcenter-docs/issues/587), that's already an open issue.

**Comment by radolo1111** [comment]
20.09.2019 2:31 PM "Nuno Bem" <notifications@github.com> napisał(a):

**Comment by NunoBem** [comment]
Wrong repo for this issue. Opened one in AppCenter [https://github.com/microsoft/appcenter/issues/1060](https://github.com/microsoft/appcenter/issues/1060)
