### ISSUE TITLE
The Crashes service doesn't really support React Native on Android

### ISSUE THREAD

**Issue by fedegl** [MicrosoftDocs/appcenter-docs#73]
This document is misleading since the Crashes service doesn't support SourceMaps for React Native on Android, which means that you won't get a line number of where the crash occurred, which in my opinion makes the Crashes services not very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0087c543-d8f4-5ea6-5ac6-8b30ec1b9e6c
* Version Independent ID: 92b8f8de-268b-a249-46e9-053edf2e97c0
* Content: [App Center Operating System/Platform Services Matrix - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/platform-service-matrix)
* Content Source: [docs/general/platform-service-matrix.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/platform-service-matrix.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by saraford** [comment]
Thanks for the feedback. Support for source maps for Android is on our roadmap.

**Comment by fedegl** [comment]
@saraford Should the docs specify that the support is not there yet, and also mention when will it be available? A checkmark doesn't address that nuance.
