### ISSUE TITLE
[Distribute for Android] What is a Release build? What is a debuggable build?

### ISSUE THREAD

**Issue by philhinco** [MicrosoftDocs/appcenter-docs#730]
In the [docs](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#enable-in-app-updates-for-debug-builds) it is mentioned that Distribute only works for "Release" builds.

What, according to AppCenter, is the definition of a "Release" build? Is the definition somehow tied to what Gradle defines as a debuggable/non-debuggable build? If so, a clarifying comment in the docs would be greatly appreciated.

In our case we have 4 different builds:

- Debug (self explanatory, no HockeyApp/AppCenter features enabled)
- CI (has/had HockeyApp's UpdateManager & Crash Reporting enabled)
- Beta (has/had HockeyApp's UpdateManager & Crash Reporting enabled)
- Release (only has Crash Reporting enabled)

Which of those would be considered a "Release" build? All except Debug? Or just "Release"?

I'm currently planning our migration, so I want to be sure that everything works as it has once we do the migration.

**Comment by philhinco** [comment]
Any news on this?

**Comment by olmisa** [comment]
Hi @philhinco . Debug build means that the `android:debuggable` flag is set to `true` (which is usually automatically set by gradle predefined debug build variants). Otherwise, this is a release build.

**Comment by olmisa** [comment]
Hi  @philhinco,  this information was added to the documentation. This issue will be closed since there is no answer for a long time. You could reopen this issue if it would be necessary. Thanks.
