### ISSUE TITLE
iOS - Distribute to App Store

### ISSUE THREAD

**Issue by gaecer** [MicrosoftDocs/appcenter-docs#731]
At the moment I am able to distribute an app to App Store just if I drag the .ipa file manually. With the enterprise license I can setup the certificate (Development or Distribution) to auto build and distribute the builds after a push to the repo.
Is it possible to distribute in the same way the build to the App Store? 
If on "build->branch->Sign builds" I put the **right** iTunes provisioning profiles and Certificate I'm getting an error: 
"
Oh no, we couldn’t configure your branch!

Provisioning profile "my profile name" does not include signing certificate "my certificate name"
"

**Comment by anywherepilot** [comment]
Hi @gaecer. You mention an enterprise license. Are you trying to use an enterprise provisioning profile?

I assume you had a look at the [documentation for iOS code signing](https://docs.microsoft.com/en-us/appcenter/build/ios/code-signing)?

App Center does support directly releasing to the App Store whenever you push code to a branch. Enable **Distribute builds** in the build configuration of your branch and select **Store**, then choose the store track you want to release to from the dropdown.

**Comment by King-of-Spades** [comment]
closing due to age / no response from last comment.
