### ISSUE TITLE
Issues with Edge and Create Key (JSON)

### ISSUE THREAD

**Issue by ZeProgFactory** [MicrosoftDocs/appcenter-docs#732]
The step: 

> On the new page click + Create Key (optional) and a modal appears.
> Select JSON and click CREATE and a file with the .json extension will download to your system; this file will be used in App Center to establish the connection to Google Play.

doesn't work on Edge 44.18362.329.0, nor on Internet Explorer. The generated file just vanishes. I had to use FireFox to be able to retrieve the JSON file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868e3edf-f3af-950e-4f8a-ea30c392e883
* Version Independent ID: a725a1f2-fe7b-b7be-8e5e-6db22c2a756d
* Content: [Publish to Google Play Store - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay#feedback)
* Content Source: [docs/distribution/stores/googleplay.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/googleplay.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by Oddj0b** [comment]
Thank you for reporting the bug. However, this repository and its issues are for reporting issues with our documentation, and I think this is a bug with Google's pages or Internet Explorer.

Please feel free to re-open if you think this is a documentation issue.

**Comment by ZeProgFactory** [comment]
It may by a bug with Google's pages or Edge, but the fact is that the "step by step" descritption isn't working for this reason. I belive that a notification would be a nice thing and prevent that people lost their time.
