### ISSUE TITLE
The macOS requirements are incorrect

### ISSUE THREAD

**Issue by mlilback** [MicrosoftDocs/appcenter-docs#738]
The macOS release notes say Xcode 10 is required, while this page says 8.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb38f19-e7f0-8349-8731-e701745c644f
* Version Independent ID: d8928ac3-206c-e8f3-0124-364311e4e4d7
* Content: [App Center SDK Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/#feedback)
* Content Source: [docs/sdk/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/index.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by anywherepilot** [comment]
Thank you for notifying us! An update is on the way.
