### ISSUE TITLE
Distribution group managers?

### ISSUE THREAD

**Issue by lbrownell-gpsw** [MicrosoftDocs/appcenter-docs#739]
Coming from HockeyApp, all our distribution groups have been replicated...but we use the manager role to allow different people to add/remove members.  This has disappeared from distribution groups, but does exist in teams (in fact, teams seem to map more closely to HA's distribution group concept).

Is the idea that you should use teams instead of distribution groups, if you want fine-grained access management to specific apps/builds?  Or will the Distribution Group "manager" concept come to App Center?  Or is it there and I'm missing it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a807b36-339c-dd76-a6bb-132005991516
* Version Independent ID: 8ffb33e3-09fd-fe41-742f-a9f4d11bf901
* Content: [Manage App Center Distribution Groups - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/groups)
* Content Source: [docs/distribution/groups.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/groups.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by fphilipe** [comment]
Our customers that self manage their distribution groups just pointed out to us that they can no longer add people to their group.

We rely heavily on this feature and cannot manage testers for our customers as it simply doesn't scale.

Are there any plans to bring this in to App Center?

**Comment by lbrownell-gpsw** [comment]
@fphilipe (et al), what we're looking at doing (yes, we haven't migrated hardly anything yet!) is making those who managed a group in HA be "users" of the app in question, and create the group they want for that app.  They can therefore manage the group.

What is unclear from the documentation (it might be there, but I haven't found it) is what level of app member you need to be to create/manage a group within an app.  Same with the org-level multi-app groups (which most of our HA groups were) -- probably Admins only.

That said -- it would be easier to have in-group managers...

**Comment by jvnike** [comment]
Hello. We have not looked at Teams yet, but here is how we are performing this in App Center:
1. User had Developer access to a HA, and created one or more Groups (which in HA are global by default).
2. We made sure the HA and Group are owned by our Organization, then move the app.
3. In AC, we set the user  in the Org level Collaborators group with the role of Collaborators. This means the user can managed membership for ALL shared distribution groups, but can only add or remove the apps that they have access to via the  Local App level Collaborators group.

**Comment by anywherepilot** [comment]
Let me summarize my understanding of the permissions system and then get back to your question.

**Overview**
Organizations have People, Teams and Distribution Groups. The People have roles "Admin", "Collaborator" or "Member". These are roles within the Organization and determine the actions the People can take regarding the adding and changing of People, Apps, etc. in the Organization.

The Teams are filled with People from the Organization. Adding an account to a Team before adding them to the Organization first is not possible. People and Teams (groups of People) can be assigned roles inside Apps. You can see these assignments in **Settings** > **People** in an app. Here you can add a Team to an App. You can also add an App to a Team from the **<Organization name>** > **People** > **Teams** > **<Team name>** > **APPS** overview.

Here you see different roles: "Manager", "Developer" and "Viewer". With regard to changing others' permissions, these roles affect what the People can do in the Distribution Groups of the App. Only People who (through their own permissions or those of a Team) have the Manager role in an App can add persons (not necessarily People) to Distribution Groups which are part of that App.

Distribution groups are only used for what their name implies: distributing releases. A distribution group can be added to an app, and an app can be added to a distribution group, which is the same thing. Adding someone to a distribution group does not add them to the organization. Let's call these Testers. Testers are only in a distribution group and not in the organization, they have no organization role and hence can do nothing but download releases.

When a Person (singular of People? 😄) with the Manager role in an App adds someone to a Distribution Group which is connected to that App, that someone now can also view all other Apps that Distribution Group is linked to.

**Issue at hand**
First, if you want new feature in App Center, please put in a feature request in the main repo. We regularly ship the top requests: https://github.com/microsoft/appcenter

The functionality I believe you are looking for, allowing only specific people to add others to be allowed to download releases, is the Manager role of a Team-App relation or a specific Person-App relation. Creating a relationship like this by adding a Person or a Team to an App (or an App to a Team, you can't currently add Apps to People) will allow them to manage the members of the Distribution Groups which are connected to that app.

If you instead want to create a group of people who is allowed to add other People to the Organization and determine who has which rights in which App etc., that is the Admin role you set on a Person.

I hope this at least clarifies what is possible. If what you want to do is not currently supported, please put in a feature request in the main repo. Thank you!

**Comment by anywherepilot** [comment]
Since this is quite old, @-ing everyone who had questions... See above @lbrownell-gpsw @fphilipe

**Comment by fphilipe** [comment]
> The functionality I believe you are looking for, allowing only specific people to add others to be allowed to download releases, is the Manager role of a Team-App relation or a specific Person-App relation. Creating a relationship like this by adding a Person or a Team to an App (or an App to a Team, you can't currently add Apps to People) will allow them to manage the members of the Distribution Groups which are connected to that app.

The point is that this person managing the distribution group is external. A Manager role  is at the organization level.

We have many customers, for each customer we have a distribution group. We build a white-label app and have a version of the app for each customer (iOS and Android). This distribution group has access to the customer's iOS and Android app.

We cannot add an employee of our customer as a member of our organization as that person would see our other customers and their apps.

At the same time, we don't want to manage the distribution group for our customer. The customer decides which of their employees and friends get to test their app. Thus, on HockeyApp, we gave a few employees of this customer the "Manager" role, which would push this responsibility to the customer.

Unfortunately, with the migration to AppCenter, our customers have to send us an email whenever a tester should be added or removed. This is painful for us as we have about ten customers.

Maybe I'm missing something, but as far as I can tell (and I tested), there's no way to push this responsibility of managing the distribution group to our customer, is there?

**Comment by anywherepilot** [comment]
Hi @fphilipe. I understand what you want to do now. That is not possible in App Center at the moment. The functionality is on the road map for the first half of 2020. I can't find a public version of that at the moment, but will link it below if I get it.

Even though it is already on the planning, you may add some priority to it by upvoting an issue for it in the main repository. Please have a look whether this describes your issue closely enough, then upvote it or create a new one and copy what you just wrote here down there: https://github.com/microsoft/appcenter/issues/1437

Do you believe there is any documentation issue at the moment? If not then I will link this issue to one in the App Center repository and close it here.

We do have doc for organization roles: https://docs.microsoft.com/appcenter/dashboard/creating-and-managing-organizations#organization-roles
App roles: https://docs.microsoft.com/appcenter/dashboard/creating-and-managing-apps#app-roles
Teams: https://docs.microsoft.com/appcenter/dashboard/creating-and-managing-teams

You can't distribute to a team like you can a distribution group.

Finally, there is a difference between shared distribution groups and app-level distribution groups: https://docs.microsoft.com/appcenter/distribution/groups#types-of-distribution-groups

**Comment by fphilipe** [comment]
> Do you believe there is any documentation issue at the moment? If not then I will link this issue to one in the App Center repository and close it here.

Works for me! I've upvoted microsoft/appcenter#1437. Thanks ✋
