### ISSUE TITLE
Eng/SW

### ISSUE THREAD

**Issue by Mullineaux** [MicrosoftDocs/appcenter-docs#74]
Hello Glenn,  Was noticing that this post speaks to PII, but not as much around methods used to I) Automated Secure Code Review, i.e. MS-approved methods to Inspect code posts by isolating known SI/Live links/Credentials, etc, ii)Monitoring & Tracking plans & investments, iii) Redundancy wrt AKV, or others. Can you say when we might hope to see more?  Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47ee8bb1-0229-793b-2766-1c8ed9a91d3f
* Version Independent ID: 4d368875-689b-4b1f-0fb6-716c0557b613
* Content: [Test Cloud Security - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/security)
* Content Source: [docs/test-cloud/security.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/security.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@glennwester this you?

**Comment by glennwester** [comment]
Hi @jwargo and @Mullineaux, 

Looking into this, will have an update soon.

**Comment by glennwester** [comment]
@Mullineaux Please see [Microsoft Privacy Statement](https://aka.ms/privacy) for App Center privacy terms and [Security Guide](https://www.microsoft.com/en-us/trustcenter/security) for additional details regarding our polices.

**Comment by Mullineaux** [comment]
a generic answer to 3 very specific questions, but thanks anyway.

cheers,

Mike
