### ISSUE TITLE
HockeyApp app sign-in

### ISSUE THREAD

**Issue by hkodungallur** [MicrosoftDocs/appcenter-docs#743]
1. I am looking at the transition now. But my old hockey app sign-in credentials are honored only on appcenter web, not when I try to sign in to the new App Center / HockeyApp mobile app (android). 
2. Are the existing HockeyApp api tokens honored when uploading to app center via a build tool like jenkins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27acd64c-5106-51ce-628c-8a1a17269e95
* Version Independent ID: d57cf8a3-d9de-4a8a-b746-e1f278e2c80c
* Content: [HockeyApp Transition - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/#feedback)
* Content Source: [docs/transition/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/index.md)
* Service: **vs-appcenter**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by dipree** [comment]
@hkodungallur please reach out to us via support (blue bubble).
1. The Android mobile app requires the same credentials as App Center web.
2. No, create new ones to use the App Center API
