### ISSUE TITLE
Problem setting up branch build config via API

### ISSUE THREAD

**Issue by benalexb** [MicrosoftDocs/appcenter-docs#746]
Hi everyone,

I was hoping maybe you could point me in the right direction. I have been trying to set up build configs on feature branches for our mobile pipeline using AppCenter's API. Master and Release branches are fine because we set them manually, and retrieving build status is also very straight forward using the endpoints
* `https://api.appcenter.ms/v0.1/apps/{OWNER}/{APP}/branches/master/builds`
* `https://api.appcenter.ms/v0.1/apps/{OWNER}/{APP}/builds/{BUILD_ID}`

But when it comes to actually setting up a build config from scratch by sending a POST to this endpoint `https://api.appcenter.ms/v0.1/apps/{OWNER}/{APP}/branches/{BRANCH}/config` I can never get it right. The API error I receive is not so insightful, it's always the same
```
{
    "id": "06cae000-247e-49eb-b3bb-628fa0ad2351",
    "message": "An error occurred"
}
```

One of the things I've tried is to fetch build configs for a working branch/build such as master (using `https://api.appcenter.ms/v0.1/apps/{OWNER}/{APP}/branches/master/config`), and then trying to send these same configs when trying to set up from scratch, but I sill get the same error I mentioned earlier.

I would like to share the payload I'm sending, but I reckon there's some sensitive information there.

I also tried using the cli, which works great to fetch build status or queue a new build for a branch that has already been set up, but I could not find a way to set up build configs for the first time using the cli.

Any suggestions, examples, or questions that might point me in the right direction?

Thank you so much! I really appreciate your help!

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by chriscoderdr** [comment]
@benalexb 
I don't know if that solves your problem or if you already solved it, but what I did was this

curl -X POST "https://api.appcenter.ms/v0.1/apps/$OWNER/$APP_NAME/branches/$BRANCH_NAME/config" -H  "accept: application/json" -H  "X-API-Token: $API_TOKEN" -H  "Content-Type: application/json" -d "{  \"cloneFromBranch\": \"dev\" }"

So I use my dev branch as a template for all the others, and when I make a merge request gitlab call this endpoint for the branch of the merge request
