### ISSUE TITLE
Powershell example needed. Specifically with environment variable reference.

### ISSUE THREAD

**Issue by L0G1C** [MicrosoftDocs/appcenter-docs#747]
Greetings,

I've been successfully able to setup a pre-build script using bash script for Android/iOS, but I'm now trying to create a powershell script for UWP platform and having issues getting the values of the App center environment variables I'm trying to get the value of the "pre-set" variable APPCENTER_SOURCE_DIRECTORY, as well as a custom environment variable I'm setting myself on the build configuration.

I think the appcenter-docs (or the github repo with the sample fiels) should have a few samples written in powershell as well! The bash ones were a major help.

**Comment by L0G1C** [comment]
In case I'm able to get any eyes on this. I want to share that I've tried using a powershell parameter like this (Where I have created an environment variable called ENV on the App center build configuration):

`Param(
	[Parameter()]
	[string]
	$ENV = "DEV"
)`

As well as just referring to the variable directly by name like this:
`if (![string]::IsNullOrEmpty($ENV)) { Write-Host "You need define the ENV variable in App Center" }`

In either case it seems the $ENV variable or parameter is empty

**Comment by L0G1C** [comment]
Another slight update. I just realized $ENV is a special variable in powershell. But issue still exists as I'm unable to pull the value for  $APPCENTER_SOURCE_DIRECTORY

**Comment by anywherepilot** [comment]
Hi @L0G1C. In PowerShell you get variables from the environment using the `$env:<VARIABLE_NAME>` syntax. Have you tried that? It is documented briefly here: https://docs.microsoft.com/en-us/appcenter/build/custom/variables/#build-scripts

**Comment by anywherepilot** [comment]
Feature Request label for UWP examples in https://github.com/Microsoft/appcenter/tree/master/sample-build-scripts

**Comment by King-of-Spades** [comment]
I transferred this over to the App Center repository since that hosts code samples.
