### ISSUE TITLE
Change "stared" to "started" typo

### ISSUE THREAD

**Issue by theyota** [MicrosoftDocs/appcenter-docs#75]
You can expect API support for everything you see in the portal. We have a swagger as well as documentation on how to get stared with our APIs.  Change "stared" to "started". hope this helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb96601-f906-374d-b0d8-537e5f80de3e
* Version Independent ID: b66d21ae-1205-3d76-f577-d58891382c08
* Content: [App Center Push API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/push/pushapi)
* Content Source: [docs/push/pushapi.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/push/pushapi.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by jwargo** [comment]
@theyota thanks for letting us know, fixing it now.
