### ISSUE TITLE
Not working for XCUITest

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/appcenter-docs#750]
I tried using   `--test-parameter "test_env=USERNAME=clever_user@example.com"` to pass the env to the test. But it doesn't seem that the test can retrieve the env using `ProcessInfo.processInfo.environment`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01181288-ab5c-4fd5-1d76-3d5dbe61c486
* Version Independent ID: 2aeffa5c-b5b5-cf71-e382-4210e7d10454
* Content: [Environment variables - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/environment-variables#feedback)
* Content Source: [docs/test-cloud/environment-variables.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/environment-variables.md)
* Service: **vs-appcenter**
* GitHub Login: @GlennWilson
* Microsoft Alias: **v-glenw**

**Comment by jmoody** [comment]
You are correct, this is not working in XCUITest.  We have updated the docs to reflect this.

We are tracking this feature internally.

**Comment by stoneman** [comment]
Closing as the docs are now accurate. They will be updated again once the capabilities have been added to XCUITests running in App Center.
