### ISSUE TITLE
Blue chat button is useless

### ISSUE THREAD

**Issue by gtgray** [MicrosoftDocs/appcenter-docs#752]
Hi there!
Your blue chat button is useless.
I try to ask questions to solve my issue with app testing in chat, but getting no answer.
Thejaswini is always away. 2 days already (but there was told that 24h delay for answering).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dd71a0-a249-a87b-e4eb-e4da0a20472f
* Version Independent ID: 450c26f5-ab13-8df5-d45a-6086f5391b23
* Content: [App Center Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/support-center)
* Content Source: [docs/general/support-center.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/support-center.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by blparr** [comment]
Hi @gtgray , sorry to hear - I think I found your conversation and reassigned to the right team. They should be in touch with you soon. If that's not the case, please ping us here. Closing this for now.
