### ISSUE TITLE
Wrong CocoaPods version.

### ISSUE THREAD

**Issue by tobiasjunsten** [MicrosoftDocs/appcenter-docs#753]
The document states CocoaPods 1.7.5 but is 1.8.1 and that breaks my build :(. My build is a Flutter build. So pleas add support for flutter! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022126c7-2d61-9c53-6881-149310c137c0
* Version Independent ID: 4fe62fb4-6dd9-057e-8f57-fb4c6dcb71f8
* Content: [App Center Cloud Build Machines - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/software#feedback)
* Content Source: [docs/build/software.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/software.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **niloferr**

**Comment by anywherepilot** [comment]
Thank you for reporting this. Keeping all the versions up to date sometimes fails. We do our best! We recently changed the format of this page, however it still has the same information. I see the CocoaPods version is now set to 1.9.1, so I will close this issue.
