### ISSUE TITLE
Crashes.TrackError documentation unclear about when it sends.

### ISSUE THREAD

**Issue by dweedul** [MicrosoftDocs/appcenter-docs#755]
While implementing this in my WPF application, I found that it queues up the information from `Crashes.TrackError()` calls, and only sends them when a Crash notification is finally sent.  This was very confusing, and would benefit from one of the big callouts letting folks know that it won't send on handled errors until later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eae5644-1b90-680a-25aa-9ebc77b3ce58
* Version Independent ID: 05a373b3-f6eb-e92e-72a3-d8bd49fa9aab
* Content: [App Center Crashes for Windows - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms#feedback)
* Content Source: [docs/sdk/crashes/wpf-winforms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/wpf-winforms.md)
* Service: **vs-appcenter**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by TranstecJasonD** [comment]
I just started using this today, but it's working fine for me in WinForms. When I use TrackError for a handled exception, the report is sent right after I restart the app.

**Comment by russelarms** [comment]
Hi @dweedul, sorry for the delay, the issue has only appeared on our board this week.
I've tested Crashes.TrackError on our [WPF demo project](https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/Apps/Contoso.WPF.Puppet/MainWindow.xaml.cs#L268) and the SDK sends the logs to the backend on each TrackError call. Do you still experience this behavior with the latest (3.1.0) SDK version?

**Comment by russelarms** [comment]
I'm closing this issue now, feel free to reopen it if it is still a problem.

**Comment by dweedul** [comment]
I haven't checked since I opened the issue. I'll check later and reopen like you said.

Thanks!
