### ISSUE TITLE
Start the App Center SDK, Xamarin.Forms

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/appcenter-docs#756]
There is no exact information about where to put new App Center code in.
it will be great help if you can clearly specify where to put "AppCenter.Start()" on all three types of projects specially Xamarin.Forms, since it has change a bit to App.Xaml.cs. Info can found in https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin#423-xamarinforms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e158918e-8740-6b57-4579-9baa3db532ac
* Version Independent ID: 9d14e1ae-ca37-791b-44eb-e3448cbc70ae
* Content: [HockeySDK for Xamarin Migration - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/xamarin-sdk-migration)
* Content Source: [docs/transition/xamarin-sdk-migration.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/xamarin-sdk-migration.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by PRMerger6** [comment]
GitHub user hamswan has been removed from the MicrosoftDocs organization, so they were automatically removed as an assignee.

**Comment by timeyoutakeit** [comment]
Hey @ahdbilal, would you be able to add some clarification to this document? Thanks.

**Comment by russelarms** [comment]
The document was updated, so I'm closing the issue.
