### ISSUE TITLE
Dealing with permissions dialogs?

### ISSUE THREAD

**Issue by milanio** [MicrosoftDocs/appcenter-docs#759]
I eventually found it for Android at - https://forums.xamarin.com/discussion/62141/handling-permission-requests-in-marshmallow. But this seems like well-hidden secret - shouldn't it be directly somewhere here? There will be plenty of apps which needs to be granted permissions during test runtime...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd5535b-f176-9808-90c3-e35d1ad4ca88
* Version Independent ID: 382fe3a0-b895-8283-95ad-615475c94d5e
* Content: [Xamarin.UITest cheat sheet - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/cheatsheet)
* Content Source: [docs/test-cloud/uitest/cheatsheet.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/cheatsheet.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by Oddj0b** [comment]
@milanio thank you for reporting it, I'll add it to the cheatsheet next week.
