### ISSUE TITLE
createPom gradle Task

### ISSUE THREAD

**Issue by marisaroman** [MicrosoftDocs/appcenter-docs#76]
I ran into a few issues attempting to follow these instructions. 

1. I believe the final curly brace is missing from the code snippet. I had to add one for the Gradle build to work.
2. There is a comment in the createPom task indicating that we don't want to iterate over test dependencies, but the subsequent line of code appears to be iterating over the test dependencies. Which is correct?
3. The pom being produced for my project ends up with two dependencies nodes, which is causing a problem. I couldn't figure out how to fix the gradle script to resolve this problem, so I just deleted the extra dependencies node from the pom.
4. I had to add a groupId and the jcenter repository to the pom in order for the maven execution to work.

For now, I will just commit the modified pom.xml file and remove the createPom task from build.gradle in my project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium)
* Content Source: [docs/test-cloud/preparing-for-upload/appium.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by glennwester** [comment]
Hi @marisaroman, thanks for making us aware. I'm having one of our engineers review this and we'll update the docs to make this right.

**Comment by jwargo** [comment]
@glennwester close this issue or leave it open until engineering has looked at it?

**Comment by marisaroman** [comment]
Great - thank you!
