### ISSUE TITLE
Owner Mapping

### ISSUE THREAD

**Issue by lbrownell-gpsw** [MicrosoftDocs/appcenter-docs#761]
For this:
"All Apps" flag is false && "All Distribution Groups" flag is false && "All Distribution Groups" flag is false == Member

Did you mean this?
"All Apps" flag is false && "Billing" flag is false && "All Distribution Groups" flag is false == Member

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f26fc9-b652-dd7f-9232-3400bdfa884c
* Version Independent ID: 6cdf238b-c699-a5e1-abad-447993158895
* Content: [HockeyApp Accounts in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/accounts/)
* Content Source: [docs/transition/accounts/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/accounts/index.md)
* Service: **vs-appcenter**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by dipree** [comment]
@lbrownell-gpsw good catch, fixing.

**Comment by anywherepilot** [comment]
I assume Daniel actually fixed it. The original page no longer exists.
