### ISSUE TITLE
[iOS Distribute] The distribute delegate interface uses ! (force unwrap) operator in method selector

### ISSUE THREAD

**Issue by huNt-FMJ** [MicrosoftDocs/appcenter-docs#764]
Hi there,

when taking a look at the generated swift method selector, the parameter types are annotated using the force unwrap operator. This indicates that the Objective-C method selector and class are lacking the nullability annotation.

```
optional func distribute(_ distribute: MSDistribute!, releaseAvailableWith details: MSReleaseDetails!) -> Bool
```

It would be great if the nullability specification could be done on the SDK side.

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For feature request, see the [App Center public repo](https://github.com/Microsoft/appcenter/issues/new/choose).
