### ISSUE TITLE
"Unauthorized" responses when make API Request

### ISSUE THREAD

**Issue by balivo** [MicrosoftDocs/appcenter-docs#765]
Hi everyone,

My (own) admin panel has a push send functionality connected to AppCenter, I have 2 types of push, immediate and scheduled... In the immediate push, a message is sent at registration and everything works perfectly... Scheduled push, registers a message to be sent in the future through a Timer Trigger Function that every hour consults the pending messages and sends them according to the established time.

When sending via Function that triggers an Endpoint from my API to send the messages using AppCenter, the AppCenter API requests return "Unauthorized" status, but I am using the same web panel token (used in immediate way).

This is intermittent, not every time AppCenter API calls gives error, sometimes it fires correctly.

Any information about?

Tks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dd71a0-a249-a87b-e4eb-e4da0a20472f
* Version Independent ID: 450c26f5-ab13-8df5-d45a-6086f5391b23
* Content: [App Center Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us)
* Content Source: [docs/general/support-center.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/support-center.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by jwargo** [comment]
@balivo have you discussed this issue with our support team? What did they tell you?  The token should work in both cases and I'm assuming you compared the requests to ensure they're both the same?  To connect with App Center support, use the blue chat button in the lower-right corner of any app center page; that connects you with our dedicated support team

**Comment by balivo** [comment]
Hi... I'm talking with support team and we investigating yet....

Tks!

**Comment by jwargo** [comment]
@balivo I'm assuming you have this issue addressed. In case you missed it: We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

**Comment by balivo** [comment]
Yes @jwargo, and I moving to new services... Tks!
