### ISSUE TITLE
IP Addresses

### ISSUE THREAD

**Issue by joaosilvareed** [MicrosoftDocs/appcenter-docs#77]
I need to whitelist the app center IP Address so that it does have access to our environments for testing, what are the IP Addresses?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb0ff0a-1fb7-9362-34e4-50879d07f0f2
* Version Independent ID: 469a4e00-53a3-b903-eb0d-1d307b4b4166
* Content: [Preparing Xamarin.UITests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/uitest)
* Content Source: [docs/test-cloud/preparing-for-upload/uitest.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/uitest.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@joaosilvareed The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by joaosilvareed** [comment]
@jwargo  And this should be part of the documentation? Like this: https://developer.xamarin.com/guides/testcloud/uitest/working-with/submitting-tests-to-xamarin-test-cloud/#Firewall_Configuration

**Comment by jwargo** [comment]
@joaosilvareed I've started a conversation with program management to investigate publishing the list of endpoints. In the mean time, reach out to our support team through the link I gave you and you'll get an answer.

**Comment by rogerhmar** [comment]
@jwargo Any progress on this?

**Comment by jwargo** [comment]
@rogerhmar no, not that I'm aware of. I'll ask again.

**Comment by jwargo** [comment]
@rogerhmar so I spoke with Engineering on this topic and got the answer. We don't publish the IP address list, mostly because there's no guarantee they'll stay the same. As we adjust our infrastructure, our resources could (and can) get new IP addresses.
