### ISSUE TITLE
New users / activations

### ISSUE THREAD

**Issue by jbrodriguez** [MicrosoftDocs/appcenter-docs#771]
Is it possible to track new users of my app ?

It's an important metric to know how many new users the app is getting.

I can't see that info in the dashboard, nor I can seem to get notified about it via email.

Thanks in advance for any insights.

**Comment by blparr** [comment]
This is not available at the moment. We encourage you to create a feature request in our App Center Github repo to see if it gets traction from other users.

https://github.com/microsoft/appcenter/issues
