### ISSUE TITLE
Unclear how to "Copy the upload_url"

### ISSUE THREAD

**Issue by armandzwan** [MicrosoftDocs/appcenter-docs#775]
At 3b of 'Uploading using the APIs', the instructions are : Copy the upload_url ...
But there is no example of how to do that in a script or something similar. Maybe it is out of the scope of this page, but a few examples (in Shell?) would be very helpful.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/nl-nl/appcenter/distribution/uploading#feedback)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by manju656** [comment]
Here is how i did it in my shell script:
API_1_RESPONSE=$(
curl -X POST "https://api.appcenter.ms/v0.1/apps/${OWNER_NAME}/${APP_NAME}/release_uploads" -H "accept:application/json" -H "X-API-Token: ${APPCENTER_API_TOKEN}" -H "Content-Type: application/json" -d "{ \"release_id\": ${RELEASE_ID}, \"build_version\": \"${BUILD_VERSION}\", \"build_number\": \"${BUILD_NUMBER}\"}")

upload_id=$(echo $API_1_RESPONSE | awk -F '"upload_id":"' '{print $2}' | sed "s/\".*$//")
log "UPLOAD_ID ...$upload_id"

upload_url=$(echo $API_1_RESPONSE | awk -F '"upload_url":"' '{print $2}' | sed "s/\".*$//")
log "UPLOAD_URL ...$upload_url"

**Comment by jeffkelsey** [comment]
Script causes errors, `upload_id=$(echo $API_1_RESPONSE | awk -F '"upload_id":"' '{print $2}' | sed "s/".*$//")` is not formatted correctly

**Comment by anywherepilot** [comment]
The current documentation is already quite thorough in the steps you need to take. I wrote it by manually executing all these steps in Postman. If you are writing a script to perform the actions, then you hopefully know how to extract properties from a response into a variable in the scripting language you are using.

**Comment by anywherepilot** [comment]
Feature Request label for adding scripts on top of manual API steps. I doubt we will do this, since there are more important things to work on regarding API documentation. This is the only page I am aware of that really describes how to do anything with the API, while the API can be used to do almost everything.

**Comment by King-of-Spades** [comment]
@anywherepilot So is your recommendation for this to create a sample if possible/feasible?

**Comment by anywherepilot** [comment]
@King-of-Spades It's what would be needed to resolve this issue. It's not a recommendation per se. My recommendation is to have a different page somewhere which actually describes in detail, including scripts you can copy paste and build on top of, how to use our API.

This page just describes how to use the API (which calls to make) in this particular scenario. How you make those calls, either manually or through a script, is up to the reader. It's not a script you can just copy paste. In places like this we should have a link to the general API documentation that we would have to write first.

**Comment by ahdbilal** [comment]
Closing this issues. I agree with @anywherepilot recommendation. We should probably create another page that can share some scripts on how to use our APIs.
