### ISSUE TITLE
Mention of Apple Admin account - can developer role be used?

### ISSUE THREAD

**Issue by msifniotis-bbc** [MicrosoftDocs/appcenter-docs#777]
Hi team!

The Apple Store docs state 
"An active Apple Developer Program account, or have your Apple ID added as an admin in your teams iTunes Connect account."

For Internal Testflight upload purposes, can you clarify whether an account with developer permission would be enough to do this? 

Currently in our build system we use a developer role instead of admin and I am not sure why admin access would be needed in AppCenter side

Here is Apple's Role table
https://developer.apple.com/support/roles/

Thank you,

Maria

**Comment by Oddj0b** [comment]
As a developer role, you're not able to create apps or submit new versions that are required for an app store release. I'll also create a PR for the documentation.

**Comment by msifniotis-bbc** [comment]
@Oddj0b Does the above mean that were we to give access with developer role instead we could restrict to Testflight upload? (And then decide if we wanted the elevated features of new version creation etc, we would give administrator access..)

**Comment by Oddj0b** [comment]
@msifniotis-bbc I believe that should be possible.
