### ISSUE TITLE
Hockey App Api Tokens

### ISSUE THREAD

**Issue by jeffkelsey** [MicrosoftDocs/appcenter-docs#779]
I understand that the Upload API endpoint is still accessible, but what about the Hockey App API tokens required for making these POST requests? Are these API tokens still valid? Do we need to generate new tokens for App Center migration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c4f7c6b-8208-7e5e-4145-255f4c11d907
* Version Independent ID: 731aaf8b-9300-ce44-3ff5-20c585a7b5b5
* Content: [HockeyApp to App Center API migration - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/api#feedback)
* Content Source: [docs/transition/api.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/api.md)
* Service: **vs-appcenter**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by guidovezzoni** [comment]
Also is APP_ID the one coming from HockeyApp or it an AppCenter ID?
Is the host for this call going to be https://rink.hockeyapp.net or https://api.appcenter.ms ?

I tried with the old hockeyapp values of token, appid and host and I'm uploading only in hockeyapp.
I tried with the new version of these and I can't get it to work

**Comment by guidovezzoni** [comment]
Just to clarify my message above I'm getting:

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.15.8</center>
</body>
</html>

```

**Comment by dipree** [comment]
Only the HockeyApp API token is valid. You keep the API call as it was in HockeyApp, not changing the app id or the url to call.

We'll clarify that in the docs.

**Comment by guidovezzoni** [comment]
Thanks for the fast answer!
I currently use a curl command to upload my apk and if after the migration I use the same script I had for HockeyApp, it will re-create my HockeyApp app rather than uploading it in AppCenter.
Is there anything that I need to change to upload directly to AppCenter?

**Comment by grndvl1** [comment]
SO basically we do not need to do anything with our CircleCI scripts?  THey all point to hockeyapp so it should work with tokens, groups...all those IDS will remain the same?
