### ISSUE TITLE
Xamarin.UITest support is a joke - don't know even where to write

### ISSUE THREAD

**Issue by artur-malendowicz-gain** [MicrosoftDocs/appcenter-docs#781]
![image](https://user-images.githubusercontent.com/50327899/67767508-02560e80-fa51-11e9-8348-6c5de8c893ea.png)

So what is that? Where can I ask about help regarding that issues? There is no github for Xamarin.UITests and no help anywhere. Do you even support it officialy?

**Comment by Oddj0b** [comment]
Hi @artur-malendowicz-gain,
This repo is for the documentation and we're looking for constructive criticism and pull requests with documentation improvements.

To get help with Xamarin.UITest I recommend asking the App Center support by clicking the blue chat icon in the lower right side of the portal.

**Comment by artur-malendowicz-gain** [comment]
@Oddj0b great, then we can say that Xamarin.UITest framework has no support at all, because everything I ask at the "blue chat icon" they say they will "investigate" and then ask me for retrying x, y, z while I inform them that nothing is working and nobody can make it work.

**Comment by Oddj0b** [comment]
I'm sorry that our supporters haven't been able to help out with your issue. The reason our support is asking for your help and will need to investigate is that Xamarin.UITest is highly customizable and not every case is the same.
