### ISSUE TITLE
Coming from HockeyApp and can't find my "App Secret"

### ISSUE THREAD

**Issue by altimac** [MicrosoftDocs/appcenter-docs#782]
"Make sure to replace {Your App Secret} text with the actual value for your application. The App Secret can be found on the Getting Started page or Settings page on the App Center portal."
Unfortunately the "Getting Started" page seems to display an example, not the actual App Secret. And the "Settings" page does not exist either. I'm just lost.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45228922-4a96-8c08-7d27-69ef98d44943
* Version Independent ID: d04ef359-7b17-8a14-970b-5c48820976cd
* Content: [Get Started with iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#feedback)
* Content Source: [docs/sdk/getting-started/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by altimac** [comment]
Getting Started provides some code. The App Secret seems to be a variable so the code shows the correct App Secret. How am I supposed to know that?
There is nowhere in my app page where I can see my App Secret. This should be visible in the Overview section.

**Comment by dipree** [comment]
@altimac sorry for the struggle there. The app secret can be found in the app settings and then in the upper right corner there's a vertical three dots menu. Clicking that will reveal an entry to "Copy app secret".

I will assign this to my colleagues to ensure we're pointing that out in the documentation correctly.

**Comment by altimac** [comment]
IMHO the App Secret should not be hidden like this. It's a very important information and should be accessible more easily. For example in the App settings > App details "box".
Just my 2cents. Thanks for the reply!

**Comment by anywherepilot** [comment]
We updated all docs like this to clearly indicate where to get the app secret. Suggestions for improving App Center itself, like making the app secret more obvious to find, should go here: https://github.com/microsoft/appcenter/issues
