### ISSUE TITLE
In Default Payload - What variables from App Center can be used?

### ISSUE THREAD

**Issue by W0GER** [MicrosoftDocs/appcenter-docs#783]
We would like to pass along the version of the app to a specific field in Azure Dev Ops (eg Found in build field). However, to do so would require App Center to provide the version as a variable. I've looked and can't find any list of supported variables that can be used in the Default Payload section. Please provide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99771c68-5f45-887a-e926-9ea772021f99
* Version Independent ID: 865109fc-64b8-ba77-2e10-8002886c46c7
* Content: [App Center bug tracker documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/index)
* Content Source: [docs/dashboard/bugtracker/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/bugtracker/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by shipitfaster** [comment]
Agreed, the link provided in AppCenter goes to a generic page, not specific to work item payloads. Very confusing and not sure how to proceed as I need my bugs to go to a specific path or tagged specially.

**Comment by araujoraphael** [comment]
Any luck guys?
