### ISSUE TITLE
To document limitations of AppCenter with Appium

### ISSUE THREAD

**Issue by ashishmundrajll** [MicrosoftDocs/appcenter-docs#784]
We started using Appium with AppCenter and hit following limitations due to which we stopped using AppCenter. It would have saved us some time if these limitations were documented somewhere. Posting what we found so that if you have some apps which has this, you can avoid using AppCenter.

1. If mobile App opens a WebView in browser, e.g. in our case we use ADB2C for Authentication which opens a Browser window. Such Mobile Apps cannot be tested using Appium + AppCenter combination.

2. If mobile App opens a Camera App, then such application cannot be tested using Appium + AppCenter.

3. AppCenter does not support JUnit version &gt; 4.12 and hence if your tests are reading Parameters from an Excel and using @Parameterized, that will not work, you will have to keep your test data in a config file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1f8239-19fa-9c4b-52f5-b9c19cafbb4a
* Version Independent ID: 1980a317-8a4a-10b3-eedd-32af9d36cfbe
* Content: [Supported Test Frameworks - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/supported-frameworks)
* Content Source: [docs/test-cloud/supported-frameworks.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/supported-frameworks.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by King-of-Spades** [comment]
Thanks for the feedback! Those limitations are currently documented for preparing tests for upload here: https://docs.microsoft.com/en-us/appcenter/test-cloud/appium/preparing-for-upload
