### ISSUE TITLE
Upload a build to App Center via API or CLI: Version and build number, and distribution groups

### ISSUE THREAD

**Issue by lbrownell-gpsw** [MicrosoftDocs/appcenter-docs#785]
The `release_uploads` API requires that you specify version and build number.  Which I did for an app upload.  But there are some problems with it:
* Build number and version are switched.  I had to enter 1.0.0.0 (the version number) for the build number and 155 (the build number) for the version number.  If I do it the other way, I'm told that the version number supplied (1.0.0.0) doesn't match the expected value (155). I'd also gotten that 1.0.0.0 isn't an integer.
* If I don't provide build number and version, I get an error because they are missing.
* The end result is that I do get an new release, but with version/build as "155 (1.0.0.0)".  Not good!

This problem existed in HockeyApp, too, if you had an app type that it couldn't derive the version/build number from data inside the app.  Fortunately, you just didn't pass the version/build number and it would do the right thing.  However, we had other apps that didn't work for, and they always had version and build backward.

Can we get that fixed?  Or tell me how to use these apis so that it will work?

UPDATE 1:  In the API documentation page for this ticket, it doesn't show providing the body in the POST to `release_uploads`.  POST with no data?  Weird.  I tried it and it worked, except the build number wasn't included, only the version number.  I had previously tried sending only the build number or version, which was rejected because if you include post data, all fields are required.  And they are still wrong.  This is probably a fault of the release package, not having the data available.  But for custom applications (still on the roadmap for Nov 16th, yes?) the ability to set the version and build number correctly, manually, will be required.

Please fix the api swagger page to indicate that the post data isn't required -- and in fact, is incorrect.

UPDATE 2:  Found how to add groups to an existing release (or releases), via `appcenter distribute releases add-destination`, so the following isn't critical.  That said, it seems like it would be good to be able to add multiple groups to a release when creating the release -- via one call.

I'd be fine with the CLI, but it appears it can only add one distribution group at upload time.  Is that not correct?  Also, it isn't obvious how one can add distribution groups after upload to a release.  The `appcenter distribute groups` command doesn't appear to have an option to add a distribution group to a release.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by lbrownell-gpsw** [comment]
UPDATE: It appears that the requirement that the version number parameter be an integer has been removed, and there is no restriction either on build number.  This allows the user (me) to pass the values into their correct fields, in the case of an upload type that App Center can't otherwise determine the version/build number.  This is excellent!

However, the swagger page still shows the body as required.  I'm not using it on apps where the version/build can be extracted, and it's working well.

**Comment by tomhaycockwest** [comment]
Would you mind providing an example of how you have passed in the release_id, build_number and build version. I can see that the release_id needs to be an integer. The build_number and build_version need to be strings. The command below succeeds but all of the parameters are ignored and therefore not reflected in app center.

RESULT=$(curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "X-API-Token: $TOKEN" -d '{ "release_id": '"${RELEASE_ID}"', "build_version": "'${BUILD_VERSION}'", "build_number": "'${BUILD_NUMBER}'"}' "https://api.appcenter.ms/v0.1/apps/${APP_OWNER}/${APP_NAME}/release_uploads")

**Comment by lbrownell-gpsw** [comment]
Very late reply @tomhaycockwest -- note that my response prior to yours indicates that it was working then, for me. Version and build are indeed strings (thus, no restrictions), and the release ID is the App Center ID. You needn't pass them if the app type is one that App Center can dig into the bundle and determine what they are (e.g., iOS, Android).  Others, not so much (especially "Custom", which we have some of).  That said, we just recently tried uploading our first custom os build -- failed, 422:  "status":"error","message":"Version could not be created from build."  Harrumph.

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
