### ISSUE TITLE
Crash reports from Visual Studio

### ISSUE THREAD

**Issue by jamers99** [MicrosoftDocs/appcenter-docs#788]
In the docs it says it only supports crashes from "both beta apps and those submitted to the Windows Store".  What does a "beta" app mean?  A package pushed to App Center?  A package made for Sideloading?  Does it have to be associated with the store?

I'm trying to get a crash report on something I am reproducing locally, but our app is not yet in the store, nor associated with the Store.  What can I do to get the crash report?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5756765e-fef2-e8d9-f8d9-5c01690095b8
* Version Independent ID: b474e30a-6e59-97fc-476a-92be5ec3a01a
* Content: [App Center Crashes for UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp)
* Content Source: [docs/sdk/crashes/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by annakocheshkova** [comment]
Hi there @jamers99, crash reports should work locally. Just make sure you detach the debugger.
If something's not working, let us know.

**Comment by jamers99** [comment]
Yes, thank you. Full crash logs are now officially supported in UWP.
