### ISSUE TITLE
Xamarin UI Tests Template

### ISSUE THREAD

**Issue by AutumnEvans418** [MicrosoftDocs/appcenter-docs#790]
I am not seeing the Xamarin UI Test template in visual studio 2019.  What is the correct way to create ui tests for xamarin forms in visual studio 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d92e81-8d62-5775-b110-882c6ad6aa9a
* Version Independent ID: 62d282ce-ab98-46d1-1b82-fd28260330d2
* Content: [Get started with UITest and Xamarin.Forms - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/get-started-xamarin-forms)
* Content Source: [docs/test-cloud/uitest/get-started-xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/get-started-xamarin-forms.md)
* Service: **vs-appcenter**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @chrisevans9629 

It's available in VS2019 if you search on uitest in the mobile category:

![uitest](https://user-images.githubusercontent.com/8092460/68043461-405f6680-fccd-11e9-8683-c13ebc39ab39.PNG)
