### ISSUE TITLE
Missing react-native using Expo

### ISSUE THREAD

**Issue by ronaldokz33** [MicrosoftDocs/appcenter-docs#791]
Hi, 

I'm began use react-native lately and I'm using Expo for develop.

My question is, how do I configure the android native part without eject my project?

I tried eject and configuring but I had more problems then I solved.

Thank you.

**Comment by blparr** [comment]
Hello! Would you mind reaching out to us via in-portal support? We have a dedicated team ready to help you with your questions.

Thanks!
