### ISSUE TITLE
Installation snippets for Kotlin

### ISSUE THREAD

**Issue by yorch** [MicrosoftDocs/appcenter-docs#792]
Started developing Android with Kotlin, and would be helpful to have the installation example snippets (and possibly other snippets) in Kotlin along side Java.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa9700f5-b9e0-dfe1-ddbc-b5a3231dde11
* Version Independent ID: 11728c80-1474-c1dc-caf0-2c6b6c44bbb3
* Content: [Get Started with Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android)
* Content Source: [docs/sdk/getting-started/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by guperrot** [comment]
Hi, you can already switch documentation to Kotlin from any of our Android SDK pages:

<img width="873" alt="Screen Shot 2019-11-05 at 12 05 15 PM" src="https://user-images.githubusercontent.com/623672/68242001-93366800-ffc4-11e9-8b3f-7bf31f4525b2.png">
