### ISSUE TITLE
Xamarin Android build fails during signing phase

### ISSUE THREAD

**Issue by ataparia** [MicrosoftDocs/appcenter-docs#793]
Hello,
I have configured a Xamarin Android project to build using app center. I have also configured Xamarin.iOS and UWP projects which builds file but the xamarin android project fails with the following message:

Task         : Android Signing
Description  : Sign and align Android APK files
Version      : 1.122.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613717)
==============================================================================
[command]/usr/bin/jarsigner -keystore /Users/runner/runners/2.159.2/work/1/s/.certs/keystore.jks -storepass *** -keypass *** -verbose -sigalg MD5withRSA -digestalg SHA1 -signedjar /Users/runner/runners/2.159.2/work/1/s/DevelopmentUtilities/AdobeReader5/adobe-reader.apk /Users/runner/runners/2.159.2/work/1/s/DevelopmentUtilities/AdobeReader5/adobe-reader.apk.unsigned ***
jarsigner: unable to sign jar: java.util.zip.ZipException: invalid entry compressed size (expected 35616 but got 36379 bytes)
##[error]Error: /usr/bin/jarsigner failed with return code: 1
##[error]Return code: 1
##[section]Finishing: Sign APK
##[section]Starting: Checkout

I have checked and the credentials to the signing key are right.
Can you guys please help me on this?

Thanks
Amit

**Comment by nilofer** [comment]
Hi @ataparia, can you please reach out to App Center support for this issue? We can dig into the error better there. Thanks!
