### ISSUE TITLE
Creating team without being part of it

### ISSUE THREAD

**Issue by lordzsolt** [MicrosoftDocs/appcenter-docs#795]
Why does the person creating the team has to be part of the team? I want to set up various teams, such as Developers, QA, Design, PM, External Collaborators, etc. so I don't need to assign people to Apps one by one. But I cannot do it without being part of all those teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c96ab2f-7fca-bbcd-e159-3501f3ce1a4c
* Version Independent ID: 48e57a3d-d5c6-d4b3-380c-289095d5e933
* Content: [Creating and managing teams - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/creating-and-managing-teams#feedback)
* Content Source: [docs/dashboard/creating-and-managing-teams.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/creating-and-managing-teams.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by King-of-Spades** [comment]
I've moved your request to the microsoft/appcenter repository where feature requests are tracked: https://github.com/microsoft/appcenter/issues/1811
