### ISSUE TITLE
Question about part 3.b

### ISSUE THREAD

**Issue by chrismcx** [MicrosoftDocs/appcenter-docs#797]
Hi,
I've a question regarding section 3.b
Currently with HockeyApp, i'm uploading current IPA using curl -H "X-Hockeyapp-token:xxx" -F "status=2" -F "ipa=@myfile.ipa" https://rink.hockeyapp.net/api/2/apps/${appId}/app_versions/upload 

Should i use a https://api.appcenter.ms/v0.1/apps/ uri ? You've wrote rink.hockeyapp.net in your section.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Upload a Build to Distribute via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#feedback)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by pqtuan86** [comment]
Once you've done with step 3.a, get the upload_url from the response of this step, and use it for 3.b
You don't need to care about whether it is hockey or appcenter url, just use it within 24h. FYI, it's still hockeyapp url.

**Comment by ahdbilal** [comment]
Closing this as the doc has been updated to reflect the new url. Thanks
