### ISSUE TITLE
Guide for setting up Application Insights in custom export is inaccurate

### ISSUE THREAD

**Issue by SWATTeamMember** [MicrosoftDocs/appcenter-docs#799]
When creating the Application Insights it not possible to set Application Type to be App Center application type. After creation I cannot find anywhere to set Application Type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14a1fd-c1c2-f1a7-dd70-97c1200571f1
* Version Independent ID: f502c9bf-5593-1dd7-3551-6a7ca21f6f5c
* Content: [App Center Export - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/export#feedback)
* Content Source: [docs/analytics/export.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/export.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
