### ISSUE TITLE
Application is breaking after adding code push

### ISSUE THREAD

**Issue by patrickCode** [MicrosoftDocs/appcenter-docs#80]
After enabling code push in React Native, the application is crashing. While building I am getting the below error

ERROR in ./node_modules/react-native/Libraries/react-native/react-native-implementation.js
Module not found: Error: Can't resolve 'AccessibilityInfo' in 'C:\Github\React\Native\Basic_Controls\node_modules\react-native\Libraries\react-native'
 @ ./node_modules/react-native/Libraries/react-native/react-native-implementation.js 19:31-59
 @ ./node_modules/react-native-code-push/CodePush.js
 @ ./App.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.web.js

What is causing this issue? And how to resolve it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39490e39-be97-2bba-5afc-6bc8bed39690
* Version Independent ID: 357a2070-e41c-b346-e18b-606eec7255c2
* Content: [Using the React Native SDK with CodePush - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native)
* Content Source: [docs/distribution/codepush/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@patrickCode The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
