### ISSUE TITLE
Why Explain Without Explaining?

### ISSUE THREAD

**Issue by 6Hat** [MicrosoftDocs/appcenter-docs#804]
In section 2.3 You give very vague instructions on adding URL Types. If you are not going to fully explain it why bother writing the article? I have no idea what you are talking about!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d269a0-0b09-c2f6-d37a-319831bcf782
* Version Independent ID: f2c17a3a-87bb-0c75-9efb-de6ffb6f7738
* Content: [App Center Distribute for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#feedback)
* Content Source: [docs/sdk/distribute/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by fredrikhaglund** [comment]
The reason for step 2.3 is partly explained further down in section "How do in-app updates work?".

Might be good to explain that iOS requires that you registers a unique schema/protocol to enable information to be transferred from a browser to a specific app via navigation to an url?

**Comment by timeyoutakeit** [comment]
Hey @ahdbilal could you add some clarity to the relevant section? Thanks.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for mention it! We updated docs about it.
I’m closing this issue, but feel free to reopen this issue if it isn’t resolved or you have additional questions.
