### ISSUE TITLE
Customize Distribution Group Invitation?

### ISSUE THREAD

**Issue by dill0wn** [MicrosoftDocs/appcenter-docs#805]
Is it possible to customize the invitation message to distribution groups like it was in HockeyApp?

Related: Is is possible to omit the username from the main header message of the invitation email "$USER invited you to test $APP_NAME for Android on App Center" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a807b36-339c-dd76-a6bb-132005991516
* Version Independent ID: 8ffb33e3-09fd-fe41-742f-a9f4d11bf901
* Content: [Manage App Center Distribution Groups - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/groups)
* Content Source: [docs/distribution/groups.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/groups.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by dipree** [comment]
@dill0wn no, it's not possible. Please open a feature request in our public [GitHub repository](https://github.com/microsoft/appcenter/) so we can better track your request.
