### ISSUE TITLE
Define oversized crash report attachment error

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/appcenter-docs#806]
[Add attachments to a crash report](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin#add-attachments-to-a-crash-report) has this note about attachments:

> The size limit is currently 7 MB. Attempting to send a larger attachment will trigger an error.

What happens if the error occurs? Will it crash the app at startup as App Center is attempting to send the crash report? (That would be very bad.) Should the application code attempt to handle this error and how? Does `GetErrorAttachments` need to ensure it doesn't throw any exceptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a98dc868-6ec0-4d6e-652a-ed90d6c092b4
* Version Independent ID: d6061a26-6aef-be3a-c89a-3c8b290e2c9a
* Content: [App Center Crashes for Xamarin - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin)
* Content Source: [docs/sdk/crashes/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by breyed** [comment]
The documentation around the whole feature is sloppy. For example, the code for [AttachmentsWithCrashes](https://github.com/microsoft/appcenter-sdk-dotnet/blob/master/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.iOS/Crashes.cs) checks whether `GetErrorAttachments` returns null. Yet the IntelliSense for `GetErrorAttachments` just has this for the return value:

> The error attachments to be associated with report.

If null is allowed, the docs should say. Likewise, the behavior regarding exceptions should be clear. I would expect a crash reporting library to be very liberal in handling exceptions in any callback, but there may be other opinions. Whatever is decided should be spelled out.

**Comment by timeyoutakeit** [comment]
Hey @winnie @ahdbilal, I'm not sure which of you this falls under, but it looks like some clarification is necessary here.

**Comment by winnie** [comment]
@breyed thanks for the feedback! If your attachment size is above 7 MB, an error message will print out in the device logs and App Center will discard the attachement from being sent. However the crash will still be reported. Hope that clarifies things a bit! I will submit a PR to make the docs more clear.
