### ISSUE TITLE
How to check push permission (React Native)

### ISSUE THREAD

**Issue by vinjegaard** [MicrosoftDocs/appcenter-docs#807]
It took me some time to understand that `const pushEnabled = await Push.isEnabled();` only checks if App Center Push is enabled or not and *not* if the user has allowed push notifications for the app or not. Is it possible to check if the user has allowed push for the app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb94e7c4-0cce-e560-e548-5e0a930a4f75
* Version Independent ID: 5cc41638-30ea-62d5-de78-cb7a69c3aec2
* Content: [App Center Push for React Native iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-ios)
* Content Source: [docs/sdk/push/react-native-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/react-native-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@vinjegaard I'm not aware of a way to do that via the SDK. That would be something you can do using the APIs provided by the device OS.

**Comment by dhei** [comment]
There is no way to do that via App Center SDK. You will need to use OS API from Android or iOS to check that.
