### ISSUE TITLE
Which version of appium is working with appcenter ?

### ISSUE THREAD

**Issue by tutkuayavefe** [MicrosoftDocs/appcenter-docs#809]
I am using appium for test automation. And I want to use appcenter. As I read document of Microsoft which is "https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium" , one of the item is **"Support for Appium version 1.11.0 only. This appium version requires the appium java client to be at least 6.0.0"** . Is it up-to-date information? Because now, I am using XCode version 10.3 and appium version is 1.12.1. That is the minimum version to support XCode 10.3 .  And now I am going to update my XCode to 11.2.1 and appium need to be updated to 1.15.1 . So what should I do to handle this issue?

**Comment by 509dave16** [comment]
@tutkuayavefe I am also curious as the article for appium usage  was from 02/12/2019, which was 8 months ago. Have there been any updates to the supported version of appium for AppCenter Test Cloud?
+1

**Comment by ahanag22** [comment]
Appium 1.11 is the highest supported version of Appium we have on the servers currently. There is a feature request on github that can be tracked from here: https://github.com/microsoft/appcenter/issues/1203. 

Our product team is already aware about this issue and they moved Appium up in the list of priorities during the last bug triage meeting considering the importance of this feature. However,  currently we don't have an ETA as to when that might be available.
