### ISSUE TITLE
Cannot change the owner of a distribution group on Hockey App

### ISSUE THREAD

**Issue by evgeniyd** [MicrosoftDocs/appcenter-docs#811]
Our Hockey App account has a Distribution Group (DG) that's owned by a member of an organization and added to an app owned by the organization. According to [this App Center Incompatibilities article](https://docs.microsoft.com/en-us/appcenter/transition/moving/incompatibilities#distribution-groups) this DG cannot be migrated unless the outlined migration steps are performed. 
The owner of the DG tried to do the steps, but this is where we stuck: 

> * In the first tab, Basic Data, at the bottom under Account select the new owner of the distribution group and Save.

The reason is there is no controls to change the owner:

<img width="1068" alt="Screen_Shot_2019-11-11_at_2_30_50_PM" src="https://user-images.githubusercontent.com/5212518/68627584-f1ff5400-0492-11ea-83ff-5a47da74a030.png">

Please advise.

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
