### ISSUE TITLE
Unity WebGL

### ISSUE THREAD

**Issue by ChuckWalters** [MicrosoftDocs/appcenter-docs#813]
Is there a solution for Unity WebGL builds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0365781-58e5-a72a-9422-0ebd586877fe
* Version Independent ID: 5f7e41ef-448a-b27b-9041-bb38ff38ae16
* Content: [Get Started with Unity - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/unity#feedback)
* Content Source: [docs/sdk/getting-started/unity.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/unity.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by maestersid** [comment]
Hi @ChuckWalters not at this time no, our Unity support is mainly around Android/iOS scenarios, as well as UWP for what it supports.
