### ISSUE TITLE
Instructions are incomplete and console push message delivery is broken!

### ISSUE THREAD

**Issue by akaila** [MicrosoftDocs/appcenter-docs#815]
We need to fix few things in order for push to work here:

1. Fix react-native link step and mention that step here. This does all the necessary linking of native iOS and Android modules so the end developers can start importing and using JS/TS classes.

2. For manual integration (if above step is not done or enabled) it is necessary to modify Application class as follows:

```
import com.microsoft.appcenter.reactnative.push.AppCenterReactNativePushPackage;
```

and

```
@Override
        protected List<ReactPackage> getPackages() {
           // Other modules
           new AppCenterReactNativePushPackage(getApplication()),
       }
```

Otherwise things won't work.

**Note even with above steps in place, I could not use AppCenter console to send test message to my app within emulator. I was able to do the same from Firebase console directly. So something is broken in the console !**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7078a8ed-8f99-1544-8601-8c778fd2bbc1
* Version Independent ID: 9b1886d6-c9f8-e73b-e2b6-db6022f579ac
* Content: [App Center Push for React Native Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-android#feedback)
* Content Source: [docs/sdk/push/react-native-android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/react-native-android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by agnieszkabugla** [comment]
I have exactly the same problem. I can send push notifications from Firebase Cloud Messaging console, but not from AppCenter. Have you managed to fix the problem?

**Comment by akaila** [comment]
I decided not to use push notifications in the end. So not an issue now.

**Comment by timeyoutakeit** [comment]
Hey @ahdbilal, could you fix these steps? Thanks.

**Comment by ahdbilal** [comment]
closing this as this is no longer relevant
