### ISSUE TITLE
objective C code examples for starting the SDK

### ISSUE THREAD

**Issue by pjgrandinetti** [MicrosoftDocs/appcenter-docs#816]
There doesn't appear to be objective C code examples for starting the SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdaabafa-4dc0-7db9-cf7a-fafa24667c62
* Version Independent ID: b033ae6a-2ff6-59f6-7e0f-2d05f4a0ae34
* Content: [Get Started with macOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/macos#feedback)
* Content Source: [docs/sdk/getting-started/macos.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/macos.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by alamathe1** [comment]
@ahdbilal @timeyoutakeit Any ETA on this? Thanks.

**Comment by ahdbilal** [comment]
@alamathe1 you can review the sample project on our repo. here is the link: https://github.com/microsoft/appcenter-sdk-apple/tree/develop/SasquatchMac

**Comment by annakocheshkova** [comment]
@pjgrandinetti there's a switch at the top of the page.
![image](https://user-images.githubusercontent.com/34677812/79309896-b403d180-7f03-11ea-91cf-577ab9cd8636.png)
My apologies that it took so long to respond.
