### ISSUE TITLE
Error Uploading with Hockeyapp/Appcenter

### ISSUE THREAD

**Issue by grndvl1** [MicrosoftDocs/appcenter-docs#818]
Did not change a thing in my script understanding that it would not be an issue pointing to Hockeyapp.  Well it is.  gettint this error 

`{"errors":{"tags":["Tags are not supported in App Center, use distribution groups instead by specifying their names in the 'teams' parameter"]}}`  

Our CircleCI script uses tags to set the QA group and group ID
I know in the curl command we add this to it 

`            -F "tags=$TAGS" \
            -F "teams=$TEAMS"
`

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
