### ISSUE TITLE
How about VB winForms or WPF app?

### ISSUE THREAD

**Issue by AhmadKelany** [MicrosoftDocs/appcenter-docs#820]
There is no program.vb in visual basic app.. what should I do?

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For feature requests, use the [App Center public repo](https://github.com/Microsoft/appcenter/issues/new/choose).

**Comment by AhmadKelany** [comment]
> Hello, this forum is only used for issues with the documentation. For feature requests, use the [App Center public repo](https://github.com/Microsoft/appcenter/issues/new/choose).

Hello,
I am not requesting a new feature,

I am just requesting the documentation of the use cases in VB along with C#..
