### ISSUE TITLE
WinForms .Net Framework VB.Net Issue

### ISSUE THREAD

**Issue by AhmadKelany** [MicrosoftDocs/appcenter-docs#821]
Hello,
I added the Appcenter.Start(..) method to the application_startup event of the ApplicationEvents module,
and I got the  "App Center SDK configured successfully" confirmation in the console, but still no data is shown an analytics nor logs nor anything, the device is online..

What am I doing wrong? How can I get the data to show?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2add0f-2806-8bfa-92d5-cc3fdd1e1055
* Version Independent ID: c572b535-a780-fba3-0845-f5127d98d7d6
* Content: [UWP SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/uwp)
* Content Source: [docs/sdk/troubleshooting/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
