### ISSUE TITLE
Github Android sample app url leads to a 404

### ISSUE THREAD

**Issue by julien-conan** [MicrosoftDocs/appcenter-docs#823]
"2. Access the sample app's GitHub repository."

Url update proposition : https://github.com/microsoft/appcenter-sampleapp-android

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd0fc568-48f7-a1a0-f0a8-fb72d931d071
* Version Independent ID: bf93c8d7-7344-cc55-35b1-7b8ab740328a
* Content: [Getting Started - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/quickstarts/android/getting-started#feedback)
* Content Source: [docs/quickstarts/android/getting-started.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/quickstarts/android/getting-started.md)
* Service: **vs-appcenter**
* GitHub Login: @sshibu
* Microsoft Alias: **t-shshib**

**Comment by MatkovIvan** [comment]
It looks like app-secret value is incorrect, please follow our [Getting Started](https://docs.microsoft.com/en-us/appcenter/quickstarts/android/getting-started#replace-the-app-secret) doc
