### ISSUE TITLE
Why do I need to manually upload provisioning profiles with a connected store / apple developer account?

### ISSUE THREAD

**Issue by hanshamm** [MicrosoftDocs/appcenter-docs#824]
Manual upload of Provisioning Profiles should not be necessary.

I can already use resign and automatic manage my devices in other locations. Why do I have to upload manually provisioning profiles. I would assume that the system should be able to get all profiles from apple portal. Certificates makes sense, but profiles is a thing you want to automate. Through XCode you can download all necessary profiles (team provisioning, dev, adhoc..)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01f1809-2316-7d47-1547-23775f6dd618
* Version Independent ID: 7d719380-4d1d-e995-e0e5-b2474ae5e9af
* Content: [iOS Code Signing in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/code-signing#feedback)
* Content Source: [docs/build/ios/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/code-signing.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by nilofer** [comment]
Hi @hanshamm, issues and comments on our docs are for specific clarifications on things in the docs. Today, we don't connect directly to your Apple Developer Account for building in App Center. That connection is only used in resigning your app when it is distributed. To create a feature request for this, please open an issue in our [main repo](https://github.com/microsoft/appcenter/issues).
