### ISSUE TITLE
Table of Contents order is off

### ISSUE THREAD

**Issue by jhornick-ms** [MicrosoftDocs/appcenter-docs#825]
The "Introduction" page ends with a sentence saying the reader should first read the Core Concepts page, before getting started.  But the ToC lists the Getting Started page before the Core Concepts page.  We should swap the order of those two pages in the ToC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b34a665-39c4-e724-115c-489617a84cf7
* Version Independent ID: 9911c56b-792f-5fed-cd2b-7147647fee16
* Content: [App Center Test Core Concepts - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/core-concepts#feedback)
* Content Source: [docs/test-cloud/core-concepts.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/core-concepts.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by glennwester** [comment]
Thanks for making us aware! @Oddj0b for triage.
