### ISSUE TITLE
Objective C examples

### ISSUE THREAD

**Issue by keithburgoyne** [MicrosoftDocs/appcenter-docs#826]
Hi there,

Seems the example code in this documentation is largely in Swift, though there are scattered bits of Objective-C throughout. Would you be able to flesh out your Objective-C example code? It would be incredibly useful.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df91a5b-58a1-d91a-0aac-8866357f8bdf
* Version Independent ID: c7baedc0-0e95-80b5-d851-bb209adadd0a
* Content: [App Center Crashes for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#feedback)
* Content Source: [docs/sdk/crashes/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @WinnieLi
* Microsoft Alias: **yuli1**

**Comment by annakocheshkova** [comment]
Hi @keithburgoyne , there's a switch at the top of the page:
![image](https://user-images.githubusercontent.com/34677812/79311445-1a89ef00-7f06-11ea-8e72-3e14576a3a9a.png)
Apologies that it took so long to respond.
