### ISSUE TITLE
Broken Install

### ISSUE THREAD

**Issue by dmcgill50** [MicrosoftDocs/appcenter-docs#827]
Davids-MacBook-Air:~ dave$ npm install -g appcenter-cli
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@szmarczak%2fhttp-timer - User not found
npm ERR! 404
npm ERR! 404  '@szmarczak/http-timer@^1.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'got'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dave/.npm/_logs/2019-11-20T14_08_04_927Z-debug.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/index)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by timeyoutakeit** [comment]
Hi, this repo is only for issues with the documentation, rather than issues with the product. If you're experiencing issues with the product, please contact the [in-product support](https://intercom.help/appcenter/en/articles/1698824-getting-help-with-app-center) .
