### ISSUE TITLE
Apple account must have App Manager permissions to successfully publish builds

### ISSUE THREAD

**Issue by AntonPetrov83** [MicrosoftDocs/appcenter-docs#828]
Please see this issue of the fastlane: https://github.com/fastlane/fastlane/issues/14372
App Manager permissions are required to make this API call: https://developer.apple.com/documentation/appstoreconnectapi/modify_a_beta_app_review_detail
otherwise build publishing will fail.

Please mention this detail in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edcd9010-7381-ef0a-85ee-3289b742c8de
* Version Independent ID: 63c5a53d-e211-a17e-e0c0-27638748da7d
* Content: [Publish to App Store Connect - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple#feedback)
* Content Source: [docs/distribution/stores/apple.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/apple.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by MohamadMousheimish** [comment]
What's the fix for this issue?

**Comment by sangeetavishwanath** [comment]
Is there a resolution for this issue?

**Comment by renetik** [comment]
Any solution ?
