### ISSUE TITLE
Unclear message for a 401 response

### ISSUE THREAD

**Issue by srinivas3120** [MicrosoftDocs/appcenter-docs#829]
``POST https://api.appcenter.ms/v0.1/apps/srinivas3120/GitUserListMVVM/release_uploads``
``{
    "message": "9f51a3c4-d5ef-4258-a5ef-1bc475018289",
    "statusCode": 401,
    "code": "Unauthorized"
}``

It would be better to add a doc on how to read the message or a more meaningful message.

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
