### ISSUE TITLE
No page for WPF/WinForms

### ISSUE THREAD

**Issue by ranjan-2209** [MicrosoftDocs/appcenter-docs#831]
No page for WPF/WinForms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2add0f-2806-8bfa-92d5-cc3fdd1e1055
* Version Independent ID: c572b535-a780-fba3-0845-f5127d98d7d6
* Content: [UWP SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/uwp)
* Content Source: [docs/sdk/troubleshooting/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by timeyoutakeit** [comment]
We updated page title to reflect that this content is applicable to WPF and WinForms too
