### ISSUE TITLE
Appcenter test 30 days free trial

### ISSUE THREAD

**Issue by zank-stlab** [MicrosoftDocs/appcenter-docs#832]
Not sure if it's the right place but I didn't find the documentation very clear on that point:

If I start 30 days free trial for testing apps after the 30 days it'll automatically take money from the cart?
Or it ll ask if I want to keep use the service and pay for it?

In case it take money automatically where can I disable it?

Thanks

**Comment by ahanag22** [comment]
> If I start 30 days free trial for testing apps after the 30 days it'll automatically take money from the cart?

No, it won't take money automatically from the cart.

After the 30-day free trial the device test runs feature is disabled and you aren't automatically billed. The only way to reactivate the Test runs again is to start a subscription of our Test service.

Let me know if you have any additional questions.
