### ISSUE TITLE
Version Name

### ISSUE THREAD

**Issue by jkl334** [MicrosoftDocs/appcenter-docs#833]
For this particular part of the page: 
```
6. A new release of the app shows the in-app update dialog asking users to update your application if it has

a higher value of versionCode or
an equal value of versionCode but a higher value of versionName.
```

What does a higher value of a versionName mean. Since a versionName in android can be any string, I'm wondering how app center determines one version name is a higher value than another. Thanks in advance for the help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40294974-bc6b-45af-f1bd-3bd8187153ac
* Version Independent ID: 21420d35-1e72-a8b8-d587-40b2913120ba
* Content: [App Center Distribute for Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#feedback)
* Content Source: [docs/sdk/distribute/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/distribute/android.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jkl334** [comment]
bump

**Comment by ahdbilal** [comment]
Version name has to be different than previous. This has been changed in the document.
