### ISSUE TITLE
minimum IAM role needed to select a subscription in App Centre org

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/appcenter-docs#834]
what is the minimum IAM Role needed to view and select a subscription for billing against an app in app centre?
this should be outlined here as shops will have a governance element to consider for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1143ee54-3dad-1bbb-1b43-30dd4d6c3e6d
* Version Independent ID: c27a4b60-76ce-033a-0da1-87e5f9d14add
* Content: [Azure Subscriptions in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/azure-subscriptions)
* Content Source: [docs/general/azure-subscriptions.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/azure-subscriptions.md)
* Service: **vs-appcenter**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by bakerm00** [comment]
so will this get any traction?

**Comment by maestersid** [comment]
Hi @bakerm00 sorry for the delay in this response. You need to be a subscription owner to associate it with an App Center organization, as mentioned here in the doc: https://docs.microsoft.com/en-us/appcenter/general/azure-subscriptions#connecting-to-an-existing-azure-subscription
