### ISSUE TITLE
Attachments not available for handled errors

### ISSUE THREAD

**Issue by viktorszekeress** [MicrosoftDocs/appcenter-docs#835]
Documentation claims: "You can also optionally add one binary and one text attachment to a handled error report. Pass the attachments as an array of ErrorAttachmentLog objects as shown in the example below."
But there is no Crashes.TrackError(exception, attachments: attachments) overload for UWP, only Crashes.TrackError(exception, properties).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5756765e-fef2-e8d9-f8d9-5c01690095b8
* Version Independent ID: b474e30a-6e59-97fc-476a-92be5ec3a01a
* Content: [App Center Crashes for UWP - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp#feedback)
* Content Source: [docs/sdk/crashes/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by dhei** [comment]
Hi @viktorszekeress,

 `Crashes.TrackError(exception, attachments: attachments)` API is available on UWP since SDK v2.6.1 (https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.6.1).

Please check whether you are using a version no later than 2.6.1 to be able to use that API.
