### ISSUE TITLE
Reserved push notification custom data "badge" and "sound" not honored in Production

### ISSUE THREAD

**Issue by vkuttyp** [MicrosoftDocs/appcenter-docs#837]
I have successfully configured AppCenter push notification for my iOS app and it's working fine with sandbox.
Today uploaded the app to Appstore and opted for production on App center. Push notification is working fine. However, the custom data for badge and sound are not honored in the production version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c6b58f7-f9e7-7e79-1557-521fbc3c45e6
* Version Independent ID: 6888f550-74e2-1ef2-dc20-1dc3a0202330
* Content: [App Center Push for Cordova iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/cordova-ios#feedback)
* Content Source: [docs/sdk/push/cordova-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/cordova-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
