### ISSUE TITLE
Update for React Native v0.50+ codepush support

### ISSUE THREAD

**Issue by lxcid** [MicrosoftDocs/appcenter-docs#84]
Its been 4+ months since this document updated, I was wondering if I can use code push with React Native v0.53 at least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39490e39-be97-2bba-5afc-6bc8bed39690
* Version Independent ID: 357a2070-e41c-b346-e18b-606eec7255c2
* Content: [Using the React Native SDK with CodePush - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#feedback)
* Content Source: [docs/distribution/codepush/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/codepush/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **zakeelm**

**Comment by jwargo** [comment]
@lxcid I've asked the product's manager to respond to you. You should be OK, I used CodePush with the latest React Native a couple of weeks ago and it worked fine for me.

**Comment by lxcid** [comment]
Thanks for the reply! Thats good to hear! 👍

**Comment by Zakeelm** [comment]
Hey there @lxcid . I apologize for the confusion, the docs are definitely in need of an update. Thanks for pointing this out!  But, to answer your question, yes you can use CodePush with React Native v0.53 😊
