### ISSUE TITLE
No blue chat button, No Contact us in question mark menu

### ISSUE THREAD

**Issue by chao-master** [MicrosoftDocs/appcenter-docs#840]
Title is self explanatory,
I have also checked with my ad blocked disabled and the blue chat bubble doesn't appear
The "question mark" menu contains: System Status, Docs & APIs, Roadmap, Top feature requests, Submit feature request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dd71a0-a249-a87b-e4eb-e4da0a20472f
* Version Independent ID: 450c26f5-ab13-8df5-d45a-6086f5391b23
* Content: [App Center Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/support-center#feedback)
* Content Source: [docs/general/support-center.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/support-center.md)
* Service: **vs-appcenter**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by timeyoutakeit** [comment]
Hi @chao-master, it looks like there was a similar issue reported earlier on the [product support page](https://github.com/microsoft/appcenter/issues/1416). Can you try again and see if the issue has been resolved for you?

**Comment by chao-master** [comment]
I will have to check at work tomorrow
But even if the solution listed there still stands the second part of the issue
> No Contact us in question mark menu
> The "question mark" menu contains: System Status, Docs & APIs, Roadmap, Top feature requests, Submit feature request

Still applies
