### ISSUE TITLE
How do Apple ID and certificates work in relation to organizations?

### ISSUE THREAD

**Issue by JoeAlamo** [MicrosoftDocs/appcenter-docs#843]
Context: We have an organization in App Center, with all our apps belonging to the organization.

How can I add my Apple Id and certificate at an organization level so I am able to use them across our apps? or is that workflow not currently supported?

If it's not supported, what would be the alternative workflow?

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de79b71-e877-4882-9b78-bb4084afeed7
* Version Independent ID: 0991f861-34cc-2b8d-f155-8005bda5e2df
* Content: [Managing your Apple ID and certificates - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/manage-apple-secrets#feedback)
* Content Source: [docs/dashboard/manage-apple-secrets.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/manage-apple-secrets.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by Oddj0b** [comment]
Hi @JoeAlamo, I have a PR open to add the following paragraph. In other words, we don't support adding Apple IDs to organization because it is a personal identity.
```
## How can app members use my Apple ID

When you add an Apple ID to an app all other members will use it for App Store Connect communication and automatic device management. Because the Apple ID is a personal log it's only possible to add it to an app.
```
