### ISSUE TITLE
Enable caching of dependencies

### ISSUE THREAD

**Issue by externalshawnhong** [MicrosoftDocs/appcenter-docs#844]
I'm running a React Native iOS build. Our build times are taking much longer than we anticipated (&gt;30 minutes). The majority of the build time is taken up by the fresh installation of our pods and npm modules. When will caching be enabled as a feature? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bc0d05a-138a-1b77-3c1f-14f580063585
* Version Independent ID: 85e7e311-91af-7c45-8bbb-9fdc4a4eff74
* Content: [App Center Build Frequently Asked Questions - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/troubleshooting/general#feedback)
* Content Source: [docs/build/troubleshooting/general.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/troubleshooting/general.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajp**

**Comment by GrillAndChill** [comment]
@ranterle @DennisPan 

@patniko

**Comment by dennispan** [comment]
@externalshawnhong The feature request is tracked here: https://github.com/microsoft/appcenter/issues/473 . Unfortunately no update to share at the moment. 

I assume you are using the free plan? If you change to paid plan, each build extends timeout to 60 minutes.

**Comment by GrillAndChill** [comment]
@DennisPan it's not best to wait 60min to build and then repeat the entire process a couple of times if something breaks..

Do App Center team have this feature on their roadmap? Do you know when will it be added? This will block us from using the App Center.

**Comment by dennispan** [comment]
@GrillAndChill I understand. This isn't currently on our immediate roadmap.
