### ISSUE TITLE
Question:  AppCenter.start(..) needs be called from all entry activities?

### ISSUE THREAD

**Issue by ben-zhang-at-salesforce** [MicrosoftDocs/appcenter-docs#845]
Hi There:
     As you know android app has a main entry activity which is usually the home activity user see after clicking app icon.  AppCenter.start() will definitely be called on the activity onCreate method.  
    Beside home activity, app usually has some secondary entry activities(like deeplink activity - clicking a web link and app goes to a specific secondary activity) .  I believe AppCenter.start() needs be called in all entry activity.  Otherwise the crash in these secondary activity would NOT be tracked properly.  
    so AppCenter.start(..) needs be called in all entry activities? if so, please update the doc at 
https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android.

thx,
ben zhang

**Comment by timeyoutakeit** [comment]
Hey @ahdbilal can you confirm and update the docs if necessary? Thanks!

**Comment by annakocheshkova** [comment]
Hi, thanks for the mention. Yes, you need to start App Center in each of them. To avoid duplicate `start` calls, check if App Center is enabled before that. I will update the docs. You can also incapsulate the code in some class that will be called from any place where the app can be started.

**Comment by annakocheshkova** [comment]
If you don't have any more questions, I'm closing this issue. Thanks.
