### ISSUE TITLE
Android App Crash

### ISSUE THREAD

**Issue by nithinyell** [MicrosoftDocs/appcenter-docs#848]
App is getting crash, if I add
```
dependencies {
   def appCenterSdkVersion = '2.5.0'
   implementation "com.microsoft.appcenter:appcenter-distribute:${appCenterSdkVersion}"
}
```

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
