### ISSUE TITLE
Integrating AppCenter SDK in VB winForms. 

### ISSUE THREAD

**Issue by Adama-Doh** [MicrosoftDocs/appcenter-docs#850]
Hi,
I have been trying to integrate AppCenter sdk into my project(Vb winForms).

I've installed the AppCenter packages in my project but, I haven't been able to continue with the integration because I couldn't locate program.vb (the docs used program.cs instead). The official documentation page also doesn't show how to add the sdk in vb winForm.

**Tried adding the AppCenter(..) method to ApplicationEvent.vb Startup file but i got some errors.**
![image](https://user-images.githubusercontent.com/57943500/70052653-ab050a00-15cb-11ea-807d-22f1a46a7f1f.png)

What could i be doing wrong? 
Or probably i missed something out?
Kindly assist me

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
