### ISSUE TITLE
No internet access analytics event does not save

### ISSUE THREAD

**Issue by kingeaglewang** [MicrosoftDocs/appcenter-docs#851]
I just read the document as followed.

When there is no network connectivity, the SDK saves up to 10MB of logs in the local storage. Once the storage is full, the SDK will start discarding old logs to make room for the new logs. Once the device gets internet access back, the SDK will send logs in the batch of 50 or after every 3 seconds.

I do the experiment, I turn off the Internet, and run my app many times(about 5 times). After doing so, I turn on the Internet, and wait about one night, but no event was sent to the backend.
Then, I run my app with Internet, but I only got one event. Where are the above 5 events go?
It seems that it does not save in the local storage when there is no Internet.

Any idea about this problem?
Thanks for help.

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
