### ISSUE TITLE
Misleading Parts in "Delay push notification permission dialog"

### ISSUE THREAD

**Issue by fritzfr** [MicrosoftDocs/appcenter-docs#852]
In this section (https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-ios#delay-push-notification-permission-dialog), the following part is misleading:

> Once you get approval from the user to use Push at runtime, call Push.setEnabled(true).

This suggests that there is something you need to do to get approval, and **then** call `Push.setEnabled(true)`. However, it is this very call (`Push.setEnabled(true).`) which opens the Dialogbox and asks for this very approval.

So the following would be more accurate:

> When appropriate, call `Push.setEnabled(true)` at runtime to ask the user for approval to use Push.

Bonus points of you add a note that the dialogbox does not open on iOS simulator on macOS, and (I believe) only once in the lifetime of an App install on a physical device on iOS. Not sure about android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb94e7c4-0cce-e560-e548-5e0a930a4f75
* Version Independent ID: 5cc41638-30ea-62d5-de78-cb7a69c3aec2
* Content: [App Center Push for React Native iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-ios#feedback)
* Content Source: [docs/sdk/push/react-native-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/react-native-ios.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by dhei** [comment]
Hi @felix-voicehub,

Thanks for your feedback, that's a great point. 

> Once you get approval from the user to use Push at runtime, call Push.setEnabled(true).

This sentence is unclear about what does "approval from the user" actually means. The intention is to let the application have some custom UI (not provided by App Center SDK) to ask the user to opt-in for Push notification, then call `Push.setEnabled(true)` to enable Push notification.

> Bonus points of you add a note that the dialogbox does not open on iOS simulator on macOS, and (I believe) only once in the lifetime of an App install on a physical device on iOS. Not sure about android.

iOS Push notification only works on iOS physical device, not iOS simulators -- that is a limitation from Apple. Android Push has no such limitation and it works on Android emulators.
