### ISSUE TITLE
Receive notification data in background

### ISSUE THREAD

**Issue by ArgusMagnus** [MicrosoftDocs/appcenter-docs#855]
The documentation explicitly states, that the PushNotificationReceived event is fired only by clicking the notification when the app is in the background. Is there a way to receive the notification data in the app, even if the user does not click on the notification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65373652-7eda-af01-0f72-d01fcce4c131
* Version Independent ID: f85b66b3-ca30-bb5c-bfae-6425661d3365
* Content: [App Center Push for Xamarin.Forms Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms#feedback)
* Content Source: [docs/sdk/push/xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-forms.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by dhei** [comment]
The behavior is documented at https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms#subscribe-to-the-push-event.

> You can subscribe to the Push.PushNotificationReceived event to be notified whenever a push notification is received in the foreground or a background push notification has been clicked by the user.

> For all platforms, when the push is received in background, the event is not fired right away, the user will first see an Android system notification, an iOS alert, or a UWP toast.

> The event is fired only by clicking the notification in that case.

When the notification is received in the background, if the event is only fired when user clicks on it. If user never clicks on it, then the event is not triggered.
