### ISSUE TITLE
How to use RN Screens?

### ISSUE THREAD

**Issue by askpatrickw** [MicrosoftDocs/appcenter-docs#856]
This example works well if you want to use a redirect to the web for authentication and then back to the app. And that may be the norm if using B2C with a 3rd party authentication service (Google, Facebook, etc..). But this example does not show how to properly implement an ADB2C authentication scheme with the SignIn\SignUp\Profile\PasswordReset\ETC. screens implemented in ReactNative for apps which want to use Active Directory as the authentication service.

For comparison, checkout how easy it is to implement these functions in React Native with Expo and AWS Amplify.
Granted Expo is a bit of a closed eco-system, but this is the bar ADB2C needs to meet for RN auth.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 503d3676-f0a8-54a3-ff7a-649b85d84d1c
* Version Independent ID: 8bffba73-dc5a-475d-9c21-caf5c736ca2c
* Content: [App Center Auth for React Native - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/auth/react-native)
* Content Source: [docs/sdk/auth/react-native.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/auth/react-native.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **achew**

**Comment by reganlawton** [comment]
This is so my thinking this has been a totally pain to add to a React Native project as the scope of the docs is so limited with Appcenter Auth

**Comment by ElYusubov** [comment]
Do we have any timeline when we could expect requested feature/documentation?

**Comment by timeyoutakeit** [comment]
@ahdbilal @Zakeelm IS this something either of you have insight in to?

**Comment by askpatrickw** [comment]
App Center Auth is being deprecated for using Azure AD B2C directly, so this team is no longer the place to seek help.
https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/

The right place to focus attention is on the Azure AD group.
