### ISSUE TITLE
Upload iOS Symbolication from App Center build

### ISSUE THREAD

**Issue by cvo-4tell** [MicrosoftDocs/appcenter-docs#857]
Is it possible to upload iOS Symbolication from App Center build? It means that we don't need to download & upload the iOS Symbolication.

**Comment by elamalani** [comment]
@cvo-4tell Where do you want to upload the iOS symbol files? This link might be helpful - https://docs.microsoft.com/en-us/appcenter/build/ios/first-build#43-the-symbols-file-dsym

**Comment by King-of-Spades** [comment]
Closing due to the answer @elamalani provided (pointing to the doc) and lack of follow up response.
