### ISSUE TITLE
Swift example

### ISSUE THREAD

**Issue by yazoonic** [MicrosoftDocs/appcenter-docs#858]
can you add Swift examples here for create, read, replace. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5daee3ed-f796-73bd-af36-6deb5e33db9d
* Version Independent ID: 91af479e-8b3e-2395-c3f6-0bb0c108b61e
* Content: [Configuring App Center Data for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/data/ios)
* Content Source: [docs/sdk/data/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/data/ios.md)
* Service: **vs-appcenter**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by vineetchoudhary** [comment]
Hi @yazoonic , It's already there.
<img width="1106" alt="Screenshot 2019-12-18 at 10 31 13 AM" src="https://user-images.githubusercontent.com/8479436/71057164-c6524680-2181-11ea-83b9-6f4a0a7d864a.png">

**Comment by yazoonic** [comment]
Thank you.. is there any complete example for swift data. I am newbie to swift and I have this error 
Argument type 'User' does not conform to expected type 'MSSerializableDocument' 
Azure.ios provided complete docs on how to configure the class
