### ISSUE TITLE
No mention about SFSafariViewController or ASWebAuthenticationSession

### ISSUE THREAD

**Issue by olivereisenhut** [MicrosoftDocs/appcenter-docs#859]
On the whole document there is no mention of SFSafariViewController and
ASWebAuthenticationSession. I got no idea if those two classes are actually supported or not to query HTML content. Would be fantastic to have a feedback that those two classes are not supported or a link to the corresponding docs to get things clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58e1e042-6c42-460b-54a6-b5e7b7f80d94
* Version Independent ID: 75bc65d3-183b-457b-4bb6-913250a78140
* Content: [Working With - Web Views - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-webviews)
* Content Source: [docs/test-cloud/uitest/working-with-webviews.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/working-with-webviews.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by timeyoutakeit** [comment]
Hey @Oddj0b, would you be able to address this? Thanks.

**Comment by olivereisenhut** [comment]
Just wanted to mention here that we're not able to use those two browser abstractions for our UI tests. Therefore we inject a `WKWebView` as a workaround in our UI tests.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
