### ISSUE TITLE
Generic Git sources?

### ISSUE THREAD

**Issue by batjko** [MicrosoftDocs/appcenter-docs#86]
Any plans to allow integration from self-hosted or other Git source?
My company uses a self-hosted Gitlab instance which is not accessible from the outside, so we would only want to set up an outgoing webhook from our side.
Anyone can add a webhook to appcenter manually, if that's what is required, so I'm not quite clear why appcenter is not serving this very common use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12fa9a24-2575-3fa4-ffab-cafaeab496c1
* Version Independent ID: bbb99ead-eecc-222a-bc16-7509be5e8ec9
* Content: [Connect to a repository to start building your mobile app - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/connect)
* Content Source: [docs/build/connect.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/connect.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by jwargo** [comment]
@batjko I apologize for my late response, I was on vacation last week. The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
