### ISSUE TITLE
tes

### ISSUE THREAD

**Issue by kuyu007** [MicrosoftDocs/appcenter-docs#860]
tes

---
#### Detail Dokumen

⚠ *Jangan edit bagian ini. Diperlukan untuk masalah penautan docs.microsoft.com ➟ GitHub.*

* ID: 06813350-a37b-a4a2-fdbc-a59caefb9f32
* Version Independent ID: 29787958-5b4e-efc2-2af5-2af0ee53216e
* Content: [App Center Build - Visual Studio App Center](https://docs.microsoft.com/id-id/appcenter/build/)
* Content Source: [docs/build/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/index.md)
* Service: **vs-appcenter**
* GitHub Login: @siminapasat
* Microsoft Alias: **siminap**

**Comment by anywherepilot** [comment]
Hi @kuyu007. Did you have a question or comment?

**Comment by anywherepilot** [comment]
Closing this, looks like a mistake. Please reopen if you do have a question.
