### ISSUE TITLE
what if you have multiple organisations going to one Azure AD?

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/appcenter-docs#861]
what if you have multiple organisations going to one Azure AD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da9d9d48-17c2-f7a3-b4a9-55e6a37017eb
* Version Independent ID: eeaedcce-7367-619e-6c73-2814b727d83d
* Content: [Connecting App Center Organizations to Azure Active Directory - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/connecting-to-azure-active-directory)
* Content Source: [docs/general/connecting-to-azure-active-directory.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/connecting-to-azure-active-directory.md)
* Service: **vs-appcenter**
* GitHub Login: @ScottArbeit
* Microsoft Alias: **scarbeit**

**Comment by maestersid** [comment]
That is fine, you would just associate the same Azure subscription to each Organization. Should not be an issue.
