### ISSUE TITLE
what is the minimal permissions the Azure AD enterprise app is assigned?

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/appcenter-docs#862]
what is the minimal permissions the Azure AD enterprise app is assigned?
currently i have defined an iDP but the "app centre" app has no permissions assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da9d9d48-17c2-f7a3-b4a9-55e6a37017eb
* Version Independent ID: eeaedcce-7367-619e-6c73-2814b727d83d
* Content: [Connecting App Center Organizations to Azure Active Directory - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/connecting-to-azure-active-directory)
* Content Source: [docs/general/connecting-to-azure-active-directory.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/connecting-to-azure-active-directory.md)
* Service: **vs-appcenter**
* GitHub Login: @ScottArbeit
* Microsoft Alias: **scarbeit**

**Comment by maestersid** [comment]
Could you clarify what you mean by minimal permissions to the Azure AD Enterprise app?

**Comment by King-of-Spades** [comment]
closing due to more than a month of no response to @maestersid's question.
