### ISSUE TITLE
Cordova iOS push not working

### ISSUE THREAD

**Issue by jaguarg** [MicrosoftDocs/appcenter-docs#866]
Hi, 

I have followed the steps in the documentation and I can't get notifications to work. 
I can't find any error in my application log. 

Below you can find  an extract of what I can see in my application logs re: push . Also I have attached a screenshot of the appcenter push console when trying to send a push message.

`2019-12-18 10:35:32.863771+0100 MyAppName[1129:353692] [AppCenter] DEBUG: -[MSChannelUnitDefault sendLogContainer:withAuthTokenFromArray:atIndex:]/224 Sending 2/2 log, group Id: Push, batch Id: 7BEE9BAC-1B0F-4A29-81E7-8538AF4D6A7C, session Id: E1787737-20B6-4711-B7AF-F073EF579084, payload:
{
  "sid" : "E1787737-20B6-4711-B7AF-F073EF579084",
  "timestamp" : "2019-12-18T09:35:29.754Z",
  "device" : {
    "appVersion" : "1.0.90",
    "appBuild" : "1.0.90",
    "osName" : "iOS",
    "timeZoneOffset" : 60,
    "carrierCountry" : "fr",
    "wrapperSdkVersion" : "0.5.1",
    "osVersion" : "13.1.2",
    "wrapperSdkName" : "appcenter.cordova",
    "locale" : "fr_FR",
    "carrierName" : "SFR",
    "appNamespace" : "com.xxxxxxx.yyyy",
    "osBuild" : "17A860",
    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "sdkVersion" : "2.5.1",
    "model" : "iPhone8,1",
    "screenSize" : "1334x750"
  },
  "type" : "pushInstallation",
  "userId" : "yyyyyyyy@yyyyy.com",
  "pushToken" : "ff5bb352178dc9c9e9f5a69c29cea32dffafbcf27b2df38ba170c3bcaaa1c064"
}`
.... 

![Screenshot 2019-12-18 at 10 53 23](https://user-images.githubusercontent.com/8936602/71075786-f2bb9200-2184-11ea-9a20-9d520406a82b.png)

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
