### ISSUE TITLE
Xcode 11.x

### ISSUE THREAD

**Issue by mtannerfors** [MicrosoftDocs/appcenter-docs#867]
As of xcode 11 you should use the Apple Development Certificate, NOT the iOS App development certificate. You will receive build error [No signing certificate "iOS Development" found]. Make sure you set the xcode version to 11.x+ in the build settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01f1809-2316-7d47-1547-23775f6dd618
* Version Independent ID: 7d719380-4d1d-e995-e0e5-b2474ae5e9af
* Content: [iOS Code Signing in App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/ios/code-signing#feedback)
* Content Source: [docs/build/ios/code-signing.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/ios/code-signing.md)
* Service: **vs-appcenter**
* GitHub Login: @nrajpurkar
* Microsoft Alias: **nirajpur**

**Comment by timeyoutakeit** [comment]
Hey @elamalani, could you update this doc?

**Comment by King-of-Spades** [comment]
I was able to confirm this based on how the profiles are referenced in Xcode 11 itself. Addressing this in a pending update that will be published soon.
