### ISSUE TITLE
How far through the Apple process is automated here?

### ISSUE THREAD

**Issue by qhartman** [MicrosoftDocs/appcenter-docs#868]
What portion of the manual process does this integration cover? It seems like it would cover through the upload of the package, similar to what the Application Loader utility would do. Then we would need to do final submission, and then release to the store through Apple. Is that correct, or does it go further? The term "Published" is a little ambiguous here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a4d2d9-1a2d-add6-6100-67dbfefdee5e
* Version Independent ID: 9da7c8d6-b10f-d649-265f-5b10e999d4f2
* Content: [Publish an iOS package to the App Store (Production) - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple/app_store#feedback)
* Content Source: [docs/distribution/stores/apple/app_store.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/apple/app_store.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by timeyoutakeit** [comment]
Hey @ahdbilal, do you know the answer to this? Thanks!
