### ISSUE TITLE
Analytics : Event name property seems do not accept slash characters

### ISSUE THREAD

**Issue by carolelucas** [MicrosoftDocs/appcenter-docs#869]
Hello,
General event name : 18/12/2019 => OK
Detailled event name : api/route/someroute => **KO**
Detailled event property : 18/12/2019 : api/route/someroute => OK
The event appears correctly in the log flow but is not show in the event report.

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
