### ISSUE TITLE
How to add files as environmental variable 

### ISSUE THREAD

**Issue by akm0012** [MicrosoftDocs/appcenter-docs#873]
How can I add an environmental variable that is a file? 

I am working on an Android app and I want to be able to completely control the build process and not have App Center do it automatically. But in order to do that I need my keystore file to be able to live as an environmental variable.

**Comment by nilofer** [comment]
@akm0012 check out our doc on how to use [environment variables ](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/)in your build.

**Comment by akm0012** [comment]
@nilofer  That tells me how to use environment variables when they are Strings, Ints, Bools, etc. But is there not a way to store a file as an environment variable? I have a keystore file that I don't want to store in my repository.
