### ISSUE TITLE
Appium Python

### ISSUE THREAD

**Issue by gremito** [MicrosoftDocs/appcenter-docs#874]
I'm already using Appium and have Python test code.
Can Python (Appium) be used with Test Cloud?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed7c0d11-e60a-f088-e983-7465aca41515
* Version Independent ID: b2c6a308-1fcb-a385-239d-862b2c14114c
* Content: [Preparing Appium Tests for Upload - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/appium)
* Content Source: [docs/test-cloud/preparing-for-upload/appium.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/preparing-for-upload/appium.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by glennwester** [comment]
Hi @gremito, @Oddj0b would be happy to help with the above.

**Comment by King-of-Spades** [comment]
Currently we only support Appium Java tests as noted in the doc. 

You can file and vote on this or other feature requests here: https://github.com/Microsoft/appcenter/issues
