### ISSUE TITLE
appcenter login return error

### ISSUE THREAD

**Issue by cvo-4tell** [MicrosoftDocs/appcenter-docs#875]
appcenter login --token $APPCENTER_ACCESS_TOKEN

Error: can't login when token is set in environment variable APPCENTER_ACCESS_TOKEN
Error: Could not find a logged in profile, please note that this command is not compatible with the '--token' parameter or the token environment variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a947746f-ae22-69e1-83a5-b4c71e57faa9
* Version Independent ID: 1fe0b1a8-1562-3ec7-7973-ea76964e478e
* Content: [App Center Command Line Interface (CLI) - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/cli/)
* Content Source: [docs/cli/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/cli/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by duncwa** [comment]
This is the same error that I get when attempting to run the appcenter command in a Jenkins fastlane lane on a virtual mac machine.  Runs fine a bare metal.  1st Command in lane:  sh(`npm install -g appcenter-cli`),  2nd Command in lane: sh(`appcenter test run xcuitest --app "NameOfOrganization/NameOfApp" --device "NameOfOrganization/DeviceTestSetName" --test-series  "NameOfTestSeries" --locale "en_US" --build-dir DerivedData/Build/Products/Debug-iphoneos --token $appcenter_access_token`).  Error: You must logon to appcenter.   If I then try to insert the following command: sh(`appcenter login --token $appcenter_access_token`) between these two commands I get the browser pop up dialog in my Jenkins job and the VM shows the Safari browser window with a token.

**Comment by King-of-Spades** [comment]
Hi @duncwa, can you reach out to support like I mentioned in my last comment so they can investigate?
