### ISSUE TITLE
release upload via CURL API does not work

### ISSUE THREAD

**Issue by denisxaritonov** [MicrosoftDocs/appcenter-docs#876]
CURL:

curl -X POST \
    --header 'Content-Type: application/json' \
    --header 'Accept: application/json'\
    --header 'X-API-Token: &lt;my token&gt;'\
    -d "{\"release_id\": 8275,\
         \"build_version\": \"6.5.6\",\
         \"build_number\": \"8275\"\
        }"\
    'https://api.appcenter.ms/v0.1/apps/MyOrganization/MyAppName/release_uploads'

Response: 
{"code":"bad_request","message":"Error: Uploading to a HockeyApp store app is not supported."}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Distribute a build via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#feedback)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* GitHub Login: @botatoes
* Microsoft Alias: **bofu**

**Comment by RAM237** [comment]
Hi, just passing by...  
Faced this one myself last year, the reason is that your iOS app " Release Type" is set to Store (probably migrated from HockeyApp).  
To be able to upload releases to it in AppCenter, you will have to change it to something else (e.g. Enterprise) in app settings.

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
