### ISSUE TITLE
skynet

### ISSUE THREAD

**Issue by skynetrmz** [MicrosoftDocs/appcenter-docs#878]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba5bae42-8218-6f63-b28f-b6e6642f3ea2
* Version Independent ID: 1082232d-7609-692b-5d76-903a1134bf97
* Content: [Getting Started with App Center Test - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/getting-started)
* Content Source: [docs/test-cloud/getting-started.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/getting-started.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by King-of-Spades** [comment]
There's no description of the feedback, was this submitted by accident? Please feel free to reopen with more details if you have some feedback for the doc.
