### ISSUE TITLE
Cordova Build

### ISSUE THREAD

**Issue by VickyAbishek** [MicrosoftDocs/appcenter-docs#879]
Is the cordova build included in the current roadmap? When it will be available / Is it feasible?

**Comment by nilofer** [comment]
@VickyAbishek Build support for Cordova is not currently available. Please refer to our [non-docs repo](https://github.com/microsoft/appcenter/issues) for feature requests. The Cordova Build Support request can be found [here](https://github.com/microsoft/appcenter/issues/890).
