### ISSUE TITLE
How can I upload our provision and cert files via open api and what about secure problems?

### ISSUE THREAD

**Issue by yuenwinyun** [MicrosoftDocs/appcenter-docs#880]
Hi, according to API docs(/v0.1/apps/{owner_name}/{app_name}/branches/{branch}/config). We can upload our encoded provision and encoded cert file via API, but which format should I encode with? I also noticed that there are words like "secure file storage", how can I work with it? Will helpful if you can answer my questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/#feedback)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by yuenwinyun** [comment]
https://openapi.appcenter.ms/#/build/branchConfigurations_create

**Comment by msadeqshajary** [comment]
I have the same question. I follow [this ](https://intercom.help/appcenter/en/articles/1750391-build-api-how-to-upload-a-provisioning-profile-and-or-distribution-certificate-to-app-center-and-configure-a-branch-for-build-via-the-api) link as only guide in internet for this. But I got wrong password message. I think it's because I do not encrypt file before sending. Please help me about that.

**Comment by DmitriyKirakosyan** [comment]
Hi @msadeqshajary,

Thanks for reaching out!
It sounds like this issue for technical support, but this repository isn't monitored by our support team.
If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by yuenwinyun** [comment]
hi @msadeqshajary `base64` is a workable format

**Comment by msadeqshajary** [comment]
hi @yuenwinyun thanks for your response. But sorry. I try that but I still have the same error message. I think I have a problem in my code. Could you please share a simple example of upload process? Regards
