### ISSUE TITLE
Can't get App Center to see my tenant

### ISSUE THREAD

**Issue by Tiberriver256** [MicrosoftDocs/appcenter-docs#882]
It just says, "No tenants found". I've created a free subscription, associated that subscription with the app in app center, created the Azure AD B2C tenant and associated it with the subscription and App Center still can't find it.

Is there a timing thing to this? Like do I need to wait a couple of hours after creating a B2C tenant and associating it to the subscription before App Center picks up that it exists?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bac43716-ce54-d6bf-8a2a-0260a8b8f1d3
* Version Independent ID: 5f836302-e4f3-897a-c964-c3a60d39ff6b
* Content: [Getting started with the App Center Auth Service - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/auth/getting-started)
* Content Source: [docs/auth/getting-started.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/auth/getting-started.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by thekeviv** [comment]
I have been facing this issue from a week now and have had many conversations with support and they redirected me to the identity team to solve this but haven'r really gotten a solution for this. Even the data part doesn't work for me and it keeps logging me out, I am just getting so annoyed of app center that I am just going to use the azure sdk's until this product gets better, please fix this.....

**Comment by NCleverly** [comment]
I have had the same issue since the 6th and asked for updates twice no answer still.

**Comment by Tiberriver256** [comment]
Just discovered that "auth" + Azure AD is still a feature in the backlog:
https://github.com/microsoft/appcenter/issues/994

I would REALLY recommend hiding it in the App Center and your docs until it's finished. Although you do have it tagged as "preview" it still should be in some kind of working order before you display it to users. On top of that ghosting people with no response or apologies for someone accidentally displaying it, I personally feel is somewhat rude. Show a little respect for the time of other people.

**Comment by WolfyUK** [comment]
App Center Auth _could_ be configured for one of our apps towards the end of last year. Trying to configure this again in a new app against a different Azure subscription/tenant now fails with the error described above. The best we have got from the support team is:

> We're currently facing an issue with this, and unfortunately there's no ETA for the fix. If this is urgent, I'd highly recommend you using Azure AD B2C with the MSAL SDK directly.

When it was working, one of the 'features' of the Auth configuration was having to wait ~60 minutes after making a change for it to become effective. It is possible that some of the problems described above are due to timing issues?

**Comment by WolfyUK** [comment]
The answer may have just arrived: https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/

**Comment by Tiberriver256** [comment]
Haha thanks for that @WolfyUK. I'll take that as an answer. Still feel kinda shafted that no MSFT person ever stooped to give an answer on this thread but A+ to Microsoft for putting this stuff on Github so the community can be awesome.
