### ISSUE TITLE
Signing unclear

### ISSUE THREAD

**Issue by markusfassbender** [MicrosoftDocs/appcenter-docs#883]
I don't understand how signing is handled in the mentioned scenarios. Can there be issues, for example ad-hoc vs. app-store?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edcd9010-7381-ef0a-85ee-3289b742c8de
* Version Independent ID: 63c5a53d-e211-a17e-e0c0-27638748da7d
* Content: [Publish to App Store Connect - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple)
* Content Source: [docs/distribution/stores/apple.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/apple.md)
* Service: **vs-appcenter**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by timeyoutakeit** [comment]
@Oddj0b Is this something that you can add some clarity too? Thanks!

**Comment by Oddj0b** [comment]
You'll have to sign your app with an App Store provisioning profile and a distribution certificate.
