### ISSUE TITLE
Offline feature working in 'Aeroplane Mode' only

### ISSUE THREAD

**Issue by rajnikantpatel23** [MicrosoftDocs/appcenter-docs#885]
**Additional context**
The app is written using Xamarin Forms.
I am using App Center Auth+Data services in my Xamarin Forms Application. I have followed all the steps mentioned in the document. 
https://docs.microsoft.com/en-us/appcenter/sdk/auth/xamarin
https://docs.microsoft.com/en-us/appcenter/sdk/data/xamarin

**Describe the solution you'd like**
App is working fine in **online** mode. But for my App the **offline** feature is only working if my device is in **Aeroplane Mode** (no sim network + no wifi data). 
If I turn off the 'Aeroplane Mode' and my SIM network is available but internet is off then locally cached data is not visible in the device. 
Again If I will go to 'Aeroplane Mode' restart the App now locally cached data is visible for me.

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, please use the [in-product support channel](https://intercom.help/appcenter/).
