### ISSUE TITLE
build script for iOS/Android using powershell

### ISSUE THREAD

**Issue by radderz** [MicrosoftDocs/appcenter-docs#886]
Do the iOS and Android build hosts have powershell installed? We currenltly use an Azure DevOps pipeline rather than a app center pipeline, if we could do powershell we could move over to these tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca50588e-c8ad-2b8e-683f-bc5fc612dfe4
* Version Independent ID: 5d9513bd-d179-eaeb-96aa-06bd5ba0224f
* Content: [Build Scripts - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/index#feedback)
* Content Source: [docs/build/custom/scripts/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/scripts/index.md)
* Service: **vs-appcenter**
* GitHub Login: @King-of-Spades
* Microsoft Alias: **kegr**

**Comment by King-of-Spades** [comment]
It looks like it does, according to this doc: https://docs.microsoft.com/en-us/appcenter/build/software#language-and-runtime

Though I haven't personally tested it.
