### ISSUE TITLE
About alerting webhook API

### ISSUE THREAD

**Issue by yuenwinyun** [MicrosoftDocs/appcenter-docs#887]
Could /v0.1/apps/{owner_name}/{app_name}/webhooks support POST method? I'm writing scripts to interact with appcenter, and slack webhook can't be added by openapi, and this would be dirty if I create a lot of app and I should manually add webhooks to every single app.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/zh-cn/appcenter/api-docs/index)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For feature request, see the [App Center public repo](https://github.com/Microsoft/appcenter/issues/new/choose).
