### ISSUE TITLE
Can't See stack trace after uploading symbols with CLI for android

### ISSUE THREAD

**Issue by luciodondaGLBNT** [MicrosoftDocs/appcenter-docs#888]
I'm using this command:
`appcenter crashes upload-symbols -a Company_Name/APP-GO-1 --breakpad Tnt-Android-2249-symbols-PS.zip --debug`
Altough im receiveing a correct response:
```
\ Uploading symbols...Response status code: 200
Body: {"symbol_upload_id":"...-5169-1840-8d13-...","app_id":"...-032b-4166-8862-...","user":{"email":"sfsfs.sdfsdf@globant.com","display_name":"sfsfs.sdfsdf"},"status":"committed","symbol_type":"Breakpad","symbols_uploaded":[],"origin":"User","file_name":"upload-2020-01-15T21-20-30Z.zip","file_size":0,"timestamp":"2020-01-15T21:21:10.337Z"}
```
I'm still unable to see the correct stack trace on appCenter.

I didn't had any problem by doing this for the iOS version of the same app and uploading symbols by hand also works.

- Is there something we're doing wrong?

- Is there a way we can check what symbols are already uploaded?

- Every time we execute `appcenter crashes upload-symbols ...` it answers with "file_size":0, is this ok?

Thanks in Advance!

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, please use the [in-product support channel](https://intercom.help/appcenter/).
