### ISSUE TITLE
Crash data and statistics via API

### ISSUE THREAD

**Issue by BillyBunn** [MicrosoftDocs/appcenter-docs#889]
My team relies the metrics in our App Center dashboard, but we'd like to automate collecting this data with App Center's API. Specifically, there's no way to query the API for the crash data we need: "% of affected users" or "total crashes" (which appear as a graph in the dashboard).

How can we query for this data? Is there some simple math we need to do with the available routes or is there a simpler endpoint you could add? How is App Center calculating those numbers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b113ae49-c84f-05c6-e4fd-e414e5c64304
* Version Independent ID: a04ff30c-e14b-9b76-6dd3-223e05d3a8cb
* Content: [App Center API Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/api-docs/#feedback)
* Content Source: [docs/api-docs/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/api-docs/index.md)
* Service: **vs-appcenter**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by dipree** [comment]
@BillyBunn the docs feedback is only for improvements in the documentation itself. Please open a support ticket so we can look into your scenario and answer your question accordingly. If you think that outcome affects the documentation somehow, we can still improve it.
