### ISSUE TITLE
Need more information in purple sections

### ISSUE THREAD

**Issue by cihan-m** [MicrosoftDocs/appcenter-docs#890]
Specifically this phrase: "will not delete existing data associated with the app". How do we delete existing data associated with the app then? Thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67fac13b-a00b-2ac8-682c-66ea2b5841b9
* Version Independent ID: e11445ce-4afa-a87b-102b-97df2b868bc7
* Content: [How to stop collecting data - Visual Studio App Center](https://docs.microsoft.com/en-gb/appcenter/gdpr/how-to-stop-collecting-data#feedback)
* Content Source: [docs/gdpr/how-to-stop-collecting-data.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/how-to-stop-collecting-data.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @kpiteira
* Microsoft Alias: **kapiteir**

**Comment by cihan-m** [comment]
I kept reading, and in the Analytics section, I found a way to delete the user data, but it doesn't mention how to do a bulk delete for an entire app. How do we do that?

**Comment by dipree** [comment]
Thanks for your feedback. The section speaks about how to "stop collecting data", the sentence in the purple section is correct and sufficient for the purpose of this page.

The deletion of install id's is addressed in separate sections for each service, e.g. https://docs.microsoft.com/en-us/appcenter/gdpr/analytics-forget-me for analytics. There's currently no way to bulk delete all data with an install id from a service. However, you can automate this part via API if you'd like to or just delete the entire app. That said, the install id is not identifying individuals (users) unless you're tracking the complementary user id explicitly alongside with a mapping for the install id's.
