### ISSUE TITLE
Appcenter SDK unknowns

### ISSUE THREAD

**Issue by sreejithvijayan** [MicrosoftDocs/appcenter-docs#893]
There are still some unknowns in this SDK like the working of SDK methods like SetUserId, like how it behaves when multiple user ids are set from same device whether it will override? Also if same userid is being set from multiple devices, will the notification go to all devices?. Feels a need that these are common scenarios for any enterprise level implementation and needs to be documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb38f19-e7f0-8349-8731-e701745c644f
* Version Independent ID: d8928ac3-206c-e8f3-0124-364311e4e4d7
* Content: [App Center SDK Documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/)
* Content Source: [docs/sdk/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/index.md)
* Service: **vs-appcenter-sdk**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by olmisa** [comment]
Hello @sreejithvijayan ,
as I see, the method 'SetUserId' should override the previous 'UserId' value.
If we have the same 'UserId' on several devices then notifications which were sent to this 'UserId' will be sent to all devices.
Thanks.

**Comment by sreejithvijayan** [comment]
That clarification helps!!! Can this be part of the documentation?

**Comment by annakocheshkova** [comment]
Sure, I will add a note to the docs. Thank you.

**Comment by jwargo** [comment]
@sreejithvijayan the answer to your one question is provided here: https://devblogs.microsoft.com/appcenter/visual-studio-app-center-user-identity-shared-devices/
