### ISSUE TITLE
'AndroidAppConfigurator' does not contain a definition for 'AppBundle' and no accessible extension method 'AppBundle' accepting a first argument of type 'AndroidAppConfigurator' could be found

### ISSUE THREAD

**Issue by Cload** [MicrosoftDocs/appcenter-docs#894]
In one of the examples there is the following line:
app = ConfigureApp.Android.AppBundle("/path/to/application.apk").StartApp();
Should it be  app = ConfigureApp.Android.ApkFile("/path/to/application.apk").StartApp(); ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0474be-6e14-b8e6-b6cf-934a04f0e509
* Version Independent ID: 4a79fc1d-8dca-1c17-718f-c30fda180f05
* Content: [Xamarin.UITest - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/#feedback)
* Content Source: [docs/test-cloud/uitest/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by glennwester** [comment]
@Oddj0b for triage.

**Comment by timeyoutakeit** [comment]
@Oddj0b Could you please take a look at this and make the change, if necessary?

**Comment by Oddj0b** [comment]
You're correct @Cload, I just created a PR.
