### ISSUE TITLE
Can not figure how to add zip to minidump crashreport by rest api.

### ISSUE THREAD

**Issue by truefedex** [MicrosoftDocs/appcenter-docs#895]
Please, show example of how to add attachments to minidump crashreport (so it will have two attachments as result - minidump and zip for example). I trying to make this in two separate calls and api responds "status":"Success"? and http 200 code for both, but in appcenter web UI I see only minidump.

---
#### Відомості про документ

⚠ *Не змінюйте цей розділ. Він необхідний для зв’язування питань на платформах docs.microsoft.com ➟ GitHub.*

* ID: a69bd5cb-5747-8e88-ff48-c93e5d42ae51
* Version Independent ID: 014b77ea-32ca-ba1f-745b-33496d3f02d2
* Content: [Upload crashes via API - Visual Studio App Center](https://docs.microsoft.com/uk-ua/appcenter/diagnostics/upload-crashes#feedback)
* Content Source: [docs/diagnostics/upload-crashes.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/upload-crashes.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-diagnostics**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by dipree** [comment]
@truefedex please reach out via support (blue button in the bottom right corner of App Center) so we can better investigate your issue. The purpose of the comment system in the documentation is only for improvement suggestions.

**Comment by truefedex** [comment]
@derpixeldan this is my improvement suggestion: improve docs and add example of one important operation - adding logs to an existing error report in separate api call. Docs are currently missing this but there stated that it is possible:
https://docs.microsoft.com/uk-ua/appcenter/diagnostics/upload-crashes#upload-an-attachment
