### ISSUE TITLE
Change "--symbols" option to "--symbol" in documentation

### ISSUE THREAD

**Issue by raubrey2014** [MicrosoftDocs/appcenter-docs#896]
In the `ios-symbolication`documentation found [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#app-center-cli), the command to upload symbols via the appcenter cli reads:

```
appcenter crashes upload-symbols --symbols {symbol file}
```

That produces an error:
```
Error: Command 'crashes upload-symbols --symbols' failed with exception "Unknown argument --symbols"
```

The command succeeds however for option `--symbol` as illuminated by this error message when --app is specified with no further options:
```
Error: specify either '--symbol', '--breakpad', '--xcarchive' or '--appxsym' switch
```

Appcenter cli version 2.3.3. Otherwise, great docs!

**Comment by timeyoutakeit** [comment]
Thanks for filing this @raubrey2014. I've sent the fix to the author and the doc should be updated soon.
