### ISSUE TITLE
Backend?

### ISSUE THREAD

**Issue by henrikweimenhog** [MicrosoftDocs/appcenter-docs#90]
First of all, very nice docs right here. It only leaves one question unanswered: what about the backend? 
I am comparing to what we currently use: Azure Push notifications. There I get the abstraction to registrations instead of just devices and the collecting of device registrations and also sending to one specific registration or a group of registrations.
I suppose I am to do all this on my own when I use AppCenter Push, but it would be nice with a documentation piece describing how to either use Azure Push in conjunction with AppCenter or how to approach rolling my own.
Just saying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65373652-7eda-af01-0f72-d01fcce4c131
* Version Independent ID: f85b66b3-ca30-bb5c-bfae-6425661d3365
* Content: [App Center Push for Xamarin.Forms Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms)
* Content Source: [docs/sdk/push/xamarin-forms.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/xamarin-forms.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by dimazaid** [comment]
Thanks for the comment. We will be adding more about this in the future.
