### ISSUE TITLE
This page should mention, that feedback functionality from HockeyApp is no longer available

### ISSUE THREAD

**Issue by lostmsu** [MicrosoftDocs/appcenter-docs#905]
And link to possible solutions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c28f5aa-d967-3bf1-9c96-c254a8c988ed
* Version Independent ID: 16c32455-d651-2eeb-8773-bbbd82b01536
* Content: [Incompatibilities when moving apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/moving/incompatibilities#feedback)
* Content Source: [docs/transition/moving/incompatibilities.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/moving/incompatibilities.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-transition**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by timeyoutakeit** [comment]
Hey @dipree, is this something you can help address? Thanks!

**Comment by dipree** [comment]
@lostmsu thanks for the feedback. We're updating the documentation with regards to the HockeyApp transition as HockeyApp will be shut down on February 10th and this page won't be part of it any longer.
