### ISSUE TITLE
Please clarify, if this functionality is supported for desktop apps

### ISSUE THREAD

**Issue by lostmsu** [MicrosoftDocs/appcenter-docs#906]
Please, add the note, that this functionality is not available for desktop apps and/or UWP applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc4748f-3820-3b4d-b6d5-f0566063ce30
* Version Independent ID: 103d8b55-8719-dcaa-0670-d22e46e328cb
* Content: [Enable In-app Updates - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/inappupdates)
* Content Source: [docs/distribution/inappupdates.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/inappupdates.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @JoshuaWeber
* Microsoft Alias: **JoshuaWeber**

**Comment by timeyoutakeit** [comment]
Hey @ahdbilal, could you add a note on this to the doc? Thanks.

**Comment by ahdbilal** [comment]
Desktop apps are not support. The doc has been updated to answer this question.
