### ISSUE TITLE
Support chat not work

### ISSUE THREAD

**Issue by kinkard** [MicrosoftDocs/appcenter-docs#908]
Blue bubble chat in AppCenter not work:
![image](https://user-images.githubusercontent.com/10885920/73354686-5b7b4b80-42a7-11ea-9e27-3e51e0c7e8d0.png)

--
OS: Windows 10 Enterprise, version 1903, build 18362.592
Browser: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, please use the [in-product support channel](https://intercom.help/appcenter/).
