### ISSUE TITLE
Xamarin android constantly fails with error - jarsigner failed with return code: 1

### ISSUE THREAD

**Issue by ataparia** [MicrosoftDocs/appcenter-docs#913]
Hello All,
I have setup Xamarin Android app to be build on the app center but it constantly fails with the following message:
--------------------------------------------------------------------------------------------------------------
jarsigner: unable to sign jar: java.util.zip.ZipException: invalid entry compressed size (expected 35616 but got 36379 bytes)
##[error]Error: /usr/bin/jarsigner failed with return code: 1
##[error]Return code: 1
--------------------------------------------------------------------------------------------------------------

I have verified that the following information provided to build the app is correct.
a) Android Signing Store Pass
b) Android Signing Key Alias
c) Android Signing Key Pass
d) Android signing key store file.

Any help in this matter will be highly appreciated.

Thanks

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, please use the [in-product support channel](https://intercom.help/appcenter/).
