### ISSUE TITLE
Incorrect usage of notifyWithUserConfirmation

### ISSUE THREAD

**Issue by rgbworld** [MicrosoftDocs/appcenter-docs#916]
On macOS, UIAlertView does not exist (it is iOS only), so I am unable to implement 'alertView:clickedButtonAtIndex' as described. 

Rather than using 'setUserConfirmationHandler', I've  implemented 'hasCrashedInLastSession' where - when true, I display an NSAlert to ask the user for confirmation to send the crash report. Depending on the button pressed, I still call MSCrashes.notify(with: .send) as in the example code, however, when a test crash is created, the following error is reported:

[AppCenterCrashes] ERROR: -[MSCrashes notifyWithUserConfirmation:]/1222 Incorrect usage of notifyWithUserConfirmation: it should only be called from userConfirmationHandler. For more information refer to the documentation.

Please update the documentation to provide instructions on how to handle the button click in the NSAlert without the use of 'alertView:clickedButtonAtIndex'.

Currently the docs say "you would call it from within your implementation of the alertView:clickedButtonAtIndex:-callback" which AFAIK cannot be implemented on macOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f92c600-c347-1974-f52e-b8773e6b6056
* Version Independent ID: 6e30d595-f851-06d9-7454-05e5a77ddb0a
* Content: [App Center Crashes for macOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/macos#feedback)
* Content Source: [docs/sdk/crashes/macos.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/crashes/macos.md)
* Service: **vs-appcenter-sdk**
* GitHub Login: @WinnieLi
* Microsoft Alias: **yuli1**

**Comment by timeyoutakeit** [comment]
Hi @ahdbilal, would you be able to update the docs re. AlertView example?

**Comment by annakocheshkova** [comment]
Hi, the example we have in the docs is for `NSAlert` and it is correct. The words about `alertView:clickedButtonAtIndex` seem to be occasionally copied. I will update the docs.
