### ISSUE TITLE
Partner Center doesn't have option to download symbols as described in this doc

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/appcenter-docs#917]
The Manage package -&gt; Show packages -&gt; Show details doesn't have any options to download the symbols. Maybe something changed in Partner Center and the doc is outdated? I can't find anywhere in Partner Center to download symbols though...

![image](https://user-images.githubusercontent.com/13246069/74076587-b14da300-49cd-11ea-8804-dde54dd7cdce.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e433b8e-4a4b-97a9-b1be-b32130379785
* Version Independent ID: 9d76a644-9b5c-4e0b-3d21-787d742c6f1c
* Content: [Windows Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/windows-support)
* Content Source: [docs/diagnostics/windows-support.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/windows-support.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-diagnostics**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by timeyoutakeit** [comment]
Hey @winnie would you be able to update the doc if necessary? Thanks!

**Comment by winnie** [comment]
Hey @andrewleader! I'm not aware of any UI changes but will check with the team. Was this working for you before? Can you confirm you included symbol files in your submission? Thanks!

**Comment by andrewleader** [comment]
Yeah I've downloaded symbols from Partner Center before (back when it was still called the Windows Developer Center). The option just simply doesn't seem to exist anymore!

**Comment by winnie** [comment]
I see. I just messaged the Partner Center team. Will update here when I hear back. Thanks!

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by JoeTomkinson** [comment]
Was this resolved by support? Just stumbled across the same issue; no where to download the symbol files whilst following the documentation.

More than happy to follow up with the support team if this is not something you can advise on.
