### ISSUE TITLE
Confirm whether the crash upload api of Hockeyapp would remain functional?

### ISSUE THREAD

**Issue by Acker2015** [MicrosoftDocs/appcenter-docs#919]
For the old crash HockeyApp API endpoint: **https://rink.hockeyapp.net/api/2/apps/%s/crashes/upload**
I am not sure if this API has been used in Hockeyapp SDK. So I want to confirm whether this api endpoint would remain functional.

Thx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7efdb99a-c6d6-82e3-0223-81d7a9b9c99f
* Version Independent ID: be03985f-9afb-43f2-e486-7df19bee59a6
* Content: [HockeySDK for Android Migration - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/transition/android-sdk-migration)
* Content Source: [docs/transition/android-sdk-migration.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/transition/android-sdk-migration.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-transition**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
