### ISSUE TITLE
Additional problem - linking hockey app on iOS

### ISSUE THREAD

**Issue by vchelaru** [MicrosoftDocs/appcenter-docs#92]
If you have the hockey nuget packages linked in the same iOS project as App Center packages, the project will not build. The documentation says:

> Don't use any other library that provides Crash Reporting functionality

But I thought this meant to not initialize multiple error reporting systems. It wasn't clear to me that I couldn't even have the nuget packages as part of the project.

This should be added to this section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af635c53-8b58-a6c4-bd0f-cefb71bbfee4
* Version Independent ID: c388dd37-6b0c-47f0-b2a1-58590b3d3de5
* Content: [Xamarin SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/xamarin)
* Content Source: [docs/sdk/troubleshooting/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/xamarin.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@vchelaru As I understand it, crash libraries generally initialize automatically, so that's why we have that warning. Just having the packages in your app is enough to create the problem. @elamalani please correct me if I'm wrong.

**Comment by vchelaru** [comment]
I think the problem may stem from hockey app and app center core libs using the same class names. I don't think it's tied to automatic initialization because the error was compile time, not runtime.

**Comment by elamalani** [comment]
@vchelaru App Center and HockeyApp SDK both use **PLCrashReporter framework** for Crashes. That is why you can only include one SDK in your app to avoid any compilation errors.

I think the documentation mentions it clearly that "you can only have one crash reporting SDK integrated."

**Comment by vchelaru** [comment]
The documentaiotn does mention that having only one integrated, I'm arguing the clarity of the word "integrated" as that could be interpreted to mean "started" , but in this case it more broadly means added as a package.

To support my claim that this is not clear usage, the support person I spoke on the AppCenter chat told me that this is a very common issue that they have. Would be nice to help future users earlier by adding a sentence like (this includes adding nuget packages for other products like HockeyApp).
