### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by GaryMeyers1** [MicrosoftDocs/appcenter-docs#920]
The Devices and Simulators screen is different in Xcode 11. The Simulators screen has a "Show as run destination" that I was looking for more information on but it's not addressed here because you're using the old screenshot. I have unselected the checkbox in Xcode for the simulators that I don't want to see.  However, after exiting Visual Studio for Mac and Xcode and coming back in, the unselected simulators are still showing in the Visual Studio for Mac list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334914fb-9613-959d-c02a-a0fe90b8b8b3
* Version Independent ID: 96a4911a-3c11-66c3-2f9b-f52f4e07c874
* Content: [Working with iOS Simulators - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-ios-simulator?tabs=vsmac#feedback)
* Content Source: [docs/test-cloud/uitest/working-with-ios-simulator.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/working-with-ios-simulator.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by Oddj0b** [comment]
Hey @GaryMeyersMN There's not a lot I can do about Visual Studio for Mac besides redirecting them here. But I can and will update the Screenshots.
