### ISSUE TITLE
Request to clarify missing required app fields when publishing to Intune

### ISSUE THREAD

**Issue by MaxSteinMS** [MicrosoftDocs/appcenter-docs#922]
Hi there!

We've had a report that when publishing an .ipa via App Center or in using the AppCenterDistribute task, the "Properties" field of the app would not display within the Intune console (preventing editing of user assignments, app description, info url, etc.). However, when uploading the .ipa file manually to Intune and access the "Properties" tab just fine.

The report mentioned that they were able to get everything working by manually patching the app through the Intune Graph API (https://docs.microsoft.com/en-us/graph/api/intune-apps-ioslobapp-update?view=graph-rest-1.0) to add the required description field.

Adding relevant GitHub Feedback from the VSTS Docs: https://github.com/MicrosoftDocs/vsts-docs/issues/7217.

Requesting additional clarification or note indicating that specific fields are required when uploading to Intune (and how to specify them in App Center).

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c31b388-68fd-649d-eb12-37c94fa6793c
* Version Independent ID: a590f5fc-c426-ef66-a3c5-732928325347
* Content: [Publish applications to Intune Company Portal - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/intune#feedback)
* Content Source: [docs/distribution/stores/intune.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/intune.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by ajaykn** [comment]
@MaxSteinMS  Thanks for letting us know about this.
We have verified with our test app and not able to repro, as we are able to see the `Properties` tab in Intune console.

Do you see multiple customers reporting this ?
Can you please check with the customer to raise a ticket with us via our support channel by clicking on `Contact support` tab.
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/40024974/80818383-b1d29000-8bf0-11ea-8a04-f0dcbfa48bfd.png">

Please let us know if you need any more details on this. cc @Oddj0b

**Comment by Oddj0b** [comment]
Feel free to open if the problem persists as we couldn't reproduce.
