### ISSUE TITLE
DSYM file not symbolicating 

### ISSUE THREAD

**Issue by anchormansam** [MicrosoftDocs/appcenter-docs#923]
I cloned a project and have been trying to solve a missing symbols issue: 

Build is being done through Xcode v11.3.1. Ive downloaded the DSYM from Xcode via the Archive.  I have tried to up load the file via CLI/Drag and Drop to upload the file. When I view the error report they are not symbolicating. 

Any help?

OSX App

**Comment by timeyoutakeit** [comment]
Hello, this forum is only used for issues with the documentation. For product support, the quickest way to get help is to use the [in-product support channel](https://intercom.help/appcenter/).
