### ISSUE TITLE
add troubleshooting about sandbox is not in sync with the Podfile.lock

### ISSUE THREAD

**Issue by pablomaurer** [MicrosoftDocs/appcenter-docs#924]
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0624cb1d-70e5-dc2d-81e2-322c5cf30c24
* Version Independent ID: 0986d9e9-f5da-8a08-69a3-9013028481cd
* Content: [Cordova SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/cordova#feedback)
* Content Source: [docs/sdk/troubleshooting/cordova.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/cordova.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by annakocheshkova** [comment]
Hey, this issue can appear due to different reasons and has many ways to be resolved. They are not related to the SDK. 
If you have some troubleshooting steps _specific_ to our SDK, please share them.
If you have unknown issues configuring the SDK, please open a new issue in the cordova repository.

**Comment by annakocheshkova** [comment]
Hey, we haven't heard from you in a while - if you have any updates or new questions - please reopen the issue. Thanks!
