### ISSUE TITLE
How do you use the error feature

### ISSUE THREAD

**Issue by kericbowman** [MicrosoftDocs/appcenter-docs#925]
It would be nice if the page explained how to use the features or at least linked to an explanation of how to use them. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d3221f1-fd33-0f5b-5566-8af37bbe2244
* Version Independent ID: 6efcb61b-28bf-09bc-886d-c7a7188b91dc
* Content: [App Center Diagnostics - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/index#feedback)
* Content Source: [docs/diagnostics/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-diagnostics**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by timeyoutakeit** [comment]
we've added some links to the examples on this page
