### ISSUE TITLE
Exporting to AI

### ISSUE THREAD

**Issue by JohnLivermore** [MicrosoftDocs/appcenter-docs#926]
We have AppCenter analytics set up to export to Application Insights with an instrumentation key.  In AI we are seeing items created by Analytics.CreateEvent, but Crashes.TrackError does not export the exception to AI.  Is this expected behavior?  We were expecting both types to export.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d3221f1-fd33-0f5b-5566-8af37bbe2244
* Version Independent ID: 6efcb61b-28bf-09bc-886d-c7a7188b91dc
* Content: [App Center Diagnostics - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/#feedback)
* Content Source: [docs/diagnostics/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-diagnostics**
* GitHub Login: @winnieli1208
* Microsoft Alias: **yuli1**

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
