### ISSUE TITLE
Testflight

### ISSUE THREAD

**Issue by HenrikS123** [MicrosoftDocs/appcenter-docs#927]
I need access to Testflight on a Windows 10.
I was told "just get Itunes for windows" and run it from that.
I dont seem to be able to do that.
Do I need a IOS emulator ?
Do I need to install visual Studio too ?
I would appreciate any help
Thanks

**Comment by King-of-Spades** [comment]
This might be relevant: https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/testflight?tabs=windows#upload-your-app

I'm not seeing any details specific to App Center that would be relevant here; for example, App Center builds for iOS are executed on mac machines not Windows. 

It's not clear to me if what you're requesting is something we can address in documentation, or if you require technical support. If you still want help with this, please provide a few more details on what documentation change you want, or if you're wanting to connect with our support team.
