### ISSUE TITLE
Instructions for Jira integration return error "internal error" no further information

### ISSUE THREAD

**Issue by EDMIStephen** [MicrosoftDocs/appcenter-docs#928]
After following the instructions and using an API key for Jira integration the Authenticate with Jira window shows "internal error" there is no further information to help resolve the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99771c68-5f45-887a-e926-9ea772021f99
* Version Independent ID: 865109fc-64b8-ba77-2e10-8002886c46c7
* Content: [App Center bug tracker documentation - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/#feedback)
* Content Source: [docs/dashboard/bugtracker/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/dashboard/bugtracker/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @amchew
* Microsoft Alias: **amchew**

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
