### ISSUE TITLE
How is the app center api key being protected in compiled C# application

### ISSUE THREAD

**Issue by spotlesscoder** [MicrosoftDocs/appcenter-docs#930]
The documentation page says: https://docs.microsoft.com/en-us/appcenter/dashboard/creating-and-managing-apps

```
App secrets

App secret is like an api key for your app, it allows events and telemetry to be sent to App Center backend. It doesn't provide any access to your account. It can't be used to invoke App Center REST APIs (like trigger builds or send push notifications). If your code is open source, we recommend you inject the secret at build or in a similar way.
```

How is the APIKey protected after I compiled the application? Wouldn't it be readable when someone else decompiles the binary?

**Comment by King-of-Spades** [comment]
> How is the APIKey protected after I compiled the application? Wouldn't it be readable when someone else decompiles the binary?

I believe this would depend on your specific way of handling how you're distributing your app. For example, the Google Play & Apple stores encrypt your app, so it shouldn't normally be able to be decompiled in the same way. 

If you're distributing your app through a channel that doesn't encrypt for you, you may have to obfuscate your app secret or take other measures. 

But also, it's worth noting that if you're distributing your app in a way that can it can be decompiled, that might also imply other security risks as well.
