### ISSUE TITLE
Local Storage - No Internet

### ISSUE THREAD

**Issue by Sam-Hepworth** [MicrosoftDocs/appcenter-docs#931]
On this page it you write

"No internet access
When there is no network connectivity, the SDK saves up to 10MB of logs in the local storage. Once the storage is full, the SDK starts discarding old logs to make room for the new logs. Once network connectivity returns, the SDK sends logs in the batch of 50 or after every 3 seconds (by default)."

My question: If the local storage size is set to more than 10MB will this affect how much analytics data is stored locally if there is no internet connection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea43ae40-337d-83b4-8129-85ff1a8c6ede
* Version Independent ID: d37ccc38-a4bc-5368-9b58-8720995f8bc2
* Content: [App Center Analytics for iOS - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/ios#feedback)
* Content Source: [docs/sdk/analytics/ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/analytics/ios.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-analytics**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by timeyoutakeit** [comment]
@ahdbilal do you know the answer to this?

**Comment by annakocheshkova** [comment]
Yes @Sam-Hepworth, this is correct. `SetStorageSize` API is designed to increase this available storage size.
