### ISSUE TITLE
Cordova

### ISSUE THREAD

**Issue by RHinderiks** [MicrosoftDocs/appcenter-docs#935]
Is there a way for cordova apps to retrieve the install ID?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e72e2dd-365a-121b-2a0d-6d4e2f36ae3e
* Version Independent ID: ad0cfe49-17fa-77c7-149c-28d86ddf90eb
* Content: [Application Install ID - Visual Studio App Center](https://docs.microsoft.com/en-gb/appcenter/gdpr/install-id#feedback)
* Content Source: [docs/gdpr/install-id.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/gdpr/install-id.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by annakocheshkova** [comment]
Hi. No, this API is not yet available. Please follow the [feature request](https://github.com/microsoft/appcenter-sdk-cordova/issues/84).
