### ISSUE TITLE
Can you provide the api source code on the git hub ,like how did you communicate with the Azure notification hub from app center portal , It would help any one from not an API background like me to understand and implement the same ,just to continue the process of Push uninterrupted , as i am using it now on production app.

### ISSUE THREAD

**Issue by rockclane** [MicrosoftDocs/appcenter-docs#937]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 849cb3f8-82b9-0657-7b21-ab81214d8fbd
* Version Independent ID: 4a79c4db-6586-6770-c470-c8abfae29861
* Content: [Push Migration Guide - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/migration/push/#feedback)
* Content Source: [docs/migration/push/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/migration/push/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
@rockclane You cannot communicate with ANH from the App Center Portal. They're completely different systems (although App Center uses ANH under the covers). You'll have to switch to using both the ANH SDK (to register devices) and the ANH backend REST APIs to send notifications.
