### ISSUE TITLE
Can no longer upload with release notes

### ISSUE THREAD

**Issue by ajrodbf** [MicrosoftDocs/appcenter-docs#938]
On the `Distributing using the APIs` section, step 3.b, I used to be able to use `-F "notes=[release notes here]"` within the cURL command to upload a release with release notes. As of 2/18/2020, this field no longer works in populating the release notes. Unfortunately, there is no information in the Swagger UI for the API call within this step. How do I upload  a release with release notes using that same API call?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Distribute a build via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#distributing-using-the-apis)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @ahdbilal
* Microsoft Alias: **ahbilal**

**Comment by saritaNegi** [comment]
solution : Use 

curl -X PATCH "https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/releases/Release_Id" -H "accept: application/json" -H "Content-Type: application/json" -H "X-API-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -d "{ "distribution_group_name": "provide group name", "distribution_group_id": "provide group id", "release_notes": "your notes", "mandatory_update": true }"

**Comment by StingeyNinja** [comment]
Any chance of an example of how to upload release_notes in markdown format, when this endpoint requires JSON escaping?

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
