### ISSUE TITLE
Missing Distribution Group

### ISSUE THREAD

**Issue by hienhodeveloper** [MicrosoftDocs/appcenter-docs#939]
Hello. I have been invited to a team on AppCenter, but when I click on Distribution -> Group, I cannot see all the groups of project. I thought I must be invited into a group inside project too, but my leader said it needs not. Please help me!. Thanks

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
