### ISSUE TITLE
API Upload?

### ISSUE THREAD

**Issue by ad-mca-mk** [MicrosoftDocs/appcenter-docs#94]
We would like the symbols to be uploaded from our in-house build CI. How would we go about doing that?
We cannot go in for each build and upload it manually.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff6b815-a958-7ca3-d6fb-7ae7df5ecadd
* Version Independent ID: f2ad8149-0f9d-acc9-2098-da35d7a76ac7
* Content: [Crashes - Visual Studio App Center](https://docs.microsoft.com/en-gb/appcenter/quickstarts/ios/crashes)
* Content Source: [docs/quickstarts/ios/crashes.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/quickstarts/ios/crashes.md)
* Service: **vs-appcenter**
* GitHub Login: @conceptdev
* Microsoft Alias: **t-sajia**

**Comment by jwargo** [comment]
@ad-mca-mk The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
