### ISSUE TITLE
Issue in 4th point and release notes

### ISSUE THREAD

**Issue by saritaNegi** [MicrosoftDocs/appcenter-docs#940]
1.Not able to Distribute the uploaded release to  groups though we have given correct destination group Id and performed all 3 steps correctly (destination)
2. how to pass notes within the cURL command to upload a release with release notes(Release notes)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Distribute a build via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @ahdbilal
* Microsoft Alias: **ahbilal**

**Comment by saritaNegi** [comment]
Any Update

**Comment by ahdbilal** [comment]
@saritaNegi Have you recently started facing this issue? The best way to get support on this will be to open a support ticket directly from App Center. here is the link that explains how to do it: https://intercom.help/appcenter/en/articles/1698824-getting-help-with-app-center

**Comment by saritaNegi** [comment]
1.Not able to Distribute the uploaded release to groups though we have given correct destination group Id and performed all 3 steps correctly (destination)

My Solution on this :
Before distributing releases to groups please add one more command : 

curl -X PATCH "https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/releases/Release_Id" -H "accept: application/json" -H "Content-Type: application/json" -H "X-API-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -d "{ \"distribution_group_name\": \"provide group name\", \"distribution_group_id\": \"provide group id\", \"release_notes\": \"your notes\", \"mandatory_update\": true }"

above url will pass release notes and releases to  Groups

then perform below action as per the doc:

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-API-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' -d '{ "id": "10d82aa2-8449-499f-b6d3-44a855058eca", "mandatory_update": false, "notify_testers": false }' 'https://api.appcenter.ms/v0.1/apps/JoshuaWeber/APIExample/releases/2/groups'

**Comment by King-of-Spades** [comment]
Hi @saritaNegi, is your most recent comment a workaround for the issue, or a fix? If it's a workaround, it'd probably still be best to reach out to support so they can investigate and determine if the underlying cause was a bug. 

We've also recently updated our support interface, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.
