### ISSUE TITLE
Title of the page should change from "WindForms" to "WinForms"

### ISSUE THREAD

**Issue by ranjan-2209** [MicrosoftDocs/appcenter-docs#942]
Title of the page should change from "WindForms" to "WinForms"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2add0f-2806-8bfa-92d5-cc3fdd1e1055
* Version Independent ID: c572b535-a780-fba3-0845-f5127d98d7d6
* Content: [UWP, WPF, and WindForms SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/uwp#feedback)
* Content Source: [docs/sdk/troubleshooting/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/uwp.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by timeyoutakeit** [comment]
Oops, great catch!
