### ISSUE TITLE
Empty page

### ISSUE THREAD

**Issue by ranjan-2209** [MicrosoftDocs/appcenter-docs#944]
Empty page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64bf6eee-8421-34eb-a50e-78132fa8d45f
* Version Independent ID: 99cb3da9-7d74-8648-a438-de3849bd6a2c
* Content: [Unity SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/unity)
* Content Source: [docs/sdk/troubleshooting/unity.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/unity.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @jwhiteDev
* Microsoft Alias: **jawh**

**Comment by ranjan-2209** [comment]
@ahdbilal This is closed without reason
I am not able to re-open it.

**Comment by ahdbilal** [comment]
Opening it again. We currently have no troubleshooting steps for Unity. Are there certain steps that you will like to see? or what common issues are you running with Unity?

**Comment by ranjan-2209** [comment]
The same steps that are present for other platforms.

**Comment by MatkovIvan** [comment]
Fixed
