### ISSUE TITLE
`Unity` missing from dropdown

### ISSUE THREAD

**Issue by ranjan-2209** [MicrosoftDocs/appcenter-docs#945]
`Unity` missing from dropdown

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2add0f-2806-8bfa-92d5-cc3fdd1e1055
* Version Independent ID: c572b535-a780-fba3-0845-f5127d98d7d6
* Content: [UWP, WPF, and WinForms SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/uwp)
* Content Source: [docs/sdk/troubleshooting/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/uwp.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by ahdbilal** [comment]
Closing this issue as I do see Unity in the portal. Feel free to open the request if you still can't find the Unity Platform.

**Comment by ranjan-2209** [comment]
Its present now
![snapshot](https://user-images.githubusercontent.com/16834561/80176624-d6d66a00-8616-11ea-82bc-693de9af314f.png)
