### ISSUE TITLE
Need guidance on removing devices from Distribution Group

### ISSUE THREAD

**Issue by SPConrad** [MicrosoftDocs/appcenter-docs#949]
I've been unable to find a way to remove associated devices through the AppCenter menus and also don't see any documentation about it. This is making it impossible to use the automatic management and/or the automatic provisioning. 

I have n iPhones on the distribution group, but only n-5 remaining allocations for those types of devices. 

I can't remove any devices. 

If I try to use AppCenter's handy dandy auto-registration it fails due to insufficient open spots, and doesn't register any of them.

I got around this by creating a new distribution group with only myself in it, but eventually I'm going to need to add other people, and I don't want _every single device_ associated with them, we don't even support all of them.

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
