### ISSUE TITLE
can't use hockeyapp creds?

### ISSUE THREAD

**Issue by TeeBeeRS** [MicrosoftDocs/appcenter-docs#95]
Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b24e043-b73c-c05d-b101-56d2b89a3a7a
* Version Independent ID: 234e0be5-9c02-b8b4-7a5d-6032f5cba4e8
* Content: [App Center Test - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/)
* Content Source: [docs/test-cloud/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/index.md)
* Service: **vs-appcenter**
* GitHub Login: @glennwester
* Microsoft Alias: **glwest**

**Comment by jwargo** [comment]
@TeeBeeRS The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
