### ISSUE TITLE
When will we receive the Push Migration guide?

### ISSUE THREAD

**Issue by JonnySKK** [MicrosoftDocs/appcenter-docs#956]
> We’ll provide detailed instructions for how to streamline your app’s migration from App Center Push to Azure Notification Hubs

Is there a rough estimate as to when we will receive these instructions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 849cb3f8-82b9-0657-7b21-ab81214d8fbd
* Version Independent ID: 4a79c4db-6586-6770-c470-c8abfae29861
* Content: [Push Migration Guide - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/migration/push/#feedback)
* Content Source: [docs/migration/push/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/migration/push/index.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by jwargo** [comment]
We're working on a plan to make migration easier and I expect to have more details in mid April.  I really apologize for the delay, we're just trying to figure out the best thing to do here for our customers.

**Comment by Mike-Beers** [comment]
So you don't expect to have more details until less than a month before the App Center push service is discontinued?

**Comment by JonnySKK** [comment]
@Mike-Beers  

> Since App Center Push has more sophisticated backend requirements and more complex migration steps, Push will remain available longer to give customers additional time to complete their migration to a different service.

I think it's just Auth and Data which are being retired in May, it sounds like Push will be available a while longer to allow people time to migrate to Azure Notification Hubs

**Comment by Mike-Beers** [comment]
Thanks @JonnySKK

**Comment by jwargo** [comment]
@Mike-Beers @JonnySKK is correct, we've not announced the retirement date for Push yet - that will come soon along with the migration guide.

**Comment by joemather** [comment]
@jwargo -  Are you still expecting to release the push migration plan this month?  Or will it slip to May?  Thanks.

**Comment by jwargo** [comment]
@joemather last I heard it was pending. Should be April.

**Comment by amrutha786** [comment]
@jwargo - When can we expect the instructions for how to streamline our app’s migration from App Center Push to Azure Notification Hubs?

**Comment by tjsomasundaram-zz** [comment]
Hi

We are working on finalizing the migration guide. You should have instructions on moving from App Center Push to Azure Notification Hubs within a week. Thank you for your patience.

Thanks
Thejaswini (PM for Azure Notification Hubs )

**Comment by ricavir11** [comment]
Can you provide a timeline for end of App center Push notification service ?

**Comment by jwargo** [comment]
We will be announcing that date soon (very soon). You'll have months to complete your migration to another service.

**Comment by merzink** [comment]
Blogpost with additional App Center Push retirement details is now [published](https://devblogs.microsoft.com/appcenter/migrating-off-app-center-push/).

**Comment by rt-mobile-apps** [comment]
The blog talks about SDKs for iOS and Android. One of the great benefits of app center was the React Native SDKs, will any React Native SDKs be provided as well?

**Comment by tjsomasundaram-zz** [comment]
@rt-mobile-apps , at this point we do not have React Native SDKs for ANH. We definitely hear the feedback that the RN App Center SDKs were appreciated and will incorporate that into the ANH roadmap. If you wouldnt mind me asking, how big of a blocker is the lack of an RN SDK in your case?

**Comment by rt-mobile-apps** [comment]
> ...If you wouldnt mind me asking, how big of a blocker is the lack of an RN SDK in your case?

Big. Our app development strategy is based around "cross-platform development" with app center originally positioned as the core platform to enable features like notifications (and originally other features like auth and data that were retired as well).

Given the change in direction for app center and the fragmented approach from Microsoft for support of cross-platform frameworks we really need to ask ourselves if it makes sense to stick with app center / Microsoft or pivot to an offering like Amplify/AWS which has a far more clear, coherent and consistent approach.

Thanks for the reply.
