### ISSUE TITLE
Download latest artifacts from app center using API 

### ISSUE THREAD

**Issue by saritaNegi** [MicrosoftDocs/appcenter-docs#957]
How can we download latest artifacts from appcenter using API . 
we are creating a pipeline where we can automatically download artifacts and do testing
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ccb786-5f74-9c47-f6fa-a22720f823ad
* Version Independent ID: 3185af63-60df-aa2b-1d8c-b3db0ca3ad8c
* Content: [Distribute a build via App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/uploading)
* Content Source: [docs/distribution/uploading.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/uploading.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @ahdbilal
* Microsoft Alias: **ahbilal**

**Comment by ahdbilal** [comment]
I will revert you to this [document](https://openapi.appcenter.ms/#/) to help you with this task. You might want to specifically look into this API "/v0.1/sdk/apps/{app_secret}/releases/{release_hash}" (set release_hash = "latest'). We have couple of other APIs as well that can help in downloading the latest public or private releases.
