### ISSUE TITLE
Service Connection - Server URL

### ISSUE THREAD

**Issue by Krumiasty** [MicrosoftDocs/appcenter-docs#958]
Please add information that when creating service connection to App Center, the default Server URL needs to be: 
https://api.appcenter.ms/v0.1 (at least for distribution to App Center step)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28aa9747-f64a-d886-487d-8ebb97d717b8
* Version Independent ID: 0c7edbb7-4bf7-f66c-c8a7-275308365f27
* Content: [Deploy Azure DevOps Builds with App Center - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/vsts-deploy#feedback)
* Content Source: [docs/distribution/vsts-deploy.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/vsts-deploy.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by Oddj0b** [comment]
Thank you for your comment, I've added a PR that will go live at the latest tomorrow.
