### ISSUE TITLE
Default Env Vars

### ISSUE THREAD

**Issue by freever** [MicrosoftDocs/appcenter-docs#96]
Are there any environment variables created automatically by the build process? For example, I want to access the auto-incremented Build ID so that I can set the version code in my android app - is there any way I can access this value in a bash script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f3af3f-ef07-8896-4b3c-05cef163b51a
* Version Independent ID: b4b1f6a4-5975-358b-1cf4-f7b10a2245cd
* Content: [Environment Variables - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/)
* Content Source: [docs/build/custom/variables/index.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/custom/variables/index.md)
* Service: **mobile-center**
* GitHub Login: @derpixeldan
* Microsoft Alias: **daadam**

**Comment by dipree** [comment]
We don't create an environment variable for that but I'd like to understand what you need. Do you want to set your own offset for the "Build ID" option or are you looking for something more complex?

**Comment by freever** [comment]
Well, I'd like to create a bash script that automatically sets the version code and version names in my AndroidManifest.xml and Info.plist files based on a calculation that uses the Build ID. Using some other build servers I've been able to access the auto-incremented build number and do something like the following:

- set a current VERSIONBASE base eg "1.1."
- set a current build offset 
- calculate current minor version eg CURRENTMINOR = $BUILDNUMBER - $CURRENTOFFSET
- set the version in the manifests to $VERSIONBASE$CURRENTMINOR

So for eg when I version up to 1.1 at build 54, I set the CURRENTOFFSET to 54 and the VERSIONBASE to 1.1. Every build thereafter automatically increments the minor version to 1.1., 1.1.2 etc

I just find it very useful to auto-increment build numbers on the build server. Setting these things manually causes too much chaos :)

**Comment by jwargo** [comment]
@freever The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center] (https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by SABRYX** [comment]
> Well, I'd like to create a bash script that automatically sets the version code and version names in my AndroidManifest.xml and Info.plist files based on a calculation that uses the Build ID. Using some other build servers I've been able to access the auto-incremented build number and do something like the following:
> 
> * set a current VERSIONBASE base eg "1.1."
> * set a current build offset
> * calculate current minor version eg CURRENTMINOR = $BUILDNUMBER - $CURRENTOFFSET
> * set the version in the manifests to $VERSIONBASE$CURRENTMINOR
> 
> So for eg when I version up to 1.1 at build 54, I set the CURRENTOFFSET to 54 and the VERSIONBASE to 1.1. Every build thereafter automatically increments the minor version to 1.1., 1.1.2 etc
> 
> I just find it very useful to auto-increment build numbers on the build server. Setting these things manually causes too much chaos :)

Did you find anything on this ?

**Comment by saamerm** [comment]
I figured out to Automate Build numbering & App versioning for Android WITHOUT shell scripting while using Microsoft AppCenter CI/CD pipelines!
You can create environment variables and then use them in the build.gradle file like this:
```
versionCode System.getenv("VERSION_CODE") ? System.getenv("VERSION_CODE").toInteger() : 201
versionName System.getenv("VERSION_NAME") ? System.getenv("VERSION_NAME").toString() : "1.2.1"
```
[More details in this article](https://dev.to/saamerm/android-version-code-name-from-appcenter-environment-variables-2a3a)
