### ISSUE TITLE
Blue chat button visible on Mac but throws error message and disabled on Windows (Chrome browsers)

### ISSUE THREAD

**Issue by SaiNiranjan** [MicrosoftDocs/appcenter-docs#961]
I am using Mac Mini OS Catalina 10.15.3, Chrome Version 80.0.3987.149. When I sign into my microsoft account &gt; appcenter, I did find Blue chat button but every time I select it displays error "Something went wrong, we're unable to load the messenger, Try Again". I have been clicking on the button through out the day but same error. When I switch to Windows, open same version of Chrome &gt; log into appcenter &gt; There is no Blue chat button at all. Please help! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45dd71a0-a249-a87b-e4eb-e4da0a20472f
* Version Independent ID: 450c26f5-ab13-8df5-d45a-6086f5391b23
* Content: [App Center Support - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/general/support-center#feedback)
* Content Source: [docs/general/support-center.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/general/support-center.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-general**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by King-of-Spades** [comment]
Hi, we've updated our support ticket system; you can now find in the **App Center Portal > ? (help menu) > Contact Support**.
