### ISSUE TITLE
There Was a Problem Parsing the Package

### ISSUE THREAD

**Issue by genifycom** [MicrosoftDocs/appcenter-docs#963]
If the package is for a later Android version than the device on which it is being installed, please provide an appropriate message.

I created a package for API Level 28 (Android Pie) in Xamarin.Android.

Attempting to load this on Android 8.1 (Oreo) should not give the message "There Was a Problem Parsing the Package"!

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.
