### ISSUE TITLE
xcode 11.4

### ISSUE THREAD

**Issue by ergunkocak** [MicrosoftDocs/appcenter-docs#964]
When will the Xcode 11.4 (11E146) be available? Currently only beta can be selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 022126c7-2d61-9c53-6881-149310c137c0
* Version Independent ID: 4fe62fb4-6dd9-057e-8f57-fb4c6dcb71f8
* Content: [App Center Cloud Build Machines - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/build/software)
* Content Source: [docs/build/software.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/build/software.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-build**
* GitHub Login: @elamalani
* Microsoft Alias: **elamalani**

**Comment by ergunkocak** [comment]
🎉

**Comment by ergunkocak** [comment]
Actual link to supported software for the ones interested : https://docs.microsoft.com/en-us/appcenter/build/macos-10.15-software

**Comment by King-of-Spades** [comment]
Requests for adding features or updating tooling can be filed here: https://github.com/Microsoft/appcenter/issues
