### ISSUE TITLE
Has AppCenter SDK output changed?

### ISSUE THREAD

**Issue by MrXemiu** [MicrosoftDocs/appcenter-docs#965]
I'm having problems with App Center log output showing up in App Center, but I can see all the events, crashes, and handled exceptions I'm generating in my app output to the Debug Consoles as well as Android logCat.  I never see the message "App Center SDK configured successfully," but I do see "App Center initialized."  

The log output also shows logs successfully sent to App Center, as indicated by the HTTP 200 response that's logged immediately after the view of the JSON object that's sent.  If the SDK wasn't configured correctly, would it still log correctly and POST the logs to App Center?  If it is configured correctly but the sample output isn't shown, does that mean this documentation needs to be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af635c53-8b58-a6c4-bd0f-cefb71bbfee4
* Version Independent ID: c388dd37-6b0c-47f0-b2a1-58590b3d3de5
* Content: [Xamarin SDK Troubleshooting - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/xamarin#feedback)
* Content Source: [docs/sdk/troubleshooting/xamarin.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/troubleshooting/xamarin.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by annakocheshkova** [comment]
Hey @MrXemiu! No, we haven't changed anything related to that. Please tell me when have you stopped seeing this message (with what SDK version)? Could you include the sample of such logs?

Thanks.

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by MrXemiu** [comment]
I'll review logcat output tomorrow and verify whether I see "App Center SDK configured successfully," and let you guys know.
