### ISSUE TITLE
Finer granularity Analytics and Issues 'Time' filter

### ISSUE THREAD

**Issue by Thejacques1** [MicrosoftDocs/appcenter-docs#966]
The active users area in 'Analytics' is very useful. However, it's not very useful if you shipped several versions in a couple of days. Reason being the smallest period granularity is 7 days. It would be great to have 1 day and 1 hour as well.

Would be great if this applied to 'Issues' too.

Thanks

**Comment by King-of-Spades** [comment]
I'm migrating this to the App Center feature request repo along with a similar request: https://github.com/microsoft/appcenter/issues/795
