### ISSUE TITLE
In 2020, limiting to 20 properties and 125 characters per property is pretty pathetic

### ISSUE THREAD

**Issue by walteriousnut** [MicrosoftDocs/appcenter-docs#969]
"Limits
The maximum number of distinct custom events that can be tracked daily is 200. This count resets at 12 AM UTC. However, there is no limit on the maximum number of events instances sent per device.
The maximum number of event properties per event is 20. When more than 20 properties are sent, the first 20 properties are processed, and the rest are automatically dropped.
The SDK truncates event names to the first 256 characters.
The SDK truncates each property key and value to the first 125 characters.
The portal will show up the ten property values with highest count."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f69ecd-7f5b-570c-4777-c68acdacaf70
* Version Independent ID: 2987abb6-1dad-c456-827a-600952e416ee
* Content: [Understanding App Center Events Metrics - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/analytics/event-metrics#feedback)
* Content Source: [docs/analytics/event-metrics.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/analytics/event-metrics.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-analytics**
* GitHub Login: @blparr
* Microsoft Alias: **blparr**

**Comment by King-of-Spades** [comment]
Thanks for the feedback! Feature requests can be filed and upvoted here: https://github.com/Microsoft/appcenter/issues
