### ISSUE TITLE
Capacitor

### ISSUE THREAD

**Issue by miqmago** [MicrosoftDocs/appcenter-docs#970]
Are there any plans to support capacitor in any of appcenter functionalities?
At the end, capacitor is a native app with webview too, similar to cordova. Capacitor also offers cordova plugins compatibility.

**Comment by King-of-Spades** [comment]
@miqmago I found a related feature request here: 
> Capacitor Support for Code Push
https://github.com/microsoft/appcenter/issues/1245

Does that cover what you're looking for? If so, I recommend giving it a 👍, if not (and there aren't any other duplicates); then we should move this request over to that repository where it's more visible. 

It'd be good if you can also outline what specific support you want added in the same way as that issue. I'm not familiar with Capacitor personally, so I don't know which services it'd be applicable to.

**Comment by johnborges** [comment]
@miqmago A [Capacitor community plugin](https://github.com/capacitor-community/appcenter-sdk-capacitor) is for AppCenter is in the works with dev builds already being published.
