### ISSUE TITLE
Incorrect info about 'appLaunchTimestamp'

### ISSUE THREAD

**Issue by bramborman** [MicrosoftDocs/appcenter-docs#972]
The 'appLaunchTimestamp' value is marked as optional on this page but when I omit it in a request, I get a response code 400 Bad Request. Either the API is broken or this page has invalid info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a69bd5cb-5747-8e88-ff48-c93e5d42ae51
* Version Independent ID: 014b77ea-32ca-ba1f-745b-33496d3f02d2
* Content: [Upload crashes via API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes)
* Content Source: [docs/diagnostics/upload-crashes.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/upload-crashes.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-diagnostics**
* GitHub Login: @winnie
* Microsoft Alias: **yuli1**

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by bramborman** [comment]
Just to complete this thread, I've contacted the support and they said they'll update the documentation to reflect the real behavior which is that the `appLaunchTimestamp` is required.
