### ISSUE TITLE
Add link to AppCenter APK available from App Center itself to the testing android page

### ISSUE THREAD

**Issue by lacostej** [MicrosoftDocs/appcenter-docs#973]
As per microsoft/appcenter#1628, add the link to https://install.appcenter.ms/orgs/bitstadium/apps/app-center/distribution_groups/all-users-of-app-center to https://github.com/MicrosoftDocs/appcenter-docs/blob/ff10f3cfdf2176f6f1f3bc6e65f4684adf638a20/docs/distribution/testers/testing-android.md

**Comment by ahdbilal** [comment]
A PR has been sent with the requested update.

**Comment by lacostej** [comment]
This PR was closed and never merged: https://github.com/MicrosoftDocs/appcenter-docs/pull/1001. The issue remains. How do we move forward? @ahdbilal
