### ISSUE TITLE
Calabash required

### ISSUE THREAD

**Issue by jimicze** [MicrosoftDocs/appcenter-docs#975]
If the ios app coded in xcode, doesnt have calabash, this solution dont work. Calabash part is depreciated, so I dont know hot to run xcode ios app in simulator and test it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334914fb-9613-959d-c02a-a0fe90b8b8b3
* Version Independent ID: 96a4911a-3c11-66c3-2f9b-f52f4e07c874
* Content: [Working with iOS Simulators - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/working-with-ios-simulator?tabs=vsmac)
* Content Source: [docs/test-cloud/uitest/working-with-ios-simulator.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/test-cloud/uitest/working-with-ios-simulator.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-test**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by Oddj0b** [comment]
Should be explained here: https://docs.microsoft.com/en-gb/appcenter/test-cloud/uitest/get-started-with-ios-native
