### ISSUE TITLE
No possibility to add device

### ISSUE THREAD

**Issue by PerDFSjov** [MicrosoftDocs/appcenter-docs#979]
There is no possibility to add a new device. The 'Add device' button is not visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811f9eee-5b17-06e1-c108-dbef47984425
* Version Independent ID: 8fe50e13-c934-6a43-bf7d-1f33946da9d3
* Content: [Testing iOS Apps - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-ios#feedback)
* Content Source: [docs/distribution/testers/testing-ios.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/testers/testing-ios.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @Zakeelm
* Microsoft Alias: **Zakeelm**

**Comment by King-of-Spades** [comment]
Thanks for filing this report & sorry that you haven't heard back from us. It sounds like this issue for technical support, but this repository isn't monitored by our support team. 

If you need technical help, you can contact support by: 
1. Going to https://appcenter.ms/apps 
2. Selecting **? > Contact Support** (in the upper right corner). 
Reference this issue for context if needed.

If you've already resolved your issue/still want us to document this, give us an update of your current observations. We're catching up on our backlog here.

**Comment by BogdanRad** [comment]
I have same problem..

**Comment by King-of-Spades** [comment]
@BogdanRad have you reached out to App Center Support? If not, I recommend doing that.
