### ISSUE TITLE
appSecret best practice

### ISSUE THREAD

**Issue by snitkjaer** [MicrosoftDocs/appcenter-docs#980]
Is it a good idea to store the appSecret in code like in the example above? 

https://github.com/codepath/android_guides/wiki/Storing-Secret-Keys-in-Android

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa9700f5-b9e0-dfe1-ddbc-b5a3231dde11
* Version Independent ID: 11728c80-1474-c1dc-caf0-2c6b6c44bbb3
* Content: [Get Started with Android - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android)
* Content Source: [docs/sdk/getting-started/android.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/getting-started/android.md)
* Service: **vs-appcenter-sdk**
* Sub-service: **app-center-general**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by olmisa** [comment]
Hi @snitkjaer ,
As I understand, this is a normal situation to store 'app_secret' in a code. Looks like there is no way to be totally secure about 'app_secret' and it is just token.
For example, to be more secured, the 'app_secret' could be injected into code by a build system.
The way described here https://github.com/codepath/android_guides/wiki/Storing-Secret-Keys-in-Android also could be used.
Thanks.
