### ISSUE TITLE
'Threads' property not described

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/appcenter-docs#982]
It is shown in the examples but never mentioned otherwise. Is it optional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a69bd5cb-5747-8e88-ff48-c93e5d42ae51
* Version Independent ID: 014b77ea-32ca-ba1f-745b-33496d3f02d2
* Content: [Upload crashes via API - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes#upload-a-breakpad-crash-log-and-minidump)
* Content Source: [docs/diagnostics/upload-crashes.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/diagnostics/upload-crashes.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-diagnostics**
* GitHub Login: @winnie
* Microsoft Alias: **yuli1**

**Comment by winnie** [comment]
Hi @avakhrushev - 'Threads' are not a required property. This is an array of thread stack frames associated with the error. You can find a complete description or all our properties [here](https://in.appcenter.ms/preview/swagger.json). 

All required properties are listed in the "Log properties" list in the doc. Hope this helps!
