### ISSUE TITLE
There is no "Release management in the left-hand menu"

### ISSUE THREAD

**Issue by askpatrickw** [MicrosoftDocs/appcenter-docs#985]
App Signing is now  top-level menu item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868e3edf-f3af-950e-4f8a-ea30c392e883
* Version Independent ID: a725a1f2-fe7b-b7be-8e5e-6db22c2a756d
* Content: [Publish to Google Play Store - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay#feedback)
* Content Source: [docs/distribution/stores/googleplay.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/googleplay.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by King-of-Spades** [comment]
Looks like you're referring to this subsection? https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay#set-up-app-signing-by-google

**Comment by askpatrickw** [comment]
yep... that's the section.

**Comment by ahdbilal** [comment]
@askpatrickw I still see the "Release Management" option in the menu. You need to create/select your app to see that. 

<img width="1523" alt="Screen Shot 2020-04-23 at 5 03 31 PM" src="https://user-images.githubusercontent.com/55514721/80161226-8c0c1200-8584-11ea-8fdb-99dbdad064b3.png">

**Comment by askpatrickw** [comment]
Hmmm. I must have had it scrolled off or something. Sorry.
