### ISSUE TITLE
There are now 4 App Signing key management options

### ISSUE THREAD

**Issue by askpatrickw** [MicrosoftDocs/appcenter-docs#986]
```
You can choose between three options:

    Upload a key exported from Android Studio
    Export and upload a key from a Java keystore
    Export and upload a key (not using a Java keystore)
```

Is now incorrect.  There is now a 4th option "Let Google create and manage my app signing key (recommended)"

In this documentation it is unclear which is the correct option to choose or if all are acceptable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868e3edf-f3af-950e-4f8a-ea30c392e883
* Version Independent ID: a725a1f2-fe7b-b7be-8e5e-6db22c2a756d
* Content: [Publish to Google Play Store - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay#feedback)
* Content Source: [docs/distribution/stores/googleplay.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/stores/googleplay.md)
* Service: **vs-appcenter**
* Sub-service: **app-center-distribute**
* GitHub Login: @Oddj0b
* Microsoft Alias: **vigimm**

**Comment by askpatrickw** [comment]
The screenshot is wrong too.

**Comment by askpatrickw** [comment]
After mucking about with this for two days. I think the "happy path" (i.e., default recommendation) should be to use Google's app signing and then you need to also generate your own keystore to do the code signing. Annoying thing about that is the Android Studio steps in the link no longer match the Android Studio UI...

You can generate your own keystore using the CLI though:

`keytool -genkey -v -keystore release.keystore -alias yourkeystorename -keyalg RSA -keysize 2048 -validity 10000`

and use this config in AppCenter

<img width="517" alt="image" src="https://user-images.githubusercontent.com/4002194/79916251-44975180-83dd-11ea-87ba-ea69f7f344b1.png">

I am working from MacOS on this project. Those steps need to be verified on Windows\Linux.

**Comment by Oddj0b** [comment]
Thank you for your help. I have an open PR listing the fourth option with a link to Google's help page: https://support.google.com/googleplay/android-developer/answer/7384423
