### ISSUE TITLE
Unable to Distribute aab file

### ISSUE THREAD

**Issue by pranavi9** [MicrosoftDocs/appcenter-docs#993]
Hi,
We updated our code to generate AAB file instead of APK file for Android builds. I am unable to distribute AAB builds to QA teams, could you please guide me how can we follow the steps to install build from AAB file?

**Comment by ahdbilal** [comment]
@pranavi9 We currently don't support distribution of .aab files to test users. However, this feature is under consideration by our team. You can follow this feature request on https://github.com/microsoft/appcenter/issues/955.
