### ISSUE TITLE
App Center SDK + required Windows 10 versions

### ISSUE THREAD

**Issue by theothernt** [MicrosoftDocs/appcenter-docs#994]
As the newer App Center SDK 3.x for UWP requires a more recent version of Windows 10 (1803 I think?), it might be worth adding which versions of Windows 10 are required for 3.x and maybe 2.x if it's still supported?

**Comment by King-of-Spades** [comment]
@theothernt I'm not quite clear on what you're requesting...are you asking if the App Center team can update support for those versions, or are you asking if we can document the current support?

**Comment by theothernt** [comment]
Apologies for not being clear. I think documenting the currently supported versions in the docs would be a good idea (eg. 3.x requires Win10 1803 and above)

**Comment by King-of-Spades** [comment]
Thanks for confirming that! I'll pass it to our PM team so they can evaluate it during our upcoming Doc-a-thon.

**Comment by MatkovIvan** [comment]
@theothernt SDK 3.x supports 16299 or above. This is already documented here - https://docs.microsoft.com/en-us/appcenter/sdk/#windows-uwp

**Comment by theothernt** [comment]
@MatkovIvan thanks for that. I was also thinking it would make a good addition to https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/uwp#1-prerequisites (maybe a link?) as that is the page linked within some of the App Center web site.

**Comment by MatkovIvan** [comment]
@thambuzk yeah, I already did this a few hours ago, it should be published soon
